### PR TITLE
feat: [CI-6765]: Added inputV1 support for triggers

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Added inputV1 support for triggers
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5FZS5O0its2MKBks:-NMS5FZS5O0its2MKBkt:b-69imva) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java#L59)):*
> ```Java
>         inputPayloadNode = JsonPipelineUtils.readTree(inputPayload);
>       } else {
>         inputPayloadNode = YamlUtils.tryReadTree(inputPayload).getNode().getCurrJsonNode();
> ```

Why we are using one place yamlUtils and another as JsonPipelineUtils?



_Code quote:_
```Java
        inputPayloadNode = JsonPipelineUtils.readTree(inputPayload);
      } else {
        inputPayloadNode = YamlUtils.tryReadTree(inputPayload).getNode().getCurrJsonNode();
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5LfI1q5sGMCHAsy6:-NMS5LfI1q5sGMCHAsy7:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L94)):*
> ```Java
>           JsonPipelineUtils.jsonNodeToMap(JsonPipelineUtils.readTree(inputSet).get(YAMLFieldNameConstants.INPUTS));
>     } else {
>       inputSetMap = JsonPipelineUtils.jsonNodeToMap(
> ```

same as above

**Comment by raghavharness** [comment]
> > Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)_ status: 1 change requests. 0 of 1 approvals obtained.
> 
> _[`884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5FZS5O0its2MKBks:-NMS5FZS5O0its2MKBkt:b-69imva) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java#L59)):_
> 
> > ```java
> >         inputPayloadNode = JsonPipelineUtils.readTree(inputPayload);
> >       } else {
> >         inputPayloadNode = YamlUtils.tryReadTree(inputPayload).getNode().getCurrJsonNode();
> > ```
> 
> Why we are using one place yamlUtils and another as JsonPipelineUtils?
> 
> _Code quote:_
> 
> ```java
>         inputPayloadNode = JsonPipelineUtils.readTree(inputPayload);
>       } else {
>         inputPayloadNode = YamlUtils.tryReadTree(inputPayload).getNode().getCurrJsonNode();
> ```
> 
> _[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5LfI1q5sGMCHAsy6:-NMS5LfI1q5sGMCHAsy7:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L94)):_
> 
> > ```java
> >           JsonPipelineUtils.jsonNodeToMap(JsonPipelineUtils.readTree(inputSet).get(YAMLFieldNameConstants.INPUTS));
> >     } else {
> >       inputSetMap = JsonPipelineUtils.jsonNodeToMap(
> > ```
> 
> same as above

@archit-harness This is because runtimeInput can either be in json or yaml format. For manual executions we get the runtime input in json format now (for V1 pipeline) but for triggers since we just define inputSetRefs that gets resolved in BE, it's always yaml.

**Comment by raghavharness** [comment]
For manual execution the runtime input would be coming like this. Ref PR - https://github.com/harness/harness-core/pull/41540/files
`"{\"inputs\":{\"repo\":\"harness-core\",\"image\":\"nginx\",\"password\":\"dockerPass\",\"count\":5,\"version\":\"V1\"}}"`

For triggers, we don't take runtime input in payload but use inputSetRef instead which are in yaml format. For triggers case I had to parse the yaml inputSet to resolve the inputsFunctor For eg:
`version: 1
name: set2
inputs:
  image: alpine
repository:
  reference:
    type: branch
    value: main`

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5FZS5O0its2MKBks:-NMSEX4fCeUDibDRhZ1l:btgdyhe) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/884-pms-commons/src/main/java/io/harness/pms/yaml/RepositoryUtils.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we are using one place yamlUtils and another as JsonPipelineUtils?
</blockquote></details>

@hextechpal @brijeshdhakar why we have decision to take runtime input in run form as json and not yaml? is this some limitation of open API spec, as then customer using apis will now have to write both yaml and json.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5LfI1q5sGMCHAsy6:-NMSEk7Y32T-vjII0HmF:blixsgx) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L94)):*
<details><summary><i>Previously, raghavharness (Raghav) wrote…</i></summary><blockquote>

@archit-harness This is because runtimeInput can either be in json or yaml format. For manual executions we get the runtime input in json format now (for V1 pipeline) but for triggers since we just define inputSetRefs that gets resolved in BE, it's always yaml.
</blockquote></details>

As discussed offline, create v1 common utils in pms-commons having comments to explain example

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42888)* status: :shipit: complete! ✓

___
*[`pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/42888#-NMS5LfI1q5sGMCHAsy6:-NMbtsSY3ZoR9t_VMoMf:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3ba4b47fee2cd384d958ff1e09b55b5339496fca/pipeline-service/service/src/main/java/io/harness/pms/expressions/functors/InputsFunctor.java#L94)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

As discussed offline, create v1 common utils in pms-commons having comments to explain example
</blockquote></details>

done

**Pull request merged**
