### PR TITLE
[fix]: [DEL-4617]: use atmosphere native way of reconnecting to backend from delegate

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
Currently we do manual reconnection of websocket which leads to issues of having multiple websockets open which leads to other issues in stability. 
This change uses the native library's reconnect logic which adds to stability of the connection between delegates and manager. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36627)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 594 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6jHbHBXhLY_4ndeGh:-NA6jHbHBXhLY_4ndeGi:b7d5rvr) ([raw file](https://github.com/harness/harness-core/blob/3a63d2e922065a7fa569a35f5c5fa0220980810b/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L594)):*
> ```Java
>   }
> 
>   private Delegate buildDelegateFromParams(DelegateParams delegateParams, boolean isConnectedUsingMtls) {
> ```

if we making change here, then we need to verify flow of registration, HB on polling mode delegate also.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 81 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6jje7Bq0X_aCcor-V:-NA6jje8DJDGtl9g0qMk:b3e93jh) ([raw file](https://github.com/harness/harness-core/blob/615090b2934fc09cf127b2605ef4c4d938d55049/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L81)):*
> ```Java
>         List<String> pathSegments = SPLITTER.splitToList(req.getPathInfo());
>         accountId = pathSegments.get(1);
>         delegateId = req.getParameter("delegateId");
> ```

it will be useful to add warning log if delegate id is null since we occurrence , for both GET and POST

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 594 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6jHbHBXhLY_4ndeGh:-NA6k5rYAjFQj2Q77I19:b426mjo) ([raw file](https://github.com/harness/harness-core/blob/3a63d2e922065a7fa569a35f5c5fa0220980810b/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L594)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

if we making change here, then we need to verify flow of registration, HB on polling mode delegate also.
</blockquote></details>

Also test ECS delegate flow

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 602 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6l8_zB_8GtB0J4tzf:-NA6l8a-5CL4rksR4AVE:b5f3f8k) ([raw file](https://github.com/harness/harness-core/blob/615090b2934fc09cf127b2605ef4c4d938d55049/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L602)):*
> ```Java
>                                     .runtime(asyncHttpClient, true)
>                                     .reconnect(true)
>                                     .reconnectAttempts(Integer.MAX_VALUE)
> ```

why rationale  behind MAX value here?  why not make its as 1000 instead? Wondering any side effect.



_Code quote:_
```Java
.reconnectAttempts(
```

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)* status: 0 of 1 approvals obtained.

**Review by mdmilic — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)* status: :shipit: complete! ✓

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1716 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6uXz47K-9SOr9ZcY7:-NA6uXz47K-9SOr9ZcY8:b-18u2ps) ([raw file](https://github.com/harness/harness-core/blob/615090b2934fc09cf127b2605ef4c4d938d55049/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1716)):*
> ```Java
>                                                    .collect(toList()))
>               .location(Paths.get("").toAbsolutePath().toString())
>               .tokenName(DelegateAgentCommonVariables.getDelegateTokenName())
> ```

This looks to only ever be set by watcher, can't understand how it ever has a valid value. Also why do we even need to name a token.

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/36627#-NADKI-ND0x2nxPpFN7Q:-NADKI-Q6RwQ5069BOe6:b5mh9ko) ([raw file](https://github.com/harness/harness-core/blob/a26e52759c528674f59e0022731b3ed006745b55/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L132)):*
> ```Java
>       String accountId = pathSegments.get(1);
>       String delegateId = req.getParameter("delegateId");
>       String delegateConnectionId = req.getParameter("delegateConnectionId");
> ```

We are sending connectionId in delegate Params from delegate agent, will it be available in query string ?



_Code quote:_
```Java
 String delegateConnectionId = req.getParameter("delegateConnectionId");
```

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 602 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6l8_zB_8GtB0J4tzf:-NADZKCP5MguXpEr0V_B:bwb3t5h) ([raw file](https://github.com/harness/harness-core/blob/615090b2934fc09cf127b2605ef4c4d938d55049/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L602)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

why rationale  behind MAX value here?  why not make its as 1000 instead? Wondering any side effect.
</blockquote></details>

we need to keep trying to reconnect forever, there is no reason to stop.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1716 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6uXz47K-9SOr9ZcY7:-NADZbCx7XGcYodgLFx2:b-mm0w2y) ([raw file](https://github.com/harness/harness-core/blob/615090b2934fc09cf127b2605ef4c4d938d55049/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1716)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This looks to only ever be set by watcher, can't understand how it ever has a valid value. Also why do we even need to name a token.
</blockquote></details>

i was following to set it since its set for the URI, don't want to risk not setting it

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/36627#-NADKI-ND0x2nxPpFN7Q:-NADf5PWB9ecfkIicIR3:bkvy0wk) ([raw file](https://github.com/harness/harness-core/blob/a26e52759c528674f59e0022731b3ed006745b55/400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java#L132)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We are sending connectionId in delegate Params from delegate agent, will it be available in query string ?
</blockquote></details>

discussed offiline

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 594 at r2](https://reviewable.io/reviews/harness/harness-core/36627#-NA6jHbHBXhLY_4ndeGh:-NADf7lQ0wpXjPc0IK_1:b-msxvoh) ([raw file](https://github.com/harness/harness-core/blob/3a63d2e922065a7fa569a35f5c5fa0220980810b/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L594)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Also test ECS delegate flow
</blockquote></details>

yes, cc @bharatgoelharness

**Comment by raghuAtWings** [comment]
trigger ti3

**Comment by raghuAtWings** [comment]
trigger ft1

**Comment by raghuAtWings** [comment]
trigger ft1

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)* status: 1 change requests. 1. unresolved discussions.

**Comment by raghuAtWings** [comment]
trigger codebasehash

**Review by puneetsar — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36627)* status: 1 change requests. 1. unresolved discussions.

**Pull request merged**
