### PR TITLE
[fix]: [CDS-35339]: added null check and instance check

### PR DESCRIPTION
**Pull request by prabu-kr**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31633)

### CODE REVIEW

**Review by poojaSinghal — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31633)* status: :shipit: complete! ✓

**Comment by prabu-kr** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31633)* status: 2 file(s) to review. 

___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 2090 at r2](https://reviewable.io/reviews/harness/harness-core/31633#-MymXn3FDjjAe1AI3P4c:-MymXn3FDjjAe1AI3P4d:bjd9qwz) ([raw file](https://github.com/harness/harness-core/blob/9e9740b620d7869ddf11d07506b389a10d326dea/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L2090)):*
> ```Java
>         Map<String, Object> properties = stageElement.getProperties();
>         properties.forEach((name, value) -> {
>           if (USER_GROUPS.equals(name) && value instanceof List && isNotEmpty((List<String>) value)) {
> ```

`isNotEmpty((List<String>) value` can it lead to CLassCAst

**Review by prabu-kr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31633)* status: 2 file(s) to review. 

___
*[400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, line 2090 at r2](https://reviewable.io/reviews/harness/harness-core/31633#-MymXn3FDjjAe1AI3P4c:-MymeYzf1s92DWc3Dum7:b-9ap29r) ([raw file](https://github.com/harness/harness-core/blob/9e9740b620d7869ddf11d07506b389a10d326dea/400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java#L2090)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

`isNotEmpty((List<String>) value` can it lead to CLassCAst 
</blockquote></details>

Shouldn't lead to. value can only be List<String> or null. We're doing instanceOf check before too

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31633)* status: :shipit: complete! ✓

**Pull request merged**
