### PR TITLE
feat: [SRM-11592]: Adding all the SLO's data in the SLOPolicyDTO

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36788)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36788)

**Comment by Varsha-lalwani** [comment]
trigger ti0, ti3, compile

**Comment by Varsha-lalwani** [comment]
trigger ti0

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36788)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/governance/beans/SLOPolicyDTO.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/36788#-NAP0rH870IpSCQp1pQW:-NAdhK0m-QDxXYi1ma9C:b-cm9nmf) ([raw file](https://github.com/harness/harness-core/blob/61f6552e35ea5315f57e85c77c6428d595de5912/300-cv-nextgen/src/main/java/io/harness/cvng/governance/beans/SLOPolicyDTO.java#L37)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

lets use slos rather than sloMappedToTheirHealthIndicators. this will be exposed to customer they need not know about health inducators
</blockquote></details>

Lets use SLOHealthIndicatorDTO to send the data back rather than using the SLOHealthIndicator entity directly

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 6 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36788)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger codebasehash

**Pull request closed without merging**
