### PR TITLE
fix: [CDS-42710]: Revert "Completely remove the dependency on canaryDeletefqn and moving to stage."

### PR DESCRIPTION
**Pull request by GoelPratyush99**
Reverts harness/harness-core#37134

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37410)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37410)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37410#-:-NBmZ_PpCvEHT3EoKH1Q:bb7f2mf)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37410#-:-NBmZbwT0kNxI-BD2hj9:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
