### PR TITLE
techdebt: [PIE-3279]: Start new engine for each collection

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)

### CODE REVIEW

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4akTrb4s1H9NO9bPgc:-N4akTrb4s1H9NO9bPgd:b-20k32i) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L112)):*
> ```Java
> 
>   private String getLockName() {
>     return DEBEZIUM_LOCK_PREFIX + changeConsumer.getCollection();
> ```

use the names as discussed
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4alzqhDbLJU40dQ_x0:-N4alzqhDbLJU40dQ_x1:b-zcem2a) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java#L37)):*
> ```Java
>       try {
>         MongoCollectionChangeConsumer changeConsumer = consumerFactory.get(monitoredCollection, changeConsumerConfig);
>         Properties props = DebeziumConfiguration.getDebeziumProperties(debeziumConfig, redisLockConfig);
> ```

moved this preparation to config
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4akxwZEYMKPnRyW13c:-N4akxwZEYMKPnRyW13d:b-eh9av0) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java#L39)):*
> ```Java
>         Properties props = DebeziumConfiguration.getDebeziumProperties(debeziumConfig, redisLockConfig);
>         props.setProperty(DebeziumConfiguration.OFFSET_STORAGE_KEY,
>             debeziumConfig.getOffsetStorageTopic() + "-" + monitoredCollection);
> ```

updates names as discussed

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java` line 112 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4akTrb4s1H9NO9bPgc:-N4bjTDMAB0se5hVk_k-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumController.java#L112)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

use the names as discussed
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4alzqhDbLJU40dQ_x0:-N4fVFA-DuWL9pi9siKf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java#L37)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

moved this preparation to config
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/34253#-N4akxwZEYMKPnRyW13c:-N4fVH8qEgQIH_6W39Bu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cdc4beb9f05465cfbf87f995a08556def9495cf9/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumControllerStarter.java#L39)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

updates names as discussed
</blockquote></details>

Done.

**Review by vaibhav-si — DISMISSED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 7 of 10 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34253)* status: :shipit: complete! ✓

**Pull request merged**
