### PR TITLE
fix: [DEL-3134]: Gracefully fail task in case of vault encryption fails

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30573)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30573)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2633 at r1](https://reviewable.io/reviews/harness/harness-core/30573#-MvJg_vaBVmXD8OPk5ph:-MvJg_vaBVmXD8OPk5pi:b-1s1o9i) ([raw file](https://github.com/harness/harness-core/blob/4067d5f3612e93691d4e45c68cd534173b810797/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2633)):*
> ```Java
>       applyDelegateExpressionEvaluator(delegateTaskPackage, delegateExpressionEvaluator);
>     } catch (Exception e) {
>       SendErrorResponse(delegateTaskPackage);
> ```

S should be small in method name
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2669 at r1](https://reviewable.io/reviews/harness/harness-core/30573#-MvJggFVEoqJGK1j64an:-MvJggFVEoqJGK1j64ao:bz225g6) ([raw file](https://github.com/harness/harness-core/blob/4067d5f3612e93691d4e45c68cd534173b810797/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2669)):*
> ```Java
>     try {
>       Response<ResponseBody> resp =
>           delegateAgentManagerClient.sendTaskStatus(delegateId, taskId, accountId, taskResponse).execute();
> ```

we should retry with backoff here

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30573)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2633 at r1](https://reviewable.io/reviews/harness/harness-core/30573#-MvJg_vaBVmXD8OPk5ph:-MvMt59gEpX0cf0Cd4ZE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4067d5f3612e93691d4e45c68cd534173b810797/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2633)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

S should be small in method name
</blockquote></details>

Done.
___
*[260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, line 2669 at r1](https://reviewable.io/reviews/harness/harness-core/30573#-MvJggFVEoqJGK1j64an:-MvMt5SK2TtK1Yali2Tu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4067d5f3612e93691d4e45c68cd534173b810797/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2669)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

we should retry with backoff here 
</blockquote></details>

Done.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30573)* status: :shipit: complete! ✓

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Comment by gaurav-jain1** [comment]
trigger messagecheck

**Pull request merged**
