### PR TITLE
feat: [PLG-2153]: Implement CreditResourceTest and CreditObjectConverterTest

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
Implement the unit test for CreditResource and Credit Object converter
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48056)

### CODE REVIEW

**Comment by Xin-Harness** [comment]
trigger uts

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48056)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/test/java/io/harness/credit/api/resource/CreditResourceTest.java` line 57 at r1](https://reviewable.io/reviews/harness/harness-core/48056#-NVp6CV24TN6PinwSyDR:-NVp6CV24TN6PinwSyDS:b-7zkdny) ([raw file](https://github.com/harness/harness-core/blob/340478102305eeca7b577222d234a6f0dbf3ffba/930-ng-license-manager/src/test/java/io/harness/credit/api/resource/CreditResourceTest.java#L57)):*
> ```Java
>   public void testGetCredits() {
>     doReturn(Lists.newArrayList(defaultCreditDTO)).when(creditService).getCredits(ACCOUNT_IDENTIFIER);
>     ResponseDTO<List<CreditDTO>> creditsResponseDTO = creditResource.getCredits(ACCOUNT_IDENTIFIER);
> ```

we can try and make an actual client call to this API.
That will exactly mimic the API calls.



_Code snippet:_
```Java
io.harness.cvng.core.resources.MonitoredServiceResourceTest#testCreateFromYaml
```

**Comment by Xin-Harness** [comment]
> ```java
> MonitoredServiceResourceTest
> ```

I am not quite convinced by implementing the real local host resource call just to test if the local host endpoint can be reached or not. If you refer to the previous PR screenshot you could see that the local rest end point has been tested.  https://github.com/harness/harness-core/pull/46350 and https://github.com/harness/harness-core/pull/46069 in the dev environment. However what we really focus on the test scenario is that if the endpoint could retrieve and post the values we want.

**Review by kapil-harness — COMMENTED** [review]
Real local host resource API call will ensure that if in future anything changes in your API headers e.g. POST API becomes PUT API then this UT will fail. 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48056#-:-NWBk9K_9tTVQmRJC4mC:b-35698m)* status: Some of the checks are too old. 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48056)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by Xin-Harness** [comment]
trigger uts

**Comment by Xin-Harness** [comment]
Had discussed with Kapil, the more comprehensive test can be added in separate PR.

**Review by kapil-harness — APPROVED** [review]
Thanks for putting efforts on this. I am approving this PR and will take a stab at it myself once I am back from my vacations.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48056#-:-NWEPOxa6vKM2o9IDi_N:b-mzyo87)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
trigger review

**Comment by Xin-Harness** [comment]
trigger ut2

**Pull request merged**
