### PR TITLE
fix: [SRM-12318]: Updating CloudWatchMetricDataCollectionInfo to handle null collection of MetricInfos and adding UT.

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38504)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38504)

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38504)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/CloudWatchMetricDataCollectionInfo.java` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/38504#-NE-M1-A-8ZwY1NDkYzo:-NE-M1-A-8ZwY1NDkYzp:bywgugj) ([raw file](https://github.com/harness/harness-core/blob/96e9778618f781829f06e138796e5a85ad6b2f22/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/CloudWatchMetricDataCollectionInfo.java#L65)):*
> ```Java
> 
>   public List<CloudWatchMetricInfoDTO> getMetricInfos() {
>     if (CollectionUtils.isEmpty(metricInfos)) {
> ```

nit: You can use CollectionUtils.emptyIfNull()



_Code quote:_
```Java
    if (CollectionUtils.isEmpty(metricInfos)) {
      metricInfos = Collections.emptyList();
    }
    return metricInfos;
```

**Comment by AbhijithHarness** [comment]
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/utils/CloudWatchUtils.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/38504#-NE-MLD4B-EUCB2NJiHx:-NE-MLD4B-EUCB2NJiHy:b7jhj5h) ([raw file](https://github.com/harness/harness-core/blob/96e9778618f781829f06e138796e5a85ad6b2f22/948-cv-nextgen-beans/src/main/java/io/harness/cvng/utils/CloudWatchUtils.java#L97)):*
> ```Java
>     List<String> metricIdentifiers = new ArrayList<>();
>     if (CollectionUtils.isNotEmpty(cloudWatchMetricInfoDTOs)) {
>       requestBodies.addAll(cloudWatchMetricInfoDTOs.stream()
> ```

nit: The old one itself was better code.

**Comment by AbhijithHarness** [comment]
*[`948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/CloudWatchMetricDataCollectionInfo.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/38504#-NE-Mjgn2lXKXmR3fWzF:-NE-Mjgn2lXKXmR3fWzG:b-uu3vkb) ([raw file](https://github.com/harness/harness-core/blob/96e9778618f781829f06e138796e5a85ad6b2f22/948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/CloudWatchMetricDataCollectionInfo.java#L33)):*
> ```Java
>   String region;
>   String groupName;
>   List<CloudWatchMetricInfoDTO> metricInfos;
> ```

nit: Make the metricInfo non nullable and add a default of empty. This will mean no delegate deployment.

**Pull request merged**
