### PR TITLE
fix: [CDS-50509]: fixing BG deployment for TAS

### PR DESCRIPTION
**Pull request by sourabh-awashti**
fixing BG deployment in TAS

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42568)

### CODE REVIEW

**Comment by sourabh-awashti** [comment]
trigger messagecheck

**Comment by sourabh-awashti** [comment]
trigger ft2

**Review by RishabhGupta34 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42568)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42568)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/pcf/TasBlueGreenSetupTaskHandler.java` line 445 at r1](https://reviewable.io/reviews/harness/harness-core/42568#-NLdubnD7Plft9SE8tIh:-NLdubnD7Plft9SE8tIi:b427chu) ([raw file](https://github.com/harness/harness-core/blob/92e9226ce1f0b4186569a7c94b104e85b670b969/930-delegate-tasks/src/main/java/io/harness/delegate/pcf/TasBlueGreenSetupTaskHandler.java#L445)):*
> ```Java
>       }
>     }
>   }
> ```

Do the same for TasBasicSetupTaskHandler

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42568#-:-NLdxaBX7GvDclwjlZTk:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by RishabhGupta34 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42568)* status: :shipit: complete! ✓

**Pull request merged**
