### PR TITLE
fix: [CDS-35753]: modified setup abstraction to include ng - true

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31925)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31925)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
any test required for this?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31925#-:-Mzy6I1x4soZB7bx9opK:b-adze9u)* status: :shipit: complete! ✓

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31925)* status: :shipit: complete! ✓

___
*[125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/AwsResourceServiceHelper.java, line 105 at r1](https://reviewable.io/reviews/harness/harness-core/31925#-MzyAPoiDsGh6AC0-5tn:-MzyAPoiDsGh6AC0-5to:b-lbroa2) ([raw file](https://github.com/harness/harness-core/blob/74c6f3dcbbbacb651a747cfd0646b6e4dffd3a9f/125-cd-nextgen/src/main/java/io/harness/cdng/common/resources/AwsResourceServiceHelper.java#L105)):*
> ```Java
>             .taskSetupAbstraction(SetupAbstractionKeys.projectIdentifier, ngAccess.getProjectIdentifier())
>             .taskSetupAbstraction("ng", "true")
>             .taskSetupAbstraction("owner", ngAccess.getOrgIdentifier() + "/" + ngAccess.getProjectIdentifier())
> ```

we need to provide delegate selector also, no?

**Review by acasian-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31925)* status: :shipit: complete! ✓

**Review by achyuth-harness — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31925#-:-Mzya63x-2wmi5WJq5Qb:bb6un1j)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger license/cla, license, cla

**Pull request merged**
