### PR TITLE
[feat]: [PIE-9489]: Add Pipeline Rollback Stage config, plan creator, and step

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)

### CODE REVIEW

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)* status: 20 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationStepTypes.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/46167#-NSQO3KT9zIt2phAb2PW:-NSQO3KT9zIt2phAb2PX:bc2fykw) ([raw file](https://github.com/harness/harness-core/blob/380bbbf7747279f71e7f4e858497c7789ad00ae2/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationStepTypes.java#L24)):*
> ```Java
>   public static final String CUSTOM_STAGE = "CUSTOM_STAGE";
>   public static final String PIPELINE_STAGE = "PIPELINE_STAGE";
>   public static final String PIPELINE_ROLLBACK_STAGE = "PIPELINE_ROLLBACK_STAGE";
> ```

This is already defined in multiple places. We can use the existing one



_Code quote:_
```Java
PIPELINE_ROLLBACK_STAGE
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)* status: 20 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationStepTypes.java` line 24 at r5](https://reviewable.io/reviews/harness/harness-core/46167#-NSQO3KT9zIt2phAb2PW:-NSQOye9DawXkWs4z3AD:b-889kmj) ([raw file](https://github.com/harness/harness-core/blob/380bbbf7747279f71e7f4e858497c7789ad00ae2/pipeline-service/modules/orchestration/src/main/java/io/harness/OrchestrationStepTypes.java#L24)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

This is already defined in multiple places. We can use the existing one
</blockquote></details>

This is the only place where this exact string literal is. You can search for `"PIPELINE_ROLLBACK_STAGE"`

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 3 of 8 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)* status: 18 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by jamie-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 3 of 8 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 3 of 8 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46167)* status: 1. unresolved discussions.

**Pull request merged**
