### PR TITLE
fix: [PL-30335]: added validation for ldap settings

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
Added validation for NG ldap settings in the following 3 flows:-
1. Validate ldap connection settings.
2. Validate ldap user settings.
3. Validate ldap group settings.

Testing:
1. Local testing done for the validation APIs for ldap connection settings, user settings and group settings.
2. For each API, in case of invalid ldap setting, the validator throws 400 error along with the error message informing the erroneous field.
3. Added UT covering various invalid ldap settings cases.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43313)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43313)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/resource/NGLdapResourceImpl.java` line 102 at r1](https://reviewable.io/reviews/harness/harness-core/43313#-NNAIBJV6YOAzUG0lV9_:-NNAIBJV6YOAzUG0lV9a:b-pylj1a) ([raw file](https://github.com/harness/harness-core/blob/71e5de9a1ee1ff1981ff92157bb196330a6d2f03/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/resource/NGLdapResourceImpl.java#L102)):*
> ```Java
>     }
>     if (isNull(ldapSettings.getConnectionSettings())) {
>       throw new InvalidRequestException("Connection settings cannot be null for ldap settings");
> ```

Is this error propogating to UI ? If so, is null meaningful to end user? 
Something like "Connection settings is not defined for ldap settings"

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43313)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/resource/NGLdapResourceImpl.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/43313#-NNBMtn85gp_oUqrLP6Y:-NNBMtn85gp_oUqrLP6Z:b-iak763) ([raw file](https://github.com/harness/harness-core/blob/7b61904f83e7fddfa954e2ccaabb6c515df0ff7e/120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/resource/NGLdapResourceImpl.java#L97)):*
> ```Java
>   }
> 
>   public void validateLdapSettings(LdapSettings ldapSettings) {
> ```

Please add UT for this and do changes for validator.validate as discussed.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43313)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43313#-:-NNGDcDO0iG9ksFiYnlG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
