### PR TITLE
[fix]: [PL-30993]: Skipping access check on list User Groups in flows where system is fetching User Groups.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
… where system is fetching User Groups.

## Describe your changes
Skipping access check on list User Groups in flows where system is fetching User Groups.
Performing RBAC check on list User Groups only for User context.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)

### CODE REVIEW

**Review by shashank-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)* status: 8 file(s) to review. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/LastAdminCheckServiceImpl.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/43461#-NNL5UPJ7n2nwZCRJbCZ:-NNL5UPJ7n2nwZCRJbC_:b-9xgg61) ([raw file](https://github.com/harness/harness-core/blob/fe054a26d089fdc990f02317c26c20201d09babe/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/LastAdminCheckServiceImpl.java#L145)):*
> ```Java
>                                      .accountIdentifier(accountIdentifier)
>                                      .identifierFilter(new HashSet<>(adminUserGroupIds))
>                                      .build(), true);
> ```

In invite flow skip check is required, but why it is required here?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/LastAdminCheckServiceImpl.java` line 145 at r2](https://reviewable.io/reviews/harness/harness-core/43461#-NNL5UPJ7n2nwZCRJbCZ:-NNL6KPbEFl99Asdqtjt:b-855emu) ([raw file](https://github.com/harness/harness-core/blob/fe054a26d089fdc990f02317c26c20201d09babe/123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/LastAdminCheckServiceImpl.java#L145)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

In invite flow skip check is required, but why it is required here?
</blockquote></details>

In this case as well, its system trying to fetch User Groups and basically in all where system is checking we need avoid RBAC check.

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)* status: 8 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43461)* status: :shipit: complete! ✓

**Pull request closed without merging**
