### PR TITLE
feat: [PL-30386]: remove use of reflection to reduce memory load

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
remove use of reflection to reduce memory load

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41623)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41623)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/41623#-NJKVcf18_jJIOVBK7SE:-NJKVcf18_jJIOVBK7SF:b-cark8i) ([raw file](https://github.com/harness/harness-core/blob/dbb0cf04e67bb48cdda3150bb4b445cd191c9706/400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java#L165)):*
> ```Java
> 
>   @Override
>   public void purgeOlderRecords() {
> ```

Lets make the change in this method too
___
*[`400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/41623#-NJKVgZ_61YRzRg_V9nW:-NJKVgZ_61YRzRg_V9nX:b84b6li) ([raw file](https://github.com/harness/harness-core/blob/dbb0cf04e67bb48cdda3150bb4b445cd191c9706/400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java#L196)):*
> ```Java
>   @Override
>   public void purgeDataRetentionOlderRecords(Map<String, Long> accounts) {
>     Set<Class<? extends GoogleDataStoreAware>> dataStoreClasses =
> ```

Have we checked dataStoreclasses are same after this change?

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41623)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java` line 165 at r1](https://reviewable.io/reviews/harness/harness-core/41623#-NJKVcf18_jJIOVBK7SE:-NJKXa2dCeKxbOQ7gnis:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/dbb0cf04e67bb48cdda3150bb4b445cd191c9706/400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java#L165)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets make the change in this method too
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/41623#-NJKVgZ_61YRzRg_V9nW:-NJKXabd7TcmuJMUvuAZ:burriov) ([raw file](https://github.com/harness/harness-core/blob/dbb0cf04e67bb48cdda3150bb4b445cd191c9706/400-rest/src/main/java/software/wings/service/impl/GoogleDataStoreServiceImpl.java#L196)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Have we checked dataStoreclasses are same after this change?
</blockquote></details>

yes, I have tested it.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41623)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41623)* status: :shipit: complete! ✓

**Pull request merged**
