### PR TITLE
[feat]: [CDS-69593]: Integrating get pipeline api with the async bg reference task

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Have integrated the get pipeline api with the async computation of entity reference in the background thread and updated the thread context name to ScmGitMetaDataContext from NG_GIT_SYNC_CONTEXT. Have tested out the following:
1. for gitX enabled project, inline pipeline
2. for gitX enabled project, remote pipeline from default branch and loaded from cache
3. for gitX enabled project, remote pipeline from default branch and loaded from git
4. for gitX enabled project, remote pipeline from non default branch

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48525)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 601 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkoyB71KSvpd_E6Kw3:-NWkoyB71KSvpd_E6Kw4:bcoixyl) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L601)):*
> ```Java
>     if (StoreType.REMOTE.equals(pipelineEntity.getStoreType()) && !loadFromCache) {
>       GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
>       if (gitEntityInfo != null && gitEntityInfo.getIsDefaultBranch()) {
> ```

this can be a complete util where we just check if its default branch. We don't need to put this condition explicitly here.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 602 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkp67r4Efjf4LzXkDO:-NWkp67r4Efjf4LzXkDP:b-n22xwv) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L602)):*
> ```Java
>       GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
>       if (gitEntityInfo != null && gitEntityInfo.getIsDefaultBranch()) {
>         String branchName = gitEntityInfo.getBranch();
> ```

Lets stop fetching gitEntityInfo and then using it. We should start using helpers for all such stuff that just give us value.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48525)* status: 7 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 601 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkoyB71KSvpd_E6Kw3:-NWpGICq6k-f_LLwh3rw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L601)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this can be a complete util where we just check if its default branch. We don't need to put this condition explicitly here.
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 602 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkp67r4Efjf4LzXkDO:-NWpGkyH5-oWaSRDGeDz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L602)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Lets stop fetching gitEntityInfo and then using it. We should start using helpers for all such stuff that just give us value.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGitMetaDataContext.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/48525#-NWplcyA5YM82LEQukDT:-NWplcyA5YM82LEQukDU:bqc7b1x) ([raw file](https://github.com/harness/harness-core/blob/30a9587eee3b474a6d259bebaf2ca3240159c698/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGitMetaDataContext.java#L25)):*
> ```Java
> @TypeAlias("ScmGitMetaDataContext")
> public class ScmGitMetaDataContext implements GlobalContextData {
>   public static final String SCM_GIT_META_DATA_CONTEXT = "SCM_GIT_META_DATA_CONTEXT";
> ```

I think we cannot do this change right away. This is a common change in sdk and impacts every other service.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 601 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkoyB71KSvpd_E6Kw3:-NWplmkSEPv_Gms1f3QH:b-pipf7c) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L601)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is this in pipeline helper? This is pretty generic utility

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 323 at r2](https://reviewable.io/reviews/harness/harness-core/48525#-NWpm54r7TfS5sDYV1VR:-NWpm54r7TfS5sDYV1VS:b-12uqrm) ([raw file](https://github.com/harness/harness-core/blob/30a9587eee3b474a6d259bebaf2ca3240159c698/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L323)):*
> ```Java
>     }
>     if (pipelineEntity.isPresent()
>         && gitSyncSdkService.isGitSimplificationEnabled(accountId, orgIdentifier, projectIdentifier)) {
> ```

why are these conditions required?

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48525)* status: 7 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java` line 323 at r2](https://reviewable.io/reviews/harness/harness-core/48525#-NWpm54r7TfS5sDYV1VR:-NWpsvnX5hKliuqEFiZd:bq21z5g) ([raw file](https://github.com/harness/harness-core/blob/30a9587eee3b474a6d259bebaf2ca3240159c698/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java#L323)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are these conditions required?
</blockquote></details>

as this is the same flow for the git sync fetch pipeline call, we dont want to have any impact on the existing git sync and compute the reference only for the git experience enabled projects only

the other pipeline.isPresent is just a check for handling null

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48525)* status: 7 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java` line 601 at r1](https://reviewable.io/reviews/harness/harness-core/48525#-NWkoyB71KSvpd_E6Kw3:-NWqz9MB3NWeub2oW8Is:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/384b09e3cafb7f6787885356f3a2d4f4692fa454/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceHelper.java#L601)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why is this in pipeline helper? This is pretty generic utility
</blockquote></details>

Done.
___
*[`900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGitMetaDataContext.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/48525#-NWplcyA5YM82LEQukDT:-NWqzdFJCDeMMwFSf1Ue:b-1i0la7) ([raw file](https://github.com/harness/harness-core/blob/30a9587eee3b474a6d259bebaf2ca3240159c698/900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans/ScmGitMetaDataContext.java#L25)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we cannot do this change right away. This is a common change in sdk and impacts every other service. 
</blockquote></details>

Done.
https://harness.atlassian.net/browse/CDS-70855

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 3 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48525)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger uts

**Comment by adivishy1** [comment]
trigger ut5

**Comment by adivishy1** [comment]
trigger ut5

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by adivishy1** [comment]
trigger review

**Pull request merged**
