### PR TITLE
fix: [DEL-5956]: Fix delegate restart metrics issue

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary
-Fix to delegate restart metrics showing incorrect count. 

Test
- Verified with log statement (Delegate restarted)
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43853)

### CODE REVIEW

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43853)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/43853#-NO8Hl6Z7UMgugcGY7SQ:-NO8Hl6Z7UMgugcGY7SR:b-34n4k2) ([raw file](https://github.com/harness/harness-core/blob/7da26fcd2a65568ceb4ad592b0648c676a6c593b/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L76)):*
> ```Java
>         }
>         delegateMetricsService.recordDelegateMetrics(existingDelegate, DELEGATE_RESTARTED);
>         log.info("Delegate restarted");
> ```

Do we have delegateId along with this log ?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/43853#-NO8Hl6Z7UMgugcGY7SQ:-NO8IQdk5J1N2_HV5mAP:br1xkhe) ([raw file](https://github.com/harness/harness-core/blob/7da26fcd2a65568ceb4ad592b0648c676a6c593b/400-rest/src/main/java/io/harness/delegate/heartbeat/DelegateHeartbeatService.java#L76)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Do we have delegateId along with this log ?
</blockquote></details>

putting back to debug, used that for test

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43853)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger messagecheck

**Pull request merged**
