### PR TITLE
[feat]: [PLG-2326]: added an iterator for sending telemetry events for CI build credits

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added an iterator for sending telemetry events for CI build credits

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48345)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger its

**Comment by kapil-harness** [comment]
trigger uts

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48345#-:-NWHh7Wi9CTUHcx9oDkh:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — CHANGES_REQUESTED** [review]

**Comment by kapil-harness** [comment]
local testing results:
Screenshot 2023-05-26 at 2 47 04 AM

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48345)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/SendProvisionedCICreditsToSegmentHandler.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/48345#gh-1205621748:-NWJmmDh8KQQ9rZhoD6z:bp8fp90) ([raw file](https://github.com/harness/harness-core/blob/7cbbcd0c09be8c6e8adc7b93cd4a614ed90a79d2/930-ng-license-manager/src/main/java/io/harness/credit/schedular/SendProvisionedCICreditsToSegmentHandler.java#L40)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

Please extends the Generic CreditExpiryIteratorHandler, the reason we introduce the generic handler is that we can reuse the below fields as well as the common getFilterQuery() method. All the fields defined below are the same as the ones in CreditExpiryIteratorHandler  except for INTERVAL, please only define INTERNAL as you need in the sub class.
</blockquote></details>

nice catch @Xin-Harness !! Thanks! done!
___
*[`930-ng-license-manager/src/main/java/io/harness/credit/schedular/SendProvisionedCICreditsToSegmentHandler.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/48345#gh-1205624651:-NWJmqQ0-j-OTP_jH2OX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7cbbcd0c09be8c6e8adc7b93cd4a614ed90a79d2/930-ng-license-manager/src/main/java/io/harness/credit/schedular/SendProvisionedCICreditsToSegmentHandler.java#L102)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

You can directly reuse the super class CreditExpiryIteratorHandler getFilterQuery(). 
</blockquote></details>

Done.

**Comment by kapil-harness** [comment]
trigger uts

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48345)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]

**Comment by kapil-harness** [comment]
trigger review

**Pull request merged**
