### PR TITLE
feat: [CDS-44143]: Implement batch undelete api 

### PR DESCRIPTION
**Pull request by rohitk-h**
This api will allow users to specify multiple clusters for unliking them from the environment. 
Added a new bulkDelete function to delete multiple gitops clusters

## Checklist
- [] I've documented the changes in the PR description.
- [] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38299)

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/gitops/custom/ClusterRepositoryCustomImpl.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/38299#-NDVLh361xFqS3gnVohy:-NDVLh374IeG4kO3HdkY:b-qt5ynq) ([raw file](https://github.com/harness/harness-core/blob/a4412e8d6cea8c697d4b421a38981c0e4592ff87/127-cd-nextgen-entities/src/main/java/io/harness/repositories/gitops/custom/ClusterRepositoryCustomImpl.java#L96)):*
> ```Java
>           .execute()
>           .getDeletedCount();
>     } catch (Exception ex) {
> ```

@rohitk-h: Do we get an exception if the record is not found or the cluster is already deleted?

**Comment by rohitk-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/repositories/gitops/custom/ClusterRepositoryCustomImpl.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/38299#-NDVLh361xFqS3gnVohy:-NDVMQYiAj9zwY0qFgg1:bv1nhb8) ([raw file](https://github.com/harness/harness-core/blob/a4412e8d6cea8c697d4b421a38981c0e4592ff87/127-cd-nextgen-entities/src/main/java/io/harness/repositories/gitops/custom/ClusterRepositoryCustomImpl.java#L96)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

@rohitk-h: Do we get an exception if the record is not found or the cluster is already deleted?
</blockquote></details>

No we do not get an exception. Just the deleted count returned is 0.

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by anshul-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterBatchRequest.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/38299#-NDVgXvTE_-1hV1pRCTc:-NDVgXvTE_-1hV1pRCTd:b-wzs6wk) ([raw file](https://github.com/harness/harness-core/blob/22389b253554b0e5f319efb50f0225094787bb7d/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterBatchRequest.java#L57)):*
> ```Java
>   @AssertTrue(
>       message =
>           "Either linkAllClusters/unlinkAllClusters must be set OR clusters must be provided. Search term cannot be set if not linking all clusters")
> ```

Add linking/unlinking here



_Code quote:_
```Java
not linking all clusters
```

**Review by anshul-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterBatchRequest.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/38299#-NDVgXvTE_-1hV1pRCTc:-NDVkpq91tCqpMiN9_nB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22389b253554b0e5f319efb50f0225094787bb7d/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/beans/ClusterBatchRequest.java#L57)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

Add linking/unlinking here
</blockquote></details>

Done.

**Review by anshul-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38299)* status: :shipit: complete! ✓

**Pull request merged**
