### PR TITLE
fix: [PL-29854]: cleanup of startup error logs related to indexes

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)

### CODE REVIEW

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/IndexManagerSession.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/40558#-NHbs5iW4IgcyGkwbg5s:-NHbs5iW4IgcyGkwbg5t:bzcxwsm) ([raw file](https://github.com/harness/harness-core/blob/947f54118d1c528ead2750a04601fb84014118a5/960-persistence/src/main/java/io/harness/mongo/IndexManagerSession.java#L334)):*
> ```Java
> 
>       if (creator.isSubsequence(newCreator)) {
>         log.error("Index {} is a subsequence of index {}", newCreator.getOptions().toString(),
> ```

this should be error. it is anti pattern to create such indexes

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/IndexManagerSession.java` line 334 at r1](https://reviewable.io/reviews/harness/harness-core/40558#-NHbs5iW4IgcyGkwbg5s:-NHc0HX40Y3XI3YShaay:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/947f54118d1c528ead2750a04601fb84014118a5/960-persistence/src/main/java/io/harness/mongo/IndexManagerSession.java#L334)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

this should be error. it is anti pattern to create such indexes
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)* status: 4 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/index/SortCompoundMongoIndex.java` line 95 at r3](https://reviewable.io/reviews/harness/harness-core/40558#-NHi42eqERFTcTVrVc1n:-NHi42eqERFTcTVrVc1o:bmd0k3d) ([raw file](https://github.com/harness/harness-core/blob/928a36ac4aea5dd3ec36ef2e344a5eaa55452ee6/960-persistence/src/main/java/io/harness/mongo/index/SortCompoundMongoIndex.java#L95)):*
> ```Java
>     if ((getFields().size() + getSortFields().size() + getRangeFields().size() == 1)
>         && !getFields().get(0).contains(".")) {
>       log.error("Composite Sort index with only one field {}", getFields().get(0));
> ```

Is this an error?

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558#-:-NI1T5FH52U4Vc57IxCB:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)* status: 1 change requests. 1. unresolved discussions.

**Review by kshitij-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40558#-:-NI6uG5B1xsJQ-7eM-JG:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
