### PR TITLE
feat: [CVS-9083]: Added VerificationTasks and DataCollectionTasks in SLO Debug API

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)

### CODE REVIEW

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/SLODebugResponse.java, line 44 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-Mvyygzr1Kk6U57vtSTI:-Mvyygzs--CcoXzlXyHn:bmi97ey) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/SLODebugResponse.java#L44)):*
> ```Java
>   SLOHealthIndicator sloHealthIndicator;
> 
>   Map<ServiceLevelIndicator, VerificationTask> verificationTaskMap;
> ```

Map<String, VerificationTask> sliIdentifierToVerificationTaskMap -> use only SLI identifier

same for below also. use SLIIdToDataCollectionTaskMap
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DataCollectionTaskService.java, line 37 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-MvyyxkW-O19OgIPouf2:-MvyyxkW-O19OgIPouf3:b-oadw3l) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DataCollectionTaskService.java#L37)):*
> ```Java
>   DataCollectionTask getLastDataCollectionTask(String accountId, String verificationTaskId);
> 
>   List<DataCollectionTask> getDataCollectionTasksDebugData(String accountId, String verificationTaskId, int count);
> ```

Functions should be named on what it does, and not on what it is used for, so that it can be reused.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/VerificationTaskService.java, line 40 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-MvyzJxTAIXwJgp33yRX:-MvyzJxTAIXwJgp33yRY:bt04qi3) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/VerificationTaskService.java#L40)):*
> ```Java
>   String getServiceGuardVerificationTaskId(String accountId, String cvConfigId);
>   String getSLIVerificationTaskId(String accountId, String sliId);
>   VerificationTask getSLIVerificationTaskDebugData(String accountId, String sliId);
> ```

Functions should be named on what it does, and not on what it is used for, so that it can be reused.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, line 221 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-MvyzX65E8yCtmp64ed7:-MvyzX65E8yCtmp64ed8:bdqto39) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L221)):*
> ```Java
>             .filter(DataCollectionTaskKeys.accountId, accountId)
>             .filter(DataCollectionTaskKeys.verificationTaskId, verificationTaskId)
>             .order(Sort.descending(DataCollectionTaskKeys.startTime))
> ```

The data can be too large to get from db. Use .asList(FindOptions findOptions)

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)* status: 8 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/VerificationTaskServiceImpl.java, line 232 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-Mw-kdetE8hgrW0ZQ_vE:-Mw-kdeu1DzmJOPWyTxE:b919wng) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/VerificationTaskServiceImpl.java#L232)):*
> ```Java
> 
>   @Override
>   public VerificationTask getSLIVerificationTaskDebugData(String accountId, String sliId) {
> ```

you can directly use getSLITask

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)* status: 8 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java, line 60 at r1](https://reviewable.io/reviews/harness/harness-core/30776#-Mw-l4Dl2PFrvKDUQGgH:-Mw-l4Dl2PFrvKDUQGgI:b-tnep6j) ([raw file](https://github.com/harness/harness-core/blob/949b8896326e11d5ad7d29f0f44d739c32783749/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java#L60)):*
> ```Java
>     for (VerificationTask verificationTask : verificationTaskMap.values()) {
>       dataCollectionTaskListMap.put(verificationTask,
>           dataCollectionTaskService.getDataCollectionTasksDebugData(
> ```

10 is too much. Let's only get last 3.

**Review by kjoshi12345 — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)* status: 2 change requests. 0 of 1 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776#-:-Mw52Z-w4Fzt-iHA7hYF:bnfp4nl)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30776)* status: :shipit: complete! ✓

**Pull request merged**
