### PR TITLE
fix: [CDS-54103]: Improved error message for evalsymlink failure.

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Earlier error message: `Invalid request: 2023/02/23 11:14:45 evalsymlink failure on '/opt/harness-delegate/repository/k8s/67d9f1ba-f729-34c2-a225-900b72daef36/base' : lstat /opt/harness-delegate/repository/k8s/67d9f1ba-f729-34c2-a225-900b72daef36/base: no such file or directory Error: accumulating resources: accumulating resources from '../../base': evalsymlink failure on '/opt/harness-delegate/repository/k8s/67d9f1ba-f729-34c2-a225-900b72daef36/base' : lstat /opt/harness-delegate/repository/k8s/67d9f1ba-f729-34c2-a225-900b72daef36/base: no such file or directory`

New Error Message: `Invalid request: Kustomize manifest resource not found ../../application inside kustomize base directory`
Screenshot 2023-03-06 at 2 41 51 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/44741#-NPqJVWW3-DMak3DgLLW:-NPqJVWW3-DMak3DgLLX:b2ikrjk) ([raw file](https://github.com/harness/harness-core/blob/4dc71bc29feec5e1660ca0d0efb879ba7127855d/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java#L128)):*
> ```Java
> 
>   private String getMissingResourcePath(String errorMessage) {
>     Pattern pattern = Pattern.compile("accumulating resources from '(.*?)'");
> ```

This can be compiled statically as static class const, no need to compile it every time
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/44741#-NPqJkTZ7iDWyJr-WLrG:-NPqJkTZ7iDWyJr-WLrH:b-pcrl4n) ([raw file](https://github.com/harness/harness-core/blob/4dc71bc29feec5e1660ca0d0efb879ba7127855d/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java#L130)):*
> ```Java
>     Pattern pattern = Pattern.compile("accumulating resources from '(.*?)'");
>     Matcher matcher = pattern.matcher(errorMessage);
>     return matcher.find() ? matcher.group(1) : "";
> ```

let's handle this empty, as discussed, by passing original error instead of RESOURCE_NOT_FOUND one

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java` line 128 at r1](https://reviewable.io/reviews/harness/harness-core/44741#-NPqJVWW3-DMak3DgLLW:-NPr3K2D19wiluPtNe7X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4dc71bc29feec5e1660ca0d0efb879ba7127855d/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java#L128)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This can be compiled statically as static class const, no need to compile it every time
</blockquote></details>

Done.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/44741#-NPqJkTZ7iDWyJr-WLrG:-NPr3KIN45H4r6lsRXD-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4dc71bc29feec5e1660ca0d0efb879ba7127855d/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java#L130)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

let's handle this empty, as discussed, by passing original error instead of RESOURCE_NOT_FOUND one
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/44741#-NPr4rc54TWbZ3gtBSTR:-NPr4rc54TWbZ3gtBSTS:b5ejn4o) ([raw file](https://github.com/harness/harness-core/blob/7a01c3b17ae27771e57870d514b1aed4446c3850/930-delegate-tasks/src/main/java/io/harness/delegate/k8s/kustomize/KustomizeTaskHelper.java#L58)):*
> ```Java
>   @Inject private KustomizeClient kustomizeClient;
>   @Inject private K8sTaskHelperBase k8sTaskHelperBase;
>   private Pattern pattern = Pattern.compile("accumulating resources from '(.*?)'");
> ```

Should be static final and better name, ex: ACCUMULATING_RESOURCES_PATH_PATTERN

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by thisrohangupta — APPROVED** [review]
This one looks good to me.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741)* status: 3 file(s) to review.

**Review by namantalaycha10 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44741#-:-NPvbIJy40AJ4ENsV0gh:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
