### PR TITLE
[fix]: [CDS-37130]: Fixed allow retry failed stage in pipeline template

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34411)

### CODE REVIEW

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34411)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/34411#-N5E-ngq3i6uXxSGD-AQ:-N5E-ngq3i6uXxSGD-AR:b9zypk9) ([raw file](https://github.com/harness/harness-core/blob/9ef8e81aea40a8403d980b712134ecc1c7874f2e/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L160)):*
> ```Java
>     if (TemplateRefHelper.hasTemplateRef(updatedPipeline)) {
>       templateMergeResponseDTO = pmsPipelineTemplateHelper.resolveTemplateRefsInPipeline(
>           accountId, orgIdentifier, projectIdentifier, updatedPipeline);
> ```

please add a unit test for this segment

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34411#-:-N5ERqC77fqJg--p1k4T:bnfp4nl)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 160 at r1](https://reviewable.io/reviews/harness/harness-core/34411#-N5E-ngq3i6uXxSGD-AQ:-N5ERo5E63zfo5ueUPYi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9ef8e81aea40a8403d980b712134ecc1c7874f2e/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L160)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

please add a unit test for this segment
</blockquote></details>

Done.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34411)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Pull request merged**
