### PR TITLE
feat: [DEL-4338]: Change versioning of immutable delegate

### PR DESCRIPTION
**Pull request by AnupamIO**
JIRA: https://harness.atlassian.net/browse/DEL-4338

Tested script changes in local. 
Have not tested using new build.properties in updateVersionInfoYaml.sh, pipeline would need to be updated to use new build.properties. @bharatgoelharness 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)

### CODE REVIEW

**Review by gaurav-jain1 — DISMISSED** [review]
> Reviewed 4 of 10 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: :shipit: complete! ✓

___
*[`build.properties` line 5 at r2](https://reviewable.io/reviews/harness/harness-core/35396#-N7G09VKED2h-NdFDs9t:-N7G09VKED2h-NdFDs9u:b-o1ia6w) ([raw file](https://github.com/harness/harness-core/blob/da3e2f3dc141dd04c9744e6e8829376d78b6cbe7/build.properties#L5)):*
> ```INI
> build.number=76000
> build.patch=000
> delegate.version=22.07.76000
> ```

Right now this field is never actually used. The pipeline stamps with `date().{build.number}`, but we can decide if it makes more sense to have full version in the properties file.  This file might make sense when building .jar but not when building docker image (which is stamped with the same version)

**Comment by AnupamIO** [comment]
trigger ti4

**Comment by AnupamIO** [comment]
trigger messagecheck

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/build.properties` line 2 at r4](https://reviewable.io/reviews/harness/harness-core/35396#-N7uMpAtCKAX5LCXGSRy:-N7uMpAtCKAX5LCXGSRz:b477irc) ([raw file](https://github.com/harness/harness-core/blob/c3d9b43e7eaf80fc7464bccd549f7ec19cdadc6b/260-delegate/build.properties#L2)):*
> ```INI
> build.majorVersion=22
> build.minorVersion=7
> ```

With this new build.properties, person has to bump up build number at both places, /portal/build.properties and portal/260-delegate/build.properties, because former one will generate build for mutable and later for immutable delegates.
@mdmilic I would suggest to keep only one build.properties for both type of delegates. That will even help in separating our code to a separate branch.



_Code quote:_
```INI
build.majorVersion=22
build.minorVersion=7
build.number=76100
build.patch=000
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35396)

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: Some of the checks are too old.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35396)* status: :shipit: complete! ✓

___
*[`260-delegate/build.properties` line 2 at r4](https://reviewable.io/reviews/harness/harness-core/35396#-N7uMpAtCKAX5LCXGSRy:-N8j35eJBGvSJZUP4iAE:br9g7f1) ([raw file](https://github.com/harness/harness-core/blob/c3d9b43e7eaf80fc7464bccd549f7ec19cdadc6b/260-delegate/build.properties#L2)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

With this new build.properties, person has to bump up build number at both places, /portal/build.properties and portal/260-delegate/build.properties, because former one will generate build for mutable and later for immutable delegates.
@mdmilic I would suggest to keep only one build.properties for both type of delegates. That will even help in separating our code to a separate branch.
</blockquote></details>

Agree, we should keep only the one in 260-delegate, this should probably become effective starting with us doing branch cuts.

**Pull request merged**
