### PR TITLE
[fix]: [PIE-7754]: Add only those fields from service inputs that are not in service

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42805)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42805)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86RSF0_kREwGA9qxo:-NM86RSF0_kREwGA9qxp:bqwr9f5) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L98)):*
> ```Java
>         Object value = inputSetFQNMap.get(key);
>         Object templateValue = pipelineYamlFQNMap.get(key);
>         if (!NGExpressionUtils.matchesInputSetPattern(((TextNode) templateValue).asText())) {
> ```

can you add comment what we are doing here
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 184 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86V5v6HI5ywFWHI6K:-NM86V5v6HI5ywFWHI6L:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L184)):*
> ```Java
>       Map<FQN, Object> subMapFromInputSet = YamlSubMapExtractor.getFQNToObjectSubMap(inputSetFQNMap, baseFQN);
>       subMapFromInputSet.keySet().forEach(inputSetKey -> {
>         if (pipelineYamlFQNMap.containsKey(inputSetKey)
> ```

same here
___
*[`953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86a0e55mGhlYe8pkT:-NM86a0e55mGhlYe8pkU:bdra4ig) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java#L522)):*
> ```Java
>             "  field: <+input>\n";
>     merged = MergeHelper.mergeInputSetFormatYamlToOriginYaml(base, runtime);
>     assertThat(merged).isEqualTo(base);
> ```

do we already have test that both base and runtime values are getting merged

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42805)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86RSF0_kREwGA9qxo:-NM87lmH5K5o4Aj_FTBS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L98)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add comment what we are doing here
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java` line 184 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86V5v6HI5ywFWHI6K:-NM87m5zAc2r-6lGqDi6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java#L184)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86a0e55mGhlYe8pkT:-NM87mwf5JxTJ5WoBF2p:b-kasu2z) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java#L522)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we already have test that both base and runtime values are getting merged
</blockquote></details>

That test has top key as stage, needed a separate test for top key as service

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42805)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java` line 522 at r2](https://reviewable.io/reviews/harness/harness-core/42805#-NM86a0e55mGhlYe8pkT:-NM8bGZcCsfrmxQIybRG:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/1232c658c01170750ae4eb3637819f02133b6daf/953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java#L522)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

That test has top key as stage, needed a separate test for top key as service
</blockquote></details>

done

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42805)* status: :shipit: complete! ✓

**Pull request merged**
