### PR TITLE
[feat]: [CDS-41685]: add start and end for rolling strategy

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36275)

**Comment by vladimir-peric** [comment]
trigger messagecheck

**Comment by vladimir-peric** [comment]
trigger recency

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: 38 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/ssh-basic-jar.yaml` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/36275#-N9CDrTVA_RylgzBILD5:-N9CDrTVA_RylgzBILD6:bi1wl9v) ([raw file](https://github.com/harness/harness-core/blob/4523aebae61a80e052be2dfafc068d43c3bace55/125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/ssh-basic-jar.yaml#L97)):*
> ```YAML
>                 type: Script
>                 spec:
>                   workingDirectory: ${HARNESS_RUNTIME_PATH}/tomcat/bin
> ```

This is the old way how to define expressions and could be confusing with the new way  <+...>

**Comment by vladimir-peric** [comment]
*[`125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/ssh-basic-jar.yaml` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/36275#-N9CDrTVA_RylgzBILD5:-N9CGHkK5hiLA0fi4x6J:bv919gz) ([raw file](https://github.com/harness/harness-core/blob/4523aebae61a80e052be2dfafc068d43c3bace55/125-cd-nextgen/src/main/resources/snippets/Pipelines/execution/ssh-basic-jar.yaml#L97)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

This is the old way how to define expressions and could be confusing with the new way  <+...>
</blockquote></details>

In my tests it worked fine. Without {} workingDir is usually not found without manual inputs.

**Comment by vladimir-peric** [comment]
trigger ti0, ti1

**Comment by vladimir-peric** [comment]
trigger ti2, ti3

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 2 of 43 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275#-:-N9CbO1T1Sg4qKkg_XZF:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger ti3

**Comment by acasian-harness** [comment]
trigger ti3

**Review by ivan-83 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36275)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger ti3

**Comment by vladimir-peric** [comment]
trigger ti3

**Comment by vladimir-peric** [comment]
trigger ti3

**Pull request merged**
