### PR TITLE
[feat]: [PIE-4456]: Add .harness folder check while importing Yaml from git

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
It has to be checked that the Yaml which is to be imported is in .harness folder, hence required changes are made

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger ti0

**Review by namanvermah — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 395 at r3](https://reviewable.io/reviews/harness/harness-core/35779#-N8395gu5NVOubl7h3x1:-N8395gu5NVOubl7h3x2:b-nfllut) ([raw file](https://github.com/harness/harness-core/blob/308f7a0ce90250dc8a82c23dde7d3fa4376fd7fa/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L395)):*
> ```Java
>   @POST
>   @Path("/import/{pipelineIdentifier}")
>   @Hidden
> ```

We are making it visible to customer?
cc: @namanvermah

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java` line 395 at r3](https://reviewable.io/reviews/harness/harness-core/35779#-N8395gu5NVOubl7h3x1:-N83Z3JhBJPsNpiJZcBF:b-i4kso5) ([raw file](https://github.com/harness/harness-core/blob/308f7a0ce90250dc8a82c23dde7d3fa4376fd7fa/pipeline-service/contracts/src/main/java/io/harness/pms/pipeline/PipelineResource.java#L395)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

We are making it visible to customer?
cc: @namanvermah 
</blockquote></details>

Added Again

**Review by namanvermah — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35779)* status: :shipit: complete! ✓

**Pull request merged**
