### PR TITLE
feat: [PIE-6591]: Standardize Trigger catalog category and trigger catalog type names - Updated with Constants

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 3 of 10 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: Some of the checks are too old. 12 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 4 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41644#-NJsup2C1FqTli8t25_b:-NJsup2C1FqTli8t25_c:b-o7xb75) ([raw file](https://github.com/harness/harness-core/blob/ada6828638ec1977dbe108f850d1f8f3c0663021/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java#L34)):*
> ```Java
> @Schema(description = "This has details of the Trigger Catalog.")
> public class TriggerCatalogItem {
>   @NotNull @Schema(description = Constants.TRIGGER_CATEGORY) NGTriggerType category;
> ```

Not sure where triggerCatalogItem is used, but if used by customer or some persistent entity, then its a breaking change isn't?

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41644#-NJsup2C1FqTli8t25_b:-NJvRK_P56AEqxRUrIU0:bnuhg7h) ([raw file](https://github.com/harness/harness-core/blob/ada6828638ec1977dbe108f850d1f8f3c0663021/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java#L34)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Not sure where triggerCatalogItem is used, but if used by customer or some persistent entity, then its a breaking change isn't?
</blockquote></details>

This is not being used anywhere. These are changes we are doing as a part of UI refactoringg for trigger. It's a new endpoint used by UI alone

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java` line 34 at r4](https://reviewable.io/reviews/harness/harness-core/41644#-NJsup2C1FqTli8t25_b:-NJvS8pLEdjM6wegk7IF:bqf8c04) ([raw file](https://github.com/harness/harness-core/blob/ada6828638ec1977dbe108f850d1f8f3c0663021/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java#L34)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

This is not being used anywhere. These are changes we are doing as a part of UI refactoringg for trigger. It's a new endpoint used by UI alone
</blockquote></details>

Also, it is not being persisted

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 1 of 2 approvals obtained.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/41644#-NJxkGRp7_wv0fF7Bu5o:-NJxkGRp7_wv0fF7Bu5p:b-m9au81) ([raw file](https://github.com/harness/harness-core/blob/ada6828638ec1977dbe108f850d1f8f3c0663021/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java#L33)):*
> ```Java
> @ApiModel("TriggerCatalogItem")
> @Schema(description = "This has details of the Trigger Catalog.")
> public class TriggerCatalogItem {
> ```

is this backward compatible?

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/41644#-NJxkGRp7_wv0fF7Bu5o:-NJxlyb6EmlqtbMCu8KZ:b-9nfegg) ([raw file](https://github.com/harness/harness-core/blob/ada6828638ec1977dbe108f850d1f8f3c0663021/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog/TriggerCatalogItem.java#L33)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

is this backward compatible?
</blockquote></details>

This is not being used anywhere. These are changes we are doing as a part of UI refactoring for trigger. It's a new endpoint used by UI alone

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41644)* status: :shipit: complete! ✓

**Pull request merged**
