### PR TITLE
feat: [PL-39278]: Added API to fetch unique referred entity types for an entity

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Describe your changes
On the secrets listing page, UI requires an API to fetch all the unique referredByEntity types for secrets. This is required to provide options for the user to select in the referredByEntity filter from UI for the secret usage list.
Since, the EntityType enum contains a lot of unrelated types as well which are not relevant to secrets, this PR introduces an API to fetch all the unique "referredByEntityType" fields for the specified entity from the DB.
It also takes an optional query param- activityTypes, to return the referredByEntity types for specific activity types.

Testing-
1. Tested that the correct unique list of entity types is returned when "referredEntityType" is passed as "Secrets".
2. Tested that the correct unique list of entity types is returned when "referredEntityType" is passed as "Secrets" and "activityTypes" is passed as "ENTITY_USAGE".
3. Added unit testing.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50164)

### CODE REVIEW

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by mohitg0795** [comment]
*[`950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java` line 123 at r4](https://reviewable.io/reviews/harness/harness-core/50164#-NaCCI_ZEy9S3EYXE8au:-NaCCI_ZEy9S3EYXE8av:b-4du7yd) ([raw file](https://github.com/harness/harness-core/blob/84d5ed2f8be6f2e32507434578d383666ceb8757/950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java#L123)):*
> ```Java
> 
>   @GET
>   @Path("/uniqueReferredByEntities")
> ```

we should use kebab case naming for urls.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50164)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java` line 126 at r4](https://reviewable.io/reviews/harness/harness-core/50164#-NaCCVxi5DZajc1qhKWR:-NaCCVxj3IEISetCrGka:bffc8ev) ([raw file](https://github.com/harness/harness-core/blob/84d5ed2f8be6f2e32507434578d383666ceb8757/950-ng-core/src/main/java/io/harness/ng/core/activityhistory/resource/NGActivityResource.java#L126)):*
> ```Java
>   @Hidden
>   @ApiOperation(value = "Get Unique Referred By Entity Types", nickname = "getUniqueReferredByEntities")
>   public ResponseDTO<List<String>> getUniqueReferredByEntityTypes(
> ```

I would suggest the response to be always a structure which may contain list in this case.

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Comment by tiwaritejas** [comment]
trigger uts_JDK11

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 5 files at r2, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50164)* status: 10 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Comment by tiwaritejas** [comment]
trigger uts

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 5 files at r2, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50164)* status: :shipit: complete! ✓

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Comment by tiwaritejas** [comment]
trigger messagecheck

**Pull request merged**
