### PR TITLE
[fix]: [CDS-78115]: Refactor Infrastructure step to support resolving provisioner expressions

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
This PR involves two changes broadly. 
1. `InfrastructureStep`, `AbstractInfrastructureTaskExecutableStep` & `InfrastructureTaskExecutableStepV2` - all 3 classes had 2 infrastructure validation methods which were similar for all 3 classes. Extracted those common methods out and combined the two methods in one validation method. 
2. Before doing infrastructure validation, added a method to resolve provisioner expressions. These expressions were earlier getting resolved after validation and thus the validation was throwing errors. 

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 188 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEpvFO4cRta0yiw6sc:-NdEpvFO4cRta0yiw6sd:bcm6qu3) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L188)):*
> ```Java
>             PdcInfrastructureOutcome.builder()
>                 .credentialsRef(getParameterFieldValue(pdcInfrastructure.getCredentialsRef()))
>                 .hosts(getParameterFieldValue(pdcInfrastructure.getHosts()))
> ```

hosts will not work for dynamic provisioning because we haven't populated it. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 84 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEl3we5iT28ndsFoVc:-NdEl3wfCUqcpR_4SxJA:b-lupq7h) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L84)):*
> ```Java
> 
>   @VisibleForTesting
>   public void validateInfrastructure(Infrastructure infrastructure, Ambiance ambiance, NGLogCallback logCallback) {
> ```

Check if we can remove logging logic from the validation.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 551 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEkTVk5O2LqgffgETr:-NdEkTVlEATnbD15E5ea:b-nt0btu) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L551)):*
> ```Java
>   }
> 
>   public void resolveProvisionerExpressions(Ambiance ambiance, Infrastructure infrastructure) {
> ```

Pls, create a separate class for resolving provisioner expressions. It's not related to validation. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 601 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEpJWQBKWwBumwA6WF:-NdEpJWQBKWwBumwA6WG:bs0646e) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L601)):*
> ```Java
>         PdcInfrastructure pdcInfrastructure = (PdcInfrastructure) infrastructure;
> 
>         List<Map<String, Object>> hostObjects = (List<Map<String, Object>>) expressionEvaluator.evaluateExpression(
> ```

I think this should work , but we need to test dynamic provisioning for PDC. 
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 615 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEnGQjBjuALacZhB6A:-NdEnGQkBSenQL7Lr7h0:b-49f57s) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L615)):*
> ```Java
>         expressionEvaluator.resolveExpression(
>             sshWinRmAwsInfrastructure.getRegion(), ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED);
>         expressionEvaluator.evaluateExpression(
> ```

This is good.
___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 625 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEnK1t5S8VuYZ7s1tq:-NdEnK1t5S8VuYZ7s1tr:b-49f57s) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L625)):*
> ```Java
>         expressionEvaluator.resolveExpression(
>             sshWinRmAzureInfrastructure.getResourceGroup(), ExpressionMode.THROW_EXCEPTION_IF_UNRESOLVED);
>         expressionEvaluator.evaluateExpression(
> ```

This is good.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEh4-F3xPb6kE31IyJ:-NdEgz9h-jsHU7ADNnKK:bueftp2) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L166)):*
> ```Java
>     validateConnector(infrastructure, ambiance, logCallback);
> 
>     if (infrastructure.isDynamicallyProvisioned()) {
> ```

@yogesh-chauhan @lovish1999  I think if we move this if for dynamic provisioning expression and infrastructureValidator.validateInfrastructure() snippet to io.harness.cdng.infra.steps.InfrastructureTaskExecutableStepV2#executeAsyncAfterRbac method that we are good. 
Because, io.harness.cdng.infra.steps.AbstractInfrastructureTaskExecutableStep#obtainTaskInternal is called from executeAsyncAfterRbac and io.harness.cdng.infra.steps.InfrastructureTaskExecutableStepV2#executeSync is also called from executeAsyncAfterRbac. 

Due to the fact that we are having switch-case in validateInfrastructure and resolveProvisionerExpressions, it should work. @lovish1999 just check whether everything that is needed for validation is resolved in terms of not getting NPE.  

Actually, just removed this check because this method is called from executeAsyncAfterRbac where we already have validation. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 327 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdEjKNz80yZ5w1Dtb-J:-NdEjKO-0S4Z_GIHIMvg:b-jn925v) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L327)):*
> ```Java
>     validateConnector(spec, ambiance, logCallback);
>     saveExecutionLog(logCallback, "Fetching environment information...");
>     if (spec.isDynamicallyProvisioned()) {
> ```

Actually, just removed this check because this method is called from executeAsyncAfterRbac where we already have validation.

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 544 at r1](https://reviewable.io/reviews/harness/harness-core/52268#-NdF-PXQ4DVx8E2FGdXN:-NdF-PXQ4DVx8E2FGdXO:b-dfa84m) ([raw file](https://github.com/harness/harness-core/blob/1bafbf2e011c1addc56993e17b1096f2e7064dab/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L544)):*
> ```Java
>   }
> 
>   public void requireOne(ParameterField<?> first, ParameterField<?> second) {
> ```

Pass the list of ParameterFileds.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 10 of 12 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYnz84-aJBct1cOWzG:-NdYnz84-aJBct1cOWzH:b-91exbi) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L117)):*
> ```Java
>             K8sDirectInfrastructureOutcome.builder()
>                 .connectorRef(k8SDirectInfrastructure.getConnectorRef().getValue())
>                 .namespace(k8SDirectInfrastructure.getNamespace().getValue())
> ```

this means, now we will not resolve namespace if it comes through provisioner ?

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)* status: Some of the checks are too old. 14 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 117 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYnz84-aJBct1cOWzG:-NdYoTS1BmWAiTUK3wyu:br6338l) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L117)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this means, now we will not resolve namespace if it comes through provisioner ?
</blockquote></details>

We will be doing it via this method ```infrastructureTaskHelper.resolveProvisionerExpressions(ambiance, infrastructure);

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 80 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYuuM0EuF2A-FrBpuA:-NdYuuM0EuF2A-FrBpuB:bi424e5) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L80)):*
> ```Java
>   @Inject private CustomDeploymentInfrastructureHelper customDeploymentInfrastructureHelper;
> 
>   @VisibleForTesting
> ```

public methods need not be made Visible. They are by default

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 82 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYv5Fz9kgceKYa0M-B:-NdYv5Fz9kgceKYa0M-C:b4bqf5s) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L82)):*
> ```Java
>   @VisibleForTesting
>   public void validateInfrastructure(Infrastructure infrastructure, Ambiance ambiance, NGLogCallback logCallback) {
>     String k8sNamespaceLogLine = "Kubernetes Namespace: %s";
> ```

string declaration should move below the if check. 

Also, this should be a private final static constant

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 84 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYvCYd3L_G-p6Mc0UQ:-NdYvCYd3L_G-p6Mc0UR:bgvytqu) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L84)):*
> ```Java
>     String k8sNamespaceLogLine = "Kubernetes Namespace: %s";
>     if (infrastructure == null) {
>       throw new InvalidRequestException("Infrastructure definition can't be null or empty");
> ```

can't -> cannot

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java` line 121 at r3](https://reviewable.io/reviews/harness/harness-core/52268#-NdYvNvJ5sDhTrITN8Mq:-NdYvNvK30Ifo4XVnzYA:b-qptxjp) ([raw file](https://github.com/harness/harness-core/blob/9b61ae1b0d2c3f5f817d3135d93bf2723d9242ba/125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/infra/InfrastructureValidator.java#L121)):*
> ```Java
>         if (k8sGcpInfrastructure.getNamespace() != null && isNotEmpty(k8sGcpInfrastructure.getNamespace().getValue())) {
>           saveExecutionLogSafely(
>               logCallback, color(format(k8sNamespaceLogLine, k8sGcpInfrastructure.getNamespace().getValue()), Yellow));
> ```

why are logging this here ? Is this in addition to the logging for k8s namespace we already have ? If there is a behaviour difference in logging, could you please attach relevant screenshots

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52268)* status: Some of the checks are too old. 12 file(s) to review. 1 of 2 approvals obtained.

**Pull request closed without merging**
