### PR TITLE
[feat]:[pl-28768]: add yaml validation in pipeline, input-set and template service

### PR DESCRIPTION
**Pull request by adivishy1**
Adding yaml validation in pipeline, input-set and template service for creating, getting and updating entity on git

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38712)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger checkstyle, compile, pmd, ti1, ft2

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38712#-NEAdjg9Cs6RkZ-HKQsz:-NEAdjg9Cs6RkZ-HKQt-:bgtgi5u) ([raw file](https://github.com/harness/harness-core/blob/00fb649ff005ba8a8a618760a91ce3e129839992/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L99)):*
> ```Java
>       String yamlToPush = templateToSave.getYaml();
>       addGitParamsToTemplateEntity(templateToSave, gitEntityInfo);
>       gitAwareEntityHelper.validateFilePathHasCorrectExtension(gitEntityInfo.getFilePath());
> ```

why is it specially added in repo layer? Why can't it be inherent part of createEntity method?

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/38712#-NEAdyQTEQwdtz3Q05eR:-NEAdyQTEQwdtz3Q05eS:b7pxrv1) ([raw file](https://github.com/harness/harness-core/blob/00fb649ff005ba8a8a618760a91ce3e129839992/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L100)):*
> ```Java
>       addGitParamsToTemplateEntity(templateToSave, gitEntityInfo);
>       gitAwareEntityHelper.validateFilePathHasCorrectExtension(gitEntityInfo.getFilePath());
>       gitAwareEntityHelper.createEntityOnGit(templateToSave, yamlToPush, scope);
> ```

Why is it only integrated in createEntity calls? It should be in all fetch calls as well as we don't allow to fetch any file other than yaml.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38712#-NEAdjg9Cs6RkZ-HKQsz:-NEAkr0hChylYUeIJHqB:b-oxp81n) ([raw file](https://github.com/harness/harness-core/blob/00fb649ff005ba8a8a618760a91ce3e129839992/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L99)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

If we add this on the create method, then we will be making this specific to the yaml creation
Added this check from service so that, we will be keeping the createEntityOnGit generic

</blockquote></details>

GitAwareEntityHelper is sort of service specific only. Our SDK method is the one that is common for all to use which shouldn't have any such checks. We can add it to the create/update/read methods.
If later someone doesn't want this check, they should create their own method for the same.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38712)* status: 6 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java` line 99 at r2](https://reviewable.io/reviews/harness/harness-core/38712#-NEAdjg9Cs6RkZ-HKQsz:-NEAo6SkBxBRJ_X67hv_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/00fb649ff005ba8a8a618760a91ce3e129839992/840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java#L99)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

GitAwareEntityHelper is sort of service specific only. Our SDK method is the one that is common for all to use which shouldn't have any such checks. We can add it to the create/update/read methods.
If later someone doesn't want this check, they should create their own method for the same.
</blockquote></details>

Done.

**Comment by adivishy1** [comment]
trigger

**Pull request closed without merging**
