### PR TITLE
[feat]: [CDS-67801]: Provide original execution stage ID to rollback steps

### PR DESCRIPTION
**Pull request by namanvermah**
Add original stage execution id to PostExecutionRollbackInfo and put it in ambiance whenever a stage node starts in rollback mode

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47281)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger uts

**Comment by namanvermah** [comment]
trigger commonchecks

**Comment by namanvermah** [comment]
trigger codebasehash

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47281)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47281)* status: :shipit: complete! ✓

**Comment by namanvermah** [comment]
trigger review

**Pull request merged**
