### PR TITLE
feat: [PL-25846]: added error handling for ADO integration

### PR DESCRIPTION
**Pull request by mohitg0795**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)

### CODE REVIEW

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 6 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreatePullRequestScmApiErrorHandlerTest.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/34350#-N5-Vspc04FzAmYc7vBd:-N5-Vspc04FzAmYc7vBe:b-wec3rt) ([raw file](https://github.com/harness/harness-core/blob/126f3c27ed4e162cd5b6113b50117fbc3554e029/136-git-sync-manager/src/test/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreatePullRequestScmApiErrorHandlerTest.java#L94)):*
> ```Java
> 
>   @Test
>   @Owner(developers = BHAVYA)
> ```

Test name contains bhavya's name

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreatePullRequestScmApiErrorHandlerTest.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/34350#-N5-Vspc04FzAmYc7vBd:-N5-X5z2CUcyB6zpuyk3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/126f3c27ed4e162cd5b6113b50117fbc3554e029/136-git-sync-manager/src/test/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreatePullRequestScmApiErrorHandlerTest.java#L94)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

Test name contains bhavya's name
</blockquote></details>

done

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: 22 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateBranchScmApiErrorHandler.java` line 33 at r4](https://reviewable.io/reviews/harness/harness-core/34350#-N5-toLL1SCR7vJkWO5p:-N5-toLL1SCR7vJkWO5q:b-el3n8f) ([raw file](https://github.com/harness/harness-core/blob/d0c6de70a3ed01769b34cdcbe8477812316ec60b/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/ado/AdoCreateBranchScmApiErrorHandler.java#L33)):*
> ```Java
>   public void handleError(int statusCode, String errorMessage, ErrorMetadata errorMetadata) throws WingsException {
>     switch (statusCode) {
>       case 203:
> ```

have you tested this flow?
As far as I know, there is a check that if status code is greater than 300, then only handlers will be called

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 8 files at r2, 7 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: 11 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by bhavya181 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by DeepakPatankar — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34350)* status: :shipit: complete! ✓

**Pull request merged**
