### PR TITLE
fix: [PL-22114]: added account identifier as mandatory param in create git sync config request

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)

### CODE REVIEW

**Review by DeepakPatankar — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 43 files at r2, 37 of 37 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)* status: 43 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 6 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)* status: 37 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 6 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)* status: 37 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209#-:-MupzdwdBNlvquKV1y-X:bnfp4nl)* status: 37 file(s) to review.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 37 of 37 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30209)* status: :shipit: complete! ✓

**Pull request merged**
