### PR TITLE
feat: [PL-27456]: Un-revert "Added build files for 980-commons with no cycles pres…

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Original PR https://github.com/harness/harness-core/pull/36688

This was reverted earlier and now we are getting it back. Revert was done as harness-core was reaching its classpath limit and I reverted this to help unblock other engineers.

We have already fixed the underlying problem by moving to bazel 5. In addition to changes in the original PR, here are a few changes:

1) Removed CLASSPATH limit -- this is not required as we have moved to bazel 5 which fixes the underlying issue of longer class paths.
2) There are some tests that are reading source file like 220-graphql and expect source files to be present in some location relative to the test file. We have to handle bazel-5's sandboxing specific logic to read the source code.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38011)

### CODE REVIEW

**Review by puneetsar — APPROVED** [review]
> Reviewed 35 of 35 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38011)* status: 37 file(s) to review. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 35 of 35 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38011)* status: :shipit: complete! ✓

**Review by piyush-harness — APPROVED** [review]
> Reviewed 35 of 35 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38011)* status: :shipit: complete! ✓

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 35 of 35 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38011)* status: :shipit: complete! ✓

**Pull request merged**
