### PR TITLE
fix: [DEL-5976]: Add referenceFalse kryo serializer option to perpetual task

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary: 
Add referenceFalseKryoSerializer option to Perpetual task serialization

Test Performed
NG
-Verify the Connector creation and validation which creates PT task
-Verify PT task getting assigned, alive, and making PT context calls to manager/NG Manager.
-Sanity on pipeline or task execution which uses the connector.
-Sanity on connector creation, delegate creation and pipeline execution with the latest and older delegate version

CG
-Verified PT K8Watch task creation, aliveness and making PT context calls to manager
- End to end k8 task flow
- Test with older and newer delegate versions

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44079)

### CODE REVIEW

**Comment by jennyjames21** [comment]
NG Connector + pipeline execution (Same delegate version)
image
image
Connector Validation PT Task
image
image

Older Version delegate - NG Connector and pipeline
image


CG - K8 end to end flow(same delegate version)
image
K8 Perpetual task
image

CG Older version delegate
image
image

**Comment by jennyjames21** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
trigger ti0

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by jennyjames21** [comment]
trigger ti2

**Comment by jennyjames21** [comment]
trigger ti3

**Comment by jennyjames21** [comment]
trigger ti4

**Comment by jennyjames21** [comment]
trigger ti0

**Comment by jennyjames21** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/artifact/ArtifactCollectionPTaskServiceClient.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/44079#-NOfrX0q46J-NxBTStQW:-NOfrX0sBgMzUV5oumf8:b-i9axv5) ([raw file](https://github.com/harness/harness-core/blob/ce52d5300d7a7bdb04e6015bd78f47fcb52a5db3/400-rest/src/main/java/io/harness/artifact/ArtifactCollectionPTaskServiceClient.java#L58)):*
> ```Java
>   }
> 
>   private KryoSerializer getKryoSerializer(boolean referenceFalse) {
> ```

instead of copying in every class, create an abstract class where you have this method and both the serializer and have these client classes extend the abstract class. This way the logic is at one place and later we can just make one change to use referenceFalse serializer

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/44079#-NOfsW9E71tOo6WHEyUI:-NOfsW9E71tOo6WHEyUJ:b-tyzvht) ([raw file](https://github.com/harness/harness-core/blob/ce52d5300d7a7bdb04e6015bd78f47fcb52a5db3/420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java#L56)):*
> ```Java
>       responseObserver.onNext(PerpetualTaskContextResponse.newBuilder()
>                                   .setPerpetualTaskContext(perpetualTaskService.perpetualTaskContext(
>                                       request.getPerpetualTaskId().getId(), false))
> ```

do we use this? id not then can we remove it?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 26 of 26 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44079)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/io/harness/artifact/ArtifactCollectionPTaskServiceClient.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/44079#-NOfrX0q46J-NxBTStQW:-NOgLDFt15DpUq4g86pq:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/ce52d5300d7a7bdb04e6015bd78f47fcb52a5db3/400-rest/src/main/java/io/harness/artifact/ArtifactCollectionPTaskServiceClient.java#L58)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

instead of copying in every class, create an abstract class where you have this method and both the serializer and have these client classes extend the abstract class. This way the logic is at one place and later we can just make one change to use referenceFalse serializer 
</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/44079#-NOfsW9E71tOo6WHEyUI:-NOgLHk2E8pcxq3i8bQx:b-r8xs6l) ([raw file](https://github.com/harness/harness-core/blob/ce52d5300d7a7bdb04e6015bd78f47fcb52a5db3/420-delegate-service/src/main/java/io/harness/perpetualtask/grpc/PerpetualTaskServiceGrpc.java#L56)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

do we use this? id not then can we remove it?
</blockquote></details>

no we dont, for compilation purpose.
I have JIRA to remove grpc related code

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 11 of 26 files at r1, 14 of 14 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44079)* status: 16 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44079)* status: :shipit: complete! ✓

**Comment by jennyjames21** [comment]
trigger ti0

**Comment by jennyjames21** [comment]
trigger ti1

**Review by xingchi-jin — APPROVED** [review]
read all files, LG 

> Reviewed 11 of 26 files at r1, 14 of 14 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44079#-:-NOhFv2UDScE0jDCGH55:b-xnwvb6)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44079)* status: :shipit: complete! ✓

**Pull request merged**
