### PR TITLE
feat: [CDS-49907]: Added connector outcome classes

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Added connector outcome classes for the following connectors:
1. ArtifactoryConnector
2. BitbucketConnector
3. AzureArtifactsConnector
4. DockerConnector
5. HttpHelmConnector
6. OciHelmConnector
7. JenkinsConnector
8. NexusConnector
9. AwsCodeCommitConnector
10. AzureRepoConnector

so that connector attributes can be accessed as variables in Deployment Template Stage in NG.
Tested accessing all variables for these connectors in local environment

 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by RishabhGupta34** [comment]
trigger ft1, ft2

**Comment by USB-05** [comment]
trigger gl

**Comment by USB-05** [comment]
trigger gl

**Review by shivamnegi94 — APPROVED** [review]

**Comment by vtxorxwitty** [comment]
trigger ft1

**Comment by vtxorxwitty** [comment]
trigger ft2

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)* status: 52 file(s) to review.

**Review by vtxorxwitty — APPROVED** [review]
> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632#-:-NM8uVcR3NVMQBfhpbB2:bnfp4nl)* status: :shipit: complete! ✓

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)* status: :shipit: complete! ✓

**Review by GoelPratyush99 — APPROVED** [review]

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)* status: :shipit: complete! ✓

**Review by devkimittal — APPROVED** [review]
Validated for bitbucket, azureRepo, awsCodeCommit.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed 48 of 52 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42632)* status: :shipit: complete! ✓

**Pull request merged**
