### PR TITLE
[fix]: [CDS-83539] : fix input validation and reconcile for remote svc/env in linked template

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

* adding service.gitBranch & environment.gitBranch in exclude set for validation
* gitbranch field is not part of template input yaml (generated from enity), but is given from pipeline as template inputs, 
in this case refresh input call was removing gitBranch field from pipeline yaml. Which in turn was making refresh-input for remote service and env fail.

now added custom logic to add gitBranch filed in templateRefreshedYaml

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by adivishy1** [comment]
the statement
```
gitbranch field is not part of template input yaml (generated from enity), but is given from pipeline as template inputs,
in this case refresh input call was removing gitBranch field from pipeline yaml. Which in turn was making refresh-input for remote service and env fail.
```
gitBranch will be passed by the parent entity, if the parent entity happens to be a template, we will be having the gitBranch in the template yaml

**Comment by tchaurasiya** [comment]
trigger review

**Comment by tchaurasiya** [comment]
trigger uts

**Review by hingerabhinav — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)* status: 7 file(s) to review. 0 of 2 approvals obtained.

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)* status: 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlRefreshHelper.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/55118#-NimeW2_AvGzphfASHeT:-NimeW2_AvGzphfASHeU:bazsnoi) ([raw file](https://github.com/harness/harness-core/blob/b687198c6f3611ffd296916ef143475194d99f7a/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlRefreshHelper.java#L179)):*
> ```Java
>           if (doesSourceNodeHaveSiblingRuntime(sourceNodeFqnToValueMap, fqnToSiblingOfNonIgnorableKey)) {
>             refreshedFqnToValueMap.put(fqn, nodeToRefreshFqnToValueMap.get(fqn));
>             putNonIgnorableFQNInSourceNodeYamlConfig(sourceNodeYamlConfig, nodeToRefreshFqnToValueMap, fqn);
> ```

@tchaurasiya i think if we put the value only in the `sourceNodeYamlConfig` that would suffice. As per implementation of YamlCOnfig, No need to put  `refreshedFqnToValueMap.put(fqn, nodeToRefreshFqnToValueMap.get(fqn))`; Can you check once?
___
*[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/55118#-Nimf1jvAZkHhosrRwkf:-Nimf1jvAZkHhosrRwkg:b-9c59qi) ([raw file](https://github.com/harness/harness-core/blob/b687198c6f3611ffd296916ef143475194d99f7a/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L59)):*
> ```Java
>   // Returns the refreshed YAML when a YAML String is passed.
> 
>   private static final String FQN_SEPARATOR = "\\.";
> ```

Is this constant being used?

**Comment by tchaurasiya** [comment]
> > Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)_ status: 1 change requests. 0 of 2 approvals obtained.
> 
> _[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlRefreshHelper.java` line 179 at r2](https://reviewable.io/reviews/harness/harness-core/55118#-NimeW2_AvGzphfASHeT:-NimeW2_AvGzphfASHeU:bazsnoi) ([raw file](https://github.com/harness/harness-core/blob/b687198c6f3611ffd296916ef143475194d99f7a/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlRefreshHelper.java#L179)):_
> 
> > ```java
> >           if (doesSourceNodeHaveSiblingRuntime(sourceNodeFqnToValueMap, fqnToSiblingOfNonIgnorableKey)) {
> >             refreshedFqnToValueMap.put(fqn, nodeToRefreshFqnToValueMap.get(fqn));
> >             putNonIgnorableFQNInSourceNodeYamlConfig(sourceNodeYamlConfig, nodeToRefreshFqnToValueMap, fqn);
> > ```
> 
> @tchaurasiya i think if we put the value only in the `sourceNodeYamlConfig` that would suffice. As per implementation of YamlCOnfig, No need to put `refreshedFqnToValueMap.put(fqn, nodeToRefreshFqnToValueMap.get(fqn))`; Can you check once?
> 
> _[`template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/55118#-Nimf1jvAZkHhosrRwkf:-Nimf1jvAZkHhosrRwkg:b-9c59qi) ([raw file](https://github.com/harness/harness-core/blob/b687198c6f3611ffd296916ef143475194d99f7a/template-service/service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L59)):_
> 
> > ```java
> >   // Returns the refreshed YAML when a YAML String is passed.
> > 
> >   private static final String FQN_SEPARATOR = "\\.";
> > ```
> 
> Is this constant being used?

Yeah checked once, Both are required here.

**Comment by tchaurasiya** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by lovish1999 — APPROVED** [review]

**Comment by tchaurasiya** [comment]
trigger review

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55118)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
