### PR TITLE
feat: [PL-31580]: Enhanced code to apply global limits on documents fetched by mongo queries

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
Enhanced code to apply global limits on documents fetched by mongo queries
we have overridden all mongo queries and set the limits at end point on queries, added a config maxDocumentsToBeFetched for setting the value of this limit
These are the queries on which limits have been added -

stream - working ✅
mapReduce - working ✅, ensure mapeReduceOptions != null
executeQuery - working ✅
find - working ✅
findAllAndRemove - will need to remove all its usages, tracking in separate ticket
findAll - all usages has been diverted to use find method with empty query ✅
findDistinct - not work (spring mongo does not consider limit for this operation)
aggregate - working ✅
aggregateStream - working ✅

Currently the config maxDocumentsToBeFetched value has been set to INT_MAX, so, that it will not affect any existing query

Tested above mentioned different queries by setting maxLimit to 1

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)

### CODE REVIEW

**Review by ankit-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSLpAU0FBU6ffM2zP4:-NOSLpAU0FBU6ffM2zP5:bhd8lxx) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L57)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.PL)
> public class HMongoTemplate extends MongoTemplate implements HealthMonitor {
> ```

We should expose a public static value of int NO_LIMIT = Integer.MAX_VALUE
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 339 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSKWAT9OvQfIPmoZqZ:-NOSKWAU92HEvxlHNhHA:b6r0ca) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L339)):*
> ```Java
>       aggregationOperations.add(Aggregation.limit(maxDocumentsToBeFetched));
>     }
>     // Todo: once spring got updated, set maxTimeMS in aggregation options
> ```

Lets finish this TODO as well
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 359 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSKYbD38YpKjNMC3N9:-NOSKYbD38YpKjNMC3NA:b6r0ca) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L359)):*
> ```Java
>       aggregationOperations.add(Aggregation.limit(maxDocumentsToBeFetched));
>     }
>     // Todo: once spring got updated, set maxTimeMS in aggregation options
> ```

Lets finish this TODO as well

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 57 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSLpAU0FBU6ffM2zP4:-NOnciv-12WjeeWAvyCt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L57)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We should expose a public static value of int NO_LIMIT = Integer.MAX_VALUE
</blockquote></details>

Done.
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 339 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSKWAT9OvQfIPmoZqZ:-NOnckh8EUl7lg0q00Ft:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L339)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets finish this TODO as well
</blockquote></details>

Done.
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 359 at r4](https://reviewable.io/reviews/harness/harness-core/44038#-NOSKYbD38YpKjNMC3N9:-NOnclYt2wCsg9Kfx1Ij:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7e933b7c64b6e5dd29db4d99d6ba8be6beaf4342/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L359)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets finish this TODO as well
</blockquote></details>

Done.

**Review by gn-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 357 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqSRUf2_uUM1b0mgVq:-NOqSRUf2_uUM1b0mgVr:b-j4f6tn) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L357)):*
> ```Java
>     document.append(MAX_TIME, (long) maxOperationTimeInMillis);
>     List<AggregationOperation> aggregationOperations = new ArrayList<>(aggregation.getPipeline().getOperations());
>     boolean isLimitOperationNotApplied = aggregationOperations.stream().noneMatch(
> ```

nit: create positive variables rather than negative ones. 

 isLimitOperationApplied = aggregationOperations.stream().anyMatch();

if (!isLimitOperationApplied) {
  ...
}



_Code quote:_
```Java
boolean isLimitOperationNotApplied 
```
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 361 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqSLB65sw1c5jr0DWA:-NOqSLB65sw1c5jr0DWB:bze0xlt) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L361)):*
> ```Java
>     if (isLimitOperationNotApplied) {
>       aggregationOperations.add(Aggregation.limit(maxDocumentsToBeFetched));
>     }
> ```

deduplicate this logic in a separate private function



_Code quote:_
```Java
    Document document = aggregation.getOptions().toDocument();
    document.append(MAX_TIME, (long) maxOperationTimeInMillis);
    List<AggregationOperation> aggregationOperations = new ArrayList<>(aggregation.getPipeline().getOperations());
    boolean isLimitOperationNotApplied = aggregationOperations.stream().noneMatch(
        aggregationOperation -> LimitOperation.class.equals(aggregationOperation.getClass()));
    if (isLimitOperationNotApplied) {
      aggregationOperations.add(Aggregation.limit(maxDocumentsToBeFetched));
    }
```
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoConfig.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqOyyZ4f-AcUnk8OZI:-NOqOyy_8uwAEyQy3ZaX:b-s8gaee) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/960-persistence/src/main/java/io/harness/mongo/MongoConfig.java#L55)):*
> ```Java
>   public static final String DEFAULT_URI = "mongodb://localhost:27017/wings";
>   public static final String MONGODB_SCHEMA = "mongodb";
>   public static final int NO_LIMIT = Integer.MAX_VALUE;
> ```

nit: not adding much value - can inline Integer.MAX_VALUE

unless you want to reuse this variable in many other files going forward



_Code quote:_
```Java
 public static final int NO_LIMIT = Integer.MAX_VALUE;
```

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 2 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 357 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqSRUf2_uUM1b0mgVq:-NOrSuGh011jshpaJBvg:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L357)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: create positive variables rather than negative ones. 

 isLimitOperationApplied = aggregationOperations.stream().anyMatch();

if (!isLimitOperationApplied) {
  ...
}
</blockquote></details>

done
___
*[`959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java` line 361 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqSLB65sw1c5jr0DWA:-NOrSwCy4L9t_lJYxmsV:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/959-ng-persistence/src/main/java/io/harness/springdata/HMongoTemplate.java#L361)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

deduplicate this logic in a separate private function
</blockquote></details>

done
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoConfig.java` line 55 at r5](https://reviewable.io/reviews/harness/harness-core/44038#-NOqOyyZ4f-AcUnk8OZI:-NOrSxGSEjVwkadGLdOj:b-b5kqtb) ([raw file](https://github.com/harness/harness-core/blob/c4f5d81d8b69e8149130f488ea3eadea7463aa43/960-persistence/src/main/java/io/harness/mongo/MongoConfig.java#L55)):*
<details><summary><i>Previously, gn-harness (Gaurav Nanda) wrote…</i></summary><blockquote>

nit: not adding much value - can inline Integer.MAX_VALUE

unless you want to reuse this variable in many other files going forward
</blockquote></details>

yes, we want to expose it so that developers can use it, if they have no other option than fetching all documents

**Review by gn-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 2 file(s) to review. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by rijajoo — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44038)* status: 3. unresolved discussions.

**Pull request merged**
