### PR TITLE
[fix]: [PL-28680]: Improved NG & CG audits to include more scenarios of Auth settings

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
Generate audits when auth settings change from:
1. SAML to LDAP
2. LDAP to SAML
3. USER_PASSWORD to OAUTH
4. OAUTH to USER_PASSWORD 

## Checklist

- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/39323#-NFSEOQk8_yFeeyHrml6:-NFSEOQl65Eln_BntK7_:b5n52vf) ([raw file](https://github.com/harness/harness-core/blob/90019619913927ced5c07aafb594b274a9fa8bd7/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L218)):*
> ```Java
>       } else if (newAuthMechanism == OAUTH) {
>         ssoSettings = ssoSettingService.getOauthSettingsByAccountId(accountIdentifier);
>       }
> ```

Nit switch case would have been better in this scenario. Thanks



_Code quote:_
```Java
      if (newAuthMechanism == SAML) {
        ssoSettings = ssoSettingService.getSamlSettingsByAccountId(accountIdentifier);
      } else if (newAuthMechanism == LDAP) {
        ssoSettings = ssoSettingService.getLdapSettingsByAccountId(accountIdentifier);
      } else if (newAuthMechanism == OAUTH) {
        ssoSettings = ssoSettingService.getOauthSettingsByAccountId(accountIdentifier);
      }
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/39323#-NFSF9BeBrFXoUiWEMSu:-NFSF9BeBrFXoUiWEMSv:bwl8net) ([raw file](https://github.com/harness/harness-core/blob/90019619913927ced5c07aafb594b274a9fa8bd7/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L219)):*
> ```Java
>         ssoSettings = ssoSettingService.getOauthSettingsByAccountId(accountIdentifier);
>       }
>       auditServiceHelper.reportForAuditingUsingAccountId(accountIdentifier, null, ssoSettings, Event.Type.ENABLE);
> ```

Minor Can we add a log line here, will help in debugging, Thanks



_Code quote:_
```Java
auditServiceHelper.reportForAuditingUsingAccountId(accountIdentifier, null, ssoSettings, Event.Type.ENABLE);
```

**Review by pbarapatre10 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)* status: 2 file(s) to review. 0 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 218 at r2](https://reviewable.io/reviews/harness/harness-core/39323#-NFSEOQk8_yFeeyHrml6:-NFSPeDq-VWvGkCGpi69:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/90019619913927ced5c07aafb594b274a9fa8bd7/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L218)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Nit switch case would have been better in this scenario. Thanks
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 219 at r2](https://reviewable.io/reviews/harness/harness-core/39323#-NFSF9BeBrFXoUiWEMSu:-NFSPcLtBrbDgeIPaUqc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/90019619913927ced5c07aafb594b274a9fa8bd7/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L219)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Minor Can we add a log line here, will help in debugging, Thanks
</blockquote></details>

done

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
Screenshot 2022-10-27 at 11 45 19 PM
Screenshot 2022-10-27 at 11 38 41 PM

**Comment by kapil-harness** [comment]
Screenshot 2022-10-28 at 12 44 27 PM
Screenshot 2022-10-28 at 12 44 17 PM

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39323)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
