### PR TITLE
feat: [CDS-42393]: Resolve secret service variables before exporting

### PR DESCRIPTION
**Pull request by bojanmicovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36853)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36853)

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36853)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/36853#-NAUXzjI9MOychLUuDpW:-NAUXzjI9MOychLUuDpX:b6swyjs) ([raw file](https://github.com/harness/harness-core/blob/4c422bac984ff06168adec9c79a3643842368eaf/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L252)):*
> ```Java
>       return null;
>     }
>     Matcher matcher = Pattern.compile("\\<\\+secrets\\.getValue\\(\"(.*?)\"\\)").matcher(expression);
> ```

let's compile the patter once, have it static

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36853)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 237 at r2](https://reviewable.io/reviews/harness/harness-core/36853#-NAUZBwK8sFzjdL2QWRT:-NAUZBwK8sFzjdL2QWRU:btb2826) ([raw file](https://github.com/harness/harness-core/blob/4c422bac984ff06168adec9c79a3643842368eaf/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L237)):*
> ```Java
>     String projectIdentifier = AmbianceUtils.getProjectIdentifier(ambiance);
>     Secret secret =
>         ngSecretServiceV2.get(getIdentifierRef(extractIdentifier(value), accountId, orgIdentifier, projectIdentifier))
> ```

in case we cannot extract the identifier it will throw InvalidIdentifierException but actually the customer will have no idea which one is failing. Perhaps we can return optional here and if the identifier was found we fetch else we skip it.
Regarding the onElseThrow, let's include the id of secret in the exception.

**Comment by bojanmicovic** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/36853#-NAUXzjI9MOychLUuDpW:-NAZih6rDgcNcrBgioVt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c422bac984ff06168adec9c79a3643842368eaf/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L252)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

let's compile the patter once, have it static
</blockquote></details>

Done.

**Comment by bojanmicovic** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java` line 237 at r2](https://reviewable.io/reviews/harness/harness-core/36853#-NAUZBwK8sFzjdL2QWRT:-NAZij9I2G-Z_ZVhVSmu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4c422bac984ff06168adec9c79a3643842368eaf/125-cd-nextgen/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java#L237)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

in case we cannot extract the identifier it will throw InvalidIdentifierException but actually the customer will have no idea which one is failing. Perhaps we can return optional here and if the identifier was found we fetch else we skip it.
Regarding the onElseThrow, let's include the id of secret in the exception.
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36853)* status: :shipit: complete! ✓

**Pull request merged**
