### PR TITLE
fix: [SRM-11214]: Adding exception mapper for ServiceCallException and improving wrapping of exceptions.

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36170)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36170)

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36170)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/36170#-N97EwgyCz6VMoXpMkUb:-N97EwgzBd4ZeZVFnNNB:b-r08byg) ([raw file](https://github.com/harness/harness-core/blob/65d4a35a795aeffddc1eb328bb64a164b7e017c5/300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java#L56)):*
> ```Java
>     }
>     List<ResponseMessage> responseMessages = restResponse.getResponseMessages();
>     if (CollectionUtils.isNotEmpty(responseMessages)) {
> ```

use EmptyPredicate.isNotEmpty(). I think there's a pmd check which will force you to use that.

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36170)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/36170#-N97EwgyCz6VMoXpMkUb:-N9FeM-6-YTYrvz4Fihv:ba4zqi0) ([raw file](https://github.com/harness/harness-core/blob/65d4a35a795aeffddc1eb328bb64a164b7e017c5/300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java#L56)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

use EmptyPredicate.isNotEmpty(). I think there's a pmd check which will force you to use that. 
</blockquote></details>

I didnt see any check failures for this. Also is there any reason we want to use EmptyPredicate.isNotEmpty() when we have common library methods available?

**Review by praveensugavanam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36170)* status: :shipit: complete! ✓

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/36170#-N97EwgyCz6VMoXpMkUb:-N9az7S92LF_QLNWcYu0:b-j79ka5) ([raw file](https://github.com/harness/harness-core/blob/2e49464c6f693e830f37fef2f675d1675313edd6/300-cv-nextgen/src/main/java/io/harness/cvng/client/RequestExecutor.java#L56)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

I didnt see any check failures for this. Also is there any reason we want to use EmptyPredicate.isNotEmpty() when we have common library methods available?
</blockquote></details>

That's the convention we've used across the company code for a long time. This might be mostly for consistency point of view.

**Pull request merged**
