### PR TITLE
feat: [CDS-43504]: Service changes for Elastigroup NG

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)

### CODE REVIEW

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Comment by piyush-bhuwalka** [comment]
trigger messagecheck

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 21 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 201 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmD0Lo8fVxDvM3Q0vo:-NEmD0Lo8fVxDvM3Q0vp:b-7uhzbb) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L201)):*
> ```Java
>               .uuid("elastigroup-settings-" + UUIDGenerator.generateUuid())
>               .stepType(ElastigroupServiceSettingsStep.STEP_TYPE)
>               .name(PlanCreatorConstants.CONNECTION_STRINGS)
> ```

Create the new constant and name for elasticsearch settings node. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmE12FC6AWh-mdAsyO:-NEmE12FC6AWh-mdAsyP:bwh8e5f) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java#L104)):*
> ```Java
>   }
> 
>   private void saveExecutionLog(NGLogCallback logCallback, String line) {
> ```

I think we have a helper with a lot of useful save execution logs methods, just reuse it. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmGZyS2h3KsPUhgpr_:-NEmGZyS2h3KsPUhgpra:bygalq5) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L72)):*
> ```Java
>     if (HARNESS_STORE_TYPE.equals(storeKind)) {
>       validateSettingsFileRefs((HarnessStore) storeConfig, ambiance, entityType);
>     } else if (!storeKind.equals(ManifestStoreType.INLINE)) {
> ```

Can we be more specific and concrete here,  what store kind do we expect here? 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmIjWz7agKZIdjKpEa:-NEmIjWz7agKZIdjKpEb:b-x0e9yj) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L77)):*
> ```Java
>   }
> 
>   private void validateSettingsFileRefs(HarnessStore harnessStore, Ambiance ambiance, String entityType) {
> ```

What I suggest here is moving validation logic to two separate methods one for secrets and another one for files.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmJ2Ge7Nrqu-woGqR5:-NEmJ2Ge7Nrqu-woGqR6:b-chdsjj) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L98)):*
> ```Java
>             format("Cannot find any file for %s, store kind: %s", entityType, harnessStore.getKind()));
>       }
>       if (fileReferences.size() > 1) {
> ```

We could have more files stored in Harness File store as well as secrets on the secret manager, 
we just limited it for config files because it was the requirement from the PM. It might be that it is not the case for you. If yes, this is ok.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ElastigroupServiceSpec.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmFmf4BrUlXxmvK_Ds:-NEmFmf4BrUlXxmvK_Dt:b-39c0fw) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ElastigroupServiceSpec.java#L76)):*
> ```Java
>     if (EmptyPredicate.isNotEmpty(configFiles)) {
>       configFiles.forEach(configFile -> children.add("configFiles", configFile));
>     }
> ```

StartupScriptConfiguration implements Visitable and you added StartupScriptConfigurationVisitorHelper as a helper visitor class, hence add as children here.

**Comment by piyush-bhuwalka** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmGZyS2h3KsPUhgpr_:-NEnt0k8BVh2BbQ2HcjL:bp6vlul) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L72)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Can we be more specific and concrete here,  what store kind do we expect here? 
</blockquote></details>

IN AzureHelperService, we have 

if (HARNESS_STORE_TYPE.equals(storeKind)) {
      validateSettingsFileRefs((HarnessStore) storeConfig, ambiance, entityType);
    } else {
      validateSettingsConnectorByRef(storeConfig, ambiance, entityType);
    }

and inside validateSettingsConnectorByRef method, we check 

if (ParameterField.isNull(storeConfig.getConnectorReference())) {
      throw new InvalidRequestException(
          format("Connector ref field not present in %S, store kind: %s ", entityType, storeConfig.getKind()));
    }

So it would always throw error for INLINE store. Is inline store not supported for azure ?

**Comment by piyush-bhuwalka** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ElastigroupServiceSpec.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmFmf4BrUlXxmvK_Ds:-NEntrpr9LzNWsgt33MY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ElastigroupServiceSpec.java#L76)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

StartupScriptConfiguration implements Visitable and you added StartupScriptConfigurationVisitorHelper as a helper visitor class, hence add as children here.
</blockquote></details>

Done

**Comment by piyush-bhuwalka** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 98 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmJ2Ge7Nrqu-woGqR5:-NEntvdW0PKvHjURB2wv:b7o7v3o) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L98)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

We could have more files stored in Harness File store as well as secrets on the secret manager, 
we just limited it for config files because it was the requirement from the PM. It might be that it is not the case for you. If yes, this is ok.
</blockquote></details>

For now, it should be good

**Comment by piyush-bhuwalka** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 77 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmIjWz7agKZIdjKpEa:-NEnvDb1BBF84DpCJAm-:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L77)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

What I suggest here is moving validation logic to two separate methods one for secrets and another one for files.
</blockquote></details>

Done

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmE12FC6AWh-mdAsyO:-NEnv_rMCuTg2LSOnJL5:b-pu1f4z) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java#L104)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I think we have a helper with a lot of useful save execution logs methods, just reuse it. 
</blockquote></details>

Did not find a similar method. Keeping this as it is for the time being

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinitionType.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/38780#-NEocv8d67KDODRBgs77:-NEocv8eCohzcyZwSK4h:bl1ag2v) ([raw file](https://github.com/harness/harness-core/blob/cfa91596fb4e5dc551d501e0d70ee3053bc96b11/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinitionType.java#L65)):*
> ```Java
> 
>   @JsonProperty(ServiceSpecType.ELASTIGROUP)
>   ELASTIGROUP("ELASTIGROUP",
> ```

Can we use - ServiceSpecType.ELASTIGROUP instead of "ELASTIGROUP". (It shouldn't be all CAPS)



_Code quote:_
```Java
ServiceSpecType.ELASTIGROUP
```

**Comment by piyush-bhuwalka** [comment]
trigger codebasehash

**Comment by arvind-choudhary-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmGZyS2h3KsPUhgpr_:-NEomSJC8S2PcsJS59lp:b-t4nrtj) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L72)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I am not sure what Azure swimline considers as the INLINE store and whether it is supported or not. Here you should consider your use cases. 
</blockquote></details>

@piyush-bhuwalka -- we want to support only Inline and Harness Store for now. For other, can throw -- not implemented.

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 18 of 21 files at r1, 2 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: 1. unresolved discussions.

**Comment by piyush-bhuwalka** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/38780#-NEodjGiBTC0dMZOiXIK:-NEp8m-a7R2MfsCqrZW8:b15842j) ([raw file](https://github.com/harness/harness-core/blob/cfa91596fb4e5dc551d501e0d70ee3053bc96b11/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java#L104)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Can use LogCallbackUtils
</blockquote></details>

Keeping this as it was for now. If needed would change it later

**Review by piyush-bhuwalka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: 3. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/38780#-NEmGZyS2h3KsPUhgpr_:-NEp8eyZ6QQOEuOGBT2T:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/3c56fa746a34c313592a68b2a04bc3c3c61a98f6/127-cd-nextgen-entities/src/main/java/io/harness/cdng/elastigroup/ElastigroupHelperService.java#L72)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

@piyush-bhuwalka -- we want to support only Inline and Harness Store for now. For other, can throw -- not implemented.
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinitionType.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/38780#-NEocv8d67KDODRBgs77:-NEp8gfSEDPSMGYb-AF2:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/cfa91596fb4e5dc551d501e0d70ee3053bc96b11/127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinitionType.java#L65)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Can we use - ServiceSpecType.ELASTIGROUP instead of "ELASTIGROUP". (It shouldn't be all CAPS)
</blockquote></details>

Done

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java` line 104 at r3](https://reviewable.io/reviews/harness/harness-core/38780#-NEodjGiBTC0dMZOiXIK:-NEtqk59-z8JdCG9KYRy:bdove0k) ([raw file](https://github.com/harness/harness-core/blob/cfa91596fb4e5dc551d501e0d70ee3053bc96b11/125-cd-nextgen/src/main/java/io/harness/cdng/elastigroup/ElastigroupServiceSettingsStep.java#L104)):*
<details><summary><i>Previously, piyush-bhuwalka wrote…</i></summary><blockquote>

Keeping this as it was for now. If needed would change it later
</blockquote></details>

Let's change this in next PR and shall use similar strategy i other steps.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: 1. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38780)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
