### PR TITLE
fix: [CDS-52523]: Populate artifact.image variable for GAR artifacts

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
This PR makes the "Service" step populate the artifact.image variable in a NG CD stage.
From Google Artifact Registry docs, this is the format of the image path:
image
https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43590)

### CODE REVIEW

**Comment by vcalasansh** [comment]
retrigger smartchecks

**Comment by vcalasansh** [comment]
trigger smartchecks

**Comment by vcalasansh** [comment]
trigger gitleaks

**Comment by vcalasansh** [comment]
trigger smartchecks

**Comment by vcalasansh** [comment]
trigger smartchecks

**Comment by vcalasansh** [comment]
trigger messagecheck

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43590)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java` line 247 at r2](https://reviewable.io/reviews/harness/harness-core/43590#-NNmSes9DjHtUEWLMzaa:-NNmSes9DjHtUEWLMzab:b-exnhax) ([raw file](https://github.com/harness/harness-core/blob/2bf5389e1c500f13a459f2c29716875eef89b5e0/960-api-services/src/main/java/io/harness/artifacts/gar/service/GARApiServiceImpl.java#L247)):*
> ```Java
> 
>   private String getImageName(GarInternalConfig garinternalConfig, String tag) {
>     return garinternalConfig.getRegion() + '-' + "docker.pkg.dev/" + garinternalConfig.getProject() + "/"
> ```

Would the path be same for the SMP customers  if GAR supports on-prem setup?

**Comment by vcalasansh** [comment]
trigger tin2

**Review by sribalij — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43590)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by lasdox — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43590)* status: Some of the checks are too old.

**Review by lasdox — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43590)* status: :shipit: complete! ✓

**Pull request merged**
