### PR TITLE
feat: [CDB-76]: increase timeout before mongo client stops trying to reconnect

### PR DESCRIPTION
**Pull request by sean-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31163)

### CODE REVIEW

**Comment by sean-harness** [comment]
trigger messagecheck

**Comment by gunascode** [comment]
___
*[110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java, line 88 at r1](https://reviewable.io/reviews/harness/harness-core/31163#-MxGEhwD3RupDACBfj0A:-MxGEhwD3RupDACBfj0B:b-18kkfh) ([raw file](https://github.com/harness/harness-core/blob/e0bd08790da0ec43cc612db9c010be42a9099d72/110-change-data-capture/src/main/java/io/harness/changestreamsframework/ChangeTracker.java#L88)):*
> ```Java
>     return new MongoClientURI(mongoClientUrl,
>         MongoClientOptions.builder(MongoModule.getDefaultMongoClientOptions(mongoConfig))
>             .serverSelectionTimeout(86400000)
> ```

This needs to be externalized

**Comment by sean-harness** [comment]
retrigger coverage

**Comment by sean-harness** [comment]
retrigger coverage

**Comment by sean-harness** [comment]
trigger messagecheck

**Pull request merged**
