### PR TITLE
fix: [CDS-68993]: Set imagePullSecret primary when Artfiact Resource is Primary

### PR DESCRIPTION
**Pull request by sarthakkasat**
## Describe your changes
When changing the identifier of Artifact Resource from primary to identifier provided, it was also changing he identifier for imagePullSecret which was causing the the pipeline to fail, so we are changing the identifier to primary in getArtifactKey as this would update the identifier for imagePullSecret and does not impact other uses of this method.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49617)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/49617#-NYq8nho4vF1gw5Yck3b:-NYq8nho4vF1gw5Yck3c:b-tb7oq6) ([raw file](https://github.com/harness/harness-core/blob/39336b1310578e8829bfe1993f8d8a4ec84c86cd/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L68)):*
> ```Java
>       + " connectorRef: %s%n";
> 
>   public String getArtifactKey(ArtifactConfig artifactConfig) {
> ```

lets write UT for this

**Review by sarthakkasat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49617)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/49617#-NYq8nho4vF1gw5Yck3b:-NYrD_QT2_YnYGFJ1nu6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/39336b1310578e8829bfe1993f8d8a4ec84c86cd/127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java#L68)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets write UT for this
</blockquote></details>

Done.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49617)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — DISMISSED** [review]

**Comment by sarthakkasat** [comment]
trigger uts

**Comment by sarthakkasat** [comment]
trigger review

**Comment by sarthakkasat** [comment]
trigger ut0

**Comment by sarthakkasat** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49617)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]
lgtm

**Comment by sarthakkasat** [comment]
trigger review

**Pull request merged**
