### PR TITLE
feat: [PL-32708]: Added support to set expiration date for azure keyvault secrets

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
This is an enhancement to azure key vault. Any secret created in azure key vault can have an expiration date associated with it. When creating a secret via harness, support to set this date has also been added. This is done by taking expiration date time as part of secret metadata.

Testing:
1. Tested by creating a secret with expiration date. The expiry date is reflected for secret azure key vault as well.
2. Tested updating expiration date
    1. Along with changing of secret value (update flow)
    2. Without any change other than changing expiry date. (rename flow)
3. Tested create and update flow of other secret managers (impact testing)
4. Tested with previous version of delegate.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47488)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 338 at r2](https://reviewable.io/reviews/harness/harness-core/47488#-NUwNxqZ6vTKeKJE9RVO:-NUwNxqZ6vTKeKJE9RVP:b8wc4cs) ([raw file](https://github.com/harness/harness-core/blob/b6559170e351432feaa7b607d9b101e16be511c4/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L338)):*
> ```Java
>               .value(Boolean.TRUE.toString())
>               .additionalMetadata(AdditionalMetadata.builder()
>                                       .value(EXPIRES_ON, Instant.now().plus(5, ChronoUnit.HOURS).toEpochMilli())
> ```

Can we reduce this expiry? Why 5 hours?

**Review by piyush-harness — DISMISSED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47488)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by nishantsaini20** [comment]
trigger uts

**Comment by nishantsaini20** [comment]
trigger uts

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47488)* status: 9 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java` line 338 at r2](https://reviewable.io/reviews/harness/harness-core/47488#-NUwNxqZ6vTKeKJE9RVO:-NUzzGPT3Sm9OU9Ncx1A:bpgaafr) ([raw file](https://github.com/harness/harness-core/blob/b6559170e351432feaa7b607d9b101e16be511c4/931-encryption-service/src/java/io/harness/encryptors/clients/AzureVaultEncryptor.java#L338)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Can we reduce this expiry? Why 5 hours?
</blockquote></details>

Reduced to 1 hr.

**Comment by nishantsaini20** [comment]
trigger ut1

**Comment by nishantsaini20** [comment]
trigger ut1

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47488)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
