### PR TITLE
feat: [CDS-40080]: Added azure infra step integration with command step

### PR DESCRIPTION
**Pull request by acasian-harness**
## Describe your changes

- Added new infrastructure step that will have the ability to execute delegate tasks
- New infrastructure step is controlled by infra type, atm only available for Azure infra for both ssh/winrm service types
- Added LIST_HOSTS delegate subtask to existing Azure delegate task.
- Fixed LIST_HOSTS to consider the public ip address instead of hostname
- Exposed host to Command step to have control from yaml/ui
- Removed old unnecessary code from Command step plan creator since the new matrix/looping strategy will take care of iterating through hosts.
- Re-use the infra delegate config from sweeping output (published at infra step) instead of building it twice.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/35755#-N7zK3LCCxX85khQiHd5:-N7zK3LCCxX85khQiHd6:bdaqdfk) ([raw file](https://github.com/harness/harness-core/blob/daa255c3a13df13ce4dde9814b4c3c4d54c0698e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L74)):*
> ```Java
>   public PlanNode getInfraStepPlanNode(Infrastructure pipelineInfrastructure) {
>     if (InfrastructureKind.SSH_WINRM_AZURE.equals(pipelineInfrastructure.getKind())) {
>       return PlanNode.builder()
> ```

Should we extract out the common fields in a builder variable?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 31 of 39 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/35755#-N7zK3LCCxX85khQiHd5:-N899EKX1u17HgTgnCpn:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/daa255c3a13df13ce4dde9814b4c3c4d54c0698e/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L74)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Should we extract out the common fields in a builder variable?
</blockquote></details>

Done

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 20 of 39 files at r1, 3 of 8 files at r2, 4 of 15 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755#-:-N8KEdX1Ei5R_jz5Ohwx:bnfp4nl)* status: 1 change requests. 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8KCW0_BzebyTmZLk9s:-N8KCW0_BzebyTmZLk9t:blhx3hr) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L90)):*
> ```Java
>   }
> 
>   private boolean isTaskStep(Infrastructure pipelineInfrastructure) {
> ```

Minor - this could be done later when we start implementing getting hosts for AWS - what I suggest here is to provide one more level of abstraction, it means having   InfrastructureTaskExecutableStep as an abstract class and putting common things there, like calling validation, publishers... After that having more classes that extend that class and in our case having InfrastructureSSHWinRmAzureTaskExecutableStep new class where we will have the logic for Azure. A similar should be done for AWS. 

And, here in this method having logic like,  
if (InfrastructureKind.SSH_WINRM_AZURE.equals(pipelineInfrastructure.getKind()) return InfrastructureSSHWinRmAzureTaskExecutableStep.STEP_TYPE and so on. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8K4rIZ2w2IBHzwC0qZ:-N8K4rIZ2w2IBHzwC0q_:b-6ulx8n) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L272)):*
> ```Java
>   private TaskRequest buildSshTaskRequest(InfrastructureOutcome infrastructureOutcome, Ambiance ambiance) {
>     SshInfraDelegateConfig sshInfraDelegateConfig =
>         publishSshInfraDelegateConfigOutput(infrastructureOutcome, ambiance);
> ```

Minor - question - should we publish delegate config after getting a successful task response? 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 319 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8K3EjK9RvKtSo2-q1N:-N8K3EjK9RvKtSo2-q1O:b6vykap) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L319)):*
> ```Java
>             .async(true)
>             .taskType(TaskType.NG_AZURE_TASK.name())
>             .timeout(StepUtils.getTimeoutMillis(ParameterField.createValueField("10m"), DEFAULT_TIMEOUT))
> ```

Minor - 10m could be constant or reuse DEFAULT_TIMEOUT.

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 5 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 90 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8KCW0_BzebyTmZLk9s:-N8Kk78ZBnItsVKgAHSW:b8u6g8h) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L90)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - this could be done later when we start implementing getting hosts for AWS - what I suggest here is to provide one more level of abstraction, it means having   InfrastructureTaskExecutableStep as an abstract class and putting common things there, like calling validation, publishers... After that having more classes that extend that class and in our case having InfrastructureSSHWinRmAzureTaskExecutableStep new class where we will have the logic for Azure. A similar should be done for AWS. 

And, here in this method having logic like,  
if (InfrastructureKind.SSH_WINRM_AZURE.equals(pipelineInfrastructure.getKind()) return InfrastructureSSHWinRmAzureTaskExecutableStep.STEP_TYPE and so on. 
</blockquote></details>

i was thinking about that also, but in the end we would maintain infra steps per infra that we provide. Also the code for azure and aws infra is very simillar so we would end up doing duplication of code. Beside this, each step needs minor fix on UI (logo of the step).
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 272 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8K4rIZ2w2IBHzwC0qZ:-N8KkZD56KX3M_wBMghC:b-cjry6q) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L272)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - question - should we publish delegate config after getting a successful task response? 
</blockquote></details>

We need delegate config when we build the task, if we will publish after - it will end up in 2 invocations, which i tend to remove from performance consideration. Also i removed the same infra delegate config creation from step, now it will be consumed from sweeping output.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 319 at r4](https://reviewable.io/reviews/harness/harness-core/35755#-N8K3EjK9RvKtSo2-q1N:-N8KkxIO0gb2bxeTe-s9:budzpkh) ([raw file](https://github.com/harness/harness-core/blob/0acf914ee8d63a9c5df25f7292ad780a58627713/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L319)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

Minor - 10m could be constant or reuse DEFAULT_TIMEOUT.  
</blockquote></details>

Good point, now i've put a hardcoded value, but will speak to Meenakshi if it makes sense to add a timeout input on the infra page also, if not, will have default timeout and that's it. But that can be clarified later.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755#-:-N8KsYnQ3QIMyz4fCGhc:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/35755#-N8NKCvO0s5TW6J9eSB3:-N8NKCvP0yz94UA1Ki40:b-mpsqn1) ([raw file](https://github.com/harness/harness-core/blob/5f077b2ba3220a0b4731c0dd806b13c48da8168e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L342)):*
> ```Java
>     AzureTaskParams azureTaskParamsTaskParams =
>         AzureTaskParams.builder()
>             .azureTaskType(AzureTaskType.LIST_HOSTS)
> ```

This delegate task should fail in case we start to call from Manager with older delegates.

**Review by acasian-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 1 change requests. 2. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 342 at r5](https://reviewable.io/reviews/harness/harness-core/35755#-N8NKCvO0s5TW6J9eSB3:-N8NLFlB1Fyn9JxiHtLx:b-sqx4x8) ([raw file](https://github.com/harness/harness-core/blob/5f077b2ba3220a0b4731c0dd806b13c48da8168e/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L342)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

This delegate task should fail in case we start to call from Manager with older delegates.
</blockquote></details>

correct, `LIST_HOSTS` is not used by any customer, it will be used once we will release SSH/WinRM parity

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 19 of 39 files at r1, 2 of 8 files at r2, 4 of 15 files at r3, 11 of 14 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 1 change requests. 1. unresolved discussions.

**Review by arvind-choudhary-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: 1 change requests. 1. unresolved discussions.

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 4 of 15 files at r3, 11 of 14 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35755)* status: :shipit: complete! ✓

**Pull request merged**
