### PR TITLE
[feat]: [CDS-73311]: Provide the logBaseKey for each node in the execution graph for Download logs feature

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Provide the logBaseKey for each node in the execution graph for Download logs feature.

For downloading the logs of any step/Stage/Pipeline or any intermediate node, UI need to know the base logKey for those nodes(Without command-units). Then UI sends this to Log-service then it will zip all the logs belonging to keys with the given logBaseKey as prefix.

Issue: Right now the steps add the logKeys in the executable responses. But Sometimes steps has multiple logKeys. And logKeys are not available for the non-leaf nodes. So Adding this logKey for each node will help the UI and customer to download the logs for any node(Leaf or parent).

Changes: Adding an extra key in the nodeMap entries `logBaseKey` that will be the value of logKey for that node. 

Impact: Adding one more field in the nodeMap entries. So i see no impact of this.

NodeMap entries in the Graph API response:
```{
  "uuid": "9ONPHi_jSzCuecWfFfbSJA",
  "setupId": "3N3JAPX-SMKir9_etI4NRg",
  "name": "ShellScript_1_9",
  "identifier": "ShellScript_1_9",
  "baseFqn": "pipeline.stages.cs0.spec.execution.steps.ShellScript_1_9",
  "outcomes": {},
  "stepParameters": null,
  "startTs": null,
  "endTs": null,
  "stepType": "ShellScript",
  "status": "Queued",
  "failureInfo": null,
  "skipInfo": null,
  "nodeRunInfo": null,
  "executableResponses": [],
  "unitProgresses": [],
  "progressData": null,
  "delegateInfoList": [],
  "interruptHistories": [],
  "stepDetails": null,
  "strategyMetadata": {
    "currentiteration": 9,
    "totaliterations": 10
  },
  "executionInputConfigured": false,
  "logBaseKey": "accountId:kmpySmUISimoRrJL6NL73w/orgId:default/projectId:Brijesh/pipelineId:child/runSequence:77/level0:pipeline/level1:stages/level2:cs0/level3:spec/level4:execution/level5:steps/level6:ShellScript_1/level7:ShellScript_1_9"
}```


```{
  "uuid": "TvW0gS8QS--XNI7fY1Q-OQ",
  "setupId": "3N3JAPX-SMKir9_etI4NRg",
  "name": "ShellScript_1_0",
  "identifier": "ShellScript_1_0",
  "baseFqn": "pipeline.stages.cs0.spec.execution.steps.ShellScript_1_0",
  "outcomes": {},
  "stepParameters": {
    "identifier": "ShellScript_1_0",
    "name": "ShellScript_1_0",
    "timeout": "10s",
    "failureStrategies": [],
    "type": "ShellScript",
    "spec": {
      "outputVariables": {},
      "environmentVariables": {},
      "shell": "Bash",
      "source": {
        "type": "Inline",
        "spec": {
          "script": "sleep 20"
        }
      },
      "onDelegate": true
    }
  },
  "startTs": 1688104490553,
  "endTs": null,
  "stepType": "ShellScript",
  "status": "Running",
  "failureInfo": null,
  "skipInfo": null,
  "nodeRunInfo": {
    "whenCondition": "<+OnStageSuccess>",
    "evaluatedCondition": true,
    "expressions": [
      {
        "expression": "OnStageSuccess",
        "expressionValue": "true",
        "count": 1
      }
    ]
  },
  "executableResponses": [],
  "unitProgresses": [],
  "progressData": null,
  "delegateInfoList": [],
  "interruptHistories": [],
  "stepDetails": null,
  "strategyMetadata": {
    "currentiteration": 0,
    "totaliterations": 10
  },
  "executionInputConfigured": false,
  "logBaseKey": "accountId:kmpySmUISimoRrJL6NL73w/orgId:default/projectId:Brijesh/pipelineId:child/runSequence:77/level0:pipeline/level1:stages/level2:cs0/level3:spec/level4:execution/level5:steps/level6:ShellScript_1/level7:ShellScript_1_0"
}```


## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions


## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

<!-- Reviewable:start -->
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/49918)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49918)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
