### PR TITLE
[feat]: [CDS-54739]: Add API Client for EKS Infra

### PR DESCRIPTION
**Pull request by lovish1999**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)

### CODE REVIEW

**Review by abhinavsingh1196 — CHANGES_REQUESTED** [review]
Please check sonar issues as well

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589#-:-NRHqYrkC7Z7tJBEA1nq:bbpf730)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtG6T0B80LkzZcOyC:-NRHtG6T0B80LkzZcOyD:baeqbh2) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L103)):*
> ```Java
>     }
>     if (kubernetesConfig.getServiceAccountTokenSupplier() != null) {
>       serviceAccountTokenAuthentication(kubernetesConfig, clientBuilder);
> ```

nit: can provide a better name here, like `addSATokenAuthentication`
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHt4KD398OWtUg2GgN:-NRHt4KD398OWtUg2GgO:b-v1usau) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L116)):*
> ```Java
>       //      AzureTokenAuthentication(kubernetesConfig.getAzureConfig().getAadIdToken()));
>       clientBuilder.setAuthentication(new AccessTokenAuthentication(kubernetesConfig.getAzureConfig().getAadIdToken()));
>     } else if (kubernetesConfig.getAuthType() == EXEC_OAUTH) {
> ```

EXEC_OAUTH is not only for EKS. 
Is the base branch not rebased with develop? I don't see changes made by @GoelPratyush99 
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtXBd3y9tO0FAEfuZ:-NRHtXBe6mOoJLTDRqa4:b-rwciqj) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L144)):*
> ```Java
> 
>   private static void eksAuthentication(KubernetesConfig kubernetesConfig, ClientBuilder clientBuilder) {
>     if (kubernetesConfig.getExec().getCommand() == EKS_AUTH_PLUGIN_BINARY) {
> ```

this condition can be out of this method, since its specific to EKS already
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtjCl7_LhERCFYrwz:-NRHtjCl7_LhERCFYrx-:b-stuyhj) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L146)):*
> ```Java
>     if (kubernetesConfig.getExec().getCommand() == EKS_AUTH_PLUGIN_BINARY) {
>       String kubeConfigString = generateExecFormatKubeconfig(kubernetesConfig);
>       KubeConfig kubeConfig = KubeConfig.loadKubeConfig(new StringReader(kubeConfigString));
> ```

could this method throw an exception? we could add this to try block as well
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 150 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtuGV1WIslSp7juej:-NRHtuGV1WIslSp7juek:btun4y4) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L150)):*
> ```Java
>         clientBuilder.setAuthentication(new KubeconfigAuthentication(kubeConfig));
>       } catch (IOException e) {
>         throw new RuntimeException(e);
> ```

IOException is thrown only when trying to parse ClientCert/ClientKey. We aren't using ClientCert/ClientKey for EKS auth
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHuoFN3e85rZ-LrCDV:-NRHuoFO24vW683XUiR1:b-rmgw80) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L175)):*
> ```Java
>   }
> 
>   public static String generateExecFormatKubeconfig(KubernetesConfig config) {
> ```

Is the base branch not rebased with develop? I don't see changes made by @GoelPratyush99 
These changes are already done

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)* status: 1 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): k8s-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRI9KBYCOu_LX9Rt4-1:-NRI9KBYCOu_LX9Rt4-2:b-chc2kw) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L116)):*
> ```Java
>       //      AzureTokenAuthentication(kubernetesConfig.getAzureConfig().getAadIdToken()));
>       clientBuilder.setAuthentication(new AccessTokenAuthentication(kubernetesConfig.getAzureConfig().getAadIdToken()));
>     } else if (kubernetesConfig.getAuthType() == EXEC_OAUTH) {
> ```

This condition should be configurable in KubernetesConfig, either enum or boolean up to you
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHuoFN3e85rZ-LrCDV:-NRI9P_q9qRuwsomG80e:b-ttxgd4) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L175)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

Is the base branch not rebased with develop? I don't see changes made by @GoelPratyush99 
These changes are already done 
</blockquote></details>

We should have a common class for both use cases

**Review by lovish1999 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)* status: 1 file(s) to review. 2 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtG6T0B80LkzZcOyC:-NRWvQVT-VkVKlQyWm8I:b-9g4ua5) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L103)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

nit: can provide a better name here, like `addSATokenAuthentication`
</blockquote></details>

ok. changed. 
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRI9KBYCOu_LX9Rt4-1:-NRX0eBQ8QcEwh_AyZ5Q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L116)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

This condition should be configurable in KubernetesConfig, either enum or boolean up to you
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 116 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHt4KD398OWtUg2GgN:-NRX0ekF4JBTvv9QR48q:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L116)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

EXEC_OAUTH is not only for EKS. 
Is the base branch not rebased with develop? I don't see changes made by @GoelPratyush99 
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtXBd3y9tO0FAEfuZ:-NRX0bnl4htiA88Qhfig:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L144)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

this condition can be out of this method, since its specific to EKS already
</blockquote></details>

ok
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 146 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtjCl7_LhERCFYrwz:-NRWzpVP2-Knt4fNUiQr:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L146)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

could this method throw an exception? we could add this to try block as well
</blockquote></details>

ok
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 150 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtuGV1WIslSp7juej:-NRWvqCi6A54UXJddk16:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L150)):*
<details><summary><i>Previously, abhinavsingh1196 (Abhinav Singh) wrote…</i></summary><blockquote>

IOException is thrown only when trying to parse ClientCert/ClientKey. We aren't using ClientCert/ClientKey for EKS auth
</blockquote></details>

ok
___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 175 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHuoFN3e85rZ-LrCDV:-NRWznMG1V-9fgp3jMC_:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L175)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We should have a common class for both use cases
</blockquote></details>

ok

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team. 

___
*[`960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java` line 144 at r2](https://reviewable.io/reviews/harness/harness-core/45589#-NRHtXBd3y9tO0FAEfuZ:-NRXT2_Q4RZ04fJ4ErWp:bfnucki) ([raw file](https://github.com/harness/harness-core/blob/84f8c66e7b5a7648e5b0933f8e64c880d30986cc/960-api-services/src/main/java/io/harness/k8s/apiclient/ApiClientFactoryImpl.java#L144)):*
<details><summary><i>Previously, lovish1999 (Lovish Bansal) wrote…</i></summary><blockquote>

ok
</blockquote></details>

This condition shouldn't be required

**Review by abosii-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)* status: 7 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained. Waiting on team(s): del-team.

**Review by abhinavsingh1196 — APPROVED** [review]
> Reviewed 4 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45589)* status: Waiting on team(s): del-team.

**Pull request merged**
