### PR TITLE
fix: [PIE-7134]: update plan status in resume only when current status isn't waiting

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

update plan status in resume only when current status isn't waiting

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41814)

### CODE REVIEW

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41814)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/41814#-NJn4Adg8qcaaaCMJinr:-NJn4Adg8qcaaaCMJins:b3us6ot) ([raw file](https://github.com/harness/harness-core/blob/8fde649c3cd23fd90bb4df5cd78701d50acd1f46/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java#L94)):*
> ```Java
> 
>   @Override
>   public PlanExecution updatePlanStatus(
> ```

Can we extract common code to a function?

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41814)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/41814#-NJn4Adg8qcaaaCMJinr:-NJnA-VWDhtQKuoUeUq_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8fde649c3cd23fd90bb4df5cd78701d50acd1f46/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/PlanExecutionServiceImpl.java#L94)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we extract common code to a function?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41814)* status: :shipit: complete! ✓

**Pull request merged**
