### PR TITLE
[fix]: [PL-30065]: Enabling Job to create Default User Groups or add any user which has not already been added to User Group.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Enabling Job to create Default User Groups.
https://docs.harness.io/article/n3cel7d8re-harness-default-user-groups

- This Job creates Default User Group(UG) in scope where it doesn't exist and adds all the users into UG or if Default UG already exists then it adds any user which has not already been added to User Group.
- This helps with following failure scenarios:
   1. When Scope entity ie. Organization, Project gets created but corresponding User Group is not created.
  2. When user is added to the scope and if is not added to Default UG due to failure in User Membership addition event consumption.

- Not assigning Account Viewer - All Account resources Role binding anymore since we had already rolled out this feature earlier and made Account Viewer - All Account resources Role binding deletable there is possibility that customer might have removed the same Role binding. This will ensure no change in system behavior.
- Also reducing the frequency of Job run from 12 hours to 24 hours.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41068)

### CODE REVIEW

**Review by reetika04 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41068)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Comment by Jimit09Gandhi** [comment]
trigger messagecheck

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41068)* status: :shipit: complete! ✓

**Pull request merged**
