### PR TITLE
feat:[CDS-77595]: added accountId queryParam in getApprovals

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- add accountId query param in getApprovals API call (internal API call) used to view approval details.
- Reason: FE needs accountId query param to use promise version of API call
- Pipeline swagger will be tested for backward compatibility in FE
- Example request: 
```
curl --location 'https://localhost:8181/pipeline/api/approvals/X8Inb4cZSqaUAo9b2njEbA?routingId=kmpySmUISimoRrJL6NL73w&accountIdentifier=kmpySmUISimoRrJL6NL73w' \
```
- Testing: 
a. case with accountId absent: 
Screenshot 2023-08-25 at 12 14 43 PM
b. case with incorrect accountId: 
Screenshot 2023-08-25 at 12 15 14 PM
c. case with correct accountId:
Screenshot 2023-08-25 at 12 15 42 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52055)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52055)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by vivekkarnatiharness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/approval/resources/ApprovalResource.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/52055#-NcuUqAt3T4YAj9rX5Qe:-NcuUqAt3T4YAj9rX5Qf:b-htci55) ([raw file](https://github.com/harness/harness-core/blob/e43e6932c7d35fd8c857e858082c91c2092ce8ae/pipeline-service/contracts/src/main/java/io/harness/pms/approval/resources/ApprovalResource.java#L97)):*
> ```Java
>                           "approvalInstanceId") String approvalInstanceId,
>       @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @Parameter(
>           description = PipelineResourceConstants.ACCOUNT_PARAM_MESSAGE) @AccountIdentifier String accountId);
> ```

Is this a required field? If not, I think we should add some default value for this field right?.

**Comment by naman-goenka** [comment]
> _[`pipeline-service/contracts/src/main/java/io/harness/pms/approval/resources/ApprovalResource.java` line 97 at r2](https://reviewable.io/reviews/harness/harness-core/52055#-NcuUqAt3T4YAj9rX5Qe:-NcuUqAt3T4YAj9rX5Qf:b-htci55) ([raw file](https://github.com/harness/harness-core/blob/e43e6932c7d35fd8c857e858082c91c2092ce8ae/pipeline-service/contracts/src/main/java/io/harness/pms/approval/resources/ApprovalResource.java#L97)):_
> 
> > ```java
> >                           "approvalInstanceId") String approvalInstanceId,
> >       @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @Parameter(
> >           description = PipelineResourceConstants.ACCOUNT_PARAM_MESSAGE) @AccountIdentifier String accountId);
> > ```
> 
> Is this a required field? If not, I think we should add some default value for this field right?.

AccountId is optional query param being added for FE. 
Behaviour -> accountId is not present -> current behaviour
                  -> if accountId is present -> match it against instance's accountId
Default value shouldn't be required here.

**Review by vivekkarnatiharness — APPROVED** [review]

**Comment by naman-goenka** [comment]
trigger review

**Comment by naman-goenka** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52055)* status: Some of the checks are too old.

**Pull request merged**
