### PR TITLE
fix: [DEL-4512]: Keep PT calls sync

### PR DESCRIPTION
**Pull request by jennyjames21**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35673)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35673)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java` line 103 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niH3v6ixgbDMEmRio:-N7niH3v6ixgbDMEmRip:bcdn65g) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java#L103)):*
> ```Java
>       if (response != null && !response.isSuccessful()) {
>         String errorResponse = response.errorBody().string();
>         int errorCode = response.code();
> ```

minor nit: make it final



_Code quote:_
```Java
        String errorResponse = response.errorBody().string();
        int errorCode = response.code();
```
___
*[`420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niEwH68S_AK9WMw2u:-N7niEwH68S_AK9WMw2v:b32w21) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java#L104)):*
> ```Java
>         String errorResponse = response.errorBody().string();
>         int errorCode = response.code();
>         log.warn("TP:Received Error {} Response: {}", errorCode, errorResponse);
> ```

PT



_Code quote:_
```Java
TP
```
___
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niY9k0MFqmwC1cGki:-N7niY9k0MFqmwC1cGkj:b9s30tf) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L52)):*
> ```Java
>       if (response != null && response.getPerpetualTaskContext() != null) {
>         PerpetualTaskExecutionContext perpetualTaskExecutionContext = response.getPerpetualTaskContext();
>         log.info("PT Context params: {}", perpetualTaskExecutionContext);
> ```

log.debug ?



_Code quote:_
```Java
log.info
```
___
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7nijT430_I89Eb5zQI:-N7nijT430_I89Eb5zQJ:b30sfgz) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L88)):*
> ```Java
>   }
> 
>   private <T> T executeRestCall(Call<T> call) throws IOException {
> ```

We can move this function at common place and use it, instead of repeating the same code at two places.



_Code quote:_
```Java
executeRestCall
```

**Comment by jennyjames21** [comment]
*[`420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java` line 104 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niEwH68S_AK9WMw2u:-N7nj0sL0fhsm706Bp5l:b5kijsj) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/delegate/DelegateServiceAgentClient.java#L104)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

PT
</blockquote></details>

it's task progress API hence PT

**Comment by jennyjames21** [comment]
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niY9k0MFqmwC1cGki:-N7nj83j2NzFVfPu9yvc:bizd6fm) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L52)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

log.debug ?
</blockquote></details>

We need this to debug in prod in case of any issue, we can remove later

**Comment by jennyjames21** [comment]
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7nijT430_I89Eb5zQI:-N7no0-D6Y7QzkUH54fG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L88)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We can move this function at common place and use it, instead of repeating the same code at two places.
</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35673)* status: :shipit: complete! ✓

___
*[`420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/35673#-N7niY9k0MFqmwC1cGki:-N7nqWyX1nTJ0Yd9fjrt:b-rfm0sh) ([raw file](https://github.com/harness/harness-core/blob/fbf1b00e18a9fda71d3546055ca0b48ead1565f8/420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java#L52)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

We need this to debug in prod in case of any issue, we can remove later
</blockquote></details>

yeah, make sure to remove this in near term, as this might create log spew.

**Pull request merged**
