### PR TITLE
[fix]: [PL-22435]: stop CG login audits from getting captured in NG

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
stop CG login audits from getting captured in NG for users who are not part of NG.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37162)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37162)

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 1261 at r1](https://reviewable.io/reviews/harness/harness-core/37162#-NBES3AMAZCxoAnpaYge:-NBES3ANAxCkmBpmOxuG:b-vkw74z) ([raw file](https://github.com/harness/harness-core/blob/367393837adfffdc56adfcf9b08e65149d38fa9f/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L1261)):*
> ```Java
>         if (accountService.isNextGenEnabled(accountId)) {
>           Boolean isUserInScope = NGRestUtils.getResponse(
>               userMembershipClient.isUserInScope(loggedInUser.getUuid(), accountId, null, null));
> ```

Here if any of the Db operation fails or any of the API call fails for a single account id, it will result into skipping all rest of the accounts. Is this expected?

**Comment by pbarapatre10** [comment]
trigger ft1

**Comment by pbarapatre10** [comment]
trigger ft2

**Comment by pbarapatre10** [comment]
@kapil-harness can we please add a Unit test for this, thanks

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by kapil-harness — COMMENTED** [review]
@pbarapatre10 added a UT

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37162#-:-NBJNMHdC0tcymJrKNi0:b-v7gzg4)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 1261 at r1](https://reviewable.io/reviews/harness/harness-core/37162#-NBES3AMAZCxoAnpaYge:-NBJNB1947OSbT2CnMlz:b-lh972h) ([raw file](https://github.com/harness/harness-core/blob/367393837adfffdc56adfcf9b08e65149d38fa9f/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L1261)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here if any of the Db operation fails or any of the API call fails for a single account id, it will result into skipping all rest of the accounts. Is this expected?
</blockquote></details>

no, handled the exception to avoid that scenario

**Comment by mohitg0795** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 1277 at r3](https://reviewable.io/reviews/harness/harness-core/37162#-NBJQmUuEq1tXmN78847:-NBJQmUuEq1tXmN78848:bx7hfx) ([raw file](https://github.com/harness/harness-core/blob/7d715e69e1da9a922d43b2c7aee09ab956b1f157/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L1277)):*
> ```Java
>           accountIdentifier, userId, ex);
>     }
>     return false;
> ```

I would suggest not returnin false here. Let the exception throw from this method and let callee method take decision on how to handle it. Returning false indicates a definite decision that user is not in scope while actually we may have faced an exception.

**Comment by pbarapatre10** [comment]
:lgtm:

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37162)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37162)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java` line 1277 at r3](https://reviewable.io/reviews/harness/harness-core/37162#-NBJQmUuEq1tXmN78847:-NBLgmXJA_WHnID7gR0_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/7d715e69e1da9a922d43b2c7aee09ab956b1f157/400-rest/src/main/java/software/wings/service/impl/AuthServiceImpl.java#L1277)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I would suggest not returnin false here. Let the exception throw from this method and let callee method take decision on how to handle it. Returning false indicates a definite decision that user is not in scope while actually we may have faced an exception.
</blockquote></details>

done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37162)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by kapil-harness** [comment]
trigger codebasehash

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37162)* status: :shipit: complete! ✓

**Pull request merged**
