### PR TITLE
[fix]: [PL-31793]: update base image to 8.7 from latest to have maven

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
[fix]: [PL-31793]: update base image to 8.7 from latest to have maven.
Maven is required for building 'gateway' artifacts, since gateway service uses maven as the build system. 
Successful feature build execution of gateway: https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/OpenJDKGatewayFeature/executions/d1EzTHOpRFKVACIGcBWqPA/pipeline?storeType=INLINE

We deployed this feature build of Gateway to PreQA and it is working fine.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PL-31793]: https://harness.atlassian.net/browse/PL-31793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44694)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/44694#-NPcT1Z283CupUb1zUVl:-NPcT1Z283CupUb1zUVm:bwyrx0h) ([raw file](https://github.com/harness/harness-core/blob/0d2108d83461250021fe082fed83b801c5812c4f/dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent#L69)):*
> ```
>     && wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz \
>     && tar -xf apache-maven-3.6.1-bin.tar.gz && mv apache-maven-3.6.1/ /usr/local/src/apache-maven \
>     && echo "export M2_HOME=/usr/local/src/apache-maven \
> ```

i don't think export will work in Dockerfile, take a look at dockerization/delegate/Dockerfile-minimal to see how PATH is being set

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44694)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Comment by diptiman-adak** [comment]
*[`dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/44694#-NPcT1Z283CupUb1zUVl:-NPexsTk5ERd6EwbLvl1:b-xbcpsz) ([raw file](https://github.com/harness/harness-core/blob/0d2108d83461250021fe082fed83b801c5812c4f/dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent#L69)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

i don't think export will work in Dockerfile, take a look at dockerization/delegate/Dockerfile-minimal to see how PATH is being set
</blockquote></details>

This we have tested. It was working.

**Review by diptiman-adak — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44694)* status: 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[`dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/44694#-NPcT1Z283CupUb1zUVl:-NPpIzog1QzmZticxq4r:bc0iku4) ([raw file](https://github.com/harness/harness-core/blob/0d2108d83461250021fe082fed83b801c5812c4f/dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent#L69)):*
<details><summary><i>Previously, diptiman-adak (Diptiman Adak) wrote…</i></summary><blockquote>

This we have tested. It was working. 
</blockquote></details>

Yes, this was tested by creating a new tag and then building gateway using the same tag. The same new built gateway artifact is deployed to PreQA and working fine. Thanks

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44694)* status: :shipit: complete! ✓

**Pull request merged**
