### PR TITLE
[feat]: [CDS-39942]: add support for values override in Service V2

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36017)

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: 9 file(s) to review. 0 of 1 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java` line 195 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8wzNaV7lsxyAVGMJSI:-N8wzNaV7lsxyAVGMJSJ:b1bt4rt) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java#L195)):*
> ```Java
> 
>     Optional<NGServiceOverridesEntity> serviceOverridesEntity =
>         fetchServiceOverrideEntities(ctx, config, kryoSerializer);
> ```

It would be better if this method directlly gets NGServiceOverridesConfig instead of dealing with the entity

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8wznRXA3X2K_8k4tfP:-N8wznRXA3X2K_8k4tfQ:bk99bjo) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java#L196)):*
> ```Java
>     Optional<NGServiceOverridesEntity> serviceOverridesEntity =
>         fetchServiceOverrideEntities(ctx, config, kryoSerializer);
>     NGEnvironmentConfig ngEnvironmentConfig = fetchEnvironmentConfig(ctx, kryoSerializer);
> ```

If we can get ngEnvironmentConfig first, we do not need to kryo deserialise again while fetching service overrides, right ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8x-UfX6kV5ljN787k4:-N8x-UfX6kV5ljN787k5:b-waab48) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L267)):*
> ```Java
>     List<ManifestConfigWrapper> svcOverrideManifests = new ArrayList<>();
> 
>     svcManifests = fetchManifestFromServiceEntity(serviceV2Config);
> ```

nit: fetch generally indicates that we need to do some work ( rest call/ db call ) to fetch. If we are just reading some field from an object, IMO its better to just call it ```get```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8x2aXwDGESzHayHPaD:-N8x2aXwDGESzHayHPaE:b-jiyzwr) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L267)):*
> ```Java
>     List<ManifestConfigWrapper> svcOverrideManifests = new ArrayList<>();
> 
>     svcManifests = fetchManifestFromServiceEntity(serviceV2Config);
> ```

We can initialize this with the declaration itself
```final List<ManifestConfigWrapper> svcOverrideManifests = fetchManifestFromServiceEntity(serviceV2Config)```



_Code quote:_
```Java
List<ManifestConfigWrapper> svcOverrideManifests 
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 330 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8x7pZ18p8ZW4ijj6U3:-N8x7pZ18p8ZW4ijj6U4:bj2zeg3) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L330)):*
> ```Java
>                                             .collect(Collectors.toList());
>     if (isNotEmpty(duplicateManifestIds)) {
>       throw new InvalidRequestException(format("Found duplicate manifest identifier in Service: %s",
> ```

can we have the following error message ?

```duplicate manifest identifiers for service <servicename> and environment <envname>```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8xR_HM1d5x4PzAEFd6:-N8xR_HM1d5x4PzAEFd7:bgjkitr) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L278)):*
> ```Java
> 
>     List<ManifestConfigWrapper> envGlobalManifests = fetchFilteredEnvGlobalManifests(ngEnvironmentConfig);
>     finalManifests.addAll(envGlobalManifests);
> ```

should we not add in this order
service -> env global -> service specific overrides in an environment

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java` line 196 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8wznRXA3X2K_8k4tfP:-N8yCn4uEU_UmwVpqDz-:b-bqsfnm) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java#L196)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

If we can get ngEnvironmentConfig first, we do not need to kryo deserialise again while fetching service overrides, right ?
</blockquote></details>

Thanks. missed it.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 267 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8x2aXwDGESzHayHPaD:-N8yCt2G7TR3mVLqdh88:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L267)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We can initialize this with the declaration itself
```final List<ManifestConfigWrapper> svcOverrideManifests = fetchManifestFromServiceEntity(serviceV2Config)```
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 278 at r3](https://reviewable.io/reviews/harness/harness-core/36017#-N8xR_HM1d5x4PzAEFd6:-N8yCv7w5isUcgdirxig:bmz1bdm) ([raw file](https://github.com/harness/harness-core/blob/9f1cfd60c8d9bd1f822263f008442f0d3be8167a/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L278)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not add in this order
service -> env global -> service specific overrides in an environment
</blockquote></details>

i observed in here 
io.harness.cdng.k8s.K8sStepHelper#resolveManifestsOutcome - when we are making following call.
it is returning manifests in opposite order.
So as of now, i have reversed the order in before. Will discuss above non intuitive behaviour of below mentioned grpc call.



_Code snippet:_
```Java
outcomeService.resolveOptional(
        ambiance, RefObjectUtils.getOutcomeRefObject(OutcomeExpressionConstants.MANIFESTS));
```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 315 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N972d9w44L-pNRGGO73:-N972d9w44L-pNRGGO74:b1thabu) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L315)):*
> ```Java
>     }
>     List<ManifestConfigWrapper> svcOverrideManifests =
>         getSvcOverrideManifests(Collections.singletonList(serviceOverrideConfig));
> ```

do we need a list as an argument in the above method ?
can we just have
``` private List<ManifestConfigWrapper> getSvcOverrideManifests( @NonNull NGServiceOverrideConfig serviceOverrideConfigs)```

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 332 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N973yY-35gbfiwW5aTg:-N973yY-35gbfiwW5aTh:b-qomap7) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L332)):*
> ```Java
> 
>     manifests.stream().map(ManifestConfigWrapper::getManifest).map(ManifestConfig::getIdentifier).forEach(id -> {
>       if (uniqueIds.contains(id)) {
> ```

we can do this instead
```
if (!uniqueIds.add(id)) {
  duplicateIds.add(id)
}
```

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGEnvironmentGlobalOverride.java` line 36 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N978ZveE9AcFv-LAWeW:-N978ZveE9AcFv-LAWeX:b-2ey73o) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGEnvironmentGlobalOverride.java#L36)):*
> ```Java
>   @Getter(onMethod_ = { @ApiModelProperty(hidden = true) })
>   @ApiModelProperty(hidden = true)
>   String uuid;
> ```

Lets override childrenToWalk() method

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/yaml/NGEnvironmentInfoConfig.java` line 67 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N97AnRe60-N4VZrHte3:-N97AnRe60-N4VZrHte4:b-mbxfu0) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/yaml/NGEnvironmentInfoConfig.java#L67)):*
> ```Java
>   @ApiModelProperty(required = true) EnvironmentType type;
>   @Valid List<NGVariable> variables;
>   @JsonProperty("overrides") NGEnvironmentGlobalOverride ngEnvironmentGLobalOverride;
> ```

typo: GL -> Gl

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 2 of 7 files at r3, 2 of 5 files at r5, 3 of 5 files at r6, 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 315 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N972d9w44L-pNRGGO73:-N9C-gnGDLkzL6VMBHqj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L315)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need a list as an argument in the above method ?
can we just have
``` private List<ManifestConfigWrapper> getSvcOverrideManifests( @NonNull NGServiceOverrideConfig serviceOverrideConfigs)``` 
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 332 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N973yY-35gbfiwW5aTg:-N9C-jKh4h_qzo1tO2SA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L332)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we can do this instead
```
if (!uniqueIds.add(id)) {
  duplicateIds.add(id)
}
```
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGEnvironmentGlobalOverride.java` line 36 at r7](https://reviewable.io/reviews/harness/harness-core/36017#-N978ZveE9AcFv-LAWeW:-N9C-lgC0AcPja-q97Lz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ed77695a838fa1b4739d91c6ee93598f59adfd13/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans/NGEnvironmentGlobalOverride.java#L36)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets override childrenToWalk() method
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 2 of 7 files at r3, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: 6 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java` line 233 at r10](https://reviewable.io/reviews/harness/harness-core/36017#-N9CJ_QR3TdgeRya1Tyk:-N9CJ_QR3TdgeRya1Tyl:b9xk1zz) ([raw file](https://github.com/harness/harness-core/blob/8caa821d4d7881ff692b4fc7b7fdb61d46bd6a4f/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorHelper.java#L233)):*
> ```Java
>     // in case no manifest is present no node should be created
>     if (isEmpty(finalManifests)) {
>       return StringUtils.EMPTY;
> ```

lets also test this case when there are no manifests to make sure that "not creating the node" does not create any impact

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 230 at r10](https://reviewable.io/reviews/harness/harness-core/36017#-N9CJ-vcBH84MVPNePLX:-N9CJ-vcBH84MVPNePLY:b-mtc3yx) ([raw file](https://github.com/harness/harness-core/blob/8caa821d4d7881ff692b4fc7b7fdb61d46bd6a4f/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L230)):*
> ```Java
>         environmentEntity.getProjectIdentifier(), environmentEntity.getAccountId());
>     if (isNotEmpty(environmentEntity.getYaml())) {
>       validateEnvGlobalManifestsOverrides(environmentEntity);
> ```

we are already deserializing the yaml here
```Environment environmentEntity = EnvironmentMapper.toEnvironmentEntity(accountId, environmentRequestDTO)```

maybe we can reuse the same method or the same ngEnvironmentConfig instead of doing this twice ?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java` line 230 at r10](https://reviewable.io/reviews/harness/harness-core/36017#-N9CJ-vcBH84MVPNePLX:-N9G7RhC9tXkrBvhGW7O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8caa821d4d7881ff692b4fc7b7fdb61d46bd6a4f/120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java#L230)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we are already deserializing the yaml here
```Environment environmentEntity = EnvironmentMapper.toEnvironmentEntity(accountId, environmentRequestDTO)```

maybe we can reuse the same method or the same ngEnvironmentConfig instead of doing this twice ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 3 of 4 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger ti4

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 2 of 7 files at r3, 2 of 5 files at r6, 2 of 3 files at r7, 2 of 6 files at r9, 5 of 6 files at r10, 3 of 4 files at r11, 1 of 1 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: Some of the checks are too old.

**Comment by tchaurasiya** [comment]
trigger ti1

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: :shipit: complete! ✓

**Comment by tchaurasiya** [comment]
trigger ti4

**Comment by tchaurasiya** [comment]
trigger ti4

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r14, 1 of 1 files at r15, 7 of 12 files at r16, 1 of 2 files at r18, 2 of 3 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36017)* status: :shipit: complete! ✓

**Pull request merged**
