### PR TITLE
feat: [CDS-39559]: Optimizing Kustomize Manifest Fetch in NG

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 602 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N83-COF61mnR-RJz4AI:-N83-COF61mnR-RJz4AJ:b-hefs0w) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L602)):*
> ```Java
>             .storeDelegateConfig(getStoreDelegateConfig(kustomizeManifestOutcome.getStore(), ambiance, manifestOutcome,
>                 manifestOutcome.getType() + " manifest"))
>             .kustomizeYamlPath(kustomizeManifestOutcome.getOverlayConfiguration() == null
> ```

shouldn't this value be set based on FF? What is the plan for inline manifest?
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifest.java` line 76 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N83-QGd11lP34UfyISC:-N83-QGd11lP34UfyISD:bmjtmp6) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/KustomizeManifest.java#L76)):*
> ```Java
>   @ApiModelProperty(dataType = "io.harness.cdng.manifest.yaml.kinds.kustomize.OverlayConfiguration")
>   @SkipAutoEvaluation
>   OverlayConfiguration overlayConfiguration;
> ```

for @SkipAutoEvaluation to work, this should be a ParameterField
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N83-WCj4hoYfzW0YiUA:-N83-WCk2u5YG0nHI2K3:b-q1qonr) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java#L36)):*
> ```Java
>   @NotNull
>   @ApiModelProperty(dataType = STRING_CLASSPATH)
>   @SkipAutoEvaluation
> ```

You don't need SkipAutoEvaluationHere if you have it in parent object

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 534 at r3](https://reviewable.io/reviews/harness/harness-core/35781#-N8309kJ5QPuSalerOR0:-N8309kJ5QPuSalerOR1:b-39im9s) ([raw file](https://github.com/harness/harness-core/blob/02d72e307c254cb62285c7f8d63bc1680a83ac2f/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L534)):*
> ```Java
> 
>   public boolean isOptimizeFetchFilesKustomize(String accountId) {
>     return cdFeatureFlagHelper.isEnabled(accountId, FeatureName.NG_OPTIMIZE_FETCH_FILES_KUSTOMIZE);
> ```

do we really need to put this behind an FF.
Will this optimisation break any existing setup of a customer.?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 2 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N831nIE2tkSUiHZ65vR:-N831nIF3e8qSjtZaswY:b-dsukdn) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java#L38)):*
> ```Java
>   @SkipAutoEvaluation
>   @Wither
>   private ParameterField<String> kustomizeYamlPath;
> ```

Will kustomizeYamlFolderPath will make more sense? Can you check

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 7 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java` line 534 at r3](https://reviewable.io/reviews/harness/harness-core/35781#-N8309kJ5QPuSalerOR0:-N83PR6s2zAXAO7L1FAj:boh5w36) ([raw file](https://github.com/harness/harness-core/blob/02d72e307c254cb62285c7f8d63bc1680a83ac2f/125-cd-nextgen/src/main/java/io/harness/cdng/CDStepHelper.java#L534)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

do we really need to put this behind an FF.
Will this optimisation break any existing setup of a customer.?
</blockquote></details>

Yes @shubham-in10se we discussed this in standup
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 602 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N83-COF61mnR-RJz4AI:-N83QEu02nk3ceE79hwK:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L602)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

shouldn't this value be set based on FF? What is the plan for inline manifest?
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N83-WCj4hoYfzW0YiUA:-N83QItO5h2nXONfAqFu:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java#L36)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

You don't need SkipAutoEvaluationHere if you have it in parent object
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/35781#-N831nIE2tkSUiHZ65vR:-N83QKlg2nfRXrc8S-6K:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/18eefe6c0789ce3e410d67afca7fc465d28a08c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/kustomize/OverlayConfiguration.java#L38)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Will kustomizeYamlFolderPath will make more sense? Can you check 
</blockquote></details>

Done

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed 7 of 7 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 2 change requests. 4. unresolved discussions.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 1 change requests. 3. unresolved discussions.

**Comment by namantalaycha10** [comment]
trigger codebasehash

**Review by GoelPratyush99 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 1 change requests. 3. unresolved discussions.

**Review by GoelPratyush99 — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by GoelPratyush99 — APPROVED** [review]

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 2 of 7 files at r4, 3 of 4 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 606 at r8](https://reviewable.io/reviews/harness/harness-core/35781#-N88rRd2BuBVR-Kg3YK8:-N88rRd3DE4HSAe0ezfh:b52mdjf) ([raw file](https://github.com/harness/harness-core/blob/01d4479c581c3e790917b7ec52cbe5224828269f/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L606)):*
> ```Java
>                 manifestOutcome.getType() + " manifest"))
>             .kustomizeYamlFolderPath(cdStepHelper.isOptimizeFetchFilesKustomize(AmbianceUtils.getAccountId(ambiance))
>                         && ParameterField.isNotNull(kustomizeManifestOutcome.getOverlayConfiguration())
> ```

Let's make this common method, I can see the same logic is used in getKustomizeManifestBasePath

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: :shipit: complete! ✓

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35781)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger codebasehash

**Pull request merged**
