### PR TITLE
feat: [PLG-2080]: Make Credit iterator handler generic

### PR DESCRIPTION
**Pull request by Xin-Harness**
## Describe your changes
This PR refactor the Credit iterator handler to handle Credit type instead of subtype and make it more adaptable for future change.
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)

### CODE REVIEW

**Review by kapil-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/47259#-NUTYMCAA9r3wItAEHWH:-NUTYMCAA9r3wItAEHWI:bnzxkm1) ([raw file](https://github.com/harness/harness-core/blob/a77463fb05134a7215c3f0f75253e5567f9153e6/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L649)):*
> ```Java
>         .registerIterators(ngIteratorsConfig.getOauthTokenRefreshIteratorConfig().getThreadPoolSize());
>     injector.getInstance(NGVaultUnsetRenewalHandler.class).registerIterators(5);
>     injector.getInstance(CICreditExpiryIteratorHandler.class).registerIterator(2);
> ```

with this solution we would need to add more iterators in future e.g. SRMCreditExpiryIteratorHandler, so doesn't seem like its generic.

**Review by Xin-Harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 649 at r1](https://reviewable.io/reviews/harness/harness-core/47259#-NUTYMCAA9r3wItAEHWH:-NUT_mjq1omZ6emnHPXy:bmohelc) ([raw file](https://github.com/harness/harness-core/blob/a77463fb05134a7215c3f0f75253e5567f9153e6/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L649)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

with this solution we would need to add more iterators in future e.g. SRMCreditExpiryIteratorHandler, so doesn't seem like its generic.
</blockquote></details>

I have checked with @abhinav-harness and this is the best solution to make it abstract. 
The registration for iterator has to be done for all subclasses no matter what.

since each iterator of different expiry handler can have different thread pool runtime etc - It just need to register with ng manager.

**Review by kapil-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
trigger review

**Review by neelam-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259#-:-NUTv8zT5dI7s63inoyK:bnfp4nl)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
trigger utAll

**Comment by Xin-Harness** [comment]
trigger uts

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by kapil-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47259)* status: :shipit: complete! ✓

**Comment by Xin-Harness** [comment]
trigger review

**Pull request merged**
