### PR TITLE
fix: [CDS-39369]: Update artifact details from deployment summary bas…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…ed on matching buildNumber

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1270 at r1](https://reviewable.io/reviews/harness/harness-core/34925#-N66foiD2Lkg_oMgqGmi:-N66foiD2Lkg_oMgqGmj:b-5l0l72) ([raw file](https://github.com/harness/harness-core/blob/79fe5220e1d4eb4eab3d07c5bc97013a19b3a9f9/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1270)):*
> ```Java
>             break;
>           }
>         }
> ```

lets extract this logic of finding the correct artifact into a separate method. It does look like that this complexity belongs here. We can discuss offline

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1270 at r1](https://reviewable.io/reviews/harness/harness-core/34925#-N66foiD2Lkg_oMgqGmi:-N67-COSAdeY5YlpmuPB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/79fe5220e1d4eb4eab3d07c5bc97013a19b3a9f9/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1270)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets extract this logic of finding the correct artifact into a separate method. It does look like that this complexity belongs here. We can discuss offline
</blockquote></details>

Done.

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1252 at r2](https://reviewable.io/reviews/harness/harness-core/34925#-N6738E2Azp6ZDEuX_7N:-N6738E2Azp6ZDEuX_7O:b-gfc3aa) ([raw file](https://github.com/harness/harness-core/blob/98f9924792788e1d1fb532f07a703980392003cb/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1252)):*
> ```Java
> 
>     if (deploymentSummary != null && deploymentSummary.getArtifactStreamId() != null) {
>       return buildInstanceFromPodHelper(builder, deploymentSummary, infraMapping, pod).build();
> ```

maybe call this ```populateArtifactInInstanceBuilder```

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java` line 1252 at r2](https://reviewable.io/reviews/harness/harness-core/34925#-N6738E2Azp6ZDEuX_7N:-N674hM2-yNBEHmMAIt_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/98f9924792788e1d1fb532f07a703980392003cb/400-rest/src/main/java/software/wings/service/impl/instance/ContainerInstanceHandler.java#L1252)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe call this ```populateArtifactInInstanceBuilder```
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34925)* status: :shipit: complete! ✓

**Pull request merged**
