### PR TITLE
[feat]: [PL-31351]: NG SCIM add support for unique external id in userName SCIM request

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes
As per SCIM 2.0 standard the externalId is also part of SCIM 2.0 request and response for Users. 
We are adding support for 'externalId' in request and response, and this detail will be persisted in the users collection of Harness. We are not supporting updates to 'externalId' in this change

Test scenarios:
- Unit tests added
- Checked CREATE user API and found correct response:
curl --location --request POST 'http://localdev.harness.io/gateway/ng/api/scim/account/kmpySmUISimoRrJL6NL73w/Users' \
--header 'Content-Type: application/json' \
--data-raw '{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "externalId": "E9999",
    "userName": "bjollylyyy@example.com",
    "userType": "EMP",
    "name": {
        "formatted": "Ms. Barbara J Jensen III",
        "familyName": "Jensen",
        "givenName": "Boss"
    },
    "displayName": "Boss Johnson",
    "title": "Typist"
}'
Response: 
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "userName": "bjollylyyy@example.com",
    "displayName": "bjollylyyy@example.com",
    "active": true,
    "emails": [
        {
            "value": "bjollylyyy@example.com",
            "primary": true
        }
    ],
    "name": {
        "displayName": "bjollylyyy@example.com",
        "formatted": "Boss, Jensen",
        "familyName": "Jensen",
        "givenName": "Boss"
    },
    "id": "7eRLuNg-TOSyUr19YDTqkA",
    "externalId": "E9999",
    "meta": {
        "created": "2023-03-09T11:19:35.491+0530",
        "location": "",
        "lastModified": "2023-03-09T11:19:35.504+0530",
        "version": "",
        "resourceType": "User"
    }
}

- Get /User/{userId} response:
GET http://localdev.harness.io/gateway/ng/api/scim/account/kmpySmUISimoRrJL6NL73w/Users/7eRLuNg-TOSyUr19YDTqkA
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "userName": "bjollylyyy@example.com",
    "displayName": "bjollylyyy@example.com",
    "active": true,
    "emails": [
        {
            "value": "bjollylyyy@example.com",
            "primary": true
        }
    ],
    "name": {
        "displayName": "bjollylyyy@example.com",
        "formatted": "Boss, Jensen",
        "familyName": "Jensen",
        "givenName": "Boss"
    },
    "id": "7eRLuNg-TOSyUr19YDTqkA",
    "externalId": "E9999",
    "meta": {
        "created": "2023-03-09T11:19:35.491+0530",
        "location": "",
        "lastModified": "2023-03-09T11:19:35.504+0530",
        "version": "",
        "resourceType": "User"
    }
}

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)

### CODE REVIEW

**Review by VikasMaddukuriHarness — DISMISSED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 367 at r2](https://reviewable.io/reviews/harness/harness-core/44831#-NQ-CO2816xUw9hjrRRx:-NQ-CO2816xUw9hjrRRy:btux351) ([raw file](https://github.com/harness/harness-core/blob/0d59066de9fc68dbd706dab097105a5a39ea19df/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L367)):*
> ```Java
>     }
> 
>     if (ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.UPDATE_EMAILS_VIA_SCIM)
> ```

@pbarapatre10 We will also have to handle the email update operations separately as well, right? It will be based on emails field instead of userName if this feature flag is enabled.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 367 at r2](https://reviewable.io/reviews/harness/harness-core/44831#-NQ-CO2816xUw9hjrRRx:-NQ-DdXF-jz4WV9PgB7J:b-4itegu) ([raw file](https://github.com/harness/harness-core/blob/0d59066de9fc68dbd706dab097105a5a39ea19df/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L367)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

@pbarapatre10 We will also have to handle the email update operations separately as well, right? It will be based on emails field instead of userName if this feature flag is enabled.
</blockquote></details>

Update email flow is not part of this commit, we will handle it in separate PR. Thanks

**Review by tiwaritejas — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: :shipit: complete! ✓

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: 3 file(s) to review.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44831)* status: :shipit: complete! ✓

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Pull request merged**
