### PR TITLE
feat: [CDS-43393]: Remove FFs NG_SERVICE_CONFIG_FILES_OVERRIDE NG_SERVICE_MANIFEST_OVERRIDE

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37655)

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/37655#-NCa2eU4CIlxoLVA4es9:-NCa2eU4CIlxoLVA4esA:b-s4j2yp) ([raw file](https://github.com/harness/harness-core/blob/6a17dc0dccaffb525ec6f62eed6bc085d7f4f581/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L220)):*
> ```Java
>   }
> 
>   private void validateEnvGlobalOverrides(NGEnvironmentConfig ngEnvironmentConfig, boolean ngSvcManifestOverrideEnabled,
> ```

nit: We can remove this whole method, Doesn't seems like we need this anymore.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)* status: Some of the checks are too old.

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/37655#-NCa2eU4CIlxoLVA4es9:-NCe6DXCAZvI6LU6bowA:b-5vi4j) ([raw file](https://github.com/harness/harness-core/blob/6a17dc0dccaffb525ec6f62eed6bc085d7f4f581/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java#L220)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Its being used actually, from the `io.harness.ng.core.environment.mappers.EnvironmentMapper#toEnvironmentEntity` method
</blockquote></details>

I meant, with ff gone code wont go to inside this block, so kind of noOp method.



_Code quote:_
```Java
      if (!ngSvcManifestOverrideEnabled
          && isNotEmpty(
              ngEnvironmentConfig.getNgEnvironmentInfoConfig().getNgEnvironmentGlobalOverride().getManifests())) {
        throw new InvalidRequestException("Manifest Override is not supported");
      }
```

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)* status: Some of the checks are too old.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)* status: Some of the checks are too old.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37655)* status: :shipit: complete! ✓

**Pull request merged**
