### PR TITLE
feat: [CDS-67745]: upgrade go-scm version

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Upgrade go-scm version in scm-service. And use findEmail api of go-scm in getauthenticated user.

**Testing:** Tested the changes locally, the email is correctly fetched for bitbucket.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47199)

### CODE REVIEW

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47199)* status: 4 file(s) to review. 0 of 2 approvals obtained.

**Review by senjucanon2 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47199)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`product/ci/scm/git/git.go` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/47199#-NURDIa3B_JAhf39ior5:-NURDIa3B_JAhf39ior6:be9anqc) ([raw file](https://github.com/harness/harness-core/blob/7c5f5566f6a76bfb43f9ab7d6b0805c3fc2a6eaa/product/ci/scm/git/git.go#L589)):*
> ```Go
> 
> 	if response.Email == "" {
> 	    email, _, err := client.Users.FindEmail(ctx)
> ```

what if FindEmail is unimplemented for some git provider just like it was in the case of bitbucket?

**Comment by shalini-agr** [comment]
*[`product/ci/scm/git/git.go` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/47199#-NURDIa3B_JAhf39ior5:-NUREs8C2gXX1txsYRYh:b6d2q8x) ([raw file](https://github.com/harness/harness-core/blob/7c5f5566f6a76bfb43f9ab7d6b0805c3fc2a6eaa/product/ci/scm/git/git.go#L589)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what if FindEmail is unimplemented for some git provider just like it was in the case of bitbucket?
</blockquote></details>

In that case scm error: Not supported is thrown

**Comment by mohitg0795** [comment]
*[`product/ci/scm/git/git.go` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/47199#-NURDIa3B_JAhf39ior5:-NURMGJd3HVKywrkVljZ:b-wg8aod) ([raw file](https://github.com/harness/harness-core/blob/7c5f5566f6a76bfb43f9ab7d6b0805c3fc2a6eaa/product/ci/scm/git/git.go#L589)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

In that case scm error: Not supported is thrown
</blockquote></details>

Yes, so thats an issue right? It will start breaking flows for some git providers.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47199)* status: 4 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`product/ci/scm/git/git.go` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/47199#-NURDIa3B_JAhf39ior5:-NURTU9r-uSdPw7FJLpq:b-2kwgqc) ([raw file](https://github.com/harness/harness-core/blob/7c5f5566f6a76bfb43f9ab7d6b0805c3fc2a6eaa/product/ci/scm/git/git.go#L589)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, so thats an issue right? It will start breaking flows for some git providers.
</blockquote></details>

yes, added a check for BB here

**Pull request merged**
