### PR TITLE
feat: [PL-23733]: Endpoints for fetching both inherited and user groups of a scope

### PR DESCRIPTION
**Pull request by naman-goenka**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33424)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger compile

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33424#-:-N2jfNba4JoMmZLLrjxs:bnfp4nl)* status: 19 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1, 16 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33424#-:-N2jmaAK9vJ2rFSBw2Cb:bnfp4nl)* status: 1 file(s) to review.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33424#-:-N2jq1CH8zrjmRDnoj-8:bnfp4nl)* status: 1 file(s) to review.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33424)* status: :shipit: complete! ✓

**Pull request merged**
