### PR TITLE
fix: [PL-24821]: UserGroup deletion via GraphQl

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33123)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger messagecheck

**Comment by kanikamittal09** [comment]
trigger pr_apibackwardcompatibility

**Comment by kanikamittal09** [comment]
trigger pr_apibackwardcompatibility

**Comment by kanikamittal09** [comment]
trigger pr_apibackwardcompatibility

**Comment by kanikamittal09** [comment]
trigger pr_apibackwardcompatibility

**Comment by kanikamittal09** [comment]
trigger pr_apibackwardcompatibility

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33123)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by boopesh007 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33123)* status: :shipit: complete! ✓

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33123)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java` line 799 at r1](https://reviewable.io/reviews/harness/harness-core/33123#-N2VD11j4-Phb68dosL9:-N2VD11j4-Phb68dosLA:b-srrpmw) ([raw file](https://github.com/harness/harness-core/blob/f654103ae560e261baf5fb6a2d44a1c86a3f1a21/400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java#L799)):*
> ```Java
>     UserGroup userGroup = get(accountId, userGroupId, false);
>     notNullCheck("userGroup", userGroup);
>     if (!(userGroup.getParents().isEmpty())) {
> ```

nit - `isNotEmpty(userGroup.getParents())`

**Pull request merged**
