### PR TITLE
feat: [CDS-44504]: ssh/winrm Support ECR docker artifact type

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44498)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger ut4

**Comment by vitsafronovici** [comment]
trigger ut5

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/44498#-NPROqnM6fbiLYEncxud:-NPROqnM6fbiLYEncxue:bmiw0qc) ([raw file](https://github.com/harness/harness-core/blob/b400e49c029d420871b1f3bc6dd08f719084b1e8/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L119)):*
> ```Java
>       }
>       if (context.getArtifactDelegateConfig() instanceof SkipCopyArtifactDelegateConfig) {
>         log.info("Artifactory {} registry found, skipping copy artifact.",
> ```

let's replace artifactory with Docker

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498#-:-NPRTa_W86kkMCK0UMKg:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by vitsafronovici — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/44498#-NPROqnM6fbiLYEncxud:-NPRTvhNAFIR5Jn2g42V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b400e49c029d420871b1f3bc6dd08f719084b1e8/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/SshCopyCommandHandler.java#L119)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

let's replace artifactory with Docker
</blockquote></details>

Done.

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498)* status: 1 of 2 approvals obtained.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44498#-:-NPRx3KK6HnbSAswnCnS:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
