### PR TITLE
feat: [PL-23577]: User Deletion flow V2 behind FF USER_DELETION_V2

### PR DESCRIPTION
**Pull request by boopesh007**
## Describe your changes
User deletion is modularised now for CG and NG. We see a lot of customers migrating to NG through SCIM. Customers tend to retire CG SCIM whereas it deletes the user from NG as well. It's now being separated. The deletion flows will now affect only the respective scope of the user. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 368 at r5](https://reviewable.io/reviews/harness/harness-core/42297#-NLKR3Z7D9HcLD6AnCUr:-NLKR3Z7D9HcLD6AnCUs:b-8diiig) ([raw file](https://github.com/harness/harness-core/blob/5a9d1c16251cf563e10698a1a337ed82b1fc882b/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L368)):*
> ```Java
> 
>   private boolean shouldUpdateUser(ScimUser userQuery, UserMetadataDTO user, String accountId) {
>     if (ngFeatureFlagHelperService.isEnabled(accountId, FeatureName.SPG_USER_DELETION_V2)) {
> ```

no need to change this method

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 92 at r5](https://reviewable.io/reviews/harness/harness-core/42297#-NLKRHrm263HmhoeF0Q-:-NLKRHrm263HmhoeF0Q0:b-fu19vp) ([raw file](https://github.com/harness/harness-core/blob/5a9d1c16251cf563e10698a1a337ed82b1fc882b/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L92)):*
> ```Java
>       userQuery.setId(user.getUuid());
>       userQuery.setActive(true);
>       if (shouldUpdateUser(userQuery, user, accountId)) {
> ```

no change required here

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 227 at r9](https://reviewable.io/reviews/harness/harness-core/42297#-NLyJj4v1jGIxgzvzJ6H:-NLyJj4v1jGIxgzvzJ6I:b-m1abtp) ([raw file](https://github.com/harness/harness-core/blob/0151e66a37055df03707179f0f2ca5276702d165/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L227)):*
> ```Java
>   @Override
>   public ScimUser updateUserDetails(String accountId, String userId, PatchRequest patchRequest) {
>     return null;
> ```

minor: could have thrown NotImplementedException with a message



_Code quote:_
```Java
return null;
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 243 at r9](https://reviewable.io/reviews/harness/harness-core/42297#-NLyIfK-Bvpg7Cw2EyYt:-NLyIfK-Bvpg7Cw2EyYu:b-krmy7b) ([raw file](https://github.com/harness/harness-core/blob/0151e66a37055df03707179f0f2ca5276702d165/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L243)):*
> ```Java
>         boolean cgUpdateResult = ngUserService.updateScimUser(accountId, userId, scimUser);
>         if (!cgUpdateResult) {
>           log.error("NGSCIM: User is not in CG found. userId: {}, accountId: {}", userId, accountId);
> ```

nit: User is not found in CG



_Code quote:_
```Java
User is not in CG found.
```

**Review by pbarapatre10 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 17 files at r1, 1 of 4 files at r2, 3 of 3 files at r3, 2 of 7 files at r5, 1 of 1 files at r7, 5 of 7 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297#-:-NLyS-6G9KPc2ECD3BGV:bnfp4nl)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 242 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM2xe6Y5dPzzcV2Vkxr:-NM2xe6Y5dPzzcV2Vkxs:b-lsq3ke) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L242)):*
> ```Java
>         userMetadata.setName(displayName);
>         userMetadata.setExternallyManaged(true);
>         log.info("NGSCIM: Updating name for user {} ; Updated name: {}", userId, displayName);
> ```

please check why this log line is deleted

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 247 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM2xhvK9mocULNt5EZv:-NM2xhvK9mocULNt5EZw:b-apx525) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L247)):*
> ```Java
>       String updatedEmail = getPrimaryEmail(scimUser);
> 
>       if (CGRestUtils.getResponse(
> ```

this piece of code shoudl not be deleted as it is used to update email

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 368 at r5](https://reviewable.io/reviews/harness/harness-core/42297#-NLKR3Z7D9HcLD6AnCUr:-NM2yXte-AkCNmJFKuYP:b85yajv) ([raw file](https://github.com/harness/harness-core/blob/5a9d1c16251cf563e10698a1a337ed82b1fc882b/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L368)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

no need to change this method
</blockquote></details>

this part is of no use



_Code quote:_
```Java
 !userQuery.getActive()
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 223 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM3-i9X1_8t1aXCL0nW:-NM3-i9X1_8t1aXCL0nX:b7ah528) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L223)):*
> ```Java
>       return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, false));
>     } else {
>       return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));
> ```

better way would be to write:



_Code quote (i):_
```Java
if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
```



_Code snippet (ii):_
```Java
if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
     disabled = false;
}
return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 268 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30awd0ywJF7yl3G7t:-NM30awd0ywJF7yl3G7u:b-w9yo6y) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L268)):*
> ```Java
>   }
> 
>   private void applyUserUpdateOnlyDetails(String accountId, String userId, PatchOperation patchOperation)
> ```

Isn't this duplicate?
We do have similar method to do these things, right?



_Code snippet:_
```Java
private void applyUserUpdateOperation(String accountId, String userId, PatchOperation patchOperation)
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 219 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30v8LCr7yHu8433ww:-NM30v8LCr7yHu8433wx:b-reimyq) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L219)):*
> ```Java
>   @Path("/scim/disabled")
>   public RestResponse<Boolean> disableScimUser(@QueryParam("accountId") String accountId,
>       @QueryParam("userId") String userId, @QueryParam("disabled") boolean disabled) {
> ```

Instead of 

    if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, false));
    } else {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));


write:

    if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
      disabled = false;
    } 
    return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));



_Code snippet:_
```Java
    if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, false));
    } else {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));
```

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 268 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30awd0ywJF7yl3G7t:-NM31FOX5hadbBwKFsVn:bh0b3gp) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L268)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Isn't this duplicate?
We do have similar method to do these things, right?


</blockquote></details>

@pbarapatre10 Please review this part.
Their should not be duplication of code.
we an refactor existing methods if needed but not copy almost entire method

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 322 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM31YU452mxN6_cKqeu:-NM31YU452mxN6_cKqev:b5ca5ih) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L322)):*
> ```Java
>     } else {
>       if ("active".equals(patchOperation.getPath()) && patchOperation.getValue(Boolean.class) != null) {
>         changeScimUserDisabled(accountId, user.getUuid(), !(patchOperation.getValue(Boolean.class)));
> ```

please add a log line here too, to differentiate between the two actions.
It will help in debugging.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 332 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM31jLK5_KYr4hlABNF:-NM31jLK5_KYr4hlABNG:b5ca5ih) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L332)):*
> ```Java
> 
>     if (!featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)
>         && patchOperation.getValue(ScimUserValuedObject.class) != null) {
> ```

please add a log line here too, to differentiate between the two actions.
It will help in debugging.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceHelper.java` line 85 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM320XM5NmZv5aCbb5o:-NM320XM5NmZv5aCbb5p:b-piyabq) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/service/impl/UserServiceHelper.java#L85)):*
> ```Java
>         userMembershipClient.removeUserInternal(userId, deletedAccountId, null, null, removeUserFilter));
>     if (!Boolean.TRUE.equals(deletedFromNG)) {
>       throw new InvalidRequestException(
> ```

Does this mean USer is Deleted form CG but not from NG?
cc: @pbarapatre10

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2878 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM32Axt3TSEpDIbGkEk:-NM32Axt3TSEpDIbGkEl:b-5ggsmv) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2878)):*
> ```Java
>   }
> 
>   @Override
> ```

why delete this?

**Review by shashank-harness — COMMENTED** [review]
> Reviewed 4 of 17 files at r1, 1 of 4 files at r2, 2 of 7 files at r5, 1 of 1 files at r7, 5 of 7 files at r8, 3 of 4 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 92 at r5](https://reviewable.io/reviews/harness/harness-core/42297#-NLKRHrm263HmhoeF0Q-:-NM3MChBDYJu4COzY275:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5a9d1c16251cf563e10698a1a337ed82b1fc882b/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L92)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

no change required here
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 227 at r9](https://reviewable.io/reviews/harness/harness-core/42297#-NLyJj4v1jGIxgzvzJ6H:-NM3MEUT5qLi_vb0eVSw:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/0151e66a37055df03707179f0f2ca5276702d165/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L227)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

minor: could have thrown NotImplementedException with a message
</blockquote></details>

Done

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 242 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM2xe6Y5dPzzcV2Vkxr:-NM3MIuU8reARFigjmhg:beuchye) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L242)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

please check why this log line is deleted
</blockquote></details>

Got added in the recent change, hence got missed.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 247 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM2xhvK9mocULNt5EZv:-NM3MR0E7E6DXTWYcf6i:b-slwua6) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L247)):*
> Got added in the recent change, hence got missed.

**Comment by boopesh007** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java` line 368 at r5](https://reviewable.io/reviews/harness/harness-core/42297#-NLKR3Z7D9HcLD6AnCUr:-NM3MTQd-fy-wQqHutja:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/5a9d1c16251cf563e10698a1a337ed82b1fc882b/120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java#L368)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

this part is of no use
</blockquote></details>

Done

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 200 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM3-LsO34wvUfAia-sj:-NM3MUuO3ZpVfKH0y2uK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L200)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

can we add a log line to tell we are deleting this user form CG as well because theya re not part of any user group?
It will help us debug if a user is deleted from CG but was not expected to.
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 219 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30v8LCr7yHu8433ww:-NM3MW0r2DUk4-kE1mfY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L219)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Instead of 

    if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, false));
    } else {
      return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));


write:

    if (featureFlagService.isEnabled(FeatureName.SPG_USER_DELETION_V2, accountId)) {
      disabled = false;
    } 
    return new RestResponse<>(scimUserService.changeScimUserDisabled(accountId, userId, disabled));

</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 223 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM3-i9X1_8t1aXCL0nW:-NM3MX39BvMzkD3Xl3LD:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L223)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

better way would be to write:
</blockquote></details>

Done

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 268 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30awd0ywJF7yl3G7t:-NM3N7saCBADCK1v7E_P:b-oy0i68) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L268)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

@pbarapatre10 Please review this part.
Their should not be duplication of code.
we an refactor existing methods if needed but not copy almost entire method
</blockquote></details>

Had to segregate the old update method into update details and deletion. Removed the duplication by calling the update details in the original method.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 322 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM31YU452mxN6_cKqeu:-NM3NNNJEJXT5u-nLhxh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L322)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

please add a log line here too, to differentiate between the two actions.
It will help in debugging.
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 332 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM31jLK5_KYr4hlABNF:-NM3NOkp-ibov0l-ErVJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L332)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

please add a log line here too, to differentiate between the two actions.
It will help in debugging.
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceHelper.java` line 85 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM320XM5NmZv5aCbb5o:-NM3NQ2EEkjk9xDE-wqz:b-xej5a0) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/service/impl/UserServiceHelper.java#L85)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Does this mean USer is Deleted form CG but not from NG?
cc: @pbarapatre10 
</blockquote></details>

This happens when we are not able to delete the user memberships in NG. Potential case is user is the last admin of the account.

**Comment by boopesh007** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2878 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM32Axt3TSEpDIbGkEk:-NM3Osm2DLTFZ3uy55Od:b-6yhx8p) ([raw file](https://github.com/harness/harness-core/blob/59d1b840a8c75a5803fa17bd3e165d6c276d12cb/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2878)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

why delete this?
</blockquote></details>

getUserGroupsOfAccount still exist. 



_Code quote:_
```Java
getUserGroupsOfAccount
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)* status: 10 file(s) to review. 10. unresolved discussions. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 332 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM31jLK5_KYr4hlABNF:-NM40Uy-9xiru-QUed7-:b7c2lrw) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L332)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any logs



_Code quote:_
```Java
if (!featureFlagService.isEnabled(FeatureName.PL_USER_DELETION_V2, accountId
```

**Review by shashank-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)* status: 10 file(s) to review. 

___
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 268 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30awd0ywJF7yl3G7t:-NM40irL78KotIPENs2h:b-4xdd6a) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L268)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

Had to segregate the old update method into update details and deletion. Removed the duplication by calling the update details in the original method. 
</blockquote></details>

@pbarapatre10 Please review this part once too.

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java` line 268 at r11](https://reviewable.io/reviews/harness/harness-core/42297#-NM30awd0ywJF7yl3G7t:-NM8h5IH6MIMEMt8mFJU:b8wexri) ([raw file](https://github.com/harness/harness-core/blob/e2b14dd94699fcc2a8aa36116e4d237ed5dd4624/400-rest/src/main/java/software/wings/scim/ScimUserServiceImpl.java#L268)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

@pbarapatre10 Please review this part once too.
</blockquote></details>

This looks fine to me & Boopesh has tested it. After FF is removed we can refactor again once if there are overlapping code

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42297)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
