### PR TITLE
fix: [CVS-9529]: Analysis State machine retry with back off and metrics k

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31695)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31695)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[toolset/git-hooks/jira-projects.txt, line 1 at r2](https://reviewable.io/reviews/harness/harness-core/31695#-MyqsAv38KySj3bqTxsJ:-MyqsAv42wZ-lmntiOUw:b-juyl2l) ([raw file](https://github.com/harness/harness-core/blob/21d5c011ef839ea097747891c2530f9fde3b34e4/toolset/git-hooks/jira-projects.txt#L1)):*
> ```help
> ART|BT|CCE|CCM|CDB|CDC|CDNG|CDP|CDS|CE|CI|COMP|SRM|CVS|DEL|DOC|DX|ER|FFM|FFM|GIT|GTM|LWG|OENG|ONP|OPA|OPS|PIE|PL|SEC|SPG|SRM|STO|SWAT
> ```

We should use SRM in the title. SRM is the new jira id now.

**Comment by AbhijithHarness** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/TimeSeriesAnalysisStateExecutor.java, line 85 at r1](https://reviewable.io/reviews/harness/harness-core/31695#-MyqmPU5CD-Qgp0bJswG:-Mytutu_BksN7gqF5yva:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/2ba71bc85b6cbd6368cd63d260c677d38a16e87c/300-cv-nextgen/src/main/java/io/harness/cvng/statemachine/services/api/TimeSeriesAnalysisStateExecutor.java#L85)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we need to have different way to retry for deployment states. And it should be limited to 3.
Also I think it simpler to use fixed array similar to 
io.harness.cvng.core.entities.DeploymentDataCollectionTask#RETRY_WAIT_DURATIONS
</blockquote></details>

added

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 2 of 3 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31695)* status: :shipit: complete! ✓

**Pull request merged**
