### PR TITLE
fix:[CDS-56765]: Ignore and log warn when audited entities do not have userId reference

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Ignore and log warn when audited entities do not have userId reference

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45317)

### CODE REVIEW

**Review by Fernando-Dourado — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45317)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/45317#-NQl5r6q8on5AeRMhAF6:-NQl6jZDAermUF9AC3Ns:b-8zd2nq) ([raw file](https://github.com/harness/harness-core/blob/1bf816fbcd43cbe2454ae5cfca24787f9b4c0c0d/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L499)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Can we make it like  - dont want to make any big change 
```      
      entityMetadataHelper.addUserDetails(accountId, entity, header);
if (isEmpty(header.getCreatedBy().getUuid())) {
        log.warn("Unable to audit entity due to missing userId [entity={},type={}]", entity.getClass(), type);
      }```
```

</blockquote></details>

But, doing that way the exception keeps throwing every time the code is executed.

Another option is to identify when the execution comes from API or not, it simply just evaluates if the header has X-API-Key set. What is your opinion on that?

**Comment by abhinav-harness** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/45317#-NQl5r6q8on5AeRMhAF6:-NQl8NGe0y1K-JUaLx2q:b-q4l277) ([raw file](https://github.com/harness/harness-core/blob/1bf816fbcd43cbe2454ae5cfca24787f9b4c0c0d/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L499)):*
<details><summary><i>Previously, Fernando-Dourado (Fernando Dourado) wrote…</i></summary><blockquote>

But, doing that way the exception keeps throwing every time the code is executed.

Another option is to identify when the execution comes from API or not, it simply just evaluates if the header has X-API-Key set. What is your opinion on that?
</blockquote></details>

ok we are getting exception in such cases - can we keep like this (the comment) for now and identify root cause and fix. (let error logs come for more time). ?

**Review by Fernando-Dourado — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45317)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java` line 499 at r1](https://reviewable.io/reviews/harness/harness-core/45317#-NQl5r6q8on5AeRMhAF6:-NQlJfGY9yehpnjTSrgS:b7rcobr) ([raw file](https://github.com/harness/harness-core/blob/1bf816fbcd43cbe2454ae5cfca24787f9b4c0c0d/400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java#L499)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

ok we are getting exception in such cases - can we keep like this (the comment) for now and identify root cause and fix. (let error logs come for more time). ?
</blockquote></details>

The root cause is the operation starting from API execution.

If you do the same using the UI the exception is not thrown because the audited entity has the information of the user doing the action. When it comes from the API we don't know who is the user, we only know the user group.

As I said it is simple to identify and add a condition to don't audit again when it comes from API call.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45317)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
We are going to split this change into two different pieces to reduce the blasting radio of a side effect.

1. Fix the root cause of delegate tag updates
2. Fix the root cause of CaC updates

**Pull request closed without merging**
