### PR TITLE
[fix]: [SRM-13139]: PR Comments refactoring MetricThreshold and DSL Factory, code clean-up

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41776)

### CODE REVIEW

**Comment by n00bitax** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger smartchecks

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 29 of 34 files at r1, 7 of 7 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41776)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/41776#-NJxqJWwCSPc5LNmjjMy:-NJxqJWwCSPc5LNmjjMz:b7w2bmy) ([raw file](https://github.com/harness/harness-core/blob/05c86570405036b5287edb305022cd49ba6a9d69/srm-service/modules/cv-nextgen-service/contracts/delegate/src/main/java/io/harness/cvng/beans/SumologicMetricDataCollectionInfo.java#L61)):*
> ```Java
>         String fullQuery = String.format("%s%s", metric.getQuery(), GROUPING_CLAUSE_NON_HOST);
>         metric.setQuery(fullQuery);
>         dslEnvVariables.put("serviceInstanceIdentifierTag", metric.getServiceInstanceIdentifierTag());
> ```

nit: We can extract out the logic to make the full query and reuse the other code.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java` line 19 at r2](https://reviewable.io/reviews/harness/harness-core/41776#-NJxvbcQCiJbCx3ODCik:-NJxvbcQCiJbCx3ODCil:bbdx6tt) ([raw file](https://github.com/harness/harness-core/blob/c9ea8ef796a0f0b748b24061964079eca323c661/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java#L19)):*
> ```Java
> 
> public class DataCollectionDSLFactory {
>   public static String readLogDSL(DataSourceType dataSourceType) {
> ```

Since its a factory, we can make the name a bit better, like DataCollectionDSLFactory.getDslFromDataSourceType()

**Comment by n00bitax** [comment]
trigger messagecheck

**Comment by n00bitax** [comment]
trigger messagecheck

**Comment by n00bitax** [comment]
trigger ti0

**Comment by n00bitax** [comment]
trigger ti4

**Comment by n00bitax** [comment]
trigger ti0

**Comment by n00bitax** [comment]
trigger ti4

**Pull request merged**
