### PR TITLE
fix: [SRM-13907]: Adding awsSecurityToken in the DSL scripts for AWS data collection calls.

### PR DESCRIPTION
**Pull request by dhruv-harness**
## Describe your changes

If the AWS connector is using iRSA authentication method, the API needs to have the security token to authenticate the request. The delegate change to support this was merged sometime back. This PR adds the token to the DSL scripts which are responsible for data collection. 
Minimum supported version for AWS CloudWatch or AWS Prometheus - 78904

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger ut7

**Comment by dhruv-harness** [comment]
trigger review

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdSFeOBnbkH-edUHgZ:-NSdSFeOBnbkH-edUHg_:b-ctpw1d) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection#L25)):*
> ```
>         Var:bodyMap.put("StartTime",  Env:startTimeSeconds)
>         Var:bodyMap.put("MetricDataQueries", Var:body)
>         Var response = sync-call-aws(url=Env:url, header=Env:commonHeaders, options=Env:commonOptions, body=Var:bodyMap, bodyType=JSON, method=POST, region=Env:region, serviceName=Env:serviceName, secretAccessKey=Env:awsSecretKey, accessKeyId=Env:awsAccessKey, awsTarget=Env:awsTarget, securityToken=Env:awsSecurityToken)
> ```

nit: Please confirm that the ordering doesn't matter for the variables?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdS0kxB-iNGqjBgK5X:-NSdS0kxB-iNGqjBgK5Y:bxg8jwc) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection#L64)):*
> ```
>         Var:dataQueryParamMap.put("step","60s")
>         Var:dataQueryParamMap.put("query", Var:query)
>         Var result = result = sync-call-aws(url=Env:baseUrlForDataCollection, header=Env:commonHeaders, options=Env:commonOptions, method=GET, region=Env:region, serviceName=Env:serviceName, secretAccessKey=Env:awsSecretKey, accessKeyId=Env:awsAccessKey, securityToken=Env:awsSecurityToken, awsQueryParams=Var:dataQueryParamMap)
> ```

We dont need this code right? Was it working fine?



_Code quote:_
```
Var result = result =
```

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdS0kxB-iNGqjBgK5X:-NSdSipg817CkHBeWODr:b-2zst17) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection#L64)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

We dont need this code right? Was it working fine?
</blockquote></details>

Please Test DSL Test for, collectHostData != true too.

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdSFeOBnbkH-edUHgZ:-NSdVxQSBhR-H4YKYQ8Y:bxx4wgr) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection#L25)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: Please confirm that the ordering doesn't matter for the variables?
</blockquote></details>

Ordering does matter, do you see any potential issue here
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdS0kxB-iNGqjBgK5X:-NSdVwOO6i2itCUEGQ-2:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection#L64)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

Please Test DSL Test for, collectHostData != true too. 
</blockquote></details>

ok

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdSFeOBnbkH-edUHgZ:-NSdglQ86yyve9bMzbzd:b-9ebt47) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/cloudwatch/dsl/cloudwatch-metrics.datacollection#L25)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Ordering does matter, do you see any potential issue here
</blockquote></details>

As discussed, the order is correct and only the nullable fields are missing
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection` line 64 at r3](https://reviewable.io/reviews/harness/harness-core/46137#-NSdS0kxB-iNGqjBgK5X:-NSdgsVa3UmBZUSaCyG4:b-2wwwgy) ([raw file](https://github.com/harness/harness-core/blob/6726187d9ae46a54bc7fe285f29d3883f5de5415/srm-service/modules/cv-nextgen-service/service/src/main/resources/prometheus/aws/dsl/metric-collection.datacollection#L64)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Tested, it is working. Also the DSL was working with the typo also. Removed it.

**Review by AbhijithHarness — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46137)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Pull request merged**
