### PR TITLE
feat: [PL-30623]: Fixed roleassignment api when prinipalScopeLevel is set in API

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
When passing principal scope level in role-assignment api,  there was a bug due to which principalScopeLevel was set as null. 
Expectation: it should be set as either the passed value or scope level of role- assignment.
Hence fixed code to work take value directly from api data.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/42034#-NKNVxRL3cH6H44_5FV7:-NKNVxRL3cH6H44_5FV8:b859pu3) ([raw file](https://github.com/harness/harness-core/blob/e8acdaa1e3579c01642332f3e381b03e123fb8b2/access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java#L176)):*
> ```Java
>             .resourceGroupIdentifier("_all_project_level_resources")
>             .roleIdentifier("_project_basic")
>             .principalScopeLevel(PROJECT)
> ```

principalScopeLevel is set here but per test it should be null.
___
*[`access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/42034#-NKNW4kI3CnIrXLcn1eE:-NKNW4kI3CnIrXLcn1eF:b859pu3) ([raw file](https://github.com/harness/harness-core/blob/e8acdaa1e3579c01642332f3e381b03e123fb8b2/access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java#L236)):*
> ```Java
>             .resourceGroupIdentifier("_all_project_level_resources")
>             .roleIdentifier("_project_basic")
>             .principalScopeLevel(PROJECT)
> ```

principalScopeLevel is set here but per test it should be null.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java` line 176 at r2](https://reviewable.io/reviews/harness/harness-core/42034#-NKNVxRL3cH6H44_5FV7:-NKNZfDxEDDsPyT-VNcb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e8acdaa1e3579c01642332f3e381b03e123fb8b2/access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java#L176)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

principalScopeLevel is set here but per test it should be null.
</blockquote></details>

Done.
___
*[`access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java` line 236 at r2](https://reviewable.io/reviews/harness/harness-core/42034#-NKNW4kI3CnIrXLcn1eE:-NKNZfj7DqVbL4lWuqFx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e8acdaa1e3579c01642332f3e381b03e123fb8b2/access-control/service/src/test/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtilsTest.java#L236)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

principalScopeLevel is set here but per test it should be null.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034#-:-NKN_KCyCY6Sl_dK5hlF:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 189 at r3](https://reviewable.io/reviews/harness/harness-core/42034#-NKNdnQ9156rCREVTnst:-NKNrG1u9bZQJOGRgE4W:b-28s4bh) ([raw file](https://github.com/harness/harness-core/blob/e30e9eafa2eecc0e52c73ba14c52d3d41ca432c6/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L189)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

We do not allow principal scope level in case of service account as principal scope level is used in case of inheritance. It should throw an error in case principalScopeLevel doesn’t match the service account scope level. 
</blockquote></details>

 I think we cannot block user from passing principal scope level.
But yes we can have extra check that both the scope levels are equal else throw error.
Right now the issue is irrespective of scope levels are equal or not. We were saving principalScopeLevel as null if it is passed in API due to which list api for service account wasn't including this particular roleassignment (not reflecting in UI).

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: 3 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java` line 203 at r4](https://reviewable.io/reviews/harness/harness-core/42034#-NKSWdY70aq0VHfBCh-P:-NKSWdY70aq0VHfBCh-Q:blktg9y) ([raw file](https://github.com/harness/harness-core/blob/330ce610209fff8cb8220e97f62e7b8d8788d67b/access-control/service/src/main/java/io/harness/accesscontrol/roleassignments/api/RoleAssignmentApiUtils.java#L203)):*
> ```Java
>           && !roleAssignment.getPrincipalScopeLevel().equals(scope.getLevel().toString())) {
>         throw new InvalidRequestException(
>             "Cannot create role assignment for given Principal. Principal should be of same scope as of role assignment.");
> ```

I think if the case is specific for Service Account then error should describe the same and more readable for the end user.
"Cannot create role assignment for given Service Account. PrincipalScopeLevel should be of same scope as of role assignment.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034#-:-NKXLNwa18AgyAF2i5jz:bnfp4nl)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42034)* status: :shipit: complete! ✓

**Pull request merged**
