### PR TITLE
fix: [PL-38637]: Just in time user provision

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
This pr is to support Just in time user provision
Tested out IDP initiated login cases in this sheet in pr env. In local tested vanity url as well (by making some hacks in BE code to mimic accountId as kmpy...)
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48222)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWLyfJlBUftG4dw5_pp:-NWLyfJlBUftG4dw5_pq:b-shyznt) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L125)):*
> ```Java
>       String groupMembershipAttr, Boolean authorizationEnabled, String logoutUrl, String entityIdentifier,
>       String samlProviderType, String clientId, char[] clientSecret, String friendlySamlName, boolean isNGSSO,
>       Boolean jitEnabled, String jitValidationKey, String jitValidationValue) {
> ```

We need to re-factor the code here to start passing a DTO or data object instead of these many arguments. Thanks



_Code quote:_
```Java
  public SSOConfig uploadSamlConfiguration(String accountId, InputStream inputStream, String displayName,
      String groupMembershipAttr, Boolean authorizationEnabled, String logoutUrl, String entityIdentifier,
      String samlProviderType, String clientId, char[] clientSecret, String friendlySamlName, boolean isNGSSO,
      Boolean jitEnabled, String jitValidationKey, String jitValidationValue) {
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 849 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWLzEKh6xEufhaPgRBb:-NWLzEKh6xEufhaPgRBc:b862io2) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L849)):*
> ```Java
>     UserMetadataDTO user = userOpt.get();
>     Scope scope = Scope.builder().accountIdentifier(accountId).orgIdentifier(null).projectIdentifier(null).build();
>     ngUserService.addUserToScope(user.getUuid(), scope, new ArrayList<>(), new ArrayList<>(), USER);
> ```

nit: please extract duplicate code into a separate method



_Code quote:_
```Java
    Optional<UserMetadataDTO> userOpt = ngUserService.getUserByEmail(email, true);
    Preconditions.checkState(userOpt.isPresent(), "Illegal state: user doesn't exists");
    UserMetadataDTO user = userOpt.get();
    Scope scope = Scope.builder().accountIdentifier(accountId).orgIdentifier(null).projectIdentifier(null).build();
    ngUserService.addUserToScope(user.getUuid(), scope, new ArrayList<>(), new ArrayList<>(), USER);
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java` line 292 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWLzSrJArN39EqSmIxQ:-NWLzSrJArN39EqSmIxR:b-jgv6r7) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/120-ng-manager/src/main/java/io/harness/ng/core/invites/remote/InviteResource.java#L292)):*
> ```Java
>   public ResponseDTO<Boolean>
>   completeInvite(@Parameter(description = "email") @QueryParam("email") String email,
>       @Parameter(description = "accountId") @QueryParam("accountId") String accountId) {
> ```

minor: use ACCOUNT_ID_KEY `accountIdentifier` as the query param. thanks



_Code quote:_
```Java
@Parameter(description = "accountId") 
```

**Comment by pbarapatre10** [comment]
*[`122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/resources/AuthenticationSettingsResource.java` line 306 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM-3gdAjXrvyJh9kkZ:-NWM-3gdAjXrvyJh9kk_:b-eai2hj) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/resources/AuthenticationSettingsResource.java#L306)):*
> ```Java
>       @Parameter(description = "Enable Just in time user provision") @FormDataParam("jitEnabled") @DefaultValue(
>           "false") Boolean jitEnabled,
>       @Parameter(description = "Optional Key to match in SAML assertion for JIT user provision") @FormDataParam(
> ```

minor: lets use `just in time` since this will go in harness documentation, thanks



_Code quote:_
```Java
JIT
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 270 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM-i1m2VKafx7kLU2P:-NWM-i1m2VKafx7kLU2Q:bg7kaz7) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L270)):*
> ```Java
>       String accountId, boolean isV2, T baseResponse) {
>     if (null == accountId) {
>       accountId = "kmpySmUISimoRrJL6NL73w";
> ```

This should not be there. Default account can be used, if that is what is intended here. 



_Code quote:_
```Java
accountId = "kmpySmUISimoRrJL6NL73w";
```

**Comment by pbarapatre10** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/invites/api/InviteService.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM04_SE5sC82ouQtJ7:-NWM04_SE5sC82ouQtJ8:bylw2o4) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/123-ng-core-user/src/main/java/io/harness/ng/core/invites/api/InviteService.java#L48)):*
> ```Java
>   boolean completeInvite(Optional<Invite> inviteOpt);
> 
>   boolean completeNgSetupWithoutInvite(String email, String accountId);
> ```

minor: This method name should be completeUserNgSetupWithoutInvite? 



_Code quote:_
```Java
completeNgSetupWithoutInvite(
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java` line 233 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM0ZJq2GWEalBq5hwv:-NWM0ZJq2GWEalBq5hww:bvu62j0) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/AuthenticationManager.java#L233)):*
> ```Java
>         log.info("User exists but Jit is not enabled for this SSO");
>       }
>       throw ex;
> ```

minor: we should be throwing different error when JIT is not enabled on an account vs when failed to add user to account



_Code quote:_
```Java
      } catch (WingsException e) {
        log.info("User exists but Jit is not enabled for this SSO");
      }
      throw ex;
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 190 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM0s7O7Dbhdje6WJ3D:-NWM0s7O7Dbhdje6WJ3E:bhzu0bl) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L190)):*
> ```Java
>         if ((null != user.getUserAccountLevelDataMap().get(accountId))
>             && isNotEmpty(user.getUserAccountLevelDataMap().get(accountId).getSourceOfProvisioning())
>             && JIT.equals(user.getUserAccountLevelDataMap().get(accountId).getSourceOfProvisioning().get(NG))) {
> ```

These can be combined in a single if clause, thanks



_Code quote:_
```Java
      if (null != user.getUserAccountLevelDataMap()) {
        if ((null != user.getUserAccountLevelDataMap().get(accountId))
            && isNotEmpty(user.getUserAccountLevelDataMap().get(accountId).getSourceOfProvisioning())
            && JIT.equals(user.getUserAccountLevelDataMap().get(accountId).getSourceOfProvisioning().get(NG))) {
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 763 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM12yN0_oj9Dj05AD7:-NWM12yN0_oj9Dj05AD8:bbkpnfg) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L763)):*
> ```Java
>         }
>       }
>     }
> ```

lets extract duplicate code in a method, thanks



_Code quote:_
```Java
    List<AttributeStatement> attributeStatements = samlAssertionValue.getAttributeStatements();
    for (AttributeStatement attributeStatement : attributeStatements) {
      for (Attribute attribute : attributeStatement.getAttributes()) {
        if (attribute.getName().equals(jitValidationKey)) {
          for (XMLObject xmlObject : attribute.getAttributeValues()) {
            final String value = getAttributeValue(xmlObject);
            if (Objects.equals(value, jitValidationValue)) {
              return true;
            }
          }
        }
      }
    }
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 814 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM1jEx1a8dhhm4HgeJ:-NWM1jEx1a8dhhm4HgeK:b-6cbkmz) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L814)):*
> ```Java
>           && checkForKeyValuePairAndMatchWithAssertion(samlResponseString, samlSettings)) {
>         return createNewUserOrAddUserToAccountViaJIT(nameId, samlSettings.getAccountId());
>       } else if (e.getCode() == ACCESS_DENIED
> ```

minor: combine the two if clauses 



_Code quote:_
```Java
      if (e.getCode() == USER_DOES_NOT_EXIST
          && checkForKeyValuePairAndMatchWithAssertion(samlResponseString, samlSettings)) {
        return createNewUserOrAddUserToAccountViaJIT(nameId, samlSettings.getAccountId());
      } else if (e.getCode() == ACCESS_DENIED
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 833 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM1zCk8j9YjMYD8UfI:-NWM1zCk8j9YjMYD8UfJ:bebp9yp) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L833)):*
> ```Java
>     }
>     SamlClient samlClient = samlClientService.getSamlClient(samlSettings);
>     SamlResponse samlResponse = samlClient.decodeAndValidateSamlResponse(samlResponseString);
> ```

no need to recompute samlResponse here, since samlResponse was computed in caller



_Code quote:_
```Java
SamlResponse samlResponse = samlClient.decodeAndValidateSamlResponse(samlResponseString);
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlClientService.java` line 131 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM2pjh74q4Z3vfZRTf:-NWM2pjh74q4Z3vfZRTg:bakt77e) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/saml/SamlClientService.java#L131)):*
> ```Java
>     SSORequest ssoRequest = new SSORequest();
>     try {
>       SamlSettings setting = ssoSettingService.getSamlSettingsByAccountId(account.getUuid());
> ```

Handle for multiple SAML scenario, thanks



_Code quote:_
```Java
ssoSettingService.getSamlSettingsByAccountId(account.getUuid());
```

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlClientService.java` line 225 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM32FMEUly-qvMWFzi:-NWM32FMEUly-qvMWFzj:bmrgrzu) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/saml/SamlClientService.java#L225)):*
> ```Java
>         }
>       }
>     } catch (SamlException | URISyntaxException | IOException e) {
> ```

seems duplicate code, let's re-use existing method or refactor, thanks



_Code quote:_
```Java
    try {
      List<SamlSettings> samlSettings = ssoSettingService.getSamlSettingsListByAccountId(account.getUuid());
      Map<String, SamlClientFriendlyNameProviderType> samlClientMap =
          getSamlClientListFromSamlSettingListWithJitEnabled(samlSettings);
      if (samlClientMap.isEmpty()) {
        throw new WingsException(ErrorCode.USER_DOES_NOT_EXIST);
      }
      for (Map.Entry<String, SamlClientFriendlyNameProviderType> entry : samlClientMap.entrySet()) {
        if (entry.getValue() != null && entry.getValue().getSamlClient() != null) {
          SSORequest ssoRequest = new SSORequest();
          populateRedirectUriValueInSSORequest(entry.getValue().getSamlClient(), isTestConnectionRequest, ssoRequest);
          ssoRequest.setFriendlySamlName(entry.getValue().getFriendlySamlName());
          ssoRequest.setSsoId(entry.getKey());
          ssoRequest.setSamlProviderType(entry.getValue().getSamlProviderType());
          ssoRequests.add(ssoRequest);
        }
      }
    } catch (SamlException | URISyntaxException | IOException e) {
```

**Comment by pbarapatre10** [comment]
*[`930-ng-core-clients/src/main/java/io/harness/invites/remote/NgInviteClient.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM3S9P-6MoOSfwfoK4:-NWM3S9P-6MoOSfwfoK5:b-olb4ss) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/930-ng-core-clients/src/main/java/io/harness/invites/remote/NgInviteClient.java#L33)):*
> ```Java
> public interface NgInviteClient {
>   String INVITE_POST_SIGNUP_API = "invites/complete/";
>   String INVITE_JIT = "invites/completeJIT/";
> ```

minor: in url we use a `-` format, so `invites/complete-jit` would be better



_Code quote:_
```Java
"invites/completeJIT/"
```

**Comment by shashank-harness** [comment]
Please do all changes as requested and we can merge it post that.

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java` line 763 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM12yN0_oj9Dj05AD7:-NWuYxf13bNw_SS2i_YH:bnaw72m) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/authentication/SamlBasedAuthHandler.java#L763)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

lets extract duplicate code in a method, thanks
</blockquote></details>

resolving, please handle if there is duplicate code in separate PR, thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/security/saml/SamlClientService.java` line 225 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM32FMEUly-qvMWFzi:-NWuZDK94DB4ok43aFSC:b-h85w1) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/security/saml/SamlClientService.java#L225)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

seems duplicate code, let's re-use existing method or refactor, thanks
</blockquote></details>

resolving, please ensure duplicate code is separated out in a separate PR, thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java` line 125 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWLyfJlBUftG4dw5_pp:-NWuZNFj7iz2WYYW2VGG:b-d436sh) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/400-rest/src/main/java/software/wings/service/impl/SSOServiceImpl.java#L125)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

We need to re-factor the code here to start passing a DTO or data object instead of these many arguments. Thanks
</blockquote></details>

There is a JIRA already created to start passing a DTO instead of these many arguments, will assign it to you. Handle it in separate PR, thanks

**Comment by pbarapatre10** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java` line 2149 at r10](https://reviewable.io/reviews/harness/harness-core/48222#-NWuZvb76uhRVfgA5whn:-NWuZvb76uhRVfgA5who:bvw28vb) ([raw file](https://github.com/harness/harness-core/blob/41fc4fee6725a543c3f52f1608b2666e7fb69636/400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java#L2149)):*
> ```Java
>       user.setEmailVerified(true);
>       user.setAppId(GLOBAL_APP_ID);
>       user.setAccounts(new ArrayList<>());
> ```

minor this can be done in a single line of builder, instead of setters: 
anUser() .email(email).name(email) . Also name can be set differently from email, check in the saml attribute if name comes, I remember it comes as `displayname` attribute. Handle in separate PR, thanks



_Code quote:_
```Java
      user = anUser().build();
      user.setEmail(email.trim().toLowerCase());
      user.setName(email.trim().toLowerCase());
      user.setRoles(new ArrayList<>());
      user.setEmailVerified(true);
      user.setAppId(GLOBAL_APP_ID);
      user.setAccounts(new ArrayList<>());
```

**Comment by pbarapatre10** [comment]
*[`970-ng-commons/src/main/java/io/harness/ng/core/common/beans/UserSource.java` line 14 at r3](https://reviewable.io/reviews/harness/harness-core/48222#-NWM3bET5G5MpeVL2FXz:-NWuaBlK9-i-GqPOABYE:b-92c14v) ([raw file](https://github.com/harness/harness-core/blob/3699d930b0d7e0ce201b82afb4b5e920da8818a4/970-ng-commons/src/main/java/io/harness/ng/core/common/beans/UserSource.java#L14)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

@shashank-harness please review this, if this can change anything on the migration or impact anything else. 
</blockquote></details>

This was discussed with @shashank-harness and the ned for JIT is correct. thanks

**Review by pbarapatre10 — DISMISSED** [review]
> Reviewed 11 of 13 files at r1, 3 of 12 files at r2, 5 of 7 files at r4, 2 of 5 files at r6, 2 of 2 files at r7, 3 of 4 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48222)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Comment by VikasMaddukuriHarness** [comment]
trigger uts

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48222)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
lgtm

**Comment by shashank-harness** [comment]
@VikasMaddukuriHarness Before merging please update Testing done in PR description itself.

**Pull request merged**
