### PR TITLE
fix: [CDS-77104]: Logs keys incorrect for retry execution for CI stage with parallelism enabled

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes

Logs were not printing properly for each stage in matrix
Explanation: Added comments in the code
Testing: Locally and updated the existing unit test

Local Testing: Created a two stage pipeline. First stage - matrix (with shell script printing the name of stage) and second stage custom with failed shell script.

Also tested retry on matrix stage - failed on the stage of matrix and then retried.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51982)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger uts

**Comment by prashantsharma04** [comment]
trigger uts

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51982)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/51982#-Nc_uGTMAptCv5qBUlUB:-Nc_uGTNBsTVxO9nHBjS:b-w3htfo) ([raw file](https://github.com/harness/harness-core/blob/f33a0f7a1d1e9df74db841add71d02797fb982e3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L195)):*
> ```Java
>     previous execution. So the correct data will be copied in all combinations.
>      */
>     if (node.getNodeType() == NodeType.PLAN_NODE || node.getNodeType() == NodeType.IDENTITY_PLAN_NODE) {
> ```

I think this if condition is redundant. This is always true.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/51982#-Nc_uGTMAptCv5qBUlUB:-Nca3q5F15QZlifkC9be:b-o1k46q) ([raw file](https://github.com/harness/harness-core/blob/f33a0f7a1d1e9df74db841add71d02797fb982e3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L195)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think this if condition is redundant. This is always true.
</blockquote></details>

@yuvrajharness , has already added this code I believe. @yuvrajharness  can you check if this issue is in your branch.

**Comment by yuvrajharness** [comment]
> _[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/51982#-Nc_uGTMAptCv5qBUlUB:-Nca3q5F15QZlifkC9be:b-o1k46q) ([raw file](https://github.com/harness/harness-core/blob/f33a0f7a1d1e9df74db841add71d02797fb982e3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L195)):_
> 
> Previously, brijeshdhakar (Brijesh Dhakar) wrote…
> @yuvrajharness , has already added this code I believe. @yuvrajharness can you check if this issue is in your branch.

@sahilhindwani-harness I haven't written any code for the backend part of the SSCA. Kindly reach out to Inder or Deep from the SSCA Team

**Review by archit-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51982)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 195 at r2](https://reviewable.io/reviews/harness/harness-core/51982#-Nc_uGTMAptCv5qBUlUB:-NcaKbm_4MkPtPaPP5C7:bjdy1o2) ([raw file](https://github.com/harness/harness-core/blob/f33a0f7a1d1e9df74db841add71d02797fb982e3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L195)):*
<details><summary><i>Previously, yuvrajharness (Yuvraj Verma) wrote…</i></summary><blockquote>

@sahilhindwani-harness I haven't written any code for the backend part of the SSCA. Kindly reach out to Inder or Deep from the SSCA Team
</blockquote></details>

@Y0709 ^^

**Comment by prashantsharma04** [comment]
trigger uts

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51982)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]

**Pull request merged**
