### PR TITLE
[feat]: [PL-29652]: Fix the cycles in logging of 980-commons

### PR DESCRIPTION
**Pull request by Raghav-Murali**
## Describe your changes

While trying to break 980-commons exception module into a smaller Bazel target it gives raise to multiple cyclic dependencies among the sub-modules. These cycles need to be fixed before adding Bazel build files in all the modules.

This PR fixes the below cycle of 980-commons:

[Cycle]

.-> //980-commons/src/main/java/io/harness/exception:module 
|   //980-commons/src/main/java/io/harness/logging:module 
`-- //980-commons/src/main/java/io/harness/exception:module 

The changes are mainly refactoring of code such that it gets rid of the above cycle.

Tested the below scenarios in local and PR env -

* End to End K8s workflow in PR env.
* Secret manager and secret additions in PR and local env

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)

### CODE REVIEW

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by gn-harness — DISMISSED** [review]
> Reviewed 80 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: 80 file(s) to review. 1 of 2 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 80 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: :shipit: complete! ✓

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Comment by Raghav-Murali** [comment]
trigger feature-build

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 62 of 80 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: 18 file(s) to review.

**Review by puthrayaharness — APPROVED** [review]

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 62 of 80 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819#-:-NHYUaFc5kqpkHEsil7K:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 62 of 80 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39819)* status: :shipit: complete! ✓

**Pull request merged**
