### PR TITLE
feat: [DEL-3184]: remove orgIdentifier and projectIdentifier from yaml

### PR DESCRIPTION
**Pull request by arpit3107**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3918 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-Myv9pM_AsSasadM2i0b:-Myv9pM_AsSasadM2i0c:b-c5wpzj) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3918)):*
> ```Java
>       return delegateTokenGlobalContextData.getTokenName();
>     }
>     return null;
> ```

Returning nulls is generally a bad idea. Is it expected that token doesn't exist? If yes consider returning Optional<String> instead. If it's an erroneous case, throw exceptions. 
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3927 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyvA6Ve4FI_tjz5c2Ba:-MyvA6Ve4FI_tjz5c2Bb:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3927)):*
> ```Java
>       return delegateTokenDetails != null
>           ? DelegateEntityOwnerHelper.extractOrgIdFromOwnerIdentifier(delegateTokenDetails.getOwnerIdentifier())
>           : null;
> ```

same
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3929 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyvA5jX7JWjVXNewuoX:-MyvA5jX7JWjVXNewuoY:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3929)):*
> ```Java
>           : null;
>     }
>     return null;
> ```

same
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3938 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyvA7QLB5DfRg3d3Ize:-MyvA7QLB5DfRg3d3Izf:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3938)):*
> ```Java
>       return delegateTokenDetails != null
>           ? DelegateEntityOwnerHelper.extractProjectIdFromOwnerIdentifier(delegateTokenDetails.getOwnerIdentifier())
>           : null;
> ```

same
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3940 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyvA81U1lsV2G6vsmo8:-MyvA81U1lsV2G6vsmo9:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3940)):*
> ```Java
>           : null;
>     }
>     return null;
> ```

same

**Comment by raghuAtWings** [comment]
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2372 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyxL1a37iSYTs547rRy:-MyxL1a37iSYTs547rRz:b-53ln9a) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2372)):*
> ```Java
>     String projectIdentifier = delegateParams.getProjectIdentifier() != null
>         ? delegateParams.getProjectIdentifier()
>         : getProjectIdentifierUsingTokenFromGlobalContext(delegateParams.getAccountId());
> ```

we also need to make sure that this doesn't cause the same issue as the tokenName for the delegate because of threadLocal

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 2372 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-MyxL1a37iSYTs547rRy:-MyzXJ4GDjc9uLXIZUlc:b-v51ynv) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2372)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we also need to make sure that this doesn't cause the same issue as the tokenName for the delegate because of threadLocal
</blockquote></details>

That will not happen. There is another pr to fix that bug.
___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3918 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-Myv9pM_AsSasadM2i0b:-MyvV4OY9IXneJbelRDl:bom4egs) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3918)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Returning nulls is generally a bad idea. Is it expected that token doesn't exist? If yes consider returning Optional<String> instead. If it's an erroneous case, throw exceptions. 
</blockquote></details>

Token should always be there, unless something unexpected happens. But even in that case, it shouldnt throw exceptions

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)* status: 1. unresolved discussions. 

___
*[400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, line 3918 at r1](https://reviewable.io/reviews/harness/harness-core/31711#-Myv9pM_AsSasadM2i0b:-Mz-QHTo9OlHyt6TcYAc:bvix3ia) ([raw file](https://github.com/harness/harness-core/blob/33f222b34ceb00b2685de6ca20c0391a24c36f38/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3918)):*
<details><summary><i>Previously, arpit3107 (Arpit Tiwari) wrote…</i></summary><blockquote>

Token should always be there, unless something unexpected happens. But even in that case, it shouldnt throw exceptions
</blockquote></details>

Why not? Don't be afraid to throw exceptions, even if it results in HTTP500 that's perfectly fine. This way you can e.g. contaminate the DB when error case does happen which would put it in inconsistent state (e.g. token is not in the DB record, but we expect it that it's always there), also you increase the code complexity downstream because now everyone needs to check if the token really exists (also even when reading from the DB). Wheras if you say that this is impossible scenario you don't need to check it again anywhere

**Review by mdmilic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31711)* status: 1. unresolved discussions.

**Comment by sunilgupta-harness** [comment]
reviewable status is not getting reflected correctly

**Pull request merged**
