### PR TITLE
feat: [PIE-2728]: custom stage execution implementation

### PR DESCRIPTION
**Pull request by vaibhav-si**
Change Log:

- Added plan creator, filter creator, variable creator, step for custom stage
- Plan creation fix to propagate dependency metadata across services

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`860-orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java` line 43 at r1](https://reviewable.io/reviews/harness/harness-core/33494#-N2prHWU9RbLZd3FBtYs:-N2prHWU9RbLZd3FBtYt:btykhl2) ([raw file](https://github.com/harness/harness-core/blob/78a81a27b6ed941f56692ec9e5e5820c2a6f2fe8/860-orchestration-steps/src/main/java/io/harness/steps/customstage/CustomStageVariableCreator.java#L43)):*
> ```Java
> 
>     return responseMap;
>   }
> ```

v1 impl is not required, you can return empty, we will take this up to remove it as well



_Code quote:_
```Java
  public LinkedHashMap<String, VariableCreationResponse> createVariablesForChildrenNodes(
      VariableCreationContext ctx, YamlField config) {
    LinkedHashMap<String, VariableCreationResponse> responseMap = new LinkedHashMap<>();

    YamlField executionField =
        config.getNode().getField(YAMLFieldNameConstants.SPEC).getNode().getField(YAMLFieldNameConstants.EXECUTION);
    if (VariableCreatorHelper.isNotYamlFieldEmpty(executionField)) {
      Map<String, YamlField> executionDependencyMap = new HashMap<>();
      executionDependencyMap.put(executionField.getNode().getUuid(), executionField);
      responseMap.put(executionField.getNode().getUuid(),
          VariableCreationResponse.builder()
              .dependencies(DependenciesUtils.toDependenciesProto(executionDependencyMap))
              .build());
    }

    return responseMap;
  }
```

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 11 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: :shipit: complete! ✓

**Review by archit-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494#-:-N2vCa024BFSXQU_oT4v:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 8 of 11 files at r1, 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494#-:-N33iVgJE_ZIimhNzzi-:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33494)* status: :shipit: complete! ✓

**Pull request merged**
