### PR TITLE
fix: [PL-24042]: connector error handling when delegates are not avai…

### PR DESCRIPTION
**Pull request by pbarapatre10**
…lable or inactive

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31975)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31975#-Mzo2Gdg04uV02bq6sIh:-Mzo2Gdg04uV02bq6sIi:bhb8j4w) ([raw file](https://github.com/harness/harness-core/blob/252c90733f786a7704fc69b35fd918aacd272059/910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java#L46)):*
> ```Java
>           message, new InvalidRequestException(statusRuntimeException.getMessage(), exception));
>     }
>     return new InvalidRequestException(exception.getMessage(), exception);
> ```

I see an implementation issue here in the handler. Incoming "exception" shouldn't be again attached in the final exception being returned. Handler's main job is to convert the runtime exception into wings exception. There shouldn't be any trace of unknown exception at the end of it.
Just make sure it doesn't impact you in some way @pbarapatre10 .

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31975#-:-Mzo2lck9YTsQH7UyqVx:bnfp4nl)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
*[910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31975#-Mzo2Gdg04uV02bq6sIh:-Mzo3lULDOyKbgkAD71M:b-csxlnq) ([raw file](https://github.com/harness/harness-core/blob/252c90733f786a7704fc69b35fd918aacd272059/910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java#L46)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I see an implementation issue here in the handler. Incoming "exception" shouldn't be again attached in the final exception being returned. Handler's main job is to convert the runtime exception into wings exception. There shouldn't be any trace of unknown exception at the end of it.
Just make sure it doesn't impact you in some way @pbarapatre10 . 
</blockquote></details>

Ok, will convert the incoming exception to wings exception in that case. Thanks @mohitg0795

**Comment by mohitg0795** [comment]
*[910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java, line 46 at r1](https://reviewable.io/reviews/harness/harness-core/31975#-Mzo2Gdg04uV02bq6sIh:-Mzo4L1j3hJ1-enaZny-:b-xb5p7p) ([raw file](https://github.com/harness/harness-core/blob/252c90733f786a7704fc69b35fd918aacd272059/910-delegate-service-driver/src/main/java/io/harness/exception/DelegateServiceDriverExceptionHandler.java#L46)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Ok, will convert the incoming exception to wings exception in that case. Thanks @mohitg0795  
</blockquote></details>

I think this handler is something that we don't own. Also, I see its not something that you actually intend to change, you only did some code refactor. So, it is fine if it works as expected for us, we can go ahead with it. If its creating any issue, then we can correct the handler as well.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31975)* status: :shipit: complete! ✓

**Pull request merged**
