### PR TITLE
[feat]: [SRM-13106]: Added flag for sumologic as a health source.

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)

### CODE REVIEW

**Review by deepak-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: 2 file(s) to review. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/40407#-NHbsUwZ1__ZkewaQlFA:-NHbsUw_CqYEjxg3nOqf:bg3wcv1) ([raw file](https://github.com/harness/harness-core/blob/e9850a834883de178ba2c7bd17597a9709f6180a/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L25)):*
> ```Java
>   public static final String SRM_COMPOSITE_SLO = "SRM_COMPOSITE_SLO";
> 
>   public static final String SRM_SUMO = "SRM_SUMO";
> ```

nit: not sure if it is required in backend. adding to feature name class should be fine.

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: 2 file(s) to review. 1. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/40407#-NHbsUwZ1__ZkewaQlFA:-NHbw9m1CcBgnbEDQU4z:b-6g9nam) ([raw file](https://github.com/harness/harness-core/blob/e9850a834883de178ba2c7bd17597a9709f6180a/300-cv-nextgen/src/main/java/io/harness/cvng/core/utils/FeatureFlagNames.java#L25)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

nit: not sure if it is required in backend. adding to feature name class should be fine. 
</blockquote></details>

removing it then, will add later if its required then

**Review by dhruv-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/40407#-NHc1Usy36VbdwM8swZI:-NHc1Usy36VbdwM8swZJ:b8ouevz) ([raw file](https://github.com/harness/harness-core/blob/2677880f19f5273b9368de17d42e452d0f7a8bc0/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L399)):*
> ```Java
>   ELK_HEALTH_SOURCE("Will enable ELK health source in SRM", HarnessTeam.CV),
>   SRM_COMPOSITE_SLO("Flag to start creating composite SLOs", HarnessTeam.CV),
>   SRM_SUMO("Will enable Sumologic health source in SRM", HarnessTeam.CV),
> ```

We should add the enum in the last.

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 399 at r2](https://reviewable.io/reviews/harness/harness-core/40407#-NHc1Usy36VbdwM8swZI:-NHc3zc31paN4qgDc3Xh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2677880f19f5273b9368de17d42e452d0f7a8bc0/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L399)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We should add the enum in the last.
</blockquote></details>

Done.

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: 1 file(s) to review.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40407)* status: :shipit: complete! ✓

**Pull request merged**
