### PR TITLE
[feat]: [PIE-9437]: Draft for post-prod rollback

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46053)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFDi097Jud3GCOhapt:-NSFDi0A3DGcYVQ7Drrd:b-d4e9re) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java#L49)):*
> ```Java
>   @With @Builder.Default Boolean useAdviserObtainments = false;
>   @With List<AdviserObtainment> adviserObtainments;
>   @With ExecutionMode executionMode;
> ```

As discussed, Not required



_Code quote (from pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java):_
```Java
        String postExecutionRollbackStageId = ambiance.getMetadata().getPostExecutionRollbackStageId();
        if (postExecutionRollbackStageId.equals(child.getChildNodeId())
            && ambiance.getMetadata().getRollbackStageStrategyMetadata().equals(child.getStrategyMetadata())) {
          ambianceForChild =
              AmbianceUtils.cloneBuilder(ambiance, ambiance.getLevelsCount())
                  .setMetadata(ambiance.getMetadata().toBuilder().setPostExecutionRollbackUnderStrategy(true))
                  .build();
        }
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFDuQ09-YDOQiJ8zjs:-NSFDuQ09-YDOQiJ8zjt:bbrivz8) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L34)):*
> ```protobuf
>   ExecutionMode executionMode = 19;
>   string postExecutionRollbackStageId = 20;
>   bool postExecutionRollbackUnderStrategy = 21;
> ```

move to another message and use that here. 
try to use repeat. 



_Code quote:_
```protobuf
  string postExecutionRollbackStageId = 20;
  bool postExecutionRollbackUnderStrategy = 21;
  io.harness.pms.contracts.execution.StrategyMetadata rollbackStageStrategyMetadata = 22;
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 69 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFEE_y9P9gs3WFg0aE:-NSFEE_y9P9gs3WFg0aF:b86pfk2) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L69)):*
> ```Java
>   public ExecutionMetadata transformExecutionMetadata(ExecutionMetadata executionMetadata, String planExecutionID,
>       ExecutionTriggerInfo triggerInfo, String accountId, String orgIdentifier, String projectIdentifier,
>       String stageUuid, ExecutionMode executionMode) {
> ```

nit: PrevStageExecutionId

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFEh0e8nncE3TvX5Tb:-NSFEh0e8nncE3TvX5Tc:b-q7whje) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L71)):*
> ```Java
>       String stageUuid, ExecutionMode executionMode) {
>     NodeExecution rollbackStageNodeExecution = nodeExecutionService.getWithFieldsIncluded(
>         stageUuid, Set.of(NodeExecutionKeys.planNode, NodeExecutionKeys.ambiance));
> ```

planNode might not be required

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 285 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFFCuJ48uEiQPbDCtD:-NSFFCuJ48uEiQPbDCtE:bnkisf8) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L285)):*
> ```Java
>             updatedNode.withAdviserObtainments(adviserObtainments)
>                 .withUseAdviserObtainments(true)
>                 .withExecutionMode(executionMode));
> ```

nit: not required



_Code quote:_
```Java
ollbackStageFQN
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java` line 273 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFFSWy5ghvLaZO6G7Z:-NSFFSWy5ghvLaZO6G7_:b-7pj82x) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeExecutionHelper.java#L273)):*
> ```Java
>     for (Node planNode : createdPlan.getPlanNodes()) {
>       if (EmptyPredicate.isEmpty(planNode.getAdvisorObtainmentsForExecutionMode())
>           || executionMode == ExecutionMode.POST_EXECUTION_ROLLBACK
> ```

executionMode = ExecutionMode.POST_EXECUTION_ROLLBACK
if (!stageFqnsToRollback.contains(planNode.getStageFqn()) {
   executionMode = ExecutionMode.NORMAL;
}



_Code quote:_
```Java
ExecutionMode.POST_EXECUTION_ROLLBACK
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFHD3H3JZ4XNhqj14q:-NSFHD3H3JZ4XNhqj14r:b-dpknmu) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyInternalStep.java#L166)):*
> ```Java
>   private ChildExecutableResponse getChildFromNodeExecutions(
>       NodeExecution childNodeExecution, NodeExecution originalNodeExecution, String planId) {
>     Node node = planService.fetchNode(childNodeExecution.getPlanId(), childNodeExecution.getNode().getUuid());
> ```

Can we use executionMode over here so as not to change any existing flows?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFHMMkA2602c6FAzLu:-NSFHMMkA2602c6FAzLv:bj7s5rj) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L151)):*
> ```Java
>       @PathParam(NGCommonEntityConstants.PLAN_KEY)
>       @Parameter(description = PlanExecutionResourceConstants.PLAN_EXECUTION_ID_PARAM_MESSAGE) @ResourceIdentifier
>       @NotNull String planExecutionId, @QueryParam("stageNodeExecutionId") @NotNull String stageNodeExecutionId);
> ```

Can we accept list of Strings here?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46053)* status: 10 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 151 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFHMMkA2602c6FAzLu:-NSF_J644jopdNzmpmwU:bhy9ot6) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L151)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we accept list of Strings here?
</blockquote></details>

Will do.
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFDuQ09-YDOQiJ8zjs:-NSF_RwUCrf8sdfZ6yIt:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L34)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

move to another message and use that here. 
try to use repeat. 
</blockquote></details>

Done
___
*[`pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/46053#-NSFDi097Jud3GCOhapt:-NSF_QeK7LBQQQrWHxqr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49652e8e964b72487ed93b4b889466965babbe33/pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan/IdentityPlanNode.java#L49)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As discussed, Not required
</blockquote></details>

Done.

**Pull request closed without merging**
