### PR TITLE
techdebt: [PIE-3465]: Increase code-coverage for 882-pms-sdk-core

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32412)

### CODE REVIEW

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32412)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32412)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/resolver/RefObjectUtilsTest.java, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/32412#-N0F9NfE061eLSDelS8i:-N0F9NfE061eLSDelS8j:bys1txb) ([raw file](https://github.com/harness/harness-core/blob/d7b886de646854cb8d2df5388bd6075a7318d8a3/882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/resolver/RefObjectUtilsTest.java#L17)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class RefObjectUtilsTest extends PmsSdkCoreTestBase {
> ```

Can this be CategoryTest?



_Code quote:_
```Java
PmsSdkCoreTestBase
```
___
*[882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/variables/ChildrenVariableCreatorTest.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32412#-N0F9cMX2DzRZXY4HNte:-N0F9cMX2DzRZXY4HNtf:b-z2dfta) ([raw file](https://github.com/harness/harness-core/blob/d7b886de646854cb8d2df5388bd6075a7318d8a3/882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/variables/ChildrenVariableCreatorTest.java#L38)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class ChildrenVariableCreatorTest extends PmsSdkCoreTestBase {
> ```

Can we categoryTest?



_Code quote:_
```Java
PmsSdkCoreTestBase
```

**Comment by sahilhindwani-harness** [comment]
*[882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/resolver/RefObjectUtilsTest.java, line 17 at r1](https://reviewable.io/reviews/harness/harness-core/32412#-N0F9NfE061eLSDelS8i:-N0FD01S7UMxAk0aupRH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d7b886de646854cb8d2df5388bd6075a7318d8a3/882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/resolver/RefObjectUtilsTest.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can this be CategoryTest?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/variables/ChildrenVariableCreatorTest.java, line 38 at r1](https://reviewable.io/reviews/harness/harness-core/32412#-N0F9cMX2DzRZXY4HNte:-N0FD1mU-cZ05z7RV8Px:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d7b886de646854cb8d2df5388bd6075a7318d8a3/882-pms-sdk-core/src/test/java/io/harness/pms/sdk/core/variables/ChildrenVariableCreatorTest.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we categoryTest?
</blockquote></details>

Done.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32412#-:-N0FHfUI7Ide75wNAb_A:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32412)* status: :shipit: complete! ✓

**Pull request merged**
