### PR TITLE
feat: [SPG-16]: remove velocity-1.7.jar

### PR DESCRIPTION
**Pull request by shivagowda**
old approved PR: https://github.com/harness/harness-core/pull/33932/files

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34179)

### CODE REVIEW

**Review by jennyjames21 — APPROVED** [review]

**Comment by jennyjames21** [comment]
:lgtm:

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34179)* status: :shipit: complete! ✓

**Comment by shivagowda** [comment]
trigger ti0

**Comment by shivagowda** [comment]
trigger ti0

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34179)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34179)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]

**Pull request merged**
