### PR TITLE
[fix]: [PL-0]: Remove SMTP password from codebase

### PR DESCRIPTION
**Pull request by ankit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30079)

### CODE REVIEW

**Comment by ankit-harness** [comment]
trigger ti0
trigger ti1
trigger ti2
trigger ti3
trigger ti4
trigger ft1
trigger ft2

**Comment by ankit-harness** [comment]
trigger ft1

**Comment by ankit-harness** [comment]
trigger ti0

**Comment by ankit-harness** [comment]
trigger ti1

**Comment by ankit-harness** [comment]
trigegr ti2

**Comment by ankit-harness** [comment]
trigger ti2

**Comment by ankit-harness** [comment]
trigger ti3

**Comment by ankit-harness** [comment]
trigger ti4

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30079#-:-MtlO0P57kXm_5SpTQmM:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30079#-:-MtlRGQ867H48WhH7jpR:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by karansiwach — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30079)* status: :shipit: complete! ✓

**Pull request merged**
