### PR TITLE
feat: [CDS-43512]: Elastigroup deploy YAML changes

### PR DESCRIPTION
**Pull request by filip5rovic**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 25 of 26 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 817 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOhd_W6QwThl8dGe5V:-NFOhd_W6QwThl8dGe5W:bg5pe6v) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L817)):*
> ```Java
>             .setName("Elastigroup Deploy")
>             .setType(StepSpecTypeConstants.ELASTIGROUP_DEPLOY)
>             .setStepMetaData(StepMetaData.newBuilder().addCategory(ELASTIGROUP).addFolderPaths("Elastigroup").build())
> ```

@arvind-choudhary-h  what should be the folder category for Spot steps?
@filip5rovic we also need to specify the feature flag here so we don't display the step until GA
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiF3w0UewRd2-WWhA:-NFOiF3w0UewRd2-WWhB:bqiynql) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @RecasterAlias("io.harness.cdng.spot.elastigroup.deploy.ElastigroupDeployServiceWrapper")
> public class ElastigroupDeployServiceWrapper {
> ```

why do we need this wrapper? can you pls put the generated yaml for this.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiXctEGvov11DaLOZ:-NFOiXctEGvov11DaLO_:bmh5egj) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L29)):*
> ```Java
> @Slf4j
> @OwnedBy(CDP)
> public class ElastigroupDeployStep extends TaskExecutableWithRollbackAndRbac<CommandTaskResponse> {
> ```

why do we use the commandtask req/response here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiS6w0KO8yKn0Ytou:-NFOiS6w0KO8yKn0Ytov:b-v3vthz) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L58)):*
> ```Java
>       taskResponse = responseDataSupplier.get();
>     } catch (Exception ex) {
>       log.error("Error while processing Command Task response: {}", ex.getMessage(), ex);
> ```

not a command task :smile:

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 8 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 817 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOhd_W6QwThl8dGe5V:-NFSwDBF8zKz1FEdw4g7:b-di4k8x) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L817)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

@arvind-choudhary-h  what should be the folder category for Spot steps?
@filip5rovic we also need to specify the feature flag here so we don't display the step until GA
</blockquote></details>

@arvind-choudhary-h Do we already have a feature flag for this? Maybe in some other PR (for service or infra)
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiF3w0UewRd2-WWhA:-NFSva9-DN2_haGJy7xp:bjg9yx4) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why do we need this wrapper? can you pls put the generated yaml for this.
</blockquote></details>

Here is yaml for whole step, wrapper is for old and new service part, since it can be Count or Percentage. It's similar to what we had for Command Units (Script, Copy, etc)



_Code snippet:_
```Java
identifier: ElastigroupDeploy
type: ElastigroupDeploy
name: "Elastigroup Deploy"
spec: 
  newService: 
    spec: 
      percentage: 100
    type: Percentage
  oldService: 
    spec: 
      count: 50
    type: Count
timeout: 10m
failureStrategies: []
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiXctEGvov11DaLOZ:-NFSvvShBynLkIBQxzG3:b-1csd2k) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L29)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

why do we use the commandtask req/response here?
</blockquote></details>

These are just YAML changes, I've decided to split it into two PRs. And the split point is here, it'll be changed as soon as I introduce delegate task and response
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 58 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiS6w0KO8yKn0Ytou:-NFSvuW04nPRGAm87Zuq:bt2vr1b) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L58)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

not a command task :smile: 
</blockquote></details>

Fixed.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 817 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOhd_W6QwThl8dGe5V:-NFgc_Hr9Sc2C8hMvhq2:bif32gq) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L817)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

@arvind-choudhary-h Do we already have a feature flag for this? Maybe in some other PR (for service or infra)
</blockquote></details>

Please use -- `SPOT_ELASTIGROUP_NG`

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 817 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOhd_W6QwThl8dGe5V:-NFgcklY7s6_xl057MhI:bimtge5) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L817)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Please use -- `SPOT_ELASTIGROUP_NG` 
</blockquote></details>

@acasian-harness -- folder looks good.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 177 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgekkHDC7tGodOltZq:-NFgekkIAO2nyUpVU1BI:b-cfwk4o) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L177)):*
> ```Java
>   @JsonProperty(StepSpecTypeConstants.ELASTIGROUP_DEPLOY)
>   ELASTIGROUP_DEPLOY(
>       "Elastigroup Deploy", Collections.emptyList(), "Elastigroup", StepSpecTypeConstants.ELASTIGROUP_DEPLOY);
> ```

2nd Param -- Arrays.asList(ServiceDefinitionType.ELASTIGROUP)



_Code quote:_
```Java
ELASTIGROUP_DEPLOY(
```

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFggZw62VIiktTCUvCY:-NFggZw76w3kPiEHKAfM:bwcitp8) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @RecasterAlias("io.harness.cdng.spot.elastigroup.deploy.ElastigroupDeployServiceWrapper")
> public class ElastigroupDeployServiceWrapper {
> ```

IMO, this feels misleading as this is actually not a wrapper on the service. The count/percentage is just size property.
So implementing: ElastigroupDeployServiceWrapper -> ElastigroupDeployServiceSpec -> CountElastigroupDeployServiceSpec (implements ElastigroupDeployServiceSpec) could be confusing.

How about -- `Capacity newService; Capacity oldService`. The Capacity class can be taken out of Spot/elastigroup package and others too can use it.
The Capacity can act as a wrapper for both Percentage and Count based.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStepInfo.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgk_9O76RYIMcukwuK:-NFgk_9O76RYIMcukwuL:b-uki9et) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStepInfo.java#L59)):*
> ```Java
>   ParameterField<List<TaskSelectorYaml>> delegateSelectors;
> 
>   ElastigroupDeployServiceWrapper newService;
> ```

As discussed above.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/PercentageElastigroupDeployServiceSpec.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgkzou7mSOvvDDo7ZR:-NFgkzou7mSOvvDDo7ZS:b-tl64z1) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/PercentageElastigroupDeployServiceSpec.java#L42)):*
> ```Java
>   @YamlSchemaTypes(value = {expression})
>   @JsonProperty("percentage")
>   @Min(0)
> ```

is there any max annotation?

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 20 of 26 files at r1, 2 of 5 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 1 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiXctEGvov11DaLOZ:-NFgoe7966fkzvZ8ontd:bgc94ot) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L29)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

These are just YAML changes, I've decided to split it into two PRs. And the split point is here, it'll be changed as soon as I introduce delegate task and response
</blockquote></details>

Could you please check if we can use -- SpotDelegateTaskResponse. I know it's not directly compatible but can we make it?

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiXctEGvov11DaLOZ:-NFgpMik85JFPA8pjXzJ:bvbqcno) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L29)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Could you please check if we can use -- SpotDelegateTaskResponse. I know it's not directly compatible but can we make it?
</blockquote></details>

We can maybe extend ElastigroupTaskResponse from this.

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 14 file(s) to review. 8. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 817 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOhd_W6QwThl8dGe5V:-NFhBu1B1flLUgrqpqIb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L817)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

@acasian-harness -- folder looks good.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 177 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgekkHDC7tGodOltZq:-NFhDAFz7h1kfVoPZW6L:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L177)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

2nd Param -- Arrays.asList(ServiceDefinitionType.ELASTIGROUP)
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/39280#-NFOiXctEGvov11DaLOZ:-NFhNmB7C5LtDXY0hs-Q:bfhpwmv) ([raw file](https://github.com/harness/harness-core/blob/bc9972da3339219458fa1b7869caf8941e6c3f77/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStep.java#L29)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

We can maybe extend ElastigroupTaskResponse from this.
</blockquote></details>

Sure, I'll try it out in the next PR (delegate changes). It's not important for this one
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStepInfo.java` line 59 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgk_9O76RYIMcukwuK:-NFhNWPaCxrIA2NsMwmS:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployStepInfo.java#L59)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

As discussed above.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFggZw62VIiktTCUvCY:-NFhFKaE0jUUItnllvH4:bqog7zb) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

IMO, this feels misleading as this is actually not a wrapper on the service. The count/percentage is just size property.
So implementing: ElastigroupDeployServiceWrapper -> ElastigroupDeployServiceSpec -> CountElastigroupDeployServiceSpec (implements ElastigroupDeployServiceSpec) could be confusing.

How about -- `Capacity newService; Capacity oldService`. The Capacity class can be taken out of Spot/elastigroup package and others too can use it.
The Capacity can act as a wrapper for both Percentage and Count based.
</blockquote></details>

Agree.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/PercentageElastigroupDeployServiceSpec.java` line 42 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFgkzou7mSOvvDDo7ZR:-NFhN35E6ZI0TpA_0cEt:b-npilgg) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/PercentageElastigroupDeployServiceSpec.java#L42)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

is there any max annotation?
</blockquote></details>

Actually, there is. I added it.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFggZw62VIiktTCUvCY:-NFi36OV2dcsrDILWAyb:boi1r7h) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
<details><summary><i>Previously, filip5rovic (Filip Petrovic) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

This look good. Can we remove Elastigroup from all names and change the folder/package too. 
This is not specific for Elastigroup and others too can use it like ASG or Azure apps.

**Comment by arvind-choudhary-h** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFggZw62VIiktTCUvCY:-NFi3XBZ-TZV7sNFpRq5:bnlysmt) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

This look good. Can we remove Elastigroup from all names and change the folder/package too. 
This is not specific for Elastigroup and others too can use it like ASG or Azure apps.
</blockquote></details>

Capacity can have CapacitySpec which can further have CountCapacity and PercentageCapacity.



_Code quote (from 125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupCapacity.java):_
```Java
ElastigroupCapacitySpec
```

**Review by acasian-harness — APPROVED** [review]
> Reviewed 4 of 14 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 3. unresolved discussions.

**Comment by filip5rovic** [comment]
trigger ti1

**Comment by filip5rovic** [comment]
trigger ti0 ti1 ti2 ti3 ti4

**Comment by filip5rovic** [comment]
trigger ti0

**Comment by filip5rovic** [comment]
trigger ft1 ft2 compile

**Review by filip5rovic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: 4. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/39280#-NFggZw62VIiktTCUvCY:-NFmGY2ODz4fTdDt0Kn5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e04ad33ab2a32fd285fb71df1fcd8a17cbd167c8/125-cd-nextgen/src/main/java/io/harness/cdng/spot/elastigroup/deploy/ElastigroupDeployServiceWrapper.java#L30)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

Capacity can have CapacitySpec which can further have CountCapacity and PercentageCapacity.
</blockquote></details>

Done.

**Comment by filip5rovic** [comment]
trigger ti0 ti2 ti3 ti4

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 8 of 14 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39280)* status: :shipit: complete! ✓

**Comment by filip5rovic** [comment]
trigger ti0 ti2 ti3 ti4

**Comment by filip5rovic** [comment]
trigger ti0 ti2 ti3 ti4

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
