### PR TITLE
fix: [CDS-48154]: adding hint behind feature flag

### PR DESCRIPTION
**Pull request by lasdox**
## Describe your changes
Adding index hint, behind a feature flag, to prevent query using bad index and raising I/O operations

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41334)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41334)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brettzu — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41334)* status: 1 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/41334#-NInPqLJCO4NyuwABimx:-NInPqLJCO4NyuwABimy:bst1m4k) ([raw file](https://github.com/harness/harness-core/blob/a4fd480c6709e027175cd1aff214f457d69b0707/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L416)):*
> ```Java
>       clonedQuery_2.field(InstanceKeys.deletedAt).greaterThanOrEq(timestamp);
>       FindOptions findOptions2 = wingsPersistence.analyticNodePreferenceOptions();
>       if (featureFlagService.isEnabled(FeatureName.SPG_INSTANCE_ENABLE_HINT_ON_GET_INSTANCES, accountId)) {
> ```

Why does an index hint need to be behind a feature flag?

**Comment by lasdox** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41334)_ status: 1 of 2 approvals obtained.
> 
> _[`400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java` line 416 at r1](https://reviewable.io/reviews/harness/harness-core/41334#-NInPqLJCO4NyuwABimx:-NInPqLJCO4NyuwABimy:bst1m4k) ([raw file](https://github.com/harness/harness-core/blob/a4fd480c6709e027175cd1aff214f457d69b0707/400-rest/src/main/java/software/wings/service/impl/instance/DashboardStatisticsServiceImpl.java#L416)):_
> 
> > ```java
> >       clonedQuery_2.field(InstanceKeys.deletedAt).greaterThanOrEq(timestamp);
> >       FindOptions findOptions2 = wingsPersistence.analyticNodePreferenceOptions();
> >       if (featureFlagService.isEnabled(FeatureName.SPG_INSTANCE_ENABLE_HINT_ON_GET_INSTANCES, accountId)) {
> > ```
> 
> Why does an index hint need to be behind a feature flag?

Just to be on the safe side. I don't want to take any risks, even though I dont see one here.
Do you think we should remove it from hint? @brettzu

**Comment by lasdox** [comment]
trigger messagecheck

**Review by brettzu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41334)* status: :shipit: complete! ✓

**Pull request merged**
