### PR TITLE
fix: [DEL-3836]: Move Azure delegate task out of 400-rest

### PR DESCRIPTION
**Pull request by jennyjames21**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32448)

### CODE REVIEW

**Comment by aman-harness** [comment]
trigger messagecheck

**Comment by raghuAtWings** [comment]
*[`940-secret-manager-client/src/main/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/32448#-N0RRrC62Cojfv5rQ5mc:-N0RRrC62Cojfv5rQ5md:bdg51q4) ([raw file](https://github.com/harness/harness-core/blob/682ea581af050c5c694d184e1389eef135bcfe75/940-secret-manager-client/src/main/java/io/harness/helpers/GlobalSecretManagerUtils.java#L20)):*
> ```Java
> @UtilityClass
> @OwnedBy(PL)
> public class GlobalSecretManagerUtils {
> ```

Why this new class? I don’t see this being used in this pr?

**Comment by jennyjames21** [comment]
*[`940-secret-manager-client/src/main/java/io/harness/helpers/GlobalSecretManagerUtils.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/32448#-N0RRrC62Cojfv5rQ5mc:-N0RYlEy56b8CeN2xP6_:b-oxuzmi) ([raw file](https://github.com/harness/harness-core/blob/682ea581af050c5c694d184e1389eef135bcfe75/940-secret-manager-client/src/main/java/io/harness/helpers/GlobalSecretManagerUtils.java#L20)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

Why this new class? I don’t see this being used in this pr?
</blockquote></details>

it's a duplicate class. removed from PR

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32448)* status: 23 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 22 of 23 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32448)* status: :shipit: complete! ✓

**Pull request merged**
