### PR TITLE
[feat]: [SRM-11008]: added anomalous metrics into notification message and 2 place precision for percentage

### PR DESCRIPTION
**Pull request by kapil-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/35238#-N6iyFLzCrcTxgtuvOVN:-N6iyFLzCrcTxgtuvOVO:b-3tvbwt) ([raw file](https://github.com/harness/harness-core/blob/2f4e7480697ed6d9e371be1a741798cd99f28449/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L60)):*
> ```Java
>     TimeSeriesAnalysisFilter filter = TimeSeriesAnalysisFilter.builder().anomalousMetricsOnly(true).build();
>     List<TimeSeriesMetricDataDTO> timeSeriesMetricDataDTOS =
>         timeSeriesDashboardService
> ```

in the params, you can just pass page size as 5 and page number as 1. This way you dont have to do the break inside the for-loop below

**Comment by kapil-harness** [comment]
trigger ti3

**Comment by kapil-harness** [comment]
Screenshot 2022-07-17 at 2 55 17 PM

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: 14 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java` line 60 at r2](https://reviewable.io/reviews/harness/harness-core/35238#-N6iyFLzCrcTxgtuvOVN:-N7AU32t5LqOlBUFZLRW:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2f4e7480697ed6d9e371be1a741798cd99f28449/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/ChangeImpactTemplateDataGenerator.java#L60)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

in the params, you can just pass page size as 5 and page number as 1. This way you dont have to do the break inside the for-loop below
</blockquote></details>

done

**Comment by kapil-harness** [comment]
trigger codebasehash

**Comment by kapil-harness** [comment]
Screenshot 2022-07-18 at 10 04 43 AM

**Comment by kapil-harness** [comment]
Screenshot 2022-07-18 at 11 59 17 AM

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 2 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: 8 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1767 at r5](https://reviewable.io/reviews/harness/harness-core/35238#-N7IfxOsEFlwPGJ5Qaxl:-N7IfxOt85WYnRuy7Xas:b-h6yj7l) ([raw file](https://github.com/harness/harness-core/blob/e1c5cfcb537a8e9b1a975cf64b717eece50403e2/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1767)):*
> ```Java
>       case HEALTH_SCORE:
>         MonitoredServiceHealthScoreCondition healthScoreCondition = (MonitoredServiceHealthScoreCondition) condition;
>         riskTimeBufferMins = getDurationInSeconds(healthScoreCondition.getPeriod());
> ```

why are we using `riskTimeBufferMins` in multiple places and reassigning values to it ? 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/HealthScoreTemplateDataGenerator.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/35238#-N7IgVmf7Tm2mEoQZ684:-N7IgVmf7Tm2mEoQZ685:b-13zthw) ([raw file](https://github.com/harness/harness-core/blob/e1c5cfcb537a8e9b1a975cf64b717eece50403e2/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/HealthScoreTemplateDataGenerator.java#L58)):*
> ```Java
>         timeSeriesDashboardService
>             .getTimeSeriesMetricData(
>                 monitoredServiceParams, timeRangeParams, filter, PageParams.builder().page(0).size(5).build())
> ```

make these numbers a variable uptop. It's easier to understand the code later that way. Atleast the page size param.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: 9 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java` line 1767 at r5](https://reviewable.io/reviews/harness/harness-core/35238#-N7IfxOsEFlwPGJ5Qaxl:-N7K4E7e1ewfJRvbwcB4:b81yi6w) ([raw file](https://github.com/harness/harness-core/blob/e1c5cfcb537a8e9b1a975cf64b717eece50403e2/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java#L1767)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

why are we using `riskTimeBufferMins` in multiple places and reassigning values to it ? 
</blockquote></details>

it is used in heat maps api i.e. heatMapService.isEveryHeatMapBelowThresholdForRiskTimeBuffer().
we are declaring it at one place and then reassigning it values because you cannot create same variable in 2 switch cases.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/HealthScoreTemplateDataGenerator.java` line 58 at r5](https://reviewable.io/reviews/harness/harness-core/35238#-N7IgVmf7Tm2mEoQZ684:-N7K4mrA7tt9ayyyRU6U:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e1c5cfcb537a8e9b1a975cf64b717eece50403e2/300-cv-nextgen/src/main/java/io/harness/cvng/notification/services/impl/HealthScoreTemplateDataGenerator.java#L58)):*
<details><summary><i>Previously, praveensugavanam (Praveen Kambam Sugavanam) wrote…</i></summary><blockquote>

make these numbers a variable uptop. It's easier to understand the code later that way. Atleast the page size param.
</blockquote></details>

done

**Review by praveensugavanam — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 4 files at r3, 2 of 5 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained.

**Review by praveensugavanam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35238)* status: :shipit: complete! ✓

**Pull request merged**
