### PR TITLE
[feat]: [CDS-46850]: added service id and evironment id to execution logs

### PR DESCRIPTION
**Pull request by vivekkarnatiharness**
## Describe your changes
Have added service id and evironment id to execution logs of pipeline
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
For infrastructure step, lets also add infrastructure name and id , in below order.
Also lets test it, where service/env/infra is given as expression.



_Code snippet:_
```
Fetching environment information...
Infrastructure Name: ID: 
"Kubernetes Namespace: %s"
Environment Name: ID:
```

**Review by tchaurasiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 309 at r1](https://reviewable.io/reviews/harness/harness-core/40668#-NHiuSEsA5nxoKv-foMk:-NHiuSEsA5nxoKv-foMl:b-15kpii) ([raw file](https://github.com/harness/harness-core/blob/06fa3309665cc2833b5d9a7c231363e3176066af/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L309)):*
> ```Java
> 
>     saveExecutionLog(logCallback,
>         "Environment Name: " + environmentOutcome.getName() + " , Id: " + environmentOutcome.getIdentifier());
> ```

Here lets make the order

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java` line 661 at r2](https://reviewable.io/reviews/harness/harness-core/40668#-NHxsXAq0eHniXizRWkD:-NHxsXAq0eHniXizRWkE:b-y2hxku) ([raw file](https://github.com/harness/harness-core/blob/5f938039f92bbd0dfbc3d08e9ee8bedd2c9528b4/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/AbstractInfrastructureTaskExecutableStep.java#L661)):*
> ```Java
>     }
>     saveExecutionLog(logCallback,
>         "Infrastructure Name: " + ((InfrastructureDetailsAbstract) infrastructure).infraName
> ```

Lets use getters.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 309 at r2](https://reviewable.io/reviews/harness/harness-core/40668#-NHy177E8kvhI2Tu0S1R:-NHy177F5BJndSNZlnCH:bsofp48) ([raw file](https://github.com/harness/harness-core/blob/5f938039f92bbd0dfbc3d08e9ee8bedd2c9528b4/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L309)):*
> ```Java
> 
>     saveExecutionLog(logCallback,
>         "Environment Name: " + environmentOutcome.getName() + " , Id: " + environmentOutcome.getIdentifier());
> ```

Id -> should be identifier

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/40668#-NHy1Ev323S3uR3o6p7C:-NHy1Ev323S3uR3o6p7D:bsofp48) ([raw file](https://github.com/harness/harness-core/blob/5f938039f92bbd0dfbc3d08e9ee8bedd2c9528b4/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L147)):*
> ```Java
>       saveExecutionLog(logCallback,
>           "Service Name: " + servicePartResponse.getNgServiceConfig().getNgServiceV2InfoConfig().getName()
>               + " , Id: " + servicePartResponse.getNgServiceConfig().getNgServiceV2InfoConfig().getIdentifier());
> ```

Id -> should be identifier

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 309 at r1](https://reviewable.io/reviews/harness/harness-core/40668#-NHiuSEsA5nxoKv-foMk:-NHyLFDs9jNkbB-lXyny:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/06fa3309665cc2833b5d9a7c231363e3176066af/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L309)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

Here lets make the order 
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java` line 309 at r2](https://reviewable.io/reviews/harness/harness-core/40668#-NHy177E8kvhI2Tu0S1R:-NHyLFdZ9s62cyrDcGT9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f938039f92bbd0dfbc3d08e9ee8bedd2c9528b4/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStepV2.java#L309)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Id -> should be identifier
</blockquote></details>

Done.

**Review by vivekkarnatiharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java` line 147 at r2](https://reviewable.io/reviews/harness/harness-core/40668#-NHy1Ev323S3uR3o6p7C:-NHyLHnfD8pYBIlyY_9w:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5f938039f92bbd0dfbc3d08e9ee8bedd2c9528b4/125-cd-nextgen/src/main/java/io/harness/cdng/service/steps/ServiceStepV3.java#L147)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Id -> should be identifier
</blockquote></details>

Done.

**Review by tchaurasiya — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: 3 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40668)* status: :shipit: complete! ✓

**Pull request merged**
