### PR TITLE
[feat]:[pie-7341]: move config impl for input sets

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes

Added code implementation for moving the input sets config from remote to inline and inline to remote

Impact -> Ease of moving configs

Tests covered:
1. moving input sets inline to remote [default branch]
2. moving input sets remote to inline [default branch]
3. moving input sets inline to remote [non default branch]
4. moving input sets remote to inline [non default branch]

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42209)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 480 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwRPEq-RmQgb3u0sb-:-NKwRPEq-RmQgb3u0sb0:bqajq3j) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L480)):*
> ```Java
>           String.format("InputSet with the given ID: %s does not exist or has been deleted", inputSetIdentifier));
>     }
>     InputSetEntity inputSetToMove = optionalInputSetEntity.get();
> ```

nit: lets avoid this variable declaration

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 488 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwRYVA1NrmlRFI3ppi:-NKwRYVBBFnVWxwWqM_U:b-k6k0rp) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L488)):*
> ```Java
>   @VisibleForTesting
>   protected InputSetEntity moveInputSetEntity(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String inputSetIdentifier, InputSetMoveConfigOperationDTO inputSetMoveConfigOperationDTO,
> ```

when we are passing inputSetToMove, then why do we need inputSetIdentifier separately as argument?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 499 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwRxdl1M9LFFk-fpRc:-NKwRxdl1M9LFFk-fpRd:b-8058bd) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L499)):*
> ```Java
>       String repoUrl = gitAwareEntityHelper.getRepoUrl(accountIdentifier, orgIdentifier, projectIdentifier);
> 
>       update = getUpdateForInputSetInlineToRemote(inputSetMoveConfigOperationDTO, repoUrl);
> ```

why do we need to pass repoURL here as argument?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwSG4xCa668Sx6e6vA:-NKwSG4xCa668Sx6e6vB:bnp7osv) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L501)):*
> ```Java
>       update = getUpdateForInputSetInlineToRemote(inputSetMoveConfigOperationDTO, repoUrl);
> 
>       updateInputSetToMove(inputSetToMove, inputSetMoveConfigOperationDTO, repoUrl);
> ```

why are we having 2 things : firstly we are getting Update object also and then we are also updating fields in current input set as well

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42209)* status: 9 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 488 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwRYVA1NrmlRFI3ppi:-NKwT3BOBAiwj6ltGGKQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L488)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

when we are passing inputSetToMove, then why do we need inputSetIdentifier separately as argument?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 499 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwRxdl1M9LFFk-fpRc:-NKwTm5b8SR3X61FO_nh:bcg1cq3) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L499)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to pass repoURL here as argument?
</blockquote></details>

as we are populating the current input set and the update object with repoUrl, performing the remote call once and using the value in both places.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwSG4xCa668Sx6e6vA:-NKwTPEV60hr2ozXj3pp:b-1al7ge) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L501)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we having 2 things : firstly we are getting Update object also and then we are also updating fields in current input set as well
</blockquote></details>

In case of input sets, during the file creation, in inline to remote flow, we are getting values from the current input set, hence we need it in the current input set and setting the value in the update object for having it reflect in the db as well.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42209)* status: 9 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 501 at r2](https://reviewable.io/reviews/harness/harness-core/42209#-NKwSG4xCa668Sx6e6vA:-NKwUZ8p4CnG8J5SrtMZ:bfkthg9) ([raw file](https://github.com/harness/harness-core/blob/0dd24316c75fe7a079ac219a6a5ea092c2bb7a9e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L501)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

In case of input sets, during the file creation, in inline to remote flow, we are getting values from the current input set, hence we need it in the current input set and setting the value in the update object for having it reflect in the db as well. 
</blockquote></details>

in case of pipelines as well we are doing this in both the places, its just that the code was reusable

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42209)* status: :shipit: complete! ✓

**Pull request merged**
