### PR TITLE
fix: [CDS-43492]: Improving the cleanUp for the TF plan Json export in NG

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Code issue 5 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/38071)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDEcg8dmb2EPld32I:-NDCDEcg8dmb2EPld32J:b-3ccahc) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java#L51)):*
> ```Java
>     String identity = ambiance.getMetadata().getTriggerInfo().getTriggeredBy().getExtraInfoMap().get("email");
> 
>     helper.cleanupTfPlanJson(ambiance);
> ```

Let's add a try catch here or in the cleanupTfPlanJson. Since this cleanup is not crucial for user, we can just log in case of failure
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCBl9h5BDdT02YKjy2:-NDCBl9i9vwcGgk9Pqak:b9g0mb1) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java#L105)):*
> ```Java
>       Scope scope = Scope.of(accountIdentifier, orgIdentifier, projectIdentifier);
> 
>       // retrieve List<tfPlanExecutionDetails> = retrieveTfPlanExecutionDetails(stageExecutionId)
> ```

I believe we don't need this comment
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCC2KP0ORWjI8qn5sj:-NDCC2KQ17PjSb1897AG:b13p2or) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L348)):*
> ```Java
> 
>   public void saveTerraformPlanExecutionDetails(
>       Ambiance ambiance, TerraformTaskNGResponse response, String provisionerIdentifier) {
> ```

tfPlanJsonFileId can be null, let's add a check to save this data only if tfPlanJsonFileId is not null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 401 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDz9l2AUyNpmYMrDZ:-NDCDz9m8E9ugOE5R06E:b-h51fac) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L401)):*
> ```Java
>       }
>       boolean deleteSuccess =
>           terraformPlanExectionDetailsService.deleteTerraformPlanExecutionDetails(terraformPlanExecutionDetails);
> ```

Ideally we would like to reduce calls to mongo db, so we can change this logic to delete all terraformPlanExecutionDetailsList at once, we can even use some logic like delete All that matches accountId, orgId, projectId, pipelineExecutionId
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExectionDetailsService.java` line 13 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDlR5BY_7aQqhB5Yo:-NDCDlR5BY_7aQqhB5Yp:b-6qea1s) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExectionDetailsService.java#L13)):*
> ```Java
>   TerraformPlanExecutionDetails save(TerraformPlanExecutionDetails terraformPlanExecutionDetails);
> 
>   boolean deleteTerraformPlanExecutionDetails(TerraformPlanExecutionDetails terraformPlanExecutionDetails);
> ```

nit: add an empty line after this method
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExectionDetailsServiceImpl.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDb058Gm4rOo1Jnds:-NDCDb058Gm4rOo1Jndt:b-oyz8f5) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExectionDetailsServiceImpl.java#L11)):*
> ```Java
> import javax.validation.constraints.NotNull;
> 
> public class TerraformPlanExectionDetailsServiceImpl implements TerraformPlanExectionDetailsService {
> ```

nit: missing owner
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCCT1i3CvVlRhIpeYC:-NDCCT1i3CvVlRhIpeYD:b-2mf9ob) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java#L59)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(SortCompoundMongoIndex.builder()
>                  .name("sorted_tf_plan_execution_details_idx")
> ```

this index doesn't make sense
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCCZPMEyO4YQ7yLgRY:-NDCCZPMEyO4YQ7yLgRZ:bgbh8x6) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java#L73)):*
> ```Java
>                  .build())
>         .add(CompoundMongoIndex.builder()
>                  .name("unique_tf_plan_execution_details_deployment_identifier_idx")
> ```

would we ever need to query by tfPlanJsonFieldId, I believe we don't need this index
You can keep unique_tf_plan_execution_details_idx and add a new one based on:
accountId, orgId, projectId, pipelineExecutionId - I can see that only these fields are used in queries
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsKey.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDdX9DYlVqRxEWhFE:-NDCDdX9DYlVqRxEWhFF:b-7624lu) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsKey.java#L18)):*
> ```Java
> public class TFPlanExecutionDetailsKey {
>   @NotNull Scope scope;
>   @NotNull String pipeineExecutionId;
> ```

typo in pipeine
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustom.java` line 8 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCChmn77WSZoLweEB4:-NDCChmn77WSZoLweEB5:b-oyz8f5) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustom.java#L8)):*
> ```Java
> import java.util.List;
> 
> public interface TFPlanExecutionDetailsRepositoryCustom {
> ```

nit: missing owner
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCCjQA3WsD2tGwq1oq:-NDCCjQA3WsD2tGwq1or:bfrj0je) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java#L17)):*
> ```Java
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> 
> public class TFPlanExecutionDetailsRepositoryCustomImpl implements TFPlanExecutionDetailsRepositoryCustom {
> ```

nit: missing owner and empty line after annotation is not needed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCEMHq1pf_NO-QYJwN:-NDCEMHq1pf_NO-QYJwO:b-n0o85d) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java#L21)):*
> ```Java
> 
>   @Override
>   public boolean deleteTerraformPlanExecutionDetails(TerraformPlanExecutionDetails tfPlanExecutionDetailsKey) {
> ```

please check my comment in TerraformStepHelper

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)* status: 14 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDEcg8dmb2EPld32I:-NDDQm5F9DrqPoRfb5mh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java#L51)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Let's add a try catch here or in the cleanupTfPlanJson. Since this cleanup is not crucial for user, we can just log in case of failure
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 348 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCC2KP0ORWjI8qn5sj:-NDDQoQK8On-Lv9oea7S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L348)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

tfPlanJsonFileId can be null, let's add a check to save this data only if tfPlanJsonFileId is not null
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java` line 105 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCBl9h5BDdT02YKjy2:-NDDQjQK0uC5g0FBzN7L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CdngPipelineExecutionUpdateEventHandler.java#L105)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I believe we don't need this comment
</blockquote></details>

Done.

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)* status: Some of the checks are too old. 14 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 401 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCDz9l2AUyNpmYMrDZ:-NEAjOnQ9CuJzr6MoZkG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L401)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Ideally we would like to reduce calls to mongo db, so we can change this logic to delete all terraformPlanExecutionDetailsList at once, we can even use some logic like delete All that matches accountId, orgId, projectId, pipelineExecutionId
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCCT1i3CvVlRhIpeYC:-NEAiuYp0f5qbaVIeROO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java#L59)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this index doesn't make sense
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCCZPMEyO4YQ7yLgRY:-NEAjGrA7C4i-ZHJtl4b:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TerraformPlanExecutionDetails.java#L73)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

would we ever need to query by tfPlanJsonFieldId, I believe we don't need this index
You can keep unique_tf_plan_execution_details_idx and add a new one based on:
accountId, orgId, projectId, pipelineExecutionId - I can see that only these fields are used in queries
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/38071#-NDCEMHq1pf_NO-QYJwN:-NEAjKmp8KUBtRZpG7Zy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/29af2a6cc9c3e667d88a96adac1ea4d21a83ee87/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/execution/TFPlanExecutionDetailsRepositoryCustomImpl.java#L21)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please check my comment in TerraformStepHelper
</blockquote></details>

Done.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 14 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java` line 53 at r4](https://reviewable.io/reviews/harness/harness-core/38071#-NEZl1J40uGQuw1GhDb6:-NEZl1J40uGQuw1GhDb7:bn9n6lr) ([raw file](https://github.com/harness/harness-core/blob/ac6bfd501a1c1aa37713eb5cc772e746d60cf367/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/CDPipelineEndEventHandler.java#L53)):*
> ```Java
>       }
>     } catch (Exception e) {
>       log.error("Failure in cleaning up the TF plan Json files from the GCS Bucket");
> ```

nit: add exception to arguments to logs
___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/TFPlanExecutionDetailsRepositoryCustom.java` line 9 at r4](https://reviewable.io/reviews/harness/harness-core/38071#-NEZlH7t7N_RIN1XuLDY:-NEZlH7u0qDJtOTFyfIS:b25l7al) ([raw file](https://github.com/harness/harness-core/blob/ac6bfd501a1c1aa37713eb5cc772e746d60cf367/125-cd-nextgen/src/main/java/io/harness/repositories/executions/TFPlanExecutionDetailsRepositoryCustom.java#L9)):*
> ```Java
> import io.harness.cdng.provision.terraform.executions.TerraformPlanExecutionDetails;
> 
> import java.util.List;
> ```

nit: add new line

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38071)* status: 1. unresolved discussions. 

___
*[`125-cd-nextgen/src/main/java/io/harness/repositories/executions/TFPlanExecutionDetailsRepositoryCustom.java` line 9 at r4](https://reviewable.io/reviews/harness/harness-core/38071#-NEZlH7t7N_RIN1XuLDY:-NEZuBEbCR5UWSPTXlcK:b-lb1iay) ([raw file](https://github.com/harness/harness-core/blob/94422a2533fae0494e3b677db1b2a4265428915f/125-cd-nextgen/src/main/java/io/harness/repositories/executions/TFPlanExecutionDetailsRepositoryCustom.java#L9)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: add new line
</blockquote></details>

@abosii-harness where exactly

**Pull request merged**
