### PR TITLE
feat: [CDS-71261]: Support Environment and Infra propagation

### PR DESCRIPTION
**Pull request by abhinavmittal-harness**
## Describe your changes

Have introduced useFrom stage for envYaml and when that is there env and infra will be propagated from the mentioned stage.
Have tested basic scenarios with stages and templates and reconcile cases

Test plan: https://docs.google.com/spreadsheets/d/1psU0fEMdmtH8AREIn0-RMaKNyDCoPm36F5V7M6wAoIY/edit#gid=0
The execution is in progress

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49803)

### CODE REVIEW

**Comment by abhinavmittal-harness** [comment]
trigger ng_manager

**Comment by abhinavmittal-harness** [comment]
trigger ng_manager

**Comment by abhinavmittal-harness** [comment]
trigger ng_manager

**Comment by abhinavmittal-harness** [comment]
trigger template_svc

**Comment by abhinavmittal-harness** [comment]
trigger uts

**Comment by abhinavmittal-harness** [comment]
trigger ng_manager

**Comment by abhinavmittal-harness** [comment]
trigger commonchecks

**Review by tchaurasiya — CHANGES_REQUESTED** [review]

**Comment by abhinavmittal-harness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 112 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259420354:-N_3UwSR5yP6nE66UB3R:b1tj42c) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L112)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

is it related to this feature?
</blockquote></details>

This needs to be removed, got added when I rebased I guess. Will do

**Comment by abhinavmittal-harness** [comment]
*[`884-pms-commons/src/test/java/io/harness/pms/merger/helpers/YamlRefreshHelperTest.java` line 222 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259492095:-N_3sfVb9cXmtKXOKiY4:b-hvemqy) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/884-pms-commons/src/test/java/io/harness/pms/merger/helpers/YamlRefreshHelperTest.java#L222)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

is this existing behaviour?
Shouldn't this be like
"type: Deployment\nspec:\n  environment:\n    environmentRef: prod_environment\n"

(not having environmentInput node when env is fix and does not have inputs)
</blockquote></details>

Yes this is the expected behaviour

**Comment by abhinavmittal-harness** [comment]
*[`884-pms-commons/src/test/java/io/harness/pms/merger/helpers/YamlRefreshHelperTest.java` line 222 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259492095:-N_3srEE33LjGZ4rmhSH:b-468upy) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/884-pms-commons/src/test/java/io/harness/pms/merger/helpers/YamlRefreshHelperTest.java#L222)):*
<details><summary><i>Previously, abhinavmittal-harness (Abhinav Mittal) wrote…</i></summary><blockquote>

Yes this is the expected behaviour
</blockquote></details>

Existing*

**Comment by abhinavmittal-harness** [comment]
trigger uts

**Review by abhinavmittal-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49803)* status: 24 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259474898:-N_7jB0o-BliQ1vb_5lY:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java#L489)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: can we extract above stage config related validation in another method? Making this method too long.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 450 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259456407:-N_7jGtO8AyvpNMbm2sb:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L450)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

nit: unused method
</blockquote></details>

Done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraUseFromStageV2VisitorHelper.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/49803#gh-1259449521:-N_3sxEb86QR-wT2Ykds:b-gg4pm2) ([raw file](https://github.com/harness/harness-core/blob/14703ad404325a24a2b40610188c4f65b9060291/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraUseFromStageV2VisitorHelper.java#L25)):*
<details><summary><i>Previously, tchaurasiya (Tathagat Chaurasiya) wrote…</i></summary><blockquote>

EnvironmentInfraUseFromStageV2VisitorHelper???
</blockquote></details>

This was there for ServiceUseFromStage so added. Right now this is not needed as it does nothing

**Comment by abhinavmittal-harness** [comment]
trigger ut6

**Review by tchaurasiya — APPROVED** [review]

**Comment by abhinavmittal-harness** [comment]
the test that is failing 400-rest/software.wings.service.tests4
Seems to unrelated to my changes.
So will have it force merged once review is done

**Comment by abhinavmittal-harness** [comment]
trigger ut6

**Review by puthrayaharness — APPROVED** [review]

**Comment by abhinavmittal-harness** [comment]
trigger review

**Pull request merged**
