### PR TITLE
feat: [CDS-46240]: Manager changes: K8s & Native Helm (CG - Direct Kubernetes Cluster) Instance sync V2 implementation Revisit

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Describe your changes
Instance Sync V2 implementation of K8s and Helm Deployments in CG

## Test Plan
https://docs.google.com/spreadsheets/d/1XHvQuQlvo8S3pDvfFOakUFHteh8VfVYNLJvs8sTI9xc/edit#gid=314439328

## Test Result
to be update

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40084)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
PR is inProgress

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40084)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/40084#-NHA2AHn7l99mI4nTW-h:-NHA2AHn7l99mI4nTW-i:b-p33o46) ([raw file](https://github.com/harness/harness-core/blob/a7ffcb89fa3f7b4224365c40c5e21afcc57a44b7/400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java#L31)):*
> ```Java
>       DeploymentSummary deploymentSummary, String cloudProviderId, String perpetualTaskId);
> 
>   Set<CgReleaseIdentifiers> buildReleaseIdentifiers(DeploymentSummary deploymentSummary);
> ```

nit: name should be createReleaseIdentifiers
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/40084#-NHA1bVv66vKvmN6GBgi:-NHA1bVw-OLrghaOIuZU:b-47ttcr) ([raw file](https://github.com/harness/harness-core/blob/a7ffcb89fa3f7b4224365c40c5e21afcc57a44b7/400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java#L45)):*
> ```Java
>   List<Instance> difference(List<Instance> list1, List<Instance> list2);
> 
>   Map<CgReleaseIdentifiers, List<Instance>> getDeployedInstances(
> ```

Why we would need to have 2 methods? getDeployedInstances should handle both cases (new deployment/perpetual task)
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/40084#-NHA1Chr2K4-o81uvjqK:-NHA1ChtA6P8T92nSQGr:b-vq1uf1) ([raw file](https://github.com/harness/harness-core/blob/a7ffcb89fa3f7b4224365c40c5e21afcc57a44b7/400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java#L55)):*
> ```Java
>       Set<CgReleaseIdentifiers> cgReleaseIdentifiers, String appId, String InfraMappingId);
> 
>   Map<CgReleaseIdentifiers, InstanceSyncData> getCgReleaseIdentifiersList(List<InstanceSyncData> instanceSyncData);
> ```

this should be something like groupInstanceSyncData

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40084)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java` line 45 at r3](https://reviewable.io/reviews/harness/harness-core/40084#-NHA1bVv66vKvmN6GBgi:-NHAT1cYEbd5RmKcsKxw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a7ffcb89fa3f7b4224365c40c5e21afcc57a44b7/400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java#L45)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why we would need to have 2 methods? getDeployedInstances should handle both cases (new deployment/perpetual task)
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java` line 55 at r3](https://reviewable.io/reviews/harness/harness-core/40084#-NHA1Chr2K4-o81uvjqK:-NHAT2fS0oikcedzx8oA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a7ffcb89fa3f7b4224365c40c5e21afcc57a44b7/400-rest/src/main/java/software/wings/instancesyncv2/handler/CgInstanceSyncV2Handler.java#L55)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

this should be something like groupInstanceSyncData
</blockquote></details>

Done.

**Comment by namantalaycha10** [comment]
trigger messagecheck

**Comment by namantalaycha10** [comment]
trigger codeformat

**Comment by namantalaycha10** [comment]
trigger copyrightcheck

**Comment by namantalaycha10** [comment]
trigger checkstyle

**Comment by namantalaycha10** [comment]
**Update this time RELEASE_PRESERVE_TIME to 7 days before merging**

**Comment by namantalaycha10** [comment]
trigger ft1

**Comment by namantalaycha10** [comment]
trigger ft2

**Pull request closed without merging**
