### PR TITLE
fix: [CDS-49430]: Fetching values file from Helm or K8s manifest when multiple manifest files are passed

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Fetching values file from Helm or K8s manifest when multiple manifest files are passed

The below listed case did not used to work earlier.
K8sManifest:
    spec:
            storeType: Github
            paths:
                    - deploy.yaml
                    - config-map.yaml
    valuesPaths:
         - values1.yaml
         - values2.yaml

Now we have fixed it.

1. When multiple manifest files are passed in Git subset store.
Screenshot 2022-12-28 at 5 28 37 PM
2. When multiple manifest files and folder are passed in Git subset store.
Screenshot 2022-12-28 at 5 28 22 PM

3. When Multiple manifest folders are passed in Git subset folders.
Screenshot 2022-12-28 at 5 28 05 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

2. When multiple manifest files and folder are passed in Git subset store.
3. When Multiple manifest folders and

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)

### CODE REVIEW

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/42024#-NKOSv688s-LC1MVCao_:-NKOh5HoCleFEaBppnDZ:b-e7xjt8) ([raw file](https://github.com/harness/harness-core/blob/01898e976457b6c82157d51c727ad75fa9d661a8/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L197)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Looks, just want to confirm that removing this check will not affect over manifest types as this is intended to be done only for Helm & K8s. Logically it should be the case, but just want to be sure
</blockquote></details>

The change does not impact helm at all. In Helm, we use the folderPath field which can contain only a single path to helm chart. For K8s, I have validated the above the cases and I think we have covered everything to ensure that it does not cause any regression.

**Review by achyuth-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by acasian-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/42024#-NKOSv688s-LC1MVCao_:-NKWx7K12Yg6g8yylLwT:bxc1gxj) ([raw file](https://github.com/harness/harness-core/blob/01898e976457b6c82157d51c727ad75fa9d661a8/125-cd-nextgen/src/main/java/io/harness/cdng/K8sHelmCommonStepHelper.java#L197)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

The change does not impact helm at all. In Helm, we use the folderPath field which can contain only a single path to helm chart. For K8s, I have validated the above the cases and I think we have covered everything to ensure that it does not cause any regression. 
</blockquote></details>

so previously we were doing this only for k8s & helm, now this will be available for all manifest types: oc, values, etc. Just want to understand why the reason of that condition

**Comment by GoelPratyush99** [comment]
These changes https://github.com/harness/harness-core/pull/42024 are not related to other manifests like oc or kustomize, it's only for k8s. The condition hasOnlyOne was earlier being used for the case when the user provides multiple folders to get k8s manifest files then we would not be able to decide where to fetch the default values yaml file. So we skipped reading the values file.

As we added a new feature for reading values files from the same k8s manifest. We miss reading the values files when the user provides multiple files/folders. This is a bug.

In the present scenario, we will pick default values.yaml from the first path provided by the user. If it is a directory then we try to fetch the default values and the other values provided by the user as part of k8s manifest. If it is a file then we only fetch the values provided by the user as part of k8s manifest.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42024)* status: :shipit: complete! ✓

**Pull request merged**
