### PR TITLE
[feat]: [SRM-13700]: updates onboarding APIs for Elasticsearch log.

### PR DESCRIPTION
**Pull request by n00bitax**
## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)

### CODE REVIEW

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxBFY6EEVqiZvPfUa:-NNFxBFZCuh-9ILkHMcq:b8f9dus) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java#L30)):*
> ```Java
>   @JsonIgnore
>   public static QueryParamsDTO getQueryParamsDTO(QueryParams queryParams) {
>     QueryParams queryParamsPresent = Optional.ofNullable(queryParams).orElse(QueryParams.builder().build());
> ```

I think we should refactor this variable to just queryParams
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxZqa8MAWb9b0SD1f:-NNFxZqa8MAWb9b0SD1g:b-7hpqc1) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java#L111)):*
> ```Java
>   public RestResponse<HealthSourceParamValuesResponse>
>   getParamValues(@PathParam(CVNextGenConstants.ACCOUNT_IDENTIFIER_KEY) @NonNull String accountIdentifier,
>       @PathParam(CVNextGenConstants.ORG_IDENTIFIER_KEY) @NonNull String orgIdentifier,
> ```

Can we use Bean Params here?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxrx5-3d9L3JHKcKe:-NNFxrx5-3d9L3JHKcKf:b-h407iv) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java#L28)):*
> ```Java
>         throw new IllegalStateException(e);
>       }
>     } else if (dataSourceType == DataSourceType.ELASTICSEARCH) {
> ```

We can clean this implementation. Checking for dataSourceType and the try-catch logic can be separated into different methods to reduce redundant code.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ELKDataCollectionInfoMapper.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFyREGDuA4h7XLUtH4:-NNFyREGDuA4h7XLUtH5:b-gwb378) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ELKDataCollectionInfoMapper.java#L47)):*
> ```Java
>       return elkDataCollectionInfo;
>     }
>     return null;
> ```

Instead of returning null, we can throw exception saying this is not supported.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFz0NW77aHwJs4TSDC:-NNFz0NW77aHwJs4TSDD:b-lwkjm6) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L79)):*
> ```Java
>         request = HealthSourceOnboardMappingUtils.getSumoLogicLogDataCollectionRequest(healthSourceRecordsRequest);
>         break;
>       case ELASTICSEARCH:
> ```

nit: Since we are going to add many sources here, this will grow. Can we move this switch to the utils class itself?
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFz_104Z8BEIKqfogD:-NNFz_11-jY2V7JRfc0D:bkwgc15) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L101)):*
> ```Java
>         HealthSourceRecordsResponse.builder().providerType(healthSourceRecordsRequest.getProviderType()).build();
>     if (!(result instanceof Collection) || ((Collection<?>) result).size() > 0) {
>       if (result instanceof Collection) {
> ```

nit: This can be simplified - if(not a collection) {} else if(collection but not empty){} else {}
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 214 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-2xTEHSk7jxKpYmj:-NNG-2xTEHSk7jxKpYmk:bwtzzja) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L214)):*
> ```Java
>       HealthSourceParamValuesRequest healthSourceParamValuesRequest, ProjectParams projectParams) {
>     healthSourceParamValuesRequest.validate();
>     if (healthSourceParamValuesRequest.getProviderType() == MonitoredServiceDataSourceType.ELASTICSEARCH) {
> ```

Can we make this method generic? 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-RgK7iFmb8mOUlK8:-NNG-RgK7iFmb8mOUlK9:b-cugnps) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L261)):*
> ```Java
>     CVConfig cvConfig;
>     if (queryRecordsRequest.getProviderType() == DataSourceType.SUMOLOGIC_LOG
>         || queryRecordsRequest.getProviderType() == DataSourceType.ELASTICSEARCH) {
> ```

nit: We can make a method isProviderTypeImplemented() and use that in the if. The method can be extended as new sources are added.
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 449 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-lHB-hiGmrBNg5_0:-NNG-lHB-hiGmrBNg5_1:b-8ipa7d) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L449)):*
> ```Java
>         "filebeat-6.8.8-2023.01.24", "filebeat-6.8.8-2023.01.13", "filebeat-6.8.8-2023.01.26",
>         "filebeat-6.8.8-2023.01.12", ".kibana", "filebeat-6.8.8-2023.01.27");
>     System.out.println(onboardingRequestDTO);
> ```

Do we require this print?

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxBFY6EEVqiZvPfUa:-NNG4Z49AVobgOzZNH0C:b-l16xh5) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java#L30)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

I think we should refactor this variable to just queryParams
</blockquote></details>

we already have query param any other name suggestion passed from the method, any other naming suggestion. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxZqa8MAWb9b0SD1f:-NNG6WD81K07LMp6ySav:baxoqqy) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java#L111)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Can we use Bean Params here?
</blockquote></details>

is there a advantage isn't being more specific better, PathParam vs beanparam
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java` line 28 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxrx5-3d9L3JHKcKe:-NNG5fM-4HOnOKLoB8iU:b-piu3cr) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionDSLFactory.java#L28)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

We can clean this implementation. Checking for dataSourceType and the try-catch logic can be separated into different methods to reduce redundant code.
</blockquote></details>

done, done moved reading file to a method
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ELKDataCollectionInfoMapper.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFyREGDuA4h7XLUtH4:-NNG6F2C8k31zhp_A8XC:b-im8736) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/ELKDataCollectionInfoMapper.java#L47)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Instead of returning null, we can throw exception saying this is not supported.
</blockquote></details>

done, throwing runtime exception
___
*[`srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java` line 449 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-lHB-hiGmrBNg5_0:-NNG6OslCtB9CxT6CXQS:bdek3t1) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/resources/HealthSourceOnboardingResourceTest.java#L449)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Do we require this print?
</blockquote></details>

done, removed

**Review by dhruv-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxBFY6EEVqiZvPfUa:-NNGAIwB7hGXs_NxERkI:b-nrkmy6) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java#L30)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

we already have query param any other name suggestion passed from the method, any other naming suggestion. 
</blockquote></details>

If the queryParams passed to the method is null, do we want to return null  or empty QueryParamsDTO. In either case we can have a null check, if not null build and return, else return null or empty dto
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxZqa8MAWb9b0SD1f:-NNGAeaD95I0hcc3b9IH:b-xs71t3) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java#L111)):*
<details><summary><i>Previously, n00bitax (Ansuman Satapathy) wrote…</i></summary><blockquote>

is there a advantage isn't being more specific better, PathParam vs beanparam
</blockquote></details>

nit: Bean param for this would be getting used as multiple places, reduces boilerplate and redundancy

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 101 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFz_104Z8BEIKqfogD:-NNGIYBDAREreFz1IA7r:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L101)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

nit: This can be simplified - if(not a collection) {} else if(collection but not empty){} else {}
</blockquote></details>

done
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-RgK7iFmb8mOUlK8:-NNGKJaO8QbjhbOtAbii:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L261)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

nit: We can make a method isProviderTypeImplemented() and use that in the if. The method can be extended as new sources are added.
</blockquote></details>

done

**Review by n00bitax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxBFY6EEVqiZvPfUa:-NNGWNUMAwmZnstBKfn8:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/healthsource/QueryParamsDTO.java#L30)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

If the queryParams passed to the method is null, do we want to return null  or empty QueryParamsDTO. In either case we can have a null check, if not null build and return, else return null or empty dto
</blockquote></details>

done
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java` line 111 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFxZqa8MAWb9b0SD1f:-NNGYOVX1lsET-kQE5bx:bjapvuu) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/resources/HealthSourceOnboardingResource.java#L111)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

nit: Bean param for this would be getting used as multiple places, reduces boilerplate and redundancy
</blockquote></details>

used ProjectPathParams
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 79 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNFz0NW77aHwJs4TSDC:-NNGLFN4CRfvYkuE3kvU:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L79)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

nit: Since we are going to add many sources here, this will grow. Can we move this switch to the utils class itself?
</blockquote></details>

done
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java` line 214 at r3](https://reviewable.io/reviews/harness/harness-core/43353#-NNG-2xTEHSk7jxKpYmj:-NNGWQC534LbH64PFg_d:bwy4w4p) ([raw file](https://github.com/harness/harness-core/blob/cbb159173a8052063ac76b03c6fedd0226f5ebc3/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/HealthSourceOnboardingServiceImpl.java#L214)):*
<details><summary><i>Previously, dhruv-harness (Dhruv) wrote…</i></summary><blockquote>

Can we make this method generic? 
</blockquote></details>

moved logic of ES to a private method.

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: :shipit: complete! ✓

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectParams.java` line 32 at r8](https://reviewable.io/reviews/harness/harness-core/43353#-NNGe9AtCLnemNJfEIyc:-NNGe9AtCLnemNJfEIyd:b-irzt2n) ([raw file](https://github.com/harness/harness-core/blob/a4de4062d7be28f6fc2f247b1d92d62d4b7e4559/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ProjectParams.java#L32)):*
> ```Java
> @AllArgsConstructor
> public class ProjectParams {
>   // TODO use
> ```

nit: Smell

**Review by dhruv-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43353)* status: :shipit: complete! ✓

**Comment by n00bitax** [comment]
trigger ft1

**Comment by n00bitax** [comment]
trigger ft2

**Pull request merged**
