### PR TITLE
[feat]: [PIE-8384]: Add variable default values in runtime input form API

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44041)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44041)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44041#-NOsbLpe0_or6HsNUgbu:-NOsbLpfA_BS9fHXn4cQ:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/acf343947823db8c0f887257a46da3332a843b78/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java#L31)):*
> ```Java
>   }
> 
>   public String createTemplateWithDefaultValuesFromPipeline(String pipelineYaml) {
> ```

same for this
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44041#-NOsbDOYDJDRoPYKJkZj:-NOsbDOYDJDRoPYKJkZk:byqwnnl) ([raw file](https://github.com/harness/harness-core/blob/acf343947823db8c0f887257a46da3332a843b78/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L39)):*
> ```Java
>   private String EXECUTION_FQN_FROM_STAGE =
>       YAMLFieldNameConstants.STAGE + "." + YAMLFieldNameConstants.SPEC + "." + YAMLFieldNameConstants.EXECUTION;
>   public String createTemplateFromYaml(String templateYaml) {
> ```

will this method remain, shouldnt we add default in normal one itself?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java` line 212 at r2](https://reviewable.io/reviews/harness/harness-core/44041#-NOsbJjABbE_uKDXNk-T:-NOsbJjABbE_uKDXNk-U:b4psc2y) ([raw file](https://github.com/harness/harness-core/blob/acf343947823db8c0f887257a46da3332a843b78/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/ValidateAndMergeHelper.java#L212)):*
> ```Java
>   }
> 
>   public String getMergedYamlFromInputSetReferencesAndRuntimeInputYamlWithDefaultValues(String accountId,
> ```

same for this

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44041)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/44041#-NOsbDOYDJDRoPYKJkZj:-NOsbjZaARpyTuRLqfRO:b-jl170g) ([raw file](https://github.com/harness/harness-core/blob/acf343947823db8c0f887257a46da3332a843b78/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/RuntimeInputFormHelper.java#L39)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

will this method remain, shouldnt we add default in normal one itself?
</blockquote></details>

I've added a separate method so that if the create template is called anywhere else other than the API they still see the previous behaviour. I want to make sure the change right now is restricted to just the UI API and not anywhere else

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44041)* status: 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/44041#-NOsbLpe0_or6HsNUgbu:-NOsgSxU9thQvM00zmM3:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/acf343947823db8c0f887257a46da3332a843b78/884-pms-commons/src/main/java/io/harness/pms/merger/helpers/InputSetTemplateHelper.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same for this
</blockquote></details>

done

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44041)* status: :shipit: complete! ✓

**Pull request merged**
