### PR TITLE
[feat]: [CCM-8643]: AWS Connector create/update/delete should invoke a callback to AutoCud APIs

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
AWS Connector create/update/delete should invoke a callback to AutoCud APIs

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36759)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 6 Issues 
* Vulnerability 3 Vulnerabilities 
 * Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36759)

**Comment by iamanmolm** [comment]
trigger ti3

**Review by nikunj-badjatya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36759)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/AwsEntityChangeEventServiceImpl.java` line 91 at r1](https://reviewable.io/reviews/harness/harness-core/36759#-NAinOqb0zH5OBCfN8cH:-NAinOqb0zH5OBCfN8cI:br550ij) ([raw file](https://github.com/harness/harness-core/blob/2c67b38524ea126f87c7f2e94667d18293d5e080/340-ce-nextgen/src/main/java/io/harness/ccm/service/impl/AwsEntityChangeEventServiceImpl.java#L91)):*
> ```Java
>         ceAwsConnectorDTO =
>             (CEAwsConnectorDTO) getConnectorConfigDTO(accountIdentifier, identifier).getConnectorConfig();
>         if (configuration.isEnableLightwingAutoCUDDC()) {
> ```

Can we move the contents of this if block in to a common method and pass relevant params to it ? we can avoid some repetition.

**Review by nikunj-badjatya — COMMENTED** [review]
looks good otherwise. thanks.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36759#-:-NAink__41N4gv-7ZFdL:btjxv0x)* status: 10 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Comment by iamanmolm** [comment]
trigger checkstyle

**Comment by iamanmolm** [comment]
trigger codeformat

**Comment by iamanmolm** [comment]
trigger codeformat

**Comment by iamanmolm** [comment]
trigger recency

**Comment by iamanmolm** [comment]
trigger compile

**Comment by iamanmolm** [comment]
trigger messagecheck

**Comment by iamanmolm** [comment]
trigger ti3, ti4

**Comment by iamanmolm** [comment]
trigger ft2

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36759)* status: :shipit: complete! ✓

**Comment by iamanmolm** [comment]
trigger compile, ft2, ti3, ti4

**Pull request merged**
