### PR TITLE
[feat]: [SRM-9878]: Monitored Service UT for Access Control Service

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874#-:-MzPiMSoEG13dGIz-fht:bnfp4nl)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31874#-MzPiOGw3vvGm8ERqG1m:-MzPiOGw3vvGm8ERqG1n:b81ozk7) ([raw file](https://github.com/harness/harness-core/blob/899e0e91aeed0c2f62bac9cee55a468a95ae2ef0/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L52)):*
> ```Java
>   @Owner(developers = KAPIL)
>   @Category(UnitTests.class)
>   public void testSaveMonitoredService_withFakeAccessControlClient() throws IOException {
> ```

@kapil-harness we need this for all api which are using access control right? Are we planning to write them separately? If yes we should add a separate tracking ticket for it.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31874#-MzPiOGw3vvGm8ERqG1m:-MzQ3n-I51gEdFhLtDMa:bijcyhz) ([raw file](https://github.com/harness/harness-core/blob/899e0e91aeed0c2f62bac9cee55a468a95ae2ef0/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L52)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

@kjoshi12345 We can only write UTs for resource methods which use accessControlClient because @NGAccessControlCheck goes through a method interceptor which is bypassed in our UTs.
 Because of that only "moniotred-service/create-default" resource method is left. For it I will add.

</blockquote></details>

one correction "updateMonitoredService" is the one with accessControlClient

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNj42DhJmOLK37s_c:-MzTNj42DhJmOLK37s_d:bo43vd0) (no related file):*
These tests are ok, but we need more tests.

---
___
*[123-ng-core-user/src/test/java/io/harness/ng/accesscontrol/user/AggregateUserServiceImplTest.java, line 1 at r4](https://reviewable.io/reviews/harness/harness-core/31874#-MzTMVzZ967b8KLZlx1Q:-MzTMVzZ967b8KLZlx1R:b1id4jp) ([raw file](https://github.com/harness/harness-core/blob/617d71ae309741fc66647c7bc6b97509b26d4fa2/123-ng-core-user/src/test/java/io/harness/ng/accesscontrol/user/AggregateUserServiceImplTest.java#L1)):*
> ```Java
> /*
> ```

nit: We dont need to add this to existing code, right?
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31874#-MzPiOGw3vvGm8ERqG1m:-MzTNJq89IYnCmqqVY4Q:bdmhrzs) ([raw file](https://github.com/harness/harness-core/blob/899e0e91aeed0c2f62bac9cee55a468a95ae2ef0/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L52)):*
> @NGAccessControlCheck
nit : We need tests for this too.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 37 at r4](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNTim69gqwFr8ev7g:-MzTNTim69gqwFr8ev7h:b38d9bg) ([raw file](https://github.com/harness/harness-core/blob/617d71ae309741fc66647c7bc6b97509b26d4fa2/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L37)):*
> ```Java
> import org.yaml.snakeyaml.Yaml;
> 
> public class MonitoredServiceResourceWithAccessControlTest extends CVNGResourceTestWithoutAccessBase {
> ```

nit: could have been MonitoredServiceResourceAccessControlTest

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1 file(s) to review. 1 change requests. 3. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNj42DhJmOLK37s_c:-MzULpVF38RcM4iVNIhp:balvdja) (no related file):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

These tests are ok, but we need more tests.
</blockquote></details>

this needs more research

---
___
*[123-ng-core-user/src/test/java/io/harness/ng/accesscontrol/user/AggregateUserServiceImplTest.java, line 1 at r4](https://reviewable.io/reviews/harness/harness-core/31874#-MzTMVzZ967b8KLZlx1Q:-MzULtIEAr2e_XWTEOTb:b-sx1c4m) ([raw file](https://github.com/harness/harness-core/blob/617d71ae309741fc66647c7bc6b97509b26d4fa2/123-ng-core-user/src/test/java/io/harness/ng/accesscontrol/user/AggregateUserServiceImplTest.java#L1)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: We dont need to add this to existing code, right?
</blockquote></details>

its auto added by githooks but it is harmless
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 52 at r3](https://reviewable.io/reviews/harness/harness-core/31874#-MzPiOGw3vvGm8ERqG1m:-MzUM40sC8cQQcXh9Kzm:bk9v926) ([raw file](https://github.com/harness/harness-core/blob/899e0e91aeed0c2f62bac9cee55a468a95ae2ef0/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L52)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

> @NGAccessControlCheck
nit : We need tests for this too.
</blockquote></details>

needs more research
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java, line 37 at r4](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNTim69gqwFr8ev7g:-MzULzJNCjsgX5bXdH9b:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/617d71ae309741fc66647c7bc6b97509b26d4fa2/300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceWithAccessControlTest.java#L37)):*
<details><summary><i>Previously, AbhijithHarness (Abhijith Pradeep) wrote…</i></summary><blockquote>

nit: could have been MonitoredServiceResourceAccessControlTest
</blockquote></details>

done

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 3. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 5 of 16 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1. unresolved discussions.

**Review by kapil-harness — COMMENTED** [review]
> Reviewed 14 of 16 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 14 of 16 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874#-:-Mz_6-Wy6QQHZUSKS3oL:bnfp4nl)* status: 1. unresolved discussions.

**Comment by mohitg0795** [comment]
*[a discussion](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNj42DhJmOLK37s_c:-Mz_6s_53vflD1vRktiz:bb7f2mf) (no related file):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

this needs more research
</blockquote></details>

done

---

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874#-:-Mz_7-qh7Ow6N0KLkeEM:bnfp4nl)* status: 1. unresolved discussions.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1. unresolved discussions. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31874#-MzTNj42DhJmOLK37s_c:-Mz_76eN3l1qXYCJdUOb:b-896fix) (no related file):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done.

---

**Review by mohitg0795 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: 1. unresolved discussions.

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31874)* status: :shipit: complete! ✓

**Pull request merged**
