### PR TITLE
[fix]: [PIE-7874]: Fixing retry-failed-pipeline with pipeline-stage

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxbPFAcpUvC36NhOB:-NOIxbPFAcpUvC36NhOC:b-8brtbi) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L75)):*
> ```Java
>     }
>     NodeExecution parentNodeExecution =
>         nodeExecutionService.getWithFieldsIncluded(prevNodeExecution.getParentId(), Set.of(NodeExecutionKeys.planNode));
> ```

do you need complete planNode? or only nodeType?
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxp8213fOLjd6fUqW:-NOIxp8213fOLjd6fUqX:bzhas94) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L84)):*
> ```Java
>           originalNodeExecution.getNextId(), Set.of(NodeExecutionKeys.parentId));
>       // Checking the parentIds. If match then create identityNode.
>       if (nextOfOriginalNodeExecution.getParentId().equals(originalNodeExecution.getParentId())) {
> ```

do we need this if?



_Code quote:_
```Java
nextOfOriginalNodeExecution.getParentId().equals(originalNodeExecution.getParentId())
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxbPFAcpUvC36NhOB:-NOIy4CIB4KrYGTg0Vkh:blfy71k) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do you need complete planNode? or only nodeType?
</blockquote></details>

+1, only relevant fields should be used.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxp8213fOLjd6fUqW:-NOJ08m25VmLliVy1GfL:b-40e9gc) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L84)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

do we need this if?
</blockquote></details>

Not needed. Parent will be same for the currentNode and nextNode. Removing.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxbPFAcpUvC36NhOB:-NOJ2o_ZAzGKEFifGOpM:b-dz5pf7) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L75)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1, only relevant fields should be used.
</blockquote></details>

add your projection in NodeProjectionUtils

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/43947#-NOIxbPFAcpUvC36NhOB:-NOJHg-K68XUHKDGoIVn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/26bcb55c4e9f4c755aa35ecb6f37c92fe8bffb1e/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/NextStepHandler.java#L75)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add your projection in NodeProjectionUtils
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43947)* status: :shipit: complete! ✓

**Pull request merged**
