### PR TITLE
feat: [CDS-38067]: envgroup plan creator

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
- add env group plan creator
- fix plan node creation for gitops clusters step
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33728)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger compile, ti0, ti1, ti2, ti3

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 8 of 16 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33728)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33728#-:-N4LTmXdD94jX1Q_nRt2:bnfp4nl)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 8 of 16 files at r1, 14 of 20 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33728)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreator.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4QbzZmAl-9PsvjInLh:-N4QbzZmAl-9PsvjInLi:batju40) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreator.java#L61)):*
> ```Java
>           ctx.getDependency().getMetadataMap().get(YamlTypes.INFRA_SECTION_UUID).toByteArray());
>       PlanNode gitopsNode = InfrastructurePmsPlanCreator.createPlanForGitopsClusters(
>           ctx.getCurrentField(), infraSectionUuid, config, kryoSerializer);
> ```

gitops me infra section node is required?



_Code quote:_
```Java
infraSectionUuid
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4Qcanx8b2P3XAZt6yo:-N4Qcanx8b2P3XAZt6yp:byx3acp) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L173)):*
> ```Java
>       String postServiceStepUuid = "service-" + UUIDGenerator.generateUuid();
>       String environmentUuid = "environment-" + UUIDGenerator.generateUuid();
>       //      String envGroupUuid = "environmentgroup-" + UUIDGenerator.generateUuid();
> ```

this can be deleted



_Code quote:_
```Java
 //      String envGroupUuid = "environmentgroup-" + UUIDGenerator.generateUuid();
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4Qd27n6IUFz0xzT44c:-N4Qd27o-0JcyNHudTOD:b-fh66wg) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L112)):*
> ```Java
>       final GitopsClustersOutcome outcome = toOutcome(validatedClusters, variables);
>       executionSweepingOutputResolver.consume(
>           ambiance, GITOPS_SWEEPING_OUTCOME, outcome, StepOutcomeGroup.STAGE.name());
> ```

GITOPS_SWEEPING_OUTPUT



_Code quote:_
```Java
GITOPS_SWEEPING_OUTCOME
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 113 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4QcpD9AryedpMJ-9Iv:-N4QcpD9AryedpMJ-9Iw:b-mlrzas) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L113)):*
> ```Java
>       executionSweepingOutputResolver.consume(
>           ambiance, GITOPS_SWEEPING_OUTCOME, outcome, StepOutcomeGroup.STAGE.name());
>       stepResponseBuilder.stepOutcome(StepOutcome.builder().name("gitops").outcome(outcome).build());
> ```

can we put this in a constant file so steps can refer from there, GITOPS_SWEEPING_OUTPUT



_Code quote:_
```Java
"gitops"
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33728)* status: 6 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreator.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4QbzZmAl-9PsvjInLh:-N4Qi0yJ1TDCXZGQ7MU6:b-yostui) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreator.java#L61)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

gitops me infra section node is required?
</blockquote></details>

its actually the uuid of step that runs after the service step. Changed the name to "postServiceSpecUuid" 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 173 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4Qcanx8b2P3XAZt6yo:-N4QiF_A1EutSIkp24BP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L173)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this can be deleted
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 112 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4Qd27n6IUFz0xzT44c:-N4QiGSNENUpkF0BcGIA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L112)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

GITOPS_SWEEPING_OUTPUT
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java` line 113 at r3](https://reviewable.io/reviews/harness/harness-core/33728#-N4QcpD9AryedpMJ-9Iv:-N4QiGo3-aq4QJaZ3O8S:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f3e4e4498e1c9f2902bcdf45978c18497705e5f9/125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java#L113)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we put this in a constant file so steps can refer from there, GITOPS_SWEEPING_OUTPUT
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33728)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
trigger ft1,ft2

**Pull request merged**
