### PR TITLE
feat: [CDS-43880]: create entity inputs validation api on ng manager

### PR DESCRIPTION
**Pull request by inderschera**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37986)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 8 Issues 
* Code issue 7 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37986)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/EntityRefreshResource.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/37986#-ND2LaAI76JZ0TBMMCwH:-ND2LaAI76JZ0TBMMCwI:b-i6w8s4) ([raw file](https://github.com/harness/harness-core/blob/d44ba06d9fd91677c967664fb89a71c61be473c0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/EntityRefreshResource.java#L50)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> public class EntityRefreshResource {
> ```

Lets hide this resource from open api spec

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37986#-ND2N4Gr6azwPsiufkVz:-ND2N4Gr6azwPsiufkW-:b77pjzs) ([raw file](https://github.com/harness/harness-core/blob/d44ba06d9fd91677c967664fb89a71c61be473c0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java#L75)):*
> ```Java
>     // Case -> empty YAML, cannot validate
>     if (isEmpty(yaml)) {
>       throw new NGTemplateException("Yaml to be validated cannot be empty.");
> ```

should we create a new kind of exception ?

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37986)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/37986#-ND2N4Gr6azwPsiufkVz:-ND2NBgV-v4MAd2WrXsN:b2qz7wf) ([raw file](https://github.com/harness/harness-core/blob/d44ba06d9fd91677c967664fb89a71c61be473c0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java#L75)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we create a new kind of exception ?
</blockquote></details>

I haven't added swagger3 annotations on this resource. So, these APIs won't be exposed.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37986)* status: 8 file(s) to review. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java` line 96 at r2](https://reviewable.io/reviews/harness/harness-core/37986#-ND2NPX78FdV3eWHjgHb:-ND2NPX78FdV3eWHjgHc:bxq1xz2) ([raw file](https://github.com/harness/harness-core/blob/d44ba06d9fd91677c967664fb89a71c61be473c0/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java#L96)):*
> ```Java
>       JsonNode value = currentYamlNode.getCurrJsonNode();
> 
>       // If Template is present, validate the Template Inputs
> ```

nit: comment needs an update

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37986)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37986)* status: :shipit: complete! ✓

**Pull request merged**
