### PR TITLE
feat: [PIE-6181]: Total running nodes per planExecution dashboard and alerts

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40163)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40163)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/40163#-NGvMX2WD-u1fHroQeBH:-NGvMX2X8yDm-qwzh-26:b78zt19) ([raw file](https://github.com/harness/harness-core/blob/9984ef18839df09dfae23fadcf89b323ed31e384/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java#L111)):*
> ```Java
>   // Mutable
>   @Wither @LastModifiedDate Long lastUpdatedAt;
>   @FdIndex Status status;
> ```

This index doesnt work, we need to add index using mongo indexes in below method in same class



_Code quote:_
```Java
@FdIndex
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40163)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/40163#-NGvMX2WD-u1fHroQeBH:-NGvNn2fCQy0ng15ZVw0:b6hefzh) ([raw file](https://github.com/harness/harness-core/blob/9984ef18839df09dfae23fadcf89b323ed31e384/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This index doesnt work, we need to add index using mongo indexes in below method in same class
</blockquote></details>

it only used to work in 400 cg manager and not in ng



_Code quote:_
```Java
@FdIndex 
```
___
*[`pipeline-service/service/src/main/resources/metrics/metricGroups/node-execution-count-metric-group.yaml` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/40163#-NGvNtOV5hGYXNZxk7VM:-NGvNtOV5hGYXNZxk7VN:bpnv7fs) ([raw file](https://github.com/harness/harness-core/blob/9984ef18839df09dfae23fadcf89b323ed31e384/pipeline-service/service/src/main/resources/metrics/metricGroups/node-execution-count-metric-group.yaml#L6)):*
> ```YAML
>   - accountId
>   - orgIdentifier
>   - projectIdentifier
> ```

@sribalij can we do only accountId for both planExecution and nodeExecution because of limit on gcp for different combinations available

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40163)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java` line 111 at r2](https://reviewable.io/reviews/harness/harness-core/40163#-NGvMX2WD-u1fHroQeBH:-NGw8gJyBq6I4CJGP1dl:b-wscygk) ([raw file](https://github.com/harness/harness-core/blob/9984ef18839df09dfae23fadcf89b323ed31e384/pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution/NodeExecution.java#L111)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it only used to work in 400 cg manager and not in ng
</blockquote></details>

I did try it on local and it does work. It creates a new index with name "status_1"

___
*[`pipeline-service/service/src/main/resources/metrics/metricGroups/node-execution-count-metric-group.yaml` line 6 at r2](https://reviewable.io/reviews/harness/harness-core/40163#-NGvNtOV5hGYXNZxk7VM:-NGw8yGIE7YJwBmrTXHf:b32wtd) ([raw file](https://github.com/harness/harness-core/blob/9984ef18839df09dfae23fadcf89b323ed31e384/pipeline-service/service/src/main/resources/metrics/metricGroups/node-execution-count-metric-group.yaml#L6)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@sribalij can we do only accountId for both planExecution and nodeExecution because of limit on gcp for different combinations available 
</blockquote></details>

ok

**Comment by sribalij** [comment]
trigger messagecheck

**Comment by sribalij** [comment]
trigger smartchecks

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40163)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 2 of 7 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40163#-:-NGz4l5rBFAXHqokWiuZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
