### PR TITLE
[feat]: [PL-28397]: Added endpoint for validating API Key token

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Added endpoint for validating API Key token

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39010)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/39010#-NFJncN-4zzi0VsqOZcz:-NFJoRbbA1hSCYzmXzfB:b9o7s24) ([raw file](https://github.com/harness/harness-core/blob/a1200f414a29ad5cef457db15ae5224fae5ad45c/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L333)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Is this logic duplicated elsewhere?
</blockquote></details>

Jimit can we extract all of this logic to a helper class and in the next commit you can move the NextGenAuthentication filter logic to directly invoke this new endpoint

**Review by reetika04 — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39010)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/39010#-NFJncN-4zzi0VsqOZcz:-NFORl7i8Pl0S8xIFnvq:bqyq8j6) ([raw file](https://github.com/harness/harness-core/blob/a1200f414a29ad5cef457db15ae5224fae5ad45c/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L333)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

@piyush-harness , do we really need helper class as I dont see this logic used else? 
And as we had discussed, I will make change to NextGenAuthentication to call this endpoint in another PR so that we can observe for a week in PreQA.

cc @ankit-harness 
</blockquote></details>

Helper class makes sense here because if you want to introduce new type of validation for different token you do not need to change anything in ServiceImpl and it can reside in it's own microservice. and Helper class can reside in common component.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39010)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 333 at r2](https://reviewable.io/reviews/harness/harness-core/39010#-NFJncN-4zzi0VsqOZcz:-NFS5Jir5b0A3VpN7Qi9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a1200f414a29ad5cef457db15ae5224fae5ad45c/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L333)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Helper class makes sense here because if you want to introduce new type of validation for different token you do not need to change anything in ServiceImpl and it can reside in it's own microservice. and Helper class can reside in common component.
</blockquote></details>

Done.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39010)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39010)* status: 1 change requests. 1. unresolved discussions.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39010#-:-NFe5zJs8btlY9BOdwZl:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
