### PR TITLE
[feat]: [CDS-2898]: Supporting SSH inherit for Source Module in Terraform

### PR DESCRIPTION
**Pull request by namantalaycha10**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 311 at r1](https://reviewable.io/reviews/harness/harness-core/32564#-N0e7it576EdY41NOT5F:-N0e7it576EdY41NOT5G:b-rrljzc) ([raw file](https://github.com/harness/harness-core/blob/1f8b5b84546183957059685597d753701a6de190/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L311)):*
> ```Java
>         builder.configFiles(getStoreConfigAtCommitId(
>             configuration.getConfigFiles().getStore().getSpec(), commitIdMap.get(TF_CONFIG_FILES)));
>         if (cdFeatureFlagHelper.isEnabled(
> ```

nit: can we reuse isExportCredentialForSourceModule?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 501 at r1](https://reviewable.io/reviews/harness/harness-core/32564#-N0e7eN616jQmRmyNhaI:-N0e7eN79D37iiKnB3Yf:b-8de6rb) ([raw file](https://github.com/harness/harness-core/blob/1f8b5b84546183957059685597d753701a6de190/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L501)):*
> ```Java
>                 .toGitStoreConfigDTO());
> 
>         if (cdFeatureFlagHelper.isEnabled(
> ```

nit: can we reuse isExportCredentialForSourceModule method here?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 511 at r1](https://reviewable.io/reviews/harness/harness-core/32564#-N0e7ZffDZfOn2baTxST:-N0e7Zfg54uSVs5FZ-Ym:bt4xa4c) ([raw file](https://github.com/harness/harness-core/blob/1f8b5b84546183957059685597d753701a6de190/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L511)):*
> ```Java
>                       configuration.getSpec().getConfigFiles().getModuleSource().getUseConnectorCredentials(),
>                       USE_CONNECTOR_CREDENTIALS, format("%s step", ExecutionNodeType.TERRAFORM_APPLY.getYamlType())))
>               .workspace(getParameterFieldValue(spec.getWorkspace()));
> ```

why we're populating workspace here?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java` line 511 at r1](https://reviewable.io/reviews/harness/harness-core/32564#-N0e7ZffDZfOn2baTxST:-N0f5DYaC7vZXtr1sxC-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f8b5b84546183957059685597d753701a6de190/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java#L511)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

why we're populating workspace here?
</blockquote></details>

Done.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 18 of 23 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: 1 change requests. 1. unresolved discussions.

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 18 of 23 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Review by namantalaycha10 — COMMENTED** [review]
> Reviewed 18 of 23 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger ti1

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 18 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Comment by namantalaycha10** [comment]
trigger codeformat

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 18 of 20 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564#-:-N1I6ecn8Yo3cI_ktDJd:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 18 files at r5, 14 of 20 files at r6, 28 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 12 of 23 files at r1, 3 of 6 files at r2, 1 of 1 files at r3, 1 of 18 files at r5, 28 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32564)* status: :shipit: complete! ✓

**Pull request merged**
