### PR TITLE
fix: [CDS-46440]: ignore validation in input yaml with extra keys

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
Added logic to ignore validation when some extra keys are present in node to be validated (merged pipeline yaml) compared to source node. This is needed when primary artifact ref is <+input>, we add sources as <+input> as well but these sources might not have any input fields so they will not be present in source node.
This will affect validating service inputs flows. 
*Tests*
- reconciliation with artifact sources
	- artifact ref as runtime
	- artifact ref as fixed
	- no inputs in any of the artifact sources
	- inputs in some of the artifact sources

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [X] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40319)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
We should also check for primary artifact ref as an expression @hingerabhinav

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/40319#-NH8S6kM1LIpq6bhWhGa:-NH8S6kM1LIpq6bhWhGb:b-uhro0k) ([raw file](https://github.com/harness/harness-core/blob/31f9b725a8407fcd6e32df184c64824955980071/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java#L50)):*
> ```Java
> @Slf4j
> public class InputsValidationHelper {
>   private static List<String> keysToIgnoreInNodeToValidate = Collections.singletonList("primary.sources");
> ```

can we say artifacts.primary.sources ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40319)* status: 0 of 1 approvals obtained.

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40319)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java` line 50 at r2](https://reviewable.io/reviews/harness/harness-core/40319#-NH8S6kM1LIpq6bhWhGa:-NH8nRaY12mfvIb8_r6H:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/31f9b725a8407fcd6e32df184c64824955980071/120-ng-manager/src/main/java/io/harness/ng/core/refresh/helper/InputsValidationHelper.java#L50)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we say artifacts.primary.sources ?
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40319)* status: :shipit: complete! ✓

**Comment by hingerabhinav** [comment]
trigger messagecheck

**Pull request merged**
