### PR TITLE
[feat]: [PIE-3794]: Pipeline Execution changes for Git Simplification

### PR DESCRIPTION
**Pull request by namanvermah**
For REMOTE Pipelines, entity setup usage framework cannot be relied upon. That is because the setup usages can be outdated wrt the YAML we find on Git during execution. This means the fail fast approach that we have for RBAC checks can't be provided for remote pipelines.
Other changes in this PR revolve around setting of proper git context during execution, and sending this git context properly in the various execution related APIs.

Also, added comments in the code wherever needed.
Major chunk of line changes is because of one unit tests class.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zBiyT50Ha5OSzv-Me:-N2zBiyT50Ha5OSzv-Mf:bdhmmhg) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L155)):*
> ```Java
>   }
> 
>   private String nullIfDefault(String val) {
> ```

this seems spefic to git sync, can this method be there in git sync helper somewhere?



_Code quote:_
```Java
nullIfDefault(String val)
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zByc6ELDLqvrhhuoC:-N2zByc6ELDLqvrhhuoD:b4oxvg0) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L252)):*
> ```Java
>         pipelineEntity.getProjectIdentifier(), pipelineYaml);
>     if (pipelineEntity.getStoreType() == null || pipelineEntity.getStoreType() == StoreType.INLINE) {
>       // For REMOTE Pipelines, entity setup usage framework cannot be relied upon. That is because the setup usages can
> ```

Can we create ticket for the same to keep track for handling this



_Code quote:_
```Java
// For REMOTE Pipelines, entity setup usage framework cannot be relied upon. That is because the setup usages can
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zByc6ELDLqvrhhuoC:-N2zD8iE9e0B23LpCxsm:brsgh61) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L252)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we create ticket for the same to keep track for handling this
</blockquote></details>

Already have a ticket for this: https://harness.atlassian.net/browse/PIE-3769

**Comment by mohitg0795** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zBiyT50Ha5OSzv-Me:-N2zCz1X--1flzQnEf8k:bay12vd) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L155)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this seems spefic to git sync, can this method be there in git sync helper somewhere?
</blockquote></details>

@archit-harness now the ownership of all git data management dtos is with individual services only. Git Sync SDK / Service only will manage their resource endpoints and functionalities. So, it can't be moved to git sync helper.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zBiyT50Ha5OSzv-Me:-N2zEkrb2lSBqSfts26c:b-vzpa60) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L155)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

@archit-harness now the ownership of all git data management dtos is with individual services only. Git Sync SDK / Service only will manage their resource endpoints and functionalities. So, it can't be moved to git sync helper.
</blockquote></details>

__default__ is a git sdk construct and any handling related to it should be in the sdk though.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: 10 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zBiyT50Ha5OSzv-Me:-N2zEzp-5l6y-UxHa-CG:ba1hsc8) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L155)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

__default__ is a git sdk construct and any handling related to it should be in the sdk though.
</blockquote></details>

i meant the nullIfDefault method, as both method name is not clear, plus this logic to get null or not I think of put in common helper would be bettter

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java` line 155 at r2](https://reviewable.io/reviews/harness/harness-core/33548#-N2zBiyT50Ha5OSzv-Me:-N2zKA_g2gmPZ0GzjAbh:b-e1qa68) ([raw file](https://github.com/harness/harness-core/blob/e51724d17526a1dfcdc4fdda6e36216578a6d026/800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java#L155)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i meant the nullIfDefault method, as both method name is not clear, plus this logic to get null or not I think of put in common helper would be bettter
</blockquote></details>

@namanvermah as decided, going forward any fields should be owned by service itself. If there's any concern regarding new fields and their default values, we can move it out of the current git sync thread decorator and pipeline/input-set service can handle them as per their convenience. For older fields, I don't think there's any concern right now. It should work the way it has been working until now.
For now, lets go ahead with the thing whatever we have and we can plan for a proper fix around it next week. We can keep a ticket to track it properly. I just don't want to block our progress on it.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33548)* status: :shipit: complete! ✓

**Pull request merged**
