### PR TITLE
[feat]: [SRM-10039]: Adding changes to use SideKick while deleting CVConfig

### PR DESCRIPTION
**Pull request by dhruv-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32301)

### CODE REVIEW

**Comment by dhruv-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32301)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java, line 832 at r1](https://reviewable.io/reviews/harness/harness-core/32301#-N-xLz53D94txp5CknGw:-N05sJM-8iwxW9eW-Fvp:bwg70n5) ([raw file](https://github.com/harness/harness-core/blob/1f69dd2361bff132ee78e17c17b90045978cf4e4/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L832)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

We don't have to keep commented out code. It will be in version control if we need it again.
</blockquote></details>

Let's keep it for this release to make sure we don't miss any deletion. Please create a ticket to cleanup DeletedCVConfig after this change is released.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java, line 105 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05phPVCQi5OiLhJpQ1:-N05phPVCQi5OiLhJpQ2:b-miukm9) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java#L105)):*
> ```Java
>         verificationTaskService.getServiceGuardVerificationTaskIds(cvConfig.getAccountId(), cvConfig.getUuid());
>     verificationTaskIds.forEach(verificationTaskId
>         -> CompletableFuture.runAsync(()
> ```

any reason to run async? I think we can enqueue it normally. One CVConfig will have only one VerificationTask for service guard. We should just get one. 
Getting multiple in DeletedCVConfig has historical reason which are no longer valid.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java, line 110 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05pMDNA5orIblZ4k33:-N05pMDNA5orIblZ4k34:bc7drrd) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVConfigServiceImpl.java#L110)):*
> ```Java
>                                                                           .cvConfig(cvConfig)
>                                                                           .build(),
>                                               Instant.now().plus(Duration.ofHours(2)))));
> ```

please use clock.instant() instead of Instant.now()
This helps you in writing predictable tests for the method and also your method does not depend on some global state.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java, line 97 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05qix41pgxvvB_q5am:-N05qix41pgxvvB_q5an:b-8ym7bk) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java#L97)):*
> ```Java
> 
>   private void deleteMonitoringSourcePerpetualTasks(CVConfig cvConfig) {
>     monitoringSourcePerpetualTaskService.deleteTask(cvConfig.getAccountId(), cvConfig.getOrgIdentifier(),
> ```

if (cvConfigService
            .list(deletedCVConfig.getCvConfig().getAccountId(), deletedCVConfig.getCvConfig().getOrgIdentifier(),
                deletedCVConfig.getCvConfig().getProjectIdentifier(),
                deletedCVConfig.getCvConfig().getFullyQualifiedIdentifier())
            .isEmpty()) 
Above condition is also required 
Because one identifier can have multiple CVConfig so we need to delete perpetual task only if the last one is deleted.
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java, line 289 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05rGlZC-lNTAwcy8xI:-N05rGlZC-lNTAwcy8xJ:b-itvzhp) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L289)):*
> ```Java
>         String verificationTaskId = verificationTaskService.getSLIVerificationTaskId(sli.getAccountId(), sli.getUuid());
>         if (StringUtils.isNotBlank(verificationTaskId)) {
>           CompletableFuture.runAsync(
> ```

I don't think we need runAsync here 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java, line 293 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05rLA3DaWfcDP-Ndua:-N05rLA3DaWfcDP-Ndub:b-rcwr86) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L293)):*
> ```Java
>                   -> sideKickService.schedule(
>                       VerificationTaskCleanupSideKickData.builder().verificationTaskId(verificationTaskId).build(),
>                       Instant.now().plus(Duration.ofMinutes(15))));
> ```

please use clock.
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/SideKickServiceImplTest.java, line 66 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05rYbp6QL5VN2JdP6f:-N05rYbp6QL5VN2JdP6g:b-c8o99i) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/SideKickServiceImplTest.java#L66)):*
> ```Java
>     typeSideKickExecutorMap = new HashMap<>();
>     retryChangeSourceHandleDeleteSideKickExecutor = Mockito.mock(RetryChangeSourceHandleDeleteSideKickExecutor.class);
>     cvConfigCleanupSideKickExecutor = Mockito.mock(VerificationTaskCleanupSideKickExecutor.class);
> ```

why we we need this change?
___
*[300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java, line 71 at r2](https://reviewable.io/reviews/harness/harness-core/32301#-N05rpJ0C0mNTmp13usL:-N05rpJ0C0mNTmp13usM:b-ruihh8) ([raw file](https://github.com/harness/harness-core/blob/5c11176827823e4191d8ade829c7f4719e5218f3/300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutorTest.java#L71)):*
> ```Java
>   private List<String> verificationTaskIdsForCvConfig;
> 
>   private final BuilderFactory builderFactory = BuilderFactory.getDefault();
> ```

we should get this in setup. Otherwise one test can cause issues in other tests. The isolation in test is achieved by randomness of accountId, projectIdentifier etc for each test.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32301#-:-N09N6s6DgnQjN_t3L0h:bnfp4nl)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32301)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32301)* status: :shipit: complete! ✓

**Pull request merged**
