### PR TITLE
[fix]: [CDS-86860]: fix for spawned stages ordering with repeat loop strategy in the retry and copying missed data from original strategy node execution to identity strategy step

### PR DESCRIPTION
**Pull request by rchaudharyy**
## Describe your changes

[fix]: [CDS-86860]: fix for spawned stages ordering with repeat loop strategy in the retry and copying missed data from original strategy node execution to identity strategy step

Scenario:
Pipeline with one of stage using repeat looping strategy and maxConcurrency less than no of times it should run. let's assume maxConcurrency set as 1 and times as 3. For first time stages will run one by one and suppose one of spawned stage got failed.

Issue: 
While retry the above failed stage, some of spawned stages are getting skipped if one of them failed again and ordering of the spawned stages is getting changed

Changes: 
1. added the missed field ( shouldProceedIfFailed ) while copying the data to identity strategy step
2. changed the query to get the correct ordering

Testing:
done in local

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-86860]: https://harness.atlassian.net/browse/CDS-86860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57080)

### CODE REVIEW

**Comment by rchaudharyy** [comment]
trigger uts

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57080)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyStep.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/57080#-NmGPd2O9v4m1qeHnlRg:-NmGPd2O9v4m1qeHnlRh:bky2pal) ([raw file](https://github.com/harness/harness-core/blob/b1e7a438c23c404429bbe790734b34201e5d91c3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyStep.java#L74)):*
> ```Java
>         originalStrategyNodeExecution.getExecutableResponses().get(0).getChildren().getMaxConcurrency();
> 
>     boolean shouldProceedIfFailed =
> ```

@rchaudharyy , is this solving our issue? How did we test this?

**Comment by rchaudharyy** [comment]
trigger uts

**Review by rchaudharyy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57080)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyStep.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/57080#-NmGPd2O9v4m1qeHnlRg:-NmGuMCN4byZc9rMdvhW:b-dsora9) ([raw file](https://github.com/harness/harness-core/blob/b1e7a438c23c404429bbe790734b34201e5d91c3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity/IdentityStrategyStep.java#L74)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@rchaudharyy , is this solving our issue? How did we test this?
</blockquote></details>

This change will fix the skipping of node execution in retry. For the ordering issue added one new change. Tested the same in local

**Comment by rchaudharyy** [comment]
trigger uts

**Comment by rchaudharyy** [comment]
trigger review

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57080)* status: <span>:shipit:</span> complete! ✓

**Comment by rchaudharyy** [comment]
trigger review

**Pull request merged**
