### PR TITLE
feat: [DEL-5383]: Add metrics on number of upgrader calls per account

### PR DESCRIPTION
**Pull request by mdmilic**
## Describe your changes
Adding metrics on number of checks for upgrade per account for immutable delegate. This will help understand how customers use upgrader. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)

### CODE REVIEW

**Review by AnupamIO — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBQLGg1SnEv2RQ5FAi:-NIBQLGg1SnEv2RQ5FAj:b-r8oq5n) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java#L55)):*
> ```Java
>       @QueryParam("currentDelegateImageTag") @NotEmpty String currentDelegateImageTag) {
>     try (AutoLogContext ignore1 = new AccountLogContext(accountId, OVERRIDE_ERROR)) {
>       delegateMetricsService.recordDelegateMetricsPerAccount(accountId, DELEGATE_LEGACY_UPGRADE);
> ```

I think we can remove this /delegate endpoint, this is not being used from upgrader latest image now, upgrader hits delegate-v2 endpoint only,
___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBS0W06UVUkNoCEv-z:-NIBS0W06UVUkNoCEv0-:btrq1sm) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java#L77)):*
> ```Java
>   @DelegateAuth
>   @GET
>   @Path("/upgrader")
> ```

@mdmilic from where this endpoint is called ? I'm unable to recall.
___
*[`400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml` line 65 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBSQWq6Pc14m3Kj4u_:-NIBSQWq6Pc14m3Kj4ua:b9xk8zm) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml#L65)):*
> ```YAML
>     type: Count
>     unit: "1"
>   - metricName: delegate_legacy_upgrade
> ```

can be removed, my assumption is every customer will be using latest upgrader image itself.
___
*[`420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java` line 50 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBSGHB6Y2hfwo9enyh:-NIBSGHB6Y2hfwo9enyi:b-m5pdaw) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java#L50)):*
> ```Java
>   public static final String DELEGATE_UPGRADE = "delegate_upgrade";
>   public static final String UPGRADER_UPGRADE = "upgrader_upgrade";
>   public static final String DELEGATE_LEGACY_UPGRADE = "delegate_legacy_upgrade";
> ```

DELEGATE_LEGACY_UPGRADE can be removed 



_Code quote:_
```Java
DELEGATE_LEGACY_UPGRADE
```

**Review by mdmilic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java` line 55 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBQLGg1SnEv2RQ5FAi:-NID15Se4RNxQMEvE_FW:bgy5x7u) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java#L55)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

I think we can remove this /delegate endpoint, this is not being used from upgrader latest image now, upgrader hits delegate-v2 endpoint only,
</blockquote></details>

We have pinned versions of upgrader which might hit this endpoint (e.g. `upgrader:1.0.0`). I think we should make sure no one is using it. We can do that from appD or with this metric. If we do it we would also need to remove older upgrader versions from dockerhub, so I wouldn't do it as part of this ticker. We can create a separate story for that.
___
*[`400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java` line 77 at r1](https://reviewable.io/reviews/harness/harness-core/40759#-NIBS0W06UVUkNoCEv-z:-NID1WkY7tYJhLGlIsp4:b-p38mvy) ([raw file](https://github.com/harness/harness-core/blob/ff15836141dcb1a95b6eeda837933e1810aca0ea/400-rest/src/main/java/io/harness/delegate/resources/DelegateUpgraderResource.java#L77)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

@mdmilic from where this endpoint is called ? I'm unable to recall.
</blockquote></details>

I't not called from anywhere. It was meant for upgrader selfUpgrade, but we didn't end up implementing that feature yet. I've put metric there just for consistency.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)* status: Some of the checks are too old. 2. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)* status: Some of the checks are too old. 2. unresolved discussions.

**Review by AnupamIO — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40759)* status: :shipit: complete! ✓

**Pull request merged**
