### PR TITLE
[feat]: [PIE-9068]: Propagate preserved nodes from PlanCreationResponse to blob response

### PR DESCRIPTION
**Pull request by namanvermah**
As of now the preserved nodes list won't be populated anywhere, so this propagation is effectively a noop. Have added unit tests that cover all the null/empty cases.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger ut0

**Comment by namanvermah** [comment]
trigger ut4

**Comment by namanvermah** [comment]
trigger ut5

**Comment by namanvermah** [comment]
trigger ut5

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 5 of 8 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)* status: 12 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 2 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`884-pms-commons/src/test/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtilsTest.java` line 23 at r5](https://reviewable.io/reviews/harness/harness-core/45358#-NR2hWBq4nGvs0l23_jg:-NR2hWBr8SXajkyxCXl7:bbxge0p) ([raw file](https://github.com/harness/harness-core/blob/48698e586f8d9d320e75a5e2d725db286b51f5d7/884-pms-commons/src/test/java/io/harness/pms/plan/creation/PlanCreationBlobResponseUtilsTest.java#L23)):*
> ```Java
> import org.junit.experimental.categories.Category;
> 
> public class PlanCreationBlobResponseUtilsTest extends CategoryTest {
> ```

nit: add team annotation
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/MergePlanCreationResponse.java` line 54 at r5](https://reviewable.io/reviews/harness/harness-core/45358#-NR2hdyM8uYUmi2_tktt:-NR2hdyM8uYUmi2_tktu:b22rwim) ([raw file](https://github.com/harness/harness-core/blob/48698e586f8d9d320e75a5e2d725db286b51f5d7/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/beans/MergePlanCreationResponse.java#L54)):*
> ```Java
>     mergeLayoutNodeInfo(response.getGraphLayoutResponse());
>     addYamlUpdates(response.getYamlUpdates());
>     mergePreservedNodesInRollbackMode(response.getPreservedNodesInRollbackMode());
> ```

@namanvermah we are currently using -> mergeWithoutDependencies in our code and not this, can you check if your change needs to be there?
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java` line 86 at r5](https://reviewable.io/reviews/harness/harness-core/45358#-NR2i-jNAYuwzrHTVXiW:-NR2i-jNAYuwzrHTVXiX:b-w10iyf) ([raw file](https://github.com/harness/harness-core/blob/48698e586f8d9d320e75a5e2d725db286b51f5d7/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/PlanCreatorServiceHelper.java#L86)):*
> ```Java
>         finalResponse.updateYamlInDependencies(updatedYaml);
>       }
>       finalResponse.mergePreservedNodesInRollbackMode(response.getPreservedNodesInRollbackMode());
> ```

cant we add this to mergeWithoutDependencies?



_Code quote:_
```Java
finalResponse.mergePreservedNodesInRollbackMode(response.getPreservedNodesInRollbackMode())
```

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 5 of 8 files at r1, 3 of 6 files at r2, 1 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 6 files at r2, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45358)* status: :shipit: complete! ✓

**Pull request merged**
