### PR TITLE
feat: [CDS-80184]: Add triggered by info for audit events

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Audit events for pipeline end , stage start and stage end were displaying as `SYSTEM` events. This change will now display the triggered by information for these events. 

- Before: 
before

- After: 
after

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53405)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53405)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/53405#-NfJgQVq9dJJ1tqFp8O9:-NfJgQVq9dJJ1tqFp8OA:b-3oyda1) ([raw file](https://github.com/harness/harness-core/blob/a4e3b2fe6d834331d2dded64b42a4b51c1b6a11f/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L187)):*
> ```Java
>         NodeExecutionEventUtils.mapPipelineEndEventToNodeExecutionEventData(pipelineEndEvent);
> 
>     Principal principal = null;
> ```

can we create a private method, which all methods can use it directly? else change in one line needs to be updated everywhere

**Comment by rohitk-h** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 187 at r1](https://reviewable.io/reviews/harness/harness-core/53405#-NfJgQVq9dJJ1tqFp8O9:-NfK4wt38_pslRscgiua:b-cypxrc) ([raw file](https://github.com/harness/harness-core/blob/a4e3b2fe6d834331d2dded64b42a4b51c1b6a11f/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L187)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we create a private method, which all methods can use it directly? else change in one line needs to be updated everywhere
</blockquote></details>

updated.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53405)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by rohitk-h** [comment]
trigger review

**Pull request merged**
