### PR TITLE
[fix]: [PL-27620]: Removing resource level validation check of Empty API Key and returning boolean to indicate whether its valid or not.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
Removing resource level validation check of Empty API Key and returning boolean to indicate whether its valid or not.
This will avoid flooding exceptions in the logs caused when APIKey is not passed to validate APIKey.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36845)

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 450 at r1](https://reviewable.io/reviews/harness/harness-core/36845#-NASMDSg5Xy1rJRufH9a:-NASMDSg5Xy1rJRufH9b:bqcyn) ([raw file](https://github.com/harness/harness-core/blob/ab8d7076eda5b971f0db7614461cddf63e6f54c8/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L450)):*
> ```Java
>       accountId = apiKeyService.getAccountIdFromApiKey(apiKey);
>     }
>     if (!apiKeyService.validate(apiKey, accountId)) {
> ```

I think we should throw 

throw new UnauthorizedException("Invalid Api Key", USER);



_Code quote (from 400-rest/src/main/java/software/wings/service/impl/ApiKeyServiceImpl.java):_
```Java
throw new UnauthorizedException("Invalid Api Key", USER);
```

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 450 at r1](https://reviewable.io/reviews/harness/harness-core/36845#-NASMDSg5Xy1rJRufH9a:-NASMJZo36UWI4_dSla6:b-6mhpwe) ([raw file](https://github.com/harness/harness-core/blob/ab8d7076eda5b971f0db7614461cddf63e6f54c8/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L450)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we should throw 

throw new UnauthorizedException("Invalid Api Key", USER);
</blockquote></details>

Also, would this err msg get logged?

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 450 at r1](https://reviewable.io/reviews/harness/harness-core/36845#-NASMDSg5Xy1rJRufH9a:-NATBRKP0_KdvdTqLYIg:bi57740) ([raw file](https://github.com/harness/harness-core/blob/ab8d7076eda5b971f0db7614461cddf63e6f54c8/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L450)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Also, would this err msg get logged?
</blockquote></details>

Changed to UnauthorizedException. Although I have added log now, currently I don't see any logging in Authentication filter for other exceptions thrown as well. I think we should have discuss why is that so.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/36845#-NAY2ZlzCjwizC7xbgTI:-NAY2Zm-1I-1S2NDMpe7:b-qynka7) ([raw file](https://github.com/harness/harness-core/blob/be84b89591d6b83f813dca19d4b4e09ace045394/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L166)):*
> ```Java
>           return;
>         } catch (UnauthorizedException | InvalidRequestException exception) {
>           log.error("Invalid Api Key", exception);
> ```

How frequently would this get logged? It should not bloat the logs.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/36845#-NAY2ZlzCjwizC7xbgTI:-NAY2tzc7yW0JIjn5Hz_:b-yb045j) ([raw file](https://github.com/harness/harness-core/blob/be84b89591d6b83f813dca19d4b4e09ace045394/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L166)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How frequently would this get logged? It should not bloat the logs. 
</blockquote></details>

I think we can skip logging here. There should be an Unauthorised Exception Handler in code which would be logging it anyway. So, we are covered i guess

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/AuthenticationFilter.java` line 166 at r4](https://reviewable.io/reviews/harness/harness-core/36845#-NAY2ZlzCjwizC7xbgTI:-NA_6Lfv-GooOcofUnNn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/be84b89591d6b83f813dca19d4b4e09ace045394/400-rest/src/main/java/software/wings/security/AuthenticationFilter.java#L166)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

I think we can skip logging here. There should be an Unauthorised Exception Handler in code which would be logging it anyway. So, we are covered i guess
</blockquote></details>

Done.

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845#-:-NA_6ai21GWVLU7ZLHmT:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36845#-:-NA_7iA254nDkrrACS02:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
