### PR TITLE
feat: [CDS-79514]: Harness Prod1 server name getting exposed in the failure execution logs shown to customer

### PR DESCRIPTION
**Pull request by ayushitiwari024**
feat: [CDS-79514]: Handled expection for DuplicateKey Exception

**Issue:** Harness Prod1 server name getting exposed in the failure execution logs shown to customer.

**Changes:** Made a separate DuplicateKeyException File to handle the error and display the appropriate message to the customer. Also in the PmsSweepingOutputServiceImpl.java variable ex was removed as it was sending the complete information about the exception which wasn't necessary.

**Testing:** Tested this case locally: https://harness.atlassian.net/browse/CDS-79514

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)

[CDS-79514]: https://harness.atlassian.net/browse/CDS-79514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kSuX6_bKKcRGtdrT:-Nf9kOFj-RWDhUgvjGAS:b-rkgkrs) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L30)):*
> ```Java
>   public WingsException handleException(Exception exception) {
>     if (exception instanceof DuplicateKeyException) {
>       log.error("Duplicate Key Exception: " + exception.getMessage());
> ```

we should log with string.format with complete exception
___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kWWi8AL2InGPMhnm:-Nf9kWWi8AL2InGPMhnn:b-xeh4xw) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L31)):*
> ```Java
>     if (exception instanceof DuplicateKeyException) {
>       log.error("Duplicate Key Exception: " + exception.getMessage());
>       return new GeneralException("Duplicate Key Exception occurred.Please retry your pipeline.");
> ```

send internalServerException
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9l-oJ6iiAwpODP_sz:-Nf9l-oJ6iiAwpODP_t-:bn9td42) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L49)):*
> ```Java
> import net.jodah.failsafe.RetryPolicy;
> import org.apache.commons.jexl3.JexlException;
> import org.springframework.dao.DuplicateKeyException;
> ```

can you do the same change in PmsOutcomeServiceImpl
___
*[`pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9lKcB8GcnvPtesXOs:-Nf9lKcB8GcnvPtesXOt:bdqpwu7) ([raw file](https://github.com/harness/harness-core/blob/95d77f0198ad3ab1623d3f824f2c10b838705bef/pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java#L73)):*
> ```Java
>         } else {
>           String message = ExceptionUtils.getMessage(ex);
>           log.error("Unknown exception in grpc call: " + message, ex);
> ```

why we have removed this else condition, what if the exception thrown is not wingsException?

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kSuX6_bKKcRGtdrT:-Nf9p0EO7o1tgKGzVDvI:b32v57) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should log with string.format with complete exception
</blockquote></details>

+1

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9lKcB8GcnvPtesXOs:-Nf9yXUi0K3b-SohC91C:b-fupaxx) ([raw file](https://github.com/harness/harness-core/blob/95d77f0198ad3ab1623d3f824f2c10b838705bef/pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we have removed this else condition, what if the exception thrown is not wingsException?
</blockquote></details>

@archit-harness ExceptionManager::processException always returns the WingsException. It will handle the non-wings exceptions and map those into the WingsException as per handlers(Or GeneralExceptionHandler) written for various exception. 

So its the responsibility of ErrorHandlingFramework to handle any exception and give us a wingsException.

**Comment by brijeshdhakar** [comment]
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kSuX6_bKKcRGtdrT:-Nf9zoHp5XUh8wyv8vnt:b-qyuo03) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L30)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I think we should to remove the `exception.getMessage()` from the log line as well. Because the `exception.getMessage()` will have the mongoDB address in it. So it will be logged. (The ticket is originally to remove this info from getting exposed in error message.)

If keeping in logs is fine then yeah we can use the String.format

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kSuX6_bKKcRGtdrT:-NfA02u2ETjnrkDouCTD:b7y10eh) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L30)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think we should to remove the `exception.getMessage()` from the log line as well. Because the `exception.getMessage()` will have the mongoDB address in it. So it will be logged. (The ticket is originally to remove this info from getting exposed in error message.)

If keeping in logs is fine then yeah we can use the String.format
</blockquote></details>

Can we then add handler for sweeping output and outcome to convert into internal server exception
___
*[`pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9lKcB8GcnvPtesXOs:-NfA0DWHCyygiNIYmQH-:b92hi2w) ([raw file](https://github.com/harness/harness-core/blob/95d77f0198ad3ab1623d3f824f2c10b838705bef/pipeline-service/service/src/main/java/io/harness/grpc/server/PipelineServiceGrpcErrorHandler.java#L73)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

@archit-harness ExceptionManager::processException always returns the WingsException. It will handle the non-wings exceptions and map those into the WingsException as per handlers(Or GeneralExceptionHandler) written for various exception. 

So its the responsibility of ErrorHandlingFramework to handle any exception and give us a wingsException.
</blockquote></details>

We should add handler for sweeping output and outcome

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger messagecheck

**Comment by ayushitiwari024** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kSuX6_bKKcRGtdrT:-NfB4OHG3Q96aLWAxeoF:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L30)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we then add handler for sweeping output and outcome to convert into internal server exception
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java` line 31 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9kWWi8AL2InGPMhnm:-NfB4RRz0lzJ_zAULfQn:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/DuplicateKeyExceptionHandler.java#L31)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

send internalServerException
</blockquote></details>

done
___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/SpringDataAccessExceptionHandler.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/53245#-NfB4Krv3_6GGhU5ZOvd:-NfB4Krv3_6GGhU5ZOve:b-7t4dyu) ([raw file](https://github.com/harness/harness-core/blob/721fb8f9a16c20a0bdea5d6afba28158afa4630c/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/SpringDataAccessExceptionHandler.java#L25)):*
> ```Java
> public class SpringDataAccessExceptionHandler implements ExceptionHandler {
>   public static Set<Class<? extends Exception>> exceptions() {
>     return ImmutableSet.<Class<? extends Exception>>builder().add(DuplicateKeyException.class).build();
> ```

This should be DataAccess exception
___
*[`980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/SpringDataAccessExceptionHandler.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/53245#-NfB4PLND2oYihUx88cB:-NfB4PLND2oYihUx88cC:bhutrl3) ([raw file](https://github.com/harness/harness-core/blob/721fb8f9a16c20a0bdea5d6afba28158afa4630c/980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/SpringDataAccessExceptionHandler.java#L31)):*
> ```Java
>   public WingsException handleException(Exception exception) {
>     if (exception instanceof DataAccessException) {
>       log.error(String.format("Duplicate Key Exception: %s", exception));
> ```

message should change for logging

**Review by brijeshdhakar — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: 2 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java` line 49 at r1](https://reviewable.io/reviews/harness/harness-core/53245#-Nf9l-oJ6iiAwpODP_sz:-NfCB8PA19DHKfODRdAE:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e3e4f66e4bbddb12e87292ef99926f6b1ef03e04/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/PmsSweepingOutputServiceImpl.java#L49)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you do the same change in PmsOutcomeServiceImpl
</blockquote></details>

done

**Review by rohitk-h — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53245)* status: :shipit: complete! ✓

**Comment by ayushitiwari024** [comment]
trigger uts

**Comment by ayushitiwari024** [comment]
trigger ut1

**Comment by ayushitiwari024** [comment]
trigger ut8

**Comment by ayushitiwari024** [comment]
trigger ut1

**Comment by ayushitiwari024** [comment]
trigger review

**Pull request merged**
