### PR TITLE
[fix]: [CDS-36970]: Chaos-Hub resource

### PR DESCRIPTION
**Pull request by vtxorxwitty**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32767)

### CODE REVIEW

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32767#-:-N1i7JVFC39jaR8AZM2B:bnfp4nl)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32767)* status: :shipit: complete! ✓

**Comment by hextechpal** [comment]
trigger tin1

**Comment by hextechpal** [comment]
trigger ti1

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32767#-:-N1mbuvm49lFEmwKyBq-:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vtxorxwitty** [comment]
trigger ti0

**Comment by vtxorxwitty** [comment]
trigger ti1

**Pull request merged**
