### PR TITLE
[fix]: [PIE-3408]: Sending module=PIPELINE in pipeline audit events i…

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…nstead of Core

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32116)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32116)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32116)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[970-ng-commons/src/main/java/io/harness/ModuleType.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32116#-N-1chUHD3BnZQwC3Aph:-N-1chUHD3BnZQwC3Api:bfa91te) ([raw file](https://github.com/harness/harness-core/blob/a6aad47dab8497df5fb24297e2be3d6b42c53af7/970-ng-commons/src/main/java/io/harness/ModuleType.java#L28)):*
> ```Java
>   @JsonProperty("CORE") CORE("Core", true),
>   @JsonProperty("PMS") PMS("Pipelines", true),
>   @JsonProperty("PIPELINE") PIPELINE("Pipeline", true),
> ```

PMS is already present for Pipelines. Any reason to introduce new enum type here?

**Comment by brijeshdhakar** [comment]
*[970-ng-commons/src/main/java/io/harness/ModuleType.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/32116#-N-1chUHD3BnZQwC3Aph:-N-1dVpGC5gBk9f6ZDr7:b-buezxc) ([raw file](https://github.com/harness/harness-core/blob/a6aad47dab8497df5fb24297e2be3d6b42c53af7/970-ng-commons/src/main/java/io/harness/ModuleType.java#L28)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

PMS is already present for Pipelines. Any reason to introduce new enum type here?
</blockquote></details>

PMS is very internal to us, external users can not understand this. And yes there is one option to send PMS from backend and UI will map it to Pipeline to show but this will cause issue when users use audit APIs and not UI.

**Comment by brijeshdhakar** [comment]
Closing this pr. Created another with only required changes.

**Pull request closed without merging**
