### PR TITLE
feat: [CDS-37840]: Adding environment step parameters for environment…

### PR DESCRIPTION
**Pull request by prashantsharma04**
… plan creator v2

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: 14 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QymLCDg6E2GCM5Ihn:-N2QymLCDg6E2GCM5Iho:b-5w1hup) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java#L40)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> public class EnvironmentPlanCreator implements PartialPlanCreator<EnvironmentPlanCreatorConfig> {
> ```

rename to plan creator v2



_Code quote:_
```Java
EnvironmentPlanCreator
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyZpc6JvA5XWu-8Ma:-N2QyZpc6JvA5XWu-8Mb:b-gr484e) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java#L72)):*
> ```Java
>         PlanNode.builder()
>             .uuid(ctx.getCurrentField().getNode().getUuid())
>             .stepType(EnvironmentStep.STEP_TYPE)
> ```

new step for v2



_Code quote:_
```Java
EnvironmentStep.STEP_TYPE
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyKuf0rtBK-d1LWZc:-N2QyKuf0rtBK-d1LWZd:brnxvis) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java#L28)):*
> ```Java
> @RecasterAlias("io.harness.cdng.environment.steps.EnvironmentStepParameters")
> public class EnvironmentStepParameters implements StepParameters {
>   String serviceSpecNodeUuid;
> ```

childNodeId



_Code quote:_
```Java
serviceSpecNodeUuid
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyMZ0Babl2Eyiy4gS:-N2QyMZ0Babl2Eyiy4gT:blzk2ae) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java#L29)):*
> ```Java
> public class EnvironmentStepParameters implements StepParameters {
>   String serviceSpecNodeUuid;
>   EnvironmentYaml environmentYaml;
> ```

first class fields



_Code quote:_
```Java
EnvironmentYaml
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: 16 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyKuf0rtBK-d1LWZc:-N2RHCGC-YP0yPsfPzEF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java#L28)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

childNodeId
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyMZ0Babl2Eyiy4gS:-N2RHELm85WhFK2yOqUn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/environment/steps/EnvironmentStepParameters.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

first class fields
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QymLCDg6E2GCM5Ihn:-N2RH1Hh30mVmdWYz0eh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java#L40)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to plan creator v2
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/33338#-N2QyZpc6JvA5XWu-8Ma:-N2RH3Pw5Xhvrqf67Na-:b-4qpiya) ([raw file](https://github.com/harness/harness-core/blob/67ebf41e2518738566e14630e5c83dba541473b0/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreator.java#L72)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

new step for v2
</blockquote></details>

Have added a todo. Will replace this when new step is created for environment

**Comment by prashantsharma04** [comment]
trigger ti1

**Comment by prashantsharma04** [comment]
trigger ti1

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 8 of 12 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 7 of 12 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: :shipit: complete! ✓

**Review by hextechpal — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 7 of 12 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33338)* status: :shipit: complete! ✓

**Pull request merged**
