### PR TITLE
[feat]: [CDS-59517]: service override v2 api/service/repository

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes

CRUDS for Overrides V2
RBAC added
outbox event added

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47455)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 96 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-Ztl46GKcLXZtzRag:-NV-Ztl46GKcLXZtzRah:bb7phvt) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L96)):*
> ```Java
>       , @ApiResponse(code = 500, response = ErrorDTO.class, message = "Internal server error")
>     })
> @Tag(name = "Environments", description = "This contains APIs related to Environments")
> ```

typo

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 130 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-_5Ye6lbVrnXo_3HN:-NV-_5Ye6lbVrnXo_3HO:bhv13eg) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L130)):*
> ```Java
>   @GET
>   @Path("/{serviceOverridesIdentifier}")
>   @ApiOperation(value = "Gets Service Overrides", nickname = "getServiceOverrides")
> ```

Get service override by identifier

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-_mCZCAbtQfxosY8X:-NV-_mCZCAbtQfxosY8Y:b-i3424u) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L157)):*
> ```Java
> 
>     IdentifierRef envIdentifierRef = IdentifierRefHelper.getIdentifierRef(
>         serviceOverridesEntity.getEnvironmentRef(), accountId, orgIdentifier, projectIdentifier);
> ```

catch InvalidIdentifierRefException

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 182 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-_yz85ThUtVYGQfev:-NV-_yz97YzQFmmTOXgN:bsl9xe5) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L182)):*
> ```Java
>              NGCommonEntityConstants.ACCOUNT_KEY) String accountId,
>       @Parameter(description = "Details of the ServiceOverride to be created") @NonNull
>       @Valid ServiceOverrideRequestDTOV2 serviceOverrideRequestDTOV2) {
> ```

nit: can we rename this to requestDTO

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 183 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-a3N-5zrH67IdcA7d:-NV-a3N-5zrH67IdcA7e:b-deherv) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L183)):*
> ```Java
>       @Parameter(description = "Details of the ServiceOverride to be created") @NonNull
>       @Valid ServiceOverrideRequestDTOV2 serviceOverrideRequestDTOV2) {
>     overrideValidatorService.validateRequest(serviceOverrideRequestDTOV2, accountId);
> ```

if this method throws, we can rename it validateOrThrow(..)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 239 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-adOlBRg-4rrqYBGL:-NV-adOlBRg-4rrqYBGM:b-c83sgq) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L239)):*
> ```Java
>     }
>     NGServiceOverridesEntity ngServiceOverridesEntity = ngServiceOverridesEntityOptional.get();
>     overrideValidatorService.validateEnvUsedInServiceOverrideRequest(
> ```

nit: name does not say whether this does RBAC or not

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-bayO-3-gz-Lbo3jC:-NV-bayO-3-gz-Lbo3jD:b-dwo1q9) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L118)):*
> ```Java
>     })
> @OwnedBy(HarnessTeam.CDC)
> @Slf4j
> ```

Lets hide from open api

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-cbhiBrC4EmNHXkkQ:-NV-cbhiBrC4EmNHXkkR:bk4acrv) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java#L27)):*
> ```Java
> import lombok.AllArgsConstructor;
> import lombok.NonNull;
> import org.jetbrains.annotations.NotNull;
> ```

remove not null

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-d6OBD7p_QyTWUjQz:-NV-d6OBD7p_QyTWUjR-:b-hhp3x8) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java#L60)):*
> ```Java
>   private void validateRequiredField(String infraIdentifier) {
>     if (isEmpty(infraIdentifier)) {
>       throw new InvalidRequestException("Infra Identifier should not be empty for INFRA-GLOBAL override");
> ```

Infrastructure override

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 2 of 13 files at r2, 3 of 12 files at r3, 5 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47455)* status: 25 file(s) to review. 0 of 2 approvals obtained.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47455)* status: 25 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 118 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-bayO-3-gz-Lbo3jC:-NV8frC04pSnpBNDNBcY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L118)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets hide from open api
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 130 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-_5Ye6lbVrnXo_3HN:-NV8ftrh6IwI05GIxhTK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L130)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Get service override by identifier
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-cbhiBrC4EmNHXkkQ:-NV8g14ZAXVnhx-3LuoP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java#L27)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

remove not null
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-d6OBD7p_QyTWUjQz:-NV8g1py3S4bqrqj735K:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/validators/InfraGlobalOverrideRequestParamsHandler.java#L60)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Infrastructure override
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java` line 157 at r4](https://reviewable.io/reviews/harness/harness-core/47455#-NV-_mCZCAbtQfxosY8X:-NV8gSlw3dsd9tb11yl5:b-xjsels) ([raw file](https://github.com/harness/harness-core/blob/4799e1990d3fcbea82de95e5fe67ebcc8d8c20cc/120-ng-manager/src/main/java/io/harness/ng/core/serviceoverrides/resources/ServiceOverridesResource.java#L157)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

catch InvalidIdentifierRefException
</blockquote></details>

Not needed, DB state is consistant to have scoped identifier for env/service

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 123 at r5](https://reviewable.io/reviews/harness/harness-core/47455#-NV93J5j4zxpVj7zp_Pz:-NV93J5j4zxpVj7zp_Q-:b8m16wf) ([raw file](https://github.com/harness/harness-core/blob/8b43abfa91c72d3bbc06b3ef1e8dd35f488278ba/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L123)):*
> ```Java
> 
>       return Failsafe.with(transactionRetryPolicy).get(() -> transactionTemplate.execute(status -> {
>         NGServiceOverridesEntity tempResult = serviceOverrideRepositoryV2.update(equalityCriteria, requestedEntity);
> ```

lets call it updatedService ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 123 at r5](https://reviewable.io/reviews/harness/harness-core/47455#-NV93J5j4zxpVj7zp_Pz:-NV93aPg4pK58xqwOeCD:b7hf73f) ([raw file](https://github.com/harness/harness-core/blob/8b43abfa91c72d3bbc06b3ef1e8dd35f488278ba/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L123)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets call it updatedService ?
</blockquote></details>

updatedServiceOverride

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 14 files at r1, 1 of 13 files at r2, 3 of 12 files at r3, 2 of 11 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47455)* status: 25 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java` line 123 at r5](https://reviewable.io/reviews/harness/harness-core/47455#-NV93J5j4zxpVj7zp_Pz:-NV9hTnh4RuZ-eFP_UWg:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8b43abfa91c72d3bbc06b3ef1e8dd35f488278ba/125-cd-nextgen/src/main/java/io/harness/cdng/serviceoverridesv2/services/ServiceOverridesServiceV2Impl.java#L123)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

updatedServiceOverride
</blockquote></details>

done

**Comment by tchaurasiya** [comment]
trigger uts

**Comment by tchaurasiya** [comment]
trigger uts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 9 of 11 files at r7, 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47455)* status: 26 file(s) to review. 1 of 2 approvals obtained.

**Review by sourabh-awashti — APPROVED** [review]

**Comment by tchaurasiya** [comment]
trigger review

**Pull request merged**
