### PR TITLE
[feat]: [CDS-78666]: Merging the V0 templates into the V1 pipelines

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Merging the V0 templates into the V1 pipelines.
Added YAML validations for the simplified YAML that it would not have duplicate ids.
Added support to inject id inside the simplified YAML so that each step/stage would have an auto-generated id based on its name/type.
Did some refactoring in the FqnMapGenerator and YamlMapGenerator.

Tested: 

> V0 step template inside the V1 stage.
> V0 stage template inside V1 pipeline.
> V0 step template with inputs inside V1 stage.
> V0 stage template with inputs inside V1 pipeline.

Executed the below pipeline it has Step template with input and stage template.

```version: 1
name: POC_V0_STEPS_IN_V1_PIPELINE
inputs:
  input1:
    type: string
  duration:
    type: string
stages:
  - stage:
      name: custom_stage_template
      identifier: custom_stage_template
      template:
        templateRef: Stage_template
        versionLabel: v1
  - stage:
      name: custom1
      identifier: custom1
      description: ""
      type: Custom
      spec:
        execution:
          steps:
            - step:
                type: ShellScript
                name: ShellScript_1
                identifier: ShellScript_1
                spec:
                  shell: Bash
                  onDelegate: true
                  source:
                    type: Inline
                    spec:
                      script: echo HI
                  environmentVariables: []
                  outputVariables: []
                timeout: 10m
      tags: {}
      when:
        pipelineStatus: Success
  - type: Custom
    name: stage1
    when: "true"
    spec:
      steps:
        - step:
            type: ShellScript
            name: ShellScript_1
            identifier: ShellScript_1
            spec:
              shell: Bash
              onDelegate: true
              source:
                type: Inline
                spec:
                  script: echo <+inputs.input1>
                environmentVariables: []
                outputVariables: []
            timeout: 10m
        - step:
            name: wait
            identifier: wait
            template:
              templateRef: Wait_step_template
              versionLabel: V1
              templateInputs: 
                type: Wait 
                spec: 
                  duration: <+inputs.duration>
        - type: ShellScript
          timeout: 20s
          spec:
            shell: Bash
            onDelegate: true
            source:
              type: Inline
              spec:
                script: echo HI
            environmentVariables: []
            outputVariables: []
        - type: Http
          timeout: 20s
          spec:
            method: GET
            url: https://www.google.com/
        - step:
            when:
              stageStatus: All
            type: Http
            name: Http_1
            identifier: Http_1
            spec:
              url: https://www.google.com/
              method: GET
              headers: []
              inputVariables: []
              outputVariables: []
            timeout: 30s
  - stage:
      name: custom2
      identifier: custom2
      description: ""
      type: Custom
      spec:
        execution:
          steps:
            - step:
                type: Http
                name: Http_1
                identifier: Http_1
                spec:
                  url: https://www.google.com/
                  method: GET
                  headers: []
                  inputVariables: []
                  outputVariables: []
                timeout: 10s
      tags: {}
      when:
        pipelineStatus: All
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java` line 191 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemUttDBGYASzs2VSxp:-NemUttDBGYASzs2VSxq:b-9yu6jy) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java#L191)):*
> ```Java
>           } else {
>             identifier = element.get(YAMLFieldNameConstants.TYPE).asText();
>             uuidKey = YAMLFieldNameConstants.TYPE;
> ```

as discussed last time, we should pre construct the yaml with identifiers

as 

```> The name of the action currently running, or the `id` of a step. GitHub removes special characters, and uses the name `__run` when the current step runs a script without an `id`. If you use the same action more than once in the same job, the name will include a suffix with the sequence number with underscore before it. For example, the first script you run will have the name `__run`, and the second script will be named `__run_2`. Similarly, the second invocation of `actions/checkout` will be `actionscheckout2`.

so in our case, we could use `id`, then fallback to `name` (converted to a slug) and then fallback to `type` (there will always be a type).  If we use the `name` or `type` as the step identifier, and it is non-unique, we can add a suffix with a numeric sequence.  e.g. `script_1`
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVBb1DiUNot3OUHG3:-NemVBb1DiUNot3OUHG4:baxidv1) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java#L169)):*
> ```Java
>         if (innerMap.get(YAMLFieldNameConstants.IDENTIFIER) != null) {
>           identifier = innerMap.get(YAMLFieldNameConstants.IDENTIFIER).asText();
>           uuidKey = YAMLFieldNameConstants.IDENTIFIER;
> ```

then we dont need this even
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVGJg2zRBFGI2mhR6:-NemVGJg2zRBFGI2mhR7:b-kywmef) ([raw file](https://github.com/harness/harness-core/blob/9545878431db32de484c13b8d4f9cc8910c3603c/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java#L166)):*
> ```Java
>   }
> 
>   private boolean isStagesNodeGrandChildOfPipelineNode(YamlField config) {
> ```

earlier it was added,why its not needed anymore?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVTyb2moo-pV5HzyF:-NemVTyb2moo-pV5HzyG:bosp8el) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L335)):*
> ```Java
>   private JsonNode getStagesNodeWrapperFromPipelineYaml(String pipelineYaml) {
>     JsonNode jsonNode = YamlUtils.readAsJsonNode(pipelineYaml);
>     return ((ObjectNode) JsonUtils.readTree("{}"))
> ```

are we putting stages inside spec field?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 8 file(s) to review. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java` line 191 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemUttDBGYASzs2VSxp:-NeqhmAe8DI8l3S98cNY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/FQNMapGenerator.java#L191)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

as discussed last time, we should pre construct the yaml with identifiers

as 

```> The name of the action currently running, or the `id` of a step. GitHub removes special characters, and uses the name `__run` when the current step runs a script without an `id`. If you use the same action more than once in the same job, the name will include a suffix with the sequence number with underscore before it. For example, the first script you run will have the name `__run`, and the second script will be named `__run_2`. Similarly, the second invocation of `actions/checkout` will be `actionscheckout2`.

so in our case, we could use `id`, then fallback to `name` (converted to a slug) and then fallback to `type` (there will always be a type).  If we use the `name` or `type` as the step identifier, and it is non-unique, we can add a suffix with a numeric sequence.  e.g. `script_1`
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java` line 169 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVBb1DiUNot3OUHG3:-NeqhoRi-9Y_8Bis3L1O:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/YamlMapGenerator.java#L169)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

then we dont need this even
</blockquote></details>

Done.
___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVGJg2zRBFGI2mhR6:-Neqhrq754xBSZPSwLaS:bsbv3tf) ([raw file](https://github.com/harness/harness-core/blob/9545878431db32de484c13b8d4f9cc8910c3603c/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1/StagesPlanCreatorV1.java#L166)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

earlier it was added,why its not needed anymore?
</blockquote></details>

Right now we don't need this. Might need to make some changes based on what expressions we want to support.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 335 at r2](https://reviewable.io/reviews/harness/harness-core/52568#-NemVTyb2moo-pV5HzyF:-NeqhJsDB8eOCYd7zLGD:bqfug0l) ([raw file](https://github.com/harness/harness-core/blob/982d39f6d728c3ab0ab81d50baab0846d0175257/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L335)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

are we putting stages inside spec field?
</blockquote></details>

We need to give the wrapper of the specField so that the root jsonNode has only one key and FQNMapGenerator traverses complete jsonNode. On first it expects a root node and it traverses the topKey(firstKey) only in the root node.

**Review by archit-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 8 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 10 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner8wAA2PUJU_evoOlc:-Ner8wAA2PUJU_evoOld:b-aftggu) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L46)):*
> ```Java
>   }
> 
>   private void traverseForIdsRecursively(JsonNode jsonNode, Set<String> idsValuesSet) {
> ```

rename to mention collectIdsFromYamlRecursively
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 73 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner96RVA8f9Vw4G0Vfd:-Ner96RWEZhkormypotR:b-milivy) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L73)):*
> ```Java
>   }
> 
>   private void addIdsInJsonNodeRecursively(
> ```

addGeneratedIdInJsonNodeRecursively
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner9MXG1hQRMP4BSLUg:-Ner9MXG1hQRMP4BSLUh:b-rqptvx) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L97)):*
> ```Java
>           continue;
>         }
>         Integer previousSuffixValue = idsSufixMap.getOrDefault(id, 0);
> ```

add comments what piece of code is doing what

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner8wAA2PUJU_evoOlc:-NerByVR4Chwi3x2IpLQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename to mention collectIdsFromYamlRecursively
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 73 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner96RVA8f9Vw4G0Vfd:-NerC-cjDYy4tekpsc-y:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L73)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

addGeneratedIdInJsonNodeRecursively
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/52568#-Ner9MXG1hQRMP4BSLUg:-NerC0Nz6Pmej9YKrlct:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/de3e14c77766bfce902ae112b94eb3b00f5882fc/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/preprocess/PipelineV1Preprocessor.java#L97)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add comments what piece of code is doing what
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts messagecheck

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r3, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52568)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger ut6

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
