### PR TITLE
feat: [PIE-9168]: fetch OAuth creds for git fetch and commit

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

Fetch OAuth Credentials of the user from newly created entity UserSourceCodeManager and set that value in the connector while performing git operations like create, update and get calls.

**Testing:** Tested the behaviour locally on the flows via both manager and delegate.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4mdO47UCIiemDTsr6:-NS4mdO47UCIiemDTsr7:b-zb98ps) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L133)):*
> ```Java
>     // setting service principal for connector decryption in case of Git Connector
>     GitSyncUtils.setGitSyncServicePrincipal();
>     Optional<String> userIdentifier = getUserIdentifier(currentPrincipal);
> ```

why do we need to pass principal as argument?

**Review by senjucanon2 — COMMENTED** [review]
> Reviewed 1 of 28 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 28 file(s) to review. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4pGlf1FTdxU8Dxash:-NS4pGlf1FTdxU8Dxasi:bshp88b) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L384)):*
> ```Java
>           break;
>         default:
>           log.info("OAUTH not supported for connector type: {}", connectorDTO.getConnectorType());
> ```

please check if we want to use .info or .error here.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1192 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4owif2SeRLD-s2Asz:-NS4owif2SeRLD-s2At-:b-asq275) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1192)):*
> ```Java
>     if (userIdentifier.isPresent()) {
>       connectorDTO = gitSyncConnectorHelper.fetchOAuthCreds(accountIdentifier, userIdentifier.get(), connectorDTO);
>     }
> ```

Can we log here in case of userIdentifer not present?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 28 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4mdO47UCIiemDTsr6:-NS4qs8jAduzl4DDsbI1:bckxj9f) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L133)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to pass principal as argument?
</blockquote></details>

we need userIdentifier to fetch OAuth credentials from the new table and we don't have userId in the request so we need to fetch it from the principal only.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 384 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4pGlf1FTdxU8Dxash:-NS4p_oH4CW4DtUerWwZ:bf7w5rc) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L384)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

please check if we want to use .info or .error here.
</blockquote></details>

I think info should be fine here because we have not added support for OAuth for all git providers yet.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1192 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4owif2SeRLD-s2Asz:-NS4q6bXB6YKT1mYXYr9:b-rvrcke) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1192)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Can we log here in case of userIdentifer not present?
</blockquote></details>

that should never be the case here but yeah we can add an error log just in case.

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 132 at r4](https://reviewable.io/reviews/harness/harness-core/45881#-NS4tRC85fQfnzj_v071:-NS4tRC85fQfnzj_v072:b-mo8frq) ([raw file](https://github.com/harness/harness-core/blob/1a7561769d836d46b705c190cca6830dee5fa36c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L132)):*
> ```Java
>     PrincipalContextData currentPrincipal = GlobalContextManager.get(PrincipalContextData.PRINCIPAL_CONTEXT);
>     // setting service principal for connector decryption in case of Git Connector
>     GitSyncUtils.setGitSyncServicePrincipal();
> ```

Not related to the change but why do we set this explicitly? @mohitg0795  any idea?

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 369 at r4](https://reviewable.io/reviews/harness/harness-core/45881#-NS4tzfaBKnF12JPia3-:-NS4tzfaBKnF12JPia30:btsepbs) ([raw file](https://github.com/harness/harness-core/blob/1a7561769d836d46b705c190cca6830dee5fa36c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L369)):*
> ```Java
>       switch (connectorDTO.getConnectorType()) {
>         case GITHUB:
>           GithubSCMDTO githubSCMDTO = (GithubSCMDTO) userSourceCodeManagerDTO;
> ```

nit: Can this be simplified? We can expose getApiAccess and setApi on the interface itself and use it directly here

**Comment by sahilhindwani-harness** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 395 at r4](https://reviewable.io/reviews/harness/harness-core/45881#-NS4uWgP8dV5-LxGJOAS:-NS4uWgP8dV5-LxGJOAT:b7rqjt6) ([raw file](https://github.com/harness/harness-core/blob/1a7561769d836d46b705c190cca6830dee5fa36c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L395)):*
> ```Java
>       userIdentifier = Optional.of(currentPrincipal.getPrincipal().getName());
>     } else {
>       log.error("Could not find userIdentifier from principal: {}", currentPrincipal);
> ```

nit: should we convert this to warn?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 25 of 28 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 27 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 27 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 395 at r4](https://reviewable.io/reviews/harness/harness-core/45881#-NS4uWgP8dV5-LxGJOAS:-NS55gQ43xvA2LAqQLKF:b-m0blvp) ([raw file](https://github.com/harness/harness-core/blob/1a7561769d836d46b705c190cca6830dee5fa36c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L395)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: should we convert this to warn?
</blockquote></details>

this would actually be an error if we can't find the user identifier, right?
Because git operations can only be done manually not via a trigger or in case of timeout 
And if done manually, there should always be a userId present, if it's not then it's an error that should be checked by us.
So, I think we should keep it as error only.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 362 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS588SM22kst2X2vyUk:-NS588SM22kst2X2vyUl:b-j6uab0) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L362)):*
> ```Java
>   }
> 
>   public ScmConnector fetchOAuthCreds(String accountId, String userId, ScmConnector connectorDTO) {
> ```

please use suffix "identifier" for account or user.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 27 file(s) to review. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS4mdO47UCIiemDTsr6:-NS58oNU6qRGIeDgjzGZ:bqhdmh0) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L133)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, but we don't need to pass it as argument right? We can directly use it inside the method.
</blockquote></details>

yes, we can do that. Done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 362 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS588SM22kst2X2vyUk:-NS58xtaEjEdEUeOOXPy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L362)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

please use suffix "identifier" for account or user.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 364 at r3](https://reviewable.io/reviews/harness/harness-core/45881#-NS58OAw4xa96Rpcj9DK:-NS594687Bor0hC7evyf:ba9z0ar) ([raw file](https://github.com/harness/harness-core/blob/70d316ef9cadc7cbe6398bcb863a81dcfe68c1bc/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L364)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should also have a warn log here to identify anomalies in case where we have multiple source code managers.
</blockquote></details>

but we have an index on {accountId, userId, type}, so there can never be more than one SCMs for one combination of these fields, right?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 390 at r5](https://reviewable.io/reviews/harness/harness-core/45881#-NS5WZWfEHNrTwzIWo4T:-NS5WZWfEHNrTwzIWo4U:b-73ssd2) ([raw file](https://github.com/harness/harness-core/blob/11c243b82326493c764dc048c73c812fa5be2470/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L390)):*
> ```Java
>   }
> 
>   public Optional<String> getUserIdentifier() {
> ```

Can we check if we have some other util where we can move this method to? This looks to be a pretty generic method.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java` line 395 at r4](https://reviewable.io/reviews/harness/harness-core/45881#-NS4uWgP8dV5-LxGJOAS:-NS5Wwur4qwdlEXQYKT4:bwh7n4v) ([raw file](https://github.com/harness/harness-core/blob/1a7561769d836d46b705c190cca6830dee5fa36c/136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java#L395)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

this would actually be an error if we can't find the user identifier, right?
Because git operations can only be done manually not via a trigger or in case of timeout 
And if done manually, there should always be a userId present, if it's not then it's an error that should be checked by us.
So, I think we should keep it as error only.
</blockquote></details>

If we think about it, its a generic method which just finds out user identifier from principal.
- if we really care about the error, we should throw exception here in case we are sure that it should be a user principal always. This should be done only for known use-cases where its expected.
- If we are just checking and fetching data that we require, then we should may be not have this log itself. This should be done in cases where different types of principals can exist and such logs are bound to be there.

**Review by senjucanon2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 29 file(s) to review. 7. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 723 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSATNto0VPGGXwlKx4n:-NSATNto0VPGGXwlKx4o:b-e81fxo) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L723)):*
> ```Java
>   public GetUserRepoResponse getRepoDetails(
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, ScmConnector scmConnector) {
>     ScmConnector connectorDTO = getConnectorWithUserOAuthCreds(accountIdentifier, scmConnector);
> ```

The method name seems to be wrong here. We shouldn't say "OAuth" anywhere in the method. Its simply user creds, doesn't matter which type.
Also, I think we shouldn't return connector here. We can simply say : setUserCreds or something similar.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1187 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAU80mApVWF3D9ZKNZ:-NSAU80mApVWF3D9ZKN_:bkga30v) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1187)):*
> ```Java
> 
>   private ScmConnector getConnectorWithUserOAuthCreds(String accountIdentifier, ScmConnector connectorDTO) {
>     return gitSyncConnectorHelper.fetchOAuthCreds(accountIdentifier, connectorDTO);
> ```

Method "fetchOAuthCreds" shouldn't return connector, doesn't sound right. Agreed?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 108 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAWhbJ-l1yrPHh_dII:-NSAWhbJ-l1yrPHh_dIJ:bteyr2o) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L108)):*
> ```Java
>     } else {
>       userSourceCodeManagerDTOs =
>           List.of(userSourceCodeManagerService.getByType(accountIdentifier, userIdentifier, type));
> ```

Doesn't it fail if getByType() returns null?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 19 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAXJZ7-_aqfEL5hr9g:-NSAXJZ7-_aqfEL5hr9h:b-jgxspt) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L19)):*
> ```Java
> @OwnedBy(PIPELINE)
> public interface UserSourceCodeManagerService {
>   UserSourceCodeManagerDTO getByType(String accountIdentifier, String userIdentifier, String type);
> ```

idk if we missed it last time. What does "type" represent here? Its not clear + why isn't it an enum? Can we use an enum here?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 29 file(s) to review. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 723 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSATNto0VPGGXwlKx4n:-NSAUtEgD5NB9nBVKLWq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L723)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

The method name seems to be wrong here. We shouldn't say "OAuth" anywhere in the method. Its simply user creds, doesn't matter which type.
Also, I think we shouldn't return connector here. We can simply say : setUserCreds or something similar. 
</blockquote></details>

done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java` line 1187 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAU80mApVWF3D9ZKNZ:-NSAUkld1rns_lwCUVv_:b-6ox3jo) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmDelegateFacilitatorServiceImpl.java#L1187)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Method "fetchOAuthCreds" shouldn't return connector, doesn't sound right. Agreed?
</blockquote></details>

yes agreed, done
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java` line 108 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAWhbJ-l1yrPHh_dII:-NSAYXu3-mQWNDmQZyIN:b-p7cu61) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/UserSourceCodeManagerResource.java#L108)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Doesn't it fail if getByType() returns null?
</blockquote></details>

yes it does, sorry, didn't test this before, have fixed it now
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java` line 19 at r7](https://reviewable.io/reviews/harness/harness-core/45881#-NSAXJZ7-_aqfEL5hr9g:-NSAafJW9zKZJA3tQGr_:b-fm51ea) ([raw file](https://github.com/harness/harness-core/blob/6cf3165f83c7f805a60284e0dda269dcc0c41855/136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/UserSourceCodeManagerService.java#L19)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

idk if we missed it last time. What does "type" represent here? Its not clear + why isn't it an enum? Can we use an enum here?
</blockquote></details>

yeah, done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 21 of 28 files at r2, 1 of 8 files at r6, 2 of 3 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 21 of 28 files at r2, 1 of 8 files at r6, 2 of 3 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45881)* status: 1. unresolved discussions.

**Pull request merged**
