### PR TITLE
[feat]: [CDS-35387]: Add File Store support

### PR DESCRIPTION
**Pull request by ivan-83**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 6 of 20 files at r1, 2 of 10 files at r2, 1 of 2 files at r3, 4 of 14 files at r4, 4 of 13 files at r6, 1 of 5 files at r9, 14 of 14 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/FileStoreService.java, line 17 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-McSfpC3sPr-VGpTWG:-N-McSfpC3sPr-VGpTWH:b-7le62a) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/FileStoreService.java#L17)):*
> ```Java
> import javax.validation.constraints.NotNull;
> 
> public interface FileStoreService {
> ```

owner
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 99 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N4KQM1-jbPg6nZGso:-N-N4KQM1-jbPg6nZGsp:b16u60g) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L99)):*
> ```Java
>     NGFile existingFile =
>         fileStoreRepository
>             .findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndIdentifier(
> ```

we are usually operating trough `IdenfierRef` instead of passing identifiers along.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 184 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N4w-f6xq-jBRyqSAZ:-N-N4w-f6xq-jBRyqSA_:b-1p23ih) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L184)):*
> ```Java
> 
>   private String getDuplicateEntityMessage(@NotNull FileDTO fileDto) {
>     return format("Try creating another %s, %s with identifier [%s] already exists in the parent folder",
> ```

i guess we can make it more meaningfull with `File with identifier xyz alread exists in the specified folder path.`
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 192 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N6caG1B2ynKaIiVdC:-N-N6caG1B2ynKaIiVdD:b-rnbc3s) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L192)):*
> ```Java
>         new BoundedInputStream(content, configuration.getFileUploadLimits().getFileStoreFileLimit());
>     NGBaseFile ngBaseFile = FileDTOMapper.getNgBaseFileFromFileDTO(fileDto);
>     fileService.saveFile(ngBaseFile, fileContent, FILE_STORE);
> ```

we should be careful here saving in different store name. Did we checked the scenario for the non on prem customers, do we need to raise a ticket with SECOPS to create the bucket in gcs or it will be automatically created?
___
*[120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/FileUsage.java, line 14 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N7i0r2WtDjKrHAGX4:-N-N7i0r2WtDjKrHAGX5:b-b8rha4) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/FileUsage.java#L14)):*
> ```Java
> import io.harness.annotations.dev.OwnedBy;
> 
> @OwnedBy(CDP) public enum FileUsage { MANIFEST_FILE }
> ```

Config and Script is missing also
___
*[120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/NGFileType.java, line 10 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N7onw4N5-pXR0T8x6:-N-N7onw4N5-pXR0T8x7:blz8kxu) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/NGFileType.java#L10)):*
> ```Java
> package io.harness.ng.core.dto.filestore;
> 
> public enum NGFileType { FILE, FOLDER }
> ```

owner is missing

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: 14 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/FileStoreService.java, line 17 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-McSfpC3sPr-VGpTWG:-N-SXhpA0uQc2gOaB9MB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/FileStoreService.java#L17)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 184 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N4w-f6xq-jBRyqSAZ:-N-SXk2DECWRq8hqV3z8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L184)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

i guess we can make it more meaningfull with `File with identifier xyz alread exists in the specified folder path.`
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/FileUsage.java, line 14 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N7i0r2WtDjKrHAGX4:-N-SXpNx-ZepSjnN83-h:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/FileUsage.java#L14)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

Config and Script is missing also
</blockquote></details>

Done.
___
*[120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/NGFileType.java, line 10 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N7onw4N5-pXR0T8x6:-N-SXqJF46MFbWVSNIFq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/NGFileType.java#L10)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

owner is missing
</blockquote></details>

Done.

**Comment by ivan-83** [comment]
trigger messagecheck

**Comment by ivan-83** [comment]
trigger messagecheck

**Review by ivan-83 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: 33 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 99 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N4KQM1-jbPg6nZGso:-N-ZhYGg-PraYN8fCQWR:b-hg3r25) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L99)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we are usually operating trough `IdenfierRef` instead of passing identifiers along.
</blockquote></details>

Agree, we are using this method from spring data and have to pass identifiers along.



_Code quote:_
```Java
findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndIdentifier
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 192 at r10](https://reviewable.io/reviews/harness/harness-core/31836#-N-N6caG1B2ynKaIiVdC:-N-ZhsaJCqy_fPhtrnYO:b8w1045) ([raw file](https://github.com/harness/harness-core/blob/330e2617c31132a1942b89ebc6bfc6afa5cff411/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L192)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

we should be careful here saving in different store name. Did we checked the scenario for the non on prem customers, do we need to raise a ticket with SECOPS to create the bucket in gcs or it will be automatically created?
</blockquote></details>

Will check with SECOPS team.

**Review by acasian-harness — APPROVED** [review]
> Reviewed 7 of 14 files at r12, 2 of 3 files at r13, 24 of 24 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: :shipit: complete! ✓

**Review by gupta-utkarsh — COMMENTED** [review]
> Reviewed 1 of 14 files at r10, 1 of 24 files at r14.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: 3 file(s) to review. 0 of 1 approvals obtained.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 20 files at r1, 2 of 10 files at r2, 1 of 2 files at r3, 3 of 14 files at r4, 2 of 13 files at r6, 1 of 5 files at r9, 4 of 14 files at r10, 7 of 14 files at r12, 1 of 3 files at r13, 20 of 24 files at r14, 2 of 3 files at r15, 3 of 5 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31836)* status: :shipit: complete! ✓

**Pull request merged**
