### PR TITLE
[feat]: [CDS-45130]: rPopulate Yaml Field In NGEnvironment Migration

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39021)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnonKc3UYn3X5v61EP:-NEnonKc3UYn3X5v61EQ:bdg5yck) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L42)):*
> ```Java
>       List<AccountDTO> allAccounts = CGRestUtils.getResponse(accountClient.getAllAccounts());
>       List<String> accountIdentifiers =
>           allAccounts.stream().map(AccountDTO::getIdentifier).collect(Collectors.toList());
> ```

should we not filter for NG accounts ?

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnpPB6CibDUWOrB5y5:-NEnpPB6CibDUWOrB5y6:b-5vlc2w) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L56)):*
> ```Java
>                 String yaml = EnvironmentMapper.toYaml(ngEnvironmentConfig);
>                 envEntity.setYaml(yaml);
>                 environmentService.update(envEntity);
> ```

Lets not use environmentService. It will send audit also which will be visible on Harness UI
We can directly patch the `yaml` field of the mongo document

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnpohc5Bq3kLSvDIO-:-NEnpohc5Bq3kLSvDIO0:b5ecvwp) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L62)):*
> ```Java
>           log.info(
>               DEBUG_LOG + "Migration of populating yaml field in environment completed for account : " + accountId);
>         } catch (Exception e) {
> ```

If migration fails for 1 account, will we stop there ?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 56 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnpPB6CibDUWOrB5y5:-NEoh9RFDx1mEYgbFbx_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L56)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets not use environmentService. It will send audit also which will be visible on Harness UI
We can directly patch the `yaml` field of the mongo document
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnpohc5Bq3kLSvDIO-:-NEohAvw0HYUnLmf9Zg-:bnvh6wo) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L62)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

If migration fails for 1 account, will we stop there ?
</blockquote></details>

Thanks for pointing. I missed the auto generated catch block.

**Review by tchaurasiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39021)* status: 2 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/39021#-NEnonKc3UYn3X5v61EP:-NEo2iOz2MPccJ3EQP-L:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d5b6d6b77c025f9804b9185da1c0b373bd7cee69/120-ng-manager/src/main/java/io/harness/ng/core/migration/PopulateYamlFieldInNGEnvironmentMigration.java#L42)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not filter for NG accounts ?
</blockquote></details>

Done.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
*[`.bazelrc` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/39021#-NEoo-ag0w0H1xaOqqhu:-NEoo-ag0w0H1xaOqqhv:b-lcnqd6) ([raw file](https://github.com/harness/harness-core/blob/5e95edbf0b13740bbb6af6a2c0cda8359027822d/.bazelrc#L3)):*
> ```
> import bazelrc.local
> 
> build --disk_cache=~/.bazel-dirs/cache
> ```

not needed ?

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/config.yml` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/39021#-NEoo3Wy31RrZephDc3D:-NEoo3Wy31RrZephDc3E:bfcm7q1) ([raw file](https://github.com/harness/harness-core/blob/5e95edbf0b13740bbb6af6a2c0cda8359027822d/120-ng-manager/config.yml#L261)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: true
> ```

not needed

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39021)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Comment by tchaurasiya** [comment]
*[`.bazelrc` line 3 at r3](https://reviewable.io/reviews/harness/harness-core/39021#-NEoo-ag0w0H1xaOqqhu:-NEopf7kDbB42Xod6EAy:bj7vq6s) ([raw file](https://github.com/harness/harness-core/blob/5e95edbf0b13740bbb6af6a2c0cda8359027822d/.bazelrc#L3)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

not needed ?
</blockquote></details>

pushed by mistake.reverted.

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/config.yml` line 261 at r3](https://reviewable.io/reviews/harness/harness-core/39021#-NEoo3Wy31RrZephDc3D:-NEopk4NCw8y_Zc1Y-pT:bj7vq6s) ([raw file](https://github.com/harness/harness-core/blob/5e95edbf0b13740bbb6af6a2c0cda8359027822d/120-ng-manager/config.yml#L261)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

not needed 
</blockquote></details>

pushed by mistake.reverted.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39021)* status: :shipit: complete! ✓

**Pull request merged**
