### PR TITLE
feat: [CDS-39529]: Refactor app settings config to support encrypted files

### PR DESCRIPTION
**Pull request by abosii-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.
## Codebase hashcheck
- Is it new task type? (If yes, no need to answer 2 then)
  **No**
- Did you add a new class which is added in kryo serialization
  **Yes**
- if yes then do not use that class in any of the delegate task payload till it makes to delegate release
  **Task is not used yet in production**
- Did you make changes to the code in a backward-compatible manner?
  **Task is not used yet in prod**
- will the new version of the delegate receive old version task and process?
  **N/A**
- If new version of the manager receives response for the old task will it be able to handle it successfully?
  **Yes**
- Ng backward compatibility → did you make a change in delegate task which will be created in ng services via grpc call to manager
  **No**
- If the older version of ng service creates the task parameter and calls newer cg manager, will it be okay
  **Yes**
- if the newer version of ng service creates the task parameter and calls older cg manager, will it be okay
  **Yes**
- Did you remove an enum → this is not backward compatible yet (tracked by [DEL-3648: Move to name based kryo serializer for delegate/manager communicationIN PROGRESS](https://harness.atlassian.net/browse/DEL-3648) )
  **No**
- Did you add an enum → make sure that the enum constant is added in the end of the already defined constants. If you don’t do this then you will have issues where wrong enum type will be deserialized in delegate side.
  **No**  
## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)

### CODE REVIEW

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Comment by abosii-harness** [comment]
trigger feature-build

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/config.yml` line 462 at r2](https://reviewable.io/reviews/harness/harness-core/35164#-N6i9xDs1luuqgH4xa_3:-N6i9xDs1luuqgH4xa_4:br35n3) ([raw file](https://github.com/harness/harness-core/blob/8f96f2a9dcbf0d34e9fb2b1544d8cf20d7a4c9e7/120-ng-manager/config.yml#L462)):*
> ```YAML
> 
> debeziumConsumerConfigs:
>   - topicName: ${TOPIC_NAME:-DEBEZIUM_pmsMongo.pms-harness.planExecutionsSummary}
> ```

do we want to remove it?

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger feature-build, publish-delegate

**Comment by abosii-harness** [comment]
trigger feature-build

**Review by vlica-harness — DISMISSED** [review]

**Review by vlica-harness — APPROVED** [review]

**Review by abosii-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)* status: 1 change requests. 1. unresolved discussions. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/request/AbstractSlotDataRequest.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/35164#-N7MeDG8BbZdDkrkMeln:-N7MedXM9SIL4_w2CcQg:b-snz30j) ([raw file](https://github.com/harness/harness-core/blob/c31e3bbdd6255513cea90b0d2e53aa127a8fc02d/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/azure/appservice/webapp/ng/request/AbstractSlotDataRequest.java#L36)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

You should add new parameters and not unset the old ones in the server and in the new delegate code use the new ones. 
</blockquote></details>

Task is not yet used in production and feature is still in development.  We don't expect any customers to use it with current version of delegate

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 13 of 20 files at r1, 2 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35164)* status: :shipit: complete! ✓

**Comment by abosii-harness** [comment]
trigger codebasehash

**Pull request merged**
