### PR TITLE
fix: [CDS-44652]: add command flag support for helm repo add helm rep…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…o update

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)

### CODE REVIEW

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java` line 1115 at r2](https://reviewable.io/reviews/harness/harness-core/38752#-NEFuM6P0-vX_MyisWSR:-NEFuM6P0-vX_MyisWSS:b-y2yr1n) ([raw file](https://github.com/harness/harness-core/blob/c1b391b2b04d14b3886090cd6f9bfb7eee09cbbf/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java#L1115)):*
> ```Java
>     assertThatThrownBy(()
>                            -> helmTaskHelperBase.addRepo("vault", "vault", "https://helm-server", "admin",
>                                "secret-text".toCharArray(), "/home", V2, 9000L, "", null))
> ```

add cases with command flags as well
___
*[`960-api-services/src/main/java/io/harness/helm/HelmCommandTemplateFactory.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/38752#-NEFu4PE-BKeOb9htV-T:-NEFu4PE-BKeOb9htV-U:b-gg955h) ([raw file](https://github.com/harness/harness-core/blob/c1b391b2b04d14b3886090cd6f9bfb7eee09cbbf/960-api-services/src/main/java/io/harness/helm/HelmCommandTemplateFactory.java#L162)):*
> ```Java
>             return HelmConstants.V2Commands.HELM_REPO_ADD_COMMAND_FOR_HTTP;
>         }
>       case REPO_ADD_CHART_MUSEUM:
> ```

if this value is integrated with UI, this might break.
validate once.

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java` line 1115 at r2](https://reviewable.io/reviews/harness/harness-core/38752#-NEFuM6P0-vX_MyisWSR:-NEZRJAy4IADp06im1qY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1b391b2b04d14b3886090cd6f9bfb7eee09cbbf/930-delegate-tasks/src/test/java/io/harness/delegate/task/helm/HelmTaskHelperBaseTest.java#L1115)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

add cases with command flags as well
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/helm/HelmCommandTemplateFactory.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/38752#-NEFu4PE-BKeOb9htV-T:-NEZRKaiDhLmi10j5wNn:brvkg7j) ([raw file](https://github.com/harness/harness-core/blob/c1b391b2b04d14b3886090cd6f9bfb7eee09cbbf/960-api-services/src/main/java/io/harness/helm/HelmCommandTemplateFactory.java#L162)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

if this value is integrated with UI, this might break.
validate once.
</blockquote></details>

Checked, not used in UI

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)* status: :shipit: complete! ✓

**Review by shubham-in10se — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger codebasehash

**Review by abosii-harness — APPROVED** [review]
> Reviewed 11 of 16 files at r1, 2 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38752)* status: :shipit: complete! ✓

**Pull request merged**
