### PR TITLE
feat: [Del-5792]: tasklib

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Describe your changes
K8s task separation and containerization
Executorlib implementation that can enable the containerization of tasks

Test Status:
Tested with pre-QA manager + delegate core + task container
image
Screen Shot 2023-02-03 at 4 28 19 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42635)

### CODE REVIEW

**Comment by xingchi-jin** [comment]
trigger ti1

**Review by mdmilic — APPROVED** [review]
> Reviewed 28 of 46 files at r3, 9 of 20 files at r4, 11 of 15 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42635)* status: :shipit: complete! ✓

___
*[`delegate/src/main/java/io/harness/delegate/executor/serviceproviders/DelegateAccountIdProvider.java` line 17 at r6](https://reviewable.io/reviews/harness/harness-core/42635#-NNNQbxq-C8eVoywisPX:-NNNQbxtEIRzxaxYmGW8:b-h32uns) ([raw file](https://github.com/harness/harness-core/blob/fc06ac2b6debc257cab9b2671a130f7329ede10d/delegate/src/main/java/io/harness/delegate/executor/serviceproviders/DelegateAccountIdProvider.java#L17)):*
> ```Java
>     @Override
>     public String getAccount() {
>         return null;
> ```

It's best that all these methods that are not implemented throw instead. e.g. `UnsupportedOperationException`

**Review by mdmilic — APPROVED** [review]
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42635)* status: Some of the checks are too old.

**Review by xingchi-jin — COMMENTED** [review]
I am going to split the PR into executor lib and k8s ng tasks - two PRs. 
deprecating this one. But comments are fixed in new PRs https://github.com/harness/harness-core/pull/43716 

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42635#-:-NNn9vQ1EPjl_-_pz7Z8:b-4mgypw)* status: Some of the checks are too old. 

___
*[`delegate/src/main/java/io/harness/delegate/executorlib/config/Configuration.java` line 18 at r2](https://reviewable.io/reviews/harness/harness-core/42635#-NLv3AyG8N-c0Er7UVqZ:-NNn9qHfC4huVGF0v2oK:b72qboa) ([raw file](https://github.com/harness/harness-core/blob/835ac06ae77bcd1a26c0a6099d072f85097a5a9e/delegate/src/main/java/io/harness/delegate/executorlib/config/Configuration.java#L18)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Make all final
</blockquote></details>

they don't have setter.
___
*[`delegate/src/main/java/io/harness/delegate/executorlib/config/ConfigurationProvider.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/42635#-NLv3ifN0e6e2x8TGH0w:-NNn8rSMBbavUlCWdvZG:b7k3tve) ([raw file](https://github.com/harness/harness-core/blob/835ac06ae77bcd1a26c0a6099d072f85097a5a9e/delegate/src/main/java/io/harness/delegate/executorlib/config/ConfigurationProvider.java#L22)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think we don't need this class for now (no need to read config from yaml if it's not standalone lib). Lets just have task agent construct and give the config to the executor
</blockquote></details>

Like dropwizard has some basic configurations. There are some basic configs executor lib need. and going forward I don't want some configurations come from ENV some from file, they should all come from config file. Some configurations are like where to read the file (we don't want to hard code it), core endpoints , max cpu threads to enforce (not implemented), delegate-token (currently not used but required by the core http client)

**Pull request closed without merging**
