### PR TITLE
[feat]: [PL-29696]: update logic of Token flow to redirect to NG for APIKey or JWT token case. Add caching to avoid network and db calls

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)

### CODE REVIEW

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/41287#-NIloTRy8XaOuuRqBc6y:-NIloTRy8XaOuuRqBc6z:blrr42l) ([raw file](https://github.com/harness/harness-core/blob/d40dfb9d32fc4f86c08942ee2b52b2c98b9910a8/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L272)):*
> ```Java
>   validateToken(@Parameter(description = ACCOUNT_PARAM_MESSAGE) @NotNull @QueryParam(
>                     ACCOUNT_KEY) @AccountIdentifier String accountIdentifier,
>       @QueryParam("isScimCall") @DefaultValue("false") boolean isScimCall, @NotNull ApiKeyTokenRequest tokenRequest) {
> ```

Why this has changed signature? Token validation should not check for isSCIMCall and also it should only expect API Key String and not a complex object, Other services will break who are using this API

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 272 at r2](https://reviewable.io/reviews/harness/harness-core/41287#-NIloTRy8XaOuuRqBc6y:-NIpSx1OAm4OYo0ocEyt:b-7er3la) ([raw file](https://github.com/harness/harness-core/blob/d40dfb9d32fc4f86c08942ee2b52b2c98b9910a8/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L272)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this has changed signature? Token validation should not check for isSCIMCall and also it should only expect API Key String and not a complex object, Other services will break who are using this API
</blockquote></details>

Changed it back to string, after hndling the `"` separately. `isScimCall` is a optional query parameter with default value set, so would not break anything Piyush. Thanks

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/41287#-NIpoxeG-VtT-vPUtkp5:-NIpoxeH8AuwYQAziBd1:bcbkiuq) ([raw file](https://github.com/harness/harness-core/blob/90fdcced8748af2a7baf2d2e8cb1427dfcbae56b/120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java#L46)):*
> ```Java
>   TokenDTO getToken(String tokenId, boolean withEncodedPassword);
> 
>   TokenDTO validateToken(String accountIdentifier, String apiKey, boolean isScimCall);
> ```

Why should token service care about SCIM call? Its job is to only validate token passed to it

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/41287#-NIpoxeG-VtT-vPUtkp5:-NIpyacwCoNIk65lB5hT:b92o2pq) ([raw file](https://github.com/harness/harness-core/blob/90fdcced8748af2a7baf2d2e8cb1427dfcbae56b/120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java#L46)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why should token service care about SCIM call? Its job is to only validate token passed to it
</blockquote></details>

For our case, we want to have stricter scenario where we want to allow only SCIM calls to be made using JWT, so need a parameter to determine if this is a SCIM call or not, so this optional parameter is added. If we remove this check, we may start allowing external JWT tokens to call any Harness NG API. Thanks

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/41287#-NIpoxeG-VtT-vPUtkp5:-NIqh4JNECC3Ot4w7kl3:bd9oxzz) ([raw file](https://github.com/harness/harness-core/blob/90fdcced8748af2a7baf2d2e8cb1427dfcbae56b/120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java#L46)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

For our case, we want to have stricter scenario where we want to allow only SCIM calls to be made using JWT, so need a parameter to determine if this is a SCIM call or not, so this optional parameter is added. If we remove this check, we may start allowing external JWT tokens to call any Harness NG API. Thanks
</blockquote></details>

This call will come via our filter only, Its about validating token and not identifying type of API, Filter should detect what api is allowed with which token.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 339 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrJc1SA153UubgOh53:-NIrJc1T2SSNGa-uqmBU:bo6g7zn) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L339)):*
> ```Java
>   @Override
>   public TokenDTO validateToken(String accountIdentifier, String apiKey) {
>     final String[] splitToken = apiKey.split(apiKeyOrTokenDelimiterRegex);
> ```

Why splitting token here?

**Review by piyush-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, 1 of 15 files at r3, 1 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: 22 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 273 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrK3ImEVgMH9czY_3Z:-NIrK3ImEVgMH9czY_3_:b3rmp2j) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L273)):*
> ```Java
>         "API_KEY_NG_VALIDATE: Validate token for API key or JWT token called for account id: %s", accountIdentifier));
>     if (apiKey.startsWith("\"")
>         && apiKey.endsWith("\"")) { // retro-fit sends String wrapped in '"' so this check is needed
> ```

Is this really required also what if string is empty? There should be a better way to handle this.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java` line 272 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrN7uN5CmIC76gJEjO:-NIrN7uN5CmIC76gJEjP:b-ljcmoz) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java#L272)):*
> ```Java
>     }
> 
>     jwtTokenScimSettingCache.put(
> ```

We should put cache operations under try catch, Cache unavailability should not impact normal flow of operations.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 518 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIriQJR-ot15nJilkZV:-NIriQJR-ot15nJilkZW:b-wfhf03) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L518)):*
> ```Java
>       HarnessCacheManager harnessCacheManager, VersionInfoManager versionInfoManager) {
>     return harnessCacheManager.getCache(JWT_TOKEN_SERVICE_ACCOUNT_DATA_CACHE_KEY, String.class,
>         JwtTokenServiceAccountData.class, AccessedExpiryPolicy.factoryOf(new Duration(TimeUnit.DAYS, 5)),
> ```

Shouldn't this be a lower value specially until we implement cache invalidation via event sin NG Settings framework?

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 508 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIriicnE5ipSLICFA1b:-NIriicnE5ipSLICFA1c:b-375vsv) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L508)):*
> Shouldn't this be a lower value specially until we implement cache invalidation via event sin NG Settings framework?
Same

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java` line 272 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrN7uN5CmIC76gJEjO:-NIrlJUrC4E7IoNAgInK:b32v57) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java#L272)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

We should put cache operations under try catch, Cache unavailability should not impact normal flow of operations. 
</blockquote></details>

+1

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 508 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIriicnE5ipSLICFA1b:-NIrmPsL4EgZo2CscWBD:b-yy99v7) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L508)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

> Shouldn't this be a lower value specially until we implement cache invalidation via event sin NG Settings framework?
Same
</blockquote></details>

We have logic written to invalidate this cache when the 'publicKeyUrl' in setting changes. Only for settings we can't use this logic, so have to rely on `2 minutes` time. Once we have the events framework in place there also we will increase the time. Thanks



_Code quote (from 120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java):_
```Java
jwtTokenScimSettingCache.put(
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 518 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIriQJR-ot15nJilkZV:-NIry8dl6TLzh8R-y3Od:b-ucp04j) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L518)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Shouldn't this be a lower value specially until we implement cache invalidation via event sin NG Settings framework?
</blockquote></details>

same as above, we also invalidate as soon as get settings has new ServiceAccountId in it.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 339 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrJc1SA153UubgOh53:-NIryLYa60qVCHjWAO6T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L339)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why splitting token here?
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java` line 272 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrN7uN5CmIC76gJEjO:-NIryNt98Ce7-t5vGDkq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/utils/JWTTokenFlowAuthFilterUtils.java#L272)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 273 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrK3ImEVgMH9czY_3Z:-NIryPKr6HVlrdQ-H8lw:b-kwrlxi) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L273)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Is this really required also what if string is empty? There should be a better way to handle this.
</blockquote></details>

Yes, it is required, https://stackoverflow.com/questions/33205855/retrofit-2-0-beta-2-is-adding-literal-quotes-to-multipart-values. 
Also this piece of code is otherwise harmless, if the string doesn't begin/end with `"` both and empty string also doesn't break. Thanks

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java` line 46 at r4](https://reviewable.io/reviews/harness/harness-core/41287#-NIpoxeG-VtT-vPUtkp5:-NIryrqy8JLGXsXqoA8X:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/90fdcced8748af2a7baf2d2e8cb1427dfcbae56b/120-ng-manager/src/main/java/io/harness/ng/core/api/TokenService.java#L46)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

This call will come via our filter only, Its about validating token and not identifying type of API, Filter should detect what api is allowed with which token.
</blockquote></details>

Done.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 6 of 15 files at r3, 1 of 2 files at r4, 6 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: 18 file(s) to review. 1 change requests. 6. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java` line 339 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrJc1SA153UubgOh53:-NIuHkeRDnisEZeRXcqv:b32w1t) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L339)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok

**Review by shashank-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: 18 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Comment by piyush-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java` line 273 at r5](https://reviewable.io/reviews/harness/harness-core/41287#-NIrK3ImEVgMH9czY_3Z:-NJ-6DnhDQllGZOT8NTG:bryqow4) ([raw file](https://github.com/harness/harness-core/blob/d7063d5510899395fb8c9d2bf0127d873bb16fa2/120-ng-manager/src/main/java/io/harness/ng/core/remote/TokenResource.java#L273)):*
> https://stackoverflow.com/questions/33205855/retrofit-2-0-beta-2-is-adding-literal-quotes-to-multipart-values
The solution provided are elegant but our implementation looks hackish, Why not do something like below:
  

//In NextGenAuthenticationFilter
        tokenDTO = NGRestUtils.getResponse(tokenClient.validateApiKey(accountIdentifier, RequestBody.create(MediaType.get("text/plain"),apiKeyOptional.get())));
    
//In TokenClient
@Headers({"Content-Type: text/plain; charset=utf-8", "accept-language: en-US"})
  @POST("token/validate")
  Call<ResponseDTO<TokenDTO>> validateApiKey(
      @Query(value = "accountIdentifier") String accountIdentifier, @Body RequestBody apiKey);

Can you verify if this works.

**Comment by piyush-harness** [comment]
*[`965-api-key-filter/BUILD.bazel` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/41287#-NJ-EQzG9UId1sy3bjXG:-NJ-EQzG9UId1sy3bjXH:b-ifhks0) ([raw file](https://github.com/harness/harness-core/blob/31e5a0aafb45b91305e91f879aa17a8cd554d9cb/965-api-key-filter/BUILD.bazel#L26)):*
> ```Starlark
> 
> java_library(
>     name = "tests",
> ```

Why this is removed?

**Comment by pbarapatre10** [comment]
*[`965-api-key-filter/BUILD.bazel` line 26 at r9](https://reviewable.io/reviews/harness/harness-core/41287#-NJ-EQzG9UId1sy3bjXG:-NJ-FlS20inqFlsIxJRF:blkz764) ([raw file](https://github.com/harness/harness-core/blob/31e5a0aafb45b91305e91f879aa17a8cd554d9cb/965-api-key-filter/BUILD.bazel#L26)):*
<details><summary><i>Previously, piyush-harness (Piyush Patel) wrote…</i></summary><blockquote>

Why this is removed?
</blockquote></details>

There are no more tests in this module, moved the tests to the ng-manager module, so removed it.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 3 of 16 files at r1, 6 of 15 files at r3, 2 of 7 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 6 of 16 files at r1, 6 of 15 files at r3, 2 of 7 files at r5, 3 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: :shipit: complete! ✓

**Review by shashank-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41287)* status: :shipit: complete! ✓

**Pull request merged**
