### PR TITLE
[feat]:[PL-29002]: adding additional-metadata in secret text spec

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
adding additional-metadata in secret text spec
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)

### CODE REVIEW

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEug4QX3fR1b6IPZo72:-NEug4QX3fR1b6IPZo73:b-ze8898) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L122)):*
> ```Java
>   private static final String READ_ONLY_SECRET_MANAGER_ERROR =
>       "Cannot create an Inline secret in read only secret manager";
>   private static final String REGIONS = "regions";
> ```

Should be in some common constant class?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufRkd3nFwMMLfDRIM:-NEufRkd3nFwMMLfDRIN:bh0mc69) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L196)):*
> ```Java
> 
>   @VisibleForTesting
>   void validateAdditionalMetadataInSecretTextSpecDTOForGcpSecretManager(SecretTextSpecDTO secretTextSpecDTO) {
> ```

private?
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufX4CB_Tw0oVqAjhu:-NEufX4CB_Tw0oVqAjhv:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L197)):*
> ```Java
>   @VisibleForTesting
>   void validateAdditionalMetadataInSecretTextSpecDTOForGcpSecretManager(SecretTextSpecDTO secretTextSpecDTO) {
>     // Inline secret text
> ```

remove comment
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufYTD-EsaUzV5KRk8:-NEufYTD-EsaUzV5KRk9:b-u9p8mw) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L201)):*
> ```Java
>       validateInlineSecretAdditionalMetadataForGcpSecretManager(secretTextSpecDTO);
>     }
>     // Reference secret text
> ```

remove comment
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufw7MEvZNrmS7TsZ2:-NEufw7MEvZNrmS7TsZ3:bnli3vn) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L213)):*
> ```Java
>     }
>     Map<String, Object> values = secretTextSpecDTO.getAdditionalMetadata().getValues();
>     if (values.size() != 1 || !values.containsKey("version")) {
> ```

Use constant for version
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufmBg5ZiW-78J7hfy:-NEufmBg5ZiW-78J7hfz:bc9vhb7) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L215)):*
> ```Java
>     if (values.size() != 1 || !values.containsKey("version")) {
>       throw new InvalidRequestException("Additional metadata values field should have only one field - version");
>     }
> ```

add validation for the value of version as well
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEugjLv044Oa4roVNgW:-NEugjLw26doW8OtsDAt:bzeak2w) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L226)):*
> ```Java
>             String.format("Additional metadata values expect only one key - %s", REGIONS));
>       }
>       if (values.get(REGIONS) == null || isEmpty(String.valueOf(values.get(REGIONS)))) {
> ```

isEmpty should be doing null check as well. Verify and remove explicit null check in if condition here.

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEug4QX3fR1b6IPZo72:-NEurL_FC8KCDJfOgZE0:bdqb6ez) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L122)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should be in some common constant class?
</blockquote></details>

Moved to connector constants. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufRkd3nFwMMLfDRIM:-NEurORPCSSXK0IGYlNl:byh1555) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L196)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Can't be marked private since its being used in test file. 
Marked it as visible for testing for the same reason. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 197 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufX4CB_Tw0oVqAjhu:-NEusA942LkfSpHeI___:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L197)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 201 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufYTD-EsaUzV5KRk8:-NEusAYv1Ey2zE5e6wwn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L201)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 213 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufw7MEvZNrmS7TsZ2:-NEusBtfCG-gWDlB8vqn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L213)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Use constant for version
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 215 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufmBg5ZiW-78J7hfy:-NEusDTg5l_RaWKHzwDm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L215)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

add validation for the value of version as well
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 226 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEugjLv044Oa4roVNgW:-NEusEmLBQ1vMiH2382g:bl38y1i) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L226)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

isEmpty should be doing null check as well. Verify and remove explicit null check in if condition here.
</blockquote></details>

Values map is map from String -> Object. 
So, isEmpty does not exist for object. 
If we convert null to String -> gives "null" string. Hence I had to split it in 2 parts here.

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: Some of the checks are too old. 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java` line 196 at r1](https://reviewable.io/reviews/harness/harness-core/39114#-NEufRkd3nFwMMLfDRIM:-NFHiEXf9-4YSw-emUmS:bfwo0xt) ([raw file](https://github.com/harness/harness-core/blob/7ada02f6a81ab1a959b8168ac9c3925bb27299c7/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/NGEncryptedDataServiceImpl.java#L196)):*
<details><summary><i>Previously, shreyas-harness (Shreyas Singh) wrote…</i></summary><blockquote>

Can't be marked private since its being used in test file. 
Marked it as visible for testing for the same reason. 
</blockquote></details>

Not marking a method just for testing isn't the right design approach. You should test the calling method with correct values so to test the behaviour of this method. Please consider updating this as part of different PR.
___
*[`970-ng-commons/src/main/java/io/harness/ConnectorConstants.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/39114#-NFHjheLC3Nskj9KRcJ5:-NFHjheLC3Nskj9KRcJ6:brkm1fs) ([raw file](https://github.com/harness/harness-core/blob/3a7389f6b380abf4bdb5daed6a937986061270bb/970-ng-commons/src/main/java/io/harness/ConnectorConstants.java#L63)):*
> ```Java
>   public static final String REGIONS = "regions";
>   public static final String VERSION = "version";
>   public static final String LATEST = "latest";
> ```

These are part of secret and not connector. Should go to SecretConstants

**Review by shreyas-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: 8 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/ConnectorConstants.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/39114#-NFHjheLC3Nskj9KRcJ5:-NFHnqPP08CBn5KJbLtk:bs7wumx) ([raw file](https://github.com/harness/harness-core/blob/3a7389f6b380abf4bdb5daed6a937986061270bb/970-ng-commons/src/main/java/io/harness/ConnectorConstants.java#L63)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

These are part of secret and not connector. Should go to SecretConstants
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 4 of 4 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39114)* status: :shipit: complete! ✓

**Pull request merged**
