### PR TITLE
feat: [PL-22256]: Open API changes for full sync Apis

### PR DESCRIPTION
**Pull request by bhavya181**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)

### CODE REVIEW

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: 7 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: 8 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 129 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdXp3S5wqYS-AUn7cj:-MxADHfN7cSqd6bg6wkr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L129)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should we just say : Returns the saved configuration details for the Git full sync
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 149 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdY-qd7FUcFqbIDx2h:-MxADIH91w67eJ6HYepN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L149)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Updates full sync configuration for the provided scope?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 153 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYh5e4fpyNcyEFv7n:-MxADIs-50OKCmZ3xxQA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L153)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Returns the updated full sync configuration for the provided scope
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 176 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYW0PDQ3mZL0AmlDv:-MxADK4G1L0qj3YAkoDj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L176)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Returns full sync configuration for the provided scope
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 198 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdZ4DQ5rtRVqzZgbx7:-MxADLWS5JrwhzoouuHD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L198)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Its not clear what this API does from this description.

Does it return only unsynced/failed entities or all entities?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 210 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYsCl23MWP3SMNlE9:-MxADMQIELq_0PLeq8iz:bnn7ngf) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L210)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This doesn't seem right. This must have some common description used in other APIs. We can use that
</blockquote></details>

No, there is no common description for this.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 25 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdZY_iBJJQHN9x3NKY:-MxADRMY6IKRe14642J1:b-h3cgcd) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L25)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Name of the branch to which Entities was pushed and from which pull request was created

Why is this in past tense?
</blockquote></details>

It's a response dto, that's why all fields have desc in past tense.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: 9 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 28 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdZesrCRDxKoWNjMDe:-MxJg5yPAhJUZFDUNaP6:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L28)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This also is in past tense. 

Determines if pull request should be created
</blockquote></details>

same as above
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 30 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-Mwd_7GX2KexRV5fDkU_:-MxJg7jw5JChElSxOCR6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L30)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Determines if the provided branch is a new branch
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-Mwd_DTqEPGzQXPRAnGC:-MxJg90bB6a9aw7SZlhw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This doesn't seem right.

Name of the target branch of the pull request
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java, line 32 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-Mwd_UvSBXzud6QSK0be:-MxJg9XsDZ_CvDD9pQIH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigDTO.java#L32)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Path of the root folder inside which entities are pushed
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigRequestDTO.java, line 23 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdaFy_5gJaa1w9GQhP:-MxJgALt2bUVfujq-f4a:b-tytxnx) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncConfigRequestDTO.java#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

These descriptions are much better than GitFullSyncConfigDTO. Can we reuse them there?
</blockquote></details>

GitFullSyncConfigDTO is request DTO and its a response dto, that's why al desc are in past tense

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: 9 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncEntityInfoFilterDTO.java, line 41 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-Mwd_kqp4ELjTsYhfNnH:-MxJhaCeB0Lm5ZFPb_vJ:b-n3xbze) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/fullsync/dtos/GitFullSyncEntityInfoFilterDTO.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Maybe : Specifies the entities by their type to filter on.
</blockquote></details>

I have changed it a little bit. Please check it.

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: 9 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 153 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYh5e4fpyNcyEFv7n:-MxK3drg2H8hx_khVvF0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L153)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Returns the updated gitfull sync configuration for the provided scope
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 176 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYW0PDQ3mZL0AmlDv:-MxK3ey63WKlWnjxRd1D:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L176)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Returns the updated git full sync configuration for the provided scope
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java, line 210 at r1](https://reviewable.io/reviews/harness/harness-core/30952#-MwdYsCl23MWP3SMNlE9:-MxK3jpZ0pHDUcvq3tQM:b-bouj4c) ([raw file](https://github.com/harness/harness-core/blob/b541e8a8ff2b9c3bc6c4cf90642726471978f795/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitFullSyncResource.java#L210)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We need better description for this
</blockquote></details>

It this is better

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 2 of 7 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952#-:-MxKExvXCaofQAzRIkCh:bnfp4nl)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 7 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30952)* status: :shipit: complete! ✓

**Pull request merged**
