### PR TITLE
techdebt: [CDS-39619]: Service Override and Infrastructure Def audit trail support

### PR DESCRIPTION
**Pull request by namantalaycha10**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36130)

### CODE REVIEW

**Comment by namantalaycha10** [comment]
changes are in progress

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36130)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/36130#-N8x3ZrM4Z1LKPErV_38:-N8x3ZrM4Z1LKPErV_39:bcqn8w0) ([raw file](https://github.com/harness/harness-core/blob/c9850577f651287a4e74d8613fdf3473aa370064/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L11)):*
> ```Java
> 
> import static io.harness.AuthorizationServiceHeader.NG_MANAGER;
> import static io.harness.audit.ResourceTypeConstants.*;
> ```

we should not use wild cards in imports

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90v-6n2bsuFpq-Z3PT:-N90v-6n2bsuFpq-Z3PU:b-pkrp5t) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L60)):*
> ```Java
>     if (globalContext.get(PRINCIPAL_CONTEXT) == null) {
>       principal = new ServicePrincipal(NG_MANAGER.getServiceId());
>     } else if (globalContext.get(PRINCIPAL_CONTEXT) != null) {
> ```

we do not need Else-If here. Else is sufficient
Also, there are duplicate Else-Ifs here

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90uvli5U6SAdhpxg1W:-N90uvlj4uVQzkwwq4nj:b-nsx9ja) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L49)):*
> ```Java
>     AuditEntry auditEntry = AuditEntry.builder()
>                                 .action(Action.CREATE)
>                                 .module(ModuleType.CORE)
> ```

Module should be CD for Infrastructure

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90umE1AAAbM6VZzNDb:-N90umE1AAAbM6VZzNDc:bue593q) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L47)):*
> ```Java
>         objectMapper.readValue(outboxEvent.getEventData(), InfrastructureCreateEvent.class);
>     final InfrastructureEntity infrastructure = infrastructureCreateEvent.getInfrastructureEntity();
>     AuditEntry auditEntry = AuditEntry.builder()
> ```

we should make fields final wherever possible

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 40 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90uaVd7YQcREy7yfdO:-N90uaVd7YQcREy7yfdP:b-erf0tm) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L40)):*
> ```Java
>     this.auditClientService = auditClientService;
>     this.objectMapper = NG_DEFAULT_OBJECT_MAPPER;
>   }
> ```

for better readability, its better to have the public method just below the constructor and all private methods below the public methods

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90xE8G4KfngWXTvJUC:-N90xE8G4KfngWXTvJUD:bidpewm) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L133)):*
> ```Java
>     if (globalContext.get(PRINCIPAL_CONTEXT) == null) {
>       principal = new ServicePrincipal(NG_MANAGER.getServiceId());
>     } else if (globalContext.get(PRINCIPAL_CONTEXT) != null) {
> ```

else-if not needed

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 122 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vOqc8E7nkYbPffwW:-N90vOqc8E7nkYbPffwX:b-nsx9ja) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L122)):*
> ```Java
>     AuditEntry auditEntry = AuditEntry.builder()
>                                 .action(Action.DELETE)
>                                 .module(ModuleType.CORE)
> ```

Module should be CD for Infrastructure

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vMlk5NrzdO6ZOfZF:-N90vMlk5NrzdO6ZOfZG:b-nsx9ja) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L98)):*
> ```Java
>     AuditEntry auditEntry = AuditEntry.builder()
>                                 .action(Action.UPDATE)
>                                 .module(ModuleType.CORE)
> ```

Module should be CD for Infrastructure

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vLyeARI7eKjjFaST:-N90vLyeARI7eKjjFaSU:b-nsx9ja) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L74)):*
> ```Java
>     AuditEntry auditEntry = AuditEntry.builder()
>                                 .action(Action.UPSERT)
>                                 .module(ModuleType.CORE)
> ```

Module should be CD for Infrastructure

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/InfrastructureCreateEvent.java` line 31 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90y2b_Ce6FhxExHqyK:-N90y2b_Ce6FhxExHqyL:bxdb7f1) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/InfrastructureCreateEvent.java#L31)):*
> ```Java
>   @JsonIgnore
>   @Override
>   public ResourceScope getResourceScope() {
> ```

We need to think more about this. Because infra is scoped to an environment within a project
maybe introduce a new scope ?

**Review by namantalaycha10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36130)* status: 16 file(s) to review. 7. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/36130#-N8x3ZrM4Z1LKPErV_38:-N9628Qw0jWml68WWdgP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c9850577f651287a4e74d8613fdf3473aa370064/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L11)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should not use wild cards in imports
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90uvli5U6SAdhpxg1W:-N962BDLBSZFV648eYAC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L49)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Module should be CD for Infrastructure
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90v-6n2bsuFpq-Z3PT:-N962Cqk02qWpCGQkEu1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L60)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need Else-If here. Else is sufficient
Also, there are duplicate Else-Ifs here
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 74 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vLyeARI7eKjjFaST:-N962Dlo-CODyuTI9gdb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L74)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Module should be CD for Infrastructure
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 98 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vMlk5NrzdO6ZOfZF:-N962EXh2BOOlhJCZUfL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L98)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Module should be CD for Infrastructure
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 122 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90vOqc8E7nkYbPffwW:-N962FEg8roNlFOvmhGF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L122)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Module should be CD for Infrastructure
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java` line 133 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90xE8G4KfngWXTvJUC:-N962FvnCV0kN6PlsB4J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/InfrastructureEventHandler.java#L133)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

else-if not needed
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/outbox/ServiceOverrideEventHandler.java` line 35 at r3](https://reviewable.io/reviews/harness/harness-core/36130#-N90xPj4BzrlAFzzRltf:-N90xPj4BzrlAFzzRltg:btsv3sd) ([raw file](https://github.com/harness/harness-core/blob/f683eb427c1687971a3be6b17f17817cb53636c5/120-ng-manager/src/main/java/io/harness/ng/core/outbox/ServiceOverrideEventHandler.java#L35)):*
> ```Java
> 
> @Slf4j
> @OwnedBy(HarnessTeam.CDP)
> ```

This is owned by CDC

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java` line 108 at r4](https://reviewable.io/reviews/harness/harness-core/36130#-N9AgUUr7-pk4IUm8Mzx:-N9AgUUr7-pk4IUm8Mzy:b-qwtqdt) ([raw file](https://github.com/harness/harness-core/blob/9d2bc335bea08eb1b7b1cc05ab925c243b15379a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services/impl/InfrastructureEntityServiceImpl.java#L108)):*
> ```Java
>                                .infrastructureEntity(infraEntity)
>                                .build());
>         return infrastructureEntity;
> ```

we should also do this in the BulkCreate method

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 13 files at r3, 11 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36130)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java` line 113 at r4](https://reviewable.io/reviews/harness/harness-core/36130#-N9Ag_1d6B2WkUmzWl1v:-N9Ag_1d6B2WkUmzWl1w:b-dbck1v) ([raw file](https://github.com/harness/harness-core/blob/9d2bc335bea08eb1b7b1cc05ab925c243b15379a/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java#L113)):*
> ```Java
>                              .environmentRef(requestServiceOverride.getEnvironmentRef())
>                              .serviceRef(requestServiceOverride.getServiceRef())
>                              .serviceOverride(requestServiceOverride)
> ```

Lets do the update event here so that we can show both old and new entities ( i.e the diff )

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36130)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.

**Pull request closed without merging**
