### PR TITLE
[feat]: [CDS-59342]: Adding expression script support for pipeline expression v2 json support

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes
Adding expression script support for pipeline expression v2 JSON support

Testing: Added unit test to confirm if the script support in normal flow is working for all flows

The change is backward compatible as Unit test is working now.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java` line 537 at r2](https://reviewable.io/reviews/harness/harness-core/47888#-NVc0twc9Ssw75hcGxWZ:-NVc0twc9Ssw75hcGxW_:b3lc4nd) ([raw file](https://github.com/harness/harness-core/blob/ee783d8431ff87ff35480b20d4022dcb23a9f5cf/980-commons/src/main/java/io/harness/expression/EngineExpressionEvaluator.java#L537)):*
> ```Java
> 
>   protected Object evaluateByCreatingExpression(@NotNull String expression, @NotNull EngineJexlContext ctx) {
>     if (ctx.isFeatureFlagEnabled("PIE_EXECUTION_JSON_SUPPORT")) {
> ```

nit: can we add this as a constant?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/47888#-NVc1B7Q-ckcXDveQ1sM:-NVc1B7R4ggEc9LiTZUm:b45htuj) ([raw file](https://github.com/harness/harness-core/blob/ee783d8431ff87ff35480b20d4022dcb23a9f5cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L152)):*
> ```Java
>             AmbianceUtils.getAccountId(ambiance), FeatureName.CI_DISABLE_RESOURCE_OPTIMIZATION)) {
>       // Passing the FeatureFlag.
>       List<String> enabledFeatureFlags = new LinkedList<>();
> ```

@archit-harness , could you please add a todo here. I think we should revisit this and create a cleaner way of passing FF in engine.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 4 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/47888#-NVc1B7Q-ckcXDveQ1sM:-NVc4Ws2-23HR8yw6fet:b-ozjbjd) ([raw file](https://github.com/harness/harness-core/blob/ee783d8431ff87ff35480b20d4022dcb23a9f5cf/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L152)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

@archit-harness , could you please add a todo here. I think we should revisit this and create a cleaner way of passing FF in engine. 
</blockquote></details>

Added todo to remove ff support from engine, as we should keep ff for long in engine

**Review by hextechpal — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by archit-harness** [comment]
trigger uts

**Comment by archit-harness** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 1 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by shalini-agr — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 1. unresolved discussions.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47888)* status: 1. unresolved discussions.

**Comment by archit-harness** [comment]
trigger review

**Pull request merged**
