### PR TITLE
feat: [CDS-79206]: remove dynamic schema code for pipeline service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Remove the code for dynamic schema from the pipeline service. The old API for dynamic schema has been marked deprecated and it will also return the static schema. Will be removed in the next release. The API for individual schema (dynamic schema) has also been removed. 

**Testing:** In Prod, there are no calls for old dynamic individual schema API. In Preqa and qa, there are some calls, but they are all for internal testing from UI and that code is also being removed now.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53281)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53281)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/53281#-NfK4dQt4MUnnQNdLDZn:-NfK4dQt4MUnnQNdLDZo:b3bmsg2) ([raw file](https://github.com/harness/harness-core/blob/46e336775c59d9d31f98900d6e90e8afb5ab712e/pipeline-service/contracts/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java#L63)):*
> ```Java
>   @Path("/invalidate-cache")
>   @ApiOperation(value = "Invalidate yaml schema cache", nickname = "invalidateYamlSchemaCache")
>   ResponseDTO<Boolean> invalidateYamlSchemaCache();
> ```

i dont this api is also used anymore? plus i don't think this impacts static schema

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53281)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java` line 63 at r3](https://reviewable.io/reviews/harness/harness-core/53281#-NfK4dQt4MUnnQNdLDZn:-NfKEouBDGkP9OnBdZIb:bxcqajg) ([raw file](https://github.com/harness/harness-core/blob/46e336775c59d9d31f98900d6e90e8afb5ab712e/pipeline-service/contracts/src/main/java/io/harness/pms/schema/PmsYamlSchemaResource.java#L63)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i dont this api is also used anymore? plus i don't think this impacts static schema
</blockquote></details>

yes, this is not used anymore, will remove in the next PR

**Comment by shalini-agr** [comment]
trigger ut0, ut1, ut2, ut3, ut4

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53281)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by shalini-agr** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
