### PR TITLE
feat: [CDS-49234]: Invert CDS_SERVICE_ENV_SCHEMA_VALIDATION ff and enable it by default in all env

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Invert CDS_SERVICE_ENV_SCHEMA_VALIDATION ff and enable it by default in all env
Updated FF -> DISABLE_CDS_SERVICE_ENV_SCHEMA_VALIDATION 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42154)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 539 at r1](https://reviewable.io/reviews/harness/harness-core/42154#-NKr9uA4DGGhTmY62lR7:-NKr9uA54UMYIcg-4urV:b-9tl6m1) ([raw file](https://github.com/harness/harness-core/blob/e578f6b71e27d7d05eff905eafb156b965b1639b/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L539)):*
> ```Java
>   CDC_SEND_NOTIFICATION_FOR_FREEZE("Send notifications for deployment freeze", HarnessTeam.CDC),
>   DISABLE_CDS_SERVICE_ENV_SCHEMA_VALIDATION(
>       "Added support for Service Env schema validation for new service env redesign", HarnessTeam.CDC),
> ```

lets change the description also

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42154)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 539 at r1](https://reviewable.io/reviews/harness/harness-core/42154#-NKr9uA4DGGhTmY62lR7:-NKvHGsGEk9Xv8b-4h0Z:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e578f6b71e27d7d05eff905eafb156b965b1639b/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L539)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets change the description also
</blockquote></details>

Done.

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Review by vivekkarnatiharness — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42154)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42154)* status: :shipit: complete! ✓

**Pull request merged**
