### PR TITLE
[feat]: [PIE-3803]: Creating APIs for NG ExecutionTimeInput and creat…

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…ing POJO

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 371 at r1](https://reviewable.io/reviews/harness/harness-core/33386#-N2jobn8EEkmgXR3WqVE:-N2jobn8EEkmgXR3WqVF:bz498hc) ([raw file](https://github.com/harness/harness-core/blob/a836564ae6a66bd02a7013316612dc3042e7bb01/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L371)):*
> ```Java
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_EXECUTE)
>   @Operation(operationId = "submitExecutionInput",
>       summary = "Submit the Execution Input for a Stage/Step and continue execution",
> ```

can we move all execution inputs api to new resource?



_Code quote:_
```Java
  @GET
  @Path("/input/{inputInstanceId}")
  @ApiOperation(value = "Get the Execution input template for any step", nickname = "getExecutionInputTemplate")
  @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_EXECUTE)
  @Operation(operationId = "getExecutionInputTemplate", summary = "Get the Execution Input Template for any stage/step",
      responses =
      {
        @io.swagger.v3.oas.annotations.responses.
        ApiResponse(responseCode = "default", description = "Return the Execution Input Template for any Stage/Step")
      })
  @Hidden
  public ResponseDTO<String>
  getExecutionInputTemplate(
      @NotNull @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) @Parameter(
          description = PipelineResourceConstants.ACCOUNT_PARAM_MESSAGE) @AccountIdentifier String accountId,
      @NotNull @QueryParam(NGCommonEntityConstants.ORG_KEY) @Parameter(
          description = PipelineResourceConstants.ORG_PARAM_MESSAGE) @OrgIdentifier String orgIdentifier,
      @NotNull @QueryParam(NGCommonEntityConstants.PROJECT_KEY) @Parameter(
          description = PipelineResourceConstants.PROJECT_PARAM_MESSAGE) @ProjectIdentifier String projectIdentifier,
      @NotNull @PathParam(NGCommonEntityConstants.INPUT_INSTANCE_ID) @Parameter(
          description = PipelineResourceConstants.INPUT_INSTANCE_PARAM) @ProjectIdentifier String inputInstanceId) {
    ExecutionInputInstance executionInputInstance = ExecutionInputInstance.builder().build();
    return ResponseDTO.newResponse(executionInputInstance.getTemplate());
  }

  @POST
  @Path("/input/{inputInstanceId}")
  @ApiOperation(value = "Submit the Execution Input for a Stage/Step and continue Pipeline execution",
      nickname = "submitExecutionInput")
  @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_EXECUTE)
  @Operation(operationId = "submitExecutionInput",
      summary = "Submit the Execution Input for a Stage/Step and continue execution",
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/33386#-N2jo_e5AQu65H7JQbx8:-N2jo_e5AQu65H7JQbx9:b6vydjn) ([raw file](https://github.com/harness/harness-core/blob/a836564ae6a66bd02a7013316612dc3042e7bb01/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L410)):*
> ```Java
>   @Hidden
>   public ResponseDTO<VariableMergeServiceResponse>
>   createVariablesForPipelineExecution(
> ```

why this api will be reqired?



_Code quote:_
```Java
createVariablesForPipelineExecution(
```

**Comment by brijeshdhakar** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 410 at r1](https://reviewable.io/reviews/harness/harness-core/33386#-N2jo_e5AQu65H7JQbx8:-N2jtpsa9gaAxcVWhH5U:bkgfrlh) ([raw file](https://github.com/harness/harness-core/blob/a836564ae6a66bd02a7013316612dc3042e7bb01/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L410)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this api will be reqired?
</blockquote></details>

UI does not have yaml or list of available variables at pipeline execution time. 
So when the user gives execution time input, they should see the available variables that they can use as the input values.

**Comment by brijeshdhakar** [comment]
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java` line 371 at r1](https://reviewable.io/reviews/harness/harness-core/33386#-N2jobn8EEkmgXR3WqVE:-N2jyK3z97std1ulX5ck:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a836564ae6a66bd02a7013316612dc3042e7bb01/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java#L371)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we move all execution inputs api to new resource?
</blockquote></details>

Done.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vaibhav-si — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k5cfX19fMTtsDB1vm:-N2k5cfX19fMTtsDB1vn:b-flr1n8) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L61)):*
> ```Java
> import lombok.extern.slf4j.Slf4j;
> 
> @Tag(name = "Execution-input", description = "This contains APIs for execution input of a pipeline execution.")
> ```

Comment Tag till this resource is not ready for the user.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k9mPrBVeSiW2o_j-s:-N2k9mPrBVeSiW2o_j-t:bc7fdw6) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L93)):*
> ```Java
> 
>   @GET
>   @Path("/{inputInstanceId}")
> ```

what's inputInstanceId? How does the user figure this out?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k9LYrBhWhxCK6Un_K:-N2k9LYrBhWhxCK6Un_L:b-i3kwgw) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L96)):*
> ```Java
>   @ApiOperation(value = "Get the Execution input template for any step", nickname = "getExecutionInputTemplate")
>   @NGAccessControlCheck(resourceType = "PIPELINE", permission = PipelineRbacPermissions.PIPELINE_EXECUTE)
>   @Operation(operationId = "getExecutionInputTemplate", summary = "Get the Execution Input Template for any stage/step",
> ```

Do you think it makes sense to explain what is Execution Input Template (to a new user)?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k8Raj15JjnYaU1kWr:-N2k8Raj15JjnYaU1kWs:b-2fmjov) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L103)):*
> ```Java
>       })
>   @Hidden
>   public ResponseDTO<String>
> ```

Returning String makes it non-extensible for the future. I would suggest returning a DTO with a String field to keep it extensible in the future.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 141 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kA1NnAhOg3hCH6y3W:-N2kA1No2_SGFg75aA5V:b-4snp5g) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L141)):*
> ```Java
>           description = PipelineResourceConstants.INPUT_INSTANCE_PARAM) @ProjectIdentifier String inputInstanceId,
>       @RequestBody(required = true,
>           description = "Execution Input for the provided inputInstanceId") @NotNull String runtimeInputYaml) {
> ```

nit, can we call this executionInputYaml?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 159 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kAnS72q-ORSM16Fst:-N2kAnS72q-ORSM16Fsu:b-uvila5) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L159)):*
> ```Java
>       })
>   @ApiOperation(
>       value = "Create variables for Pipeline at execution time", nickname = "createVariablesForPipelineExecution")
> ```

nit, can we call this `listVariablesDuringExecution`?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kAz9S-JzT-Rogrgiy:-N2kAz9S-JzT-Rogrgiz:b5s4qud) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java#L22)):*
> ```Java
> @Schema(name = "ExecutionInputStatus",
>     description = "Contains the Input Instance ID and the status If the Execution Input is valid")
> public class ExecutionInputStatusDTO {
> ```

all the fields would also need to have descriptions. Use Schema annotation.
___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kBWWv3CErGqYY3EIP:-N2kBWWw6rfjZCw8iL1Z:b4ov0bh) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/954-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L20)):*
> ```Java
>   String GENERATE_FULL_GRAPH_PARAM_MESSAGE = "Generate full graph";
>   String INPUT_INSTANCE_PARAM = "Input Instance Identifier for Execution Input";
>   String PLAN_EXECUTION_ID_PARAM = "PlanExecutionId";
> ```

PlanExecutionId is not a desciption. Use PLAN_EXECUTION_ID_PARAM_MESSAGE in PlanExecutionResourceConstants

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 6 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 61 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k5cfX19fMTtsDB1vm:-N2kLSg760nBcqW2UzcK:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L61)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Comment Tag till this resource is not ready for the user.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 93 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k9mPrBVeSiW2o_j-s:-N2kGJGU-6ARzKUHSvBP:bi5mmgr) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L93)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

what's inputInstanceId? How does the user figure this out?
</blockquote></details>

It will be hard to find InputInstanceId so we are using nodeExecutionId now.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k9LYrBhWhxCK6Un_K:-N2kHsOtEUSUAYb_yNEL:b-9bmw7p) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L96)):*
> listVariablesDuringExecution
updated the description.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java` line 103 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2k8Raj15JjnYaU1kWr:-N2kLUUR477tFrVYJJJc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionInputResource.java#L103)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

Returning String makes it non-extensible for the future. I would suggest returning a DTO with a String field to keep it extensible in the future.
</blockquote></details>

Done.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kAz9S-JzT-Rogrgiy:-N2kL_W85_YYezaOHlRm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java#L22)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

all the fields would also need to have descriptions. Use Schema annotation.
</blockquote></details>

Done.
___
*[`954-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java` line 20 at r3](https://reviewable.io/reviews/harness/harness-core/33386#-N2kBWWv3CErGqYY3EIP:-N2kLdJU2_tGV7fwSUPn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/548a6c588288b2adee4ad5bce653db1a6cbbe3ae/954-pms-contracts/src/main/java/io/harness/pms/pipeline/PipelineResourceConstants.java#L20)):*
<details><summary><i>Previously, vaibhav-si (Vaibhav Singhal) wrote…</i></summary><blockquote>

PlanExecutionId is not a desciption. Use PLAN_EXECUTION_ID_PARAM_MESSAGE in PlanExecutionResourceConstants
</blockquote></details>

Done.

**Review by vaibhav-si — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java` line 27 at r4](https://reviewable.io/reviews/harness/harness-core/33386#-N2kMlV_Awk1IOPvUaFE:-N2kMlV_Awk1IOPvUaFF:bfo8foz) ([raw file](https://github.com/harness/harness-core/blob/ff5397d07f55f1196a5039dc08884cbab96ae771/800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionInputStatusDTO.java#L27)):*
> ```Java
>   @Schema(name = "nodeExecutionId", description = PlanExecutionResourceConstants.NODE_EXECUTION_ID_PARAM_MESSAGE)
>   String nodeExecutionId;
>   @Schema(name = "status", description = "Status if Execution Input is valid or not") ExecutionInputStatus status;
> ```

nit, name not needed unless diff. from field name

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 3 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 2 file(s) to review.

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33386)* status: 1 file(s) to review.

**Pull request merged**
