### PR TITLE
feat: [PL-28967]: addded maxTime in Aggregation queries

### PR DESCRIPTION
**Pull request by bhavya181**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFfXVYCDgVJZS1DIfi:-NEFfXVYCDgVJZS1DIfj:bj5bvak) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L481)):*
> ```Java
>     onUpdate(query, updateOperations, currentTimeMillis());
>     AdvancedDatastore datastore = getDatastore(query.getEntityClass());
>     setMaxTimeInOptions(datastore, findAndModifyOptions);
> ```

We can skip in this method
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFfaZq1lWT60iLPG4n:-NEFfaZq1lWT60iLPG4o:b-ke9le6) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L489)):*
> ```Java
>       Query<T> query, UpdateOperations<T> updateOperations, FindAndModifyOptions findAndModifyOptions) {
>     AdvancedDatastore datastore = getDatastore(query.getEntityClass());
>     setMaxTimeInOptions(datastore, findAndModifyOptions);
> ```

Would timeout exception get logged as expected
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 440 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEF_3DU2LTt81Usn9cE:-NEF_3DU2LTt81Usn9cF:bijju35) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L440)):*
> ```Java
>   }
> 
>   default int getMaxOperationTimeInMillis(Class cls) {
> ```

1. Class<T> cls
2. getMaxTimeMs
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFZvlK5ZPG4d3320AR:-NEFZvlK5ZPG4d3320AS:b-batmy7) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L449)):*
> ```Java
>   }
> 
>   default AggregationOptions getMaxTimeAggregationOptions(Class cls) {
> ```

No need of this method. AggregationOptions should be constructed at the place of use

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)* status: 17 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFfXVYCDgVJZS1DIfi:-NEGQXeY5MmbSPGkUq6a:b-4oshhp) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L481)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

We can skip in this method
</blockquote></details>

most of the svcs are calling this method only, why do we. want to skip it?
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 489 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFfaZq1lWT60iLPG4n:-NEGQfb4Ay5Y1WERDLUr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L489)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Would timeout exception get logged as expected
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 440 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEF_3DU2LTt81Usn9cE:-NEGQhaV3QrhHcRAbC0m:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L440)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

1. Class<T> cls
2. getMaxTimeMs
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/HPersistence.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFZvlK5ZPG4d3320AR:-NEGQiYy67i5bst1R027:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/persistence/HPersistence.java#L449)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

No need of this method. AggregationOptions should be constructed at the place of use
</blockquote></details>

Done.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)* status: 17 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 481 at r1](https://reviewable.io/reviews/harness/harness-core/38765#-NEFfXVYCDgVJZS1DIfi:-NEGU2jc9sMUUncb9WHu:brn1ljj) ([raw file](https://github.com/harness/harness-core/blob/02f400cd11a70a0c75e3ad874d314a70bf9ad221/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L481)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

most of the svcs are calling this method only, why do we. want to skip it?
</blockquote></details>

Sorry I meant update one.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765#-:-NEGUD7eBUcFSfaWgfRH:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765#-:-NEGUJCEAm7fjzuQqb9w:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 14 of 16 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38765)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
