### PR TITLE
feat: [CDS-33894]: Add support for Exec step and Command Task

### PR DESCRIPTION
**Pull request by acasian-harness**
## Describe your changes

1. Added new CommandStep for ssh, winrm service definition type
2. Added new CommandTaskNG for ssh, winrm traditional deployments
3. Added support for scp command execution trough ssh.
4. Feature flag `SSH_NG`
5. No existing delegate tasks were affected

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)

### CODE REVIEW

**Comment by acasian-harness** [comment]
trigger compile

**Comment by acasian-harness** [comment]
trigger compile

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 4 of 12 files at r1, 3 of 135 files at r4, 8 of 133 files at r6, 6 of 49 files at r7, 5 of 15 files at r8, 128 of 136 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)* status: :shipit: complete! ✓

**Review by vitsafronovici — DISMISSED** [review]

**Comment by acasian-harness** [comment]
trigger ti0

**Review by vitsafronovici — DISMISSED** [review]

**Review by vladimir-peric — DISMISSED** [review]
> Reviewed 1 of 142 files at r13, 1 of 141 files at r21, 9 of 139 files at r22, 6 of 49 files at r23, 5 of 15 files at r24, 134 of 142 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 139 files at r22, 8 of 135 files at r26, 6 of 49 files at r27, 5 of 15 files at r28, 130 of 138 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)* status: :shipit: complete! ✓

**Review by vitsafronovici — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 49 files at r7, 12 of 135 files at r9, 1 of 139 files at r22, 6 of 49 files at r27, 5 of 15 files at r28, 121 of 138 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)* status: :shipit: complete! ✓

**Review by filip5rovic — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 1 of 139 files at r22, 6 of 49 files at r27, 5 of 15 files at r28, 121 of 138 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31562)* status: :shipit: complete! ✓

**Pull request merged**
