### PR TITLE
feat: [DEL-5770]: Adding APIs from VersionInfoResource to DMS

### PR DESCRIPTION
**Pull request by AnupamIO**
Changes:
1- Adding delegateAuth based resources from cg-manager to DMS.
2- Refactor ringService to DMS.
3- For fetching accountData, we will call accountClient from DMS. Latency will slightly increase because in cg-manager it's direct call to accountService and in DMS we will call accountClient which is a network call.

Testing:
Tested at local, able to call manager using account Client and fetch data. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)

### CODE REVIEW

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 13 of 71 files at r1, 58 of 58 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: Some of the checks are too old. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`419-delegate-service-app/config/config.yml` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOiz-j375Yh_6FhdyZx:-NOiz-j8E3bFWFjsfU1g:b2afokq) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/419-delegate-service-app/config/config.yml#L73)):*
> ```YAML
>   readTimeOutSeconds: 15
> 
> managerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"
> ```

The secret probably shouldn't be here. We should either have another way of injecting the secret or use the standard replace configs mechanism we use for other kinds of secrets. 
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOizHkJ9Mv6gMGEdkdF:-NOizHkJ9Mv6gMGEdkdG:b5kki9f) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/419-delegate-service-app/src/main/java/io/harness/dms/app/DelegateServiceApp.java#L74)):*
> ```Java
> 
>   private void registerResources(Environment environment, Injector injector) {
>     environment.jersey().register(injector.getInstance(DummyResource.class));
> ```

I'm assuming you can probably get rid of dummy resource now since you have the real one. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOizfJNEh2vVNL8lbNd:-NOizfJNEh2vVNL8lbNe:b4delg7) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java#L40)):*
> ```Java
>   public RestResponse<List<String>> getDelegateVersionFromRing(@PathParam("ring") String ringName) {
>     final List<String> ringVersion = delegateRingService.getDelegateVersionsForRing(ringName, false);
>     if (!CollectionUtils.isEmpty(ringVersion)) {
> ```

We should ensure ringService returns empty list if no elements (if this is not done already). That can help avoid this kind of checks all over the code. 



_Code quote:_
```Java
    if (!CollectionUtils.isEmpty(ringVersion)) {
      return new RestResponse<>(ringVersion);
    }
```
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj-ZTt1kEFzqSAgd8K:-NOj-ZTt1kEFzqSAgd8L:b-stqa8j) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java#L52)):*
> ```Java
>   @ExceptionMetered
>   @PublicApi
>   public RestResponse<Map<String, List<String>>> getDelegateVersionFromRing() {
> ```

I think method name doesn't exactly reflect what it does. It returns all versions from all rings. Maybe make it plurals. e.g. `getDelegateVersionsFromRings` or `getDelegateVersionsFromAllRings` to make it more clear what it does. 
___
*[`420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj-x9b3OavuqcHCWAA:-NOj-x9b3OavuqcHCWAB:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/delegate/resources/DelegateServiceVersionInfoResource.java#L71)):*
> ```Java
>   @ExceptionMetered
>   @PublicApi
>   public RestResponse<Map<String, String>> getWatcherVersionFromRing() {
> ```

same
___
*[`420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceSwaggerGenerator.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj004i4wyVItrTENHH:-NOj004i4wyVItrTENHI:bryxpgs) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/delegate/utils/DelegateServiceSwaggerGenerator.java#L23)):*
> ```Java
>   // Adding DelegateSetupResource as a dummy resource for swagger to work, will change later.
>   private static final List<Class<?>> RESOURCE_CLASSES =
>       ImmutableList.<Class<?>>builder().add(DummyResource.class).add(DelegateServiceVersionInfoResource.class).build();
> ```

If you are removing dummy, do it from here as well. 
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj0sgQ179OaKR5Hn5L:-NOj0sgQ179OaKR5Hn5M:bxqsnhw) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java#L38)):*
> ```Java
> public class DelegateServiceRingServiceImpl implements DelegateRingService {
>   private final HPersistence persistence;
>   private final AccountClient accountClient;
> ```

My understanding is that this class is duplicating original DelegateRingServiceImpl.java with only difference that you obtain accounts ringName in a different way (through API vs through directly using accountService). 
If so, I think there is a better way to do this, to avoid duplication. You can instead create new provider interface, something like `AcountRingProvider`.  Which has a method that takes accountId and returns delegate ring (e,g, like below). You would then have separate implementation of this interface one for DMS and one for CG Manager and inject instance of that object instead of AccountClient/AccountService. 
each of the interface implementations would basically look like the `private DelegateRing getDelegateRing(String accountId) {` that is different in your current implementations.
If there are more use cases of this pattern, you can even name this provider more generic, like `AccountDataProvider`
Or you could even make CG manager also use API  :sweat_smile: 



_Code snippet:_
```Java
public interface AccountRingProvider {
  String getDelegateRingName(String accountId)  
}

public class ManagerAccountRingProvider implements AccountRingProvider {
  private final AccountService accountService;
  
  private String getDelegateRingName(String accountId) {
    return accountService.get(accountId).getRingName();
  }
}

public class DmsAccountRingProvider implements AccountRingProvider {
  private final AccountClient accountClient;
  
  private String getDelegateRingName(String accountId) {
    AccountDTO response = CGRestUtils.getResponse(accountClient.getAccountDTO(accountId));
    return response.getRingName();
  }
}
```
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj0bdw7nSmfV_rJnZi:-NOj0bdw7nSmfV_rJnZj:b-gho15h) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java#L67)):*
> ```Java
>   @Override
>   public List<String> getDelegateVersionsForRing(String ringName, boolean skipCache) {
>     // added below for testing, remove before pushing.
> ```

Don't forget to remove

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOj0sgQ179OaKR5Hn5L:-NPIIJW67z4cizShX4-Q:b-gfgmhf) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/420-delegate-service/src/main/java/io/harness/service/impl/DelegateServiceRingServiceImpl.java#L38)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

My understanding is that this class is duplicating original DelegateRingServiceImpl.java with only difference that you obtain accounts ringName in a different way (through API vs through directly using accountService). 
If so, I think there is a better way to do this, to avoid duplication. You can instead create new provider interface, something like `AcountRingProvider`.  Which has a method that takes accountId and returns delegate ring (e,g, like below). You would then have separate implementation of this interface one for DMS and one for CG Manager and inject instance of that object instead of AccountClient/AccountService. 
each of the interface implementations would basically look like the `private DelegateRing getDelegateRing(String accountId) {` that is different in your current implementations.
If there are more use cases of this pattern, you can even name this provider more generic, like `AccountDataProvider`
Or you could even make CG manager also use API  :sweat_smile: 
</blockquote></details>

sounds good, adding: AcccountDataProvider, we will resue it in future.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: Some of the checks are too old. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/config.yml` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/43941#-NOiz-j375Yh_6FhdyZx:-NPM2kMl1ROWG9PxEEsR:b-7mn5tz) ([raw file](https://github.com/harness/harness-core/blob/9f8e506d591b30a43f1f603cb3dfe4d0a98ac84f/419-delegate-service-app/config/config.yml#L73)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

The secret probably shouldn't be here. We should either have another way of injecting the secret or use the standard replace configs mechanism we use for other kinds of secrets. 
</blockquote></details>

ack, I'll keep this as empty and will add replace_config for this, few follow-up questions:
1- If we don't add secret here, how to interact with manager from local dms, by adding the value manually later? Yes we should avoid, adding secret to git but it is already present in all other config.yml so security issue will still be there.

**Review by mdmilic — CHANGES_REQUESTED** [review]
> Reviewed 11 of 21 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/43941#-NPr7nljDPdvB_u9zonb:-NPr0E4T-nOz0MIJXsP4:b-izhtlp) ([raw file](https://github.com/harness/harness-core/blob/336906f3682b629350612bf2153b7b0beff98429/419-delegate-service-app/container/scripts/replace_configs.sh#L30)):*
> ```Shell
> fi
> 
> <<<<<<< HEAD
> ```

You missed this while merging

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/container/scripts/replace_configs.sh` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/43941#-NPr7nljDPdvB_u9zonb:-NPwENH5-PiAEPYHi00_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/336906f3682b629350612bf2153b7b0beff98429/419-delegate-service-app/container/scripts/replace_configs.sh#L30)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

You missed this while merging
</blockquote></details>

Done.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43941)* status: :shipit: complete! ✓

**Pull request merged**
