### PR TITLE
fix: [CDS-42520]: PDC connector Test connection always fails when the…

### PR DESCRIPTION
**Pull request by bojanmicovic**
… port is not specified. Also, the port from secret should take precedence over the one specified in connector or host string directly.

## Describe your changes
The port from secret should take precedence over the one specified in connector or host string directly. The connector connection needs to have port at the end, or it will default to 22. (Error message is modified)
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41828)

### CODE REVIEW

**Comment by bojanmicovic** [comment]
trigger messagecheck

**Comment by vladimir-peric** [comment]
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/41828#-NJo52l56JB7pGfwtF3M:-NJo52l72nlpByTVzeYV:b-qrtji4) ([raw file](https://github.com/harness/harness-core/blob/e9c7b17ade29dc747c89ac5bd74cf0b9ba37993f/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L78)):*
> ```Java
>   public static String AUTHORIZATION_FAILURE = "Provided credentials are unauthorized.";
>   public static String DELEGATE_TO_HOST_SOCKET_CONNECTION_FAILED =
>       "Delegate(s) is(are) not able to establish socket connection to host(s). If the port is not specified with the host, it will default to 22.";
> ```

@bojanmicovic Do we clearly say in an error message which port was used when the connection failed, no matter where the port was taken from?

**Review by ivan-83 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41828)* status: 5 file(s) to review. 1 of 2 approvals obtained. 

___
*[`980-commons/src/main/java/io/harness/exception/ExplanationException.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/41828#-NJo52l56JB7pGfwtF3M:-NJoZo3Z7WxaHXLrbNYz:botylk3) ([raw file](https://github.com/harness/harness-core/blob/e9c7b17ade29dc747c89ac5bd74cf0b9ba37993f/980-commons/src/main/java/io/harness/exception/ExplanationException.java#L78)):*
<details><summary><i>Previously, vladimir-peric (Vladimir Peric) wrote…</i></summary><blockquote>

@bojanmicovic Do we clearly say in an error message which port was used when the connection failed, no matter where the port was taken from?
</blockquote></details>

or we can log the port on BE with the host info

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41828)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/SocketConnectivityBulkOrCapabilityCheck.java` line 72 at r1](https://reviewable.io/reviews/harness/harness-core/41828#-NJob7vy2dqVjM4EOqup:-NJob7vy2dqVjM4EOquq:b-3npy76) ([raw file](https://github.com/harness/harness-core/blob/e9c7b17ade29dc747c89ac5bd74cf0b9ba37993f/930-delegate-tasks/src/main/java/io/harness/delegate/task/executioncapability/SocketConnectivityBulkOrCapabilityCheck.java#L72)):*
> ```Java
>       if (EmptyPredicate.isNotEmpty(hostNames)) {
>         for (String host : hostNames) {
>           Optional<String> optionalHost = extractHostnameFromHost(host);
> ```

pls check the following part with @vitsafronovici  because of instance sync
Optional<String> optionalHost = extractHostnameFromHost(host);

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41828#-:-NJzNx0HCnBzQkCbPRB0:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by vladimir-peric — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41828)* status: :shipit: complete! ✓

**Pull request merged**
