### PR TITLE
[feat]: [CDS-71466]: Rollback Steps status should reflect in Instance

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49023)

### CODE REVIEW

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49023)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49023)* status: :shipit: complete! ✓

**Comment by ankittiwari-harness** [comment]
trigger review

**Comment by ankittiwari-harness** [comment]
trigger review

**Review by ankittiwari-harness — APPROVED** [review]

**Pull request merged**
