### PR TITLE
feat: [CVS-9260]: Added formula for Bad event type in ratioAnalyzerService

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31244)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger messagecheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31244)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/RatioAnalyserServiceImpl.java, line 27 at r1](https://reviewable.io/reviews/harness/harness-core/31244#-MxiUzl08KKB6TwvH6ru:-MxiUzl08KKB6TwvH6rv:b-unz7mq) ([raw file](https://github.com/harness/harness-core/blob/f9a3468da6d00176763193223ef06c1cc6a2b23f/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/RatioAnalyserServiceImpl.java#L27)):*
> ```Java
>     }
>     double metricValue = (metricValue1 / metricValue2) * 100;
>     if (sliSpec.getEventType().equals(RatioSLIMetricEventType.BAD)) {
> ```

can you move this logic to RatioSLIMetricEventType?
you can just have a method in the enum.



_Code quote:_
```Java
RatioSLIMetricEventType
```

**Review by AbhijithHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31244)* status: 3 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricEventType.java, line 16 at r2](https://reviewable.io/reviews/harness/harness-core/31244#-MxmkTqx52RO-7Bp71ef:-MxmkTqx52RO-7Bp71eg:bwyylg9) ([raw file](https://github.com/harness/harness-core/blob/86cfba4037b8da897eb291ecf6851895e5a34a67/300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/slimetricspec/RatioSLIMetricEventType.java#L16)):*
> ```Java
>   @JsonProperty("Bad") BAD;
> 
>   public static double getMetricValue(
> ```

Use non static function

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31244)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31244)* status: :shipit: complete! ✓

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31244#-:-MxquOUB0xSW0ALxtc6G:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
