### PR TITLE
techdebt: [DEL-4150]: Remove 430-cv-nextgen-commons and feature-flag dependencies from 260-delegate

### PR DESCRIPTION
**Pull request by johannesHarness**
Remove 430-cv-nextgen-commons and feature-flag dependencies from 260-delegate
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 19 of 94 files at r1, 142 of 142 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 52 of 52 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 17 of 94 files at r1, 133 of 142 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 52 of 52 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]

**Review by raghuAtWings — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33467#-:-N2selTf9E4jBzfG0xBp:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
