### PR TITLE
[feat]: [CDS-58576]: added deployment metadata in deploymentStageConfig

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Added a deploymentMetaData field in deploymentStageConfig. We need to put some metadata in deployment stage for google function swimlane, that's why added this field. Other swimlanes can also implement this interface in future if required. 
Disabled the flag: FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY in mapper 953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java for backward compatibility.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)

### CODE REVIEW

**Review by sainath-b — DISMISSED** [review]

**Comment by sainath-b** [comment]
Changes look good. But UTs are failing. @PragyeshMishra01 Please fix.

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/46056#-NSB2K60Boy2tbWr5eOY:-NSB2K60Boy2tbWr5eOZ:b-4zbqzu) ([raw file](https://github.com/harness/harness-core/blob/183f60fcb816ad1be516d253289a9e9e8a5845a7/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L73)):*
> ```Java
>     mapper = new ObjectMapper(new YAMLFactory());
>     mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
>     mapper.disable(DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY);
> ```

what is the behaviour when external type id is missing here  ?
is it possible to have deploymentTypeMetadata and not have deploymentType in the yaml ?

**Review by PragyeshMishra01 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)* status: 8 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/46056#-NSB2K60Boy2tbWr5eOY:-NSBA2_4ClMfWC5N8DPj:bn9ys4i) ([raw file](https://github.com/harness/harness-core/blob/183f60fcb816ad1be516d253289a9e9e8a5845a7/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L73)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what is the behaviour when external type id is missing here  ?
is it possible to have deploymentTypeMetadata and not have deploymentType in the yaml ?
</blockquote></details>

When deploymentType is missing and deploymentMetadata is present in yaml, deserialization failing with error 
com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing external type id property 'deploymentType' .

But I think it shouldn't cause any issue as we don't seem to allow saving the pipeline yaml without deploymentType field.
Do you think if it can cause any issue?

For the other case when deploymentType is present but deploymentMetadata isn't present in yaml, deserialization shouldn't not fail as we have disabled this flag.

https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/DeserializationFeature.html#FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Comment by PragyeshMishra01** [comment]
trigger messagecheck

**Review by rohitk-h — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)* status: 1. unresolved discussions.

**Comment by yogesh-chauhan** [comment]
*[`953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java` line 73 at r1](https://reviewable.io/reviews/harness/harness-core/46056#-NSB2K60Boy2tbWr5eOY:-NSKx-cU1IV-2VZisVjS:b-hcu0wu) ([raw file](https://github.com/harness/harness-core/blob/183f60fcb816ad1be516d253289a9e9e8a5845a7/953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java#L73)):*
> But I think it shouldn't cause any issue as we don't seem to allow saving the pipeline yaml without deploymentType field.
> Do you think if it can cause any issue?
 Yes I agree with this

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46056)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
