### PR TITLE
feat: [IDP-328]: Weekly job for deleting the disabled plugin configs

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46282)

### CODE REVIEW

**Review by vikyathharekal — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46282)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 279 at r1](https://reviewable.io/reviews/harness/harness-core/46282#-NSf4bZ-EUQGOPS_OleK:-NSf4bZ-EUQGOPS_OleL:b-objw2b) ([raw file](https://github.com/harness/harness-core/blob/a3bc2ee12d6e507d5721edb29796256ade29c070/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L279)):*
> ```Java
>     bind(ScheduledExecutorService.class)
>         .annotatedWith(Names.named("AppConfigDeleter"))
>         .toInstance(new ManagedScheduledExecutorService("AppConfigDeleter"));
> ```

Can we use the `purge` word instead of `delete` everywhere?



_Code quote:_
```Java
AppConfigDeleter
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigDeletionJob.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/46282#-NSf57UZDT2fAwuxNxcU:-NSf57UZDT2fAwuxNxcV:b-6glicx) ([raw file](https://github.com/harness/harness-core/blob/a3bc2ee12d6e507d5721edb29796256ade29c070/idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigDeletionJob.java#L61)):*
> ```Java
>     log.info("App Config deletion job started for disabled plugins....");
>     List<AppConfigEntity> disabledPluginsConfigsEntities =
>         appConfigRepository.findAllByConfigTypeAndEnabled(ConfigType.PLUGIN, false);
> ```

Can we avoid using the repo layer here? We can use the service layer which inturn calls the repo layer



_Code quote:_
```Java
appConfigRepository
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46282)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/app/IdpModule.java` line 279 at r1](https://reviewable.io/reviews/harness/harness-core/46282#-NSf4bZ-EUQGOPS_OleK:-NSfEoXv0cOroxx2sbVO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3bc2ee12d6e507d5721edb29796256ade29c070/idp-service/src/main/java/io/harness/idp/app/IdpModule.java#L279)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use the `purge` word instead of `delete` everywhere?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigDeletionJob.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/46282#-NSf57UZDT2fAwuxNxcU:-NSfEp7w2Hi0dnnDhc3W:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a3bc2ee12d6e507d5721edb29796256ade29c070/idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigDeletionJob.java#L61)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we avoid using the repo layer here? We can use the service layer which inturn calls the repo layer
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46282)* status: 9 file(s) to review. 1 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/configmanager/repositories/AppConfigRepositoryCustomImpl.java` line 56 at r3](https://reviewable.io/reviews/harness/harness-core/46282#-NSiLe_8-BiMvGmn3Ago:-NSiLe_8-BiMvGmn3Agp:bevxtea) ([raw file](https://github.com/harness/harness-core/blob/125fb5feadcb5630a9bcb64594484e6f3e468d76/idp-service/src/main/java/io/harness/idp/configmanager/repositories/AppConfigRepositoryCustomImpl.java#L56)):*
> ```Java
>   @Override
>   public List<AppConfigEntity> deleteDisabledPluginsConfigBasedOnTimestampsForEnabledDisabledTime(long baseTimeStamp) {
>     Criteria criteria = Criteria.where(AppConfigEntityKeys.enabledDisabledAt)
> ```

we could add an index to cover this query in future.
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerService.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/46282#-NSiL4KfBhOK0ErlGksb:-NSiL4KfBhOK0ErlGksc:b-bvt81r) ([raw file](https://github.com/harness/harness-core/blob/125fb5feadcb5630a9bcb64594484e6f3e468d76/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerService.java#L39)):*
> ```Java
>   MergedPluginConfigs mergeEnabledPluginConfigsForAccount(String accountIdentifier) throws Exception;
> 
>   List<AppConfigEntity> deleteDisabledPluginsConfigsThatAreDisableWithinOneWeek();
> ```

nit: How about `deleteDisabledPluginsConfigsDisabledMoreThanAWeekAgo()`?



_Code quote:_
```Java
WithinOneWeek
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java` line 218 at r3](https://reviewable.io/reviews/harness/harness-core/46282#-NSiLNYu3eRbNQh_jjKf:-NSiLNYu3eRbNQh_jjKg:b-7m1grm) ([raw file](https://github.com/harness/harness-core/blob/125fb5feadcb5630a9bcb64594484e6f3e468d76/idp-service/src/main/java/io/harness/idp/configmanager/service/ConfigManagerServiceImpl.java#L218)):*
> ```Java
>   @Override
>   public List<AppConfigEntity> deleteDisabledPluginsConfigsThatAreDisableWithinOneWeek() {
>     long baseTimeStamp = System.currentTimeMillis() - 7 * 24 * 60 * 60 * 1000;
> ```

nit: we could move this to a constant



_Code quote:_
```Java
7 * 24 * 60 * 60 * 1000
```
___
*[`idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigPurgeJob.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/46282#-NSiMhnW-RE6FuNDwKeL:-NSiMhnX7TK5zTJI80so:b-vtbqcj) ([raw file](https://github.com/harness/harness-core/blob/125fb5feadcb5630a9bcb64594484e6f3e468d76/idp-service/src/main/java/io/harness/idp/configmanager/jobs/ConfigPurgeJob.java#L29)):*
> ```Java
> @Singleton
> @OwnedBy(HarnessTeam.IDP)
> public class ConfigPurgeJob implements Managed {
> ```

If needed in future, we can configure this purger to run on weekend to avoid adding to the customer load.

**Review by vigneswara-propelo — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
