### PR TITLE
fix: [CDS-47505]: Better handling for ill formatted template yamls during CRUD

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
If the yaml for the template does not contain the "template" keyword at the root fail, we currently fail with "Something went wrong"

This PR improves the message to below :- 

**The provided template yaml does not contain the "template" keyword at the root level**

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41966)

### CODE REVIEW

**Review by hextechpal — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41966)* status: Some of the checks are too old. 2 file(s) to review. 1 of 2 approvals obtained.

**Review by vivekkarnatiharness — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41966)* status: Some of the checks are too old.

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41966)* status: Some of the checks are too old.

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by tchaurasiya — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41966)* status: 1 of 2 approvals obtained.

**Review by sainath-b — APPROVED** [review]

**Pull request merged**
