### PR TITLE
fix: [CDS-43128]: [BE] - Update the logic for WinRm Copy artifact to …

### PR DESCRIPTION
**Pull request by bojanmicovic**
…not provided.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39361)

### CODE REVIEW

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39361)* status: 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/39361#-NFTq4OA5YjYxpFRiDU8:-NFTq4OA5YjYxpFRiDU9:bmsh7rw) ([raw file](https://github.com/harness/harness-core/blob/60ac186a379cfef6fa612db0cc13b160e88bed5a/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L71)):*
> ```Java
> 
>     if (!FileSourceType.ARTIFACT.equals(((NgDownloadArtifactCommandUnit) commandUnit).getSourceType())) {
>       throw new InvalidRequestException("Invalid source type specified for command unit.");
> ```

1. this code is invoked only for download artifact command unit, correct? 
2. hint with explanation my friend :smile:

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/39361#-NFTq4OA5YjYxpFRiDU8:-NFUGUBUCA7DiJa-4T3y:bxay0oa) ([raw file](https://github.com/harness/harness-core/blob/60ac186a379cfef6fa612db0cc13b160e88bed5a/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L71)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

1. this code is invoked only for download artifact command unit, correct? 
2. hint with explanation my friend :smile: 
</blockquote></details>

You are right. We don't need this part of code since now we call this just for Download

**Comment by bojanmicovic** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java` line 71 at r1](https://reviewable.io/reviews/harness/harness-core/39361#-NFTq4OA5YjYxpFRiDU8:-NFUIHD6EdXqiyfW-2xt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/60ac186a379cfef6fa612db0cc13b160e88bed5a/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/AbstractDownloadArtifactCommandHandler.java#L71)):*
<details><summary><i>Previously, bojanmicovic (Bojan Micovic) wrote…</i></summary><blockquote>

You are right. We don't need this part of code since now we call this just for Download
</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39361#-:-NFURO8H1Orxs9hSlyfA:bnfp4nl)* status: 1. unresolved discussions.

**Review by acasian-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39361)* status: :shipit: complete! ✓

**Pull request merged**
