### PR TITLE
feat: [IDP-1203]: Fetch Github API base url from app config

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53020)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53020)* status: 9 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/53020#-NekqHqK1-rM13ucrlEF:-NekqHqK1-rM13ucrlEG:b8lg97q) ([raw file](https://github.com/harness/harness-core/blob/6ad8d7137b3e125f448b7bb86d27bc0f55d75d6a/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java#L96)):*
> ```Java
>       } else {
>         inputValueData.put(DSL_RESPONSE,
>             GsonUtils.convertJsonStringToObject(response.getEntity().toString(), Map.class).get(MESSAGE_KEY));
> ```

Looks like we are making the same changes in all the DSLs. We should consider moving this code to a commonplace (we can take this up later)
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/53020#-NekrAGX6B6LAYKf7-jU:-NekrAGX6B6LAYKf7-jV:b9wzgq8) ([raw file](https://github.com/harness/harness-core/blob/6ad8d7137b3e125f448b7bb86d27bc0f55d75d6a/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java#L58)):*
> ```Java
>   final SecretManagerClientService ngSecretService;
>   final ConfigReader configReader;
>   private static final String TARGET_URL_EXPRESSION_KEY = "appConfig.integrations.github.0.apiBaseUrl";
> ```

We have the host field in the catalog connector collection. How about fetching from it directly? It would be faster I believe.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53020)* status: 16 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/53020#-NekqHqK1-rM13ucrlEF:-NelDEEfBBWzLB88blXb:b-tojwwu) ([raw file](https://github.com/harness/harness-core/blob/6ad8d7137b3e125f448b7bb86d27bc0f55d75d6a/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/GithubMeanTimeToMergePRDsl.java#L96)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Looks like we are making the same changes in all the DSLs. We should consider moving this code to a commonplace (we can take this up later)
</blockquote></details>

Its common for Github DSLs for now. Will revisit this once we have other DSLs in place
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/53020#-NekrAGX6B6LAYKf7-jU:-NelD5wE0T2-5qMugut4:b-ch6090) ([raw file](https://github.com/harness/harness-core/blob/6ad8d7137b3e125f448b7bb86d27bc0f55d75d6a/idp-service/src/main/java/io/harness/idp/scorecard/datasources/providers/GithubProvider.java#L58)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We have the host field in the catalog connector collection. How about fetching from it directly? It would be faster I believe.
</blockquote></details>

As discussed offline, I have made this config as one time fetch

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut0

**Pull request merged**
