### PR TITLE
fix:[CDS-53369]: QA Hotfix Terraform provision state throws NPE

### PR DESCRIPTION
**Pull request by alebuh**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43810)

### CODE REVIEW

**Comment by alebuh** [comment]
trigger messagecheck

**Review by akhilpandey1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43810)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 660 at r1](https://reviewable.io/reviews/harness/harness-core/43810#-NNv593rBMmndXDnr40q:-NNv593rBMmndXDnr40r:bcotttl) ([raw file](https://github.com/harness/harness-core/blob/258a6974399873c98fe1ee0517937bed9ba13479/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L660)):*
> ```Java
>       if (featureFlagService.isEnabled(TERRAFORM_REMOTE_BACKEND_CONFIG, context.getAccountId())
>           && isNotEmpty(terraformExecutionData.getBackendConfigs())
>           && terraformExecutionData.getBackendConfigStoreType() != null
> ```

Condition looks good but I think we should add this condition in the nested if condition as that is where this is used, and the nested else does not use this

**Review by alebuh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43810)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 660 at r1](https://reviewable.io/reviews/harness/harness-core/43810#-NNv593rBMmndXDnr40q:-NNvGHwM7DQh78Z4mJAj:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/258a6974399873c98fe1ee0517937bed9ba13479/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L660)):*
<details><summary><i>Previously, akhilpandey1 (Akhilesh Pandey) wrote…</i></summary><blockquote>

Condition looks good but I think we should add this condition in the nested if condition as that is where this is used, and the nested else does not use this
</blockquote></details>

added

**Review by namantalaycha10 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43810)* status: :shipit: complete! ✓

**Pull request merged**
