### PR TITLE
feat: [CDS-46098]: Reduce the dimensions of instance sync metrics

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Describe your changes
1. Limiting labels to just accountId.
2. Reporting NG metrics separately.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39830)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/39830#-NGQEaEzEupCmIyoAe3p:-NGQEaEzEupCmIyoAe3q:be5ucn8) ([raw file](https://github.com/harness/harness-core/blob/2aae8b1198682fe02139728bf22e3063e66e3e6c/970-ng-commons/src/main/java/io/harness/instancesyncmonitoring/model/InstanceSyncMetricContext.java#L17)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDP)
> public class InstanceSyncMetricContext extends AutoMetricContext {
> ```

use io.harness.cvng.metrics.beans.AccountMetricContext and delete this class

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39830)* status: 0 of 1 approvals obtained.

**Review by shubham-in10se — DISMISSED** [review]

**Comment by vikyathharekal** [comment]
trigger ti1, ti3

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39830)* status: :shipit: complete! ✓

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39830)* status: :shipit: complete! ✓

**Pull request merged**
