### PR TITLE
feat: [STO-4624]: Replace StageElementConfig and StepElementConfig usage

### PR DESCRIPTION
**Pull request by r0610205**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37273)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37273)* status: 38 file(s) to review. 1 change requests. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcDAY7ZYhlRpLRURM:-NBQcDAY7ZYhlRpLRURN:bbsao1) ([raw file](https://github.com/harness/harness-core/blob/6a3074bc0d05f28c296e84c990b05805b17e3449/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java#L23)):*
> ```Java
> @Data
> public abstract class DeploymentAbstractStageNode extends AbstractStageNode {
>   @VariableExpression(skipVariableExpression = true) List<FailureStrategyConfig> failureStrategies;
> ```

why you are removing failure strategy?
___
*[`315-sto-manager/src/main/java/io/harness/app/impl/STOYamlSchemaServiceImpl.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcOVWAfRPVMNG4ME6:-NBQcOVXBCK1yzUYuELd:b7p2tk) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/315-sto-manager/src/main/java/io/harness/app/impl/STOYamlSchemaServiceImpl.java#L62)):*
> ```Java
>   private static final String SECURITY_STAGE_NODE = YamlSchemaUtils.getSwaggerName(SecurityStageNode.class);
>   private static final String STEP_ELEMENT_CONFIG = YamlSchemaUtils.getSwaggerName(AbstractStepNode.class);
>   private static final Class<AbstractStepNode> STEP_ELEMENT_CONFIG_CLASS = AbstractStepNode.class;
> ```

in your service, instead of AbstractNode, you should have one impl of STOAbstractStepNode just like CDAbstractstepNode
___
*[`315-sto-manager/src/main/java/io/harness/sto/plan/creator/filter/STOStageFilterJsonCreator.java` line 120 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcgpl-UQshVMl7WCa:-NBQcgpl-UQshVMl7WCb:bwhgaji) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/315-sto-manager/src/main/java/io/harness/sto/plan/creator/filter/STOStageFilterJsonCreator.java#L120)):*
> ```Java
>   }
> 
>   private void validateStage(SecurityStageNode stageElementConfig) {
> ```

security stage node should not extends IntegrationStageNode, as both services should be independent of it. whatever you need directly impl AbstractStageNode
___
*[`332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java` line 38 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQd-900dX778GhVpi_:-NBQd-900dX778GhVpia:b-nq5wfh) ([raw file](https://github.com/harness/harness-core/blob/6a3074bc0d05f28c296e84c990b05805b17e3449/332-ci-manager/service/src/main/java/io/harness/ci/beans/stages/IntegrationStageNode.java#L38)):*
> ```Java
> @OwnedBy(CI)
> @RecasterAlias("io.harness.beans.stages.IntegrationStageNode")
> public class IntegrationStageNode extends IntegrationAbstractStageNode {
> ```

@harshjain12 why this IntegrationAbstractStageNode is even needed?
Plus why CI is not compulsory code owner for ci code?



_Suggestion:_
```Java
IntegrationAbstractStageNode, 
```
___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQd_GM0uq3EM-Hq0n8:-NBQd_GN8Ipu0vk5cGFl:b-hn3mgt) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java#L86)):*
> ```Java
>   @JsonIgnore public abstract StageInfoConfig getStageInfoConfig();
> 
>   @VariableExpression(skipVariableExpression = true) List<FailureStrategyConfig> failureStrategies;
> ```

it should not be added here



_Code quote:_
```Java
@VariableExpression(skipVariableExpression = true) List<FailureStrategyConfig> failureStrategies
```
___
*[`960-yaml-sdk/src/main/java/io/harness/yaml/schema/AbstractSchemaChecker.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQdc4nBjtXl4A06lbM:-NBQdc4nBjtXl4A06lbN:b-lvve9) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/960-yaml-sdk/src/main/java/io/harness/yaml/schema/AbstractSchemaChecker.java#L90)):*
> ```Java
>         writer.write(currentVersionSchema);
> 
>         writer.close();
> ```

why this needs to be here?



_Code quote:_
```Java
        BufferedWriter writer = new BufferedWriter(new FileWriter(
            "/private/var/tmp/_bazel_sergey/d63952f6b42ec203d70ac9b4930e8472/execroot/harness_monorepo/bazel-out/darwin_arm64-fastbuild/testlogs/332-ci-manager/service/io.harness.CiBeansComponentTest/new_schema"));
        writer.write(currentVersionSchema);

        writer.close();
```

**Comment by r0610205** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQd_GM0uq3EM-Hq0n8:-NBUusAC7Cp2uYCc-O1b:b38vp5x) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/AbstractStageNode.java#L86)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should not be added here
</blockquote></details>

It looks like that all the classes in harness-core that inherit AbstractStageNode add failureStrategies, so was thinking it could be part of parent class.

**Comment by r0610205** [comment]
*[`960-yaml-sdk/src/main/java/io/harness/yaml/schema/AbstractSchemaChecker.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQdc4nBjtXl4A06lbM:-NBUvDg204rSJteMWTYW:b-4mbqul) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/960-yaml-sdk/src/main/java/io/harness/yaml/schema/AbstractSchemaChecker.java#L90)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this needs to be here?
</blockquote></details>

Or, this was from dumping local yaml changes, will be removed

**Comment by r0610205** [comment]
*[`315-sto-manager/src/main/java/io/harness/app/impl/STOYamlSchemaServiceImpl.java` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcOVWAfRPVMNG4ME6:-NBUvNkNE_Hfi9VAQCft:b-iolz) ([raw file](https://github.com/harness/harness-core/blob/a65d7554f635c53a71f71cfe5dc3c1332c4372c9/315-sto-manager/src/main/java/io/harness/app/impl/STOYamlSchemaServiceImpl.java#L62)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

in your service, instead of AbstractNode, you should have one impl of STOAbstractStepNode just like CDAbstractstepNode
</blockquote></details>

Noted, good point, I'll update

**Comment by r0610205** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcDAY7ZYhlRpLRURM:-NBUvShC51aTLyiNinM9:boomw0y) ([raw file](https://github.com/harness/harness-core/blob/6a3074bc0d05f28c296e84c990b05805b17e3449/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java#L23)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why you are removing failure strategy?
</blockquote></details>

I've posted in the below comment, but basically every single class that inherits from AbstractStageNode adds it, so we might as well have it in the parent, unless there is a use case for the node class without failure strategy.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37273)* status: 38 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/37273#-NBQcDAY7ZYhlRpLRURM:-NBVMD2G0nUmU49RLXbu:b5pxwna) ([raw file](https://github.com/harness/harness-core/blob/6a3074bc0d05f28c296e84c990b05805b17e3449/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java#L23)):*
<details><summary><i>Previously, r0610205 (Sergey Bobrov) wrote…</i></summary><blockquote>

I've posted in the below comment, but basically every single class that inherits from AbstractStageNode adds it, so we might as well have it in the parent, unless there is a use case for the node class without failure strategy.
</blockquote></details>

yes there are some classes which do not need failure strategy, like FF stage or in future it could be many

**Comment by r0610205** [comment]
Closing this in favor of merging with https://github.com/harness/harness-core/pull/37100

**Pull request closed without merging**
