### PR TITLE
feat: [PIE-9103]: Remove runSequence update during plan creation

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Describe your changes
Currently while running pipeline, if it fails before start, runSequence in increased by 1. To prevent this, we have added a transaction between pipeline start and increment operation of runSequence.

Testing: Manually failed the pipeline during plan creating and checked runSequence in successfully executed pipeline.
Did testing using curl and retry failed pipeline also

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)

### CODE REVIEW

**Review by sahilhindwani-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/46675#-NTrrDC_ACbW0CtGbh84:-NTrrDC_ACbW0CtGbh85:b-pktbmk) (no related file):*
Discussed offline on the changes to be done

___

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 523 at r5](https://reviewable.io/reviews/harness/harness-core/46675#-NTw_MR7A4TkYd1tlopU:-NTw_MR7A4TkYd1tlopV:b-5m3cmc) ([raw file](https://github.com/harness/harness-core/blob/f1a9c53aec476dcd20719a739743a45850c499c4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L523)):*
> ```Java
>       } catch (Exception e) {
>         log.warn("Add transaction for increment and startExecution as execution failed after plan creation");
>         throw new InvalidRequestException(e.getMessage());
> ```

convert to InternalServerException

**Review by archit-harness — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 523 at r5](https://reviewable.io/reviews/harness/harness-core/46675#-NTw_MR7A4TkYd1tlopU:-NTwu-wF0SYTNNki_qJI:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f1a9c53aec476dcd20719a739743a45850c499c4/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L523)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

convert to InternalServerException
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46675)* status: :shipit: complete! ✓

**Comment by prashantsharma04** [comment]
trigger review

**Pull request merged**
