### PR TITLE
fix: [DEL-5101]: mark delegate with no heartbeat for 5 mins as deleted

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
Problem: When ecs delegate goes down, we stop showing the delegate in delegate listing page in UI. But the tags associated with that delegate will still be listed during task/connectors creation. And user doesnt know where the tags are coming from.

So, temp solution is to mark ecs delegate as deleted, while having graceful shutdown. So that the associated tags will not be listed anywhere.

And permanent solution is DEL-4557.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 584 at r1](https://reviewable.io/reviews/harness/harness-core/38830#-NE_jRN9BpRswnFRAN10:-NE_jRN9BpRswnFRAN11:bsnpwyw) ([raw file](https://github.com/harness/harness-core/blob/aa463b95daafea86f7dc831266338e6b62a208a2/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L584)):*
> ```Java
>   @DelegateAuth
>   @PUT
>   @Path("mark-deleted/ECS")
> ```

Can we do as part of unregister api call ? In that way we don't need to do any change from delegate side.



_Code quote:_
```Java
@Path("mark-deleted/ECS")
```

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 5 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java` line 584 at r1](https://reviewable.io/reviews/harness/harness-core/38830#-NE_jRN9BpRswnFRAN10:-NEaJ1WpEEBWSm_axC75:bpaiuyw) ([raw file](https://github.com/harness/harness-core/blob/aa463b95daafea86f7dc831266338e6b62a208a2/400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java#L584)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Can we do as part of unregister api call ? In that way we don't need to do any change from delegate side.
</blockquote></details>

No, unregister api functionality is different, as the name suggests. And even using unregister will have delegate side changes also, as only immutable delegate calls this unregister api.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2768 at r1](https://reviewable.io/reviews/harness/harness-core/38830#-NEg3hJT5qgwfjd69Mpk:-NEg3hJUCBaYUOdOiZsQ:bswnifq) ([raw file](https://github.com/harness/harness-core/blob/aa463b95daafea86f7dc831266338e6b62a208a2/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2768)):*
> ```Java
>   }
> 
>   private void markECSDelegateAsDeleted() {
> ```

this is not a good approach. Network call during the shutdown may not be reliable. What stops us to mark the delegates deleted if there are no heartbeats from them for some time?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 2768 at r1](https://reviewable.io/reviews/harness/harness-core/38830#-NEg3hJT5qgwfjd69Mpk:-NEo_Bxz4NC2czE5jRMY:b-53a289) ([raw file](https://github.com/harness/harness-core/blob/aa463b95daafea86f7dc831266338e6b62a208a2/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L2768)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this is not a good approach. Network call during the shutdown may not be reliable. What stops us to mark the delegates deleted if there are no heartbeats from them for some time?
</blockquote></details>

Done. I am using heartbeat timeout as 5 mins

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2539 at r2](https://reviewable.io/reviews/harness/harness-core/38830#-NEqOYr_-QeRvfdluX3M:-NEqOYr_-QeRvfdluX3N:b-45euyj) ([raw file](https://github.com/harness/harness-core/blob/09f1ae480bb58956189d2acb04f17accd50027f3/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2539)):*
> ```Java
>         delegate.getAccountId(), delegate.getHostName(), delegate.isNg(), delegate.getDelegateType(), delegate.getIp());
> 
>     if (existingDelegate != null && existingDelegate.getStatus() == DelegateInstanceStatus.DELETED) {
> ```

why are these removed?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/iterator/DelegateTaskExpiryCheckIterator.java` line 88 at r2](https://reviewable.io/reviews/harness/harness-core/38830#-NEqOIp2EZIxH0Zs1jef:-NEtLuMv6UK6e3pzXIfT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/164a13ad60c8c83df6439f83d693f206885d7ee5/400-rest/src/main/java/io/harness/iterator/DelegateTaskExpiryCheckIterator.java#L88)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should only do it for ECS delegates
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2539 at r2](https://reviewable.io/reviews/harness/harness-core/38830#-NEqOYr_-QeRvfdluX3M:-NEtLvej2TaDzpuNL5gq:bad0he6) ([raw file](https://github.com/harness/harness-core/blob/09f1ae480bb58956189d2acb04f17accd50027f3/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2539)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why are these removed?
</blockquote></details>

history of why it was added:  Earlier there was some efforts to migrate users from trial accounts to community edition in 2019-20. At that time there was a migration which marked few delegates as DELETED. So when the next heartbeat comes from delegate, then manager will send a self-destruction command. Check this commit : https://github.com/harness/harness-core/commit/54db60bf8d061c9d23ecf0971335b1287d8dc6ac

Now its no longer required, and since we are marking delegate as DELETED, so if next time heartbeat comes then we should allow it.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: 1 change requests. 1. unresolved discussions.

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2795 at r3](https://reviewable.io/reviews/harness/harness-core/38830#-NEvzh1h5hZd4wCOBGCo:-NEvzh1h5hZd4wCOBGCp:bv2g9ak) ([raw file](https://github.com/harness/harness-core/blob/50c9362151f781135fbb90547a842776576809c4/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2795)):*
> ```Java
>               ? DelegateInstanceStatus.WAITING_FOR_APPROVAL
>               : DelegateInstanceStatus.ENABLED);
> ```

is this logic specific to ECS?

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2605 at r3](https://reviewable.io/reviews/harness/harness-core/38830#-NEw-4J7-GXxO6414C9D:-NEw-4J7-GXxO6414C9E:b-78zwtk) ([raw file](https://github.com/harness/harness-core/blob/ee55680e7cff5ae536435bde469be77d04ffc9a7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2605)):*
> ```Java
>           "Sending self destruct command from register delegate parameters because the existing delegate has status deleted.");
>       return DelegateRegisterResponse.builder().action(DelegateRegisterResponse.Action.SELF_DESTRUCT).build();
>     }
> ```

is this safe to remove?

**Review by jennyjames21 — COMMENTED** [review]
@arpit3107 Please test with the latest develop

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830#-:-NEw-KEP1su4GbHr3qwy:bnacc7d)* status: 1 change requests. 1. unresolved discussions.

**Review by xingchi-jin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38830)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2540 at r3](https://reviewable.io/reviews/harness/harness-core/38830#-NFAEF_3D7glAdRFKpJG:-NFAEF_3D7glAdRFKpJH:b-r0pn8r) ([raw file](https://github.com/harness/harness-core/blob/ee55680e7cff5ae536435bde469be77d04ffc9a7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2540)):*
> ```Java
>         delegate.getAccountId(), delegate.getHostName(), delegate.isNg(), delegate.getDelegateType(), delegate.getIp());
> 
>     if (existingDelegate != null && existingDelegate.getStatus() == DelegateInstanceStatus.DELETED) {
> ```

can we leave this block unchanged ? 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2599 at r3](https://reviewable.io/reviews/harness/harness-core/38830#-NFAEMdYBiZ4p2cbLyJ3:-NFAEMdYBiZ4p2cbLyJ4:b-r0pn8r) ([raw file](https://github.com/harness/harness-core/blob/ee55680e7cff5ae536435bde469be77d04ffc9a7/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2599)):*
> ```Java
>         delegateParams.isNg(), delegateParams.getDelegateType(), delegateParams.getIp());
> 
>     if (existingDelegate != null && existingDelegate.getStatus() == DelegateInstanceStatus.DELETED) {
> ```

can we leave this block unchanged ? 
___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 2795 at r3](https://reviewable.io/reviews/harness/harness-core/38830#-NEvzh1h5hZd4wCOBGCo:-NFAFrFq7-_-mFxevIkw:b-xbk6c) ([raw file](https://github.com/harness/harness-core/blob/50c9362151f781135fbb90547a842776576809c4/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L2795)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

is this logic specific to ECS? 
</blockquote></details>


@arpit3107  have a question for this line: delegate has 3 status, enabled, deleted and waiting_for_approval. The logic of handling deleted status is removed above. So this line will revert the 'deleted' status to be ENABLED.

1. it will apply to all delegates more than ECS, can we do ECS only ?
2. It will apply to not only registration but also heartbeat, do we want to contain it in registration only or both?
3. If we have to revert the status from 'deleted' to 'enabled', i would suggest not to write this line. Because it implicitly does the job. I's hard to trace and debug the error one day when we see related issues. Print logs when this happens

**Comment by arpit3107** [comment]
Closing this pr as this is having merge conflicts which is hard to fix in this case. Creating a new pr.

**Pull request closed without merging**
