### PR TITLE
feat: [CI-6357]: Added inputs api support

### PR DESCRIPTION
**Pull request by raghavharness**
## Describe your changes
Added inputs api support
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)

### CODE REVIEW

**Review by brijeshdhakar — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ3mN-C-92MDz0TOlkP:-NJ3mN-C-92MDz0TOlkQ:b-otew26) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java#L30)):*
> ```Java
>   @Builder
>   public static class ReferenceInput {
>     private InputEntity type;
> ```

Should be InputEntityType

**Comment by raghavharness** [comment]
> > Reviewed 15 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)_ status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ3mN-C-92MDz0TOlkP:-NJ3mN-C-92MDz0TOlkQ:b-otew26) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java#L30)):_
> 
> > ```java
> >   @Builder
> >   public static class ReferenceInput {
> >     private InputEntity type;
> > ```
> 
> Should be InputEntityType

@brijeshdhakar Why ? type itself is InputEntity no ? The final response would look like this.
`"repository": {
            "reference": {
                "type": {
                    "prompt": false,
                    "required": true,
                    "type": "string",
                    "enums": [
                        "branch",
                        "tag",
                        "pr"
                    ]
                },
                "value": {
                    "prompt": false,
                    "required": true,
                    "type": "string"
                }
            }
        }`

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ3mN-C-92MDz0TOlkP:-NJ5j7AC0mRTyt8TzlEW:bgixs38) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/entity/RepositoryInput.java#L30)):*
<details><summary><i>Previously, raghavharness (Raghav) wrote…</i></summary><blockquote>

@brijeshdhakar Why ? type itself is InputEntity no ? The final response would look like this.
`"repository": {
            "reference": {
                "type": {
                    "prompt": false,
                    "required": true,
                    "type": "string",
                    "enums": [
                        "branch",
                        "tag",
                        "pr"
                    ]
                },
                "value": {
                    "prompt": false,
                    "required": true,
                    "type": "string"
                }
            }
        }`

</blockquote></details>

Ohh got it. I thought other way.

**Comment by brijeshdhakar** [comment]
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/resource/InputsResponseDTOPMS.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ6h0DuCmjXqucLb-Tb:-NJ6h0DuCmjXqucLb-Tc:bz860t4) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/beans/resource/InputsResponseDTOPMS.java#L36)):*
> ```Java
> @Schema(name = "InputsResponse", description = "This contains Inputs details.")
> public class InputsResponseDTOPMS {
>   @JsonProperty("inputs") Map<String, InputEntity> inputs;
> ```

nit: I am just thinking, should we send the Json in this field?  What benifits do we have in sending the Map<String,InputEntity>.
Because we will have the inputs as yaml in pipeline yaml, so if we send as Json then we don't need to convert the yaml/json into object and on UI side, conevrt the map of object into json.

**Comment by raghavharness** [comment]
> d the Json in this field

> should we send the Json in this field
Do you mean as a string ? Not sure how this would be helpful. The inputs map will be converted to json at runtime so UI will get a json response like this.
`{
    "status": "SUCCESS",
    "data": {
        "inputs": {
            "image": {
                "prompt": false,
                "required": false,
                "default": "golang",
                "type": "string",
                "desc": "image name"
            },
            "repo": {
                "prompt": true,
                "required": true,
                "type": "string",
                "desc": "repository name"
            },
            "count": {
                "prompt": false,
                "required": false,
                "type": "number"
            },
            "password": {
                "prompt": false,
                "required": true,
                "type": "secret",
                "desc": "docker password",
                "enums": [
                    "secret1",
                    "secret2"
                ]
            }
        },
        "repository": {
            "reference": {
                "type": {
                    "prompt": false,
                    "required": true,
                    "type": "string",
                    "enums": [
                        "branch",
                        "tag",
                        "pr"
                    ]
                },
                "value": {
                    "prompt": false,
                    "required": true,
                    "type": "string"
                }
            }
        }
    },
    "metaData": null,
    "correlationId": "a4420da8-3f87-43b6-b732-994fb7c12def"
}`

**Review by hextechpal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 0 of 1 approvals obtained. 

___
*[`pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ91UJM80WPfN8LDblI:-NJ91UJM80WPfN8LDblJ:b-u342cx) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml#L21)):*
> ```YAML
>     required: true
> repository:
>   disabled: true
> ```

should this property be called cloneDisabled, or just clone?

**Comment by raghavharness** [comment]
> > Reviewed 1 of 17 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)_ status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 0 of 1 approvals obtained.
> 
> _[`pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ91UJM80WPfN8LDblI:-NJ91UJM80WPfN8LDblJ:b-u342cx) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml#L21)):_
> 
> > ```yaml
> >     required: true
> > repository:
> >   disabled: true
> > ```
> 
> should this property be called cloneDisabled, or just clone?
We decided to keep it disabled only under repository as per this [spec](https://harness.atlassian.net/wiki/spaces/~62473eb34fe01d006ba7c82d/pages/21239595574/Clone+Codebase+Test+Cases+-+YAML+Simplification).

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: Some of the checks are too old. 2 change requests. 1. unresolved discussions. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/resources/InputsResourcePMS.java` line 69 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJEKAc--YuyKM57NojC:-NJEKAc--YuyKM57NojD:b-p3arpn) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputs/resources/InputsResourcePMS.java#L69)):*
> ```Java
>       , @Content(mediaType = "application/yaml", schema = @Schema(implementation = ErrorDTO.class))
>     })
> public interface InputsResourcePMS {
> ```

Please create any new api via openAPi check with @mankrit-singh

**Review by hextechpal — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 17 files at r1, 6 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326#-:-NJFW8dn9x7yYlBwKwlc:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 10 of 17 files at r1, 6 of 7 files at r3, 1 of 1 files at r4, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by archit-harness — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: 1. unresolved discussions.

**Comment by raghavharness** [comment]
trigger ti1

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)* status: 1. unresolved discussions.

**Comment by naidu-harness** [comment]
> > > Reviewed 1 of 17 files at r1.
> > > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41326)_ status: Some of the checks are too old. 2 file(s) to review. 2 change requests. 0 of 1 approvals obtained.
> > 
> > 
> > _[`pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml` line 21 at r2](https://reviewable.io/reviews/harness/harness-core/41326#-NJ91UJM80WPfN8LDblI:-NJ91UJM80WPfN8LDblJ:b-u342cx) ([raw file](https://github.com/harness/harness-core/blob/42a588f968db2cc21ec987ba5e135f51908cf184/pipeline-service/service/src/test/resources/pipeline-v1-disabled-clone.yaml#L21)):_
> > > ```yaml
> > >     required: true
> > > repository:
> > >   disabled: true
> > > ```
> > 
> > 
> > should this property be called cloneDisabled, or just clone?
> > @hextechpal We decided to keep it disabled only under repository as per this [spec](https://harness.atlassian.net/wiki/spaces/~62473eb34fe01d006ba7c82d/pages/21239595574/Clone+Codebase+Test+Cases+-+YAML+Simplification).

clone : true / false makes very explicit

**Pull request merged**
