### PR TITLE
feat: [CDS-41690]: Cleanup aws unused fields from infrastructure

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36376)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36376)

**Review by acasian-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36376)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36376#-:-N9XZBQPCcwJ0eXMCFCL:bnfp4nl)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/36376#-N9XYOh27cpLcXC5Kqo-:-N9XYOh3ASew-2JlAjto:b-otrxv3) ([raw file](https://github.com/harness/harness-core/blob/0cbc69a188c9f5719cd228b80f981f6f2e164191/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L159)):*
> ```Java
>             .region(ParameterFieldHelper.getParameterFieldValue(sshWinRmAwsInfrastructure.getRegion()))
>             .loadBalancer(ParameterFieldHelper.getParameterFieldValue(sshWinRmAwsInfrastructure.getLoadBalancer()))
>             .useAutoScalingGroup(useAutoScalingGroup)
> ```

@vitsafronovici qq, we are not going to get the list of hosts from the autoscaling group in NG. did we make that discussion based on DB query on CG or?

**Review by acasian-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36376)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java` line 159 at r1](https://reviewable.io/reviews/harness/harness-core/36376#-N9XYOh27cpLcXC5Kqo-:-N9Xagb_AwFbm4OHmgTs:b-tvmpp9) ([raw file](https://github.com/harness/harness-core/blob/0cbc69a188c9f5719cd228b80f981f6f2e164191/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructureMapper.java#L159)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

@vitsafronovici qq, we are not going to get the list of hosts from the autoscaling group in NG. did we make that discussion based on DB query on CG or? 
</blockquote></details>

Yes @ivan-83 , this was decided at the demo. We will add support for it sometime later

**Pull request merged**
