### PR TITLE
fix: [DEL-4530]: remove FAIL_WORKFLOW_IF_SECRET_DECRYPTION_FAILS

### PR DESCRIPTION
**Pull request by xingchi-jin**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36909)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36909)

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36909)* status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java` line 980 at r1](https://reviewable.io/reviews/harness/harness-core/36909#-NDBvgkA-XEavrAWMP4c:-NDBvgkB7dFIX5xcACAI:b-wq7xxq) ([raw file](https://github.com/harness/harness-core/blob/da170e554508fbcb9aaffc6ebbd124d6bc88b249/400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java#L980)):*
> ```Java
>       delegateTaskService.handleResponse(delegateTask, taskQuery, response);
>       if (featureFlagService.isEnabled(
>               FeatureName.FAIL_WORKFLOW_IF_SECRET_DECRYPTION_FAILS, delegateTask.getAccountId())) {
> ```

any background on what's the use of this and why we want to remove this now ?



_Code quote:_
```Java
      if (featureFlagService.isEnabled(
              FeatureName.FAIL_WORKFLOW_IF_SECRET_DECRYPTION_FAILS, delegateTask.getAccountId())) {
        throw exception;
      }
```

**Review by xingchi-jin — COMMENTED** [review]
This feature flag has been enabled for 3 weeks, should be safe to remove it now. @raghuatwings  

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36909#-:-NDEq6cX1h4m0AjuaveO:bug3o1e)* status: Some of the checks are too old. 2 file(s) to review. 0 of 1 approvals obtained.

**Comment by xingchi-jin** [comment]
trigger ti1

**Comment by xingchi-jin** [comment]
trigger ti2

**Comment by xingchi-jin** [comment]
trigger messagecheck

**Comment by xingchi-jin** [comment]
trigger ti2

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36909)* status: Some of the checks are too old.

**Pull request closed without merging**
