### PR TITLE
feat: [CDS-49222]: Support migration of workflows as Pipelines

### PR DESCRIPTION
**Pull request by puthrayaharness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402#-:-NPJUB7xA3Hm-2d4og7C:bnfp4nl)* status: 29 file(s) to review. 1 of 2 approvals obtained.

**Review by arvind-choudhary-h — DISMISSED** [review]
> Reviewed 10 of 14 files at r1, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 29 file(s) to review.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 9 of 14 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 44 file(s) to review. 1 of 2 approvals obtained.

**Comment by puthrayaharness** [comment]
trigger ut3

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 19 files at r3, 1 of 1 files at r4, 1 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 39 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateRequestDTO.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/44402#-NPQipZEAEcCqOI_Jlvd:-NPQipZEAEcCqOI_Jlve:b-ejx6l4) ([raw file](https://github.com/harness/harness-core/blob/b0e45f578e3ce5f2f359b59091f0fb603262bf24/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateRequestDTO.java#L32)):*
> ```Java
> @ApiModel("InputSetTemplateRequest")
> @Schema(name = "InputSetTemplateRequest", description = "Contains Stage Identifiers to filter Runtime Input Template.")
> public class InputSetTemplateRequestDTO {
> ```

why we changing the package here?
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateResponseDTOPMS.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/44402#-NPQirdqAmRzbHqXK1lc:-NPQirdqAmRzbHqXK1ld:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/b0e45f578e3ce5f2f359b59091f0fb603262bf24/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateResponseDTOPMS.java#L36)):*
> ```Java
>     description = "This is the Runtime Input Template for a Pipeline defined in Harness.")
> public class InputSetTemplateResponseDTOPMS {
>   @Schema(description = InputSetSchemaConstants.RUNTIME_INPUT_TEMPLATE_MESSAGE) String inputSetTemplateYaml;
> ```

same as above

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 39 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateRequestDTO.java` line 32 at r6](https://reviewable.io/reviews/harness/harness-core/44402#-NPQipZEAEcCqOI_Jlvd:-NPQjU4R4atnvhvT2aVq:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b0e45f578e3ce5f2f359b59091f0fb603262bf24/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateRequestDTO.java#L32)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why we changing the package here?
</blockquote></details>

done
___
*[`pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateResponseDTOPMS.java` line 36 at r6](https://reviewable.io/reviews/harness/harness-core/44402#-NPQirdqAmRzbHqXK1lc:-NPQjUoI8CD6SO90wM0h:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b0e45f578e3ce5f2f359b59091f0fb603262bf24/pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource/InputSetTemplateResponseDTOPMS.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

done

**Review by puthrayaharness — COMMENTED** [review]
> Reviewed 10 of 14 files at r1, 15 of 19 files at r3, 1 of 1 files at r4, 9 of 14 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 39 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: 39 file(s) to review.

**Review by javeeth-basha — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 15 of 19 files at r3, 1 of 1 files at r4, 9 of 14 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44402)* status: :shipit: complete! ✓

**Pull request merged**
