### PR TITLE
feat: [CDS-46471]: Support filtering gitops clusters with environment group

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- This feature allows users to add filters on environments and gitOpsClusters based on tags of these entities. 
- This feature is will mainly be used in conjunction with multi service and multi infra deployments
- Users can select to filter `environments` and then provide filters to specific environments or chose to select to manually select clusters to deploy to. 
- Eg userflow: A user can select to deploy to a environment group and then deploy to filtered list of environments that have matching tags. 

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40912)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 93 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NIMNbfD4OV4pdlKZaFN:-NIMNbfE8a_Jl3tPubDI:bxut736) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L93)):*
> ```Java
>     // If no clusters are eligible then throw an exception.
> 
>     if (isNotEmpty(envGroupYaml.getFilters().getValue())) {
> ```

should we check for `ParameterField.isNotNull(envGroupYaml.getFilters())` also ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 102 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NIMOE7Q4IY2gDHxEGQ2:-NIMOE7Q4IY2gDHxEGQ3:b-jwwb2x) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L102)):*
> ```Java
>       List<String> filteredEnvRefs = filteredEnvs.stream().map(Environment::getIdentifier).collect(Collectors.toList());
> 
>       Map<String, io.harness.cdng.gitops.entity.Cluster> clsToCluster =
> ```

should we put this logic behind gitOpsEnabled flag ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 6 of 16 files at r1, 1 of 6 files at r2, 5 of 10 files at r3, 2 of 2 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40912)* status: 18 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 130 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINP2BRBsK78kwegdjM:-NINP2BRBsK78kwegdjN:bo7rdps) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L130)):*
> ```Java
>   private boolean applyMatchAllFilter(List<NGTag> entityTags, TagsFilter tagsFilter) {
>     return tagsFilter.getMatchType().name().equals(TAGFILTER_MATCHTYPE_ALL)
>         && areAllTagFiltersMatching(entityTags, TagMapper.convertToList(tagsFilter.getTags().getValue()));
> ```

does this handle the case when entityTags are null ? I see we are calling a for loop over it in `areAllTagFiltersMatching`

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 10 files at r3, 1 of 3 files at r4, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40912)* status: 18 file(s) to review. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 97 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINMkeZ7R_WMGlbbo55:-NINMkeZ7R_WMGlbbo56:b-xrpks9) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L97)):*
> ```Java
>    */
>   public Set<Environment> processTagsFilterYamlForEnvironments(FilterYaml filterYaml, Set<Environment> envs) {
>     if (filterYaml.getType().name().equals(FilterType.all.name())) {
> ```

nit: constant on left side of equals 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 102 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINNCCn4U5gGWNoibAj:-NINNCCn4U5gGWNoibAk:b-xrpks9) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L102)):*
> ```Java
>     // filter env that match all tags
>     Set<Environment> filteredEnvs = new HashSet<>();
>     if (filterYaml.getType().equals(FilterType.tags)) {
> ```

nit: constant on left side of equals

**Review by rohitk-h — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40912)* status: 18 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 93 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NIMNbfD4OV4pdlKZaFN:-NIQ49oDEzK0OhUn2muj:b-7g7nm2) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L93)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we check for `ParameterField.isNotNull(envGroupYaml.getFilters())` also ?
</blockquote></details>

yes, 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java` line 102 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NIMOE7Q4IY2gDHxEGQ2:-NIQ4EK71mSKlX09l_zr:b-ttktxn) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java#L102)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we put this logic behind gitOpsEnabled flag ?
</blockquote></details>

This plan creator is only for gitops flow, is not required. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 97 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINMkeZ7R_WMGlbbo55:-NIQ5IZQ3WHL0vMDgJFQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L97)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: constant on left side of equals 
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 102 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINNCCn4U5gGWNoibAj:-NIQ5JrQ1b2YbEcBt6MD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L102)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: constant on left side of equals 
</blockquote></details>

done
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 130 at r6](https://reviewable.io/reviews/harness/harness-core/40912#-NINP2BRBsK78kwegdjM:-NIQDHCO8s6WFyIV_lqy:b558pra) ([raw file](https://github.com/harness/harness-core/blob/6d74acdfe2873616edf5774c9b0ec07f4bb123c8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L130)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

does this handle the case when entityTags are null ? I see we are calling a for loop over it in `areAllTagFiltersMatching` 
</blockquote></details>

entityTags list is initialized as empty list and not null so it skips the loop. 
I did test the flow. I still added a safety check, good catch.

**Review by vaibhav-si — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40912)* status: 18 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java` line 79 at r7](https://reviewable.io/reviews/harness/harness-core/40912#-NIR2DC95ujrmMLqUxgx:-NIR2DCAASSSKgGzG31h:bxt40yu) ([raw file](https://github.com/harness/harness-core/blob/0a96613bb289a1948663d22f0cf9ca76117a8359/127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/helper/EnvironmentInfraFilterHelper.java#L79)):*
> ```Java
>     int count = 0;
>     for (NGTag tag : entityTags) {
>       if (tagsInFilter.contains(tag)) {
> ```

nit, given these are public methods, should we add null/empty check for tagsInFilter?

**Pull request closed without merging**
