### PR TITLE
fix: [CDS-35483]: ensure new random cache dir is created for each exe…

### PR DESCRIPTION
**Pull request by achyuth-harness**
…cution

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 395 at r1](https://reviewable.io/reviews/harness/harness-core/31801#-MzFV99Y43aCAQcytPYb:-MzFV99Y43aCAQcytPYc:bgy5i89) ([raw file](https://github.com/harness/harness-core/blob/20fa1c7b7739a6e214e78960ce8ce16f04c60dc2/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L395)):*
> ```Java
>           timeoutInMillis, repoName, cacheDir, chartVersion, checkIncorrectChartVersion);
>     } finally {
>       if (!cacheDir.contains(repoName + "/"
> ```

Don't you think it will make more sense to delete cacheDir in the same method where it is initialized? 
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 503 at r1](https://reviewable.io/reviews/harness/harness-core/31801#-MzFVeu17jNPNslp5Z5F:-MzFVeu17jNPNslp5Z5G:b8xp5ng) ([raw file](https://github.com/harness/harness-core/blob/20fa1c7b7739a6e214e78960ce8ce16f04c60dc2/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L503)):*
> ```Java
>     addRepo(storeDelegateConfig.getRepoName(), storeDelegateConfig.getRepoDisplayName(),
>         httpHelmConnector.getHelmRepoUrl(), username, password, destinationDirectory, manifest.getHelmVersion(),
>         timeoutInMillis, "");
> ```

Why we're passing here empty? Before we were using flags?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 395 at r1](https://reviewable.io/reviews/harness/harness-core/31801#-MzFV99Y43aCAQcytPYb:-MzFpYrDDh6Re97YpyU-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20fa1c7b7739a6e214e78960ce8ce16f04c60dc2/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L395)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Don't you think it will make more sense to delete cacheDir in the same method where it is initialized? 
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 503 at r1](https://reviewable.io/reviews/harness/harness-core/31801#-MzFVeu17jNPNslp5Z5F:-MzFpZbw9h0f7g89T4nH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20fa1c7b7739a6e214e78960ce8ce16f04c60dc2/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L503)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why we're passing here empty? Before we were using flags? 
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 420 at r2](https://reviewable.io/reviews/harness/harness-core/31801#-MzG-I47-Xu_b4ZKEqs0:-MzG-I47-Xu_b4ZKEqs1:b197c31) ([raw file](https://github.com/harness/harness-core/blob/614cdba72398f4895cd9d4da2c5c055d1409befe/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L420)):*
> ```Java
>           helmCommandFlag, timeoutInMillis, helmChartConfigParams.isCheckIncorrectChartVersion(), cacheDir);
>     } finally {
>       if (!cacheDir.contains(helmChartConfigParams.getRepoName() + "/"
> ```

can we use instead helmChartConfigParams.isDeleteRepoCacheDir()
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 517 at r2](https://reviewable.io/reviews/harness/harness-core/31801#-MzG-NP1CNy_ZUZcwiCd:-MzG-NP1CNy_ZUZcwiCe:b-ucwncj) ([raw file](https://github.com/harness/harness-core/blob/614cdba72398f4895cd9d4da2c5c055d1409befe/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L517)):*
> ```Java
>           manifest.getHelmCommandFlag(), timeoutInMillis, manifest.isCheckIncorrectChartVersion(), cacheDir);
>     } finally {
>       if (!cacheDir.contains(storeDelegateConfig.getRepoName() + "/"
> ```

Can we use instead helmChartConfigParams.isDeleteRepoCacheDir()

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)* status: 2 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java, line 420 at r2](https://reviewable.io/reviews/harness/harness-core/31801#-MzG-I47-Xu_b4ZKEqs0:-MzG7q7I4_-rTMboVav1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614cdba72398f4895cd9d4da2c5c055d1409befe/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L420)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we use instead helmChartConfigParams.isDeleteRepoCacheDir()
</blockquote></details>

Done.
___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java, line 517 at r2](https://reviewable.io/reviews/harness/harness-core/31801#-MzG-NP1CNy_ZUZcwiCd:-MzG7qV10ZVa2HJea-uL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/614cdba72398f4895cd9d4da2c5c055d1409befe/930-delegate-tasks/src/main/java/io/harness/delegate/task/helm/HelmTaskHelperBase.java#L517)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Can we use instead helmChartConfigParams.isDeleteRepoCacheDir()
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31801)* status: :shipit: complete! ✓

**Pull request merged**
