### PR TITLE
feat: [PL-25205]: Project hard delete

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33620)

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger OpenJDKPortalWithPatch-openjdkportalfeature

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33620)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 561 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bkIZZ3BYAVsY5obvF:-N3bkIZZ3BYAVsY5obvG:b3jlbqc) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L561)):*
> ```Java
>         log.info(String.format("Project with identifier %s and orgIdentifier %s was successfully deleted",
>             projectIdentifier, orgIdentifier));
>         yamlGitConfigService.deleteAll(accountIdentifier, orgIdentifier, projectIdentifier);
> ```

Should this be also behind the same FF?
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bl0kV0HdfyBShNUlD:-N3bl0kV0HdfyBShNUlE:bx0jy8g) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L119)):*
> ```Java
>     projectService = spy(new ProjectServiceImpl(projectRepository, organizationService, transactionTemplate,
>         outboxService, ngUserService, accessControlClient, scopeAccessHelper, instrumentationHelper,
>         yamlGitConfigService, ngFeatureFlagHelperService));
> ```

No change in delete method test case(s)?
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/AccountOrgProjectHelper.java` line 9 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bko9p7cNMPhx6eGcE:-N3bko9p7cNMPhx6eGcF:bj0i44m) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/123-ng-core-user/src/main/java/io/harness/ng/core/AccountOrgProjectHelper.java#L9)):*
> ```Java
> 
> @OwnedBy(PL)
> public interface AccountOrgProjectHelper {
> ```

Why it was required to take out interface as part of this PR?
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/eventHandlers/ConnectorEntityCRUDEventHandler.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bm3Z_9QxFPeJ0OG6z:-N3bm3Z_9QxFPeJ0OG7-:b-1swxoo) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/440-connector-nextgen/src/main/java/io/harness/connector/eventHandlers/ConnectorEntityCRUDEventHandler.java#L61)):*
> ```Java
>         entityScopeInfoBuilder.setOrgId(StringValue.of(orgIdentifier));
>       }
>       entityKeySource.updateKey(entityScopeInfoBuilder.build());
> ```

What is the purpose of this call?
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bmnk6EFFNBmVFNqOV:-N3bmnk6EFFNBmVFNqOW:bqvt9bh) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L227)):*
> ```Java
>         && gitSyncSdkService.isGitSyncEnabled(accountIdentifier, orgIdentifier, projectIdentifier)) {
>       connectors = connectorRepository.findAll(criteria, pageable, true);
>     } else if (Boolean.FALSE.equals(getDistinctFromBranches)
> ```

What is the impact of adding this in other flows calling the list method?

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33620)* status: 11 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java` line 561 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bkIZZ3BYAVsY5obvF:-N3bqHFH2v55Vza-f5G5:bfimw8w) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java#L561)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Should this be also behind the same FF?
</blockquote></details>

This needs to be done for connectors to delete gitSynced projects. This will complete the connectors hard delete functionality.
___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 119 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bl0kV0HdfyBShNUlD:-N3br9Nb1-VyXeQPRUEi:b-mwjhcz) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L119)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

No change in delete method test case(s)?
</blockquote></details>

Project delete test is done a bit weird. This test is projectResource class test. There is no change in this case. I thought I added another test class. Will check this again.
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/AccountOrgProjectHelper.java` line 9 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bko9p7cNMPhx6eGcE:-N3bqXim0FD2ukOZBXTh:bb2o5le) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/123-ng-core-user/src/main/java/io/harness/ng/core/AccountOrgProjectHelper.java#L9)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why it was required to take out interface as part of this PR?
</blockquote></details>

This is needed to be done inorder to get some dependency issues. Without this we are getting dependency error.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/eventHandlers/ConnectorEntityCRUDEventHandler.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bm3Z_9QxFPeJ0OG6z:-N3bqnVFCg1aZU_Foabm:b8yr0z7) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/440-connector-nextgen/src/main/java/io/harness/connector/eventHandlers/ConnectorEntityCRUDEventHandler.java#L61)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What is the purpose of this call?
</blockquote></details>

This call will clear of the gitSync cache
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java` line 227 at r2](https://reviewable.io/reviews/harness/harness-core/33620#-N3bmnk6EFFNBmVFNqOV:-N3bqrt34BE2tbLKxGLd:b-gighi9) ([raw file](https://github.com/harness/harness-core/blob/def65e0ef204f40be84a1c4bc480b7151ae466b9/440-connector-nextgen/src/main/java/io/harness/connector/impl/DefaultConnectorServiceImpl.java#L227)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

What is the impact of adding this in other flows calling the list method?
</blockquote></details>

No effect on existing list. Checked all flows to verify this. This comes to play in gitSynced projects. In that call we have 3 different types of connectors list. Verified this.

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Vulnerability 1 Vulnerabilities 
 
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/33620)

**Pull request closed without merging**
