### PR TITLE
feat: [PL-24409]: K8s Auth for vault in CG

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32062)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[400-rest/src/main/java/software/wings/scheduler/VaultSecretManagerRenewalHandler.java, line 85 at r2](https://reviewable.io/reviews/harness/harness-core/32062#-N-WrsTIAYqg9wDpcXmq:-N-WrsTIAYqg9wDpcXmr:btgmmrz) ([raw file](https://github.com/harness/harness-core/blob/5e1aa1fa2f13a28c85e6ad0bc3b1a5cc32bb21d0/400-rest/src/main/java/software/wings/scheduler/VaultSecretManagerRenewalHandler.java#L85)):*
> ```Java
>       return;
>     }
>     if (baseVaultConfig.isUseK8sAuth()) {
> ```

Can you please move this check and above one in a single method where we can check if renewal is needed or not and based on that you can either renew or just log that for the configured auth method renewal is not needed.

**Comment by shashank-harness** [comment]
*[400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java, line 91 at r2](https://reviewable.io/reviews/harness/harness-core/32062#-N-WsrIECoxyS739_9Ng:-N-WsrIECoxyS739_9Nh:b-ohtvte) ([raw file](https://github.com/harness/harness-core/blob/5e1aa1fa2f13a28c85e6ad0bc3b1a5cc32bb21d0/400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java#L91)):*
> ```Java
>       EncryptedData encryptedSecretId = wingsPersistence.get(EncryptedData.class, baseVaultConfig.getSecretId());
>       if (encryptedToken == null && encryptedSecretId == null && !baseVaultConfig.isUseVaultAgent()
>           && !baseVaultConfig.isUseK8sAuth()) {
> ```

This is wrong.
It should be something like this:



_Code snippet:_
```Java
      if (encryptedToken == null && encryptedSecretId == null && 
(!baseVaultConfig.isUseVaultAgent() ||  !baseVaultConfig.isUseK8sAuth())) {
//
}
```

**Comment by shashank-harness** [comment]
*[400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java, line 91 at r2](https://reviewable.io/reviews/harness/harness-core/32062#-N-WtL1MC4RQz1onffeB:-N-WtL1MC4RQz1onffeC:b-tes6vd) ([raw file](https://github.com/harness/harness-core/blob/5e1aa1fa2f13a28c85e6ad0bc3b1a5cc32bb21d0/400-rest/src/main/java/software/wings/service/impl/security/BaseVaultServiceImpl.java#L91)):*
> ```Java
>       EncryptedData encryptedSecretId = wingsPersistence.get(EncryptedData.class, baseVaultConfig.getSecretId());
>       if (encryptedToken == null && encryptedSecretId == null && !baseVaultConfig.isUseVaultAgent()
>           && !baseVaultConfig.isUseK8sAuth()) {
> ```

Lets discuss this. This seems wrong.

**Review by shashank-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32062)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32062)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32062)* status: 4 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32062)* status: 4 file(s) to review.

**Pull request merged**
