### PR TITLE
feat: [PL-32650]: In ACS, Acl processing for Role assignment in Outbox event handler.

### PR DESCRIPTION
**Pull request by Jimit09Gandhi**
## Describe your changes
In ACS, moved Role assignment event handlers from service to core module.
Added way to do Acl processing for Role assignment in Outbox event handler.
The change is behind config flag enableAclProcessingThroughOutbox.

## Checklist
- [X] I've documented the changes in the PR description.
- [X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)

### CODE REVIEW

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 36 of 38 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 41 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumer.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9ul09MEX8MLPCSyc:-Nfp9ul09MEX8MLPCSyd:b-mzyhgl) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumer.java#L31)):*
> ```Java
> @Singleton
> @Slf4j
> public class RoleAssignmentChangeConsumer implements AccessControlChangeConsumer<RoleAssignmentChangeEventData> {
> ```

Any changes from current debezium consumer?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp754z3S7Cv9OUSy8S:-Nfp754z3S7Cv9OUSy8T:brib2gu) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java#L36)):*
> ```Java
>   long deleteByRoleAssignmentIdAndImplicitForScope(String roleAssignmentId);
> 
>   long deleteByRoleAssignmentIdentifierAndScopeIdentifier(String identifier, String scopeIdentifier);
> ```

Lets be consistent and make it roleAssignmentId
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp22VO37h0EAUG2Ic4:-Nfp22VO37h0EAUG2Ic5:b-cwxvlq) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L102)):*
> ```Java
>   public long deleteByRoleAssignmentIdentifierAndScopeIdentifier(String identifier, String scopeIdentifier) {
>     return mongoTemplate
>             .remove(new Query(Criteria.where(scopeIdentifier).is(identifier).and(ACL.ROLE_ASSIGNMENT_IDENTIFIER_KEY).is(identifier)), ACL.class, getCollectionName())
> ```

It should be scopeIdentifier and not identifier
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp7AKr22QkNPtpXBRg:-Nfp7AKr22QkNPtpXBRh:b-dhweez) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java#L34)):*
> ```Java
> @EqualsAndHashCode
> public class RoleAssignment {
>   final String id;
> ```

The need for this change is not clear
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentService.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp3s3j-Q7z8xMug08D:-Nfp2m0aE1Wae7bSKA5A:b-qmkfwj) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentService.java#L40)):*
> ```Java
>   Optional<RoleAssignment> delete(@NotEmpty String identifier, @NotEmpty String scopeIdentifier);
> 
>   long deleteMultiAndAvoidAudit(@Valid @NotNull RoleAssignmentFilter roleAssignmentFilter);
> ```

We should avoid to have such method. Can we save the information whether to audit or not in Outbox Event itself?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentServiceImpl.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9H5-7q1mvUgYS6gG:-Nfp9H5-7q1mvUgYS6gH:b-5utcze) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentServiceImpl.java#L152)):*
> ```Java
>       for (String id : roleAssignmentIdsDeleted) {
>         RoleAssignment roleAssignment = RoleAssignment.builder().id(id).build();
>         outboxService.save(new RoleAssignmentDeleteEventV2(roleAssignment, roleAssignment.getScopeIdentifier(), false));
> ```

This logic isn't clear.
Wouldn't roleAssignment.getScopeIdentifier() return null?

Why fetch Ids? Can we not fetch all deleted RoleAssignmentDBOs?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentServiceImpl.java` line 162 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp8MLyDmoZ6-GQs1dj:-Nfp8MLyDmoZ6-GQs1dk:b-k2cwv0) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignmentServiceImpl.java#L162)):*
> ```Java
>   public List<RoleAssignment> deleteMulti(String scopeIdentifier, List<String> identifiers) {
>     return Failsafe.with(transactionRetryPolicy).get(() -> outboxTransactionTemplate.execute(status -> {
>       List<RoleAssignment> roleAssignmentsDeleted = roleAssignmentDao.findAllAndRemove(scopeIdentifier, identifiers);
> ```

How many roleAssignments are expected to be returned here? Should we delete in chunks?
Are transactions enabled in Access Control
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentCreateEventV2.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4ANV9dCB1476r-R0:-Nfp4ANV9dCB1476r-R1:bi21kxk) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentCreateEventV2.java#L20)):*
> ```Java
> @NoArgsConstructor
> public class RoleAssignmentCreateEventV2 implements Event {
>   public static final String ROLE_ASSIGNMENT_CREATE_EVENT = "RoleAssignmentCreated";
> ```

Should this be ROLE_ASSIGNMENT_CREATE_EVENT_V2
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4J8i7S2ptOLk9qK6:-Nfp4J8i7S2ptOLk9qK7:b777t8h) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java#L20)):*
> ```Java
> @NoArgsConstructor
> public class RoleAssignmentDeleteEventV2 implements Event {
>   public static final String ROLE_ASSIGNMENT_DELETE_EVENT = "RoleAssignmentDeleted";
> ```

Should this be ROLE_ASSIGNMENT_DELETE_EVENT_V2
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4bPL-7b2PjfRA-Dd:-Nfp4bPL-7b2PjfRA-De:b-tbb0ns) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java#L23)):*
> ```Java
>   private RoleAssignment roleAssignment;
>   private String scope;
>   private boolean audit;
> ```

skipAudit?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentUpdateEventV2.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4NPf5r_VUjCNT65s:-Nfp4NPf5r_VUjCNT65t:b-vu1uof) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentUpdateEventV2.java#L23)):*
> ```Java
>   private RoleAssignment newRoleAssignment;
>   private String scope;
>   public static final String ROLE_ASSIGNMENT_UPDATE_EVENT = "RoleAssignmentUpdated";
> ```

Should this be ROLE_ASSIGNMENT_UPDATE_EVENT_V2?
Should we also have skipAudit flag here?
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9aABCM3n5J5OEf4w:-Nfp9aABCM3n5J5OEf4x:b-ouuc3z) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java#L39)):*
> ```Java
>   long deleteMulti(@Valid @NotNull RoleAssignmentFilter roleAssignmentFilter);
> 
>   List<String> findAllIdsAndRemove(RoleAssignmentFilter roleAssignmentFilter);
> ```

findAndRemove
I think this should also return List<RoleAssignment>
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9bT59get8F0NyLBu:-Nfp9bT59get8F0NyLBv:b-kmoig3) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java#L41)):*
> ```Java
>   List<String> findAllIdsAndRemove(RoleAssignmentFilter roleAssignmentFilter);
> 
>   List<RoleAssignment> findAllAndRemove(String scopeIdentifier, List<String> identifiers);
> ```

findAndRemove
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp7VZ-CYvJojGIfdJ-:-Nfp7VZ-CYvJojGIfdJ0:b-t7gjn) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L74)):*
> ```Java
>     log.info("The current query for deleting multiple role assignment is: {}", query.toString());
>     query.fields().include(RoleAssignmentDBOKeys.id);
>     List<RoleAssignmentDBO> roleAssignmentDBOS = mongoTemplate.findAllAndRemove(query, RoleAssignmentDBO.class);
> ```

How man records are expected to be deleted in 1 shot?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-NfpA87NCK1r12GMXP1z:-NfpA87NCK1r12GMXP2-:b-mfz9v0) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java#L192)):*
> ```Java
>     if (enableAclProcessingThroughOutbox) {
>       RoleAssignmentChangeEventData roleAssignmentChangeEventData = RoleAssignmentChangeEventData.builder().newRoleAssignment(newRoleAssignment).build();
>       roleAssignmentChangeConsumer.consumeEvent(CREATE_ACTION, null, roleAssignmentChangeEventData);
> ```

Shouldn't this be UPDATE_ACTION?

I think we should thoroughly review this code. It seems to have been copy pasted

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: Some of the checks are too old. 41 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumer.java` line 31 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9ul09MEX8MLPCSyc:-Ng4s0B88cKMmvjMXTfN:b-8q3i0q) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/aggregator/src/main/java/io/harness/aggregator/consumers/RoleAssignmentChangeConsumer.java#L31)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Any changes from current debezium consumer?
</blockquote></details>

Core logic stays same.  I had already refactored in previous tasks and cleaned up to move acl generation logic to ACLGeneratorService.
Here, we need to handle case for Event V1 outbox types where we wont get the uuid from outbox event for deleted Role Assignments hence using  deleteByRoleAssignmentIdentifierAndScopeIdentifier.
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp754z3S7Cv9OUSy8S:-Ng4tRauAVurRgbiXyeg:bsentgj) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java#L36)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets be consistent and make it roleAssignmentId
</blockquote></details>

Made it roleAssignmentIdentifier as here it is Identifier and not _id (uuid).

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 41 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java` line 102 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp22VO37h0EAUG2Ic4:-Ng8zEu_7HzPd2sTV0rD:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/BaseACLRepositoryImpl.java#L102)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

It should be scopeIdentifier and not identifier
</blockquote></details>

done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp7AKr22QkNPtpXBRg:-Ng8yYQ37hr9WHkGgcL1:b-n2hr27) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java#L34)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

The need for this change is not clear
</blockquote></details>

We need role assignment uuid to delete the Corresponding ACLs on RoleAssignmentId. 
When delete event is generated, we write to outbox RoleAssignment model and so that model needs to have Id. Because RoleAssignmentDao layer returns RoleAssignment model and not RoleAssignmentDBO which is right way. 
In Debezium flow, change consumer used to id of RoleAssignment that was deleted.

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 43 file(s) to review. 1 change requests. 12. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentCreateEventV2.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4ANV9dCB1476r-R0:-Nh80cg8Evyu0VriAt-a:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentCreateEventV2.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be ROLE_ASSIGNMENT_CREATE_EVENT_V2
</blockquote></details>

done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4J8i7S2ptOLk9qK6:-Nh81HXBBQegjfwWQz8S:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java#L20)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be ROLE_ASSIGNMENT_DELETE_EVENT_V2
</blockquote></details>

done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentUpdateEventV2.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4NPf5r_VUjCNT65s:-Nh81LBL9K19-SlDBE6V:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentUpdateEventV2.java#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Should this be ROLE_ASSIGNMENT_UPDATE_EVENT_V2?
Should we also have skipAudit flag here?
</blockquote></details>

done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java` line 39 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9aABCM3n5J5OEf4w:-Nh829qn7_M7z2CYfoA4:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java#L39)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

findAndRemove
I think this should also return List<RoleAssignment>
</blockquote></details>

done
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp9bT59get8F0NyLBu:-Nh82pWYEMDnOBOa9gTb:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/RoleAssignmentDao.java#L41)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

findAndRemove
</blockquote></details>

done

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 43 file(s) to review. 1 change requests. 13. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp4bPL-7b2PjfRA-Dd:-NhAZejMA3Q8tTFXpxCr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/events/RoleAssignmentDeleteEventV2.java#L23)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

skipAudit?
</blockquote></details>

done

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: Some of the checks are too old. 43 file(s) to review. 1 change requests. 14. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-NfpA87NCK1r12GMXP1z:-Nh_Dvh5Cwdek2uZQ0-C:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/service/src/main/java/io/harness/accesscontrol/commons/outbox/RoleAssignmentEventHandler.java#L192)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Shouldn't this be UPDATE_ACTION?

I think we should thoroughly review this code. It seems to have been copy pasted
</blockquote></details>

done

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: Some of the checks are too old. 43 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java` line 74 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp7VZ-CYvJojGIfdJ-:-NhkNz87ENJ6AW08aEUz:bfz80zi) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/persistence/repositories/RoleAssignmentCustomRepositoryImpl.java#L74)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

How man records are expected to be deleted in 1 shot?
</blockquote></details>

As discussed in worst case role assignments to be deleted and fetched for scope can be upto 10k-20k as we scale. 
But loading that many records is memory shouldn't be issue. So we are doing any premature optimization.

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 19 files at r4, 11 of 18 files at r6, 7 of 8 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 44 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java` line 36 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp754z3S7Cv9OUSy8S:-NiEZsGI9-Lvjic4LKcc:b21wmq4) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/acl/persistence/repositories/ACLRepository.java#L36)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Made it roleAssignmentIdentifier as here it is Identifier and not _id (uuid).
</blockquote></details>

But other methods in this class use id like roleAssignmentId
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/53507#-Nfp7AKr22QkNPtpXBRg:-NiEbw0QBL1kJnPEu_CJ:bx1zeg9) ([raw file](https://github.com/harness/harness-core/blob/b4b931d85b3f65a20bedcdb222b4f92fd4ac131a/access-control/libs/core/src/main/java/io/harness/accesscontrol/roleassignments/RoleAssignment.java#L34)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We need role assignment uuid to delete the Corresponding ACLs on RoleAssignmentId. 
When delete event is generated, we write to outbox RoleAssignment model and so that model needs to have Id. Because RoleAssignmentDao layer returns RoleAssignment model and not RoleAssignmentDBO which is right way. 
In Debezium flow, change consumer used to id of RoleAssignment that was deleted.
</blockquote></details>

Lets discuss this once over a call
___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupServiceImpl.java` line 76 at r4](https://reviewable.io/reviews/harness/harness-core/53507#-NiEbznB1KKmBMhUvcVA:-NiEbznB1KKmBMhUvcVB:bcgjvre) ([raw file](https://github.com/harness/harness-core/blob/0f9690588331e760c8724198fef60bebe978336a/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupServiceImpl.java#L76)):*
> ```Java
> 
>   @Override
>   public List<UserGroup> listUserGroupForUserInAccessibleScopes(
> ```

Why this change?

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53507)* status: 44 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupServiceImpl.java` line 76 at r4](https://reviewable.io/reviews/harness/harness-core/53507#-NiEbznB1KKmBMhUvcVA:-NiEe7FD10YNsaRYvFuR:b64ezfo) ([raw file](https://github.com/harness/harness-core/blob/0f9690588331e760c8724198fef60bebe978336a/access-control/libs/core/src/main/java/io/harness/accesscontrol/principals/usergroups/UserGroupServiceImpl.java#L76)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

There are no changes in this file.

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Comment by Jimit09Gandhi** [comment]
trigger copyrightcheck

**Comment by Jimit09Gandhi** [comment]
trigger uts

**Pull request merged**
