### PR TITLE
[feat]: [PL-43848]: add Connector entity to generic uniqueId, parentUniqueId migration job

### PR DESCRIPTION
**Pull request by pbarapatre10**
## Describe your changes

Testing done locally:
- UniqueId populated for connectors
- parentUniqueId populated for connectors 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/57288)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57288)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJh5UYCPCnWbo99TAC:-NnJh5UYCPCnWbo99TAD:bou2960) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java#L82)):*
> ```Java
>       if (isNotEmpty(orgProjectKeysValue)) {
>         if (orgProjectKeysValue.size() == 2) {
>           orgFieldName = orgProjectKeysValue.get(0);
> ```

projectIdentifierFieldName
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJh7Qc42LYbosDuaow:-NnJh7Qc42LYbosDuaox:b-nsgqir) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java#L85)):*
> ```Java
>           projectFieldName = orgProjectKeysValue.get(1);
>         } else if (orgProjectKeysValue.size() == 1) {
>           orgFieldName = orgProjectKeysValue.get(0);
> ```

orgIdentifierFieldName
___
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJgvuhANvde3C0C1zz:-NnJgvuhANvde3C0C2--:b-s1ncr7) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java#L17)):*
> ```Java
> public interface UniqueIdAccess {
>   String UNIQUE_ID_KEY = "uniqueId";
>   String PARENT_UNIQUE_ID_KEY = "parentUniqueId";
> ```

Keep it in Migration class itself

**Review by pbarapatre10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57288)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java` line 82 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJh5UYCPCnWbo99TAC:-NnJj6LOA-L4Eh6UdW2v:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java#L82)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

projectIdentifierFieldName
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java` line 85 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJh7Qc42LYbosDuaow:-NnJj6jb4Ma-eS3VYlV3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/120-ng-manager/src/main/java/io/harness/ng/core/migration/AddUniqueIdParentIdToEntitiesTask.java#L85)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

orgIdentifierFieldName
</blockquote></details>

Done.
___
*[`960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/57288#-NnJgvuhANvde3C0C1zz:-NnJj7zU6pCTZMgoA4lY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/20763453038d41bcfe007491768cde8ff9406f85/960-persistence/src/main/java/io/harness/persistence/api/UniqueIdAccess.java#L17)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Keep it in Migration class itself
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/57288)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
trigger ut7

**Comment by pbarapatre10** [comment]
trigger ut8

**Comment by pbarapatre10** [comment]
trigger ut9

**Comment by pbarapatre10** [comment]
trigger pmd

**Comment by pbarapatre10** [comment]
trigger messagecheck

**Pull request merged**
