### PR TITLE
feat: [PIE-6221]: Add timeout of 10 second for yaml schema validation

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)

### CODE REVIEW

**Review by hextechpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQpkYi6Mf9cGhfdDZa:-NGQpkYi6Mf9cGhfdDZb:b-k5h3g7) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L130)):*
> ```Java
> 
>   @Override
>   public void validateYamlSchema(String accountId, String orgId, String projectId, String yaml) {
> ```

this should return a boolean
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 135 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQp_87B9cSjpzCJxh0:-NGQp_87B9cSjpzCJxh1:b9r1834) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L135)):*
> ```Java
>     if (pmsYamlSchemaHelper.isFeatureFlagEnabled(FeatureName.DISABLE_PIPELINE_SCHEMA_VALIDATION, accountId)) {
>       Future<Boolean> future = yamlSchemaExecutor.submit(() -> {
>         validateYamlSchemaInternal(accountId, orgId, projectId, yaml);
> ```

make these methods return boolean
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQpofx5saTFV22UuO0:-NGQpofy1jxkLXF7xAUz:b-hlk79j) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L140)):*
> ```Java
>       try (AutoLogContext accountLogContext =
>                new AccountLogContext(accountId, AutoLogContext.OverrideBehavior.OVERRIDE_NESTS)) {
>         future.get(10, TimeUnit.SECONDS);
> ```

capture the result and return that

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: 1 file(s) to review. 2 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQqJ-T3DubA8niCTc9:-NGQqJ-W5lzGqZ6V2avj:btjlyrm) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L108)):*
> ```Java
>       PmsSdkInstanceService pmsSdkInstanceService, PmsYamlSchemaHelper pmsYamlSchemaHelper, SchemaFetcher schemaFetcher,
>       @Named("allowedParallelStages") Integer allowedParallelStages,
>       @Named("YamlSchemaExecutorService") ExecutorService executor) {
> ```

Where we are creating this executor service? i think you forgot to commit the file



_Code quote:_
```Java
YamlSchemaExecutorService
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQqa7z9NqKgV17vAdi:-NGQqa7z9NqKgV17vAdj:b-8hbb5a) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L140)):*
> ```Java
>       try (AutoLogContext accountLogContext =
>                new AccountLogContext(accountId, AutoLogContext.OverrideBehavior.OVERRIDE_NESTS)) {
>         future.get(10, TimeUnit.SECONDS);
> ```

Can we keep this value as static constant at top of file



_Code quote:_
```Java
10
```

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQqJ-T3DubA8niCTc9:-NGR2Qi3E_YrOFwAOp_D:bj1vsye) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L108)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Where we are creating this executor service? i think you forgot to commit the file
</blockquote></details>

Yes :(

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 130 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQpkYi6Mf9cGhfdDZa:-NGR65Da2Ntj5F2DBLlr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L130)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

this should return a boolean
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 135 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQp_87B9cSjpzCJxh0:-NGR65nJCCWe62d4tlJU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L135)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

make these methods return boolean
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQpofx5saTFV22UuO0:-NGR66gxAHG1B45zlFSc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L140)):*
<details><summary><i>Previously, hextechpal (Prashant Pal) wrote…</i></summary><blockquote>

capture the result and return that
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 140 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQqa7z9NqKgV17vAdi:-NGR677j4EOM_meIp-Re:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L140)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we keep this value as static constant at top of file
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 108 at r1](https://reviewable.io/reviews/harness/harness-core/39865#-NGQqJ-T3DubA8niCTc9:-NGR685NE4Wz5f-dOk6u:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b7301869256c261d9988a807dee3bf13516859b7/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L108)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Yes :( 
</blockquote></details>

Done

**Review by archit-harness — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: 5 file(s) to review. 2 change requests. 4. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: 5 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by hextechpal — DISMISSED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: Some of the checks are too old.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39865)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
