### PR TITLE
Fix: [SRM-12316]: Fix monitored service URL in notifications

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)* status: 11 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/44138#-NOr2BpFEAaU4Ij0f_df:-NOr2BpFEAaU4Ij0f_dg:bhngqzv) ([raw file](https://github.com/harness/harness-core/blob/4f74330b3ad7888a7461b5c40677de2820c180be/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/BurnRateTemplateDataGenerator.java#L20)):*
> ```Java
> public class BurnRateTemplateDataGenerator extends SLOTemplateDataGenerator<SLOErrorBudgetBurnRateCondition> {
>   @Override
>   public Map<String, String> getTemplateData(ProjectParams projectParams, String name, String identifier,
> ```

duplicate code. should be part of  SLOTemplateDataGenerator. No need to make it an abstract method.

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java` line 42 at r1](https://reviewable.io/reviews/harness/harness-core/44138#-NOmr3hkPB2Yci9RpWe_-r1-42:-NOrw_h94kuLtzNs5ncC:b-vztnzg) ([raw file](https://github.com/harness/harness-core/blob/4f74330b3ad7888a7461b5c40677de2820c180be/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/notification/services/impl/SLOTemplateDataGenerator.java#L42)):*
<details><summary><i>Previously, naveen-harness (Naveen Shukla) wrote…</i></summary><blockquote>

nit: should be part of separate string constants file
</blockquote></details>

ideally it should be, but this constant won't be used anywhere else, and this is how it is like for other URL's as well, do didn't change. Plus it is dependent on lot of parameters which won't be used anywhere

**Review by deepak-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger messagecheck

**Review by naveen-harness — APPROVED** [review]

**Review by naveen-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)* status: 1. unresolved discussions.

**Review by naveen-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44138)* status: :shipit: complete! ✓

**Pull request merged**
