### PR TITLE
fix: [PL-27610]: added null check in isValidAttributeFilter method 

### PR DESCRIPTION
**Pull request by bhavya181**
## Describe your changes
 added null check in isValidAttributeFilter method in ConnectorResourceImpl
 
added UTs to verify changes

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)

### CODE REVIEW

**Comment by bhavya181** [comment]
trigger ut0, ut1, ut3, ut7, ut9

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQcI7mw4u8MIyi0VfsV:b8jlzlt) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
> ```Java
>           && isNotEmpty(attributeFilter.getAttributeValues());
>     }
>     return false;
> ```

Shouldn't null check be in the caller code

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQedIh63cXJqEIR3g_p:b2mwm2p) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Ideally this method should throw NullPointerException on null attribute filter. It should not say null attributeFilter is invalid. 
</blockquote></details>

Thats why check in caller for null

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQeiy6d4Lf7Gdm_ERxL:b-g7oalj) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Thats why check in caller for null
</blockquote></details>

I have added invalid request exception here only.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQep8cZ8vyYV2-i3KUY:b-ne5cyb) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

I have added invalid request exception here only.
</blockquote></details>

Let's throw NullPointerException from here.

Also, I see this code with null check already in ResourceGroupValidatorImpl

if (resourceSelector.getAttributeFilter() != null) {
          if (!isEmpty(resourceSelector.getIdentifiers())) {
            throw new InvalidRequestException("Cannot provide specific resources when you include attribute filter");
          }

          boolean isValidAttributeFilter = resourceMap.get(resourceSelector.getResourceType())
                                               .isValidAttributeFilter(resourceSelector.getAttributeFilter());
          if (!isValidAttributeFilter) {
            throw new InvalidRequestException("Invalid attribute filter");
          }

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQevhJY8H8d23eZzXI_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Let's throw NullPointerException from here.

Also, I see this code with null check already in ResourceGroupValidatorImpl

if (resourceSelector.getAttributeFilter() != null) {
          if (!isEmpty(resourceSelector.getIdentifiers())) {
            throw new InvalidRequestException("Cannot provide specific resources when you include attribute filter");
          }

          boolean isValidAttributeFilter = resourceMap.get(resourceSelector.getResourceType())
                                               .isValidAttributeFilter(resourceSelector.getAttributeFilter());
          if (!isValidAttributeFilter) {
            throw new InvalidRequestException("Invalid attribute filter");
          }
</blockquote></details>

done

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQew4wkD4FYB0F2SLMi:br5sgc4) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

done
</blockquote></details>

@bhavya181 Will NotNull annotation kick in? I don't think so. Did you check

**Review by bhavya181 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java` line 125 at r2](https://reviewable.io/reviews/harness/harness-core/45191#-NQcI7mw4u8MIyi0VfsU:-NQf2gTq1y252ubmfjjY:borhxw0) ([raw file](https://github.com/harness/harness-core/blob/ef602db663d305028fcf28377dc8def3e76cfbd6/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/connector/ConnectorResourceImpl.java#L125)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

@bhavya181 Will NotNull annotation kick in? I don't think so. Did you check
</blockquote></details>

yes, it will work, I have added UT on this, you can check that UT

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191#-:-NQfCOtJDaEN3uTp3_Mz:bnfp4nl)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by bhavya181** [comment]
trigger messagecheck

**Review by rijajoo — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: :shipit: complete! ✓

**Review by rijajoo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191#-:-NQjQyL24UPKhOLSyo6d:bnfp4nl)* status: :shipit: complete! ✓

**Comment by bhavya181** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger messagecheck

**Comment by abhayganvir** [comment]
trigger abhaymessagecheck

**Comment by abhayganvir** [comment]
trigger abhaymessagecheck

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45191)* status: Some of the checks are too old.

**Comment by abhayganvir** [comment]
trigger abhaymessagecheck

**Pull request merged**
