### PR TITLE
techdebt:[CDS-68173]: Added additional permission checks - PIPELINE_CREATE_AND_EDIT and PIPELINE_EXECUTE - for InputSet

### PR DESCRIPTION
**Pull request by sandeshsalunkhegh**
techdebt:[CDS-68173]: Added additional permission check for PIPELINE_CREATE_AND_EDIT and PIPELINE_EXECUTE

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-68173]: https://harness.atlassian.net/browse/CDS-68173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51033)

### CODE REVIEW

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger uts

**Comment by sandeshsalunkhegh** [comment]
trigger messagecheck, checkstylecodeformat

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51033)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 427 at r7](https://reviewable.io/reviews/harness/harness-core/51033#-NczEFc17RYDHt3hE8HJ:-NczEFc17RYDHt3hE8HK:b-kfyjnd) ([raw file](https://github.com/harness/harness-core/blob/d94396880e3f6743d2ecd04699595183c1e0941e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L427)):*
> ```Java
>       @NotNull @ResourceIdentifier String pipelineIdentifier, String inputSetIdentifier, String pipelineBranch,
>       String pipelineRepoID, GitEntityUpdateInfoDTO gitEntityInfo, @NotNull String invalidInputSetYaml)
>       throws AccessControlException {
> ```

what is this change helping to achieve?

**Review by sandeshsalunkhegh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51033)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 427 at r7](https://reviewable.io/reviews/harness/harness-core/51033#-NczEFc17RYDHt3hE8HJ:-Nd3Tmsh-tt7KbT06ATe:b-iauohe) ([raw file](https://github.com/harness/harness-core/blob/d94396880e3f6743d2ecd04699595183c1e0941e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L427)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

what is this change helping to achieve?
</blockquote></details>

This helps raise an exception in case of invalid access permissions.

**Comment by sandeshsalunkhegh** [comment]
trigger feature-build

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51033)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java` line 620 at r9](https://reviewable.io/reviews/harness/harness-core/51033#-Nd3nQSD4g2rMrfPKSS0:-Nd3nQSD4g2rMrfPKSS1:b-uqmfo7) ([raw file](https://github.com/harness/harness-core/blob/0cbc799beb076cf82cec7be933c9b0417dc9250c/pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMS.java#L620)):*
> ```Java
>       @PathParam(NGCommonEntityConstants.INPUT_SET_IDENTIFIER_KEY) @Parameter(
>           description = PipelineResourceConstants.INPUT_SET_ID_PARAM_MESSAGE) String inputSetIdentifier,
>       @BeanParam InputSetMoveConfigRequestDTO inputSetMoveConfigRequestDTO, @NotNull String permission);
> ```

Why we should pass permission into API? customer can send pipeline view permission then?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51033)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java` line 427 at r7](https://reviewable.io/reviews/harness/harness-core/51033#-NczEFc17RYDHt3hE8HJ:-Nd3nYJI14hEufoFe0nb:bh1df3d) ([raw file](https://github.com/harness/harness-core/blob/d94396880e3f6743d2ecd04699595183c1e0941e/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java#L427)):*
<details><summary><i>Previously, sandeshsalunkhegh (Sandesh Salunkhe) wrote…</i></summary><blockquote>

This helps raise an exception in case of invalid access permissions.
</blockquote></details>

Check my comment why permission needs to be passed to API

**Pull request closed without merging**
