### PR TITLE
[fix]: [CI-2901]: Remove github.com/dgrijalva/jwt-go dependency

### PR DESCRIPTION
**Pull request by shubham149**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30470)

### CODE REVIEW

**Review by vistaarjuneja — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30470#-:-MutYiQPDKvq1cLke11h:bnfp4nl)* status: :shipit: complete! ✓

**Comment by shubham149** [comment]
trigger messagecheck

**Comment by shubham149** [comment]
trigger messagecheck

**Comment by shubham149** [comment]
trigger messagecheck

**Comment by harshjain12** [comment]
trigger MessageMetadata

**Comment by harshjain12** [comment]
trigger MessageMetadata-message_metadata

**Comment by shubham149** [comment]
trigger messagecheck

**Pull request merged**
