### PR TITLE
[feat]:[pie-6323]: BE api for getFileUrl added

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Exposed a new api on the BE for getting fileUrl.

Testing:
1. GitHub file urls.
2. BB file urls.
3. BB server urls.
4. ADO urls.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42470)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV7knZD3MeQs0RgUol:-NLV7knZD3MeQs0RgUom:b-1f3xhu) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L449)):*
> ```Java
>   public String getFileUrl(ScmGetFileUrlRequestDTO scmGetFileUrlRequestDTO) {
>     if (isEmpty(scmGetFileUrlRequestDTO.getBranch())) {
>       return scmGetFileUrlRequestDTO.getFilePath();
> ```

No, we don't send filepath instead of file url. Thats wrong.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 461 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV83vW6IWibTbUyc_0:-NLV83vW6IWibTbUyc_1:b-ea3qf7) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L461)):*
> ```Java
>   @ApiOperation(value = "Get file url", nickname = "getFileURL")
>   @Hidden
>   public ResponseDTO<String> getFileURL(@Parameter(description = ACCOUNT_PARAM_MESSAGE) @NotBlank @QueryParam(
> ```

I think it was discussed that sending a plain data type isn't advisable. Rather we should send a object which contains this value.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV8G7R1kugimUKobAy:-NLV8G7R1kugimUKobAz:b88dtot) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java#L118)):*
> ```Java
>   ExecutorService executorService = Executors.newFixedThreadPool(1);
> 
>   @Mock GitFilePathHelper gitFilePathHelper;
> ```

can we add more test cases around : what if connector is invalid, what if connector isn't found etc.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42470)* status: 5 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java` line 449 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV7knZD3MeQs0RgUol:-NLV8wqM9kWfFrQ_eHE-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java#L449)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

No, we don't send filepath instead of file url. Thats wrong.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java` line 461 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV83vW6IWibTbUyc_0:-NLV96QwDRdluLKsytJo:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/ScmFacilitatorResource.java#L461)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think it was discussed that sending a plain data type isn't advisable. Rather we should send a object which contains this value.
</blockquote></details>

done
___
*[`136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java` line 118 at r1](https://reviewable.io/reviews/harness/harness-core/42470#-NLV8G7R1kugimUKobAy:-NLVC10D7OD0Q_-F1rSz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2c3107427d2789ddb8b21d0f09bf25affe260e65/136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java#L118)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we add more test cases around : what if connector is invalid, what if connector isn't found etc.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42470)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42470)* status: :shipit: complete! ✓

**Pull request merged**
