### PR TITLE
feat: [CDS-37176]: Support Custom approvals in NG

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)

### CODE REVIEW

**Comment by puthrayaharness** [comment]
trigger ti1 ti2 ti3 ti0

**Comment by puthrayaharness** [comment]
trigger ti1 ti2 ti3 ti0

**Comment by puthrayaharness** [comment]
trigger messagecheck

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 7 of 53 files at r1, 4 of 12 files at r2, 6 of 39 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 43 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54s6iW1Zxi21ErMyeJ:-N54s6iW1Zxi21ErMyeK:b-40o03l) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L78)):*
> ```Java
>   private void pushInternal(Map<String, ResponseData> response) {
>     log.info("Received response from custom approval script execution with instanceId - {}", approvalInstanceId);
>     CustomApprovalInstance instance = (CustomApprovalInstance) approvalInstanceService.get(approvalInstanceId);
> ```

passed instance to internal method
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/entities/CustomApprovalInstance.java` line 116 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54qTWt3BA2dcRaEHr4:-N54qTWt3BA2dcRaEHr5:b6oo0xp) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/entities/CustomApprovalInstance.java#L116)):*
> ```Java
>   public List<Long> recalculateNextIterations(String fieldName, boolean skipMissed, long throttled) {
>     long nextAttempt = ZonedDateTime.now(ZoneOffset.UTC).toInstant().toEpochMilli();
>     long gap = getGap();
> ```

Adding index to nextIterations in Approval Instance.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54wUYECNPhIN60bCFr:-N54wUYECNPhIN60bCFs:blrqhr3) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L36)):*
> ```Java
>     if (ticket == null || ticket.getFields() == null || EmptyPredicate.isEmpty(ticket.getFields())) {
>       throw new ApprovalStepNGException(
>           "Custom Approval has no output fields. At least one output field must be set", true);
> ```

Check fatal=false for retrying approval
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54wrLbEzTwNCstVrKa:-N54wrLbEzTwNCstVrKb:bvh9zo2) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L60)):*
> ```Java
>         return (boolean) result;
>       } else {
>         throw new ApprovalStepNGException("Non boolean result while evaluating approval condition", true);
> ```

check fatal here, can be true here
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54xb1yBcb7tbS5IJeS:-N54xb1yBcb7tbS5IJeT:b-8bvydb) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L81)):*
> ```Java
>         String standardValue = condition.getValue();
>         if (!ticket.getFields().containsKey(condition.getKey())) {
>           log.warn("Field {} is not exported. Evaluating criteria to false", condition.getKey());
> ```

log callback to show warning to users 
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 85 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54xrOb8Xyq2nlbu1qt:-N54xrOb8Xyq2nlbu1qu:b63rtq8) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L85)):*
> ```Java
>         }
>         Object ticketValue = ticket.getFields().get(condition.getKey());
>         Object ticketDisplayValue = ticket.getFields().get(condition.getKey());
> ```

ticketValue should be enough
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54yiPm5RfZ7pf_OlPL:-N54yiPm5RfZ7pf_OlPM:b-k5qoe5) ([raw file](https://github.com/harness/harness-core/blob/563c36e70d857bbffa5d0f5c8e7d30d5338e82fa/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L140)):*
> ```Java
>         if (commandExecutionStatus == SUCCESS) {
>           saveExecutionLog(format("Command completed with ExitCode (%d)", processResult.getExitValue()), INFO,
>               commandExecutionStatus);
> ```

Check for CG shell script

**Review by puthrayaharness — COMMENTED** [review]
> Reviewed 46 of 53 files at r1, 5 of 12 files at r2, 21 of 39 files at r3, 2 of 5 files at r5, 29 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 52 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 1 approvals obtained. Waiting on team(s): sto. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54s6iW1Zxi21ErMyeJ:-N5Jhtim1XJj-0YUZWL_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L78)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

passed instance to internal method
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/entities/CustomApprovalInstance.java` line 116 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54qTWt3BA2dcRaEHr4:-N5JhuRk9h7Nc0yzAX9e:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/entities/CustomApprovalInstance.java#L116)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Adding index to nextIterations in Approval Instance.
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 36 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54wUYECNPhIN60bCFr:-N5Jhv3gDawXkgE2mo2T:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L36)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Check fatal=false for retrying approval
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 60 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54wrLbEzTwNCstVrKa:-N5Jhvao5XycQdk9vyLh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L60)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

check fatal here, can be true here
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 81 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54xb1yBcb7tbS5IJeS:-N5JhwMOB5C9ihvbUZpM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L81)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

log callback to show warning to users 
</blockquote></details>

Done.
___
*[`860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java` line 85 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54xrOb8Xyq2nlbu1qt:-N5JhwhQ3uuKmrTqiyD-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/860-orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation/CustomApprovalCriteriaEvaluator.java#L85)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

ticketValue should be enough
</blockquote></details>

Done.
___
*[`960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java` line 140 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54yiPm5RfZ7pf_OlPL:-N5JhxCH8F-x0z7TZXk-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/563c36e70d857bbffa5d0f5c8e7d30d5338e82fa/960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java#L140)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

Check for CG shell script
</blockquote></details>

Done.

**Review by prabu-kr — APPROVED** [review]
> Reviewed 19 of 53 files at r1, 5 of 12 files at r2, 11 of 39 files at r3, 2 of 5 files at r5, 29 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 1 change requests. 7. unresolved discussions. Waiting on team(s): sto.

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 1 of 53 files at r1, 6 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 1 change requests. 6. unresolved discussions. Waiting on team(s): sto. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54s6iW1Zxi21ErMyeJ:-N5JiQn1DI0H9341hwXd:b-knka3x) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L78)):*
<details><summary><i>Previously, puthrayaharness (Deepak Puthraya) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We're calling approvalInstanceService again in internal method.

**Review by arpit3107 — APPROVED** [review]
> Reviewed 19 of 53 files at r1, 5 of 12 files at r2, 11 of 39 files at r3, 2 of 5 files at r5, 29 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 1 change requests. 6. unresolved discussions. Waiting on team(s): sto.

**Review by puthrayaharness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 1 change requests. 7. unresolved discussions. Waiting on team(s): sto. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java` line 78 at r4](https://reviewable.io/reviews/harness/harness-core/32938#-N54s6iW1Zxi21ErMyeJ:-N5Jkk1q0DKcI4MyccTD:bmkyga) ([raw file](https://github.com/harness/harness-core/blob/8e9d70407d866c8f05ed7bf5787bdd3f776025d1/800-pipeline-service/src/main/java/io/harness/pms/approval/custom/CustomApprovalCallback.java#L78)):*
<details><summary><i>Previously, hingerabhinav (Abhinav Hinger) wrote…</i></summary><blockquote>

We're calling approvalInstanceService again in internal method. 
</blockquote></details>

Done. You are looking at old changes

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: 1. unresolved discussions. Waiting on team(s): sto.

**Review by hingerabhinav — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938)* status: Waiting on team(s): sto.

**Comment by puthrayaharness** [comment]
trigger license/cla

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 19 of 53 files at r1, 5 of 12 files at r2, 11 of 39 files at r3, 2 of 5 files at r5, 29 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32938#-:-N5JrAPw2xqGATOtJbo7:bnfp4nl)* status: Waiting on team(s): sto.

**Pull request merged**
