### PR TITLE
[fix]: [PL-38528]: Fixing incorrect usage of allowableValues in RoleDTO to avoid wrong openapi schema generation

### PR DESCRIPTION
**Pull request by ashishsanodia-harness**
## Describe your changes
Fixing incorrect usage of allowableValues in RoleDTO to avoid wrong openapi schema generation

Test:

- Verified Roles listing page working fine
- Verified Get Role working fine
- Verified new Role creation working fine
- Verified Role update working fine
- Verified generated openapi diff. Attached screenshot new V/S old
Screenshot 2023-05-05 at 11 10 12 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47402)

### CODE REVIEW

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/47402#-NUfsPJHE3eGrHdGJqJ9:-NUfsPJHE3eGrHdGJqJA:bi6qty) ([raw file](https://github.com/harness/harness-core/blob/39efba97411e478c533492b294ae20477ed9d968/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L53)):*
> ```Java
> 
>   @Schema(type = "string", allowableValues = {"account", "organization", "project"})
>   public enum ScopeLevel {
> ```

Can we use some ScopeLevel from some common utils in mono-repo?

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/47402#-NUfsPJHE3eGrHdGJqJ9:-NUhCZXT2_3c8P5T18Bb:b9f28et) ([raw file](https://github.com/harness/harness-core/blob/39efba97411e478c533492b294ae20477ed9d968/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L53)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can we use some ScopeLevel from some common utils in mono-repo? 
</blockquote></details>

values are different than what we are using for this allowedScopeLevels

**Review by Jimit09Gandhi — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402#-:-NV0Cp3n0OYFQOcrn17W:bnfp4nl)* status: Some of the checks are too old. 8 file(s) to review. 1 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 53 at r1](https://reviewable.io/reviews/harness/harness-core/47402#-NUfsPJHE3eGrHdGJqJ9:-NV0Cr2Q4zQ6Fo--3_IN:b1lpiu2) ([raw file](https://github.com/harness/harness-core/blob/39efba97411e478c533492b294ae20477ed9d968/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L53)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

values are different than what we are using for this allowedScopeLevels
</blockquote></details>

As discussed we found we cant use ScopeLevel defined in common package in Harness core as

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/47402#-NV81HvS35toCKV0g9Uf:-NV81HvS35toCKV0g9Ug:b9lk8k8) ([raw file](https://github.com/harness/harness-core/blob/cc1862ead14767f99b91f761c382c84540023872/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java#L80)):*
> ```Java
>   }
> 
>   public static String fromAllowedScopeLevelEnum(ScopeLevel scopeLevel) {
> ```

Whats the need for this method?
___
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/47402#-NV81MFZ4pnvs3W75Gku:-NV81MFZ4pnvs3W75Gkv:bcnomb0) ([raw file](https://github.com/harness/harness-core/blob/cc1862ead14767f99b91f761c382c84540023872/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java#L91)):*
> ```Java
>   }
> 
>   public static ScopeLevel toAllowedScopeLevelEnum(String scopeLevel) {
> ```

This method belongs to ScopeLevel enum as a static method

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9BYg54SIxA3-tdyQm:-NV9BYg6EHo8xgHhh2z7:b-4tsxtb) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L73)):*
> ```Java
>     }
> 
>     public static ScopeLevel toAllowedScopeLevelEnum(String scopeLevel) {
> ```

Lets call it fromString
___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9Bitv8Kmh3QPgTOKO:-NV9Bitv8Kmh3QPgTOKP:b5lkr0j) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L77)):*
> ```Java
>         return null;
>       }
>       return getEnum(ScopeLevel.class, scopeLevel.toUpperCase());
> ```

Why change to upperCase?

we should do something like this https://stackoverflow.com/a/37841094

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9BYg54SIxA3-tdyQm:-NV9JC9L8BFX9eeEZnDl:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L73)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Lets call it fromString
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 77 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9Bitv8Kmh3QPgTOKO:-NV9JDu57c7lBu5KUur7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L77)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why change to upperCase?

we should do something like this https://stackoverflow.com/a/37841094
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
*[`access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/47402#-NV81HvS35toCKV0g9Uf:-NV9LGn4ATO7YoY1dasO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/cc1862ead14767f99b91f761c382c84540023872/access-control/service/src/main/java/io/harness/accesscontrol/roles/api/RoleDTOMapper.java#L80)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Whats the need for this method?
</blockquote></details>

Done.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9BYg54SIxA3-tdyQm:-NV9V7yd9LiPDdKl7Qtr:b-7506gg) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L73)):*
<details><summary><i>Previously, ashishsanodia-harness (Ashish Sanodia) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not done yet

**Comment by ashishsanodia-harness** [comment]
*[`access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java` line 73 at r3](https://reviewable.io/reviews/harness/harness-core/47402#-NV9BYg54SIxA3-tdyQm:-NV9Y8M83WrXTSsvIuhP:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/97d0759a5524accf61bca99e237e48c0ea036893/access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api/RoleDTO.java#L73)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

This is not done yet
</blockquote></details>

Done.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47402#-:-NV9ao-3BimpBddN-eoO:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by ashishsanodia-harness** [comment]
trigger uts

**Pull request merged**
