### PR TITLE
feat: [CDS-43839]: Implementing the Dry Run Manifest Step Manager Side Changes

### PR DESCRIPTION
**Pull request by GoelPratyush99**
## Describe your changes
Implementing a New Dry Run Manifest step for Kubernetes and Native Helm swimlanes. The customers could not retrieve the rendered Kubernetes Manifest with the Harness variables templated in and leverage it before the Harness K8s apply. Now they store the rendered manifest yaml file as this variable "<+pipeline.stages.{Stage_Name}.spec.execution.steps.{Dry_Run_Manifest_id}.dryRunManifestYaml>".

Tech Spec: https://harness.atlassian.net/wiki/spaces/CDP/pages/21231601335/Tech+Spec+for+Kubernetes+Dry+Run+Step+NG

Automation: [https://github.com/wings-software/Automation/pull/4141](https://github.com/wings-software/Automation/pull/4141)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)

### CODE REVIEW

**Comment by GoelPratyush99** [comment]
TI-bootstrap: trigger ti0
TI-bootstrap1: trigger ti1
TI-bootstrap2: trigger ti2
TI-bootstrap3: trigger ti3
TI-bootstrap4: trigger ti4

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 24 of 41 files at r1, 15 of 18 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 42 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6qPS09_68y7jwie4:-NLe6qPS09_68y7jwie5:b-jogs3f) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java#L82)):*
> ```Java
> 
>     K8sDryRunManifestRequest k8sDryRunManifestRequest =
>         K8sDryRunManifestRequest.builder()
> ```

When inCanaryWorkflow is populated? and localOverride FF?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java` line 160 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe8VCYCP0bROLHNQMp:-NLe8VCYCP0bROLHNQMq:b-x5yagd) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java#L160)):*
> ```Java
>     K8sDryRunManifestResponse k8sDryRunManifestResponse =
>         (K8sDryRunManifestResponse) k8sTaskExecutionResponse.getK8sNGTaskResponse();
>     K8sDryRunManifestOutcome k8sDryRunManifestOutcome =
> ```

As discussed we would like to limit manifest size, please make sure to handle the case when k8sDryRunManifestResponse.getDryRunManifestYaml() is null or empty
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe4kWZ6zBj44NYt1Oc:-NLe4kWa63QNaytD9i6l:b5tzbc0) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L165)):*
> ```Java
>   }
> 
>   public TaskChainResponse queueK8sDryRunManifestTask(StepElementParameters stepElementParameters,
> ```

We can have 2 methods here instead:
  public TaskChainResponse queueK8sTask(StepElementParameters stepElementParameters, K8sDeployRequest k8sDeployRequest,
      Ambiance ambiance, K8sExecutionPassThroughData executionPassThroughData, TaskType taskType) {
     // Current implementation with just changing task type
}

  public TaskChainResponse queueK8sTask(StepElementParameters stepElementParameters, K8sDeployRequest k8sDeployRequest,
      Ambiance ambiance, K8sExecutionPassThroughData executionPassThroughData) {
  return queueK8sTask(stepElementParameters, k8sDeployRequest, ambiance, executionPassThroughData,  TaskType.K8S_COMMAND_TASK_NG)
}
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6XoNDMLKIBw7GOps:-NLe6XoO44xsFwAQqIHu:b-p2otp7) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java#L30)):*
> ```Java
>   @Expression(ALLOW_SECRETS) List<String> openshiftParamList;
>   @Expression(ALLOW_SECRETS) List<String> kustomizePatchesList;
>   K8sTaskType taskType;
> ```

can we just override getTaskType and provide static value. This request should be the case only for dry run manifest
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 571 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe7O4gESibeqxXFihq:-NLe7O4h2-1yLQcw7WCk:b3neobn) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L571)):*
> ```Java
>   SPG_MODULE_VERSION_INFO("Enable version information on module level", HarnessTeam.SPG),
>   CIE_HOSTED_VMS_WINDOWS("FF for enabling hosted builds for windows amd64", HarnessTeam.CI),
>   K8S_DRY_RUN_NG("Enable K8s Dry Run Step in NG", HarnessTeam.CDP);
> ```

Don't we need to add PM here?

**Review by GoelPratyush99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 44 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java` line 82 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6qPS09_68y7jwie4:-NLfNjS13gRdCo-XRDix:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java#L82)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

When inCanaryWorkflow is populated? and localOverride FF?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java` line 160 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe8VCYCP0bROLHNQMp:-NLfNkIq15XaJuJUj9jH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sDryRunManifestStep.java#L160)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

As discussed we would like to limit manifest size, please make sure to handle the case when k8sDryRunManifestResponse.getDryRunManifestYaml() is null or empty
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe4kWZ6zBj44NYt1Oc:-NLfNldODQtpcerO7LED:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/125-cd-nextgen/src/main/java/io/harness/cdng/k8s/K8sStepHelper.java#L165)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

We can have 2 methods here instead:
  public TaskChainResponse queueK8sTask(StepElementParameters stepElementParameters, K8sDeployRequest k8sDeployRequest,
      Ambiance ambiance, K8sExecutionPassThroughData executionPassThroughData, TaskType taskType) {
     // Current implementation with just changing task type
}

  public TaskChainResponse queueK8sTask(StepElementParameters stepElementParameters, K8sDeployRequest k8sDeployRequest,
      Ambiance ambiance, K8sExecutionPassThroughData executionPassThroughData) {
  return queueK8sTask(stepElementParameters, k8sDeployRequest, ambiance, executionPassThroughData,  TaskType.K8S_COMMAND_TASK_NG)
}
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6XoNDMLKIBw7GOps:-NLfNmLA1MwlCJVs5sCm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java#L30)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

can we just override getTaskType and provide static value. This request should be the case only for dry run manifest
</blockquote></details>

Done.
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 571 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe7O4gESibeqxXFihq:-NLfNpFEATOTJnP82uxe:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L571)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Don't we need to add PM here?
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 44 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6XoNDMLKIBw7GOps:-NLfUFEsDW41W8z1jjnl:b6wyonn) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java#L30)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you need to remove this field
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 571 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe7O4gESibeqxXFihq:-NLfUM8nAgV-ijm-lb7L:brnfavs) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L571)):*
<details><summary><i>Previously, GoelPratyush99 (Pratyush Goel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still no changes or is reviewable messing up?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 44 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java` line 30 at r4](https://reviewable.io/reviews/harness/harness-core/40423#-NLe6XoNDMLKIBw7GOps:-NLfUU7j1U0q9H43DJ8v:baw1pw3) ([raw file](https://github.com/harness/harness-core/blob/a8a101cff9be56b328ca853c1d1376d3d17b1738/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s/K8sDryRunManifestRequest.java#L30)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

you need to remove this field
</blockquote></details>

just to point it out (by error marked as done)

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 1 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 44 file(s) to review. 1 of 2 approvals obtained.

**Review by puthrayaharness — DISMISSED** [review]

**Review by achyuth-harness — DISMISSED** [review]
> Reviewed 29 of 41 files at r1, 11 of 18 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 7 of 11 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by acasian-harness** [comment]
trigger ti0

**Comment by GoelPratyush99** [comment]
TI-bootstrap: trigger ti0
TI-bootstrap1: trigger ti1
TI-bootstrap2: trigger ti2
TI-bootstrap3: trigger ti3
TI-bootstrap4: trigger ti4

**Comment by GoelPratyush99** [comment]
trigger ti0

**Comment by GoelPratyush99** [comment]
trigger ti1

**Comment by GoelPratyush99** [comment]
trigger ti2

**Comment by GoelPratyush99** [comment]
trigger ti3

**Comment by GoelPratyush99** [comment]
trigger ti4

**Comment by GoelPratyush99** [comment]
trigger ft2

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 18 of 41 files at r1, 11 of 18 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 7 of 11 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 3 of 3 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40423)* status: :shipit: complete! ✓

**Comment by GoelPratyush99** [comment]
trigger ft2

**Pull request merged**
