### PR TITLE
feat: [CDS-40134]: Support mergePR for AzureRepo connector

### PR DESCRIPTION
**Pull request by rohitk-h**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 4 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36011)

**Review by anshul-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/36011#-N8a6Phc1Csc3CzBaqZR:-N8a6PhdEMylRVshlSYR:b8kj1z6) ([raw file](https://github.com/harness/harness-core/blob/36d3a60bb975a502afc1b0a88d69377edff08989/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L109)):*
> ```Java
>     } catch (Exception e) {
>       log.error(
>           new StringBuilder("failed while merging PR using connector: ").append(gitApiTaskParams.getRepo()).toString(),
> ```

nit: Can we capitalize the first character

**Comment by rohitk-h** [comment]
trigger feature-build

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/36011#-N8a6Phc1Csc3CzBaqZR:-N8fECrC2QMhZDugxY-b:b-7ql1td) ([raw file](https://github.com/harness/harness-core/blob/36d3a60bb975a502afc1b0a88d69377edff08989/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L109)):*
<details><summary><i>Previously, anshul-harness (Anshul) wrote…</i></summary><blockquote>

nit: Can we capitalize the first character 
</blockquote></details>

fixed

**Review by anshul-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java` line 109 at r3](https://reviewable.io/reviews/harness/harness-core/36011#-N8a6Phc1Csc3CzBaqZR:-N8fFQ-W4blknzOJ3OXx:b-tz8s7m) ([raw file](https://github.com/harness/harness-core/blob/36d3a60bb975a502afc1b0a88d69377edff08989/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L109)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

This is not fixed

**Comment by GabeAboy** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java` line 138 at r5](https://reviewable.io/reviews/harness/harness-core/36011#-N8fGPdY5TwKhjxMhF-b:-N8fGPdY5TwKhjxMhF-c:b-qjz7mv) ([raw file](https://github.com/harness/harness-core/blob/c821378e822f582da916301be6e88d378aabea10/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L138)):*
> ```Java
>     if (url.contains("azure.com")) {
>       return AZURE_REPO_API_URL;
>     } else {
> ```

nit: We don't need the else statement

**Comment by GabeAboy** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoRestClient.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/36011#-N8fGbQN-7M48bsvbnGb:-N8fGbQN-7M48bsvbnGc:b-pul9pd) ([raw file](https://github.com/harness/harness-core/blob/c821378e822f582da916301be6e88d378aabea10/960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoRestClient.java#L29)):*
> ```Java
>       @Body Map<String, Object> parameters);
> 
>   // https://dev.azure.com/harness-gitops/_apis/git/repositories/2467c125-630d-4ea1-9878-eef40de3f646/pullrequests/1?api-version=5.0
> ```

nit: remove this comment

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 2 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java` line 138 at r5](https://reviewable.io/reviews/harness/harness-core/36011#-N8fGPdY5TwKhjxMhF-b:-N8fIbgJ6XKhBXkqM9Fb:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/c821378e822f582da916301be6e88d378aabea10/930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java#L138)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

nit: We don't need the else statement
</blockquote></details>

updated

**Comment by rohitk-h** [comment]
*[`960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoRestClient.java` line 29 at r5](https://reviewable.io/reviews/harness/harness-core/36011#-N8fGbQN-7M48bsvbnGb:-N8fHOM23YcQc7ZBIJB1:bss4dba) ([raw file](https://github.com/harness/harness-core/blob/c821378e822f582da916301be6e88d378aabea10/960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoRestClient.java#L29)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

nit: remove this comment
</blockquote></details>

Removing

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by GabeAboy — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 1 files at r2, 2 of 3 files at r4, 3 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

**Review by GabeAboy — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

**Review by anshul-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codebasehash

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 1 files at r2, 2 of 3 files at r4, 3 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36011)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger codebasehash

**Pull request merged**
