### PR TITLE
fix: [DEL-4039]: Handling null value in watcher while read

### PR DESCRIPTION
**Pull request by bharatgoelharness**
fix: [DEL-4039]: Handling null value in watcher while read

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

[DEL-4039]: https://harness.atlassian.net/browse/DEL-4039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33000)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33000)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]

**Comment by bharatgoelharness** [comment]
trigger pmd

**Comment by bharatgoelharness** [comment]
trigger codebasehash

**Comment by bharatgoelharness** [comment]
trigger messagecheck

**Pull request merged**
