### PR TITLE
[feat]: [CVNG-4018]: adding support for yaml 2.0

### PR DESCRIPTION
**Pull request by deepak-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)

### CODE REVIEW

**Comment by deepak-harness** [comment]
trigger ti1

**Comment by deepak-harness** [comment]
trigger ti1

**Comment by deepak-harness** [comment]
trigger ti0

**Comment by deepak-harness** [comment]
trigger ti0

**Comment by deepak-harness** [comment]
trigger ti2

**Comment by deepak-harness** [comment]
trigger ti3

**Comment by deepak-harness** [comment]
trigger ti4

**Comment by deepak-harness** [comment]
trigger ft1

**Comment by deepak-harness** [comment]
trigger ft2

**Comment by deepak-harness** [comment]
trigger ti3

**Comment by deepak-harness** [comment]
trigger ti0

**Comment by deepak-harness** [comment]
trigger ti0

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 3 of 4 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)* status: :shipit: complete! ✓

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 3 of 4 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/main/java/io/harness/serializer/CvNextGenRegistrars.java, line 70 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpIu3UE6MnG714FDoE:-MtpIu3UE6MnG714FDoF:b-egbzuo) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/300-cv-nextgen/src/main/java/io/harness/serializer/CvNextGenRegistrars.java#L70)):*
> ```Java
>       ImmutableList.<YamlSchemaRootClass>builder()
>           .add(YamlSchemaRootClass.builder()
>                    .entityType(EntityType.DEPLOYMENT_STEPS)
> ```

we should remove this now right? Do we still need DEPLOYMENT_STEPS?
___
*[300-cv-nextgen/src/test/resources/schema/DeploymentSteps/partialSchemaDTO.json, line 865 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpJD1IDZCjmc_eajPM:-MtpJD1IDZCjmc_eajPN:b1c64r5) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/300-cv-nextgen/src/test/resources/schema/DeploymentSteps/partialSchemaDTO.json#L865)):*
> ```JSON
>                 },
>                 "approvers": {
>                   "$ref": "#/definitions/cvng/Approvers"
> ```

This should only have verify step related schema now. I think after removing deployment steps from registration these steps should go away.
___
*[970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java, line 49 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpKDF81cIVt_pycolP:-MtpKDF81cIVt_pycolQ:b-8623k0) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L49)):*
> ```Java
>   String HARNESS_APPROVAL = "HarnessApproval";
>   String BARRIER = "Barrier";
>   String Verify = "Verify";
> ```

nit: It is surprising that this file is in commons. This logic is very specific to PMS. 
@brijeshdhakar

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)* status: :shipit: complete! ✓

___
*[300-cv-nextgen/src/test/resources/schema/DeploymentSteps/partialSchemaDTO.json, line 865 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpJD1IDZCjmc_eajPM:-MtpLsKj7MloRnMNzFGO:b8re8y7) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/300-cv-nextgen/src/test/resources/schema/DeploymentSteps/partialSchemaDTO.json#L865)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

This should only have verify step related schema now. I think after removing deployment steps from registration these steps should go away.
</blockquote></details>

I think component specific test for YAML should also fail. I think CI skipped it. Please try running them locally.

**Comment by brijeshdhakar** [comment]
___
*[970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java, line 49 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpKDF81cIVt_pycolP:-Mtq0puxDPB6HHfUdBzd:bweoyzb) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/970-ng-commons/src/main/java/io/harness/common/EntityTypeConstants.java#L49)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

nit: It is surprising that this file is in commons. This logic is very specific to PMS. 
@brijeshdhakar 
</blockquote></details>

This is used by entityTypes and these entityTypes can be of any service. Like K8S_CANARY_DEPLOY this constant is for the `K8S_CANARY_DEPLOY_STEP` entity type and its owned by CDNG. and it will be used in 125-cd-nextgen.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 12 of 15 files at r1, 3 of 4 files at r3, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)* status: 1 change requests. 1. unresolved discussions.

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048)* status: 1 change requests. 1. unresolved discussions. 

___
*[300-cv-nextgen/src/main/java/io/harness/serializer/CvNextGenRegistrars.java, line 70 at r5](https://reviewable.io/reviews/harness/harness-core/30048#-MtpIu3UE6MnG714FDoE:-Mtvw74S6Acrep9CJp1Q:b-cg7u6l) ([raw file](https://github.com/harness/harness-core/blob/d3de50cf30e245a5a958dcd6704088f9506817cb/300-cv-nextgen/src/main/java/io/harness/serializer/CvNextGenRegistrars.java#L70)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

we should remove this now right? Do we still need DEPLOYMENT_STEPS?
</blockquote></details>

nit: can we please create a jira to track this.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30048#-:-MtvwMEO0YoF_GjRQxSR:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
