### PR TITLE
fix: [CDS-34125]: Add awsConfigId to rollback config query

### PR DESCRIPTION
**Pull request by jelenaHarness**
This pr fixes an issue when using a templatized cloud provider. In this case, we'll pick up the last cloudFormationRollbackConfig, which causes deployment to the wrong AWS account. 

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32597)

### CODE REVIEW

**Comment by jelenaHarness** [comment]
trigger messagecheck

**Comment by tmacari-harness** [comment]
By editing cloud-provider  we can make it to point to different accounts, and there could be different cloudproviders pointing to the same account. Not sure if using awsconfigId would definitely fix the issue.

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32597)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32597)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32597)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32597)* status: :shipit: complete! ✓

**Pull request merged**
