### PR TITLE
[feat]:[PIE-7958]: Added new error handling for error code 429 for BB

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Added new error handling for error code 429 for BB

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43397)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG-zcQD3mhzwv4W2Zt:-NNG-zcQD3mhzwv4W2Zu:bffz1p9) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java#L63)):*
> ```Java
>       case 429:
>         throw NestedExceptionUtils.hintWithExplanationException(ScmErrorHints.RATE_LIMIT_REACHED,
>             ScmErrorExplanations.RATE_LIMIT, new ScmBadRequestException(errorMessage));
> ```

Why's different name of variable for ScmErrorHints and ScmErrorExplanations? It should be same ideally as its for same purpose.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG-zcQD3mhzwv4W2Zt:-NNG0B6a1fsgiUD2dO8G:b-tjesbf) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Why's different name of variable for ScmErrorHints and ScmErrorExplanations? It should be same ideally as its for same purpose.
</blockquote></details>

Also, I think the error message comes as empty in this case. Lets put a conditional check here that if error message is empty, we should put a default error message of rate limit.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG0S4x1QMQkYQ17ZIt:-NNG0S4x1QMQkYQ17ZIu:b-j2as2) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java#L28)):*
> ```Java
>   public static final String WRONG_REPO_OR_BRANCH = "The provided branch<BRANCH> or the repo<REPO> are invalid.";
> 
>   public static final String RATE_LIMIT = "The number of api requests for your account is too high.";
> ```

I think we can put something simple like "Rate limit reached on XYZ provider". Everyone understands rate limit so we don't need to be too naive here.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG1FXU3BKKxBAbtzh-:-NNG1FXU3BKKxBAbtzh0:bp6l10u) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java#L28)):*
> ```Java
> 
>   public static final String RATE_LIMIT_REACHED =
>       "Please check the number of requests, you have reached your account's rate limit for too many requests.";
> ```

Suggestion should be the following:
1) Please try and rotate your tokens used for GIT operations.
2) Please check your rate limits with your XYZ GIT provider

"reached your account's rate limit" is misleading as we aren't clear what account are we talking about here. We should be explicit that its their GIT provider which is faulty.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43397)* status: 44 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java` line 63 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG-zcQD3mhzwv4W2Zt:-NNGKDug6-IT9R8jRzW4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketCreateBranchScmApiErrorHandler.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also, I think the error message comes as empty in this case. Lets put a conditional check here that if error message is empty, we should put a default error message of rate limit.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG0S4x1QMQkYQ17ZIt:-NNGIp8F1aYwp2zFRgGC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorExplanations.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think we can put something simple like "Rate limit reached on XYZ provider". Everyone understands rate limit so we don't need to be too naive here.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java` line 28 at r2](https://reviewable.io/reviews/harness/harness-core/43397#-NNG1FXU3BKKxBAbtzh-:-NNGMIV_BYZoqGmN9bCZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b0023d1b38cd6a6f75aa8c919fa8ee1c76217e80/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/ScmErrorHints.java#L28)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Suggestion should be the following:
1) Please try and rotate your tokens used for GIT operations.
2) Please check your rate limits with your XYZ GIT provider

"reached your account's rate limit" is misleading as we aren't clear what account are we talking about here. We should be explicit that its their GIT provider which is faulty.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 21 of 44 files at r1, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43397)* status: 46 file(s) to review. 1 of 2 approvals obtained.

**Comment by adivishy1** [comment]
trigger messagecheck

**Pull request merged**
