### PR TITLE
techdebt: [SRM-14805]: Add metrics for state machine time taken, Add debug APIs to verify resource deletion ,  Add Uts to verify resources are deleted with slo deletion, and remove unnecessary DeleteByEntity Handler for Downtime Serviceand force deletion

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Describe your changes
Successful pipeline run for pr env: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/pipelines/PR_Harness_Env/executions/jLIMJSPsSPmIwKdgHLRG_w/pipeline?connectorRef=account.PRenvHarnessYamlGithub&repoName=ng-pr-manifests&branch=main&storeType=REMOTE&stage=jYsiSSh2QTercRNtg_Fncg

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)

### CODE REVIEW

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)* status: Some of the checks are too old. 21 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmKIpAfxB3yhPBuPq:-NWbmKIpAfxB3yhPBuPr:b-to51ys) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L23)):*
> ```Java
>   Boolean isProjectDeleted(ProjectParams projectParams);
> 
>   Boolean isSLODeleted(ProjectParams projectParams, String identifier);
> ```

nit: we can make it a bulk call.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmNiO3Hs29SWhvfEK:-NWbmNiO3Hs29SWhvfEL:b-gzv9su) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L29)):*
> ```Java
>   boolean forceDeleteSLO(ProjectParams projectParams, String sloIdentifier);
> 
>   boolean forceDeleteSLI(ProjectParams projectParams, String sliIdentifier);
> ```

nit: we can make it a bulk call
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmred-OChZbvBocJV:-NWbmred-OChZbvBocJW:be739r) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java#L170)):*
> ```Java
> 
>   @Override
>   public Boolean isProjectDeleted(ProjectParams projectParams) {
> ```

Shouldn't we make a ng-manager call and check if the project is deleted. If not then its ok. If yes. then check if all the resources are deleted or not.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java` line 200 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbn8YT2kJOpYpxZthV:-NWbn8YT2kJOpYpxZthW:b-cwzrfn) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java#L200)):*
> ```Java
>         monitoringSourcePerpetualTaskService.listByProjectParams(projectParams, Scope.PROJECT);
>     Preconditions.checkArgument(
>         monitoringSourcePerpetualTasks.isEmpty(), "MonitoringSourcePerpetualTasks are present in the database");
> ```

Can we make a similar class like delete we can iterate over collections and get data based on project params. rather than making a new method for each collection and calling them. Will be much more scalable to add new classes.. 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbnVZUE8blKXGO-6gD:-NWbnVZUE8blKXGO-6gE:b-1v7mnm) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java#L34)):*
> ```Java
>   String CALCULATION_FAILURE = "calculation_failure";
> 
>   String STATE_MACHINE_EXECUTION_TIME = "state_machine_execution_time";
> ```

Need to register the metric in resource path.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by Varsha-lalwani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)* status: 29 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmKIpAfxB3yhPBuPq:-NWfCt7D6IFYuBzUhurE:bmseirt) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L23)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

nit: we can make it a bulk call.
</blockquote></details>

the use case will be I think more for complete project or a single SLO 
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmNiO3Hs29SWhvfEK:-NWfD-r-6f41qYgBdw1n:b-pemco0) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L29)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

nit: we can make it a bulk call
</blockquote></details>

for delete it makes sense to have bulk, made that change
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java` line 170 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbmred-OChZbvBocJV:-NWfMj0y4I4GOYg3RvPc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DebugServiceImpl.java#L170)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Shouldn't we make a ng-manager call and check if the project is deleted. If not then its ok. If yes. then check if all the resources are deleted or not.
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/48298#-NWbnVZUE8blKXGO-6gD:-NWfMjUo1wRsTvHOvjuF:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/88f3acdff5f374d5beb6d45ec092154d141bfb24/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/metrics/CVNGMetricsUtils.java#L34)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Need to register the metric in resource path.
</blockquote></details>

Done.

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 14 of 21 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut7

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger uts

**Review by deepak-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r6, 2 of 9 files at r7, 4 of 6 files at r9, 3 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298)* status: Some of the checks are too old.

**Review by deepak-harness — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48298#-:-NXhppiiEPWdk0F63-op:bb6ywmx)* status: Some of the checks are too old.

**Comment by Varsha-lalwani** [comment]
trigger uts

**Comment by Varsha-lalwani** [comment]
trigger ut5

**Pull request merged**
