### PR TITLE
techdebt: [DEL-5690]: Move Log out of delegate jar

### PR DESCRIPTION
**Pull request by raghuAtWings**
## Describe your changes
In an effort to remove mongo dependency in delegate we are doing the following

1. Moved Log to 400-rest
2. created a dto with name Log in 930-delegate-tasks

**PR Tests Done**

1. end to end k8 deployment in cg
2. end to end shell script deployment in ng

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42302)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
Why AwsHelperService changes didn't catch their connection to Log class. 

> Reviewed 47 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42302#-:-NL5tUvGDVnh99GgJyP3:bd0gprm)* status: 5 file(s) to review. 0 of 1 approvals obtained.

**Review by sainath-b — APPROVED** [review]

**Review by sainath-b — APPROVED** [review]
> Reviewed 49 of 52 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42302)* status: :shipit: complete! ✓

**Review by acasian-harness — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42302)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 2173 at r3](https://reviewable.io/reviews/harness/harness-core/42302#-NLVKlOv8Umy3k78ddm0:-NLVKlOv8Umy3k78ddm1:b-jfr033) ([raw file](https://github.com/harness/harness-core/blob/502822cfd9f549d1c4bfaa4371ed0493c8e211d9/400-rest/src/test/resources/manager-kryo-registrations.txt#L2173)):*
> ```help
> 71100:software.wings.service.impl.ThirdPartyApiCallLog.ThirdPartyApiCallField
> 71101:software.wings.service.impl.ThirdPartyApiCallLog.FieldType
> 71102:software.wings.beans.dto.Log
> ```

is it safe to use same Id for new dto?



_Code quote:_
```help
71102
```

**Review by arvind-choudhary-h — COMMENTED** [review]
> Reviewed 49 of 52 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42302)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`400-rest/src/test/resources/manager-kryo-registrations.txt` line 2173 at r3](https://reviewable.io/reviews/harness/harness-core/42302#-NLVKlOv8Umy3k78ddm0:-NLcDgla2bm3hVYoeX7S:b1qxqe3) ([raw file](https://github.com/harness/harness-core/blob/502822cfd9f549d1c4bfaa4371ed0493c8e211d9/400-rest/src/test/resources/manager-kryo-registrations.txt#L2173)):*
<details><summary><i>Previously, arvind-choudhary-h (Arvind Choudhary) wrote…</i></summary><blockquote>

is it safe to use same Id for new dto?
</blockquote></details>

yes. it has to be same otherwise it will not be backward compatible. Thats why the class name is same, just package name is different

**Pull request merged**
