### PR TITLE
techdebt: [PIE-0]: Codebase hash generation fix

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
What was the issue?
There was a file we changed that was not used (both direct and indirect) in the delegate-module or delegate-service-app module, still the code-base hash changed.
We generated the dependency graph and validated that there was no direct/indirect dependency on that module wherein we changed the file.

What we found out while debugging?
When we generate kryo-dependencies for a particular module, we get `KryoRegistrar` interface too as part of the list. Now in our code logic for dependency hash generation, we have a check for kryo classes from where we use endsWith query. Since all our registrars had kryoRegistrar in the end, they were all being treated as if they got changed and hence the code base hash was getting updated even though the change was in an unrelated class not part of that service.

What is the fix?
We have added a fix to check  equality with simple name rather than the endsWith check with canonical name.

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)

### CODE REVIEW

**Review by bojanmicovic — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)* status: :shipit: complete! ✓

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)* status: 2 file(s) to review.

**Review by archit-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)* status: 2 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30298)* status: :shipit: complete! ✓

**Pull request merged**
