### PR TITLE
feat: [CDS-37291]: Add yaml updates for environment in deploymentStag…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…ePmsPlanCreatorV2

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/33315#-N2MpCmP98BtBMbfu7kt:-N2MpCmQ0z8Xsv-5KHar:becziqb) ([raw file](https://github.com/harness/harness-core/blob/8e783bb92d5724da2e91b146725510040ac7c229/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L229)):*
> ```Java
>                              .build())
>             .build());
>   }
> ```

can we add test for it ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 229 at r1](https://reviewable.io/reviews/harness/harness-core/33315#-N2MpCmP98BtBMbfu7kt:-N2PiaEU9bEvB2Nd6Olb:b-7tfmjp) ([raw file](https://github.com/harness/harness-core/blob/8e783bb92d5724da2e91b146725510040ac7c229/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L229)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can we add test for it ?
</blockquote></details>

added

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33315)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2Test.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/33315#-N2Pu2dlCHRwO8aS53yx:-N2Pu2dlCHRwO8aS53yy:bnqubwl) ([raw file](https://github.com/harness/harness-core/blob/7e32c04ae3068b75fe4cb462c2071c47145c0b08/125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2Test.java#L96)):*
> ```Java
>         getYamlFromPath("cdng/plan/environment/environmentPlanCreatorConfigWithInfra.yml");
>     EnvironmentPlanCreatorConfig environmentPlanCreatorConfig =
>         YamlUtils.read(envPlanCreatorConfigYaml, EnvironmentPlanCreatorConfig.class);
> ```

can be made into class variable so that multiple times deserialisation is not done



_Code quote:_
```Java
    String envPlanCreatorConfigYaml =
        getYamlFromPath("cdng/plan/environment/environmentPlanCreatorConfigWithInfra.yml");
    EnvironmentPlanCreatorConfig environmentPlanCreatorConfig =
        YamlUtils.read(envPlanCreatorConfigYaml, EnvironmentPlanCreatorConfig.class);
```

**Pull request merged**
