### PR TITLE
feat: [PLG-2006]: Add support for CCM version in release notes

### PR DESCRIPTION
**Pull request by neelam-harness**
## Describe your changes
1. Adding support for CCM version update in Release Notes
2. Refactoring existing code for CD version in Release Notes
More Details: https://harness.atlassian.net/wiki/spaces/GTM/pages/21346058344/Release+Notes+-+Service+standardization 

Tested the changes locally and saw the update in local mongoDB:
Screen Shot 2023-03-23 at 5 54 48 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45584)

### CODE REVIEW

**Review by pranil-harness — APPROVED** [review]

**Comment by neelam-harness** [comment]
trigger messagecheck

**Comment by neelam-harness** [comment]
trigger ut2

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45584)* status: 6 file(s) to review.

**Review by hitesharinga — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45584)* status: :shipit: complete! ✓

___
*[`.gitignore` line 80 at r1](https://reviewable.io/reviews/harness/harness-core/45584#-NRJWRmk2UMq1E_7FETu:-NRJWRmk2UMq1E_7FETv:bbnv4v9) ([raw file](https://github.com/harness/harness-core/blob/04b1f630a8731562ff6ed18a894483447d5348ec/.gitignore#L80)):*
> ```ignore
> .build-cleaner-index
> product/ci/scm/.idea
> pom.xml
> ```

Do we need this ?
___
*[`120-ng-manager/config.yml` line 145 at r1](https://reviewable.io/reviews/harness/harness-core/45584#-NRJWWMj7aPQXyZzXdMR:-NRJWWMj7aPQXyZzXdMS:bhcc9jp) ([raw file](https://github.com/harness/harness-core/blob/04b1f630a8731562ff6ed18a894483447d5348ec/120-ng-manager/config.yml#L145)):*
> ```YAML
> 
> pipelineServiceClientConfig:
>   baseUrl: http://localhost:12001/pipeline/api/
> ```

Can we revert this file. Not sure how devs are using this locally. 
___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java` line 296 at r1](https://reviewable.io/reviews/harness/harness-core/45584#-NRJWw5iBjYELSx8pjeh:-NRJWw5iBjYELSx8pjei:baelhm) ([raw file](https://github.com/harness/harness-core/blob/04b1f630a8731562ff6ed18a894483447d5348ec/120-ng-manager/src/main/java/io/harness/ng/NextGenApplication.java#L296)):*
> ```Java
>       log.warn("Shutdown hook, entering maintenance...");
>       MaintenanceController.forceMaintenance(false);
>     }));
> ```

Do we need this change

**Pull request closed without merging**
