### PR TITLE
feat: [IDP-987]: Add flag for scorecards when custom checks are deleted

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
1. Added flag for scorecards when custom check is deleted
2. Using custom flag to uniquely identify a check (To support GLOBAL_ACCOUNT)
3. Removed tags from CheckEntity
4. Optimised scorecard list API (Making use of single API to fetch all data)
5. Validate if checks are present before saving/updating scorecard 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51555)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 7 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51555)* status: 14 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 2424 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUcE2A5QkwRdw2ycPy:-NbUcE2B81JmtvCFH6qI:b-ob6udp) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/contracts/openapi/v1/openapi.yaml#L2424)):*
> ```YAML
>           x-stoplight:
>             id: bprjxwrnen0vj
>         checks_missing:
> ```

Just wondering - In the scorecard page we might want to show a user "Check 'ABC' is deleted". For this, we would have to return a list of deleted checks. Instead of a boolean flag
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUds8QEzokJ7dne10y:-NbUds8QEzokJ7dne10z:b-2sxmqf) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java#L52)):*
> ```Java
> 
>   @Override
>   public Response getCheck(String checkId, Boolean custom, String harnessAccount) {
> ```

Can we use primitive boolean?
Also nit: `isCustom` instead of `custom`



_Code quote:_
```Java
Boolean
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUh5VwAsRiGtfb-GLW:-NbUh5VwAsRiGtfb-GLX:bq8wb2h) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java#L68)):*
> ```Java
>       uniqueCheckIds.addAll(checkIds);
>     }
>     Map<String, CheckEntity> checkEntityMap =
> ```

The same check identifier can be present in customer accounts as well as global account based on the index we have. But I guess @sathish-soundarapandian is adding a prefix to default checks. So we should still be good here



_Code quote:_
```Java
Map<String, CheckEntity>
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51555)* status: 14 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/contracts/openapi/v1/openapi.yaml` line 2424 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUcE2A5QkwRdw2ycPy:-NbUtca53uVDE1eVW8yP:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/contracts/openapi/v1/openapi.yaml#L2424)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Just wondering - In the scorecard page we might want to show a user "Check 'ABC' is deleted". For this, we would have to return a list of deleted checks. Instead of a boolean flag
</blockquote></details>

done
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java` line 52 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUds8QEzokJ7dne10y:-NbUqLUa8UjdGPTSziyy:baoeyhc) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/src/main/java/io/harness/idp/scorecard/checks/resources/ChecksApiImpl.java#L52)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we use primitive boolean?
Also nit: `isCustom` instead of `custom`
</blockquote></details>

By default, open spec generates 'Boolean' type. we will not be able to change it
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java` line 68 at r3](https://reviewable.io/reviews/harness/harness-core/51555#-NbUh5VwAsRiGtfb-GLW:-NbUp2Na-tR3yZlKeybA:b3lfls) ([raw file](https://github.com/harness/harness-core/blob/e66e747cd15f39c40e87dce2a7e09c554d498239/idp-service/src/main/java/io/harness/idp/scorecard/scorecards/service/ScorecardServiceImpl.java#L68)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

The same check identifier can be present in customer accounts as well as global account based on the index we have. But I guess @sathish-soundarapandian is adding a prefix to default checks. So we should still be good here
</blockquote></details>

I have constructed the map key as a combination of accountId & checkId and later in the mapper we are filtering based on isCustom flag. So we should be fine even we have conflicts

**Review by vikyathharekal — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51555)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by mankrit-singh — DISMISSED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Comment by vigneswara-propelo** [comment]
trigger ut8

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut0

**Review by vikyathharekal — APPROVED** [review]

**Review by mankrit-singh — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
