### PR TITLE
feat: [CDS-42428]: support s3 artifact source for azure webapp

### PR DESCRIPTION
**Pull request by vlica-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Vulnerability 2 Vulnerabilities 
 * Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36963)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 343 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjI8i2DaeDjsFf-JjI:-NAjI8i2DaeDjsFf-JjJ:b-iw1uli) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L343)):*
> ```Java
>         return !(artifactOutcome instanceof ArtifactoryArtifactOutcome);
>       case AMAZON_S3_NAME:
>         return (artifactOutcome instanceof S3ArtifactOutcome);
> ```

nit: this can return true, S3 will always be package artifact type
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 444 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHAZZ8qMolG8ceVh8:-NAjHAZZ8qMolG8ceVh9:bd72w3d) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L444)):*
> ```Java
>                                                   .bucketName(s3ArtifactOutcome.getBucketName())
>                                                   .filePath(s3ArtifactOutcome.getFilePath())
>                                                   .primaryArtifact(s3ArtifactOutcome.isPrimaryArtifact())
> ```

why it does matter if it's primary artifact?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHEIG0f2TF4VljTyF:-NAjHEIG0f2TF4VljTyG:bp1es24) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L445)):*
> ```Java
>                                                   .filePath(s3ArtifactOutcome.getFilePath())
>                                                   .primaryArtifact(s3ArtifactOutcome.isPrimaryArtifact())
>                                                   .type(s3ArtifactOutcome.getType())
> ```

there is already source type, why we need another type here?
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHOgr7iqQe9RW2zjD:-NAjHOgr7iqQe9RW2zjE:b-j0mlgr) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java#L127)):*
> ```Java
>     List<DecryptableEntity> decryptableEntities = s3ArtifactConfig.getConnectorConfig().getDecryptableEntities();
>     if (isNotEmpty(decryptableEntities)) {
>       for (DecryptableEntity entity : decryptableEntities) {
> ```

decryption should be done automatically
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHVj41Bs2bVmGfbtg:-NAjHVj41Bs2bVmGfbth:boe971h) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java#L152)):*
> ```Java
>             String.format(DOWNLOAD_FROM_S3_EXPLANATION, artifactRequestDetails.getBucketName(),
>                 artifactRequestDetails.getFilePath()),
>             new ServerlessCommandExecutionException(
> ```

Why it's ServerlessCommandExecutionException?

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 444 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHAZZ8qMolG8ceVh8:-NAs67EsEObKYZ3wQeSs:bz73rwp) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L444)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

why it does matter if it's primary artifact?
</blockquote></details>

in our case it does not matter, just wanted to map all the info we have in the s3outcome, property removed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java` line 445 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHEIG0f2TF4VljTyF:-NAs6G9FETI0RyLAL_6V:b-4wwuul) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/125-cd-nextgen/src/main/java/io/harness/cdng/azure/webapp/AzureWebAppStepHelper.java#L445)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

there is already source type, why we need another type here?
</blockquote></details>

I agree, just wanted to map all the info we have in the s3outcome, property removed
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java` line 127 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHOgr7iqQe9RW2zjD:-NAs6WoKEATjxxIp0wNM:b-mw8cpf) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java#L127)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

decryption should be done automatically
</blockquote></details>

you are right, it's done earlier
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java` line 152 at r2](https://reviewable.io/reviews/harness/harness-core/36963#-NAjHVj41Bs2bVmGfbtg:-NAs6gT7C3yTTAtJ4ClF:bxmzbxj) ([raw file](https://github.com/harness/harness-core/blob/0b226dc01dfe8ab11968359925db812f773bcff5/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java#L152)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Why it's ServerlessCommandExecutionException?
</blockquote></details>

whoooh, my bad, I used an existing hint with this content, changed to custom exception

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java` line 141 at r4](https://reviewable.io/reviews/harness/harness-core/36963#-NAsQ8tF92Epc4DENTiE:-NAsQ8tF92Epc4DENTiF:b2lp1dt) ([raw file](https://github.com/harness/harness-core/blob/d4b135e5d67f9dc8c525d35e853e1c5d331720ab/930-delegate-tasks/src/main/java/io/harness/delegate/task/azure/artifact/AzureArtifactDownloadServiceImpl.java#L141)):*
> ```Java
>             String.format(DOWNLOAD_FROM_S3_EXPLANATION, artifactRequestDetails.getBucketName(),
>                 artifactRequestDetails.getFilePath()),
>             new AzureAppServicesDownloadS3ArtifactException(
> ```

I can see this is a runtime exception but is not handler later and I don't see why we would need to handle it later because you already provide hint & explanation. You can use AzureWebAppTaskException instead

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 1 of 8 files at r1, 1 of 5 files at r3, 4 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: :shipit: complete! ✓

**Review by abosii-harness — DISMISSED** [review]
> Reviewed 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 1 of 5 files at r3, 3 of 5 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963#-:-NAyPAlxEtco9QfDQYQi:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger ti4

**Comment by vlica-harness** [comment]
trigger ti3

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36963#-:-NAyUY9OEPvjEsuwEhiL:bnfp4nl)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger codebasehash

**Pull request merged**
