### PR TITLE
feat: [CDS-35475]: File Store Search: Investigate and implement APIs …

### PR DESCRIPTION
**Pull request by bojanmicovic**
…for New Filter dialog

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)

### CODE REVIEW

**Review by ivan-83 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 194 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00VC9JAOWfHKXdAAZj:-N00VC9JAOWfHKXdAAZk:byckkg7) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L194)):*
> ```Java
> 
>   @Override
>   public List<FileDTO> listFilesWithFilter(String accountIdentifier, String orgIdentifier, String projectIdentifier,
> ```

My concern here is, we could have more the 100 files listed(more files then supported by one page), hence i will go with pagination here. And add support for pagination on resource endpoint. 
___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java, line 221 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00Vir_9NFgu8hVuX3c:-N00Vir_9NFgu8hVuX3d:bzfucn7) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/FileStoreServiceImpl.java#L221)):*
> ```Java
>     criteria.and(NGFile.NGFiles.type).is(NGFileType.FILE);
> 
>     return fileStoreRepository.findAllAndSort(criteria, createSortByName(Sort.Direction.ASC))
> ```

Here findAllAndSort could be expensive, of course not now, we could have a lot of files in memory, hence i will try to leverage, groupBy and  projection from aggregation. If it is not doable we can go with this solution and improve query in the future. 



_Code quote:_
```Java
findAllAndSort
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/filter/FilesFilterPropertiesDTO.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00OM6_CscvAKcVGbc1:-N00OM6_CscvAKcVGbc2:bez41xk) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/dto/filestore/filter/FilesFilterPropertiesDTO.java#L31)):*
> ```Java
> @AllArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> @OwnedBy(DEL)
> ```

Minor - OwnedBy CDP



_Code quote:_
```Java
@OwnedBy(DEL)
```
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 229 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00QEwNDaL51Br2766m:-N00QEwOE0LEw2Cv4dF1:bf428wr) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L229)):*
> ```Java
>   public ResponseDTO<List<FileDTO>>
>   listFilesWithFilter(@Parameter(description = ACCOUNT_PARAM_MESSAGE) @QueryParam(
>                           ACCOUNT_KEY) @EntityIdentifier String accountIdentifier,
> ```

Minor -  remove @EntityIdentifier from account, or and project identifiers
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 233 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00QV85355YgPU1m4_o:-N00QV85355YgPU1m4_p:b-o39g5p) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L233)):*
> ```Java
>           allowBlank = true) String orgIdentifier,
>       @Parameter(description = PROJECT_PARAM_MESSAGE) @QueryParam(PROJECT_KEY) @EntityIdentifier(allowBlank = true)
>       String projectIdentifier, @QueryParam(NGResourceFilterConstants.FILTER_KEY) String filterIdentifier,
> ```

Minor - static imports FILTER_KEY and SEARCH_TERM_KEY
___
*[120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java, line 254 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00Qj-K9r4vAG7_0iTC:-N00Qj-K9r4vAG7_0iTD:bf428wr) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/ng/core/remote/FileStoreResource.java#L254)):*
> ```Java
>                        ACCOUNT_KEY) @EntityIdentifier String accountIdentifier,
>       @Parameter(description = ORG_PARAM_MESSAGE) @QueryParam(ORG_KEY) @EntityIdentifier(
>           allowBlank = true) String orgIdentifier,
> ```

Minor -  remove @EntityIdentifier from account, or and project identifiers
___
*[120-ng-manager/src/main/java/io/harness/repositories/filestore/FileStoreRepositoryCriteriaCreator.java, line 54 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00Sv8w7ga7fLdTBLN_:-N00Sv8w7ga7fLdTBLNa:bs6npx8) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/repositories/filestore/FileStoreRepositoryCriteriaCreator.java#L54)):*
> ```Java
> 
>     if (isNotEmpty(searchTerm)) {
>       criteria.orOperator(
> ```

Question, do we need andOperator here?
___
*[120-ng-manager/src/main/java/io/harness/repositories/filestore/FileStoreRepositoryCriteriaCreator.java, line 67 at r1](https://reviewable.io/reviews/harness/harness-core/32300#-N00RxTP3Zcl5xkNz0Ms:-N00RxTQ3ZFnB_HzkXlJ:b-83m54x) ([raw file](https://github.com/harness/harness-core/blob/5d75fb6adbf08f9b60874576655ed7a2515912eb/120-ng-manager/src/main/java/io/harness/repositories/filestore/FileStoreRepositoryCriteriaCreator.java#L67)):*
> ```Java
> 
>     if (filterProperties != null && !isEmpty(filterProperties.getTags())) {
>       criteria.and(Connector.ConnectorKeys.tags).in(TagMapper.convertToList(filterProperties.getTags()));
> ```

Minor - try to use NGFiles.tags

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/entities/NGFile.java, line 81 at r2](https://reviewable.io/reviews/harness/harness-core/32300#-N016JcT16Nfe0DOQXsl:-N016JcT16Nfe0DOQXsm:b-jcki5u) ([raw file](https://github.com/harness/harness-core/blob/09a3e5a8ce5c2e053d810c3c6bb9594fd1849b9a/120-ng-manager/src/main/java/io/harness/ng/core/entities/NGFile.java#L81)):*
> ```Java
>   String mimeType;
>   Long size;
>   @CreatedBy private String createdBy;
> ```

i don't see `createdAt` and `lastModifiedBy` `lastModifiedAt` properties. @ivan-83 in case of update, are we storing somewhere this kind of data?

**Review by ivan-83 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)* status: 5 file(s) to review.

**Review by ivan-83 — COMMENTED** [review]
> Reviewed 2 of 15 files at r3, 2 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)* status: 0 of 1 approvals obtained.

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300#-:-N07WApuAJ7BEz1jAcq3:bnfp4nl)* status: :shipit: complete! ✓

**Review by ivan-83 — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32300)* status: :shipit: complete! ✓

**Pull request merged**
