### PR TITLE
feat: [CDS-50125]: New api to support references for templates

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
New api to support references for templates

Previous api used to fetch results with 1 fqns, but it is possible to have 2 different fqns present for a single template entity, therefore we are introducing this new api 
2 fqns are as follows:-
*  accId/OrgId/ProjId/templateId/versionLabel/
*  accId/OrgId/ProjId/templateId/__STABLE__/

Response :- 
{
    "status": "SUCCESS",
    "data": [
        {
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "referredEntity": {
                "type": "Template",
                "entityRef": {
                    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
                    "orgIdentifier": "default",
                    "projectIdentifier": "njh",
                    "identifier": "rtrt",
                    "versionLabel": "__STABLE__",
                    "repoIdentifier": null,
                    "branch": null,
                    "isDefault": true,
                    "scope": "project",
                    "default": true
                },
                "name": ""
            },
            "referredByEntity": {
                "type": "Template",
                "entityRef": {
                    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
                    "orgIdentifier": "default",
                    "projectIdentifier": "njh",
                    "identifier": "cvcv",
                    "versionLabel": "cv",
                    "repoIdentifier": null,
                    "branch": null,
                    "isDefault": true,
                    "scope": "project",
                    "default": true
                },
                "name": "cvcv"
            },
            "detail": null,
            "createdAt": 1675075748603
        },
        {
            "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
            "referredEntity": {
                "type": "Template",
                "entityRef": {
                    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
                    "orgIdentifier": "default",
                    "projectIdentifier": "njh",
                    "identifier": "rtrt",
                    "versionLabel": "r",
                    "repoIdentifier": null,
                    "branch": null,
                    "isDefault": true,
                    "scope": "project",
                    "default": true
                },
                "name": ""
            },
            "referredByEntity": {
                "type": "Template",
                "entityRef": {
                    "accountIdentifier": "kmpySmUISimoRrJL6NL73w",
                    "orgIdentifier": "default",
                    "projectIdentifier": "njh",
                    "identifier": "cvcv",
                    "versionLabel": "gdfg",
                    "repoIdentifier": null,
                    "branch": null,
                    "isDefault": true,
                    "scope": "project",
                    "default": true
                },
                "name": "cvcv"
            },
            "detail": null,
            "createdAt": 1675064167476
        }
    ],
    "metaData": null,
    "correlationId": "c11bb67e-ec08-4b2f-85f6-0e867a4fe316"
}

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/resource/EntitySetupUsageResource.java` line 98 at r4](https://reviewable.io/reviews/harness/harness-core/43150#-NN5oS0N4GnWqR89wpUd:-NN5oS0N4GnWqR89wpUe:bunbaal) ([raw file](https://github.com/harness/harness-core/blob/f501dd9d578e1b7308bbe8f1a2830189a979158d/120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/resource/EntitySetupUsageResource.java#L98)):*
> ```Java
>       @QueryParam(NGResourceFilterConstants.SIZE_KEY) @DefaultValue("100") int size,
>       @NotEmpty @QueryParam(NGCommonEntityConstants.ACCOUNT_KEY) String accountIdentifier,
>       @QueryParam(REFERRED_ENTITY_FQN) String referredEntityFQN,
> ```

lets call with referredEntityFQN1

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 624 at r4](https://reviewable.io/reviews/harness/harness-core/43150#-NN5ofEa1R4eRRHsOVOc:-NN5ofEa1R4eRRHsOVOd:b-rxcrm4) ([raw file](https://github.com/harness/harness-core/blob/f501dd9d578e1b7308bbe8f1a2830189a979158d/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L624)):*
> ```Java
>       @Parameter(description = TEMPLATE_PARAM_MESSAGE) @PathParam(
>           "templateIdentifier") @ResourceIdentifier String templateIdentifier,
>       @Parameter(description = "Version Label") @QueryParam(NGCommonEntityConstants.VERSION_LABEL_KEY)
> ```

should we get a query param if the version is stable ?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 624 at r4](https://reviewable.io/reviews/harness/harness-core/43150#-NN5ofEa1R4eRRHsOVOc:-NN6NMeW63F3RK0MREkw:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/f501dd9d578e1b7308bbe8f1a2830189a979158d/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L624)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we get a query param if the version is stable ?
</blockquote></details>

Done.

**Review by utkarshchoubey-harness — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 10 files at r2, 1 of 1 files at r3, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150#-:-NN6NOER4nJ8hFMoLwW5:bnfp4nl)* status: 13 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Comment by utkarshchoubey-harness** [comment]
trigger ft1

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1145 at r6](https://reviewable.io/reviews/harness/harness-core/43150#-NNBTvrHBqIFnNtN1Zta:-NNBTvrHBqIFnNtN1Ztb:b-lrq3wl) ([raw file](https://github.com/harness/harness-core/blob/5489ebf2f3b611a97fac384deafc0e1178df0ddb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1145)):*
> ```Java
>     } else {
>       referredEntities = NGRestUtils
>                              .getResponse(entitySetupUsageClient.listAllEntityUsageWith2Fqns(
> ```

we should use the older method here



_Code quote:_
```Java
listAllEntityUsageWith2Fqns
```

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1153 at r6](https://reviewable.io/reviews/harness/harness-core/43150#-NNBUFai8FnwUpTVIjPS:-NNBUFai8FnwUpTVIjPT:b-375ff6) ([raw file](https://github.com/harness/harness-core/blob/5489ebf2f3b611a97fac384deafc0e1178df0ddb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1153)):*
> ```Java
> 
>   private String createFqnForTemplate(String accountIdentifier, String orgIdentifier, String projectIdentifier,
>       String templateIdentifier, String versionLabel) {
> ```

Lets use "io.harness.utils.FullyQualifiedIdentifierHelper#getFullyQualifiedIdentifier"

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 10 files at r2, 6 of 8 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: 13 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1145 at r6](https://reviewable.io/reviews/harness/harness-core/43150#-NNBTvrHBqIFnNtN1Zta:-NNBuwAzC7JirKIz8jGa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5489ebf2f3b611a97fac384deafc0e1178df0ddb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1145)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we should use the older method here
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1153 at r6](https://reviewable.io/reviews/harness/harness-core/43150#-NNBUFai8FnwUpTVIjPS:-NNBuwoOAr1tGeRS-Ppf:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/5489ebf2f3b611a97fac384deafc0e1178df0ddb/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1153)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets use "io.harness.utils.FullyQualifiedIdentifierHelper#getFullyQualifiedIdentifier"
</blockquote></details>

Done.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 2 of 10 files at r2, 1 of 1 files at r3, 4 of 8 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: 5 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43150)* status: :shipit: complete! ✓

**Pull request merged**
