### PR TITLE
feat: [PL-29434]: Changing default boolean to true

### PR DESCRIPTION
**Pull request by boopesh007**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39641)

### CODE REVIEW

**Comment by boopesh007** [comment]
trigger messagecheck

**Review by abhinav-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39641)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3h3Kt2ufwWporEqps:-NG3h3Kt2ufwWporEqpt:blzneqq) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java#L30)):*
> ```Java
> public class EmailConfig extends NotificationSettingConfig {
>   String groupEmail;
>   boolean sendEmailToAllUsers = true;
> ```

Can you test this making a object via builder - i am not sure this works
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3hABF1EhXUFK3BPf5:-NG3hABF1EhXUFK3BPf6:b-liyhoi) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L46)):*
> ```Java
>   @Override
>   public void migrate() {
>     log.info("{}} starts ...", DEBUG_LINE);
> ```

extra brace
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3lEJbAni4ibguitsj:-NG3lEJc1llP6Jq2rLVt:by6tspi) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L58)):*
> ```Java
> 
>   private void addSendNotificationBoolean(UserGroup userGroup) {
>     log.info("UserGroup name is {}", userGroup.getIdentifier());
> ```

this is not enough push more details in log
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3liHA9mhkzlEP5BRb:-NG3liHB4C_luiCq_S73:b-rvvvdz) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L61)):*
> ```Java
>     try {
>       if (userGroup.getNotificationConfigs().size() > 0) {
>         List<NotificationSettingConfig> notificationConfigs = userGroup.getNotificationConfigs();
> ```

use stream/forEach
___
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3kVTa5Z1i5C5_glE9:-NG3kVTa5Z1i5C5_glEA:b-my7plf) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L63)):*
> ```Java
>         List<NotificationSettingConfig> notificationConfigs = userGroup.getNotificationConfigs();
>         for (NotificationSettingConfig notificationSettingConfig : notificationConfigs) {
>           if (notificationSettingConfig.getType().equals(NotificationChannelType.EMAIL)) {
> ```

flip equals

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3hABF1EhXUFK3BPf5:-NG5Irl44EOJft1VZqO1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L46)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

extra brace
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 58 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3lEJbAni4ibguitsj:-NG5Itsb9VLucKggDiG4:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L58)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

this is not enough push more details in log
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 61 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3liHA9mhkzlEP5BRb:-NG5K0xH7FKU6nOSMrH8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L61)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

use stream/forEach
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java` line 63 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3kVTa5Z1i5C5_glE9:-NG5Kl8S2nBmw_MOrljJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/migration/UserGroupNotificationConfigMigration.java#L63)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

flip equals
</blockquote></details>

Done.

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3h3Kt2ufwWporEqps:-NG5NAvY4L2iUPQ7Qhjk:b-t5cb71) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java#L30)):*
<details><summary><i>Previously, abhinav-harness (Abhinav Singh) wrote…</i></summary><blockquote>

Can you test this making a object via builder - i am not sure this works
</blockquote></details>

Can you elaborate on this @abhinav-harness ?

**Comment by boopesh007** [comment]
*[`123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java` line 30 at r1](https://reviewable.io/reviews/harness/harness-core/39641#-NG3h3Kt2ufwWporEqps:-NG5f7GI9DjWwBShOQcw:bodgdmx) ([raw file](https://github.com/harness/harness-core/blob/9f57208aedfd44921a076c1c484478f8602d85d2/123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java#L30)):*
<details><summary><i>Previously, boopesh007 (Boopesh Shanmugam) wrote…</i></summary><blockquote>

Can you elaborate on this @abhinav-harness ?
</blockquote></details>

Synced and added a test case for the same.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39641)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39641)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39641#-:-NGAMZ_i1CRqC4fRboE1:bnfp4nl)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by boopesh007** [comment]
trigger messagecheck

**Comment by boopesh007** [comment]
trigger messagecheck

**Pull request merged**
