### PR TITLE
feat: [CDS-76089]: support post prod rollback for running executions

### PR DESCRIPTION
**Pull request by Y0709**
Context : For post prod rollback of running exections we were not properly forming the yaml for the rollback pipeline with parallel and strategy in the pipelines and also we were encountering in the issue that when rolling back a running execution it was converting all the planNodes to identity nodes for the running executions resulting in stuck executions . This issue was fixed in https://github.com/harness/harness-core/pull/51652. 

In this pr we are basically fixing the yaml formation 

Testing done 

1) Normal pipeline rollback
2) Post prod rollback with all stages in series while running as well as after completion
3) Post prod rollback for parallel stages while running as well as after completion
4) Post prod rollback with strategy in series stages and rolling back strategy and non strategy stage while running as well as after completion
5) Post prod rollback with strategy on a parallel stage and rolling back strategy and non strategy stage while running as well as after completion
6) Post prod rollback on multi svc and env pipeline while running and after completion

Case 1
Screenshot 2023-08-29 at 10 24 48 AM

Case 2
Screenshot 2023-08-29 at 10 26 07 AM

Screenshot 2023-08-29 at 10 26 22 AM

Case 3

Screenshot 2023-08-29 at 10 27 53 AM

Screenshot 2023-08-29 at 10 28 04 AM

Case 4

Screenshot 2023-08-29 at 10 30 20 AM

Screenshot 2023-08-29 at 10 30 30 AM

Case 5 and Case 6 (same as multi svc/infra also use strategy

Screenshot 2023-08-29 at 10 31 30 AM

Screenshot 2023-08-29 at 10 31 48 AM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51518)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger ut7

**Comment by Y0709** [comment]
trigger uts

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 5 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51518)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java` line 119 at r5](https://reviewable.io/reviews/harness/harness-core/51518#-NczjEm4A_9WnFeLM-IG:-NczjEm4A_9WnFeLM-IH:b-73o8di) ([raw file](https://github.com/harness/harness-core/blob/9b9a499a37eda3125cf75b8c78d65ec3a2b67748/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java#L119)):*
> ```Java
>   String transformProcessedYamlForPostExecutionRollbackMode(String processedYaml, String originalPlanExecutionId) {
>     List<String> executedStages = new ArrayList<>();
>     List<NodeExecution> nodeExecutions = nodeExecutionService.fetchStageExecutions(originalPlanExecutionId);
> ```

can you use projection here? to get only identifier and status
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/51518#-NczkhbLDUv-MvYM8EnK:-NczkhbLDUv-MvYM8EnL:b-pk6si) ([raw file](https://github.com/harness/harness-core/blob/9b9a499a37eda3125cf75b8c78d65ec3a2b67748/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RollbackModeYamlTransformer.java#L147)):*
> ```Java
>         handleSerialStage(currentNode, executedStageIds, reversedStages);
>       } else {
>         handleParallelStagesForPostExecutionRollback(currentNode, executedStageIds, reversedStages);
> ```

we should return the value rather than updating in same list passed in params, as its difficult to read

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51518)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 4 of 5 files at r2, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51518)* status: :shipit: complete! ✓

**Comment by Y0709** [comment]
trigger messagecheck, review

**Comment by Y0709** [comment]
trigger ut0, ut1,ut2

**Pull request merged**
