### PR TITLE
fix: [PIE-3963]: Fix in interrupt monitor to abort the stuck executions

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33882)

### CODE REVIEW

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33882)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33882)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33882)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/33882#-N3cunE75-nvJ9giUxOT:-N3cunE86MP58JyXTxua:b-199k56) ([raw file](https://github.com/harness/harness-core/blob/30a3929e1337fcbb5edbd6529a617dbb361ef5c1/870-orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L137)):*
> ```Java
>         forceTerminate(
>             interrupt, nodeExecutions, nodeExecutions.stream().map(NodeExecution::getUuid).collect(Collectors.toSet()));
>         interruptService.markProcessedForceful(interrupt.getUuid(), PROCESSED_UNSUCCESSFULLY, true);
> ```

This should be processed successfully



_Code quote:_
```Java
PROCESSED_UNSUCCESSFULLY
```

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33882)* status: :shipit: complete! ✓

___
*[`870-orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java` line 137 at r1](https://reviewable.io/reviews/harness/harness-core/33882#-N3cunE75-nvJ9giUxOT:-N3d3ZIX-N3WQKBR-bK9:b-d2m7tv) ([raw file](https://github.com/harness/harness-core/blob/30a3929e1337fcbb5edbd6529a617dbb361ef5c1/870-orchestration/src/main/java/io/harness/engine/interrupts/InterruptMonitor.java#L137)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

This should be processed successfully
</blockquote></details>

discussed offline

**Pull request merged**
