### PR TITLE
feat: [cds-53715]: Added appendInputSetValidator in applyTemplates api

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added appendInputSetValidator param in applyTemplates api

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44142)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44142)* status: 16 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/44142#-NOnCXYQ3OYK3YCr7YsT:-NOnCXYQ3OYK3YCr7YsU:bopyc2j) ([raw file](https://github.com/harness/harness-core/blob/fdd52c39f748f169edc763f2f683f42f8aeb2662/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L66)):*
> ```Java
>                     customNGSecretManagerConfigDTO.getOrgIdentifier(),
>                     customNGSecretManagerConfigDTO.getProjectIdentifier(), null, null, null, BOOLEAN_FALSE_VALUE,
>                     TemplateApplyRequestDTO.builder().originalEntityYaml(yaml).build(), true))
> ```

shouldnt default be false and only be made true for pipelines only?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44142)* status: 16 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 66 at r1](https://reviewable.io/reviews/harness/harness-core/44142#-NOnCXYQ3OYK3YCr7YsT:-NOnD1oy40ut7xAUOY0M:bkiijqm) ([raw file](https://github.com/harness/harness-core/blob/fdd52c39f748f169edc763f2f683f42f8aeb2662/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L66)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

shouldnt default be false and only be made true for pipelines only?
</blockquote></details>

yes makes sense, setting as false

**Review by archit-harness — DISMISSED** [review]
> Reviewed 7 of 20 files at r1, 4 of 5 files at r2, 6 of 8 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44142)* status: :shipit: complete! ✓

**Review by tchaurasiya — DISMISSED** [review]
> Reviewed 9 of 20 files at r1, 4 of 5 files at r2, 6 of 8 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44142)* status: :shipit: complete! ✓

**Comment by utkarshchoubey-harness** [comment]
trigger ti0

**Pull request merged**
