### PR TITLE
fix: [PIE-8696]: add regex for allowing only runtime input in when

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Issue:** We do not have support for default, allowed values and execution time input for when as runtime input from backend but while saving yaml, user is able to save it with default, allowed values and execution time input.

**Changes:** The reason for this is that we are using SupportedPossibleFieldTypes.runtime for when whose regex pattern includes allowed values, default, and execution time input. So, now, we are using a different supported field type with only <+input> in regex.

**Impact:** Now, user won't be able to save when as .allowedValues(), default or execution time input in the pipeline yaml.

Is the change backward compatible? **Yes**

**Testing:** Tested the behavior in local.

Screenshots of the behavior:

Screenshot 2023-03-03 at 11 48 36 AM

Screenshot 2023-03-03 at 11 48 52 AM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44593)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44593)* status: 25 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 10 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44593)* status: Waiting on team(s): sto.

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44593#-:-NPacPhH0xWI7m2Ir-LK:bnfp4nl)* status: Waiting on team(s): sto.

**Review by r0610205 — APPROVED** [review]

**Review by r0610205 — APPROVED** [review]
> Reviewed 10 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44593)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 10 of 25 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44593)* status: :shipit: complete! ✓

**Pull request merged**
