### PR TITLE
feat: [CDS-41838]: ServiceNow Import Set Step

### PR DESCRIPTION
**Pull request by naman-goenka**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 17 Issues 
* Vulnerability 5 Vulnerabilities 
 * Code issue 12 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37087)

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 4 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: 49 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java` line 75 at r1](https://reviewable.io/reviews/harness/harness-core/37087#-NBLVOEx8Al2_2VaX3P_:-NBLVOEyAMl9mUq0URWj:b-9xdp95) ([raw file](https://github.com/harness/harness-core/blob/2118af23e570317f8eba69f645518cc8f4a39755/120-ng-manager/src/main/java/io/harness/ng/servicenow/resources/ServiceNowResource.java#L75)):*
> ```Java
>   @GET
>   @Path("stagingTable")
>   @ApiOperation(value = "Get serviceNow staging tables", nickname = "getServiceNowStagingTables")
> ```

@hidden annotation until testing is complete
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/servicenow/resources/service/ServiceNowResourceServiceImpl.java` line 122 at r1](https://reviewable.io/reviews/harness/harness-core/37087#-NBLWEvG26jwX3Fa-Rxy:-NBLWEvG26jwX3Fa-Rxz:b-do3n2s) ([raw file](https://github.com/harness/harness-core/blob/2118af23e570317f8eba69f645518cc8f4a39755/125-cd-nextgen/src/main/java/io/harness/cdng/servicenow/resources/service/ServiceNowResourceServiceImpl.java#L122)):*
> ```Java
>   @Override
>   public List<ServiceNowStagingTable> getStagingTableList(IdentifierRef connectorRef, String orgId, String projectId) {
>     ServiceNowTaskNGParametersBuilder parametersBuilder =
> ```

We can just make task params changes in a separate PR and merge them to avoid kryo issues with older delegates

**Review by hingerabhinav — CHANGES_REQUESTED** [review]
> Reviewed 13 of 53 files at r1, 17 of 34 files at r3, 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: 37 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 603 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZ_fDsBJkoZRoR90KB:-NCZ_fDwCFeWB7083d1U:b-c0dujb) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L603)):*
> ```Java
>         importDataJsonMap =
>             JsonUtils.asObject(serviceNowTaskNGParameters.getImportData(), new TypeReference<Map<String, String>>() {});
>       } catch (Exception ex) {
> ```

can we catch specific exception if the intended error message is invalid json?
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 447 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZbp1yEGNjd9PiQsi2:-NCZbp1yEGNjd9PiQsi3:b7t0t0) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L447)):*
> ```Java
>   AZURE_WEBAPP_NG_S3_ARTIFACTS(
>       "UI FF to enable AWS S3 as an artifact source option for Azure Web App NG", HarnessTeam.CDP),
>   SERVICENOW_IMPORT_SET_NG("Enable ServiceNow Import Set Step", HarnessTeam.CDC);
> ```

 need to follow naming conventions for FF
___
*[`970-api-services-beans/src/main/java/io/harness/servicenow/ServiceNowUtils.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZcB5hB5GGuelwdVTM:-NCZcB5hB5GGuelwdVTN:by5tbkk) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/970-api-services-beans/src/main/java/io/harness/servicenow/ServiceNowUtils.java#L43)):*
> ```Java
>   }
> 
>   public String prepareTicketUrlFromTicketIdV2(String baseUrl, String ticketId, String ticketType) {
> ```

nit: we can reuse the same method? if not, can we make sure older code uses this method as well

**Comment by naman-goenka** [comment]
> > Reviewed 13 of 53 files at r1, 17 of 34 files at r3, 2 of 11 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)_ status: 37 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java` line 603 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZ_fDsBJkoZRoR90KB:-NCZ_fDwCFeWB7083d1U:b-c0dujb) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/930-delegate-tasks/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNgHelper.java#L603)):_
> 
> > ```java
> >         importDataJsonMap =
> >             JsonUtils.asObject(serviceNowTaskNGParameters.getImportData(), new TypeReference<Map<String, String>>() {});
> >       } catch (Exception ex) {
> > ```
> 
> can we catch specific exception if the intended error message is invalid json?
> We are having generic exception from utility itself
```
  @JsonDeserialize
  public static <T> T asObject(String jsonString, TypeReference<T> valueTypeRef, ObjectMapper objectMapper) {
    try {
      return objectMapper.readValue(jsonString, valueTypeRef);
    } catch (Exception exception) {
      throw new RuntimeException(exception);
    }
  }
```
> _[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 447 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZbp1yEGNjd9PiQsi2:-NCZbp1yEGNjd9PiQsi3:b7t0t0) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L447)):_
> 
> > ```java
> >   AZURE_WEBAPP_NG_S3_ARTIFACTS(
> >       "UI FF to enable AWS S3 as an artifact source option for Azure Web App NG", HarnessTeam.CDP),
> >   SERVICENOW_IMPORT_SET_NG("Enable ServiceNow Import Set Step", HarnessTeam.CDC);
> > ```
> 
> need to follow naming conventions for FF
> sure will change it 
>
> _[`970-api-services-beans/src/main/java/io/harness/servicenow/ServiceNowUtils.java` line 43 at r3](https://reviewable.io/reviews/harness/harness-core/37087#-NCZcB5hB5GGuelwdVTM:-NCZcB5hB5GGuelwdVTN:by5tbkk) ([raw file](https://github.com/harness/harness-core/blob/c5c3ab67da166aa52032ac8d001490ad06781350/970-api-services-beans/src/main/java/io/harness/servicenow/ServiceNowUtils.java#L43)):_
> 
> > ```java
> >   }
> > 
> >   public String prepareTicketUrlFromTicketIdV2(String baseUrl, String ticketId, String ticketType) {
> > ```
> 
> nit: we can reuse the same method? if not, can we make sure older code uses this method as well
> I intended to do this for the purpose of backward compatibility, we can shift to V2 after sometime.

**Review by puthrayaharness — DISMISSED** [review]
> Reviewed 24 of 53 files at r1, 16 of 34 files at r3, 10 of 11 files at r4, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: 1 change requests. 1. unresolved discussions.

**Comment by naman-goenka** [comment]
trigger codebasehash

**Review by hingerabhinav — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: :shipit: complete! ✓

**Comment by naman-goenka** [comment]
trigger codebasehash

**Comment by naman-goenka** [comment]
trigger codebasehash

**Comment by naman-goenka** [comment]
trigger codebasehash

**Comment by naman-goenka** [comment]
trigger codebasehash

**Review by puthrayaharness — APPROVED** [review]
> Reviewed 4 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: :shipit: complete! ✓

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 10 of 53 files at r1, 10 of 34 files at r3, 8 of 11 files at r4, 11 of 17 files at r5, 4 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: :shipit: complete! ✓

**Comment by puthrayaharness** [comment]
trigger codebasehash

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 23 of 53 files at r1, 16 of 34 files at r3, 10 of 11 files at r4, 11 of 17 files at r5, 4 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: :shipit: complete! ✓

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 23 of 53 files at r1, 16 of 34 files at r3, 10 of 11 files at r4, 11 of 17 files at r5, 4 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37087)* status: :shipit: complete! ✓

**Pull request merged**
