### PR TITLE
feat: [PL-40597]: make error message clear when jwt token has expired

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes
Earlier when the token has expired for an invite we where giving an error message "We couldn’t find an invitation matching the email address you entered. Please search your email for an invitation from Harness or contact your admin." Which was miss leading for user.
Now we have changed it to give the message suggesting expiration of the invite that is "This invitation URL has expired. Please request for a new invitation from your admin."

Tested for:
-> When the token is invalid
-> when the token has expired
-> when token is valid
## Checklist
- [ ] I've 

https://github.com/harness/harness-core/assets/112424209/f13bb864-c6ef-47db-84d7-cb1f78806b79

documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51558)

### CODE REVIEW

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 578 at r2](https://reviewable.io/reviews/harness/harness-core/51558#-NbXm45501wi9B29bkuV:-NbXm45501wi9B29bkuW:b-e1nk9u) ([raw file](https://github.com/harness/harness-core/blob/4b14913d41c13647f17f97f1854a3944efa45ed2/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L578)):*
> ```Java
>     } catch (ExpiredTokenException e) {
>       throw new ExpiredTokenException(TOKEN_EXPIRED, WingsException.USER);
>     } catch (Exception e) {
> ```

minor: Should this be `catch (InvalidRequestException e) {` ? 



_Code quote:_
```Java
} catch (Exception e) {
```

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 581 at r2](https://reviewable.io/reviews/harness/harness-core/51558#-NbXm_fb8daDAkLMUpXK:-NbXm_fb8daDAkLMUpXL:b-jin8mx) ([raw file](https://github.com/harness/harness-core/blob/4b14913d41c13647f17f97f1854a3944efa45ed2/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L581)):*
> ```Java
>       log.error("Invalid invite JWT token", e);
>     }
>     if (!inviteIdOptional.isPresent()) {
> ```

nit: can replace by `inviteIdOptional.isEmpty()` 



_Code quote:_
```Java
if (!inviteIdOptional.isPresent()) {
```

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51558)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahibaCCM** [comment]
> _[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 578 at r2](https://reviewable.io/reviews/harness/harness-core/51558#-NbXm45501wi9B29bkuV:-NbXm45501wi9B29bkuW:b-e1nk9u) ([raw file](https://github.com/harness/harness-core/blob/4b14913d41c13647f17f97f1854a3944efa45ed2/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L578)):_
> 
> > ```java
> >     } catch (ExpiredTokenException e) {
> >       throw new ExpiredTokenException(TOKEN_EXPIRED, WingsException.USER);
> >     } catch (Exception e) {
> > ```
> 
> minor: Should this be `catch (InvalidRequestException e) {` ?
> 
> _Code quote:_
> 
> ```java
> } catch (Exception e) {
> ```

We have changed V2 to through InvalidTokenException instead of InvalidRequestException ; we can make it specific.

**Comment by pbarapatre10** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java` line 578 at r2](https://reviewable.io/reviews/harness/harness-core/51558#-NbXm45501wi9B29bkuV:-NbY-XunEl279A2m5B6E:bkfvu9w) ([raw file](https://github.com/harness/harness-core/blob/4b14913d41c13647f17f97f1854a3944efa45ed2/120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java#L578)):*
<details><summary><i>Previously, sahibaCCM (Sahiba Khan) wrote…</i></summary><blockquote>

We have changed V2 to through InvalidTokenException instead of InvalidRequestException ; we can make it specific.
</blockquote></details>

yes, lets make it specific, thanks

**Comment by sahibaCCM** [comment]
trigger uts

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51558)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by meenakshi-harness — APPROVED** [review]

**Pull request merged**
