### PR TITLE
fix: [BT-911]: Baking versionInfo.yaml into delegate jar.

### PR DESCRIPTION
**Pull request by USB-05**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31344)

### CODE REVIEW

**Comment by USB-05** [comment]
trigger ti2 ti3

**Comment by raghuAtWings** [comment]
___
*[260-delegate/container/scripts/start.sh, line 16 at r1](https://reviewable.io/reviews/harness/harness-core/31344#-My8Qxyg2NHtTaklOWs9:-My8Qxyy9sJp5K-4QTi3:b-8vng3k) ([raw file](https://github.com/harness/harness-core/blob/95392f09a71ad218e67b96ae27bb2da139599a52/260-delegate/container/scripts/start.sh#L16)):*
> ```Shell
>   if [ -z "$VERSION" ]
>   then
>     if unzip -l $JAR | grep -q BOOT-INF/classes/main/resources-filtered/versionInfo.yaml
> ```

we should do the same change in the following files

1. 260-delegate/container/scripts/start.sh
2. 400-rest/src/main/resources/delegatetemplates/common.start.sh.ftl
3. dockerization/delegate/scripts/delegate.sh
4. dockerization/delegate/scripts/start.sh

**Comment by mdmilic** [comment]
Also, do we want version with the patch number or without it? I think there were some recent changes in the delegate related to this?

**Comment by diptiman-adak** [comment]
@raghuAtWings I have updated the PR. But keeping a single source of truth is always a better choice. Now same function is used in multiple scripts. Better to move that function in a common script and invoke it from different places.

**Comment by diptiman-adak** [comment]
___
*[260-delegate/container/scripts/start.sh, line 22 at r4](https://reviewable.io/reviews/harness/harness-core/31344#-MyHble50cChKk5Y4iXg:-MyHeXJhBLEOIJ6vUizk:b-62b8t) ([raw file](https://github.com/harness/harness-core/blob/556174ff807f30843c8ebb9b9ef37d3fc5c5643a/260-delegate/container/scripts/start.sh#L22)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

This looks duplicated?
</blockquote></details>

Thanks for noticing it, updated the PR

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31344)* status: Some of the checks are too old.

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 5 files at r8, 4 of 4 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31344)* status: :shipit: complete! ✓

**Pull request merged**
