### PR TITLE
[feat]: [PIE-4375]: Update execution info in pipeline metadata on every status change

### PR DESCRIPTION
**Pull request by namanvermah**
**On Execution Start**:
  1. Fetch the metadata
  2. If recent execution info is not there, then initialise a list with one element being the info for the execution in
  question. Else, add this new execution's info into the head of the list. Make sure that the list size is not greater
  than NUM_RECENT_EXECUTIONS
  3. make an update call to set this new recent executions list into the pipeline metadata

**On Execution Update**:
  1. Fetch the metadata
  2. If recent execution info for this execution is there, then update the status of that execution, and add an endTs if
  the execution has ended. If the info is not there, it means this execution has been going on for too long
  3. make an update call to set this new recent executions list into the pipeline metadata

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vJMVy8W-rN-NKZHJW:-N6vJMVy8W-rN-NKZHJX:b-6i5rfq) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L59)):*
> ```Java
>     String lockName = getLockName(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
>     try (AcquiredLock<?> lock =
>              persistentLocker.waitToAcquireLock(lockName, Duration.ofSeconds(1), Duration.ofSeconds(2))) {
> ```

Just keep a check every week after prod, number of errors in taking lock, we might need to increase dock wait time then



_Code quote:_
```Java
Duration.ofSeconds(2)
```
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vL7fUDy9OpU1AHoL8:-N6vL7fUDy9OpU1AHoL9:b2slzop) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L100)):*
> ```Java
>    */
>   public void onExecutionUpdate(Ambiance ambiance, PlanExecution planExecution) {
>     String accountId = AmbianceUtils.getAccountId(ambiance);
> ```

Can common method in both execution start and update be extracted out?



_Code quote:_
```Java
    String accountId = AmbianceUtils.getAccountId(ambiance);
    String orgIdentifier = AmbianceUtils.getOrgIdentifier(ambiance);
    String projectIdentifier = AmbianceUtils.getProjectIdentifier(ambiance);
    String pipelineIdentifier = ambiance.getMetadata().getPipelineIdentifier();
    String planExecutionId = planExecution.getPlanId();
    String lockName = getLockName(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
    try (AcquiredLock<?> lock =
             persistentLocker.waitToAcquireLock(lockName, Duration.ofSeconds(1), Duration.ofSeconds(2))) {
      if (lock == null) {
        log.error(String.format(
            "Unable to acquire lock while updating Pipeline Metadata for Pipeline [%s] in Project [%s], Org [%s], Account [%s]",
            pipelineIdentifier, projectIdentifier, orgIdentifier, accountId));
        return;
      }
      Optional<PipelineMetadataV2> optionalPipelineMetadata =
          pipelineMetadataService.getMetadata(accountId, orgIdentifier, projectIdentifier, pipelineIdentifier);
      if (!optionalPipelineMetadata.isPresent()) {
        log.error(
            String.format("Could not find Pipeline Metadata for Pipeline [%s] in Project [%s], Org [%s], Account [%s]",
                pipelineIdentifier, projectIdentifier, orgIdentifier, accountId));
        return;
```

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vJMVy8W-rN-NKZHJW:-N6vqHsPAhYWkiYhfJDp:bh61yn2) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L59)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Just keep a check every week after prod, number of errors in taking lock, we might need to increase dock wait time then
</blockquote></details>

We have a log line to check this, so shouldn't be an issue.
___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vL7fUDy9OpU1AHoL8:-N6vqLAo2Oql4XNg4_o5:b41vonh) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can common method in both execution start and update be extracted out?
</blockquote></details>

Done as much as possible.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 59 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vJMVy8W-rN-NKZHJW:-N6vqgHeDRIQ3ejp5pgJ:b23y2o7) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L59)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

We have a log line to check this, so shouldn't be an issue.
</blockquote></details>

Yes meant the same, that just add this task after one month check these failures

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vL7fUDy9OpU1AHoL8:-N6vrNZ38GGyrKxmmbKg:b-6kd1aa) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L100)):*
<details><summary><i>Previously, namanvermah (Naman Verma) wrote…</i></summary><blockquote>

Done as much as possible.
</blockquote></details>

Discussed offline, trying with supplier

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/35266#-N6vL7fUDy9OpU1AHoL8:-N6w5kG11Tl9LzwWaiW8:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/2810dadf5d8fda24b0ae080fbf9e9fd6d90305f4/800-pipeline-service/src/main/java/io/harness/pms/pipeline/metadata/RecentExecutionsInfoHelper.java#L100)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Discussed offline, trying with supplier
</blockquote></details>

Done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35266)* status: :shipit: complete! ✓

**Pull request merged**
