### PR TITLE
[fix]: [PIE-8159]: Fixing error-message coming empty when resource-contraint fails the execution

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44169)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44169#-NOpUBli6SJRK5ZwR6W7:-NOpUBli6SJRK5ZwR6W8:bo0o17o) ([raw file](https://github.com/harness/harness-core/blob/c333f8610081d8425b437f4f78e5aabcb5513e24/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java#L47)):*
> ```Java
>                                   .addFailureData(FailureData.newBuilder()
>                                                       .setMessage(facilitatorResponseProto.getPassThroughData())
>                                                       .setCode(ErrorCode.GENERAL_ERROR.name())
> ```

whats a general error?

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/44169#-NOpUJ0d8VOZD18y5Sjz:-NOpUJ0d8VOZD18y5Sk-:b-7wtofs) ([raw file](https://github.com/harness/harness-core/blob/c333f8610081d8425b437f4f78e5aabcb5513e24/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java#L51)):*
> ```Java
>                                                       .addFailureTypes(FailureType.APPLICATION_FAILURE)
>                                                       .build())
>                                   .setErrorMessage(facilitatorResponseProto.getPassThroughData())
> ```

whats the difference b/w errorMessage and failureData.Message?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44169)* status: 3 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44169#-NOpUBli6SJRK5ZwR6W7:-NOrNudm-UPE4fc8Tbi0:bxlhpat) ([raw file](https://github.com/harness/harness-core/blob/c333f8610081d8425b437f4f78e5aabcb5513e24/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java#L47)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats a general error?
</blockquote></details>

When we don't have a dedicated errorCode for an error, we can set GeneralError as errorCode.
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/44169#-NOpUJ0d8VOZD18y5Sjz:-NOrNThP2JF99iEM95Pv:b-tlxf4n) ([raw file](https://github.com/harness/harness-core/blob/c333f8610081d8425b437f4f78e5aabcb5513e24/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java#L51)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

whats the difference b/w errorMessage and failureData.Message?
</blockquote></details>

outer errorMessage is depreciated as this does not the other required information like FailureTypes(Used for failure-strategy), but its used by UI so populating. 
FailureData is the correct thing to use going forward, so populating the required information in failureData(Along with message)

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44169)* status: 3 file(s) to review. 2. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/44169#-NOpUBli6SJRK5ZwR6W7:-NOs8HMa80YYUXRitMng:b-mfhvxa) ([raw file](https://github.com/harness/harness-core/blob/c333f8610081d8425b437f4f78e5aabcb5513e24/pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers/FacilitateResponseRequestProcessor.java#L47)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

When we don't have a dedicated errorCode for an error, we can set GeneralError as errorCode.
</blockquote></details>

As discussed, we should be using correct ERROR codes as per the use-case. Right now it requires change in different services and with proper release plan. Resolving for now, but should be taken care of in future.

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44169)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44169)* status: :shipit: complete! ✓

**Pull request merged**
