### PR TITLE
[feat]:[pie-6511]: gitx caching impl for getTemplate api

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Implementation for integrating getTemplate api with gitx caching. The basic getTemplate flows have been tested out.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 413 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI6zCDIABc46A0P0_RS:-NI6zCDIABc46A0P0_RT:b-ybk2jh) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L413)):*
> ```Java
>       return false;
>     } else {
>       return BOOLEAN_TRUE_VALUE.equals(loadFromCache);
> ```

should this be case insensitive ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 2 file(s) to review. 0 of 1 approvals obtained.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 2 file(s) to review. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 413 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI6zCDIABc46A0P0_RS:-NI73kJO9XDsWHwif60Q:b-gym2ro) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L413)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should this be case insensitive ?
</blockquote></details>

ideally not, but have code to handle it

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 121 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7ErkD9nWHlqM-s6a-:-NI7ErkD9nWHlqM-s6a0:b-xvjo7w) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L121)):*
> ```Java
>     TemplateMergeResponseDTO response = NGRestUtils.getResponse(templateResourceClient.applyTemplatesOnGivenYaml(
>         accountId, orgIdentifier, projectIdentifier, gitEntityBasicInfo.getBranch(),
>         gitEntityBasicInfo.getYamlGitConfigId(), gitEntityBasicInfo.getDefaultFromOtherRepo(), "false",
> ```

this shouldn't be hardcoded

**Comment by mohitg0795** [comment]
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7F7a60w_hm30wwBgK:-NI7F7a60w_hm30wwBgL:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L63)):*
> ```Java
>                                 customNGSecretManagerConfigDTO.getAccountIdentifier(),
>                                 customNGSecretManagerConfigDTO.getOrgIdentifier(),
>                                 customNGSecretManagerConfigDTO.getProjectIdentifier(), null, null, null, "false",
> ```

same

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 413 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI6zCDIABc46A0P0_RS:-NI7G5-z8pmPWkcwfsPR:b9k30ea) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L413)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

ideally not, but have code to handle it
</blockquote></details>

This should be case sensitive @adivishy1 . If someone gives True or TRUE or true, everything should point to same TRUE value.

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 413 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI6zCDIABc46A0P0_RS:-NI7GEZT-ZfBK94MVy9I:b-99rvnu) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L413)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This should be case sensitive @adivishy1 . If someone gives True or TRUE or true, everything should point to same TRUE value.
</blockquote></details>

insensitive *

**Comment by mohitg0795** [comment]
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 677 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI7GSP13YJqPBYDX1QM:-NI7GSP13YJqPBYDX1QN:b-nr8b9j) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L677)):*
> ```Java
>       @QueryParam(NGCommonEntityConstants.PROJECT_KEY) @ProjectIdentifier String projectId,
>       @BeanParam GitEntityFindInfoDTO gitEntityBasicInfo, @NotNull TemplateApplyRequestDTO templateApplyRequestDTO,
>       @HeaderParam("Load-From-Cache") @DefaultValue("false") String loadFromCache) {
> ```

where is this being used here? added just for contract right now?

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 85 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7Gres7i3walVpRv8u:-NI7GretBEffnYFfAp-k:b-gd1k1g) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L85)):*
> ```Java
>           return NGRestUtils.getResponse(templateResourceClient.applyTemplatesOnGivenYamlV2(accountId, orgId, projectId,
>               gitEntityInfo.getBranch(), gitEntityInfo.getYamlGitConfigId(), true, getConnectorRef(), getRepoName(),
>               accountId, orgId, projectId, "false",
> ```

shouldn't be hardcoded

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7Gt5d19ObsTlEywlz:-NI7Gt5d19ObsTlEywm-:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L93)):*
> ```Java
>         }
>         return NGRestUtils.getResponse(templateResourceClient.applyTemplatesOnGivenYamlV2(accountId, orgId, projectId,
>             null, null, null, null, null, null, null, null, "false",
> ```

same

**Comment by mohitg0795** [comment]
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/template/TemplateFacade.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7GzNk6KDU19MqWRyP:-NI7GzNk6KDU19MqWRyQ:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/template/TemplateFacade.java#L31)):*
> ```Java
>     TemplateMergeResponseDTO templateMergeResponseDTO =
>         NGRestUtils.getResponse(templateResourceClient.applyTemplatesOnGivenYaml(projectParams.getAccountIdentifier(),
>             projectParams.getOrgIdentifier(), projectParams.getProjectIdentifier(), null, null, null, "false",
> ```

same

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 16 file(s) to review. 6. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java` line 121 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7ErkD9nWHlqM-s6a-:-NI7a1CwC8oD2CmlAh50:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java#L121)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this shouldn't be hardcoded
</blockquote></details>

Done.
___
*[`440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java` line 63 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7F7a60w_hm30wwBgK:-NI7a77qAKhckn7KLUs1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/440-connector-nextgen/src/main/java/io/harness/connector/helper/CustomSecretManagerHelper.java#L63)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java` line 413 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI6zCDIABc46A0P0_RS:-NI7a8Vw16ZuodX5ilI-:b65pz69) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/mappers/NGTemplateDtoMapper.java#L413)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

insensitive *
</blockquote></details>

Have made the comparison case insensitive
___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 677 at r3](https://reviewable.io/reviews/harness/harness-core/40797#-NI7GSP13YJqPBYDX1QM:-NI7aCvWDi00JKS4wPZk:b-fl0iqz) ([raw file](https://github.com/harness/harness-core/blob/e59b4e93de2d7f1c2fdc07800902458b963f38af/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L677)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

where is this being used here? added just for contract right now?
</blockquote></details>

yes, this is just the contract 
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 85 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7Gres7i3walVpRv8u:-NI7aNOw8bQjWsS5m5kG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L85)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

shouldn't be hardcoded
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java` line 93 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7Gt5d19ObsTlEywlz:-NI7aNeQ4wFTXellDttQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java#L93)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/template/TemplateFacade.java` line 31 at r4](https://reviewable.io/reviews/harness/harness-core/40797#-NI7GzNk6KDU19MqWRyP:-NI7aTabENw4XrB6qf-6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/930892889153aada3949b4118786ae1144575934/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/utils/template/TemplateFacade.java#L31)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 13 of 13 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 6. unresolved discussions.

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797#-:-NI7bykD5M8AJ1y8nZaW:bnfp4nl)* status: 6. unresolved discussions.

**Review by utkarshchoubey-harness — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797#-:-NI7ctAo1QiWPrh1anD1:bnfp4nl)* status: 5 file(s) to review. 6. unresolved discussions.

**Review by mohitg0795 — DISMISSED** [review]
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 9 of 13 files at r4, 2 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Review by archit-harness — COMMENTED** [review]
> Reviewed 1 of 13 files at r4, 1 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 1 file(s) to review. 0 of 1 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: 1 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Review by utkarshchoubey-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797#-:-NIAnkYD0l7IxUWm0NrP:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 9 of 13 files at r4, 2 of 2 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40797)* status: :shipit: complete! ✓

**Pull request merged**
