### PR TITLE
fix: [CDS-38676]: Soft delete the correct instance

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34932)

### CODE REVIEW

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34932)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceService.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/34932#-N671Dwk2DRcOY1e3dts:-N671Dwk2DRcOY1e3dtt:b-z3uhpo) ([raw file](https://github.com/harness/harness-core/blob/22bb3bd09677e64aac4221807bc72cd62853758d/126-instance/src/main/java/io/harness/service/instance/InstanceService.java#L34)):*
> ```Java
>   void deleteAll(List<InstanceDTO> instanceDTOList);
> 
>   Optional<InstanceDTO> softDelete(String instanceKey, String accountIdentifier, String orgIdentifier,
> ```

Instances are always soft deleted, so I think we should call this method as ```delete``` to not give an impression that other delete methods do a hard delete
___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceService.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/34932#-N672JF80RTeIIhsz22o:-N672JF80RTeIIhsz22p:b-wrdg6t) ([raw file](https://github.com/harness/harness-core/blob/22bb3bd09677e64aac4221807bc72cd62853758d/126-instance/src/main/java/io/harness/service/instance/InstanceService.java#L35)):*
> ```Java
> 
>   Optional<InstanceDTO> softDelete(String instanceKey, String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String infrastructureMappingId);
> ```

Also, we should use @NotEmpty from javax for validations here to make sure we do not end of deleting undesired instances 
- ```account, org, project, inframappingId, instanceKey``` all should be non empty

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34932)* status: 1 change requests. 0 of 1 approvals obtained.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34932)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceService.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/34932#-N671Dwk2DRcOY1e3dts:-N67ZQp34TLBpX9_cYMj:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bb3bd09677e64aac4221807bc72cd62853758d/126-instance/src/main/java/io/harness/service/instance/InstanceService.java#L34)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Instances are always soft deleted, so I think we should call this method as ```delete``` to not give an impression that other delete methods do a hard delete
</blockquote></details>

Done.
___
*[`126-instance/src/main/java/io/harness/service/instance/InstanceService.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/34932#-N672JF80RTeIIhsz22o:-N67ZRF92s3uOW_k9qEA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/22bb3bd09677e64aac4221807bc72cd62853758d/126-instance/src/main/java/io/harness/service/instance/InstanceService.java#L35)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Also, we should use @NotEmpty from javax for validations here to make sure we do not end of deleting undesired instances 
- ```account, org, project, inframappingId, instanceKey``` all should be non empty
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java` line 100 at r3](https://reviewable.io/reviews/harness/harness-core/34932#-N67_xJY8PYOOH8NcYNd:-N67_xJY8PYOOH8NcYNe:b-qisen7) ([raw file](https://github.com/harness/harness-core/blob/337800f0a5dd32bf9af35dd388e833202966e676/126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java#L100)):*
> ```Java
>     checkArgument(isNotEmpty(infrastructureMappingId), "infrastructureMappingId must be present");
> 
>     Criteria criteria = Criteria.where(InstanceKeys.instanceKey)
> ```

why do we need to change the logic from relying on instance key to adding accountId, orgId etc details as well?

**Comment by mohitg0795** [comment]
*[`126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/34932#-N67a7qc0skHdE2KUi81:-N67a7qc0skHdE2KUi82:bcqrgll) ([raw file](https://github.com/harness/harness-core/blob/337800f0a5dd32bf9af35dd388e833202966e676/126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java#L94)):*
> ```Java
>   public Optional<InstanceDTO> delete(String instanceKey, String accountIdentifier, String orgIdentifier,
>       String projectIdentifier, String infrastructureMappingId) {
>     checkArgument(isNotEmpty(instanceKey), "instanceKey must be present");
> ```

I don't think we need these checkArguments. Even if its null, it will result in correct operation on Db, so we should be fine. Also, we have added @NotNull annotation, so that should inherently do this validation for us.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34932)* status: :shipit: complete! ✓

**Comment by vikyathharekal** [comment]
> _[`126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java` line 94 at r3](https://reviewable.io/reviews/harness/harness-core/34932#-N67a7qc0skHdE2KUi81:-N67a7qc0skHdE2KUi82:bcqrgll) ([raw file](https://github.com/harness/harness-core/blob/337800f0a5dd32bf9af35dd388e833202966e676/126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java#L94)):_
> 
> > ```java
> >   public Optional<InstanceDTO> delete(String instanceKey, String accountIdentifier, String orgIdentifier,
> >       String projectIdentifier, String infrastructureMappingId) {
> >     checkArgument(isNotEmpty(instanceKey), "instanceKey must be present");
> > ```
> 
> I don't think we need these checkArguments. Even if its null, it will result in correct operation on Db, so we should be fine. Also, we have added @NotNull annotation, so that should inherently do this validation for us.

Since this is an internal layer of code and not the API layer, we aren't sure whether javax validations will be applicable here.
And in case infraMappingId is missing, we could be deleting the wrong instance

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34932#-:-N68kkbJCs9ch3Lx78QY:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
