### PR TITLE
[feat]: [PIE-7603]: Use projections for pipelineExecutionSummaryEntity

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 198 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZsCm460yhXZZy1ymU:-NLZsCm460yhXZZy1ymV:bhpog3) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L198)):*
> ```Java
>       Ambiance ambiance = strategyNodeExecution.getAmbiance();
>       Optional<PipelineExecutionSummaryEntity> entity =
>           pmsExecutionSummaryRepository.findByPlanExecutionId(planExecutionId);
> ```

nit: here we are getting all fields?
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtidN9pADgN4Ys6ds:-NLZtidN9pADgN4Ys6dt:b70zply) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L184)):*
> ```Java
>   }
> 
>   public PipelineExecutionSummaryEntity getPipelineExecutionSummaryWithProjections(
> ```

also add realMongo test for this
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZt7iA6EedzNBgUSaf:-NLZt7iA6EedzNBgUSag:b-b8r1dd) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L189)):*
> ```Java
> 
>     for (String field : fieldsToInclude) {
>       query.fields().include(field);
> ```

we should check fields should not be empty, 
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NLZtMiK18SjwsXK7OTv:b-bdx6qe) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
> ```Java
>     }
> 
>     addRequiredFieldsForProjectionOfPipelineExecutionSummaryEntity(query);
> ```

we should add this only if needed by callers, like in nodeexecutionservice we add because service layer was using it internally
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtCEu8cYM7U3H3n-s:-NLZtCEu8cYM7U3H3n-t:b-5p6g9q) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L194)):*
> ```Java
>     addRequiredFieldsForProjectionOfPipelineExecutionSummaryEntity(query);
> 
>     query.with(by(Sort.Direction.DESC, PlanExecutionSummaryKeys.createdAt));
> ```

and why why we are sorting with createdAt?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java` line 198 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZsCm460yhXZZy1ymU:-NLZu0YB5EVumaE_cJWJ:b-n8t77t) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service/PmsExecutionSummaryServiceImpl.java#L198)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: here we are getting all fields?
</blockquote></details>

Yes, here whole object is required.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 194 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtCEu8cYM7U3H3n-s:-NLZu5Ir4H6mn_Qarihg:b-ng6xd6) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L194)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

and why why we are sorting with createdAt?
</blockquote></details>

This should not be there, caller should add sort if required.
It got copied from somewhere I believe.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 184 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtidN9pADgN4Ys6ds:-NL_Vbnj65N2fnVZlrVB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L184)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

also add realMongo test for this
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NL_VgtQ5VkOj4PriY3v:b-xuznf8) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should add this only if needed by callers, like in nodeexecutionservice we add because service layer was using it internally
</blockquote></details>

This is required because most of them are marked nonnull in our pojo hence java would complain.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZt7iA6EedzNBgUSaf:-NL_WEQx6EzduD3LUic5:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L189)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should check fields should not be empty, 
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NL_WGkf9-o1TnHKfJQ1:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

This is required because most of them are marked nonnull in our pojo hence java would complain. 
</blockquote></details>

done

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 10 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)* status: 15 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_nhg6BFWopB5mgBPL:-NL_nhg6BFWopB5mgBPM:brxv0rr) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L65)):*
> ```Java
>    *
>    * @param rootParentId
>    * @return
> ```

can you also add comment users should get approval before using this method as its not using projections, example retry can use
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 189 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZt7iA6EedzNBgUSaf:-NL_n3Vh3cvuuCFoAUc2:b-1pbh0k) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L189)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry i meant we should add validation if set is empty then throw exceptions
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NL_nGfw0LIBda--RiPb:btewdvv) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

done
</blockquote></details>

did you try without these projections as well? for me other entities were not complaining
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_mDgPCB5VqYOtcykD:-NL_mDgPCB5VqYOtcykE:b-1ahmbh) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L96)):*
> ```Java
>         query.fields().include(key);
>       }
>       return pmsExecutionSummaryReadHelper.fetchExecutionSummaryEntityFromSecondary(query);
> ```

i think this method is used in tsdb then analytics may work here



_Code quote:_
```Java
findAllWithRequiredProjection
```
___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_my2y61JP0bK7OfX2:-NL_my2y61JP0bK7OfX3:b-969lof) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L151)):*
> ```Java
> 
>   @Override
>   public CloseableIterator<PipelineExecutionSummaryEntity> fetchPipelineSummaryEntityFromRootParentId(
> ```

can you add secondary in this method name as well?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java` line 99 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_nTKZ4EYt-JNxKfwd:-NL_nTKZ4EYt-JNxKfwe:b-s84z1z) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/service/src/main/java/io/harness/pms/migration/SyncPipelineExecutionsWithWrongStatusInTimescale.java#L99)):*
> ```Java
> 
>     try (CloseableIterator<PipelineExecutionSummaryEntity> iterator =
>              pmsExecutionSummaryRepository.findAllWithRequiredProjection(criteria, pageable, projections);
> ```

can we add analytics keyword in this method name?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 429 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_nYJP8ESgiUqTp2XS:-NL_nYJP8ESgiUqTp2XT:b-hd3t4h) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L429)):*
> ```Java
>   public RetryHistoryResponseDto getRetryHistory(String rootParentId) {
>     try (CloseableIterator<PipelineExecutionSummaryEntity> iterator =
>              pmsExecutionSummaryRespository.fetchPipelineSummaryEntityFromRootParentId(rootParentId)) {
> ```

can we add comment here we are fetching from secondary thus small delay should be fine in sync
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 468 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_o48x9Nr1VCH9KQg_:-NL_o48x9Nr1VCH9KQga:b7j2kfp) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L468)):*
> ```Java
>     try (CloseableIterator<PipelineExecutionSummaryEntity> iterator =
>              pmsExecutionSummaryRespository.fetchPipelineSummaryEntityFromRootParentId(rootParentId)) {
>       if (iterator.hasNext()) {
> ```

can you add comment here that we want more than 1 entries thus checking this way

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java` line 65 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_nhg6BFWopB5mgBPL:-NLdZIJo2NMdyhN86sAF:bp0t8ac) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustom.java#L65)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you also add comment users should get approval before using this method as its not using projections, example retry can use
</blockquote></details>

It is using projections.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NLdZjz95Vp65HIO-7ly:bsangf6) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

did you try without these projections as well? for me other entities were not complaining
</blockquote></details>

Sure, will give it a try and remove if working without it.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 96 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_mDgPCB5VqYOtcykD:-NLehU6SACOnGQM_PCcm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L96)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think this method is used in tsdb then analytics may work here
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 151 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_my2y61JP0bK7OfX2:-NLehVjT6C_XQYGmlmsb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L151)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add secondary in this method name as well?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 192 at r1](https://reviewable.io/reviews/harness/harness-core/42542#-NLZtMiK18SjwsXK7OTu:-NLehYD435xcsTdmdJOa:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/c1ea86fa0c2b508b8248499f42bd3c127fced3af/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L192)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Sure, will give it a try and remove if working without it.
</blockquote></details>

Done

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 429 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_nYJP8ESgiUqTp2XS:-NLehis05o59KLU38v68:b-l8xf1h) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L429)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add comment here we are fetching from secondary thus small delay should be fine in sync
</blockquote></details>

Have modified the method name to use secondary, should I add a comment too?

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)* status: 15 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/42542#-NLejv9eCXIrn2jJJaic:-NLejv9eCXIrn2jJJaid:b-35zrqt) ([raw file](https://github.com/harness/harness-core/blob/6b83a9e529828af7ecb4b8499ecd90610b9b05ed/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L191)):*
> ```Java
>     Query query = query(criteria);
>     if (EmptyPredicate.isEmpty(fieldsToInclude)) {
>       throw new GeneralException("Provided empty field names for projection");
> ```

isnt this deprecated? invalidRequestException maybe?

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java` line 191 at r4](https://reviewable.io/reviews/harness/harness-core/42542#-NLejv9eCXIrn2jJJaic:-NLvr6ir7dxXvUUzFKlX:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6b83a9e529828af7ecb4b8499ecd90610b9b05ed/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions/PmsExecutionSummaryRepositoryCustomImpl.java#L191)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this deprecated? invalidRequestException maybe?
</blockquote></details>

Done.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java` line 468 at r3](https://reviewable.io/reviews/harness/harness-core/42542#-NL_o48x9Nr1VCH9KQg_:-NLvr8brEpRp0prl_cgm:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c69e1ddcd622542b299fcaa384a0365cf144653a/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java#L468)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can you add comment here that we want more than 1 entries thus checking this way
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 5 of 11 files at r2, 2 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42542)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
