### PR TITLE
feat: [IDP-183]: Added Generic EventFramework and extended for gitintegration

### PR DESCRIPTION
**Pull request by devesh-harness**
…gration

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/modules/events/src/main/java/io/harness/events/consumers/EntityCrudStreamConsumer.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQKobw2tD_UiuwHCDT:-NPQKobw2tD_UiuwHCDU:b-2aga8) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/modules/events/src/main/java/io/harness/events/consumers/EntityCrudStreamConsumer.java#L44)):*
> ```Java
>   @Inject
>   public EntityCrudStreamConsumer(@Named(ENTITY_CRUD) Consumer redisConsumer,
>       @Named(ENTITY_CRUD) MessageListener secretCrudListener, QueueController queueController) {
> ```

We could rename this as well



_Code quote:_
```Java
secretCrudListener
```
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/factory/EventMessageHandlerFactory.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQOjA37o50cx0xYgOq:-NPQOjA37o50cx0xYgOr:bi2wiwk) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/factory/EventMessageHandlerFactory.java#L20)):*
> ```Java
> 
> public class EventMessageHandlerFactory {
>   @Inject SecretMessageHandler secretMessageHandler;
> ```

Let's use @AllArgsConstructor as much as possible instead of field injections. Ref: https://rules.sonarsource.com/java/RSPEC-3306



_Code quote:_
```Java
@Inject
```
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/messagehandler/EventMessageHandler.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQQNkO9zzbm8_P_DBB:-NPQQNkO9zzbm8_P_DBC:b-csysc) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/messagehandler/EventMessageHandler.java#L14)):*
> ```Java
> 
> public interface EventMessageHandler {
>   public void messageHandler(Message message, EntityChangeDTO entityChangeDTO, String action) throws Exception;
> ```

nit: We can omit public. It is public by default



_Code quote:_
```Java
public
```
___
*[`idp-service/service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java` line 24 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQRRazCv0u8Tchm1FX:-NPQRRazCv0u8Tchm1FY:bdqjjhe) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java#L24)):*
> ```Java
> 
> @Slf4j
> public class GitIntegrationServiceImpl implements GitIntegrationService {
> ```

nit: OwnedBy
___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQRefU-k7LeW12J3DZ:-NPQRefU-k7LeW12J3D_:b-mq232b) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L136)):*
> ```Java
> 
>   @Override
>   public void processSecretUpdate(EntityChangeDTO entityChangeDTO) throws Exception {
> ```

syncK8sSecret is not throwing anymore. we could remove this.



_Code quote:_
```Java
Exception
```
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQLOqL5f0UbyRrUwUK:-NPQLOqL5f0UbyRrUwUL:b-8ofskw) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java#L34)):*
> ```Java
> @AllArgsConstructor(onConstructor = @__({ @Inject }))
> @Slf4j
> public class EventHandler implements MessageListener {
> ```

How about naming this in the format `XxxListener`? Maybe `EntityCrudListenerStreamListener`
Just trying to use the same noun. All the other implementations have followed this same.



_Code quote:_
```Java
EventHandler
```
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQP9aa1EQycVgvKj2f:-NPQP9aa1EQycVgvKj2g:br98ez2) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java#L52)):*
> ```Java
>                 messageId);
>           }
>           log.info("Received event. Entity type : {}, Action: {}, Account: {}", entityType, action,
> ```

Better to have this log message after we narrow down the entities we need. Otherwise, this will log for any entity event which might result in too many logs.



_Code quote:_
```Java
log.info
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 13 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/modules/events/src/main/java/io/harness/events/consumers/EntityCrudStreamConsumer.java` line 44 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQKobw2tD_UiuwHCDT:-NPRZinf3vbfctPw8iQg:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/modules/events/src/main/java/io/harness/events/consumers/EntityCrudStreamConsumer.java#L44)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We could rename this as well
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/factory/EventMessageHandlerFactory.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQOjA37o50cx0xYgOq:-NPRhZEK70KAEWkliA_j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/factory/EventMessageHandlerFactory.java#L20)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Let's use @AllArgsConstructor as much as possible instead of field injections. Ref: https://rules.sonarsource.com/java/RSPEC-3306
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java` line 136 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQRefU-k7LeW12J3DZ:-NPRi1qOD-7jEe1fKGWE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/secret/service/EnvironmentSecretServiceImpl.java#L136)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

syncK8sSecret is not throwing anymore. we could remove this.
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQLOqL5f0UbyRrUwUK:-NPR_ODn9CqKCS2MEKCI:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java#L34)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

How about naming this in the format `XxxListener`? Maybe `EntityCrudListenerStreamListener`
Just trying to use the same noun. All the other implementations have followed this same.
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/44504#-NPQP9aa1EQycVgvKj2f:-NPRgaYQ6Vdp-peZJxhz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/248f2dc96d7f2793ac214230ce60aee4d74e729d/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventHandler.java#L52)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Better to have this log message after we narrow down the entities we need. Otherwise, this will log for any entity event which might result in too many logs.
</blockquote></details>

Done.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 12 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/utility/EventListenerLogger.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPStBQN1EuFR8f7qD_P:-NPStBQN1EuFR8f7qD_Q:b-wc34an) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/utility/EventListenerLogger.java#L18)):*
> ```Java
> 
> @Slf4j
> public class EventListenerLogger {
> ```

we can annotate @UtilityClass, then we don't need to inject, we can use EventListenerLogger.logForEventReceived as a static ref

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVHzXvCsGLxXLaLLZ_:-NPVHzXvCsGLxXLaLLZa:b-cg8msw) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L39)):*
> ```Java
>   @Override
>   public boolean handleMessage(Message message) {
>     if (message != null && message.hasMessage()) {
> ```

invert the condition to simplify the nesting
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVGeQn8Yawdk90ubF-:-NPVGeQn8Yawdk90ubF0:b-cg8msw) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L44)):*
> ```Java
>         Map<String, String> metadataMap = message.getMessage().getMetadataMap();
>         String entityType = metadataMap.get(ENTITY_TYPE);
>         if (entityType != null) {
> ```

invert the condition to simplify the nesting
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVIDogE5PgsebdHn4Z:-NPVIDogE5PgsebdHn4_:b-ufnplq) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L60)):*
> ```Java
>           EventMessageHandler eventMessageHandler = eventMessageHandlerFactory.getEventMessageHandler(entityType);
>           if (eventMessageHandler != null) {
>             eventMessageHandler.messageHandler(message, entityChangeDTO, action);
> ```

in case of failure how you are handling retry ?  if failure happen will the messages be replayed or saved in DLQ?

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 12 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 39 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVHzXvCsGLxXLaLLZ_:-NPVpLoz9mvKbPFFDz5J:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L39)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

invert the condition to simplify the nesting
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 44 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVGeQn8Yawdk90ubF-:-NPVpM9x3v_vNNC8Yi_2:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L44)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

invert the condition to simplify the nesting
</blockquote></details>

Done.
___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java` line 60 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPVIDogE5PgsebdHn4Z:-NPW3sW5Dr32C8NV3gYM:btx0wxe) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/eventhandler/EventCrudStreamListener.java#L60)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

in case of failure how you are handling retry ?  if failure happen will the messages be replayed or saved in DLQ?
</blockquote></details>

yes in case of event failure it will be retried first for max retries and then it will be saved in DLQ, for logic failure we should not do retries otherwise it will keep on retrying event and keep on sending it to DLQ in case of failure or InvaliedRequestException (we can add it throw exception on service layer).

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 12 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/service/src/main/java/io/harness/idp/eventlisteners/utility/EventListenerLogger.java` line 18 at r3](https://reviewable.io/reviews/harness/harness-core/44504#-NPStBQN1EuFR8f7qD_P:-NPWLk1r2XO_0UdWB4BD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6a46740a813ed561cf0749544515c8c05cb0b35f/idp-service/service/src/main/java/io/harness/idp/eventlisteners/utility/EventListenerLogger.java#L18)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

we can annotate @UtilityClass, then we don't need to inject, we can use EventListenerLogger.logForEventReceived as a static ref
</blockquote></details>

Done.

**Review by deepharness — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 5 of 11 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44504)* status: :shipit: complete! ✓

**Pull request merged**
