### PR TITLE
feat: [PL-39021]: Updated description for Attribute filter in Resourc…

### PR DESCRIPTION
**Pull request by meenakshi-harness**
## Describe your changes
1. Updated description for values in Attribute Filter for ResourceGroup API
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49176)

### CODE REVIEW

**Comment by meenakshi-harness** [comment]
trigger uts

**Comment by meenakshi-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49176)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`platform-service/modules/resource-group-service/contracts/openapi/v1/openapi.yaml` line 530 at r3](https://reviewable.io/reviews/harness/harness-core/49176#-NXsyreV7CC5D94Zq75h:-NXsyreV7CC5D94Zq75i:blhjom6) ([raw file](https://github.com/harness/harness-core/blob/b4ecf871b29afc0425492b47f70baac5bd1873b2/platform-service/modules/resource-group-service/contracts/openapi/v1/openapi.yaml#L530)):*
> ```YAML
>         attribute_values:
>           type: array
>           description: Attribute values selected. Values can be one of ["Production","PreProduction"] for ENVIRONMENT or ["ARTIFACTORY","CLOUD_COST","CLOUD_PROVIDER","CODE_REPO","MONITORING","SECRET_MANAGER","TICKETING"] for CONNECTOR.
> ```

@meenakshi-harness What is the guidance from API team? Should we include options in API description or maybe point to docs? Also string values don't have any check so doesn't seem to be maintainable.
@ankit-harness any thoughts?

**Comment by ashishsanodia-harness** [comment]
*[`platform-service/modules/resource-group-service/contracts/openapi/v1/openapi.yaml` line 530 at r3](https://reviewable.io/reviews/harness/harness-core/49176#-NXsyreV7CC5D94Zq75h:-NXtssSlEMLDLPBQVsSV:bizps46) ([raw file](https://github.com/harness/harness-core/blob/b4ecf871b29afc0425492b47f70baac5bd1873b2/platform-service/modules/resource-group-service/contracts/openapi/v1/openapi.yaml#L530)):*
<details><summary><i>Previously, meenakshi-harness (Meenakshi Raikwar) wrote…</i></summary><blockquote>

@Jimit09Gandhi this is just a short term solution but @ashishsanodia-harness can review if we should provide link to docs or not.
Agree on the contract side, String is not maintainable, we might need more insight on why we added this as a string.
</blockquote></details>

Can't we use enum?
One of the motivation behind using spec-first is that api consumer should be able to automate client generation using openapi. Instead of adding it in description we should document as part of openapi

**Pull request closed without merging**
