### PR TITLE
feat: [PIE-9164]: add new collection in ng manager for user's git auth details

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45667)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger ut0, ut2, ut5

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/BitbucketSCM.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRXw6fP6Xx8PkGIhPZQ:-NRXw6fQC60E0MVewDoX:b-y0jd3p) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/BitbucketSCM.java#L41)):*
> ```Java
> @Persistent
> public class BitbucketSCM extends UserSourceCodeManager {
>   BitbucketUsernamePasswordApiAccess bitbucketUsernamePasswordApiAccess;
> ```

we need to introduce a new OAuth api access for it. We can remove Bitbucket for now.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRY5-dU9Yp1UFPF1Uz1:-NRY5-dU9Yp1UFPF1Uz2:bbqshpq) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L41)):*
> ```Java
> @Document("userSourceCodeManagers")
> @TypeAlias("io.harness.gitsync.common.beans.UserSourceCodeManager")
> @Entity(value = "userSourceCodeManagers", noClassnameStored = true)
> ```

any particular reason to name it "user...Manager*s*" instead of "userSourceCodeManager"?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYAYQzB_oXwYa4GdgY:-NRYAYQzB_oXwYa4GdgZ:b72lv22) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L56)):*
> ```Java
>     return ImmutableList.<MongoIndex>builder()
>         .add(CompoundMongoIndex.builder()
>                  .name("uniqueIndex")
> ```

name is too vague

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYAvKOCWxNdxWBdHIT:-NRYAvKOCWxNdxWBdHIU:b5wctlx) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L48)):*
> ```Java
>   @NotEmpty String userIdentifier;
>   @NotEmpty @FdIndex String accountIdentifier;
>   @CreatedDate Long createdAt;
> ```

why are we using "Long" instead of long here? Any reasons?

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYB0941LK1vXXQDFMA:-NRYB0941LK1vXXQDFMB:b-jjxqxu) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L37)):*
> ```Java
> @Data
> @EqualsAndHashCode
> @FieldNameConstants(innerTypeName = "USCMKeys")
> ```

I think lets use clear full names here for easy clarity

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45667)* status: 6 file(s) to review. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/AwsCodeCommitSCM.java` line 40 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRXtHpy43Rubgsxq9Pq:-NRY72Of8vZoUbS6ikVu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/AwsCodeCommitSCM.java#L40)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we shouldn't implement any random SCM for now. We should only focus on Bitbucket, Github, Gitlab and ADO.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/BitbucketSCM.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRXw6fP6Xx8PkGIhPZQ:-NRY71lv3uapMz5UUpJE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/BitbucketSCM.java#L41)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we need to introduce a new OAuth api access for it. We can remove Bitbucket for now.
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 37 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYB0941LK1vXXQDFMA:-NRYCtnB8omTIEdJgMxh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L37)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

I think lets use clear full names here for easy clarity
</blockquote></details>

Done.
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYAvKOCWxNdxWBdHIT:-NRYDL_J-LCaipbrJKdU:bd4d79b) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L48)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why are we using "Long" instead of long here? Any reasons?
</blockquote></details>

we use Long only for fields like createdAt in entities, right? I checked for some like SourceCodeManager, and PipelineExecutionSummaryEntity, etc. The reason might be the advantages that objects provide over primitive types. Like serialization, the ability to be null, etc. 
 
___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYAYQzB_oXwYa4GdgY:-NRYCsnj1QZLYXToguxL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L56)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

name is too vague
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/45667#-NRYAvKOCWxNdxWBdHIT:-NRYJnDDBQkL1SSMQn4h:b-uxxwso) ([raw file](https://github.com/harness/harness-core/blob/a425139101d802f0bbc31c85934389d44b85d4d9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/beans/UserSourceCodeManager.java#L48)):*
<details><summary><i>Previously, shalini-agr (Shalini Agrawal) wrote…</i></summary><blockquote>

we use Long only for fields like createdAt in entities, right? I checked for some like SourceCodeManager, and PipelineExecutionSummaryEntity, etc. The reason might be the advantages that objects provide over primitive types. Like serialization, the ability to be null, etc. 
 
</blockquote></details>

Here actually we don't need ability to be null. createdAt and updatedAt should always be present. Lets raise this open question internally. If there's no significant reason to use Long, then we should prefer to use long here.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 6 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45667)* status: :shipit: complete! ✓

**Pull request merged**
