### PR TITLE
fix: [PIE-4632]: Incorrect error response when trigger is not present

### PR DESCRIPTION
**Pull request by sribalij**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)

### CODE REVIEW

**Comment by sribalij** [comment]
trigger messagecheck

**Comment by sribalij** [comment]
trigger messagecheck

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/35842#-N859wE12lFalvFHCAd7:-N859wE12lFalvFHCAd8:b-3mp4o2) ([raw file](https://github.com/harness/harness-core/blob/ee468d57a55c683f63b481d65e2b7ae9316c71bc/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L98)):*
> ```Java
> 
>     if (!ngTriggerEntity.isPresent()) {
>       throw new InvalidRequestException(String.format("Trigger %s doesn't not exist", triggerIdentifier));
> ```

Small message change "Trigger %s does not exist"

**Comment by sribalij** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)_ status: 2 file(s) to review. 0 of 2 approvals obtained.
> 
> _[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/35842#-N859wE12lFalvFHCAd7:-N859wE12lFalvFHCAd8:b-3mp4o2) ([raw file](https://github.com/harness/harness-core/blob/ee468d57a55c683f63b481d65e2b7ae9316c71bc/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L98)):_
> 
> > ```java
> >     if (!ngTriggerEntity.isPresent()) {
> >       throw new InvalidRequestException(String.format("Trigger %s doesn't not exist", triggerIdentifier));
> > ```
> 
> Small message change "Trigger %s does not exist"

done

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)* status: 2 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by sribalij** [comment]
trigger ti4

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842#-:-N85eCvr0iCCIYPNGagH:bnfp4nl)* status: 1. unresolved discussions.

**Review by sribalij — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)* status: 1. unresolved discussions. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/35842#-N859wE12lFalvFHCAd7:-N85ex2cBnASX5ucR14A:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/ee468d57a55c683f63b481d65e2b7ae9316c71bc/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/resource/NGTriggerResourceImpl.java#L98)):*
<details><summary><i>Previously, sribalij (Sridhar) wrote…</i></summary><blockquote>

done
</blockquote></details>

Done

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)* status: 1. unresolved discussions.

**Review by rohitk-h — APPROVED** [review]

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35842)* status: :shipit: complete! ✓

**Pull request merged**
