### PR TITLE
[feat]: [CDS-42424]: Get template with inputs Api

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37064)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 4 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37064)

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37064)* status: 9 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1023 at r2](https://reviewable.io/reviews/harness/harness-core/37064#-NBBdX478RgbvARNJaEg:-NBBdX478RgbvARNJaEh:b-51kk1c) ([raw file](https://github.com/harness/harness-core/blob/1699d47f0f42b2d41facf46be742e5ce2895325c/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1023)):*
> ```Java
>   public TemplateWithInputsResponseDTO getTemplateWithInputs(String accountId, String orgIdentifier,
>       String projectIdentifier, String templateIdentifier, String versionLabel) {
>     Optional<TemplateEntity> templateEntity = templateServiceHelper.getTemplateOrThrowExceptionIfInvalid(
> ```

We should use  io.harness.template.services.NGTemplateService#get() method.
It does enforcement check as well

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37064)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 1023 at r2](https://reviewable.io/reviews/harness/harness-core/37064#-NBBdX478RgbvARNJaEg:-NBC5yusEJ1atMEelE88:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1699d47f0f42b2d41facf46be742e5ce2895325c/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L1023)):*
<details><summary><i>Previously, inderschera (Inderpreet Chera) wrote…</i></summary><blockquote>

We should use  io.harness.template.services.NGTemplateService#get() method.
It does enforcement check as well
</blockquote></details>

Done.

**Review by inderschera — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 6 of 8 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37064)* status: :shipit: complete! ✓

**Pull request merged**
