### PR TITLE
fix: [CDS-36907]: store serviceEntity yaml as is from request DTO

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- First validate the yaml, then store it as is

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)

### CODE REVIEW

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33148#-N2-n4N31t8_R4HuEC2D:-N2-n4N31t8_R4HuEC2E:bg96j9b) ([raw file](https://github.com/harness/harness-core/blob/a96978fc86853bfd9eff3ae6a876b9a9e3a04afd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L41)):*
> ```Java
>     // This also validates the service yaml
>     NGServiceConfig ngServiceConfig = NGServiceEntityMapper.toNGServiceConfig(serviceEntity);
>     if (isEmpty(serviceEntity.getYaml())) {
> ```

Should we also introduce that if ff enabled then for any service create/update yaml is not null? in resource



_Code quote:_
```Java
if (isEmpty(serviceEntity.getYaml())) {
```

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33148#-N2-n4N31t8_R4HuEC2D:-N2AJS62-osEuYz70lO6:blgg4pq) ([raw file](https://github.com/harness/harness-core/blob/a96978fc86853bfd9eff3ae6a876b9a9e3a04afd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L41)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should we also introduce that if ff enabled then for any service create/update yaml is not null? in resource
</blockquote></details>

That means we are not allowing users to create older services once FF is enabled. We are not sure if we want to stop the older route straight away. Once we decide, it can be done

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33148#-N2AK6cREMyZ8dtby4sN:-N2AK6cREMyZ8dtby4sO:bajpsrl) ([raw file](https://github.com/harness/harness-core/blob/a96978fc86853bfd9eff3ae6a876b9a9e3a04afd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L41)):*
> ```Java
>     // This also validates the service yaml
>     NGServiceConfig ngServiceConfig = NGServiceEntityMapper.toNGServiceConfig(serviceEntity);
>     if (isEmpty(serviceEntity.getYaml())) {
> ```

isNotEmpty should be used or add ! before isEmpty

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33148#-N2AK6cREMyZ8dtby4sN:-N2AKxEk9DjwP96CV9vI:b-3oeu5u) ([raw file](https://github.com/harness/harness-core/blob/a96978fc86853bfd9eff3ae6a876b9a9e3a04afd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L41)):*
<details><summary><i>Previously, prashantsharma04 (Prashant Sharma) wrote…</i></summary><blockquote>

isNotEmpty should be used or add ! before isEmpty
</blockquote></details>

if the yaml is empty, then only we would like to overwrite the yaml from ngServiceConfig
if the yaml is already provided, we want to store it as is. The validation of the yaml is already done by ```NGServiceEntityMapper.toNGServiceConfig(serviceEntity);```

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 change requests. 2. unresolved discussions.

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148)* status: 1 change requests. 1. unresolved discussions. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java` line 41 at r1](https://reviewable.io/reviews/harness/harness-core/33148#-N2AK6cREMyZ8dtby4sN:-N2AMUMFBJQ95oVcMzwc:b-w0yspi) ([raw file](https://github.com/harness/harness-core/blob/a96978fc86853bfd9eff3ae6a876b9a9e3a04afd/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceElementMapper.java#L41)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

if the yaml is empty, then only we would like to overwrite the yaml from ngServiceConfig
if the yaml is already provided, we want to store it as is. The validation of the yaml is already done by ```NGServiceEntityMapper.toNGServiceConfig(serviceEntity);```
</blockquote></details>

got it.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33148#-:-N2AMkNwCbePU9wonZWt:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
