### PR TITLE
fix: [PIE-4280]: Diff. projects/orgs with same keys should also sync

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
* Diff. projects/orgs with same keys should also sync
* Change to return null instead of throw exception to avoid break the UI
* Conditional execution should work as is for Queue step

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34793)

### CODE REVIEW

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34793)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Comment by Fernando-Dourado** [comment]
trigger messagecheck

**Comment by mbatchelor** [comment]
trigger messagecheck

**Comment by Fernando-Dourado** [comment]
trigger compile

**Comment by Fernando-Dourado** [comment]
trigger codebasehash

**Comment by Fernando-Dourado** [comment]
trigger codeformat, messagecheck, recency, buildnum, dockerizationcheck, checkstyle, pmd, ti0, ti1, ti2, ti3, ti4, ft1, ft2

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 13 of 14 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34793)* status: 32 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
