### PR TITLE
[fix]: [SRM-10682]: added validation for thresholds + NULL check for UserGroups

### PR DESCRIPTION
**Pull request by kapil-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33656)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger tin0

**Comment by kapil-harness** [comment]
trigger tin4

**Comment by kapil-harness** [comment]
trigger ti4

**Comment by kapil-harness** [comment]
trigger ti0

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33656)* status: 18 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/ErrorBudgetRemainingMinutesConditionSpec.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33656#-N3NB34LBB0Ur-35XqX1:-N3NB34M6l0axIqUulFo:bwfx391) ([raw file](https://github.com/harness/harness-core/blob/250ea11dc28d9337291e102121d603349ec8e1a8/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/ErrorBudgetRemainingMinutesConditionSpec.java#L32)):*
> ```Java
> 
>   @Override
>   public void validateConditionSpec() {}
> ```

ideally this kind of validation should result in 400 bad request and should be done using dropwizard validator
https://www.dropwizard.io/en/latest/manual/validation.html
You can use @Min and @Max annotation or @ValidationMethod for these kind of validation at framework level.
You will have to add @Valid annotation at every level.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33656)* status: 18 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/ErrorBudgetRemainingMinutesConditionSpec.java` line 32 at r1](https://reviewable.io/reviews/harness/harness-core/33656#-N3NB34LBB0Ur-35XqX1:-N3NMr96AUEaMlUtYnq1:bwfx9kj) ([raw file](https://github.com/harness/harness-core/blob/250ea11dc28d9337291e102121d603349ec8e1a8/300-cv-nextgen/src/main/java/io/harness/cvng/notification/beans/ErrorBudgetRemainingMinutesConditionSpec.java#L32)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

ideally this kind of validation should result in 400 bad request and should be done using dropwizard validator
https://www.dropwizard.io/en/latest/manual/validation.html
You can use @Min and @Max annotation or @ValidationMethod for these kind of validation at framework level.
You will have to add @Valid annotation at every level.
</blockquote></details>

agreed, done

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 18 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33656#-:-N3NNJsb2KepjDYnWqeN:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
