### PR TITLE
feat: [CDS-78762]: Added GCS artifact type support for SSH

### PR DESCRIPTION
**Pull request by acasian-harness**
## Describe your changes

Added support for GCS artifact type for SSH deployments

- [x] Support copy artifact
- [ ] Support download artifact

Testing performed:
**Service**:
Screenshot 2023-09-20 at 11 50 15

**Service Step:**
Screenshot 2023-09-20 at 11 49 50

**Command Step:**
Screenshot 2023-09-20 at 11 49 28

**Host:**
Screenshot 2023-09-20 at 11 49 34

**Bad artifact path:**
Screenshot 2023-09-20 at 12 18 10

**Artifact variables:**
```
artifact.metadata.url :https://www.googleapis.com/storage/v1/b/cdp-artifacts-bucket/o/helloworld.war
artifacts.primary.type:GoogleCloudStorage
artifacts.primary.connectorRef> :gcpconnector
artifact.metadata.bucket :cdp-artifacts-bucket
artifacts.primary.project :qa-target
artifacts.primary.artifactPath :helloworld.war
```
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52722)

### CODE REVIEW

**Review by vitsafronovici — APPROVED** [review]

**Comment by acasian-harness** [comment]
trigger uts

**Comment by acasian-harness** [comment]
trigger ut4 ut8

**Comment by acasian-harness** [comment]
trigger uts

**Comment by acasian-harness** [comment]
trigger ut2 ut4 ut7

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 15 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52722#-:-Nemj1kmB01vdcKGJygR:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained. 

___
*[`960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java` line 180 at r2](https://reviewable.io/reviews/harness/harness-core/52722#-Nemiugu4sw4i1rSkMVd:-Nemiugu4sw4i1rSkMVe:b-uu4x4a) ([raw file](https://github.com/harness/harness-core/blob/8ffdb700898a9b23471b26e65ff8f6123e3129e8/960-api-services/src/main/java/io/harness/googlecloudstorage/GcsHelperService.java#L180)):*
> ```Java
>     Bucket bucket = storage.get(gcsInternalConfig.getBucket());
>     if (bucket == null) {
>       throw new InvalidRequestException(format(INVALID_BUCKET_PROJECT__ERROR, gcsInternalConfig.getBucket()));
> ```

Minor: double __ in error msg name

**Comment by acasian-harness** [comment]
trigger ut4

**Comment by acasian-harness** [comment]
trigger uts

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52722#-:-NenOPptD4YRVLPf1VWD:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Comment by acasian-harness** [comment]
trigger uts

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52722#-:-NeoNohy3ukgT1qUsmtZ:bnfp4nl)* status: 17 file(s) to review. 1 of 2 approvals obtained. 

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java` line 165 at r4](https://reviewable.io/reviews/harness/harness-core/52722#-NeoNbRV4s_sBHayjg75:-NeoNbRV4s_sBHayjg76:b-jwlx5u) ([raw file](https://github.com/harness/harness-core/blob/fc78edbadf9f9907c3c5ed26945e0321f6aae5e8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java#L165)):*
> ```Java
>   public final String GCS_ARTIFACT_DOWNLOAD_FAILED = "Failed while trying to download GCS artifact with path: %s "
>       + "from bucket: %s and project: %s";
>   public final String GCS_ARTIFACT_DOWNLOAD_HINT = GCS_INVALID_ARTIFACT_PATH_HINT;
> ```

Minor: we could use the same const. 
___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java` line 172 at r4](https://reviewable.io/reviews/harness/harness-core/52722#-NeoNkJeCfD4BsTmzIvf:-NeoNkJeCfD4BsTmzIvg:bf26u1) ([raw file](https://github.com/harness/harness-core/blob/fc78edbadf9f9907c3c5ed26945e0321f6aae5e8/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/exception/SshExceptionConstants.java#L172)):*
> ```Java
>       "Failed while trying to calculate GCS artifact file size. Artifact details: path: %s "
>       + "from bucket: %s and project: %s";
>   public final String GCS_ARTIFACT_CALCULATE_SIZE_FAILED_HINT = GCS_INVALID_ARTIFACT_PATH_HINT;
> ```

The same as above.

**Comment by acasian-harness** [comment]
trigger ut7

**Review by vitsafronovici — APPROVED** [review]

**Comment by acasian-harness** [comment]
trigger review

**Pull request merged**
