### PR TITLE
feat: [CVS-9026]: Adding Debug API

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30680)

### CODE REVIEW

**Comment by arpit-harness** [comment]
trigger authorcheck

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30680)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/SLODebugResponse.java, line 39 at r2](https://reviewable.io/reviews/harness/harness-core/30680#-MvbXfmy3ItqZNQnxlti:-MvbXfmy3ItqZNQnxltj:b-inmwau) ([raw file](https://github.com/harness/harness-core/blob/5b49d0ee400dc3bec4af5834c48bb31e787fa627/300-cv-nextgen/src/main/java/io/harness/cvng/core/beans/SLODebugResponse.java#L39)):*
> ```Java
>   List<ServiceLevelIndicator> serviceLevelIndicatorList;
> 
>   SLOHealthIndicator sloHealthIndicator;
> ```

nit: We should include last DataCollectionTask also in this. You can do that as part of your next PR.
@abhijithharness 
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DebugService.java, line 14 at r2](https://reviewable.io/reviews/harness/harness-core/30680#-MvbXASK6HfN9Z4fowV8:-MvbXASL8Fg45Rt0MLXj:bnn75zq) ([raw file](https://github.com/harness/harness-core/blob/5b49d0ee400dc3bec4af5834c48bb31e787fa627/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L14)):*
> ```Java
> 
> public interface DebugService {
>   SLODebugResponse get(ProjectParams projectParams, String identifier);
> ```

please rename this get to getSLODebugResponse as we will add more items to it.

**Comment by kjoshi12345** [comment]
___
*[300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DebugService.java, line 14 at r2](https://reviewable.io/reviews/harness/harness-core/30680#-MvbXASK6HfN9Z4fowV8:-MvbYMUDCZ7wUni_wO7u:b-jyd62i) ([raw file](https://github.com/harness/harness-core/blob/5b49d0ee400dc3bec4af5834c48bb31e787fa627/300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/DebugService.java#L14)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

please rename this get to getSLODebugResponse as we will add more items to it.
</blockquote></details>

You can do this in the next PR.

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30680)* status: :shipit: complete! ✓

**Pull request merged**
