### PR TITLE
techdebt: [DEL-5270]: Removed 460-capability and a bunch of unused Capability classes

### PR DESCRIPTION
**Pull request by gn-harness**
## Describe your changes

Primary goal is to reduce dependency of 930-delegate-tasks module on 960-persistance.

I started with 950-delegate-tasks-beans/*/ capability module and wanted to create DTO version of the same for delegate and use morphia version for manager. As part of this exercise, I noticed that 460-capability does not seem to be used. Hence, I ended up cleaning up the entire module and a bunch of classes from the 950-delegate-tasks-beans/*/capability module too.

## Checklist
- [X] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39501)

### CODE REVIEW

**Comment by gn-harness** [comment]
trigger compile,checkstyle,ti0,ti1,ti2,ti3,ti4

**Comment by gn-harness** [comment]
trigger messagecheck,ti2,ti3

**Comment by gn-harness** [comment]
trigger buildnum

**Comment by gn-harness** [comment]
trigger ti0,ti1

**Comment by gn-harness** [comment]
trigger ti2

**Comment by gn-harness** [comment]
trigger ti3,compile

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 23 of 31 files at r1, 12 of 14 files at r2, 4 of 6 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39501)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 23 of 31 files at r1, 12 of 14 files at r2, 4 of 6 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39501)* status: :shipit: complete! ✓

**Review by USB-05 — APPROVED** [review]

**Pull request merged**
