### PR TITLE
fix: [CDS-79098]: Add user principal to pipeline start event

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Pipeline Start Audit event doesn't set the user principal.
pipeline_start_event

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)

### CODE REVIEW

**Review by shivagowda — APPROVED** [review]
lgtm

**Review by shivagowda — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Comment by rohitk-h** [comment]
trigger uts

**Review by senjucanon2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/52738#-Ne6gQV_2EjkS5vn5FX0:-Ne6gQVa53n4df2XgyVp:b6w6rbo) ([raw file](https://github.com/harness/harness-core/blob/06f37c205b81e4019b7d0ec04ce7519e7ae1a433/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L168)):*
> ```Java
>       principal = new UserPrincipal(nodeExecutionEventData.getTriggeredBy().getIdentifier(), email,
>           nodeExecutionEventData.getTriggeredBy().getIdentifier(), nodeExecutionEventData.getAccountIdentifier());
>     }
> ```

nodeExecutionEventData.getTriggeredBy().getIdentifier() value is null in some cases, this will lead to audit not being sent and outbox db will fail. Possible solutions for this are under discussion.

**Review by archit-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/52738#-Ne6gQV_2EjkS5vn5FX0:-Ne6k7LK9-ITIicKy-Ox:bude5g5) ([raw file](https://github.com/harness/harness-core/blob/06f37c205b81e4019b7d0ec04ce7519e7ae1a433/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L168)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

nodeExecutionEventData.getTriggeredBy().getIdentifier() value is null in some cases, this will lead to audit not being sent and outbox db will fail. Possible solutions for this are under discussion.
</blockquote></details>

if null, can we send default value for it? and why it will be null?

**Review by senjucanon2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/52738#-Ne6gQV_2EjkS5vn5FX0:-Ne78aot1XRF0GXQ5WZq:bb1y5se) ([raw file](https://github.com/harness/harness-core/blob/06f37c205b81e4019b7d0ec04ce7519e7ae1a433/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L168)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if null, can we send default value for it? and why it will be null?
</blockquote></details>

Sorry, debugged it further, it is not the identifier but the email value can be null. As we can see the null check is on "extraInfo" not on the email. And this email is set as identifier in AuthenticationInfoDTO, for which auditClient throws exception. Whenever the email is null we can use service Principal here.

**Comment by rohitk-h** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java` line 168 at r1](https://reviewable.io/reviews/harness/harness-core/52738#-Ne6gQV_2EjkS5vn5FX0:-NeCHA8b-t7YOW11n09_:boac9c8) ([raw file](https://github.com/harness/harness-core/blob/06f37c205b81e4019b7d0ec04ce7519e7ae1a433/pipeline-service/service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java#L168)):*
<details><summary><i>Previously, senjucanon2 (Vivek Dixit) wrote…</i></summary><blockquote>

Sorry, debugged it further, it is not the identifier but the email value can be null. As we can see the null check is on "extraInfo" not on the email. And this email is set as identifier in AuthenticationInfoDTO, for which auditClient throws exception. Whenever the email is null we can use service Principal here.
</blockquote></details>

updated.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52738)* status: :shipit: complete! ✓

**Comment by rohitk-h** [comment]
trigger uts

**Comment by rohitk-h** [comment]
trigger uts

**Pull request merged**
