### PR TITLE
[feat]: [PL-38975]: Run a migration to fix users with same email but different Harness uuid in CG v/s NG 

### PR DESCRIPTION
**Pull request by shashank-harness**
## Describe your changes
Described in this JIRA comment - https://harness.atlassian.net/browse/PL-38975?focusedCommentId=503456

**Testing:**
- Basic sanity pre and post migration for NG user.
- Tested exact CFD usecase.
     - Add a user in NG and provide them bunch of roles and add them to multiple groups, scopes that have roles themselves -> User will get appropriate access on NG
     - Disable NG in Account and delete and re-create user in CG.
     - Enable NG again
     - At this point, User ids of this user should not match for same email between CG mgr and NG mgr -> User will not be able to open NG now
     - Run my migration. -> User should get all access back

### Pseudo code of what we have implemented:

 for each entry in NG UserMetaData :
     - search with email in CG
         - if not found, then delete entry from UserMetaData.
         - if found, then compare uuid of NG vs CG
             - if uuid same - do nothing 
             - if uuid different
                 - in single transaction {Using mongotemplate - delete userMetaData ng_uuid and add new entry cg_uuid}
                 - fetch all entries from NG:userMembershipV2 for ng_uuid and add corresponding new entries to userMembershipV2 with cg_uuid -> Will create ACLs 
                 - AccessControl:roleassignment
                     - fetch all entries for principalIdentifier=ng_uuid
                     - create corresponding new entries for principalIdentifier=cg_uuid -> This will create ACLs
                     - delete all entries for  principalIdentifier=uuid_old
                 - NG Usergroup update-> delete uuid_old and add uuid_new
                     - This will take care of Access Control's user group
                 - Delete old entry from userMembershipV2 with uuid_old
 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48795)

### CODE REVIEW

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger messagecheck

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/FixInconsistentUserDataMigrationJob.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/48795#-NXFhhGS2ScUdjVdJUmH:-NXFhhGS2ScUdjVdJUmI:b39pinz) ([raw file](https://github.com/harness/harness-core/blob/8ef6e110982db7093b7e0230b7617d586adb31e8/120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/FixInconsistentUserDataMigrationJob.java#L43)):*
> ```Java
>   public void start() throws Exception {
>     log.info(DEBUG_MESSAGE + "started...");
>     defaultUserGroupJobFuture = executorService.scheduleWithFixedDelay(migrationService, 15, 15, TimeUnit.MINUTES);
> ```

I think we decided this job should run once in 24 hours. So change the delay accordingly.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/FixInconsistentUserDataMigrationService.java` line 314 at r2](https://reviewable.io/reviews/harness/harness-core/48795#-NXG0HEr-DmLUq3rB2YY:-NXG0HEr-DmLUq3rB2YZ:b-u695d5) ([raw file](https://github.com/harness/harness-core/blob/8ef6e110982db7093b7e0230b7617d586adb31e8/120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/FixInconsistentUserDataMigrationService.java#L314)):*
> ```Java
>       String cgUserId, Scope scope, List<RoleAssignmentDTO> existingRoleAssignmentDTOS) {
>     List<RoleAssignmentDTO> newRoleAssignmentDTOS = new ArrayList<>();
>     for (RoleAssignmentDTO roleAssignmentDTO : existingRoleAssignmentDTOS) {
> ```

We will need to recreate both manage and Non-Managed Role assignments.

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/FixInconsistentUserDataMigrationJob.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/48795#-NXFhhGS2ScUdjVdJUmH:-NXG8IdB4gfokvUn4Qjy:b5ytrlx) ([raw file](https://github.com/harness/harness-core/blob/8ef6e110982db7093b7e0230b7617d586adb31e8/120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/FixInconsistentUserDataMigrationJob.java#L43)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

I think we decided this job should run once in 24 hours. So change the delay accordingly.
</blockquote></details>

making to 2 hours as discussed

**Comment by shashank-harness** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/FixInconsistentUserDataMigrationService.java` line 314 at r2](https://reviewable.io/reviews/harness/harness-core/48795#-NXG0HEr-DmLUq3rB2YY:-NXG8Oel-7_Wl6_rPLQg:b-ks9d0z) ([raw file](https://github.com/harness/harness-core/blob/8ef6e110982db7093b7e0230b7617d586adb31e8/120-ng-manager/src/main/java/io/harness/ng/accesscontrol/migrations/services/FixInconsistentUserDataMigrationService.java#L314)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

We will need to recreate both manage and Non-Managed Role assignments.
</blockquote></details>

its already taken care of in adding and removing Usermmberships

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795#-:-NXGUgwsBXavZoNdYffs:bnfp4nl)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Comment by shashank-harness** [comment]
trigger uts

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 3 of 5 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795)* status: 6 file(s) to review.

**Review by pbarapatre10 — APPROVED** [review]
Please lets take a back up of all entities with help from DB team which we are deleting through this. 
Thanks

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795#-:-NXIjs577G8pYs4Uq6BF:b-odlvib)* status: 6 file(s) to review.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48795)* status: :shipit: complete! ✓

**Comment by shashank-harness** [comment]
trigger uts

**Pull request merged**
