### PR TITLE
feat: [DEL-5652]: provide support for auto revoking delegate token

### PR DESCRIPTION
**Pull request by arpit3107**
## Describe your changes
Problem: While creating a delegate token there isn't any support for auto revoking tokens after a time.

Solution: While creating a delegate token, take an additional parameter "revokeAfter" and create a scheduled job of period 1 hour to autoRevoke tokens for which revokeAfter has passed.

Testing:
1. Create few tokens in cg and ng without this change.
2. Create few tokens in cg and ng after this change.
3. For testing, I updated the job period to 10 seconds and verified that token was marked as revoked correctly.

Screenshot 2023-02-22 at 8 15 13 PM

Screenshot 2023-02-22 at 8 14 28 PM

Screenshot 2023-02-22 at 8 09 38 PM

Screenshot 2023-02-22 at 8 05 48 PM

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43672)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMXyPz4DlSnRqlbjO6:-NOMXyPz4DlSnRqlbjO7:b-q7w65) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L48)):*
> ```Java
>       @Query(NGCommonEntityConstants.ORG_KEY) String orgIdentifier,
>       @Query(NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @Query("tokenName") @NotNull String tokenName, @Query("expiry") Long revokeAfter);
> ```

lets rename it to revokeAfter as well

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMY3J1Dg5x2P2RbY3m:-NOMY3J1Dg5x2P2RbY3n:b5todmt) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L100)):*
> ```Java
>           NGCommonEntityConstants.PROJECT_KEY) String projectIdentifier,
>       @Parameter(description = "Delegate Token name") @QueryParam("tokenName") @NotNull String tokenName,
>       @Parameter(description = "Time after which delegate token will be auto revoked") @QueryParam(
> ```

if we are revoking it in background then mention in description that it can take plus that time to get it auto revoked

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMYQxxEAxLlGugAYyh:-NOMYQxxEAxLlGugAYyi:b-ip8gie) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L84)):*
> ```Java
>                                       .value(encodeBase64(Misc.generateSecretKey()))
>                                       .createdByNgUser(SourcePrincipalContextBuilder.getSourcePrincipal())
>                                       .revokeAfter(revokeAfter)
> ```

where are we marking the token revoked?

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43672)* status: 10 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMXyPz4DlSnRqlbjO6:-NOmSXRzCEToD0qyhDQJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/120-ng-manager/src/main/java/io/harness/ng/core/delegate/client/DelegateNgManagerCgManagerClient.java#L48)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

lets rename it to revokeAfter as well
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMY3J1Dg5x2P2RbY3m:-NOmScD0AorJXN0STxDq:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L100)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

if we are revoking it in background then mention in description that it can take plus that time to get it auto revoked 
</blockquote></details>

Done.
___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 84 at r2](https://reviewable.io/reviews/harness/harness-core/43672#-NOMYQxxEAxLlGugAYyh:-NOmSi06BcBHOZm2rPk8:b-t1z23d) ([raw file](https://github.com/harness/harness-core/blob/b4140ffa1cdc1af6137ab7164371586d838533a6/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L84)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

where are we marking the token revoked?
</blockquote></details>

Added, there is a scheduled thread

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 237 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmXvc59PesCb6kv_Pk:-NOmXvc7747rIvN9CcQO:b-719g1z) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L237)):*
> ```Java
>     List<DelegateToken> delegateTokenList = persistence.createQuery(DelegateToken.class)
>                                                 .filter(DelegateTokenKeys.status, DelegateTokenStatus.ACTIVE)
>                                                 .field(DelegateTokenKeys.revokeAfter)
> ```


1. shouldn't you check that revokeAfter exists?
2. by default for newly created tokens wouldn't that be zero? wouldn't you need to check for that as well?

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 102 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmYSR48mKPEJbyb8nu:-NOmYSR48mKPEJbyb8nv:b-yfol27) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L102)):*
> ```Java
>       @Parameter(
>           description =
>               "Time after which this token should be marked as revoked. There can be a difference of maximum 1 hour between this revokeAfter and the actual revocation time.")
> ```

the description should say "epoch time after which the token will be marked as revoked. There can be a delay of upto one hour from the epoch value provided and actual revoking of the token"

**Comment by raghuAtWings** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java` line 102 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmYSR48mKPEJbyb8nu:-NOmYp0Q0dRfMatmQjWn:b-yen581) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/120-ng-manager/src/main/java/io/harness/ng/core/delegate/resources/DelegateTokenNgResource.java#L102)):*
> the description should say "epoch time (in milliseconds) after which the token will be marked as revoked. There can be a delay of upto one hour from the epoch value provided and actual revoking of the token"

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 83 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmYxCM2LJQ4nKnszRr:-NOmYxCM2LJQ4nKnszRs:b-2bcqa4) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L83)):*
> ```Java
>                                       .build();
> 
>     validateCreateDelegateTokenRequest(delegateToken);
> ```

why do we need to validate?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 2 of 8 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43672)* status: 0 of 1 approvals obtained.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43672)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 83 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmYxCM2LJQ4nKnszRr:-NOspHkQCJSjdvJDq3tx:b-m9l9ve) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L83)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need to validate?
</blockquote></details>

So that a user doesnt create a token with revokeAfter less than current time. As its of no use.
___
*[`400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java` line 237 at r5](https://reviewable.io/reviews/harness/harness-core/43672#-NOmXvc59PesCb6kv_Pk:-NOspOqE49S-JfO-cYTL:bxpbwzk) ([raw file](https://github.com/harness/harness-core/blob/32717e698542864382061311446960e20efce67f/400-rest/src/main/java/io/harness/service/impl/DelegateNgTokenServiceImpl.java#L237)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>


1. shouldn't you check that revokeAfter exists?
2. by default for newly created tokens wouldn't that be zero? wouldn't you need to check for that as well?
</blockquote></details>

To avoid these things, i am marking revokAfter as Long. So it will be null if not provided. And hence we dont need to check for existence also.

**Comment by arpit3107** [comment]
trigger messagecheck

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43672)* status: :shipit: complete! ✓

**Pull request merged**
