### PR TITLE
feat: [SRM-13159]: Refactoring SLO V2 APIs.

### PR DESCRIPTION
**Pull request by sathish-soundarapandian**
## Describe your changes
 Lombok & BeanParam in having issues with inherited fields, so did a workaround of using it as plain way.
 Seems accountId is the convention for accountIdentifier, so changed it accordingly.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)

### CODE REVIEW

**Review by Varsha-lalwani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ResourcePathParams.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuNDfl5JtMXaXp7wgB:-NJuNDfl5JtMXaXp7wgC:bh83qiu) ([raw file](https://github.com/harness/harness-core/blob/7654514aeb54f2e2b9cfbfd99b6282e1ef9ffdd0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ResourcePathParams.java#L32)):*
> ```Java
> @AllArgsConstructor
> @EqualsAndHashCode(callSuper = true)
> public class ResourcePathParams extends ProjectPathParams {
> ```

why did we have to remove this?



_Code quote:_
```Java
 extends ProjectPathParams
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuN-jh20cfsNf0fIP9:-NJuN-jh20cfsNf0fIPA:b-44ssog) ([raw file](https://github.com/harness/harness-core/blob/9906b9db8acba22ecca731117428431e5640fea8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java#L80)):*
> ```Java
>         .build();
>   }
> }
> ```

Why is this piece of code in this util? and this isn't used anywhere, why is it added



_Code quote:_
```Java
  public static ProjectParams buildProjectParamsFromPathParams(ProjectPathParams projectPathParams) {
    return ProjectParams.builder()
        .accountIdentifier(projectPathParams.getAccountIdentifier())
        .orgIdentifier(projectPathParams.getOrgIdentifier())
        .projectIdentifier(projectPathParams.getProjectIdentifier())
        .build();
  }

  public static ProjectParams buildProjectParamsFromPathParams(ResourcePathParams resourcePathParams) {
    return ProjectParams.builder()
        .accountIdentifier(resourcePathParams.getAccountIdentifier())
        .orgIdentifier(resourcePathParams.getOrgIdentifier())
        .projectIdentifier(resourcePathParams.getProjectIdentifier())
        .build();
  }
}
```

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)_ status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ResourcePathParams.java` line 32 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuNDfl5JtMXaXp7wgB:-NJuNDfl5JtMXaXp7wgC:bh83qiu) ([raw file](https://github.com/harness/harness-core/blob/7654514aeb54f2e2b9cfbfd99b6282e1ef9ffdd0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/params/ResourcePathParams.java#L32)):_
> 
> > ```java
> > @AllArgsConstructor
> > @EqualsAndHashCode(callSuper = true)
> > public class ResourcePathParams extends ProjectPathParams {
> > ```
> 
> why did we have to remove this?
> 
> _Code quote:_
> 
> ```java
>  extends ProjectPathParams
> ```
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuN-jh20cfsNf0fIP9:-NJuN-jh20cfsNf0fIPA:b-44ssog) ([raw file](https://github.com/harness/harness-core/blob/9906b9db8acba22ecca731117428431e5640fea8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java#L80)):_
> 
> > ```java
> >         .build();
> >   }
> > }
> > ```
> 
> Why is this piece of code in this util? and this isn't used anywhere, why is it added
> 
> _Code quote:_
> 
> ```java
>   public static ProjectParams buildProjectParamsFromPathParams(ProjectPathParams projectPathParams) {
>     return ProjectParams.builder()
>         .accountIdentifier(projectPathParams.getAccountIdentifier())
>         .orgIdentifier(projectPathParams.getOrgIdentifier())
>         .projectIdentifier(projectPathParams.getProjectIdentifier())
>         .build();
>   }
> 
>   public static ProjectParams buildProjectParamsFromPathParams(ResourcePathParams resourcePathParams) {
>     return ProjectParams.builder()
>         .accountIdentifier(resourcePathParams.getAccountIdentifier())
>         .orgIdentifier(resourcePathParams.getOrgIdentifier())
>         .projectIdentifier(resourcePathParams.getProjectIdentifier())
>         .build();
>   }
> }
> ```

1. Lombok + BeanParam has known issue with inheritance. super class fields are not visible when accessed, so as a workaround did it in the plain way.
2. Those two functions in the util file are used in ServiceLevelObjectiveNgProjectResource.java as of now and it can be used in the future for other resources as well. It is more generalised, so added it in the utils.

**Review by Varsha-lalwani — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: 1 file(s) to review. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuN-jh20cfsNf0fIP9:-NJuP2PDAdOZdomU-9oq:bmcs4y0) ([raw file](https://github.com/harness/harness-core/blob/9906b9db8acba22ecca731117428431e5640fea8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java#L80)):*
<details><summary><i>Previously, sathish-soundarapandian (Sathish) wrote…</i></summary><blockquote>

1. Lombok + BeanParam has known issue with inheritance. super class fields are not visible when accessed, so as a workaround did it in the plain way.
2. Those two functions in the util file are used in ServiceLevelObjectiveNgProjectResource.java as of now and it can be used in the future for other resources as well. It is more generalised, so added it in the utils.

</blockquote></details>

nit: These methods can be added in ProjectPathParams and ResourcePathParams itself.

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuN-jh20cfsNf0fIP9:-NKD_-nH6OLQa42svUG_:b-b1q9fg) ([raw file](https://github.com/harness/harness-core/blob/9906b9db8acba22ecca731117428431e5640fea8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java#L80)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

nit: These methods can be added in ProjectPathParams and ResourcePathParams itself.
</blockquote></details>

 +1 : These methods can be added as ProjectParams.fromResourcePathParams()

**Comment by sathish-soundarapandian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)_ status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained.
> 
> _[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java` line 80 at r2](https://reviewable.io/reviews/harness/harness-core/41913#-NJuN-jh20cfsNf0fIP9:-NKD_-nH6OLQa42svUG_:b-b1q9fg) ([raw file](https://github.com/harness/harness-core/blob/9906b9db8acba22ecca731117428431e5640fea8/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/utils/ScopedInformation.java#L80)):_
> 
> Previously, Varsha-lalwani (Varsha Lalwani) wrote…
> +1 : These methods can be added as ProjectParams.fromResourcePathParams()

Done

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: 3 file(s) to review.

**Review by AbhijithHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: 3 file(s) to review.

**Review by AbhijithHarness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41913)* status: :shipit: complete! ✓

**Pull request merged**
