### PR TITLE
feat: [CDS-41239]: added AWS to CommandStep

### PR DESCRIPTION
**Pull request by vitsafronovici**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)

### CODE REVIEW

**Comment by vitsafronovici** [comment]
trigger messagecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 4 Issues 
* Code issue 3 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35995)

**Review by acasian-harness — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 419 at r1](https://reviewable.io/reviews/harness/harness-core/35995#-N8cLoZI8MJ_FNsFEL_5:-N8cLoZI8MJ_FNsFEL_6:b-sb3w1e) ([raw file](https://github.com/harness/harness-core/blob/14e427c1062eda351d2cfaec147e0e1d34fad4d8/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L419)):*
> ```Java
>     final AwsTaskParams awsTaskParams;
> 
>     if (StringUtils.isEmpty(awsInfraDelegateConfig.getAutoScalingGroupName())) {
> ```

let's use  our internal `EmptyPredicate#isEmpty()` instead and also we can get rid of apache import.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/35995#-N8cMZhu0iml7jo-IM4f:-N8cMZhu0iml7jo-IM4g:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/14e427c1062eda351d2cfaec147e0e1d34fad4d8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L223)):*
> ```Java
>                 .region(awsInfrastructureOutcome.getRegion());
> 
>         if (StringUtils.isEmpty(awsInfrastructureOutcome.getAutoScalingGroupName())) {
> ```

same here

**Review by vitsafronovici — COMMENTED** [review]
xxx

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995#-:-N8cTKFx4o5hZC3-plbr:b2nigcz)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java` line 419 at r1](https://reviewable.io/reviews/harness/harness-core/35995#-N8cLoZI8MJ_FNsFEL_5:-N8cTGp63Ff8Ik7hqsFU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14e427c1062eda351d2cfaec147e0e1d34fad4d8/125-cd-nextgen/src/main/java/io/harness/cdng/infra/steps/InfrastructureTaskExecutableStep.java#L419)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

let's use  our internal `EmptyPredicate#isEmpty()` instead and also we can get rid of apache import.
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 223 at r1](https://reviewable.io/reviews/harness/harness-core/35995#-N8cMZhu0iml7jo-IM4f:-N8cTIM1-EO82OZyf-z7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/14e427c1062eda351d2cfaec147e0e1d34fad4d8/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L223)):*
<details><summary><i>Previously, acasian-harness (Alexandru Casian) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: :shipit: complete! ✓

**Comment by vitsafronovici** [comment]
trigger ti0

**Comment by vitsafronovici** [comment]
trigger ti4

**Comment by vitsafronovici** [comment]
trigger ti4

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Review by acasian-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995#-:-N8dvFaU7kk9Uehwktjb:bnfp4nl)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed 1 of 59 files at r4, 58 of 58 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: :shipit: complete! ✓

**Review by vitsafronovici — COMMENTED** [review]
xxx

> Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 59 files at r4, 58 of 58 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995#-:-N8h1Mlg8xzHhGo0m9A2:b2nigcz)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 59 files at r4, 2 of 58 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995#-:-N8hN-ri60oJCSP2iwWE:bnfp4nl)* status: :shipit: complete! ✓

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 59 files at r4, 17 of 58 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35995)* status: :shipit: complete! ✓

**Comment by arvind-choudhary-h** [comment]
trigger codebasehash

**Pull request merged**
