### PR TITLE
fix: [IDP-1056]: Score APIs for plugins - fix for adding weights, description response also other fixes

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52097)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52097)* status: 6 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java` line 156 at r1](https://reviewable.io/reviews/harness/harness-core/52097#-NcpZwax2oFgow6WKkPy:-NcpZwax2oFgow6WKkPz:bkznzod) ([raw file](https://github.com/harness/harness-core/blob/6b3bd491b45ea708460868fb3c68896cd6bed1b8/idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java#L156)):*
> ```Java
>   public List<ScorecardScore> getScorecardScoreOverviewForAnEntity(String accountIdentifier, String entityIdentifier) {
>     List<ScoreEntity> scoreEntities =
>         scoreRepository.findAllByAccountIdentifierAndEntityIdentifier(accountIdentifier, entityIdentifier);
> ```

Instead of fetching all the scores for all scorecards, can we just fetch the latest one for each scorecard from mongo itself? We might need a groupBy query.
We would have 2 scores per day. And we store 6 months scores. Plus the re-calibrates initiated by the user. So about 500 which isn't a big number to load into memory. 
But good to optimise this. If not now, later.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java` line 183 at r1](https://reviewable.io/reviews/harness/harness-core/52097#-Ncpae3Z82XPmzGk3gwa:-Ncpae3Z82XPmzGk3gwb:b-o6tz2k) ([raw file](https://github.com/harness/harness-core/blob/6b3bd491b45ea708460868fb3c68896cd6bed1b8/idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java#L183)):*
> ```Java
>     if (!scorecardDetails.isPublished()) {
>       throw new UnsupportedOperationException(String.format(
>           "Recalibrated scores cannot be calculated for unpublished scorecard - %s for entity - %s in account - %s ",
> ```

nit: `will not` :sweat_smile: 



_Code quote:_
```Java
cannot
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java` line 190 at r1](https://reviewable.io/reviews/harness/harness-core/52097#-Ncpav2mEApvZ4QLdSjn:-Ncpav2mEApvZ4QLdSjo:b-sunf2y) ([raw file](https://github.com/harness/harness-core/blob/6b3bd491b45ea708460868fb3c68896cd6bed1b8/idp-service/src/main/java/io/harness/idp/scorecard/scores/service/ScoreServiceImpl.java#L190)):*
> ```Java
>         accountIdentifier, Collections.singletonList(scorecardIdentifier), Collections.singletonList(entityIdentifier));
> 
>     List<ScoreEntity> scoreEntities =
> ```

Same comment as previous. But should be a fairly simple query here as we know all the identifiers here. Just a sort and limit would be needed. And it would be faster in mongo if we have right indexes rather than doing it in java.

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52097)* status: 11 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/entities/ScoreEntity.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/52097#-NcuLuBo7LPQFE9vJXj0:-NcuLuBo7LPQFE9vJXj1:b-xgm7kk) ([raw file](https://github.com/harness/harness-core/blob/c80cb590a7799d877d5007431a2dfca0688dac7a/idp-service/src/main/java/io/harness/idp/scorecard/scores/entities/ScoreEntity.java#L54)):*
> ```Java
>                  .field(ScoreKeys.lastComputedTimestamp)
>                  .build())
>         .add(CompoundMongoIndex.builder()
> ```

We might not need these 2. The first one would be enough.
Ref: https://www.mongodb.com/docs/manual/core/indexes/index-types/index-compound/#index-prefixes
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustom.java` line 17 at r2](https://reviewable.io/reviews/harness/harness-core/52097#-NcuMZoR8GW4Rsjl0QNO:-NcuMZoS6-MLhAzkuuHO:b-t29geg) ([raw file](https://github.com/harness/harness-core/blob/c80cb590a7799d877d5007431a2dfca0688dac7a/idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustom.java#L17)):*
> ```Java
> @OwnedBy(HarnessTeam.IDP)
> public interface ScoreRepositoryCustom {
>   AggregationResults<ScoreEntityByScorecardIdentifier> getAllLatestScoresForScorecardsForAnEntity(
> ```

nit: How about `getAllLatestScoresByScorecardsForAnEntity` instead?



_Code quote:_
```Java
getAllLatestScoresForScorecardsForAnEntity
```

**Comment by devesh-harness** [comment]
trigger ut4, ut8

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
