### PR TITLE
feat: [CDS-48059]: Add junit tests for TAS

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42628)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger messagecheck

**Comment by RishabhGupta34** [comment]
trigger tin0

**Comment by RishabhGupta34** [comment]
trigger ti0

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42628)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBGAppSetupStep.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/42628#-NLuQKIO3qFUlTEl2ihn:-NLuQKIO3qFUlTEl2iho:bj1qw13) ([raw file](https://github.com/harness/harness-core/blob/3cfffef6cd34a314abf1b63227dac82952b37f8d/125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBGAppSetupStep.java#L180)):*
> ```Java
>               .newAppGuid(response.getNewApplicationInfo().getApplicationGuid())
>               .finalRoutes(routeMaps)
>               .tempRoutes(response.getNewApplicationInfo().getAttachedRoutes());
> ```

the value of tempRoutes variable should be what user has configured in the Step. Why are we setting it from New Application. Total routes attached to new application will be (temp routes + routes defined in manifest)

**Comment by RishabhGupta34** [comment]
> 



> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/42628)_ status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained.
> 
> _[`125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBGAppSetupStep.java` line 180 at r3](https://reviewable.io/reviews/harness/harness-core/42628#-NLuQKIO3qFUlTEl2ihn:-NLuQKIO3qFUlTEl2iho:bj1qw13) ([raw file](https://github.com/harness/harness-core/blob/3cfffef6cd34a314abf1b63227dac82952b37f8d/125-cd-nextgen/src/main/java/io/harness/cdng/tas/TasBGAppSetupStep.java#L180)):_
> 
> > ```java
> >               .newAppGuid(response.getNewApplicationInfo().getApplicationGuid())
> >               .finalRoutes(routeMaps)
> >               .tempRoutes(response.getNewApplicationInfo().getAttachedRoutes());
> > ```
> 
> the value of tempRoutes variable should be what user has configured in the Step. Why are we setting it from New Application. Total routes attached to new application will be (temp routes + routes defined in manifest)

We are setting it from new application, incase the user has not configured it in the step. In that case the temp route is a random one, so we won't get that value from the step parameters

**Review by sourabh-awashti — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42628)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42628#-:-NLyCHGP9EpuleHqgcbk:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
