### PR TITLE
Feat: [SRM-12115]: Remove FFs

### PR DESCRIPTION
**Pull request by AbhijithHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39252)

### CODE REVIEW

**Comment by praveensugavanam** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/APMVerificationState.java` line 157 at r2](https://reviewable.io/reviews/harness/harness-core/39252#-NFPtQWp9BddTGTNWHAD:-NFPtQWs01IWSfmhyifb:b-3kl2hm) ([raw file](https://github.com/harness/harness-core/blob/647b7f4f1434ff39e43975a9d9d0748139a64854/400-rest/src/main/java/software/wings/sm/states/APMVerificationState.java#L157)):*
> ```Java
>   @Override
>   protected Optional<FeatureName> getCVTaskFeatureName() {
>     return Optional.of(FeatureName.CUSTOM_APM_CV_TASK);
> ```

you can also remove software.wings.sm.states.APMVerificationState#createDataCollectionInfo since that wont be used anymore either.

**Comment by praveensugavanam** [comment]
*[`400-rest/src/main/java/software/wings/verification/apm/APMCVServiceConfiguration.java` line 51 at r2](https://reviewable.io/reviews/harness/harness-core/39252#-NFPubJRDGMmNLayYBrY:-NFPubJRDGMmNLayYBrZ:bipoe4l) ([raw file](https://github.com/harness/harness-core/blob/647b7f4f1434ff39e43975a9d9d0748139a64854/400-rest/src/main/java/software/wings/verification/apm/APMCVServiceConfiguration.java#L51)):*
> ```Java
>   @Override
>   public FeatureName getCVTaskBasedCollectionFeatureFlag() {
>     return FeatureName.CUSTOM_APM_24_X_7_CV_TASK;
> ```

this will cause a problem since isCVTaskBasedCollectionFeatureFlagged is returning true, the base class throws exception as can be seen below. This will end up in a failure for all data collection. How was this tested ? 



_Code snippet:_
```Java
public FeatureName getCVTaskBasedCollectionFeatureFlag() {
    throw new UnsupportedOperationException(
        "This needs to be implemented if isCVTaskBasedCollectionEnabled returns true");
  }
```

**Review by praveensugavanam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39252)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/AppDynamicsState.java` line 528 at r2](https://reviewable.io/reviews/harness/harness-core/39252#-NFPvPw13cBGQsXmsv4X:-NFPvPw13cBGQsXmsv4Y:bj8azpy) ([raw file](https://github.com/harness/harness-core/blob/647b7f4f1434ff39e43975a9d9d0748139a64854/400-rest/src/main/java/software/wings/sm/states/AppDynamicsState.java#L528)):*
> ```Java
>   @Override
>   protected Optional<FeatureName> getCVTaskFeatureName() {
>     return Optional.of(FeatureName.APPD_CV_TASK);
> ```

you can also remove createDataCollectionInfo method
___
*[`400-rest/src/main/java/software/wings/sm/states/NewRelicState.java` line 318 at r2](https://reviewable.io/reviews/harness/harness-core/39252#-NFPvS4h-RsFU28kMYMm:-NFPvS4h-RsFU28kMYMn:brwkbko) ([raw file](https://github.com/harness/harness-core/blob/647b7f4f1434ff39e43975a9d9d0748139a64854/400-rest/src/main/java/software/wings/sm/states/NewRelicState.java#L318)):*
> ```Java
>   @Override
>   protected Optional<FeatureName> getCVTaskFeatureName() {
>     return Optional.of(FeatureName.NEW_RELIC_CV_TASK);
> ```

you can also remove createDataCollectionInfo method.
___
*[`400-rest/src/main/java/software/wings/verification/newrelic/NewRelicCVServiceConfiguration.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/39252#-NFPvVOr8E3n03RUnoH1:-NFPvVOr8E3n03RUnoH2:b4s0u7q) ([raw file](https://github.com/harness/harness-core/blob/647b7f4f1434ff39e43975a9d9d0748139a64854/400-rest/src/main/java/software/wings/verification/newrelic/NewRelicCVServiceConfiguration.java#L73)):*
> ```Java
>   @Override
>   public FeatureName getCVTaskBasedCollectionFeatureFlag() {
>     return FeatureName.NEWRELIC_24_7_CV_TASK;
> ```

same as above. THis will throw an exception if you remove this method when the `isCVTaskBasedCollectionFeatureFlagged` returns true

**Comment by AbhijithHarness** [comment]
trigger ti4

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 6 of 7 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39252)* status: Some of the checks are too old.

**Review by praveensugavanam — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39252)* status: :shipit: complete! ✓

**Pull request merged**
