### PR TITLE
feat: [CDS-45549]: add terragrunt provision steps and plan creators i…

### PR DESCRIPTION
**Pull request by vlica-harness**
…n NG

In this PR are added Plan Step Creators for Terragrunt steps (plan, apply, destroy, rollback) along the variable creators. 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)

### CODE REVIEW

**Review by tmacari-harness — CHANGES_REQUESTED** [review]
> Reviewed 51 of 68 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/terragrunt/TerragruntPlanStepPlanCreator.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPUk2u3addhffr4gHZ:-NHPUk2u3addhffr4gH_:b-590pr8) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/terragrunt/TerragruntPlanStepPlanCreator.java#L52)):*
> ```Java
>     TerragruntPlanStepParameters terragruntPlanStepParameters =
>         (TerragruntPlanStepParameters) ((StepElementParameters) stepParameters).getSpec();
>     terragruntPlanStepParameters.setStepFqn(stepFqn);
> ```

would we want to have some new logic around stepFqn?
cc @abosii-harness 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPV73B8_EVlYARbtey:-NHPV73B8_EVlYARbtez:b-x31q25) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java#L210)):*
> ```Java
>     engineSteps.put(TerragruntPlanStep.STEP_TYPE, TerragruntApplyStep.class);
>     engineSteps.put(TerragruntPlanStep.STEP_TYPE, TerragruntDestroyStep.class);
>     engineSteps.put(TerragruntPlanStep.STEP_TYPE, TerragruntRollbackStep.class);
> ```

TerragruntPlanStep.STEP_TYPE 4 times
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPVU_h5lKTkVlm7tdT:-NHPVU_h5lKTkVlm7tdU:bode8ag) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L192)):*
> ```Java
>   TERRAGRUNT_DESTROY("Terragrunt Destroy", Arrays.asList(ServiceDefinitionType.values()),
>       "Infrastructure Provisioners/Terragrunt", StepSpecTypeConstants.TERRAGRUNT_DESTROY),
>   @JsonProperty(StepSpecTypeConstants.TERRAFORM_PLAN)
> ```

StepSpecTypeConstants.TERRAFORM_PLAN ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 193 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPVYpg-SQp6NEx9IVg:-NHPVYpg-SQp6NEx9IVh:bgiqlr7) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L193)):*
> ```Java
>       "Infrastructure Provisioners/Terragrunt", StepSpecTypeConstants.TERRAGRUNT_DESTROY),
>   @JsonProperty(StepSpecTypeConstants.TERRAFORM_PLAN)
>   TERRAGRUNT_ROLLBACK("Terragrunt Plan", Arrays.asList(ServiceDefinitionType.values()),
> ```

Terragrunt Plan ?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/InlineTerragruntBackendConfigSpec.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPY74-ED2P78w-0KZZ:-NHPY74-ED2P78w-0KZ_:beszyp1) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/InlineTerragruntBackendConfigSpec.java#L34)):*
> ```Java
>   @Override
>   public String getType() {
>     return TerragruntVarFileTypes.Inline;
> ```

Probably it is like that for terraform, but here lets have different constants: TerragruntVarFileTypes and TerragruntBackendConfigFileTypes
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/RemoteTerragruntBackendConfigSpec.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPYeNG3AwZSBtmlnew:-NHPYeNG3AwZSBtmlnex:b-hvj1yl) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/RemoteTerragruntBackendConfigSpec.java#L34)):*
> ```Java
>   @Override
>   public String getType() {
>     return TerragruntVarFileTypes.Remote;
> ```

Separate type for backend config
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPZkN52shYhQ-PTxga:-NHPZkN52shYhQ-PTxgb:b-3nt5mv) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java#L30)):*
> ```Java
> @OwnedBy(HarnessTeam.CDP)
> @Slf4j
> public class TerragruntApplyStep extends TaskExecutableWithRollbackAndRbac<TerragruntApplyTaskResponse> {
> ```

shouldn't we support task chain in order to fetch render var files?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHP_83M8fPBNDhjMvAk:-NHP_83M8fPBNDhjMvAl:b-72vip3) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java#L41)):*
> ```Java
> 
>   @Override
>   public void validateResources(Ambiance ambiance, StepElementParameters stepParameters) {}
> ```

let's add here a check for FF so in case someone would try to ad steps through YAM it would throw an error with a meaningful message.
The same on other steps.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHP_cESBMiosswoREp-:-NHP_cESBMiosswoREp0:bdoqwpb) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java#L86)):*
> ```Java
>   @Override
>   public String getFacilitatorType() {
>     return OrchestrationFacilitatorType.TASK;
> ```

If we ent to support task chain we should change here also
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPa9vy4LOhjDwcarx-:-NHPa9vy4LOhjDwcarx0:b-plvqa8) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java#L90)):*
> ```Java
> 
>   @Override
>   public Map<String, ParameterField<String>> extractConnectorRefs() {
> ```

We should extract connector refs for backend config also if it is remote.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPb0-yBRMWYeQ689Ls:-NHPb0-yBRMWYeQ689Lt:b-cj3xda) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java#L30)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.CDP)
> public class TerragruntDestroyStep extends TaskExecutableWithRollbackAndRbac<TerragruntDestroyTaskResponse> {
> ```

The same, should it support task chain?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStepInfo.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPb_qk6j_W9I1VzB75:-NHPb_qk6j_W9I1VzB76:b-563hnp) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStepInfo.java#L117)):*
> ```Java
>       }
>     }
>     return connectorRefMap;
> ```

the same,, add backend config connector ref.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanExecutionData.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPcF6_8cz3IVb6qk3w:-NHPcF6_8cz3IVb6qk3x:b42w01j) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanExecutionData.java#L94)):*
> ```Java
>     terragruntConfigFilesWrapper.validateParams();
>     Validator.notNullCheck("Terragrunt Plan command is null", command);
>     Validator.notNullCheck("Secret Manager Ref for Tf plan is null", secretManagerRef);
> ```

Tf plan >> Terragrunt plan
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPcQE7A_2FcRquDWZL:-NHPcQE7A_2FcRquDWZM:b-bhdp62) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java#L30)):*
> ```Java
> @Slf4j
> @OwnedBy(HarnessTeam.CDP)
> public class TerragruntPlanStep extends TaskExecutableWithRollbackAndRbac<TerragruntPlanTaskResponse> {
> ```

Same question... should we support task chain?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStepParameters.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPclIX0qSGjWZIst75:-NHPclIX0qSGjWZIst76:bd3s8jg) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStepParameters.java#L41)):*
> ```Java
>       TerragruntPlanExecutionDataParameters configuration) {
>     super(provisionerIdentifier, delegateSelectors);
>     this.stepFqn = stepFqn;
> ```

same here, do we want to build logic around stepFqn?
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPdgMP0ZYm1eQQebjq:-NHPdgMP0ZYm1eQQebjr:b78kqg4) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java#L48)):*
> ```Java
>   @Override
>   public String getType() {
>     return null;
> ```

why null
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPdiBWCiTI89J1SsLO:-NHPdiBWCiTI89J1SsLP:b-2guby3) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java#L53)):*
> ```Java
>   @Override
>   public StepSpecType getStepSpecType() {
>     return null;
> ```

same here

**Comment by tmacari-harness** [comment]
@vlica-harness please update 925-enforcement-service/src/main/resources/features/cd_features.yml woth config for new steps

**Review by vlica-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: 17 file(s) to review. 1 change requests. 15. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java` line 210 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPV73B8_EVlYARbtey:-NHPm-gH0HxC2FjDawsu:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/orchestration/NgStepRegistrar.java#L210)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

TerragruntPlanStep.STEP_TYPE 4 times
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPVU_h5lKTkVlm7tdT:-NHPm24W09HRFh-rM2KW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L192)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

StepSpecTypeConstants.TERRAFORM_PLAN ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java` line 193 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPVYpg-SQp6NEx9IVg:-NHPmJQZ4c989sV8t54j:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/NGStepType.java#L193)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Terragrunt Plan ?
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/InlineTerragruntBackendConfigSpec.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPY74-ED2P78w-0KZZ:-NHQ6tytDfj9i8os6SYL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/InlineTerragruntBackendConfigSpec.java#L34)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Probably it is like that for terraform, but here lets have different constants: TerragruntVarFileTypes and TerragruntBackendConfigFileTypes
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/RemoteTerragruntBackendConfigSpec.java` line 34 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPYeNG3AwZSBtmlnew:-NHQ6vYU2tIYyFHq_75l:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/RemoteTerragruntBackendConfigSpec.java#L34)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Separate type for backend config
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPZkN52shYhQ-PTxga:-NHQ6xVCERINV6zUGhnv:bdplv3k) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

shouldn't we support task chain in order to fetch render var files?
</blockquote></details>

For now/beginning we will have the same logic as in terraform. 
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHP_83M8fPBNDhjMvAk:-NHPmQh83TzII4dSDvCL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStep.java#L41)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

let's add here a check for FF so in case someone would try to ad steps through YAM it would throw an error with a meaningful message.
The same on other steps.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java` line 86 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHP_cESBMiosswoREp-:-NHQ75234d2njaldzAvS:b2nha9w) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java#L86)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

If we ent to support task chain we should change here also
</blockquote></details>

ACK
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java` line 90 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPa9vy4LOhjDwcarx-:-NHQ76RmBSCFe82h1WL6:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntApplyStepInfo.java#L90)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

We should extract connector refs for backend config also if it is remote.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPb0-yBRMWYeQ689Ls:-NHQ78CW8VJm1eTOQVa4:b-9pani7) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStep.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

The same, should it support task chain?
</blockquote></details>

for now we will have same logic as in terraform
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStepInfo.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPb_qk6j_W9I1VzB75:-NHQ7HCc3Y3qHTC9tJJa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntDestroyStepInfo.java#L117)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

the same,, add backend config connector ref.
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanExecutionData.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPcF6_8cz3IVb6qk3w:-NHQ7HuS4rl-Ct35dLxW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanExecutionData.java#L94)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Tf plan >> Terragrunt plan
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java` line 30 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPcQE7A_2FcRquDWZL:-NHQ7Iga97wyBQW3HRrw:byeteh9) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntPlanStep.java#L30)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

Same question... should we support task chain?
</blockquote></details>

NOt for now
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPdgMP0ZYm1eQQebjq:-NHQ7OnR-2qyBJM4Vnu1:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java#L48)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

why null
</blockquote></details>

Done.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPdiBWCiTI89J1SsLO:-NHQ7RX37HUR0fJs904V:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntRollbackStepNode.java#L53)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 2 of 68 files at r1, 8 of 8 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 12 of 12 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 50 of 68 files at r1, 6 of 9 files at r2, 4 of 8 files at r3, 4 of 7 files at r4, 6 of 12 files at r5, 2 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/terragrunt/TerragruntPlanStepPlanCreator.java` line 52 at r2](https://reviewable.io/reviews/harness/harness-core/40311#-NHPUk2u3addhffr4gHZ:-NHTreGU6nzeOe_Qi-K5:b-4ynomu) ([raw file](https://github.com/harness/harness-core/blob/67632b2f71a2dce3d17e9d9971f2c360059d5eba/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/steps/terragrunt/TerragruntPlanStepPlanCreator.java#L52)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

would we want to have some new logic around stepFqn?
cc @abosii-harness 
</blockquote></details>

let's have it as point to enhance in future

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 50 of 68 files at r1, 6 of 9 files at r2, 4 of 8 files at r3, 4 of 7 files at r4, 6 of 12 files at r5, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311#-:-NHZ6HUVDjb0YDzUSVqA:bnfp4nl)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Review by abosii-harness — APPROVED** [review]
> Reviewed 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger commonchecks

**Comment by vlica-harness** [comment]
trigger smartchecks

**Review by tmacari-harness — DISMISSED** [review]
> Reviewed 5 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Comment by vlica-harness** [comment]
trigger smartchecks

**Comment by vlica-harness** [comment]
trigger tin0

**Comment by vlica-harness** [comment]
trigger ti0

**Review by tmacari-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40311)* status: :shipit: complete! ✓

**Pull request merged**
