### PR TITLE
fix: [PL-27952]: Do not renew tokens for soft deleted connectors

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
Added additional check whether the connector is deleted or not before renewing vault tokens. This is happening because there are existing soft deleted vault entries. We can remove this changes after we clear up the existing soft deleted entries.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37195)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37195)

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37195)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/37195#-NBL8F_IE12qMQ5R106j:-NBL8F_IE12qMQ5R106k:b-uwvw2f) ([raw file](https://github.com/harness/harness-core/blob/7083a2149e3deb1244f454405ac20bb8e3b31be3/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java#L100)):*
> ```Java
>         // for existing soft deleted vault entries, do not renew token. Remove this code after existing soft deleted
>         // entries are removed from dB
>         if (vaultConnector.getDeleted()) {
> ```

We should handle null case. deleted field is of type Boolean.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37195)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java` line 100 at r1](https://reviewable.io/reviews/harness/harness-core/37195#-NBL8F_IE12qMQ5R106j:-NBLBhQr8aGXk9jJ7GKH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7083a2149e3deb1244f454405ac20bb8e3b31be3/120-ng-manager/src/main/java/io/harness/ng/core/handler/NGVaultSecretManagerRenewalHandler.java#L100)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We should handle null case. deleted field is of type Boolean.
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37195)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37195)* status: :shipit: complete! ✓

**Pull request merged**
