### PR TITLE
feat: [CHAOS-1706]: Adding Service Discovery resources to the AccessControl 

### PR DESCRIPTION
**Pull request by shovanmaity**
## Describe your changes

The changes adds 4 new actions on `networkmap` resource in `servicediscovery`  module on `account`, `organization` and `project` levels.
1. `servicediscovery_networkmap_create`
2. `servicediscovery_networkmap_edit`
3. `servicediscovery_networkmap_delete`
4. `servicediscovery_networkmap_view`

New managed role `_servicediscovery_admin`  is added ini this pr. With this role use can create update delete view network map resources.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)

### CODE REVIEW

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger codeformat

**Comment by shovanmaity** [comment]
trigger checkstyle

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger codeformat

**Comment by shovanmaity** [comment]
trigger checkstyle

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger compile

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger checkstylecodeformat

**Comment by shovanmaity** [comment]
trigger messagecheck

**Comment by shovanmaity** [comment]
trigger commonchecks

**Comment by shovanmaity** [comment]
trigger codebasehash

**Comment by shovanmaity** [comment]
trigger messagecheck

**Comment by shovanmaity** [comment]
trigger uts

**Comment by shovanmaity** [comment]
trigger ut5

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1473 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcAJ-w2hwvufLhdPd-:-NVcAJ-w2hwvufLhdPd0:byxbksr) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1473)):*
> ```YAML
>       - organization
>       - project
>   - identifier: servicediscovery_networkmap_create
> ```

Is servicediscovery new module in Harness or entity in Chaos? Naming convention we follow for permissions is ModuleName_ResourceName_Permission
___
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcB0xx3escpX3z5NkD:-NVcB0xx3escpX3z5NkE:b-7wjzo5) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java#L67)):*
> ```Java
>   public Map<ScopeLevel, EnumSet<ValidatorType>> getSelectorKind() {
>     return ImmutableMap.of(ScopeLevel.ACCOUNT, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES),
>         ScopeLevel.ORGANIZATION, EnumSet.of(BY_RESOURCE_TYPE_INCLUDING_CHILD_SCOPES), ScopeLevel.PROJECT,
> ```

Can networkmap resource be created only at project scope?

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcBbG89yfDczICeyRj:-NVcBbG89yfDczICeyRk:b-v8n4lf) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L210)):*
> ```YAML
>         - core_setting_view
>         - code_repo_view
>         - servicediscovery_networkmap_view
> ```

Add view permissions in privileged-roles.yml as well.

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 978 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcBj2iEk7AmYOyyoqe:-NVcBj2iEk7AmYOyyoqf:b-ms7fvm) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L978)):*
> ```YAML
>     - identifier: _servicediscovery_admin
>       name: ServiceDiscovery Admin
>       description: Can create, edit, delete and view Namework Map Resources
> ```

Namework -> Network

**Comment by shovanmaity** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1473 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcAJ-w2hwvufLhdPd-:-NVcQZHTBmsoJlCIWf90:bchsvz3) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1473)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Is servicediscovery new module in Harness or entity in Chaos? Naming convention we follow for permissions is ModuleName_ResourceName_Permission
</blockquote></details>

Service discovery is a new capability that we are adding as platform feature. Chaos is 1st user of service discovery.

**Comment by shovanmaity** [comment]
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcB0xx3escpX3z5NkD:-NVcRLMe7ze9ZtQSjRqC:b-g1pm) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java#L67)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can networkmap resource be created only at project scope?
</blockquote></details>

No, Network map can be created in project organization and account scope.

**Comment by shovanmaity** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 978 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcBj2iEk7AmYOyyoqe:-NVcS3813KoQZwaU7-G3:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L978)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Namework -> Network
</blockquote></details>

Done.

**Comment by shovanmaity** [comment]
*[`access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml` line 210 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcBbG89yfDczICeyRj:-NVcS5bI2Qqb_5SvViUN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml#L210)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Add view permissions in privileged-roles.yml as well.
</blockquote></details>

Done.

**Comment by shovanmaity** [comment]
*[`platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java` line 67 at r1](https://reviewable.io/reviews/harness/harness-core/47814#-NVcB0xx3escpX3z5NkD:-NVcxQ2886JUtqyTLxPB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eccbffa6e27e0ec904d0fa55532debe412a6b8fd/platform-service/modules/resource-group-service/src/main/java/io/harness/resourcegroup/resourceclient/servicediscovery/NetworkMapResourceImpl.java#L67)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

In that case you should add BY_RESOURCE_TYPE in all 3 scopes.
</blockquote></details>

Done.

**Review by Jimit09Gandhi — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: :shipit: complete! ✓

**Review by meenakshi-harness — APPROVED** [review]

**Review by imrajdas — DISMISSED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: :shipit: complete! ✓

**Comment by shovanmaity** [comment]
trigger uts

**Comment by shovanmaity** [comment]
trigger ut4

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: :shipit: complete! ✓

**Comment by shovanmaity** [comment]
trigger uts

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47814)* status: :shipit: complete! ✓

**Review by imrajdas — APPROVED** [review]

**Comment by shovanmaity** [comment]
trigger feature-build

**Comment by shovanmaity** [comment]
trigger feature-build

**Pull request merged**
