### PR TITLE
fix: [CDS-47901]: add logging in case there are no managed workloads

### PR DESCRIPTION
**Pull request by achyuth-harness**
## Describe your changes
Added logging:
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41195)

### CODE REVIEW

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 388 at r1](https://reviewable.io/reviews/harness/harness-core/41195#-NIbg20V7fahzMdRqLKx:-NIbg20V7fahzMdRqLKy:b-dbr3qr) ([raw file](https://github.com/harness/harness-core/blob/a165856808491421dacc9d0694972e60e9c103c0/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L388)):*
> ```Java
> 
>       if (noManagedWorkloads) {
>         executionLogCallback.saveExecutionLog("No managed workloads, skipping resource versioning \n");
> ```

nit: This code would make more sense if it would be added in else block, for example 
else {
  if (noManagedWorkloads) {
    executionLogCallback.saveExecutionLog("No managed workloads, skipping resource versioning \n");
  }
}

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 388 at r1](https://reviewable.io/reviews/harness/harness-core/41195#-NIbg20V7fahzMdRqLKx:-NIbgItmBpZaUOCiDHtU:b3jn4n7) ([raw file](https://github.com/harness/harness-core/blob/a165856808491421dacc9d0694972e60e9c103c0/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L388)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: This code would make more sense if it would be added in else block, for example 
else {
  if (noManagedWorkloads) {
    executionLogCallback.saveExecutionLog("No managed workloads, skipping resource versioning \n");
  }
}
</blockquote></details>

and can we make it bold?

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java` line 388 at r1](https://reviewable.io/reviews/harness/harness-core/41195#-NIbg20V7fahzMdRqLKx:-NIf9H4bDzSkfzTQOcSY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a165856808491421dacc9d0694972e60e9c103c0/260-delegate/src/main/java/software/wings/delegatetasks/k8s/taskhandler/K8sRollingDeployTaskHandler.java#L388)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

and can we make it bold?
</blockquote></details>

Done.

**Review by vikyathharekal — COMMENTED** [review]
@achyuth-harness Could you add any screenshot of UI where you have tested this?

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195#-:-NIfTcli0YLwJmdH9eEC:b-h4njw8)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by achyuth-harness — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195#-:-NIfj31l7u0RZuoQwv2L:b-896fix)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41195)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Pull request merged**
