### PR TITLE
techdebt: [PIE-4835]: Snapshotting via debezium service

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41443)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerConfig.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbV0-8oHRHqK_KMXT:-NJdbV0-8oHRHqK_KMXU:b-e6p18c) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerConfig.java#L23)):*
> ```Java
>   ConsumerType consumerType;
>   EventsFrameworkConfiguration eventsFrameworkConfiguration;
>   long sleepInterval;
> ```

nit: Add comments for more verbosity.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerFactory.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbZhoBwemc8sAOZTV:-NJdbZhoBwemc8sAOZTW:bldknni) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerFactory.java#L25)):*
> ```Java
>       producerFactory.overrideEventsFrameworkConfiguration(changeConsumerConfig.getEventsFrameworkConfiguration());
>       switch (consumerType) {
>         case EVENTS_FRAMEWORK_STREAMING:
> ```

As discussed, add one more mode field which will tell us if it is streaming or snapshotting.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/ConsumerType.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbhmF8qYx3tWpgBz1:-NJdbhmF8qYx3tWpgBz2:bj8bld6) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ConsumerType.java#L13)):*
> ```Java
> // Right now we only have EVENTS_FRAMEWORK but can be diff like HTTP which will
> // just post the event s to an http endpoint
> public enum ConsumerType { EVENTS_FRAMEWORK_STREAMING, EVENTS_FRAMEWORK_SNAPSHOT }
> ```

same as above.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdboZI46DE8e9dmPN0:-NJdboZI46DE8e9dmPN1:b-2r4rtg) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java#L30)):*
> ```Java
>   EventsFrameworkConfiguration configuration;
> 
>   public Producer get(String collection, int redisStreamSize, boolean isSnapshot) {
> ```

use mode rather which will be added above.

**Comment by sahilhindwani-harness** [comment]
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdc1xz7RIeten1oo8T:-NJdc1xz7RIeten1oo8U:b-iw8znc) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java#L36)):*
> ```Java
>     RedissonClient redissonClient = RedissonClientFactory.getClient(configuration.getRedisConfig());
>     String topicName = DEBEZIUM_PREFIX + collection;
>     if (isSnapshot) {
> ```

nit: remove if and use enum instead.

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41443)* status: 17 file(s) to review. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerConfig.java` line 23 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbV0-8oHRHqK_KMXT:-NJdtPhwAM14fTz1HggZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerConfig.java#L23)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: Add comments for more verbosity.
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerFactory.java` line 25 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbZhoBwemc8sAOZTV:-NJdtQfb3jRFKxonDFE-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ChangeConsumerFactory.java#L25)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

As discussed, add one more mode field which will tell us if it is streaming or snapshotting.
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java` line 30 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdboZI46DE8e9dmPN0:-NJdwrLf5X3EmLCjcrcO:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java#L30)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

use mode rather which will be added above. 
</blockquote></details>

Done.
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java` line 36 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdc1xz7RIeten1oo8T:-NJdwt4V9Fo1T76ZOV0o:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/DebeziumProducerFactory.java#L36)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

nit: remove if and use enum instead.
</blockquote></details>

Done
___
*[`952-debezium-engine/src/main/java/io/harness/debezium/ConsumerType.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/41443#-NJdbhmF8qYx3tWpgBz1:-NJdtTd-4nsazogR1zmY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/e07111652df5cfd6d3ac7608e0812ab9353f5d0e/952-debezium-engine/src/main/java/io/harness/debezium/ConsumerType.java#L13)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 7 of 10 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41443)* status: 22 file(s) to review. 1 of 2 approvals obtained.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 6 of 10 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41443)* status: 1 file(s) to review.

**Review by senjucanon2 — APPROVED** [review]
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41443)* status: :shipit: complete! ✓

**Pull request merged**
