### PR TITLE
fix: [DEL-6004]: add retry for acquire call

### PR DESCRIPTION
**Pull request by AnupamIO**
Add retry for acquire call when StreamResetException is seen.
Rev2: Rev1 will not work because in response we will get 200, so update the pr with new rev.

Testing- Rev2
- Tested on local with different exceptions, only StreamResetException will get retried.

Testing (Old):
- Tested in pr env, 
- Made manager to throw StreamResetException after setting delegateTask as started in DB.
- Call was retried 3 times from client to manager, after that acquire call will fail, task will remain in STARTED state so it will not be assigned to another delegate for execution.
- In any other exception we will not retry.

Screenshot 2023-03-28 at 8 25 52 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)

### CODE REVIEW

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1041 at r2](https://reviewable.io/reviews/harness/harness-core/45770#-NRdNgYUEtFat_btd1WY:-NRdNgYV8cNkpYmgcnKC:bdd81d8) ([raw file](https://github.com/harness/harness-core/blob/84bfab465933a186ecc692df5a1bb82b5e028a9a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1041)):*
> ```Java
> 
>   private <T> RetryPolicy<Response<T>> getRetryPolicy(String failureMessage) {
>     return new RetryPolicy<Response<T>>()
> ```

name looks generic as retry is specific to StreamResetException, can you rename  or make this method generic to pass exception class?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r2](https://reviewable.io/reviews/harness/harness-core/45770#-NRdQX152Lz_pdPRjZ8m:-NRdQX189fALMM11Uj_4:b4gm8ax) ([raw file](https://github.com/harness/harness-core/blob/84bfab465933a186ecc692df5a1bb82b5e028a9a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
> ```Java
>       throw e;
>     } finally {
>       handleResponse(response);
> ```

what happens when the response is null here? should we add an error message for such case?

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)* status: :shipit: complete! ✓

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)* status: 2. unresolved discussions. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r2](https://reviewable.io/reviews/harness/harness-core/45770#-NRdQX152Lz_pdPRjZ8m:-NRdWttr8Ku9WLD6dBeG:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84bfab465933a186ecc692df5a1bb82b5e028a9a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

what happens when the response is null here? should we add an error message for such case?
</blockquote></details>

Done.
___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1041 at r2](https://reviewable.io/reviews/harness/harness-core/45770#-NRdNgYUEtFat_btd1WY:-NRdcFXK-H_wZODDAbWR:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/84bfab465933a186ecc692df5a1bb82b5e028a9a/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1041)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

name looks generic as retry is specific to StreamResetException, can you rename  or make this method generic to pass exception class?
</blockquote></details>

Done.

**Comment by AnupamIO** [comment]
trigger messagecheck

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r3](https://reviewable.io/reviews/harness/harness-core/45770#-NRhviYX1HgIt_EkvaVV:-NRhviYX1HgIt_EkvaVW:bdv8bdk) ([raw file](https://github.com/harness/harness-core/blob/9edf8f87e02373761a7a811f50dea976622fb3d4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
> ```Java
>           log.warn(String.format("%s : Attempt: %d", failureMessage, attempt));
>         } else {
>           throw exception;
> ```

for other exceptions, we are incrementing attempts, so will it go on endless loop?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r3](https://reviewable.io/reviews/harness/harness-core/45770#-NRhviYX1HgIt_EkvaVV:-NRhvwAFAxhUJaAYrxoq:bhtarfv) ([raw file](https://github.com/harness/harness-core/blob/9edf8f87e02373761a7a811f50dea976622fb3d4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

for other exceptions, we are incrementing attempts, so will it go on endless loop? 
</blockquote></details>

i mean *not incrementing

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r3](https://reviewable.io/reviews/harness/harness-core/45770#-NRhviYX1HgIt_EkvaVV:-NRiSIjX5CS0nJg3P7pn:b9snd9d) ([raw file](https://github.com/harness/harness-core/blob/9edf8f87e02373761a7a811f50dea976622fb3d4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

i mean *not incrementing
</blockquote></details>

For any exception other than StreamResetException, function will throw exception.

**Comment by AnupamIO** [comment]
trigger ut7

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1013 at r3](https://reviewable.io/reviews/harness/harness-core/45770#-NRhviYX1HgIt_EkvaVV:-NRiUT6K65GUWPK7V3YG:b-sy57iq) ([raw file](https://github.com/harness/harness-core/blob/9edf8f87e02373761a7a811f50dea976622fb3d4/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1013)):*
<details><summary><i>Previously, AnupamIO (Anupam Jaiswal) wrote…</i></summary><blockquote>

For any exception other than StreamResetException, function will throw exception.
</blockquote></details>

but inside the catch block rite ?. Make sure that's the case, otherwise, it will end up in an endless loop

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45770)* status: :shipit: complete! ✓

**Pull request merged**
