### PR TITLE
[fix]: [PL-21962]: Error message formatting

### PR DESCRIPTION
**Pull request by nishantsaini20**
## Describe your changes
Duplicate project error message format changed to differentiate identifier values with in the error message.
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39265)

### CODE REVIEW

**Review by tiwaritejas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39265)* status: 2 file(s) to review. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/39265#-NFMzS1wDqR561utBlYP:-NFMzS1wDqR561utBlYQ:bi5zljs) ([raw file](https://github.com/harness/harness-core/blob/965ea96f6ca32e689d15f0db29d6cca8f52b41da/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L209)):*
> ```Java
>     when(projectRepository.save(any())).thenThrow(new DuplicateKeyException("Key already exists"));
> 
>     projectService.create(accountIdentifier, orgIdentifier, projectDTO);
> ```

Should we also have a check for the error message in the UT, since that is what has been improved?

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39265)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java` line 209 at r1](https://reviewable.io/reviews/harness/harness-core/39265#-NFMzS1wDqR561utBlYP:-NFN7ZSACM-eiA_lK7vt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/965ea96f6ca32e689d15f0db29d6cca8f52b41da/120-ng-manager/src/test/java/io/harness/ng/core/impl/ProjectServiceImplTest.java#L209)):*
<details><summary><i>Previously, tiwaritejas (Tejas Tiwari) wrote…</i></summary><blockquote>

Should we also have a check for the error message in the UT, since that is what has been improved?
</blockquote></details>

Done.

**Review by tiwaritejas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39265)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39265)* status: :shipit: complete! ✓

**Comment by nishantsaini20** [comment]
trigger codebasehash

**Pull request merged**
