### PR TITLE
[feat]: [CDS-41655]: add api to fetch svc & env ref from Cd stage yaml

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37065)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37065)

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37065)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/37065#-NB5zO5GBh3g0DOVobds:-NB5zO5GBh3g0DOVobdt:b-vq8mri) ([raw file](https://github.com/harness/harness-core/blob/6be6dd6473dca44df62adab9c73f847999ffb3b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L43)):*
> ```Java
>   @GET
>   @Path("metadata")
>   @ApiOperation(value = "Gets a Service and Environment refs from CD Stage Yaml", nickname = "getEnvironment")
> ```

nit: ```Gets the```
Also we should update the ```nickname```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/37065#-NB5zXLj8PeNvSKX8zQs:-NB5zXLj8PeNvSKX8zQt:b-uvm9h6) ([raw file](https://github.com/harness/harness-core/blob/6be6dd6473dca44df62adab9c73f847999ffb3b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L44)):*
> ```Java
>   @Path("metadata")
>   @ApiOperation(value = "Gets a Service and Environment refs from CD Stage Yaml", nickname = "getEnvironment")
>   public ResponseDTO<CdStageMetaDataDto> getCdStageMetadata(
> ```

We can follow this camel case convention ```CDStageMetadataDTO```
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 45 at r4](https://reviewable.io/reviews/harness/harness-core/37065#-NB5zgai8ntuMWhpUJBV:-NB5zgai8ntuMWhpUJBW:bwow1w9) ([raw file](https://github.com/harness/harness-core/blob/6be6dd6473dca44df62adab9c73f847999ffb3b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L45)):*
> ```Java
>   @ApiOperation(value = "Gets a Service and Environment refs from CD Stage Yaml", nickname = "getEnvironment")
>   public ResponseDTO<CdStageMetaDataDto> getCdStageMetadata(
>       @Parameter(description = "Stage yaml string to be parsed") @NotNull String cdStageYaml) throws IOException {
> ```

description: "Yaml of the deploy stage"

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 43 at r4](https://reviewable.io/reviews/harness/harness-core/37065#-NB5zO5GBh3g0DOVobds:-NB7nmF97QUtgNUJR4My:b2m6txr) ([raw file](https://github.com/harness/harness-core/blob/6be6dd6473dca44df62adab9c73f847999ffb3b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L43)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

nit: ```Gets the```
Also we should update the ```nickname```
</blockquote></details>

Removing nickname. Api seems self descriptive.



_Code quote:_
```Java
Gets a Service and Environment refs from 
```

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java` line 44 at r4](https://reviewable.io/reviews/harness/harness-core/37065#-NB5zXLj8PeNvSKX8zQs:-NB7o1NP39owyYsszeOT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6be6dd6473dca44df62adab9c73f847999ffb3b5/120-ng-manager/src/main/java/io/harness/ng/core/deploymentstage/DeploymentStageConfigResource.java#L44)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

We can follow this camel case convention ```CDStageMetadataDTO```
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37065)* status: :shipit: complete! ✓

**Pull request merged**
