### PR TITLE
feat: [CDS-38530]: Resolve service override inputs for environment pl…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…an creator

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger ti1

**Comment by prashantsharma04** [comment]
trigger ft1

**Comment by prashantsharma04** [comment]
trigger ft2

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/33980#-N3wZHW8Cw0a5GDSnC8_:-N3wZHW8Cw0a5GDSnC8a:bk9c1mk) ([raw file](https://github.com/harness/harness-core/blob/528c47b4a6e3ce3d06c26d5d8a94be3baf8feadf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java#L138)):*
> ```Java
>             resolveServiceOverrideInputs(serviceOverridesEntity.getYaml(), environmentV2.getServiceOverrideInputs());
>       }
>       serviceOverride = ServiceOverridesMapper.toServiceOverrides(mergedYaml);
> ```

can we convert this only if yaml is not empty



_Code quote:_
```Java
serviceOverride = ServiceOverridesMapper.toServiceOverrides(mergedYaml);
```
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/33980#-N3wZ_9bBIBoyLSWxARq:-N3wZ_9bBIBoyLSWxARr:b-i2wu4c) ([raw file](https://github.com/harness/harness-core/blob/528c47b4a6e3ce3d06c26d5d8a94be3baf8feadf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java#L64)):*
> ```Java
>   String SERVICE_DEFINITION = "serviceDefinition";
>   String SERVICE_SPEC = "spec";
>   String SERVICE_OVERRIDE = "serviceOverride";
> ```

it should be serviceOverrides, with an s both in input yaml and everywhere else, can you check this



_Code quote:_
```Java
serviceOverride
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java` line 138 at r4](https://reviewable.io/reviews/harness/harness-core/33980#-N3wZHW8Cw0a5GDSnC8_:-N3wgesoDjHka2rajgCL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/528c47b4a6e3ce3d06c26d5d8a94be3baf8feadf/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorHelper.java#L138)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we convert this only if yaml is not empty
</blockquote></details>

Done.
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java` line 64 at r4](https://reviewable.io/reviews/harness/harness-core/33980#-N3wZ_9bBIBoyLSWxARq:-N3wgfZKErF7msoo0fKn:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/528c47b4a6e3ce3d06c26d5d8a94be3baf8feadf/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

it should be serviceOverrides, with an s both in input yaml and everywhere else, can you check this
</blockquote></details>

Done.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: 1 change requests. 2. unresolved discussions.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/33980#-N3whGcpAjgcuB6U9Uri:-N3whGcpAjgcuB6U9Urj:budp85) ([raw file](https://github.com/harness/harness-core/blob/b1066f43e014ff229e6f1920505dba1a676b3d21/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java#L64)):*
> ```Java
>   String SERVICE_DEFINITION = "serviceDefinition";
>   String SERVICE_SPEC = "spec";
>   String SERVICE_OVERRIDE = "serviceOverrideS";
> ```

small s

**Comment by prashantsharma04** [comment]
trigger ti4

**Review by prashantsharma04 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33980)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/33980#-N3whGcpAjgcuB6U9Uri:-N3x8xwI3g5gxso8MOh0:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b1066f43e014ff229e6f1920505dba1a676b3d21/127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/YamlTypes.java#L64)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

small s
</blockquote></details>

Done.

**Comment by prashantsharma04** [comment]
Few tests are failing which are unrelated to my changes.

**Pull request merged**
