### PR TITLE
feat: [PL-25404]: Hard delete variables

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kbIQp17gSLlisEaig:-N2kbIQqDl9Z4Grp7zUg:b-odhypd) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L220)):*
> ```Java
>     for (String variableIdentifier : variableIdentifiersList) {
>       Optional<Variable> existingVariable =
>           variableRepository.findByAccountIdentifierAndOrgIdentifierAndProjectIdentifierAndIdentifier(
> ```

why do we need to do a find query before deletion? Can't we directly write a delete query based on query params?

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDEventHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kb_fT-ZOqcdKOi_c0:-N2kb_fT-ZOqcdKOi_c1:b6clqph) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDEventHandler.java#L28)):*
> ```Java
>   public boolean deleteAssociatedVariables(String accountIdentifier, String orgIdentifier, String projectIdentifier) {
>     variableService.deleteBatch(accountIdentifier, orgIdentifier, projectIdentifier,
>         fetchAllVariablesInGivenScope(accountIdentifier, orgIdentifier, projectIdentifier));
> ```

Store return value in a variable. This will be helpful in debugging/logging values if required.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kdEwcBjbGUAgJWjw6:-N2kdEwcBjbGUAgJWjw7:b-zfs17d) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java#L36)):*
> ```Java
> 
>   @Override
>   public boolean handleMessage(Message message) {
> ```

Add FF wherever necessary.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kc8Gp0uffn0meBZkv:-N2kc8Gp0uffn0meBZkw:bgz6pe4) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java#L62)):*
> ```Java
>     }
>     String action = message.getMessage().getMetadataMap().get(ACTION);
>     if (action != null) {
> ```

This can be handled in default case of switch statement.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java` line 98 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kcizA536bP_Lu2gvw:-N2kcizA536bP_Lu2gvx:b-fonsvw) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java#L98)):*
> ```Java
>     }
>     String action = message.getMessage().getMetadataMap().get(ACTION);
>     if (action != null) {
> ```

Same. This can be handled in default case of switch statement.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2keHC0DigmndAx_nPN:-N2keHC0DigmndAx_nPO:b-m1388k) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L219)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, List<String> variableIdentifiersList) {
>     for (String variableIdentifier : variableIdentifiersList) {
>       Optional<Variable> existingVariable =
> ```

Why not calling delete method already present in the service? Calling the service method will do other necessary actions e.g. auditing deletion.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: 10 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDEventHandler.java` line 28 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kb_fT-ZOqcdKOi_c0:-N33MOsF89wluu1WKLeL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDEventHandler.java#L28)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Store return value in a variable. This will be helpful in debugging/logging values if required.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kdEwcBjbGUAgJWjw6:-N33MPmb5RBYqbqxHQcd:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/event/VariableEntityCRUDStreamListener.java#L36)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Add FF wherever necessary.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 219 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2keHC0DigmndAx_nPN:-N33MRZn7ddcj4UCFbOD:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L219)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

Why not calling delete method already present in the service? Calling the service method will do other necessary actions e.g. auditing deletion.
</blockquote></details>

Done.
___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 220 at r1](https://reviewable.io/reviews/harness/harness-core/33440#-N2kbIQp17gSLlisEaig:-N33MRpg23JB1Jz9eExE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fddbae803190b925d080c8ecaab7d93a914db764/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L220)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

why do we need to do a find query before deletion? Can't we directly write a delete query based on query params?
</blockquote></details>

Done.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: 10 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 226 at r2](https://reviewable.io/reviews/harness/harness-core/33440#-N33Nd9DALyVIz5tGI_V:-N33Nd9DALyVIz5tGI_W:bsjou33) ([raw file](https://github.com/harness/harness-core/blob/16a6b3a645a4e8c891c8449196d9b9392f7d75ad/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L226)):*
> ```Java
>         delete(accountIdentifier, orgIdentifier, projectIdentifier, variableIdentifier);
>       } catch (NotFoundException ex) {
>         log.error(String.format("Variable [%s] Not Found with orgIdentifier- [%s], projectIdentifier- [%s]",
> ```

can you mention that it was delete operation when this error has occurred, otherwise we don't know whats the scope of this error. It will be misleading.

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/33440#-N33NsDg7UTNZaoY_rVo:-N33NsDh7K_1qur4QfkW:b-v61gaw) ([raw file](https://github.com/harness/harness-core/blob/16a6b3a645a4e8c891c8449196d9b9392f7d75ad/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L224)):*
> ```Java
>     for (String variableIdentifier : variableIdentifiersList) {
>       try {
>         delete(accountIdentifier, orgIdentifier, projectIdentifier, variableIdentifier);
> ```

Just putting it out: I hope its taken care of that if there are big num of identifiers to be deleted, it may break the system as its individual call for each delete. Not a blocking comment but should be checked for sure.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: 10 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 226 at r2](https://reviewable.io/reviews/harness/harness-core/33440#-N33Nd9DALyVIz5tGI_V:-N33RIK7-lXi5nMQmnS7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/16a6b3a645a4e8c891c8449196d9b9392f7d75ad/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L226)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can you mention that it was delete operation when this error has occurred, otherwise we don't know whats the scope of this error. It will be misleading.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440#-:-N33SWxXBM0pUJ3fq_5Y:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: 1 file(s) to review. 1 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/33440#-N33NsDg7UTNZaoY_rVo:-N33UQjEA_LiZwTXC7SZ:b-b6d30) ([raw file](https://github.com/harness/harness-core/blob/16a6b3a645a4e8c891c8449196d9b9392f7d75ad/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L224)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Just putting it out: I hope its taken care of that if there are big num of identifiers to be deleted, it may break the system as its individual call for each delete. Not a blocking comment but should be checked for sure.
</blockquote></details>

We are not expecting to have a large number of variables. So should not be an issue.

**Review by nishantsaini20 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: :shipit: complete! ✓

**Comment by mohitg0795** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java` line 224 at r2](https://reviewable.io/reviews/harness/harness-core/33440#-N33NsDg7UTNZaoY_rVo:-N33WB6aDxR6u99dTIFr:bh2xfix) ([raw file](https://github.com/harness/harness-core/blob/16a6b3a645a4e8c891c8449196d9b9392f7d75ad/120-ng-manager/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java#L224)):*
<details><summary><i>Previously, nishantsaini20 (Nishant Saini) wrote…</i></summary><blockquote>

We are not expecting to have a large number of variables. So should not be an issue.
</blockquote></details>

Any single call failure could result into inconsistent state, so do take care of it. Rest is all good if everything has been taken care of.

**Comment by VikasMaddukuriHarness** [comment]
trigger ti0

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440#-:-N34MEDm92gaDw5RjPla:bnfp4nl)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33440)* status: :shipit: complete! ✓

**Pull request merged**
