### PR TITLE
feat: [CDS-38066]: Resolving inputs for infrastructure entity

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33878)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger messagecheck

**Comment by prashantsharma04** [comment]
trigger ti0

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33878)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructurePlanCreatorHelper.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/33878#-N3cw4ce4A-70zzGwczm:-N3cw4ce4A-70zzGwczn:b20lo4y) ([raw file](https://github.com/harness/harness-core/blob/22e14af0c3607ed0b8aa65fba39c235074096ef5/125-cd-nextgen/src/main/java/io/harness/cdng/infra/InfrastructurePlanCreatorHelper.java#L40)):*
> ```Java
>       if (refToInputMap.containsKey(entity.getIdentifier())) {
>         Map<String, Object> infraInputYaml = new HashMap<>();
>         infraInputYaml.put(YamlTypes.INFRASTRUCTURE_DEF, refToInputMap.get(entity.getIdentifier()));
> ```

nit: we can have single line initialization of maps using guava's map class https://www.baeldung.com/guava-maps

**Comment by prashantsharma04** [comment]
trigger ti0

**Pull request closed without merging**
