### PR TITLE
feat: [CDS-42805]: Service V2 triggers

### PR DESCRIPTION
**Pull request by piyush-bhuwalka**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37248)

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/config.yml` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/37248#-NBQgwYWE-UA5aEF0HdJ:-NBQgwYWE-UA5aEF0HdK:bt9mfq9) ([raw file](https://github.com/harness/harness-core/blob/01bf9349ced2a83de373d356f1f717d192fe6b71/120-ng-manager/config.yml#L260)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
> ```

is this intentional ?
You can set the ```SHOULD_CONFIGURE_WITH_PMS``` environment variable to true

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpWtl_4Oe78pXAihNw:-NBpWtl_4Oe78pXAihNx:b-p2jo69) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L105)):*
> ```Java
>       @Parameter(description = "Identifier of the target pipeline") @NotNull @QueryParam("targetIdentifier")
>       @ResourceIdentifier String targetIdentifier, @NotNull @ApiParam(hidden = true, type = "") String yaml,
>       @QueryParam("ignoreError") @DefaultValue("false") boolean ignoreError, @QueryParam("serviceV2")  @DefaultValue("true") boolean serviceV2);
> ```

default should be false for this. Any one who does not pass this boolean is expected to be treated as OLD

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpX2q01vgGHn5JvbXx:-NBpX2q01vgGHn5JvbXy:bcps275) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L105)):*
> ```Java
>       @Parameter(description = "Identifier of the target pipeline") @NotNull @QueryParam("targetIdentifier")
>       @ResourceIdentifier String targetIdentifier, @NotNull @ApiParam(hidden = true, type = "") String yaml,
>       @QueryParam("ignoreError") @DefaultValue("false") boolean ignoreError, @QueryParam("serviceV2")  @DefaultValue("true") boolean serviceV2);
> ```

we should rename serviceV2 to ```withServiceV2```

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java` line 154 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpXFQx-2QjdB5qz-is:-NBpXFQx-2QjdB5qz-it:b-juucln) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity/NGTriggerEntity.java#L154)):*
> ```Java
>       return Boolean.FALSE;
>     }
>     return serviceV2;
> ```

```return serviceV2 != null && serviceV2```
Also shouldn't we just return boolean ( primitive ) from here

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpbXhTAXko_fTEYFSf:-NBpbXhTAXko_fTEYFSg:b-oy8eg) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java#L117)):*
> ```Java
>   }
> 
>   public void validateBuildType(BuildTriggerOpsData buildTriggerOpsData, Optional<Boolean> serviceV2) {
> ```

lets not pass optional as a method argument.
https://rules.sonarsource.com/java/RSPEC-3553
We can just use a primitive boolean

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact/version/HelmVersion.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/37248#-NBqB8weAT-GKRVIROOV:-NBqB8weAT-GKRVIROOW:bq1cl68) ([raw file](https://github.com/harness/harness-core/blob/285259398f697168b5f163fe0dd57d0db56b307f/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact/version/HelmVersion.java#L18)):*
> ```Java
>     return V3.equals(helmVersion) || V380.equals(helmVersion);
>   }
>   public static io.harness.ngtriggers.beans.source.artifact.version.HelmVersion fromString(String helmVersion) {
> ```

we do not need the fully qualified import here for HelmVersion

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by piyush-bhuwalka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: 32 file(s) to review. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact/version/HelmVersion.java` line 18 at r5](https://reviewable.io/reviews/harness/harness-core/37248#-NBqB8weAT-GKRVIROOV:-NBubf4c08v6QWZpLcEM:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/285259398f697168b5f163fe0dd57d0db56b307f/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact/version/HelmVersion.java#L18)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

we do not need the fully qualified import here for HelmVersion
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java` line 105 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpWtl_4Oe78pXAihNw:-NBubYcL-VGs3aS2Decs:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/resource/NGTriggerResource.java#L105)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

default should be false for this. Any one who does not pass this boolean is expected to be treated as OLD 
</blockquote></details>

Done.
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java` line 117 at r4](https://reviewable.io/reviews/harness/harness-core/37248#-NBpbXhTAXko_fTEYFSf:-NBubQcy0AayikhiSM1P:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ef7549961c111a01d0d112d3f9b5c09a0efa57d2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java#L117)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets not pass optional as a method argument.
https://rules.sonarsource.com/java/RSPEC-3553
We can just use a primitive boolean
</blockquote></details>

Done.
___
*[`120-ng-manager/config.yml` line 260 at r1](https://reviewable.io/reviews/harness/harness-core/37248#-NBQgwYWE-UA5aEF0HdJ:-NBub5L1AxkjwQ8rKbd1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/01bf9349ced2a83de373d356f1f717d192fe6b71/120-ng-manager/config.yml#L260)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

is this intentional ?
You can set the ```SHOULD_CONFIGURE_WITH_PMS``` environment variable to true
</blockquote></details>

Done

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java` line 127 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvFfsf815PFL1Ih4CI:-NBvFfsf815PFL1Ih4CJ:bti4ue0) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java#L127)):*
> ```Java
>     }
> 
>     if (buildTriggerOpsData.getTriggerDetails().getNgTriggerEntity().getWithServiceV2() == false
> ```

do we need null check here ?

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 613 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvFqIP2bKp9vNsshEi:-NBvFqIP2bKp9vNsshEj:b-ezx6sj) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L613)):*
> ```Java
>     // trigger source validation
>     if (triggerDetails.getNgTriggerEntity().getWithServiceV2() == false
>         && isBlank(triggerDetails.getNgTriggerEntity().getIdentifier())) {
> ```

should we not always check for identifier ?  ( irrespective of service v2 )

**Comment by yogesh-chauhan** [comment]
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/impl/ManifestTriggerValidator.java` line 99 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvLYn09A3zx1WN7wY1:-NBvLYn09A3zx1WN7wY2:b-vth0l6) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/impl/ManifestTriggerValidator.java#L99)):*
> ```Java
>   @VisibleForTesting
>   void validateForHelmChart(BuildTriggerOpsData buildTriggerOpsData) {
>     if (buildTriggerOpsData.getTriggerDetails().getNgTriggerEntity().getWithServiceV2() == false) {
> ```

better to push the check to the caller method
```validateBasedOnManifestType```

**Review by piyush-bhuwalka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java` line 127 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvFfsf815PFL1Ih4CI:-NBvNB8O6C6aB24lCQL9:bnhf6nc) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers/BuildTriggerHelper.java#L127)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we need null check here ?
</blockquote></details>

Not sure, should I ? In testing , haven't seen NPE yet
___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/impl/ManifestTriggerValidator.java` line 99 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvLYn09A3zx1WN7wY1:-NBvNeWZ6XQ7ED3Qhvuz:b4yekc7) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/impl/ManifestTriggerValidator.java#L99)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

better to push the check to the caller method
```validateBasedOnManifestType```
</blockquote></details>

there is validateRuntimeInputsForHelmChart which is out of the if block, so cannot move the condition to caller method

**Review by piyush-bhuwalka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java` line 613 at r10](https://reviewable.io/reviews/harness/harness-core/37248#-NBvFqIP2bKp9vNsshEi:-NBvVciw3GGrrAqAtjgo:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a810ffbec0c4a97ae47c1242a4eda6bfd0f46dc2/pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java#L613)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we not always check for identifier ?  ( irrespective of service v2 )
</blockquote></details>

Done

**Comment by piyush-bhuwalka** [comment]
trigger feature-build

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: Some of the checks are too old.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: :shipit: complete! ✓

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37248)* status: :shipit: complete! ✓

**Pull request merged**
