### PR TITLE
fix: [DEL-3933]: Fix error message on no delegate available exception

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:  Throw error message with description when available on fail task

## Checklist
- [ X] I've documented the changes in the PR description.
- [ X] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36127)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36127)

**Comment by jennyjames21** [comment]
trigger messagecheck

**Review by raghuAtWings — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36127)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceGrpcClient.java` line 202 at r1](https://reviewable.io/reviews/harness/harness-core/36127#-N92jnYjEDi8YJNcVUHO:-N92jnYjEDi8YJNcVUHP:b-ls1te2) ([raw file](https://github.com/harness/harness-core/blob/683b9830df1f3e0ce8702e3ebd1bbd6c7aed38c7/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceGrpcClient.java#L202)):*
> ```Java
>       return response;
>     } catch (StatusRuntimeException ex) {
>       if (isNotEmpty(ex.getStatus().getDescription())) {
> ```

what is ex.getStatus is null?

**Comment by jennyjames21** [comment]
*[`910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceGrpcClient.java` line 202 at r1](https://reviewable.io/reviews/harness/harness-core/36127#-N92jnYjEDi8YJNcVUHO:-N92kKlTByfHxcVvoH0L:b83zmog) ([raw file](https://github.com/harness/harness-core/blob/683b9830df1f3e0ce8702e3ebd1bbd6c7aed38c7/910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceGrpcClient.java#L202)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

what is ex.getStatus is null?
</blockquote></details>

it cannot be null. On service side whole block of code is inside try catch. And on exception we always send status (Internal). But no harm in adding a check there, so will update

catch (Exception ex) {
      if (ex instanceof NoDelegatesException) {
        log.error("No delegate exception found while processing submit task request. reason {}",
            ExceptionUtils.getMessage(ex));
      } else {
        log.error("Unexpected error occurred while processing submit task request.", ex);
      }
      responseObserver.onError(io.grpc.Status.INTERNAL.withDescription(ex.getMessage()).asRuntimeException());
    }

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36127)* status: :shipit: complete! ✓

**Pull request merged**
