### PR TITLE
fix: [CDS-78172]: Fixing null ptr in graph rendering while step grp with s…

### PR DESCRIPTION
**Pull request by Y0709**
…tep group retry FS

Fixed an issue with graph rendering which was causing null ptr with step groups with Step group retry failure strategy

Testing 

Tested with pipeline mentioned in the ticket as well as few other cases with step and step group retry

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)

### CODE REVIEW

**Comment by Y0709** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/generator/OrchestrationAdjacencyListGenerator.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/52553#-NdhzJg07_IGizEm6uLc:-NdhzJg07_IGizEm6uLd:b-x9e3w6) ([raw file](https://github.com/harness/harness-core/blob/58fafacd6309d59e0957546ae93d681baaa02fb4/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/generator/OrchestrationAdjacencyListGenerator.java#L111)):*
> ```Java
>     String currentUuid = nodeExecution.getUuid();
> 
>     if (isIdPresent(nodeExecution.getPreviousId()) && adjacencyList.containsKey(nodeExecution.getPreviousId())) {
> ```

Can we add a UT for this case?

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 change requests. 1 of 2 approvals obtained.

**Comment by Y0709** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]

**Review by Y0709 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/generator/OrchestrationAdjacencyListGenerator.java` line 111 at r1](https://reviewable.io/reviews/harness/harness-core/52553#-NdhzJg07_IGizEm6uLc:-NdihCWVDAq6CXgo1Mra:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/58fafacd6309d59e0957546ae93d681baaa02fb4/pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/generator/OrchestrationAdjacencyListGenerator.java#L111)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Can we add a UT for this case?
</blockquote></details>

Done.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 file(s) to review. 1. unresolved discussions.

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52553)* status: 1 file(s) to review.

**Comment by Y0709** [comment]
trigger messagecheck, review

**Pull request merged**
