### PR TITLE
[feat]: [CDS-69463]: Add config for Retry Step Group Failure Strategy

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/48509)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger uts

**Review by harshjain12 — DISMISSED** [review]

**Comment by namanvermah** [comment]
trigger uts

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by namanvermah** [comment]
trigger ut6

**Review by r0610205 — APPROVED** [review]

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 6 of 17 files at r1, 1 of 11 files at r2, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48509)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/48509)* status: :shipit: complete! ✓

**Comment by ankittiwari-harness** [comment]
trigger review

**Comment by ankittiwari-harness** [comment]
trigger uts

**Pull request merged**
