### PR TITLE
feat: [DEL-4888]: Enable immutable delegate for new accounts

### PR DESCRIPTION
**Pull request by AnupamIO**
**Changes**:

- Add migration for existing FF to variable immutableDelegateEnabled in account collection
- Enable immutable delegate for new accounts (default value of immutableDelegateEnabled is true)
- New endpoints for UI to fetch immutableDelegateEnabled value in ng and cg.

**Note**: After these changes are done if we want to enable immutable delegate for older account we would need to toggle immutableDelegateEnabled variable in accounts collection using pipeline. 

**Testing**: 
New Account:
immutableDelegateEnabled set to true in db and immutable delegate used.

Old Account:
- FF data is migrated to immutableDelegateEnabled variable.
- Same behaviour for older delegates, if immutable then immutable after changes and vice-versa.

- Able to hit api with correct output, link: 
cg: https://localhost:8181/api/account/kmpySmUISimoRrJL6NL73w/immutable-delegate-enabled
ng: https://localhost:8181/ng/api/accounts/kmpySmUISimoRrJL6NL73w/immutable-delegate-enabled

**What will happen if this is deployed to prod and UI changes are not released**: 
1- new accounts will have UI same as legacy delegates, they will not see instance status and root options in UI. They will download immutable delegate through wizard.
2- No impact to existing accounts. 
3- Toggling of delegate (legacy / immutable) will become confusing because UI and BE will depend on different FF.
 

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS7SgZ3Ujw2wSRHJ68:-NFS7SgZ3Ujw2wSRHJ69:b-bczbhj) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/beans/Account.java#L185)):*
> ```Java
> 
>   @Getter @Setter private boolean immutableDelegateEnabled = true;
> ```

how was this trip tested? did you see in the PR env that if a new user signs up this filed is true?

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2149 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS7h9kDEBfctZDrsPD:-NFS7h9kDEBfctZDrsPE:bntpi5u) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2149)):*
> ```Java
>   public boolean isImmutableDelegateEnabled(String accountId) {
>     Account account = getFromCacheWithFallback(accountId);
>     return account != null && account.isImmutableDelegateEnabled();
> ```

this should also check if the new flag (DONT_USE_IMMUTABLE_DELEGATE ) is not enabled

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3294 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS8Zwf9rh4Czp78hBK:-NFS8Zwf9rh4Czp78hBL:bbrchgh) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3294)):*
> ```Java
>       if (featureFlagService.isEnabled(USE_IMMUTABLE_DELEGATE, accountId)) {
>         return true;
>       } else if (featureFlagService.isEnabled(USE_LEGACY_DELEGATE, accountId)) {
> ```

you don't need else if

      if (featureFlagService.isEnabled(USE_IMMUTABLE_DELEGATE, accountId)) {
        return true;
      } 

if (featureFlagService.isEnabled(USE_LEGACY_DELEGATE, accountId)) {
  return false
}

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 0 of 1 approvals obtained.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS7SgZ3Ujw2wSRHJ68:-NFSljGp3WMD8xLrc3QW:bmd62tu) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/beans/Account.java#L185)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

how was this trip tested? did you see in the PR env that if a new user signs up this filed is true?
</blockquote></details>

yes, created a new user in pr env and checked in DB this field was populated as true.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 2149 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS7h9kDEBfctZDrsPD:-NFSmPvbDGEb4PKbCxb1:b9nqia5) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L2149)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this should also check if the new flag (DONT_USE_IMMUTABLE_DELEGATE ) is not enabled
</blockquote></details>

ack, will push in next rev.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java` line 3294 at r1](https://reviewable.io/reviews/harness/harness-core/39313#-NFS8Zwf9rh4Czp78hBK:-NFSmUIe03m5LHIhkTt_:b9nqia5) ([raw file](https://github.com/harness/harness-core/blob/84f61e2f33c0591e4465d854337236c207ad79c4/400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java#L3294)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

you don't need else if

      if (featureFlagService.isEnabled(USE_IMMUTABLE_DELEGATE, accountId)) {
        return true;
      } 

if (featureFlagService.isEnabled(USE_LEGACY_DELEGATE, accountId)) {
  return false
}


</blockquote></details>

ack, will push in next rev.

**Comment by AnupamIO** [comment]
trigger ti1

**Comment by raghuAtWings** [comment]
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddImmutableDelegateEnabledFieldToAccountCollection.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/39313#-NFqzUpsCVQe-W5_tW75:-NFqzUpsCVQe-W5_tW76:blznxie) ([raw file](https://github.com/harness/harness-core/blob/f267ffa41ca6c275917c148479034c612b3e08be/390-db-migration/src/main/java/io/harness/migrations/all/AddImmutableDelegateEnabledFieldToAccountCollection.java#L33)):*
> ```Java
>       for (Account account : accounts) {
>         if (accountIds.contains(account.getUuid())) {
>           wingsPersistence.updateField(
> ```

we should not make one db call per update. Make one list of accounts for which you need to set to true and one for which to set false and then run two update queries.

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 12 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 0 of 1 approvals obtained.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 7 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 759 at r5](https://reviewable.io/reviews/harness/harness-core/39313#-NFsYnRZ17EZWbnzY8kr:-NFsYnRZ17EZWbnzY8ks:b-f3hsyn) ([raw file](https://github.com/harness/harness-core/blob/d27c9a5c93cfb58000cf48201ac2e4e7f35da0c2/400-rest/src/main/java/software/wings/beans/Account.java#L759)):*
> ```Java
>     }
> 
>     public Builder withImmutableDelegateEnabled(boolean immutableDelegateEnabled) {
> ```

Where are we calling this ?



_Code quote:_
```Java
withImmutableDelegateEnabled
```
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 497 at r5](https://reviewable.io/reviews/harness/harness-core/39313#-NFsYuE25DCTOxBn006p:-NFsYuE25DCTOxBn006q:bdgxva6) ([raw file](https://github.com/harness/harness-core/blob/027a992b58dd3bcde85c1126f55763f256bcdbd0/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L497)):*
> ```Java
>     // TODO: MARKO uncomment this when immutable UI has been completely developed
>     //    if (!DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
>     //      featureFlagService.enableAccount(FeatureName.USE_IMMUTABLE_DELEGATE, account.getUuid());
> ```

We still need this piece if we unable to fix UI before next release.



_Code quote:_
```Java
    // TODO: MARKO uncomment this when immutable UI has been completely developed
    //    if (!DeployMode.isOnPrem(mainConfiguration.getDeployMode().name())) {
    //      featureFlagService.enableAccount(FeatureName.USE_IMMUTABLE_DELEGATE, account.getUuid());
    //    }
```

**Comment by AnupamIO** [comment]
trigger ti0

**Comment by AnupamIO** [comment]
trigger ti2

**Comment by AnupamIO** [comment]
trigger codeformat

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 7 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: :shipit: complete! ✓

**Comment by AnupamIO** [comment]
trigger ti1

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 1. unresolved discussions. 

___
*[`390-db-migration/src/main/java/io/harness/migrations/all/AddImmutableDelegateEnabledFieldToAccountCollection.java` line 33 at r3](https://reviewable.io/reviews/harness/harness-core/39313#-NFqzUpsCVQe-W5_tW75:-NFwupvt9_-N2WhpBCcQ:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/f267ffa41ca6c275917c148479034c612b3e08be/390-db-migration/src/main/java/io/harness/migrations/all/AddImmutableDelegateEnabledFieldToAccountCollection.java#L33)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should not make one db call per update. Make one list of accounts for which you need to set to true and one for which to set false and then run two update queries. 
</blockquote></details>

done
___
*[`400-rest/src/main/java/software/wings/beans/Account.java` line 759 at r5](https://reviewable.io/reviews/harness/harness-core/39313#-NFsYnRZ17EZWbnzY8kr:-NFwvEsl0XfDC71IswKb:b-8vwnla) ([raw file](https://github.com/harness/harness-core/blob/d27c9a5c93cfb58000cf48201ac2e4e7f35da0c2/400-rest/src/main/java/software/wings/beans/Account.java#L759)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

Where are we calling this ?
</blockquote></details>

not used now, can be removed. I was using in a test case previosuly.
___
*[`400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java` line 497 at r5](https://reviewable.io/reviews/harness/harness-core/39313#-NFsYuE25DCTOxBn006p:-NFwvuw_1MLhPLMzLFKC:b-icg2oe) ([raw file](https://github.com/harness/harness-core/blob/027a992b58dd3bcde85c1126f55763f256bcdbd0/400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java#L497)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

We still need this piece if we unable to fix UI before next release.
</blockquote></details>

yes raised a separate pr for this, this pr will go in next release.

**Comment by AnupamIO** [comment]
trigger ti1

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 5 of 9 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 1. unresolved discussions.

**Review by gaurav-jain1 — DISMISSED** [review]
> Reviewed 2 of 10 files at r1, 1 of 12 files at r2, 2 of 7 files at r4, 1 of 1 files at r6, 5 of 9 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 1. unresolved discussions.

**Comment by AnupamIO** [comment]
trigger ti0

**Comment by AnupamIO** [comment]
trigger ti1

**Comment by AnupamIO** [comment]
trigger ti2

**Comment by AnupamIO** [comment]
trigger ti4

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 1 of 12 files at r2, 1 of 7 files at r4, 1 of 1 files at r6, 5 of 9 files at r7, 4 of 7 files at r8, 2 of 3 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: 1. unresolved discussions.

**Review by gaurav-jain1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39313)* status: :shipit: complete! ✓

**Pull request merged**
