### PR TITLE
[feat]: [PIE-8354]: Added support for execution url at stage and step level

### PR DESCRIPTION
**Pull request by archit-harness**
## Describe your changes

Added support for execution url at stage and step level In NodeExecutionMap, so that any node referring to executionUrl can work.

Format -> <+[fqn].executionUrl>

Testing: Added unit tests for all cases for normal stage/steps, matrix, parallel, and comments for child pipeline stage.

Its a backward compatible change, as we added more functors thus its non breaking change.

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-ALL: `trigger tiAll`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)

### CODE REVIEW

**Comment by archit-harness** [comment]
trigger messagecheck

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/44044#-NOh9zyB3AxmUki7aj-N:-NOh9zyB3AxmUki7aj-O:b-x6f65v) ([raw file](https://github.com/harness/harness-core/blob/57d23a141fc32b716718a53fc1f51111ada7fae2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java#L166)):*
> ```Java
>     if (currentStrategyLevelAtStage) {
>       String stageRuntimeId = ambiance.getStageExecutionId();
>       stageExecutionUrl += String.format("&stageExecId=%s", stageRuntimeId);
> ```

why are we not doing this always?

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)* status: Some of the checks are too old. 1 of 2 approvals obtained.

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)* status: Some of the checks are too old. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java` line 166 at r2](https://reviewable.io/reviews/harness/harness-core/44044#-NOh9zyB3AxmUki7aj-N:-NOhClxY79_4NZaizhmz:b2iaj3v) ([raw file](https://github.com/harness/harness-core/blob/57d23a141fc32b716718a53fc1f51111ada7fae2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java#L166)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

why are we not doing this always?
</blockquote></details>

if the stage is under strategy then only we should do this isn't? else there is unnecessary param even though no issues occur

**Review by sahilhindwani-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)* status: Some of the checks are too old.

**Review by naidu-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44044)* status: Some of the checks are too old.

**Pull request merged**
