### PR TITLE
[feat]: [PL-21845]: Add event monitoring on event framework consumers

### PR DESCRIPTION
**Pull request by rijajoo**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30093)

### CODE REVIEW

**Comment by rijajoo** [comment]
trigger messagecheck authorcheck

**Review by ashishsanodia-harness — APPROVED** [review]

**Review by mohitg0795 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30093)* status: 3 file(s) to review. 1 of 2 approvals obtained. 

___
*[953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisAbstractConsumer.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/30093#-MtsyZjz4bgmQ05IPY35:-MtsyZjz4bgmQ05IPY36:b-wq78ni) ([raw file](https://github.com/harness/harness-core/blob/e52ee47f2294655d218918ec39ce0b77bc5bae6b/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisAbstractConsumer.java#L43)):*
> ```Java
> @Slf4j
> public abstract class RedisAbstractConsumer extends AbstractConsumer {
>   private static final String REDIS_PULL_EVENT_METRIC = "redis_pull_event_metric";
> ```

Can we use some more intuitive name. Somehow "pull" doesn't give that feeling. I agree logical reasoning would be that we already have a "push" event metric but somehow this one seems odd.
Maybe we can put something like: "redis_consumer_event_metric".

Adding this non blocking comment, team can take a call on it.

**Comment by rijajoo** [comment]
Compile: trigger compile
runAeriformCheck: trigger AeriformCheck
CodeFormat: trigger codeformat
MessageMetadata: trigger messagecheck
Recency: trigger recency
BuildNumberMetadata: trigger buildnum
runDockerizationCheck: trigger dockerizationcheck
runAuthorCheck: trigger authorcheck
Checkstyle: trigger checkstyle
PMD: trigger pmd
TI-bootstrap: trigger ti0
TI-bootstrap1: trigger ti1
TI-bootstrap2: trigger ti2
TI-bootstrap3: trigger ti3
TI-bootstrap4: trigger ti4
FunctionalTest1: trigger ft1
FunctionalTest2: trigger ft2
CodeBaseHash: trigger codebasehash

**Review by rijajoo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30093)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisAbstractConsumer.java, line 43 at r1](https://reviewable.io/reviews/harness/harness-core/30093#-MtsyZjz4bgmQ05IPY35:-MvTmNI37vj6iZsrFmWw:b-krr0fc) ([raw file](https://github.com/harness/harness-core/blob/e52ee47f2294655d218918ec39ce0b77bc5bae6b/953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisAbstractConsumer.java#L43)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Can we use some more intuitive name. Somehow "pull" doesn't give that feeling. I agree logical reasoning would be that we already have a "push" event metric but somehow this one seems odd.
Maybe we can put something like: "redis_consumer_event_metric".

Adding this non blocking comment, team can take a call on it.
</blockquote></details>

@mohitg0795 Can you please review now?

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30093)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by harshjain12 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30093#-:-MvU4jU8-nZJLwXbSh59:bnfp4nl)* status: :shipit: complete! ✓

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30093#-:-MvUAcEwDog3KDzmNzPq:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
