### PR TITLE
[feat]: [PIE-3794]: Git Simplification helper methods

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33335)

### CODE REVIEW

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335#-:-N2Q1DN3Cxu52Aif9Y73:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335#-:-N2QTdOmDctue0lwX9sE:bnfp4nl)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/engine/governance/PolicyEvaluationFailureException.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/33335#-N2QYLAO9Q2paAYtkQCB:-N2QYLAO9Q2paAYtkQCC:btgbrgi) ([raw file](https://github.com/harness/harness-core/blob/87f59b76db061ea2ef7864afdbb56d1cd2e1a7ce/870-orchestration/src/main/java/io/harness/engine/governance/PolicyEvaluationFailureException.java#L14)):*
> ```Java
>   GovernanceMetadata governanceMetadata;
> 
>   public PolicyEvaluationFailureException(String message, GovernanceMetadata governanceMetadata) {
> ```

We need to add this in response_messages.properties as well register it in kryo.
Hkryo should be the place I think else if we get this exception during execution, we will error out our plan execution

**Review by sahilhindwani-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by namanvermah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/engine/governance/PolicyEvaluationFailureException.java` line 14 at r2](https://reviewable.io/reviews/harness/harness-core/33335#-N2QYLAO9Q2paAYtkQCB:-N2R37f47TSB2bM_Pk9l:b-drqfl2) ([raw file](https://github.com/harness/harness-core/blob/87f59b76db061ea2ef7864afdbb56d1cd2e1a7ce/870-orchestration/src/main/java/io/harness/engine/governance/PolicyEvaluationFailureException.java#L14)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We need to add this in response_messages.properties as well register it in kryo.
Hkryo should be the place I think else if we get this exception during execution, we will error out our plan execution
</blockquote></details>

already added in response_messages.properties. Added kryo.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33335)* status: :shipit: complete! ✓

**Pull request merged**
