### PR TITLE
[feat]: [PL-41295]: Added uniqueId Field in AuditEvents DB Collection

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
This PR adds `uniqueId` field in Audit Events Collections in Resource 
image

Why This Change ?
We are introducing a new variable in the Audit Collections which will be used to move projects across the organization using that uniqueId.

Testing
Created a new Organization without this change , No impact on functionality
Created another new Organization with this change, No Impact on functionality
Created one more org , but post this change was rollbacked to check the behaviour in DB when the field is no longer there . No Impact was observed

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54234)

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger uts

**Comment by adiyaar24** [comment]
trigger gitleaks,checkstylecodeformat,commonchecks

**Review by pbarapatre10 — APPROVED** [review]

**Comment by adiyaar24** [comment]
trigger messagecheck

**Comment by adiyaar24** [comment]
trigger review

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54234)* status: Some of the checks are too old. 6 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`970-api-services-beans/src/main/java/io/harness/audit/streaming/outgoing/Resource.java` line 22 at r3](https://reviewable.io/reviews/harness/harness-core/54234#-Nhfll1HDuPT_0M-wuPW:-Nhfll1HDuPT_0M-wuPX:b9i8lxt) ([raw file](https://github.com/harness/harness-core/blob/0f8812913c13c78fd2c20a282712e28f057c7433/970-api-services-beans/src/main/java/io/harness/audit/streaming/outgoing/Resource.java#L22)):*
> ```Java
>   @NotBlank String type;
>   @NotBlank String identifier;
>   String uniqueId;
> ```

Don't add it right now
___
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/54234#-NhflnNQCsm90yMi1zV-:-NhflnNR8rZNbRmMNpfS:b-289xhh) ([raw file](https://github.com/harness/harness-core/blob/0f8812913c13c78fd2c20a282712e28f057c7433/platform-service/modules/audit-service/src/main/java/io/harness/audit/entities/AuditEvent.java#L172)):*
> ```Java
>     public static final String RESOURCE_LABEL_VALUES_KEY =
>         AuditEventKeys.resource + "." + ResourceKeys.labels + "." + KeyValuePairKeys.value;
>     public static final String RESOURCE_UNIQUE_ID_KEY = AuditEventKeys.resource + "." + ResourceKeys.uniqueId;
> ```

This is not needed

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54234#-:-Nhke3ORBKWE-2S3sQPX:bnfp4nl)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by adiyaar24** [comment]
trigger uts

**Pull request merged**
