### PR TITLE
[feat]: [PL-27953]: adding timeout for custom sm in NG

### PR DESCRIPTION
**Pull request by shreyas-harness**
## Describe your changes
The change allows user to pass timeout ( in millisecond ) for executing script in Custom Secret manager. 
The default value of timeout is 20 sec  ( 20,000 ms ) but is now configurable. 
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37109)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37109)

**Comment by mohitg0795** [comment]
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java` line 48 at r2](https://reviewable.io/reviews/harness/harness-core/37109#-NBC-TfZAJQxCt7SmYrb:-NBC-TfZAJQxCt7SmYrc:b-lycay2) ([raw file](https://github.com/harness/harness-core/blob/de3b7ed2ab63840cdf32d125af0f7f3ab8f96d28/890-sm-delegate/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java#L48)):*
> ```Java
>   private final TimeLimiter timeLimiter;
>   private static final String DEFAULT_TIMEOUT_IN_MILLISECOND = "20000";
>   private static final String TIMEOUT = "timeout";
> ```

Can't we use this constant from some common place in both the files?

**Comment by mohitg0795** [comment]
*[`890-sm-delegate/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/37109#-NBC0MlZ0Jh-AwMRAzuM:-NBC0MlZ0Jh-AwMRAzuN:bcm1o9j) ([raw file](https://github.com/harness/harness-core/blob/de3b7ed2ab63840cdf32d125af0f7f3ab8f96d28/890-sm-delegate/src/main/java/io/harness/encryptors/clients/NGCustomSecretManagerEncryptor.java#L67)):*
> ```Java
>     final int NUM_OF_RETRIES = 3;
>     int failedAttempts = 0;
>     int timeout = Integer.parseInt(encryptedRecord.getParameters()
> ```

There's no validation over timeout field, thus it could create runtime exception. I think we should have some validation over the field value at time of setting it in the params and throw a proper exception if there's some violation

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptSpec.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37109#-NBC0bn96DGQa9SZ-L3o:-NBC0bn96DGQa9SZ-L3p:bq106ih) ([raw file](https://github.com/harness/harness-core/blob/de3b7ed2ab63840cdf32d125af0f7f3ab8f96d28/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptSpec.java#L41)):*
> ```Java
> 
>   // TIMEOUT
>   @JsonProperty(value = "timeout") String timeoutInMillisecond;
> ```

what if input is an absurdly high value? Does it affect the system in anyway?

**Review by nishantsaini20 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37109)* status: 3 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptSpec.java` line 41 at r2](https://reviewable.io/reviews/harness/harness-core/37109#-NBGJRYu2UXURq7wCs5y:-NBGJRYu2UXURq7wCs5z:b-4z5pgb) ([raw file](https://github.com/harness/harness-core/blob/de3b7ed2ab63840cdf32d125af0f7f3ab8f96d28/878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptSpec.java#L41)):*
> ```Java
> 
>   // TIMEOUT
>   @JsonProperty(value = "timeout") String timeoutInMillisecond;
> ```

Why data type is String?

**Pull request closed without merging**
