### PR TITLE
feat:[CDS-45189]: commands step support for deployment template

### PR DESCRIPTION
**Pull request by anilchowdhury-harness**
feat:[CDS-45189]: commands step support for deployment template

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-45189]: https://harness.atlassian.net/browse/CDS-45189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39572)

### CODE REVIEW

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39572)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java` line 592 at r1](https://reviewable.io/reviews/harness/harness-core/39572#-NFxsWR43Hlj1msv-mdX:-NFxsWR43Hlj1msv-mdY:b-m0hxfx) ([raw file](https://github.com/harness/harness-core/blob/be4b16b3d4bd07456b4e114f6cd12f099d095938/125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java#L592)):*
> ```Java
>             .setFeatureFlag(FeatureName.SSH_NG.name())
>             .setStepMetaData(
>                 StepMetaData.newBuilder().addAllCategory(CUSTOM_DEPLOYMENT_CATEGORY).addFolderPaths("Commands").build())
> ```

nit: can we use the constant `COMMANDS` here?

**Review by acasian-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39572)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Review by ivan-83 — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39572)* status: :shipit: complete! ✓

___
*[`950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/EmptyHostDelegateConfig.java` line 16 at r3](https://reviewable.io/reviews/harness/harness-core/39572#-NG2fVhX6GrWer5Zl3QU:-NG2fVhX6GrWer5Zl3QV:b5fwoxi) ([raw file](https://github.com/harness/harness-core/blob/56c6d2e14a9c544229121eb7b924321a37322801/950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/ssh/EmptyHostDelegateConfig.java#L16)):*
> ```Java
> @Builder
> @OwnedBy(HarnessTeam.CDP)
> public class EmptyHostDelegateConfig implements SshInfraDelegateConfig {
> ```

Minor and not so important can be done later - I will still rename this to CustomSshInfraDelegateConfig

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39572#-:-NG2gk9D4ISWmnJyrGJs:bnfp4nl)* status: :shipit: complete! ✓

**Review by acasian-harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39572)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Pull request merged**
