### PR TITLE
feat: [PIE-5462]: Metadata for Parent Pipeline in execution metadata …

### PR DESCRIPTION
**Pull request by prashantsharma04**
…of child pipeline in ambiance

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/38851)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
trigger ft2

**Comment by prashantsharma04** [comment]
trigger ft2

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38851)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/38851#-NEjqH9IEyiA_IbT_2cg:-NEjqH9IEyiA_IbT_2ch:b-tb14r5) ([raw file](https://github.com/harness/harness-core/blob/86264acc3738756e642e6ed7531bed565f903cda/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L42)):*
> ```protobuf
>   string executionId = 3;
>   string identifier = 4;
>   string project = 5;
> ```

projectId
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/38851#-NEjqI3a6c8sIzCssG4o:-NEjqI3a6c8sIzCssG4p:b-7lhiva) ([raw file](https://github.com/harness/harness-core/blob/86264acc3738756e642e6ed7531bed565f903cda/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L43)):*
> ```protobuf
>   string identifier = 4;
>   string project = 5;
>   string org = 6;
> ```

orgId

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38851)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/38851#-NEjqH9IEyiA_IbT_2cg:-NEjtf4J09-SRCX6UoRJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86264acc3738756e642e6ed7531bed565f903cda/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L42)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

projectId
</blockquote></details>

Done.
___
*[`pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/38851#-NEjqI3a6c8sIzCssG4o:-NEjtfjB9nrwxcf5Uxy9:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/86264acc3738756e642e6ed7531bed565f903cda/pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

orgId
</blockquote></details>

Done.

**Review by archit-harness — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38851)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/38851)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Comment by prashantsharma04** [comment]
trigger ti3

**Pull request merged**
