### PR TITLE
[fix]: [CDS-40341]: parsing TF plan summary, exposing TF add/change/destroy …

### PR DESCRIPTION
**Pull request by markoharness**
…as expressions, not uploading TF plan if there is no changes

Responses to hashcheck checklist:
1. No
2. No
3. Yes
4. No
5. No
6. No

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35648)

### CODE REVIEW

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35648)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7ousWiEv38vNbMrIf6:-N7ousWiEv38vNbMrIf7:b-jphtqf) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L374)):*
> ```Java
>           : Scope.PIPELINE;
> 
>       saveTerraformPlanSummary(executionData, null, tfPlanParamBuilder, null, null, false);
> ```

nit: this logic is a bit confusing because you have a lot of null parameters, maybe saveTerraformPlanSummary can be split in save and populate methods
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 569 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7osWUw-T-sE2ZLPFEx:-N7osWUw-T-sE2ZLPFEy:bba8vu0) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L569)):*
> ```Java
> 
>       if (parameters.isExportPlanToApplyStep()
>           && (terraformPlanSummary == null || terraformPlanSummary.isChangesExist())) {
> ```

if we're going to save terrafom plan in case that there is no any changes, will it not result in terraform apply recalculating changes to be applied? Or we aren't handling this case in current implementation as well?
___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 685 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7otjetEHr-LoQ-peQ-:-N7otjetEHr-LoQ-peQ0:b-3t67fi) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L685)):*
> ```Java
>       TerraformProvisionParameters parameters, Map<String, String> envVars, LogCallback logCallback,
>       PlanLogOutputStream planLogOutputStream) throws IOException, InterruptedException, TimeoutException {
>     String command = format("terraform show %s", tfplanFileName);
> ```

Wouldn't it be safer to get json plan instead and parse json plan instead? I can see that now our logic of parsing can fail dependent on version if there is a chance that formatting can change. And json logic can be integrated with save tf plan json (at least latter). At least maybe running with no-color can be easier to parse.

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 374 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7ousWiEv38vNbMrIf6:-N7zTYdpAeReS46ReDuK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L374)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nit: this logic is a bit confusing because you have a lot of null parameters, maybe saveTerraformPlanSummary can be split in save and populate methods
</blockquote></details>

done

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 569 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7osWUw-T-sE2ZLPFEx:-N7zTcrP1nWbM75HITlh:bcgi0kt) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L569)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

if we're going to save terrafom plan in case that there is no any changes, will it not result in terraform apply recalculating changes to be applied? Or we aren't handling this case in current implementation as well?
</blockquote></details>

Added FF and placed the logic behind it.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 685 at r2](https://reviewable.io/reviews/harness/harness-core/35648#-N7otjetEHr-LoQ-peQ-:-N7zTi7p2dSXVP8BcV4-:bkckkjp) ([raw file](https://github.com/harness/harness-core/blob/727806f393f272627375b83f86651c02bb9c90c1/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L685)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Wouldn't it be safer to get json plan instead and parse json plan instead? I can see that now our logic of parsing can fail dependent on version if there is a chance that formatting can change. And json logic can be integrated with save tf plan json (at least latter). At least maybe running with no-color can be easier to parse.
</blockquote></details>

Changed the logic to use json plan

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 26 of 26 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35648)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 382 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83uD7P0CgxEM2kA4AL:-N83uD7P0CgxEM2kA4AM:bv8wg2w) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L382)):*
> ```Java
>     } else {
>       populateTerraformPlanParamWithSummaryInfo(tfPlanParamBuilder, executionData, context);
>       saveTerraformPlanSummary(context, terraformCommand, tfPlanParamBuilder);
> ```

save is not guarded by FF
___
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1029 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83uJ6XAjYEBOnSKKnw:-N83uJ6XAjYEBOnSKKnx:b-rnag08) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1029)):*
> ```Java
>           environmentVars = extractData(fileMetadata, ENVIRONMENT_VARS_KEY);
>           if (environmentVars != null
>               && featureFlagService.isNotEnabled(ANALYSE_TF_PLAN_SUMMARY, context.getAccountId())) {
> ```

It's going to be any harm if we leave these details? 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 473 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83ujN2Amx76VGJSpPZ:-N83ujN2Amx76VGJSpP_:b-aog74u) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L473)):*
> ```Java
> 
>     log.error("Parsing Terraform Plan summary has failed!");
>     logCallback.saveExecutionLog("Parsing Terraform Plan summary has failed!");
> ```

it should be at least with LogLevel.WARN 
___
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 400 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83wNbP9qmjjmOEQ2NC:-N83wNbP9qmjjmOEQ2ND:bw935fu) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L400)):*
> ```Java
>   ATTRIBUTE_TYPE_ACL_ENABLED("Enable attribute filter on NG UI for ACL", HarnessTeam.PL),
>   CREATE_DEFAULT_PROJECT("Enables auto create default project after user signup", HarnessTeam.GTM),
>   ANALYSE_TF_PLAN_SUMMARY;
> ```

please add description and harness team

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 1029 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83uJ6XAjYEBOnSKKnw:-N840gHh4vVCsr6947xk:b-gdhamk) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L1029)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

It's going to be any harm if we leave these details? 
</blockquote></details>

It is just a precaution. There might be some leftover values if between re-runs of the workflow FF is deactivated, hence the logic to remove the values altogether if the FF is not active.

**Comment by markoharness** [comment]
*[`400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java` line 382 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83uD7P0CgxEM2kA4AL:-N843IECDxkM-EHPy9Hi:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java#L382)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

save is not guarded by FF
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 473 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83ujN2Amx76VGJSpPZ:-N843KFg8kxKzO4SOnWA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L473)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

it should be at least with LogLevel.WARN 
</blockquote></details>

Done.

**Comment by markoharness** [comment]
*[`956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java` line 400 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83wNbP9qmjjmOEQ2NC:-N843MLe3oDTqodzNsRb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java#L400)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

please add description and harness team
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35648)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 473 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83ujN2Amx76VGJSpPZ:-N845PhT-Kbv6A97vHqI:b1cdl6y) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L473)):*
<details><summary><i>Previously, markoharness (Marko Lukic) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean logCallback

**Comment by markoharness** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java` line 473 at r3](https://reviewable.io/reviews/harness/harness-core/35648#-N83ujN2Amx76VGJSpPZ:-N84660DB-RVrD_9WHMo:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6813057ef6e9065b7c0a25ee0c49556a8dd58362/930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java#L473)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

I mean logCallback
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35648)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r1, 1 of 5 files at r2, 18 of 26 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35648#-:-N87vRw36nNOLt9mNKr_:bnfp4nl)* status: :shipit: complete! ✓

**Comment by markoharness** [comment]
trigger codebasehash

**Pull request merged**
