### PR TITLE
feat:[CDS-81152]: fix connectors, cdstage and tags handler issues

### PR DESCRIPTION
**Pull request by RishabhGupta34**
## Describe your changes
Fix Connectors and CD Stage execution handler to update instead of insert in case the record is already present, as it was using only insert earlier, it was printing a lot of error messages in cdc service, as the insert event might have got delayed and the update event might have already inserted that row
Fix tags handler ng to use ARRAY insert instead of string insert, this was causing issues in inserting for special characters, for e.g. if the tags have `{}` brackets in it.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54302)

### CODE REVIEW

**Comment by RishabhGupta34** [comment]
trigger uts

**Review by abhinavmittal-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54302)* status: 10 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`110-change-data-capture/src/main/java/io/harness/changehandlers/TagsInfoCDChangeDataHandlerHelper.java` line 247 at r1](https://reviewable.io/reviews/harness/harness-core/54302#-Nh1SuSxClTgvPYSnBrP:-Nh1SuSxClTgvPYSnBrQ:b-y5njog) ([raw file](https://github.com/harness/harness-core/blob/699de6677e46634844b07c2bb68e7480c73fe1a4/110-change-data-capture/src/main/java/io/harness/changehandlers/TagsInfoCDChangeDataHandlerHelper.java#L247)):*
> ```Java
>       String tagKey = tag.get(NGTagKeys.key).toString();
>       String tagValue = tag.get(NGTagKeys.value) == null ? "" : tag.get(NGTagKeys.value).toString();
>       tagKey = tagKey.replaceAll("(?<!\\\\)\\\"", "\\\\\"");
> ```

Make these constants Reduces chances of typos and a comment as to why we are doing so

**Comment by RishabhGupta34** [comment]
trigger uts

**Comment by RishabhGupta34** [comment]
trigger ut5,ut6,ut7,ut8,ut9

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54302)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by Abhishek-CDC — APPROVED** [review]

**Comment by RishabhGupta34** [comment]
trigger messagecheck, review

**Pull request merged**
