### PR TITLE
feat: [PL-29034]: introduce account license observer

### PR DESCRIPTION
**Pull request by abhinav-harness**
## Describe your changes
We plan to emit a hook for any service to do some kind of activity - say not perform certain activity - if license of account is deleted or account is marked for deletion

with this we plan to provide hook based on any license change that happen on an account

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39014)

### CODE REVIEW

**Review by pranil-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39014)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39014)* status: 4 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39014)* status: :shipit: complete! ✓

**Review by shreyas-harness — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39014)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/39014#-NEngoK48j-IkmIl64Pb:-NEngoK48j-IkmIl64Pc:b-abkdj2) ([raw file](https://github.com/harness/harness-core/blob/95391ecdcae4b58fb7913dee0669c73f1a53a0df/400-rest/src/main/java/software/wings/licensing/LicenseServiceImpl.java#L122)):*
> ```Java
>       EmailNotificationService emailNotificationService, EventPublishHelper eventPublishHelper,
>       MainConfiguration mainConfiguration, UserService userService, UserGroupService userGroupService,
>       NgLicenseHttpClient ngLicenseHttpClient, Subject<AccountLicenseObserver> accountLicenseObserverSubject) {
> ```

Why are we having it as constructor parameter if its value is not being used ?

**Comment by abhinav-harness** [comment]
trigger messagecheck

**Pull request merged**
