### PR TITLE
feat: [PIE-3854]: Support for maxConcurrency in orchestrationEngine

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

What is this PR about?
For matrix/looping, we have a requirement of running n number of executions in parallel with maxConcurrency, this change is to support that maxConcurrency.For example: If I have 10 parallel nodes and if max concurrency is 5 then we will have 5 nodes running at first then if one of them finishes, we will start the next.

What is the design to support this?
We have used waitEngine to support this. We first start by running maxConcurrent nodes in parallel and to each of the node, we attach a callback that gets called when the node is completed. Inside that callback, we have added a logic to start the next child if there is any.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)

### CODE REVIEW

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/concurrency/ConcurrentChildInstance.java` line 29 at r1](https://reviewable.io/reviews/harness/harness-core/33970#-N3shdPHCH9zW6UIC_TX:-N3shdPIAK-xqo37VMej:b-7v7ko9) ([raw file](https://github.com/harness/harness-core/blob/298cf0aad8dc1faaec12815801adf20196ce9749/870-orchestration/src/main/java/io/harness/concurrency/ConcurrentChildInstance.java#L29)):*
> ```Java
> @StoreIn(DbAliases.PMS)
> @OwnedBy(HarnessTeam.PIPELINE)
> public class ConcurrentChildInstance {
> ```

Merge with NodeExecutionInfo

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33970#-N3si_Ro-u9ddd6KB0JP:-N3si_Ro-u9ddd6KB0JQ:b2cu4uv) ([raw file](https://github.com/harness/harness-core/blob/298cf0aad8dc1faaec12815801adf20196ce9749/870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java#L46)):*
> ```Java
>     String lockName = String.format(EXECUTION_START_PREFIX, parentNodeExecutionId);
>     try (AcquiredLock<?> lock =
>              persistentLocker.waitToAcquireLock(lockName, Duration.ofSeconds(10), Duration.ofSeconds(30))) {
> ```

Add exception for lock



_Code quote:_
```Java
lockName 
```

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 103 at r1](https://reviewable.io/reviews/harness/harness-core/33970#-N3slpgj2lrJtYF2JOBd:-N3slpgj2lrJtYF2JOBe:b-evrpgs) ([raw file](https://github.com/harness/harness-core/blob/298cf0aad8dc1faaec12815801adf20196ce9749/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L103)):*
> ```Java
> 
>   private boolean shouldCreateAndStart(int maxConcurrency, int currentChild) {
>     return maxConcurrency == 0 || currentChild < maxConcurrency;
> ```

Add a note to add upper limit on maxConcurrency

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 10 of 18 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: 26 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33970#-N3si_Ro-u9ddd6KB0JP:-N3x-XL034fb5JXjnKdG:bhz1yj7) ([raw file](https://github.com/harness/harness-core/blob/298cf0aad8dc1faaec12815801adf20196ce9749/870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java#L46)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Add exception for lock
</blockquote></details>

this i think is still left
___
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 67 at r2](https://reviewable.io/reviews/harness/harness-core/33970#-N3x0_0Y0X1dMuxL35LT:-N3x0_0Y0X1dMuxL35LU:bnj7fem) ([raw file](https://github.com/harness/harness-core/blob/35923ca0ad705687b16005577a68a3a6c4708399/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L67)):*
> ```Java
>         callbackIds.add(uuid);
>         if (pmsFeatureFlagService.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.PIPELINE_MATRIX)) {
>           InitiateMode initiateMode = InitiateMode.CREATE;
> ```

apart from here where is the other initiateMode when this ff is disabled?
___
*[`870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java` line 79 at r2](https://reviewable.io/reviews/harness/harness-core/33970#-N3x0jc72vxx-YcriSTe:-N3x0jc88SXNzF0JgMVP:bms1zfg) ([raw file](https://github.com/harness/harness-core/blob/35923ca0ad705687b16005577a68a3a6c4708399/870-orchestration/src/main/java/io/harness/event/handlers/SpawnChildrenRequestProcessor.java#L79)):*
> ```Java
>       }
> 
>       if (pmsFeatureFlagService.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.PIPELINE_MATRIX)) {
> ```

above if condition also checks for same ff right?



_Code quote:_
```Java
f (pmsFeatureFlagService.isEnabled(AmbianceUtils.getAccountId(ambiance), FeatureName.PIPELINE_MATRIX)) {
```
___
*[`870-orchestration/src/main/java/io/harness/graph/stepDetail/PmsGraphStepDetailsServiceImpl.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/33970#-N3x-Dxq9GnERuoPycf0:-N3x-Dxq9GnERuoPycf1:bqf636y) ([raw file](https://github.com/harness/harness-core/blob/35923ca0ad705687b16005577a68a3a6c4708399/870-orchestration/src/main/java/io/harness/graph/stepDetail/PmsGraphStepDetailsServiceImpl.java#L124)):*
> ```Java
> 
>   @Override
>   public ConcurrentChildInstance updateCursor(String nodeExecutionId) {
> ```

nit: incrementCursor ?



_Code quote:_
```Java
updateCursor(
```
___
*[`876-orchestration-beans/src/main/java/io/harness/concurrency/ConcurrentChildInstance.java` line 11 at r2](https://reviewable.io/reviews/harness/harness-core/33970#-N3wzmUO2VcYORc18Zvf:-N3wzmUP3qMETEOZlOfv:b-2f84rq) ([raw file](https://github.com/harness/harness-core/blob/35923ca0ad705687b16005577a68a3a6c4708399/876-orchestration-beans/src/main/java/io/harness/concurrency/ConcurrentChildInstance.java#L11)):*
> ```Java
> public class ConcurrentChildInstance {
>   private List<String> childrenNodeExecutionIds;
>   private int cursor;
> ```

nit: Can we add comment what is cursor and what its value would mean, like o based index on where we are in childrenNodes



_Code quote:_
```Java
private int cursor
```

**Comment by sahilhindwani-harness** [comment]
trigger codebasehash

**Comment by sahilhindwani-harness** [comment]
trigger ft2

**Comment by sahilhindwani-harness** [comment]
trigger ti2

**Comment by sahilhindwani-harness** [comment]
*[`870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/33970#-N3si_Ro-u9ddd6KB0JP:-N41-mNSEJViRf3GEIZW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/298cf0aad8dc1faaec12815801adf20196ce9749/870-orchestration/src/main/java/io/harness/concurrency/MaxConcurrentChildCallback.java#L46)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this i think is still left
</blockquote></details>

Done.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 10 of 18 files at r1, 7 of 16 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: 26 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: 26 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 10 of 18 files at r1, 6 of 16 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970#-:-N417Y4eA_1m5sYqXCFg:bnfp4nl)* status: 4 file(s) to review.

**Review by naidu-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: 4 file(s) to review.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 10 of 18 files at r1, 6 of 16 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: 4 file(s) to review.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 4 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33970)* status: :shipit: complete! ✓

**Pull request merged**
