### PR TITLE
fix: [CDS-59112]: added ttlfield, migration handling cleanup and populate ttl field

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes
- added VaildUntil (TTL) field in approvalInstances with value as 6 months from time of creation of instance. 
- Added a migration: 
-- deleting old incompatible records.
-- On newer records populated validUntil field based on createdAt field (done using iterator, and bulk update with 500 batch size)
- Testing: Tested with preQA dump locally. Records created before 1 yr got deleted by delete query; records created between 1 yr and 6 months got auto-deleted by ttl field, for records created from 6 months to till date were adequately populated with TTL field. Newer records also had ttl field populated.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47178)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger utAll

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVIidu7dfyJEwus8cL:-NUVIidu7dfyJEwus8cM:b-he5qqz) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L61)):*
> ```Java
>     int totalApprovalInstancesUpdated = 0;
>     try {
>       log.info(DEBUG_LOG + "Starting migration of ttl field in Approval instances");
> ```

Instead of putting DEBUG_LOG in every log statement, you can simply put it in the context. Then it will get auto-appended in all the logs.
Also, even if you don't use context, you should have simply used a private method that decorates your log statement with DEBUG_LOG, instead of manually adding it everywhere.

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVJBSa85K_o--bXyBT:-NUVJBSa85K_o--bXyBU:bkkvwyy) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L73)):*
> ```Java
>         log.error(
>             String.format(
>                 "%s Migration of ttl field in Approval instances failed during deletion of old incompatible records",
> ```

The log statement says "migration failed", so should we return from here or still we can go ahead with rest of the migration?

**Comment by naman-goenka** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVJBSa85K_o--bXyBT:-NUVJBSa85K_o--bXyBU:bkkvwyy) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L73)):_
> 
> > ```java
> >         log.error(
> >             String.format(
> >                 "%s Migration of ttl field in Approval instances failed during deletion of old incompatible records",
> > ```
> 
> The log statement says "migration failed", so should we return from here or still we can go ahead with rest of the migration?

We can go ahead because in next query we searching the complement set for the first query

**Comment by mohitg0795** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVJBSa85K_o--bXyBT:-NUVM60K2R6xeH9Xva1o:b-m4vdni) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L73)):*
<details><summary><i>Previously, naman-goenka (Naman Goenka) wrote…</i></summary><blockquote>

We can go ahead because in next query we searching the complement set for the first query
</blockquote></details>

If thats the case, I would recommend to convert it into a warning log or else don't mention that migration failed. We can simply say deletion of old incompatible records failed. Saying migration failed can cause confusion unnecessarily.

**Comment by naman-goenka** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 61 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVIidu7dfyJEwus8cL:-NUVIidu7dfyJEwus8cM:b-he5qqz) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L61)):_
> 
> > ```java
> >     int totalApprovalInstancesUpdated = 0;
> >     try {
> >       log.info(DEBUG_LOG + "Starting migration of ttl field in Approval instances");
> > ```
> 
> Instead of putting DEBUG_LOG in every log statement, you can simply put it in the context. Then it will get auto-appended in all the logs. Also, even if you don't use context, you should have simply used a private method that decorates your log statement with DEBUG_LOG, instead of manually adding it everywhere.

done

**Comment by naman-goenka** [comment]
> _[`pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java` line 73 at r2](https://reviewable.io/reviews/harness/harness-core/47178#-NUVJBSa85K_o--bXyBT:-NUVM60K2R6xeH9Xva1o:b-m4vdni) ([raw file](https://github.com/harness/harness-core/blob/350894b30915ce7523b33623494e6f3f1c95a4fa/pipeline-service/service/src/main/java/io/harness/pms/migration/PopulateTTLFieldAndDeleteOldInApprovalInstancesMigration.java#L73)):_
> 
> Previously, naman-goenka (Naman Goenka) wrote…
> If thats the case, I would recommend to convert it into a warning log or else don't mention that migration failed. We can simply say deletion of old incompatible records failed. Saying migration failed can cause confusion unnecessarily.

done

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47178)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by naman-goenka** [comment]
trigger utAll

**Review by puthrayaharness — APPROVED** [review]

**Comment by naman-goenka** [comment]
trigger review

**Comment by naman-goenka** [comment]
trigger review

**Pull request merged**
