### PR TITLE
feat: [PL-26639]: Remove user group copy functionality

### PR DESCRIPTION
**Pull request by gupta-utkarsh**
## Describe your changes

Remove copy user group functionality.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36120)

**Review by reetika04 — DISMISSED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120#-:-N8w0o5mE_6YMoc7D4qC:bnfp4nl)* status: :shipit: complete! ✓

**Review by Jimit09Gandhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/36120#-N8w18Ld8go7Ri_drLta:-N8w18Ld8go7Ri_drLtb:bd049sr) ([raw file](https://github.com/harness/harness-core/blob/a787f6defa282b2847ed5b8c6dd1de627acc3c06/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L192)):*
> ```Java
>     throw new InvalidRequestException(
>         "This feature is no longer available. You can now assign role assignments at project/org to user groups linked at account level.");
>   }
> ```

Can change project/org => project/organization



_Code quote:_
```Java
project/org
```

**Review by gupta-utkarsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java` line 192 at r2](https://reviewable.io/reviews/harness/harness-core/36120#-N8w18Ld8go7Ri_drLta:-N8w4NoN3yiaOwt8RWkj:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/a787f6defa282b2847ed5b8c6dd1de627acc3c06/120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java#L192)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Can change project/org => project/organization
</blockquote></details>

Done

**Review by Jimit09Gandhi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 1 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 1 file(s) to review.

**Review by reetika04 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120#-:-N8w9ZMl0lSdZmr5ugtz:bnfp4nl)* status: 1 file(s) to review.

**Review by Jimit09Gandhi — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: 1 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36120)* status: :shipit: complete! ✓

**Pull request merged**
