### PR TITLE
feat: [PIE-2687]: Add monitoring flag to interrupt and cleanup step params

### PR DESCRIPTION
**Pull request by hextechpal**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30726)

### CODE REVIEW

**Comment by hextechpal** [comment]
trigger messagecheck

**Comment by hextechpal** [comment]
trigger messagecheck

**Comment by hextechpal** [comment]
trigger messagecheck

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30726)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30726#-:-MvwgOF59IuWYtL0kfwL:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
