### PR TITLE
[feat]: [PL-24528]: Add support for new git context fields

### PR DESCRIPTION
**Pull request by namanvermah**
These changes add the new query params to the git context, and provide methods to query the git context. Moreover, these changes include methods to get and set the SCM Git Metadata

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33529)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger ti2

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33529#-:-N2v0MrC7a-_urROc-ai:bnfp4nl)* status: 14 file(s) to review. 1 of 2 approvals obtained.

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33529)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 4 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33529)* status: :shipit: complete! ✓

**Pull request merged**
