### PR TITLE
[techdebt]: [PIE-3923]: Move validation during pipeline create to service layer

### PR DESCRIPTION
**Pull request by namanvermah**
In order to move pipeline validation into the service layer, the service layer also needs to return the governanceMetadata along with the (if created) Pipeline Entity, hence the change in structure of response of the create method.

This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33724)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33724)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33724)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Comment by namanvermah** [comment]
trigger ft1, ft2

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33724)* status: 2 file(s) to review. 1 of 2 approvals obtained.

**Pull request merged**
