### PR TITLE
fix: [PL-31996]: Fixing manual deletion flows when FF PL_USER_DELETION is ON

### PR DESCRIPTION
**Pull request by boopesh007**
## Describe your changes
image

Thrown error info to the user when active NG user is deleted from CG
Persisted user group removal for the user in DB when the CG user is getting deleted manually keeping the user active in NG. 
Made the NG manual deletion flow to delete from CG if the last scope from NG is deleted. 

Test cases tested
Manual flows and SCIM flows through OKTA. 
Test case tested are present in this comment https://harness.atlassian.net/browse/PL-23577?focusedCommentId=392391

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45141)

### CODE REVIEW

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45141)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Comment by pbarapatre10** [comment]
Minor : please test all SCIM, Manual User Invite, LDAP flows in PR environment as well apart from local, thanks

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 425 at r3](https://reviewable.io/reviews/harness/harness-core/45141#-NQf1p5L-ibxHZx4aYMd:-NQf1p5L-ibxHZx4aYMe:b9jjct7) ([raw file](https://github.com/harness/harness-core/blob/db4a02d47a38f68b0635c5b71e77acab0fee4e73/400-rest/src/main/java/software/wings/resources/UserResource.java#L425)):*
> ```Java
>     if (featureFlagService.isEnabled(FeatureName.PL_USER_DELETION_V2, accountId) && userService.isUserPresent(userId)) {
>       User deletedUser = userService.get(userId);
>       if (deletedUser != null && isEmpty(user.getUserGroups())) {
> ```

use something like
isUserPartOfAnyUserGroupInCG and handl user not found exception instead of calling DB two times.

**Comment by boopesh007** [comment]
trigger ut1

**Comment by boopesh007** [comment]
trigger ut5

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResource.java` line 425 at r3](https://reviewable.io/reviews/harness/harness-core/45141#-NQf1p5L-ibxHZx4aYMd:-NQykIya-8p-wY6JCLDV:buxshdk) ([raw file](https://github.com/harness/harness-core/blob/db4a02d47a38f68b0635c5b71e77acab0fee4e73/400-rest/src/main/java/software/wings/resources/UserResource.java#L425)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

use something like
isUserPartOfAnyUserGroupInCG and handl user not found exception instead of calling DB two times.
</blockquote></details>

as discussed, this is needed for now

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/resources/UserResourceNG.java` line 201 at r3](https://reviewable.io/reviews/harness/harness-core/45141#-NQf2Llr7O-MeWCFO-YU:-NQykQhT6AyonvWYHmdA:b-yaq1af) ([raw file](https://github.com/harness/harness-core/blob/db4a02d47a38f68b0635c5b71e77acab0fee4e73/400-rest/src/main/java/software/wings/resources/UserResourceNG.java#L201)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

just check if first method is required.
</blockquote></details>

as discussed this is required.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 1 of 2 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45141)* status: 5 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto,del-team. 

*[a discussion](https://reviewable.io/reviews/harness/harness-core/45141#-NQe_Ju33uF6VCQ0FNG_:-NQykr_2C2giZS43bvv4:bh8hez6) (no related file):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

Minor : please test all SCIM, Manual User Invite, LDAP flows in PR environment as well apart from local, thanks
</blockquote></details>

tested.

___

**Pull request merged**
