### PR TITLE
[fix]: [PL-24403]: Add the logic to mark the previous succesful files as suc…

### PR DESCRIPTION
**Pull request by DeepakPatankar**
…cess which were not able to mark because of the full sync bug

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)

### CODE REVIEW

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 103 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQ7GE3PMGJp-TpnqZ:-MzyQ7GF9wwTx2G2OO3_:bagm4t5) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L103)):*
> ```Java
>                             .ne(currentJobId)
>                             .and(GitFullSyncEntityInfoKeys.syncStatus)
>                             .is(QUEUED);
> ```

This can give multiple entities, suppose already 2 jobs of full-sync are done and in both jobs there was the same entity but in different syncStatus, the both will be marked as success.
Also, while creating entity we are not saving job id, we have to save that also.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: 7 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 72 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQaQPAqUqCOy8zl2w:-MzyQaQPAqUqCOy8zl2x:b9rsmgk) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L72)):*
> ```Java
>     final ScopeDetails scopeDetails = getScopeDetails(gitConfigScope, messageId);
>     String accountId = gitConfigScope.getAccountId();
>     String projectId = gitConfigScope.getProjectId().getValue();
> ```

if projectId is null, will getValue throw NPE?
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 73 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQi449cdLCiSIRPyp:-MzyQi449cdLCiSIRPyq:bb7od0r) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L73)):*
> ```Java
>     String accountId = gitConfigScope.getAccountId();
>     String projectId = gitConfigScope.getProjectId().getValue();
>     String orgId = gitConfigScope.getOrgId().getValue();
> ```

same

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 72 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQaQPAqUqCOy8zl2w:-MzyZjlv3WhaYu89e1l8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L72)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

if projectId is null, will getValue throw NPE?
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 73 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQi449cdLCiSIRPyp:-MzyZkJN4P5svgcW7CCv:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L73)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 103 at r3](https://reviewable.io/reviews/harness/harness-core/32059#-MzyQ7GE3PMGJp-TpnqZ:-MzybQL69XTgzLcqGl2h:br8o23z) ([raw file](https://github.com/harness/harness-core/blob/ebddd054bb79ca602423370b4c9054fad47a1681/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L103)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

This can give multiple entities, suppose already 2 jobs of full-sync are done and in both jobs there was the same entity but in different syncStatus, the both will be marked as success.
Also, while creating entity we are not saving job id, we have to save that also.
</blockquote></details>

Oh fullSyncJobId is not populated would have created issues. 

Things worked fine on local testing, but would have broken some flows.

Made the changes to use messageId.

Will be doing the chhange to save the job Id in a different PR



_Code quote:_
```Java
fullSyncJobId
```

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 135 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-MzyyhiaC4tKgcssB8p8:-MzyyhibCt3MHWoFAMQ8:b5ro7wo) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L135)):*
> ```Java
>     for (GitFullSyncEntityInfo gitFullSyncEntityInfo : entitiesBelongingToPrevJobs) {
>       log.info("Marking the full sync entity with uuid {} as succesful", gitFullSyncEntityInfo.getUuid());
>       gitFullSyncEntityService.updateStatus(
> ```

we should have a try catch block here to prevent its failure not to affect the main thread. If any exception occurs, its fine and can be ignored for the moment. It will be re-processed in next iteration.

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 134 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzyys125f2eXOfiAH_g:-Mzyys125f2eXOfiAH_h:b-qe5x22) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L134)):*
> ```Java
>     }
>     for (GitFullSyncEntityInfo gitFullSyncEntityInfo : entitiesBelongingToPrevJobs) {
>       log.info("Marking the full sync entity with uuid {} as succesful", gitFullSyncEntityInfo.getUuid());
> ```

Also, we can put this log after the successful marking of the entity.

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityService.java, line 42 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzyz03bBMIMfs1SHi_C:-Mzyz03bBMIMfs1SHi_D:b970fpt) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityService.java#L42)):*
> ```Java
>       String accountIdentifier, String orgIdentifier, String projectIdentifier, String filePath);
> 
>   List<GitFullSyncEntityInfo> getQueuedEntityFromPrevJob(
> ```

it should be getQueuedEntityList or getQueuedEntities ...

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 91 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-MzyzVrVE78yHAULHvSy:-MzyzVrVE78yHAULHvSz:b2uab6f) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L91)):*
> ```Java
> 
>   @Override
>   public List<GitFullSyncEntityInfo> getQueuedEntityFromPrevJob(
> ```

what is the meaning of prev job here?

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 253 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz-3m97TSPuwwXzGln:-Mzz-3m97TSPuwwXzGlo:b-cr1wa4) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L253)):*
> ```Java
>     for (GitFullSyncEntityInfo gitFullSyncEntityInfo : entitiesBelongingToPrevJobs) {
>       if (!filePathsToBeProcessed.contains(gitFullSyncEntityInfo.getFilePath())) {
>         gitFullSyncEntityService.updateStatus(
> ```

Here also we can put try catch to limit the blast radius upto here itself. Any exception in this call shouldn't affect the main thread.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: 7 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 134 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzyys125f2eXOfiAH_g:-Mzz05i89d7XvlM8qO9G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L134)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Also, we can put this log after the successful marking of the entity.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 135 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-MzyyhiaC4tKgcssB8p8:-Mzz0kz13rPD8ruNniBA:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L135)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

we should have a try catch block here to prevent its failure not to affect the main thread. If any exception occurs, its fine and can be ignored for the moment. It will be re-processed in next iteration.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityService.java, line 42 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzyz03bBMIMfs1SHi_C:-Mzz0vDDAUt_BXQ5btzt:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityService.java#L42)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

it should be getQueuedEntityList or getQueuedEntities ...
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 91 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-MzyzVrVE78yHAULHvSy:-Mzz0w6c5EfDxk_QDqex:b-daq16t) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

what is the meaning of prev job here?
</blockquote></details>

prev means previouus. Renamed Prev to Previous
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 253 at r4](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz-3m97TSPuwwXzGln:-Mzz1HFbDtwUuMwVszEz:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/12c7a76d1398fc5717140262d902a85095ec9af8/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L253)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Here also we can put try catch to limit the blast radius upto here itself. Any exception in this call shouldn't affect the main thread.
</blockquote></details>

Done.

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 141 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6BkBA4yt9HdSh5CM:-Mzz6BkBA4yt9HdSh5CN:b-upxva8) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L141)):*
> ```Java
>       }
>     } catch (Exception ex) {
>       log.info("Marking the previous queued files as successful failed", ex);
> ```

error log

also you can mention that ignoring syncing other stale entries for now.

**Comment by mohitg0795** [comment]
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 91 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6V-gELTIdL2F6Ejk:-Mzz6V-gELTIdL2F6Ejl:b-n6tf58) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L91)):*
> ```Java
> 
>   @Override
>   public List<GitFullSyncEntityInfo> getQueuedEntitiesFromPreviousJob(
> ```

lets make it "previousJobs" to be exactly clear.

**Review by DeepakPatankar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: 7 file(s) to review. 1 change requests. 11. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java, line 141 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6BkBA4yt9HdSh5CM:-MzzEsBP4h77apdwxuDC:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/FullSyncAccumulatorServiceImpl.java#L141)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

error log

also you can mention that ignoring syncing other stale entries for now.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java, line 91 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6V-gELTIdL2F6Ejk:-MzzF-B01hatFU94MLOr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncEntityServiceImpl.java#L91)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

lets make it "previousJobs" to be exactly clear.
</blockquote></details>

done
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 192 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6nJg-bi5Ge7sEhuB:-MzzFFd27CAb06o_GJgQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L192)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

can we rename this method a bit better: eg markAlreadyProcessedFilesAsSuccess() or markFilesSuccessWhichGotProcessedBefore() or markFilesSuccessWhichSucceededBefore() etc.
</blockquote></details>

Done.
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java, line 260 at r5](https://reviewable.io/reviews/harness/harness-core/32059#-Mzz6f4y87CDSZqyYUM5:-MzzFGLM4_tL6sB1v-uH:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c014ffccc10b4c07dc1f706a3b2ecb4fee5e81fc/136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync/GitFullSyncProcessorServiceImpl.java#L260)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

same as before.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059#-:-Mzz_2vI1eUMXwbjPpiu:bnfp4nl)* status: 7 file(s) to review. 1 change requests. 3. unresolved discussions. 1 of 2 approvals obtained.

**Review by bhavya181 — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32059)* status: :shipit: complete! ✓

**Pull request merged**
