### PR TITLE
[fix]: [PL-22504]: Add more logs to help us debug git to harness flow

### PR DESCRIPTION
**Pull request by DeepakPatankar**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30839)

### CODE REVIEW

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30839)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Comment by DeepakPatankar** [comment]
trigger ti4

**Comment by DeepakPatankar** [comment]
trigger messagecheck

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30839)* status: 1 file(s) to review.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30839)* status: :shipit: complete! ✓

**Review by bhavya181 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30839)* status: :shipit: complete! ✓

**Pull request merged**
