### PR TITLE
feat: [CDS-53790]: Display step in step pallete

### PR DESCRIPTION
**Pull request by rohitk-h**
## Describe your changes
- Add new manifest type for creating aliases for aws lambda manifest
- Add step in step pallete
- Fix use of strategy for lambda steps

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger messagecheck

**Comment by rohitk-h** [comment]
trigger feature-build

**Review by piyush-bhuwalka — DISMISSED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: 18 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 15 of 18 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: 17 file(s) to review. 1 of 2 approvals obtained.

**Review by sribalij — DISMISSED** [review]
> Reviewed 15 of 18 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 14 of 14 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: :shipit: complete! ✓

**Review by alluvamsi-harness — COMMENTED** [review]
> Reviewed 12 of 18 files at r1, 1 of 1 files at r2, 4 of 14 files at r4, 1 of 2 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by piyush-bhuwalka — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 14 of 14 files at r4, 2 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: 1 of 2 approvals obtained.

**Review by alluvamsi-harness — APPROVED** [review]
> Reviewed 10 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: :shipit: complete! ✓

**Review by puthrayaharness — APPROVED** [review]

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44244)* status: :shipit: complete! ✓

**Pull request merged**
