### PR TITLE
fix: [PL-30979]: Added EncryptedRecord types which are still locally encrypted

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Describe your changes
We have an iterator which fetches encryptedRecords which are locally encrypted and which is not GCP_KMS. It migrates all this records to globalKms. This is behind a FF.
background - we moved to gcp_kms as default SM in CG an year and half ago. This way we moved away from local encryption and started using GcpKms encryption for secrets encrypted via default harness SM. 
Current pr context - This pr includes a migrator to move all the existing secrets that are locally encrypted (these are more than an year and half years ago) to gcp_kms. This is a security issue as local encrypted secrets are very easy to decrypt. 

Testing:
1. Tested the secrets migration locally by creating a gcp_kms and making it as default and then turning this iterator on and verfied the migation of those secrets.
2. Tested the same in pr-env as well. Verified the iterator working based on FF. 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43729)

### CODE REVIEW

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/43729#-NO8GflS5P53FksjsQUa:-NO8GflT4U4_HNUBfjz9:b-ir4t1k) ([raw file](https://github.com/harness/harness-core/blob/c3143d6f2f79ab39edd361f3bc025262f03712a2/400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java#L164)):*
> ```Java
>                .hasAnyOf(accountIds)
>                .field(EncryptedDataKeys.type)
>                .notEqual(SettingVariableTypes.GCP_KMS)
> ```

Wouldn't this mean that credential for any GCP_KMS won't be migrated?
There will be GCP_KMS other than Global KMS too.
We should think on solving that.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java` line 101 at r4](https://reviewable.io/reviews/harness/harness-core/43729#-NOJsYzmAciL08G3Yx_6:-NOJsYzmAciL08G3Yx_7:b-4pa77v) ([raw file](https://github.com/harness/harness-core/blob/f5d338899ce2583e210978259d1b8b85c9f2da81/400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java#L101)):*
> ```Java
>     //      return getFilterQueryWithAccountIdsFilter(accountIds);
>     //    }
>     //
> ```

Why do we have commented lines here?
If this is not reqiured kindly delete.

**Comment by shashank-harness** [comment]
*[`400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/43729#-NO8GflS5P53FksjsQUa:-NOJsosh0Q0C04sb9YzP:b-o9tz3w) ([raw file](https://github.com/harness/harness-core/blob/c3143d6f2f79ab39edd361f3bc025262f03712a2/400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java#L164)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Wouldn't this mean that credential for any GCP_KMS won't be migrated?
There will be GCP_KMS other than Global KMS too.
We should think on solving that.
</blockquote></details>

 If handle method() is taking care of GLOBAL KMS then shouldn't we include GCP_KMS too in migration



_Code snippet:_
```Java
  public void handle(@NotNull EncryptedData encryptedData) {
    if (GLOBAL_ACCOUNT_ID.equals(encryptedData.getAccountId())) {
      return;
    }
```

**Review by VikasMaddukuriHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729)* status: 1 file(s) to review. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java` line 164 at r2](https://reviewable.io/reviews/harness/harness-core/43729#-NO8GflS5P53FksjsQUa:-NOJuaUDEoO5Cc70a7u6:b-xnjv3p) ([raw file](https://github.com/harness/harness-core/blob/c3143d6f2f79ab39edd361f3bc025262f03712a2/400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java#L164)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

 If handle method() is taking care of GLOBAL KMS then shouldn't we include GCP_KMS too in migration
</blockquote></details>

We are including GCP_KMS as well in migration. I changed the filterExpander query. Will update the pr once testing is done. Then it would be more clear and clean.
___
*[`400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java` line 101 at r4](https://reviewable.io/reviews/harness/harness-core/43729#-NOJsYzmAciL08G3Yx_6:-NOJuI4P47RviNDYTMFx:b-lbcrkw) ([raw file](https://github.com/harness/harness-core/blob/f5d338899ce2583e210978259d1b8b85c9f2da81/400-rest/src/main/java/software/wings/security/encryption/migration/EncryptedDataLocalToGcpKmsMigrationHandler.java#L101)):*
<details><summary><i>Previously, shashank-harness (Shashank Singh) wrote…</i></summary><blockquote>

Why do we have commented lines here?
If this is not reqiured kindly delete.
</blockquote></details>

So till now the FF will be picked right at the start of the iterator and after it starts, it will not pick up new accountIds unless we restart the iterator and add turn on FF for more accounts. I'm testing out the flow to make it pick up all values and handle only based on FF. Will remove this comments once tested.

**Review by shashank-harness — CHANGES_REQUESTED** [review]
Why have you removed FF from code?
How will we control this migration accountwise?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729#-:-NONefKL4j108Zz8jEmo:bvk2dc1)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by VikasMaddukuriHarness — COMMENTED** [review]
So the flow was, when we start the iterator, we check for all the accountIds which have this FF on and then fetch only those documents of those accountIds and encryptionType local. 
Now we removed this FF as the start of iterator and use the FF while handling the record. That means now all the encryptedRecords which have the encryptionType local will be fetched but we only handle (migrate) the ones which are of a accountId which has this FF turned on.

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729#-:-NONfFiZA_zw1WzPk-E3:b-n7mxvh)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729)* status: 1 file(s) to review.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43729)* status: :shipit: complete! ✓

**Pull request merged**
