### PR TITLE
feat: [SPG-143]: upgrade from yq3 to yq4: update write and delete

### PR DESCRIPTION
**Pull request by shivagowda**
**Upgrade yq3 to yq4**
Changes performed:
  1) Changed the download path to yq4 in ubi base image dockerfile. Also, changed in all dockerfiles to be on safer side for services that are still not on ubi
  2) Made many syntax changes 
    these are some samples equivalent changes in all scripts:
            *1. write:
  			//v3: yq write -i $CONFIG_FILE $CONFIG_KEY $CONFIG_VALUE
                         //v4: export CONFIG_VALUE; export CONFIG_KEY=.$CONFIG_KEY; yq -i 'eval(strenv(CONFIG_KEY))=env(CONFIG_VALUE)' $CONFIG_FILE
             *2. delete:
			//v3: yq delete -i $CONFIG_FILE events-mongo
			//v4: yq 'del(.events-mongo)' $CONFIG_FILE
Wrote [this tool](https://github.com/harness/dataeng/blob/main/yq/yq.go) to port the scripts

Testing completed:
we generated yamls using both yq3 and yq4 - [they matched with the following environments](https://docs.google.com/spreadsheets/d/19YaB-SBjCZJUP8TPUSLPbt3IdmdzuP6rVMNhEbfDfeo/edit#gid=704344118)
with onprem env variables - extracted from the respective services configMaps
with prod env variables - extracted from the respective services configMaps
Successfully deployed to [PR](https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/cd/orgs/default/projects/PREQA_NG_Pipelines/pipelines/PR_Harness_Env/deployments/BBhGrPOkRVO_RzKY7e-aRA/pipeline) and [pre-QA](https://app.harness.io/#/account/wFHXHD0RRQWoO8tIZT5YVw/app/-jRbnwPZRoOLj2NEhrbJnQ/pipeline-execution/0XZ601ihRF6xVACb7RjVRQ/workflow-execution/4CNaxQMpThKH9PasKUie1A/details)

CD, CDP, Delegate, CCM automation succeeded in pre-qa. [slack thread](https://harness.slack.com/archives/C026HMRS2V9/p1663602377805669)

**Rollout Plan:
[Release Plan](https://harness.atlassian.net/wiki/spaces/SPG/pages/21186150401/yq4+library+update+Release+Plan+Milestone-6)
1. merge current PR to develop --> base ubi image will be updated with yq4
2. build from the branch develop and push latest to TRUE: https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ci/orgs/default/projects/RELEASEMANAGEMENT/pipelines/ubibaseimages/pipeline-studio/?storeType=INLINE
  push all images by selecting TRUE
3. HF for next week: build base images with tag: yq3  https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/ci/orgs/default/projects/RELEASEMANAGEMENT/pipelines/ubibaseimages/executions/eZ4IEBMERUu2BWb02TM1ow/pipeline
4. For HF of independent deployable services: individual owners should build with yq3 if they want to HF

Gateway changes: https://github.com/wings-software/identity-gateway/pull/330

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_NA_** 
 


            
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36109)

**Comment by shivagowda** [comment]
trigger ti1, ti3, ti4, ft1, ft2, compile

**Comment by shivagowda** [comment]
trigger ft1, pmd, ti0, ti3

**Review by williamwissemann — DISMISSED** [review]
> Reviewed 41 of 41 files at r1, 37 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: Waiting on team(s): sto.

**Review by trunapushpa — DISMISSED** [review]

**Review by gupta-utkarsh — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 41 files at r1, 4 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109#-:-NAcu7Tv25InCpjO-irT:bnfp4nl)* status: Some of the checks are too old.

**Comment by shivagowda** [comment]
trigger ti1, ti2

**Comment by Fernando-Dourado** [comment]
trigger ti1, ti2

**Review by Fernando-Dourado — APPROVED** [review]
:lgtm:

> Reviewed 1 of 74 files at r3, 1 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109#-:-NBw6voE4phdFWCvPzzB:bnfp4nl)* status: 72 file(s) to review.

**Review by Fernando-Dourado — DISMISSED** [review]
> Reviewed 1 of 41 files at r1, 3 of 37 files at r2, 38 of 74 files at r3, 34 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109#-:-NC02DPQ7HhAnS7NbvAK:bnfp4nl)* status: 8 file(s) to review.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 39 of 74 files at r3, 31 of 35 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109#-:-NC02KPk27SbwUA5541w:bnfp4nl)* status: :shipit: complete! ✓

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 39 of 74 files at r3, 31 of 35 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 74 files at r3, 3 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by reetika04 — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by nikunj-badjatya — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by hitesharinga — APPROVED** [review]

**Review by hitesharinga — APPROVED** [review]

**Review by manish-manchanda — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Review by naidu-harness — APPROVED** [review]
:lgtm:

> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109#-:-NCPf7vq2qDBZr_uhngh:bnfp4nl)* status: :shipit: complete! ✓

**Review by williamwissemann — APPROVED** [review]
> Reviewed 39 of 74 files at r3, 29 of 35 files at r4, 6 of 8 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36109)* status: :shipit: complete! ✓

**Pull request merged**
