### PR TITLE
feat: [CDS-78455]: create PATCH API for pipelines

### PR DESCRIPTION
**Pull request by shalini-agr**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54131)

### CODE REVIEW

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54131)* status: 16 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4_Mu75LdtUWUqmatF:-Ni4_Mu75LdtUWUqmatG:b-1cx1m0) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/contracts/openapi/v1/openapi.yaml#L252)):*
> ```YAML
>         id: p672d7lofj32z
>     patch:
>       summary: Partially update a Pipeline
> ```

Patch api for pipeline entity and below also



_Code quote:_
```YAML
Partially update a Pipeline
```
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2926 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4_RdA8LDmRa8UePAS:-Ni4_RdA8LDmRa8UePAT:b-aobkpt) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/contracts/openapi/v1/openapi.yaml#L2926)):*
> ```YAML
>           desc: Pipeline Description
>           tags:
>             data:
> ```

data should be removed
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4a54L8mc8xmyOpp1C:-Ni4a54L8mc8xmyOpp1D:b673oa1) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L43)):*
> ```Java
>       update.set(PipelineEntityKeys.description, pipelineEntity.getDescription());
>     }
>     // Change this to not null check when CDS-81968 is done
> ```

add todo comment
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4b5Xb-sXDZR_63UyK:-Ni4b5Xb-sXDZR_63UyL:bg4y8rv) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L91)):*
> ```Java
>   }
> 
>   public PipelineEntity updateFieldsInDBEntryForPatch(
> ```

validate if audit is coming correctly
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4b7g60bZsN3gI8zXC:-Ni4b7g60bZsN3gI8zXD:bcmdqc4) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L92)):*
> ```Java
> 
>   public PipelineEntity updateFieldsInDBEntryForPatch(
>       PipelineEntity entityFromDB, PipelineEntity fieldsToUpdate, long timeOfUpdate) {
> ```

rename this to oldEntityFromDB in old and this method
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4ZTRo7TjdKpkAeSeE:-Ni4ZTRo7TjdKpkAeSeF:b-ua375v) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L137)):*
> ```Java
>   }
> 
>   public PipelineEntity toSimplifiedPipelineEntity(
> ```

nit: check if its needs to be overloaded
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4ZRJYEyrYX65hYHS5:-Ni4ZRJYEyrYX65hYHS6:b-5jtwiu) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L148)):*
> ```Java
>     }
>     if (NGExpressionUtils.matchesInputSetPattern(pipelineId)) {
>       throw new InvalidRequestException("Pipeline identifier cannot be runtime input");
> ```

check if required?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54131)* status: 16 file(s) to review. 1 change requests. 6. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 252 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4_Mu75LdtUWUqmatF:-Ni4mSzT0luiB1rH4mNx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/contracts/openapi/v1/openapi.yaml#L252)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Patch api for pipeline entity and below also
</blockquote></details>

Done.
___
*[`pipeline-service/contracts/openapi/v1/openapi.yaml` line 2926 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4_RdA8LDmRa8UePAS:-Ni4maIK5ImAub_zYu7a:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/contracts/openapi/v1/openapi.yaml#L2926)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

data should be removed
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 43 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4a54L8mc8xmyOpp1C:-Ni4mgmA38_C-wmXxfmJ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L43)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add todo comment
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 92 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4b7g60bZsN3gI8zXC:-Ni4mmI7DmgYRJPDNAw8:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L92)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

rename this to oldEntityFromDB in old and this method
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4ZTRo7TjdKpkAeSeE:-Ni4mzci5dBedemqZYCP:b-blnmf6) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L137)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: check if its needs to be overloaded
</blockquote></details>

this is required because it is being called from old update APIs, where tags and description are not taken in the request
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java` line 148 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4ZRJYEyrYX65hYHS5:-Ni4q0w75s3tvFrIx6Bx:b-w8nkam) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java#L148)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

check if required?
</blockquote></details>

this is also called from old APIs in PipelineResource, where we haven't added NotNull annotations on identifier and name, so it is required

**Comment by shalini-agr** [comment]
trigger uts

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54131)* status: 16 file(s) to review. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java` line 91 at r2](https://reviewable.io/reviews/harness/harness-core/54131#-Ni4b5Xb-sXDZR_63UyK:-NiF6CCz1vXyoWrRcYXO:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/3b1a7fde0ba1bab1d77c55b515e44be183cb7a79/pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters/PMSPipelineFilterHelper.java#L91)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

validate if audit is coming correctly
</blockquote></details>

done

**Comment by shalini-agr** [comment]
trigger uts

**Review by ashishsanodia-harness — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54131#-:-NiIQ5c4E37b-Uqhpdww:bnfp4nl)* status: 15 file(s) to review.

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
