### PR TITLE
[feat]: [PIE-7738]: Add yaml validation on resolved templates and wit…

### PR DESCRIPTION
**Pull request by sahilhindwani-harness**
…hout <+input>

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## What is the issue?
Currently the reconciliation flow is removed from regular flows. This is affecting pipelines with templates as they are failing with weird errors during runtime. 
We need to come up with a way so that we can validate if the field marked as <+input> is required or not.

## What is the change?
The change is to parse the yaml and remove the <+input> fields and then validate the schema. This will ensure that only optional fields are marked as <+input> during the execution call.

## Impact?
This will impact every executions as schema will now be done on yaml with <+input> removed. 

# Testing? 
a) Manual -> 
- A pipeline with delay step having duration as input and not providing it during run -> Failed with the correct exception
- A pipeline using an old template which is not reconciled -> Failed with the proper schema message.

# 

- [ ] ReleaseNotes summary needed 

- [ ]  New Task Type
- [ ] Changes are backward compatible
- [ ] Added a new class which is added for kryoSerialisation
- [ ] New version of the delegate will receive old version task and process
- [ ] New version of the pipeline-service receives response for the old task will it be able to handle it successfully
- [ ] A change is made in delegate task which will be created in pipeline-services via grpc call to manager
- [ ] If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay?
- [ ] If the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay?
- [ ] Did you remove an enum
- [ ] Did you add an enum(That too at end of list)
- [ ] FeatureFlag Added/Removed

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3ZryEAIQoG4jPR8dp:-NM3ZryEAIQoG4jPR8dq:b5ic3gu) ([raw file](https://github.com/harness/harness-core/blob/783254af9728e38d8ee54ed58be0b1ad111a5a53/953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java#L36)):*
> ```Java
> @OwnedBy(PIPELINE)
> public class YamlUtilsTest extends CategoryTest {
>   private static String EXPECTED_YAML_WITHOUT_RUNTIME_INPUTS = "pipeline:\n"
> ```

can we add the yaml in yaml file in resource?
___
*[`970-ng-commons/src/main/java/io/harness/common/NGExpressionUtils.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3_5EC-vxg7XZOdCH4:-NM3_5EC-vxg7XZOdCH5:b-3im8u6) ([raw file](https://github.com/harness/harness-core/blob/783254af9728e38d8ee54ed58be0b1ad111a5a53/970-ng-commons/src/main/java/io/harness/common/NGExpressionUtils.java#L35)):*
> ```Java
>       Pattern.compile(EXPR_START_ESC + "input" + EXPR_END_ESC + ".*");
> 
>   private static final Pattern RawInputSetPattern =
> ```

why do we need this differently than current input set variable pattern? should we not remove the runtime having validator?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3_Ql34S40z6qXhZBE:-NM3_Ql34S40z6qXhZBF:b-lp245s) ([raw file](https://github.com/harness/harness-core/blob/b9c88960a2b633d1b702d17e083a745d3364cd58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L132)):*
> ```Java
>   public boolean validateYamlSchema(String accountId, String orgId, String projectId, String yaml) {
>     // Keeping pipeline yaml schema validation behind ff. If ff is disabled then schema validation will happen. Will
>     // remove after finding the root cause of invalid schema generation and fixing it.
> ```

why this is removed?

**Comment by sahilhindwani-harness** [comment]
*[`953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java` line 36 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3ZryEAIQoG4jPR8dp:-NM3aWCdAQ1yk3MKsKiE:bjjzelf) ([raw file](https://github.com/harness/harness-core/blob/783254af9728e38d8ee54ed58be0b1ad111a5a53/953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java#L36)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we add the yaml in yaml file in resource?
</blockquote></details>

Tried that but assertion is failing because of indentation.

**Comment by sahilhindwani-harness** [comment]
*[`970-ng-commons/src/main/java/io/harness/common/NGExpressionUtils.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3_5EC-vxg7XZOdCH4:-NM3a_CZA3sHf2TNgC_A:b-icrh4y) ([raw file](https://github.com/harness/harness-core/blob/783254af9728e38d8ee54ed58be0b1ad111a5a53/970-ng-commons/src/main/java/io/harness/common/NGExpressionUtils.java#L35)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why do we need this differently than current input set variable pattern? should we not remove the runtime having validator?
</blockquote></details>

The way that expression is written, it will match execution time input as well as default, therefore for now removing only once that we are sure will be <+input>

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3_Ql34S40z6qXhZBE:-NM3atjA35aXNkOYt_mB:b44vdcr) ([raw file](https://github.com/harness/harness-core/blob/b9c88960a2b633d1b702d17e083a745d3364cd58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L132)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

why this is removed?
</blockquote></details>

Sorry, was testing on local and committed by mistake. Will correct.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java` line 132 at r1](https://reviewable.io/reviews/harness/harness-core/42768#-NM3_Ql34S40z6qXhZBE:-NM3bCtN2qmr4L2aW20g:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/b9c88960a2b633d1b702d17e083a745d3364cd58/pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java#L132)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

Sorry, was testing on local and committed by mistake. Will correct.
</blockquote></details>

Done

**Review by prashantsharma04 — DISMISSED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42768)* status: :shipit: complete! ✓

**Comment by sahilhindwani-harness** [comment]
trigger messagecheck

**Pull request merged**
