### PR TITLE
feat: [PL-24264]: Fetch commit id for file operations in azure

### PR DESCRIPTION
**Pull request by goelsatyam2**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)

### CODE REVIEW

**Comment by mohitg0795** [comment]
*[product/ci/scm/file/file.go, line 491 at r1](https://reviewable.io/reviews/harness/harness-core/32287#-N-v_BK89dg3XTaKVlgr:-N-v_BK89dg3XTaKVlgs:b-p6j8h7) ([raw file](https://github.com/harness/harness-core/blob/5f9e60321f256e988da203c0baed92a66e48f344/product/ci/scm/file/file.go#L491)):*
> ```Go
> // getCommitIdByProvider returns the latest commit id of branch
> // if commit id is already set in request then it will return the same commit-id
> func getCommitIdByProvider(ctx context.Context, commitIdInRequest, slug, branch string, provider *pb.Provider, log *zap.SugaredLogger) (string, error) {
> ```

Method name sounds very generic to the operation its doing.

Can we simply create new method to fetch commit id for given slug and branch for all git providers? And implement only ADO in it for now. For others, we can return error that its not supported for now.

And then use this method at different places only if required.

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[product/ci/scm/file/file.go, line 491 at r1](https://reviewable.io/reviews/harness/harness-core/32287#-N-v_BK89dg3XTaKVlgr:-N-vssIWCwAxafaKLQDM:b-rmfxn5) ([raw file](https://github.com/harness/harness-core/blob/5f9e60321f256e988da203c0baed92a66e48f344/product/ci/scm/file/file.go#L491)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Method name sounds very generic to the operation its doing.

Can we simply create new method to fetch commit id for given slug and branch for all git providers? And implement only ADO in it for now. For others, we can return error that its not supported for now.

And then use this method at different places only if required. 
</blockquote></details>

We need a generic method to fetch the commit by a given provider. Otherwise switch case would be needed on the upper functions. 
It's making API calls for ADO and for other provider's return the commit that is present in the GRPC request.

**Comment by mohitg0795** [comment]
*[product/ci/scm/file/file.go, line 491 at r1](https://reviewable.io/reviews/harness/harness-core/32287#-N-v_BK89dg3XTaKVlgr:-N-vuGhQ6n0HUHaK3ukj:b8epcvk) ([raw file](https://github.com/harness/harness-core/blob/5f9e60321f256e988da203c0baed92a66e48f344/product/ci/scm/file/file.go#L491)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

We need a generic method to fetch the commit by a given provider. Otherwise switch case would be needed on the upper functions. 
It's making API calls for ADO and for other provider's return the commit that is present in the GRPC request. 
</blockquote></details>

Yes, but this method in itself doesn't make much sense as its calling a special case for ADO and isn't indicative of its exact behaviour.

As you mentioned, there should be a generic method to fetch commit id for given slug and branch. That method can be at best integrated in a helper method for our use-case.

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[product/ci/scm/file/file.go, line 491 at r1](https://reviewable.io/reviews/harness/harness-core/32287#-N-v_BK89dg3XTaKVlgr:-N-wAvL3DRe4ku79QT0r:b-pw8bza) ([raw file](https://github.com/harness/harness-core/blob/5f9e60321f256e988da203c0baed92a66e48f344/product/ci/scm/file/file.go#L491)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

Yes, but this method in itself doesn't make much sense as its calling a special case for ADO and isn't indicative of its exact behaviour.

As you mentioned, there should be a generic method to fetch commit id for given slug and branch. That method can be at best integrated in a helper method for our use-case.
</blockquote></details>

if we see this method from the file package perspective, it is generic enough for the file package use case.
If we want more generic then it's better to call git.GetLatestCommit.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[product/ci/scm/file/file.go, line 111 at r2](https://reviewable.io/reviews/harness/harness-core/32287#-N-wBOnd5oex6dpIErba:-N-wBOne3200A4AXL_RV:b-dufmkw) ([raw file](https://github.com/harness/harness-core/blob/572b092822b108167f421691fd2b3e6b514c8c43/product/ci/scm/file/file.go#L111)):*
> ```Go
> 		inputParams.BlobID = fileRequest.GetBlobId()
> 	default:
> 		inputParams.Sha, err = getCommitIdByProvider(ctx, fileRequest.GetCommitId(), fileRequest.GetSlug(), fileRequest.GetBranch(),
> ```

For every provider, will we be doing one more api call to get the commitId ? 
this commitId is not required by Github

**Comment by mohitg0795** [comment]
*[product/ci/scm/file/file.go, line 491 at r1](https://reviewable.io/reviews/harness/harness-core/32287#-N-v_BK89dg3XTaKVlgr:-N-wbkmr6SpmAh_R849n:bshlpiu) ([raw file](https://github.com/harness/harness-core/blob/5f9e60321f256e988da203c0baed92a66e48f344/product/ci/scm/file/file.go#L491)):*
<details><summary><i>Previously, goelsatyam2 (Satyam Goel) wrote…</i></summary><blockquote>

if we see this method from the file package perspective, it is generic enough for the file package use case.
If we want more generic then it's better to call git.GetLatestCommit.
</blockquote></details>

Discussed on call, looks good

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287#-:-N-wbsou1DkE3vK5o-ru:bnfp4nl)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Review by goelsatyam2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[product/ci/scm/file/file.go, line 111 at r2](https://reviewable.io/reviews/harness/harness-core/32287#-N-wBOnd5oex6dpIErba:-N-wbsaD76izTAKF-5rd:b-wlzh8s) ([raw file](https://github.com/harness/harness-core/blob/572b092822b108167f421691fd2b3e6b514c8c43/product/ci/scm/file/file.go#L111)):*
<details><summary><i>Previously, DeepakPatankar (Deepak Patankar) wrote…</i></summary><blockquote>

For every provider, will we be doing one more api call to get the commitId ? 
this commitId is not required by Github
</blockquote></details>

we will be doing API calls only for azure.

**Review by DeepakPatankar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: 2 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[product/ci/scm/file/file.go, line 169 at r3](https://reviewable.io/reviews/harness/harness-core/32287#-N-wc_agECq-1tCKZysQ:-N-wc_agECq-1tCKZysR:bj3babl) ([raw file](https://github.com/harness/harness-core/blob/b09b80262072a9809cf8fe78e690f0dca080f7f9/product/ci/scm/file/file.go#L169)):*
> ```Go
> 		inputParams.BlobID = fileRequest.GetBlobId()
> 	default:
> 		inputParams.Sha, err = getCommitIdIfEmptyInRequest(ctx, fileRequest.GetCommitId(), fileRequest.GetSlug(), fileRequest.GetBranch(),
> ```

Here we have changes for github also. Since we decided to do only for azure, we can remove this changes ?

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32287)* status: :shipit: complete! ✓

**Pull request merged**
