### PR TITLE
feat: [SRM-14593]: Restore SLI and Composite SLO Data

### PR DESCRIPTION
**Pull request by Varsha-lalwani**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/46683)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46683)* status: 41 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java` line 220 at r5](https://reviewable.io/reviews/harness/harness-core/46683#-NTs-ymN1_h_7_xxcgP-:-NTs-ymN1_h_7_xxcgP0:bihaivo) ([raw file](https://github.com/harness/harness-core/blob/cc132d57e59b461d127125c89b0d56539d7b9ce0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java#L220)):*
> ```Java
>     }
>     if (result.getStatus() == DataCollectionExecutionStatus.SUCCESS) {
>       if (dataCollectionTask instanceof SLIDataCollectionTask) {
> ```

Lets move this to datacollectiontaskservice with processDataCollectionSuccess processDataCollectionFailure
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/SLIDataCollectionTaskServiceImpl.java` line 115 at r5](https://reviewable.io/reviews/harness/harness-core/46683#-NTs0HkWEfj0CDImyDmy:-NTs0HkWEfj0CDImyDmz:b2nirr) ([raw file](https://github.com/harness/harness-core/blob/cc132d57e59b461d127125c89b0d56539d7b9ce0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/SLIDataCollectionTaskServiceImpl.java#L115)):*
> ```Java
>     log.info("Created data collection task {}", dataCollectionTask);
>   }
> ```

@Override



_Code quote:_
```Java
      SLIDataCollectionTask sliDataCollectionTask = (SLIDataCollectionTask) dataCollectionTask;
      if (sliDataCollectionTask.isRestore()) {
        entityUnavailabilityStatusesService.updateDCFailedToDCPassed(EntityType.SLO, serviceLevelIndicator.getUuid(),
            dataCollectionTask.getStartTime().getEpochSecond(), dataCollectionTask.getEndTime().getEpochSecond());
      }
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/impl/EntityUnavailabilityStatusesServiceImpl.java` line 165 at r5](https://reviewable.io/reviews/harness/harness-core/46683#-NTs0cC80-y2GEUl0PaU:-NTs0cC80-y2GEUl0PaV:b-wmu0wq) ([raw file](https://github.com/harness/harness-core/blob/cc132d57e59b461d127125c89b0d56539d7b9ce0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/downtime/services/impl/EntityUnavailabilityStatusesServiceImpl.java#L165)):*
> ```Java
> 
>   @Override
>   public void updateDCFailedToDCPassed(EntityType entityType, String entityId, long startTime, long endTime) {
> ```

Move from status X to Status Y



_Code quote:_
```Java
us status
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLORestoreMetricAnalysisStateExecutor.java` line 75 at r5](https://reviewable.io/reviews/harness/harness-core/46683#-NTs1k2UBK0bq9gLIxd3:-NTs1k2UBK0bq9gLIxd4:beu4pz3) ([raw file](https://github.com/harness/harness-core/blob/cc132d57e59b461d127125c89b0d56539d7b9ce0/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLORestoreMetricAnalysisStateExecutor.java#L75)):*
> ```Java
>         sloDetailsSLIRecordsAndSLIMissingDataType = sliRecordService.getSLODetailsSLIRecordsAndSLIMissingDataType(
>             compositeServiceLevelObjective.getServiceLevelObjectivesDetails(), startTime, endTime);
>     SLIEvaluationType evaluationType =
> ```

check if we can make intermidiatte abstract class.
___
*[`120-ng-manager/config.yml` line 274 at r1](https://reviewable.io/reviews/harness/harness-core/46683#-NTTwGsA49paRqNO7KkB:-NTTwGsA49paRqNO7KkC:b-81upoe) ([raw file](https://github.com/harness/harness-core/blob/7c1f1276eb1b8120b8508a6716b0840a1b7ac911/120-ng-manager/config.yml#L274)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
> ```

revert it
___
*[`260-delegate/config-delegate.yml` line 19 at r1](https://reviewable.io/reviews/harness/harness-core/46683#-NTTwE6KB8RVBtymTo6D:-NTTwE6KB8RVBtymTo6E:byj03xo) ([raw file](https://github.com/harness/harness-core/blob/7c1f1276eb1b8120b8508a6716b0840a1b7ac911/260-delegate/config-delegate.yml#L19)):*
> ```YAML
> clientToolsDownloadDisabled: false
> installClientToolsInBackground: true
> isLocalNgDelegate: true
> ```

revert it.
___
*[`srm-service/config/cv-nextgen-config.yml` line 157 at r1](https://reviewable.io/reviews/harness/harness-core/46683#-NTTwIVJ3P4aDQkVUurI:-NTTwIVJ3P4aDQkVUurJ:b-81upoe) ([raw file](https://github.com/harness/harness-core/blob/7c1f1276eb1b8120b8508a6716b0840a1b7ac911/srm-service/config/cv-nextgen-config.yml#L157)):*
> ```YAML
>   authority: localhost
> 
> shouldConfigureWithPMS: ${SHOULD_CONFIGURE_WITH_PMS:-true}
> ```

revert it

**Review by deepak-harness — DISMISSED** [review]
> Reviewed 7 of 26 files at r1, 23 of 34 files at r2, 1 of 2 files at r3, 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46683)* status: :shipit: complete! ✓

**Comment by Varsha-lalwani** [comment]
trigger ss

**Review by deepak-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/46683)* status: :shipit: complete! ✓

**Pull request merged**
