### PR TITLE
fix: [DEL-3347]: Renaming account secret to delegate token {Change 2/3}

### PR DESCRIPTION
**Pull request by gaurav-jain1**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/31003#-MxC93xs7tZYGiy2hzEj:-MxC93xs7tZYGiy2hzEk:bd5lwwx) ([raw file](https://github.com/harness/harness-core/blob/c86b5c0c57366936f475177ef906d775a9743809/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L58)):*
> ```Java
>     install(new MetricRegistryModule(new MetricRegistry()));
> 
>     String accountSecret = configuration.getAccountSecret();
> ```

we should move this to a method in Configuration class

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old. 36 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, line 58 at r1](https://reviewable.io/reviews/harness/harness-core/31003#-MxC93xs7tZYGiy2hzEj:-MxE4qMhDWg1qXv8HMCH:b5f4mp4) ([raw file](https://github.com/harness/harness-core/blob/c86b5c0c57366936f475177ef906d775a9743809/260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java#L58)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

we should move this to a method in Configuration class
</blockquote></details>

Yes, I'll rebase and republish the patchset.

**Review by arpit3107 — DISMISSED** [review]
> Reviewed 27 of 36 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by mdmilic — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old. 1. unresolved discussions. 

___
*[400-rest/src/main/resources/delegatetemplates/delegate-helm-values.yaml.ftl, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/31003#-MxdMcbu3t2Yzt9bMrJz:-MxdMcbu3t2Yzt9bMrK-:bban2pu) ([raw file](https://github.com/harness/harness-core/blob/4ca45249421b3dffa09017fb2dab27f914b61b38/400-rest/src/main/resources/delegatetemplates/delegate-helm-values.yaml.ftl#L17)):*
> ```FreeMarker
> 
> # Secret identifier associated with the account
> accountSecret: ${accountSecret}
> ```

I think this change means we need to release a new version of the delegate helm chart

**Comment by mdmilic** [comment]
Approved, but I believe tests in DelegateServiceTest should start failing. If they don't, run them manually just in case.

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 27 of 36 files at r1, 6 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old. 

___
*[400-rest/src/main/resources/delegatetemplates/delegate-helm-values.yaml.ftl, line 17 at r2](https://reviewable.io/reviews/harness/harness-core/31003#-MxdMcbu3t2Yzt9bMrJz:-MxhFpSACNnYduFAxcjT:b-hbfttc) ([raw file](https://github.com/harness/harness-core/blob/4ca45249421b3dffa09017fb2dab27f914b61b38/400-rest/src/main/resources/delegatetemplates/delegate-helm-values.yaml.ftl#L17)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

I think this change means we need to release a new version of the delegate helm chart
</blockquote></details>

Not sure about your comment exactly here, shouldn't delegate upgrade process will take care of this implicitly ?

**Review by abhinav-harness — DISMISSED** [review]
> Reviewed 16 of 36 files at r1, 26 of 26 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[260-delegate/container/scripts/delegate.sh, line 140 at r4](https://reviewable.io/reviews/harness/harness-core/31003#-MzqB_IR-aSqF7sR3oHa:-MzqB_IR-aSqF7sR3oHb:b6i7nd) ([raw file](https://github.com/harness/harness-core/blob/612d47f424c9ade598b2f1873b60835ad42656c9/260-delegate/container/scripts/delegate.sh#L140)):*
> ```Shell
>   echo "accountId: $ACCOUNT_ID" > config-delegate.yml
> fi
> test "$(tail -c 1 config-delegate.yml)" && `echo "" >> config-delegate.yml`
> ```

why do we need this line?

**Review by raghuAtWings — DISMISSED** [review]
> Reviewed 3 of 9 files at r2, 26 of 26 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old.

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: Some of the checks are too old. 

___
*[260-delegate/container/scripts/delegate.sh, line 140 at r4](https://reviewable.io/reviews/harness/harness-core/31003#-MzqB_IR-aSqF7sR3oHa:-MztMTgM-l1IcfXTarqW:b-dn3xhd) ([raw file](https://github.com/harness/harness-core/blob/612d47f424c9ade598b2f1873b60835ad42656c9/260-delegate/container/scripts/delegate.sh#L140)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why do we need this line?
</blockquote></details>

Not sure, doesn't look of any use to me.

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 15 of 36 files at r1, 4 of 26 files at r4, 24 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31003)* status: :shipit: complete! ✓

**Pull request merged**
