### PR TITLE
feat: [CDS-46761]: Added Time metrics for template api's

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Added log Time metrics for validate-template-inputs api call as part of improving user experience we want to identify where is the most time consumed for various api's like Pipeline Get Call.

## Checklist
- [ Yes ] I've documented the changes in the PR description.
- [ Yes ] I've tested this change either in PR or local environment.
- [ Yes ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/40285#-NH3ymDi8s4ohzsNngKg:-NH3ymDi8s4ohzsNngKh:b-lb48en) ([raw file](https://github.com/harness/harness-core/blob/49309eae05251dcb1eaa5d9bef9e9ba9af662f4e/120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java#L29)):*
> ```Java
>       String accountId, String orgId, String projectId, String yaml, String resolvedTemplatesYaml) {
>     log.info("[NGManager] Starting validateInputsForYaml to yaml in project {}, org {}, account {}", projectId, orgId,
>         accountId);
> ```

Lets use ```io.harness.NgAutoLogContext``` for logging here
You can check examples
try()

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: 6 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java` line 29 at r3](https://reviewable.io/reviews/harness/harness-core/40285#-NH3ymDi8s4ohzsNngKg:-NH4b9Kn58K947ZH9PtQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/49309eae05251dcb1eaa5d9bef9e9ba9af662f4e/120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java#L29)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Lets use ```io.harness.NgAutoLogContext``` for logging here
You can check examples
try()
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 235 at r4](https://reviewable.io/reviews/harness/harness-core/40285#-NH4bgn53pP4FvqVKVkd:-NH4bgn53pP4FvqVKVke:blolabw) ([raw file](https://github.com/harness/harness-core/blob/27f3b09b668c468f30e31d08fa9da7ebb2690ecf/840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java#L235)):*
> ```Java
>     TemplateEntityGetResponse templateEntityGetResponse = null;
>     try (AutoLogContext ignore1 =
>              new NgAutoLogContextForMethod(projectId, orgId, accountId, "validateTemplateInputs", OVERRIDE_ERROR);) {
> ```

should we say that the method is "validateTemplateInputs#getLinkedTemplateEntity ? because other time taking methods are being called after the logging

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: 6 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 235 at r4](https://reviewable.io/reviews/harness/harness-core/40285#-NH4bgn53pP4FvqVKVkd:-NH4ecTo-Kd0QMjsdoXy:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/27f3b09b668c468f30e31d08fa9da7ebb2690ecf/840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java#L235)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

should we say that the method is "validateTemplateInputs#getLinkedTemplateEntity ? because other time taking methods are being called after the logging 
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/NgAutoLogContextForMethod.java` line 28 at r5](https://reviewable.io/reviews/harness/harness-core/40285#-NH4wdnq0i4L7H2BBnoJ:-NH4wdnq0i4L7H2BBnoK:bm5kibu) ([raw file](https://github.com/harness/harness-core/blob/722d3d9a5df12c68dc18c5388383b67f5cafd36e/970-ng-commons/src/main/java/io/harness/NgAutoLogContextForMethod.java#L28)):*
> ```Java
>     nullSafeBuilder.putIfNotNull(ORG_KEY, orgIdentifier);
>     nullSafeBuilder.putIfNotNull(ACCOUNT_KEY, accountIdentifier);
>     nullSafeBuilder.putIfNotNull(METHOD_NAME, methodName);
> ```

we should define method name here itself, defining it in another class just introduces a dependency which is not needed

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 4 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: :shipit: complete! ✓

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: :shipit: complete! ✓

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/40285#-NH8ZEbXAinWpSzlM0xp:-NH8ZEbXAinWpSzlM0xq:b-6pikpq) ([raw file](https://github.com/harness/harness-core/blob/722d3d9a5df12c68dc18c5388383b67f5cafd36e/120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java#L38)):*
> ```Java
>       InputsValidationResponse inputsValidationResponse =
>           inputsValidationHelper.validateInputsForYaml(accountId, orgId, projectId, yaml, resolvedTemplatesYaml);
>       log.info("[NGManager] validateInputsForYaml took {}ms ", System.currentTimeMillis() - start);
> ```

i think we should log this line in finally so if even exception comes you will always have this line, same for others

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r4, 1 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java` line 38 at r5](https://reviewable.io/reviews/harness/harness-core/40285#-NH8ZEbXAinWpSzlM0xp:-NH8zZtg143nRJsDRPuw:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/722d3d9a5df12c68dc18c5388383b67f5cafd36e/120-ng-manager/src/main/java/io/harness/ng/core/refresh/service/EntityRefreshServiceImpl.java#L38)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

i think we should log this line in finally so if even exception comes you will always have this line, same for others
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 104 at r7](https://reviewable.io/reviews/harness/harness-core/40285#-NH8zvUH1ZVMgGKCMSCn:-NH8zvUI5f468jDr8OhK:bromyto) ([raw file](https://github.com/harness/harness-core/blob/594ffc514afab4e827ca0a51fcdedd7eecc3e71a/pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L104)):*
> ```Java
>         accountId, orgId, projectId, pipelineEntity.getYaml(), pipelineEntity);
>     if (refreshResponse != null && refreshResponse.isShouldRefreshYaml()) {
>       GitEntityInfo gitEntityInfo = GitAwareContextHelper.getGitRequestParamsInfo();
> ```

Why we removed this?

**Review by archit-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: 1 file(s) to review. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java` line 104 at r7](https://reviewable.io/reviews/harness/harness-core/40285#-NH8zvUH1ZVMgGKCMSCn:-NH9-2tN1OxggHP6kYm_:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/594ffc514afab4e827ca0a51fcdedd7eecc3e71a/pipeline-service/service/src/main/java/io/harness/pms/template/service/PipelineRefreshServiceImpl.java#L104)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Why we removed this?
</blockquote></details>

done

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40285)* status: :shipit: complete! ✓

**Pull request merged**
