### PR TITLE
feat: [cds-48133]: added generic utility function to validate child scope

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
added generic utility function to validate child scope and throwing valid error message

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41308)

### CODE REVIEW

**Comment by utkarshchoubey-harness** [comment]
trigger messagecheck

**Comment by utkarshchoubey-harness** [comment]
trigger ft1

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/41308#-NJ3gIBn9vDgWxbhpeIN:-NJ3gIBn9vDgWxbhpeIO:b-d7qrgp) ([raw file](https://github.com/harness/harness-core/blob/a2da4021d74569ad50fd3e69deb103278e5d32ac/970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java#L54)):*
> ```Java
>    * Project Scope -> Identifer
>    */
>   public void isEntityInAllowedScopes(
> ```

can this method be private ?

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/41308#-NJ3gYIR1U-u-FrEeIQq:-NJ3gYIR1U-u-FrEeIQr:byirjwh) ([raw file](https://github.com/harness/harness-core/blob/a2da4021d74569ad50fd3e69deb103278e5d32ac/970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java#L70)):*
> ```Java
>       parentEntityScope = 0;
>       parentScope = "account";
>     }
> ```

what about invalid combination for eg, accountId and projectId not empty ?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41308)* status: 2 file(s) to review. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java` line 54 at r2](https://reviewable.io/reviews/harness/harness-core/41308#-NJ3gIBn9vDgWxbhpeIN:-NJ4AHRN7xF5YCPuW31n:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2da4021d74569ad50fd3e69deb103278e5d32ac/970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java#L54)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

can this method be private ?
</blockquote></details>

Done.
___
*[`970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/41308#-NJ3gYIR1U-u-FrEeIQq:-NJ4AIu-7xYRPH_2dTWb:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a2da4021d74569ad50fd3e69deb103278e5d32ac/970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java#L70)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

what about invalid combination for eg, accountId and projectId not empty ?
</blockquote></details>

Done.

**Comment by yogesh-chauhan** [comment]
*[`970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java` line 70 at r2](https://reviewable.io/reviews/harness/harness-core/41308#-NJ3gYIR1U-u-FrEeIQq:-NJ4GPdk21i6k4BmOC2T:bqi0div) ([raw file](https://github.com/harness/harness-core/blob/a2da4021d74569ad50fd3e69deb103278e5d32ac/970-ng-commons/src/main/java/io/harness/utils/IdentifierRefHelper.java#L70)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if lets say user provides accountID and projectID, will we not set the scope to Account based on the switch case ?

**Pull request merged**
