### PR TITLE
feat: [SSCA-285]: add replace configs for ssca images in pipeline service

### PR DESCRIPTION
**Pull request by inderschera**
## Describe your changes
- add replace configs for ssca images in pipeline service

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/49902)

### CODE REVIEW

**Comment by inderschera** [comment]
trigger uts

**Comment by sahilhindwani-harness** [comment]
*[`dockerization/pipeline-service/scripts/replace_configs.sh` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/49902#-NZ5OeRl6BDK82l9m2wr:-NZ5OeRl6BDK82l9m2ws:b-6j8pss) ([raw file](https://github.com/harness/harness-core/blob/67dc2caffbb488db22633abc49f6f57ef0f66027/dockerization/pipeline-service/scripts/replace_configs.sh#L589)):*
> ```Shell
> replace_key_value featureFlagConfig.syncFeaturesToCF "$SYNC_FEATURES_TO_CF"
> 
> replace_key_value orchestrationStepConfig.containerStepConfig.pluginConfig.sscaOrchestrationConfig.image $SSCA_ORCHESTRATION_IMAGE
> ```

We can use this format for overriding: ```corePoolSize: ${PIPELINE_SETUP_USAGE_CREATION_EXECUTOR_POOL_CORE_SIZE:-1}```

in config.yml
then this change would not be requied.

**Review by inderschera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49902)* status: 3 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`dockerization/pipeline-service/scripts/replace_configs.sh` line 589 at r1](https://reviewable.io/reviews/harness/harness-core/49902#-NZ5OeRl6BDK82l9m2wr:-NZ5YhyB2vWABRLFvHFN:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/67dc2caffbb488db22633abc49f6f57ef0f66027/dockerization/pipeline-service/scripts/replace_configs.sh#L589)):*
<details><summary><i>Previously, sahilhindwani-harness (Sahil Hindwani) wrote…</i></summary><blockquote>

We can use this format for overriding: ```corePoolSize: ${PIPELINE_SETUP_USAGE_CREATION_EXECUTOR_POOL_CORE_SIZE:-1}```

in config.yml
then this change would not be requied.
</blockquote></details>

Done.

**Comment by inderschera** [comment]
trigger uts

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/49902)* status: 1. unresolved discussions.

**Pull request merged**
