### PR TITLE
feat: [SRM-10170]: Added ClusterId and support for Radar chart for live monitoring.

### PR DESCRIPTION
**Pull request by arpit-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32828)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32828)* status: 5 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataDTO.java` line 42 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1MyOE2EuKjaI7bH0uv:-N1MyOE2EuKjaI7bH0uw:b-xg19aq) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataDTO.java#L42)):*
> ```Java
>     Risk riskStatus;
>     List<AnalyzedLogDataDTO.FrequencyDTO> trend;
>     LogAnalysisResult.LogAnalysisTag tag;
> ```

let's keep this consistent with deployment and call it clusterType
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataDTO.java` line 56 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1MyjD47KGtWzpecwM0:-N1MyjD47KGtWzpecwM1:b-dn7ozl) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataDTO.java#L56)):*
> ```Java
>     int result = o.getLogData().getTag().compareTo(logData.getTag());
>     if (result == 0) {
>       result = Integer.valueOf(o.getLogData().getCount()).compareTo(Integer.valueOf(logData.getCount()));
> ```

We can replace this with Integer.compare(o.getLogData().getCount(), logData.getCount())
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java` line 117 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1Mytjt98rf0OUuzgLd:-N1Mytjt98rf0OUuzgLe:bu754wi) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java#L117)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @ApiOperation(value = "get all log cluster data for a time range", nickname = "getAllLogsClusterData")
> ```

please fix the nickname to more meaningful name and consistent with path.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java` line 122 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1Mx96nBuyfP8QIGnwp:-N1Mx96nBuyfP8QIGnwq:b-5jlzt) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java#L122)):*
> ```Java
>       @QueryParam("monitoredServiceIdentifier") String monitoredServiceIdentifier,
>       @BeanParam MonitoredServiceLogAnalysisFilter monitoredServiceLogAnalysisFilter) {
>     MonitoredServiceParams serviceEnvironmentParams = MonitoredServiceParams.builder()
> ```

monitoredServiceParams
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java` line 137 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1Mz9GmBdycz0G0NZS6:-N1Mz9GmBdycz0G0NZS7:bojn7eh) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java#L137)):*
> ```Java
>   @Timed
>   @ExceptionMetered
>   @ApiOperation(value = "get all log data for a time range", nickname = "getAllLogsData")
> ```

please fix the nickname



_Code quote:_
```Java
ogs-radar-chart-cluster
```
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1MxGR36ADKGHIxn8Yw:-N1MxGR36ADKGHIxn8Yx:b9jhm1s) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java#L149)):*
> ```Java
>                                                           .monitoredServiceIdentifier(monitoredServiceIdentifier)
>                                                           .build();
>     /*TimeRangeParams timeRangeParams = TimeRangeParams.builder()
> ```

PageParams can be BeanParam directly 
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java` line 154 at r2](https://reviewable.io/reviews/harness/harness-core/32828#-N1MxNoL8RvpGsA6n57r:-N1MxNoL8RvpGsA6n57s:bibonc1) ([raw file](https://github.com/harness/harness-core/blob/4505f8362117fa85801298e69980f57ec5014e68/300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java#L154)):*
> ```Java
>                                           .build();*/
>     PageParams pageParams = PageParams.builder().page(page).size(size).build();
>     /*LiveMonitoringLogAnalysisFilter liveMonitoringLogAnalysisFilter =
> ```

Why commented out code?

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32828#-:-N1Zduhl-was89-_JUZG:bnfp4nl)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java` line 172 at r3](https://reviewable.io/reviews/harness/harness-core/32828#-N1Zd5mL56pLAXewBY7_:-N1Zd5mL56pLAXewBY7a:b-pqz4e3) ([raw file](https://github.com/harness/harness-core/blob/fee864d2a2cd312e308a1e00866cdf1e68c008e2/300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java#L172)):*
> ```Java
>     String cvConfigId = generateUuid();
>     String errorTrackingCvConfigId = generateUuid();
>     Instant startTime = Instant.now().minus(10, ChronoUnit.MINUTES);
> ```

please use fixed time. Using Instant.now() can be flaky 
Use clock for getting current time.
Please check other tests also.
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java` line 178 at r3](https://reviewable.io/reviews/harness/harness-core/32828#-N1ZdfKA095PEGtlQ8SJ:-N1ZdfKA095PEGtlQ8SK:b-j4yjhj) ([raw file](https://github.com/harness/harness-core/blob/fee864d2a2cd312e308a1e00866cdf1e68c008e2/300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java#L178)):*
> ```Java
>     List<Long> labelList = Arrays.asList(1234l, 123455l, 12334l, 12345l);
>     List<LogAnalysisResult> resultList = buildLogAnalysisResults(cvConfigId, true, startTime, endTime, labelList);
>     when(mockCvConfigService.list(builderFactory.getContext().getMonitoredServiceParams()))
> ```

why do we need mockCVConfigService?
___
*[`300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java` line 273 at r3](https://reviewable.io/reviews/harness/harness-core/32828#-N1ZdkVq1MPCROcRhsjL:-N1ZdkVq1MPCROcRhsjM:bs4v1hc) ([raw file](https://github.com/harness/harness-core/blob/fee864d2a2cd312e308a1e00866cdf1e68c008e2/300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java#L273)):*
> ```Java
>         .thenReturn(Arrays.asList(createCvConfig(cvConfigId, serviceIdentifier),
>             createErrorTrackingCvConfig(errorTrackingCvConfigId, serviceIdentifier)));
>     when(mockLogAnalysisService.getAnalysisResults(anyString(), any(), any())).thenReturn(resultList);
> ```

let's discuss this. We should not be needing mocks.

**Comment by arpit-harness** [comment]
trigger compile

**Review by kjoshi12345 — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32828#-:-N1cfZmc5jzKbx1MAmXz:bnfp4nl)* status: :shipit: complete! ✓

**Pull request closed without merging**
