### PR TITLE
[fix]:[pie-6230]: updated the error experience for BB and BB server

### PR DESCRIPTION
**Pull request by adivishy1**
## Describe your changes
Enhanced the error experience by adding better hint and explanation messages for BB and BB server. Have tested the update operation via curls for BB and verified the error experience.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/42284)

### CODE REVIEW

**Comment by adivishy1** [comment]
trigger messagecheck

**Review by archit-harness — DISMISSED** [review]

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketUpdateFileScmApiErrorHandler.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/42284#-NLKFpGb-2WGBTzzzS6i:-NLKFpGb-2WGBTzzzS6j:b-o96ieu) ([raw file](https://github.com/harness/harness-core/blob/e7575c2a5cc0e978fb22bf1be6310d0709fa8b74/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketUpdateFileScmApiErrorHandler.java#L34)):*
> ```Java
>       "The requested file<FILEPATH> couldn't be updated in Bitbucket. ";
>   public static final String UPDATE_FILE_CONFLICT_ERROR_HINT =
>       "Please check the input commit id of the requested file<FILEPATH> or please check if there any changes in the file content. It should either match with current commit id of the file at head of the branch<BRANCH> in the given Bitbucket repository<REPO> or there has to be change in the file content.";
> ```

This is confusing @adivishy1. It should be written in points just like other use-cases or be written very clearly. Please check.

**Review by adivishy1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42284)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketUpdateFileScmApiErrorHandler.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/42284#-NLKFpGb-2WGBTzzzS6i:-NLKhsAp97-o9wwJvbcZ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/91de737e40e1f3ac04f0a8791afd5cb6e1ce2db9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucketcloud/BitbucketUpdateFileScmApiErrorHandler.java#L34)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

This is confusing @adivishy1. It should be written in points just like other use-cases or be written very clearly. Please check.
</blockquote></details>

Done.

**Review by mohitg0795 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/42284)* status: :shipit: complete! ✓

**Review by archit-harness — APPROVED** [review]

**Pull request merged**
