### PR TITLE
[feat]: [PL-25184]: Increment the scm version in delegate

### PR DESCRIPTION
**Pull request by DeepakPatankar**
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33521)

### CODE REVIEW

**Review by bhavya181 — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521)* status: 10 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — DISMISSED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521#-:-N2vBt6mD0qgjSXDWSS7:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521#-:-N2zsy-KDp1NSlxdMPUl:bnfp4nl)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by rathodmeetsatish — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521)* status: :shipit: complete! ✓

**Review by meenakshi-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521)* status: :shipit: complete! ✓

**Review by ujjawal-harness — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521#-:-N2zxVGz0TkSqKtScuMB:bnfp4nl)* status: :shipit: complete! ✓

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33521)* status: :shipit: complete! ✓

**Pull request merged**
