### PR TITLE
[fix]: [CDS-77291]: Fixing the interrupt marked as processed after dis-allowing one node start

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes

Issue: When there is an active interrupt present and it will not let any new node start, but then that interrupt is marked as PROCESSED_SUCCESSFULLY. And any node trying to start after this moment(when interrupt has diss-allowed one node start) will be started.
Because we invoke the `abortInterruptHandler.handleInterruptForNodeExecution(interrupt, nodeExecutionId);` for handling that node and since this flow is for handling abort for one nodeExecution, so it mark the interrupt as processed after handing that one nodeExecution.

In the below screen-shot, when the abort interrupt was triggered, both deployment stage steps were on sleep and they were starting their children after the interrupt.
So the interrupt did not let one stage stage and was marked processed_success. And the other deploy stage started and executed completely.

image

Change: Not marking the interrupt as PROCESSED while handling any new start node when there is some active interrupt resent.

Testing: 
Tested the abortAll interrupt when some nodes were being started after the interrupt. Now after the fix, all the nodes trying to start after interrupt are being aborted. See the below screen-shot.
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/51902)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51902)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Comment by sahilhindwani-harness** [comment]
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/MarkExpiredInterruptHandler.java` line 75 at r2](https://reviewable.io/reviews/harness/harness-core/51902#-NcViv-I2ohWK4LYE0dk:-NcViv-I2ohWK4LYE0dl:b-48zld3) ([raw file](https://github.com/harness/harness-core/blob/2687a06612b2d28563c75e07d0f3b787f54483c3/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/MarkExpiredInterruptHandler.java#L75)):*
> ```Java
>           nodeExecutionId, Status.DISCONTINUING, null, EnumSet.noneOf(Status.class));
>       if (nodeExecution == null) {
>         log.error("Failed to expire node with nodeExecutionId: {}", nodeExecutionId);
> ```

This and abort code can be merged. Can you please add a todo for this ?

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/51902)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
