### PR TITLE
fix: [CDS-42790]: add scoping to cluster list

### PR DESCRIPTION
**Pull request by GabeAboy**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37238)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37238)

**Comment by GabeAboy** [comment]
trigger messagecheck

**Comment by rohitk-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/37238#-NBKydYD6ImCqhEJmZIu:-NBKxadO0W7Aka_UWOTG:b1cqbio) ([raw file](https://github.com/harness/harness-core/blob/2815518542cd26f30d5d59e5ef267fc97b56c0bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java#L108)):*
> ```Java
>       case ORGANIZATION:
>         return ClusterResponse.builder()
>             .name(clusterFromGitops.get(clusterRef).getName())
> ```

shouldn't this be "org." like the `project` case?

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37238)* status: 0 of 1 approvals obtained.

**Comment by GabeAboy** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/37238#-NBKydYD6ImCqhEJmZIu:-NBL3SHF6vqU3vtR7FHs:b2bhhal) ([raw file](https://github.com/harness/harness-core/blob/2815518542cd26f30d5d59e5ef267fc97b56c0bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java#L108)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

shouldn't this be "org." like the `project` case?
</blockquote></details>

Org and Account level clusters from gitopsCluster collection will have the scope prepended to clusterRef. If you can confirm? From what I see this is true

**Comment by rohitk-h** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java` line 108 at r3](https://reviewable.io/reviews/harness/harness-core/37238#-NBKydYD6ImCqhEJmZIu:-NBL4abPCTc8XeUvXHoo:b-8mgd98) ([raw file](https://github.com/harness/harness-core/blob/2815518542cd26f30d5d59e5ef267fc97b56c0bc/127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/mappers/ClusterEntityMapper.java#L108)):*
<details><summary><i>Previously, GabeAboy (Gabriel ) wrote…</i></summary><blockquote>

Org and Account level clusters from gitopsCluster collection will have the scope prepended to clusterRef. If you can confirm? From what I see this is true
</blockquote></details>

yes, it would be, thanks.

**Review by rohitk-h — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37238)* status: :shipit: complete! ✓

**Comment by GabeAboy** [comment]
trigger ti0

**Review by rohitk-h — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37238)* status: :shipit: complete! ✓

**Pull request merged**
