### PR TITLE
feat: [PIE-6026]: Send child execution graph in parent execution graph

### PR DESCRIPTION
**Pull request by prashantsharma04**
## Have added execution metadata in lower graph. The child graph have been apended based on type of plan node in the parent graph. Lower graph will be appended based on the child stage node id
Testing: Tested in local and in pr env

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)

### CODE REVIEW

**Review by hextechpal — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 13 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/ExecutionGraphMapper.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFaKHM7B42ioAnEpDi:-NGFaKHM7B42ioAnEpDj:b7993to) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/ExecutionGraphMapper.java#L97)):*
> ```Java
> 
>   public ExecutionGraph toExecutionGraph(
>       OrchestrationGraphDTO orchestrationGraph, PipelineExecutionSummaryEntity summaryEntity) {
> ```

Can we pass getMetadataMap directly here?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 315 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFctdl7p7uFMqZ1dif:-NGFctdl7p7uFMqZ1dig:buvaltb) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L315)):*
> ```Java
>             renderFullBottomGraph, planExecutionId, executionSummaryEntity, entityGitDetails);
> 
>     return ResponseDTO.newResponse(executionDetailDTO);
> ```

we should move all details to some helper or service, and not keep in resource



_Code quote:_
```Java
    if (stageNodeId != null) {
      NodeExecution nodeExecution = null;
      try {
        nodeExecution = nodeExecutionService.getByPlanNodeUuid(stageNodeId, planExecutionId);
      } catch (InvalidRequestException ex) {
        log.info("NodeExecution is null for plan node: {} ", stageNodeId);
      }
      if (PipelineStageHelper.validatePipelineStageNode(nodeExecution)
          && isNotEmpty(nodeExecution.getExecutableResponses())) {
        String childExecutionId = nodeExecution.getExecutableResponses().get(0).getAsync().getCallbackIds(0);
        PmsStepParameters parameters = nodeExecution.getNode().getStepParameters();

        return getPipelineExecutionDetailDTOResponseDTOForPipelineStage(
            accountId, childStageNodeId, executionSummaryEntity, entityGitDetails, childExecutionId, parameters);
      }
    }

    PipelineExecutionDetailDTO executionDetailDTO =
        getPipelineExecutionDetailDTOResponseDTO(accountId, orgId, projectId, stageNodeId, stageNodeExecutionId,
            renderFullBottomGraph, planExecutionId, executionSummaryEntity, entityGitDetails);

    return ResponseDTO.newResponse(executionDetailDTO);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 349 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFcyVuELCZAmf-T-WD:-NGFcyVuELCZAmf-T-WE:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L349)):*
> ```Java
>     }
>     return ResponseDTO.newResponse(pipelineStageGraphBuilder.childGraph(childGraphBuilder.build()).build());
>   }
> ```

same as above



_Code quote:_
```Java
  private ResponseDTO<PipelineExecutionDetailDTO> getPipelineExecutionDetailDTOResponseDTOForPipelineStage(
      String accountId, String childStageNodeId, PipelineExecutionSummaryEntity executionSummaryEntity,
      EntityGitDetails entityGitDetails, String childExecutionId, PmsStepParameters parameters) {
    // if child stage node id is null, return only top graph of child and top graph of parent
    PipelineExecutionDetailDTOBuilder pipelineStageGraphBuilder = null;

    PipelineExecutionSummaryEntity executionSummaryEntityForChild =
        pmsExecutionService.getPipelineExecutionSummaryEntity(
            accountId, parameters.get("org").toString(), parameters.get("project").toString(), childExecutionId, false);

    EntityGitDetails entityGitDetailsForChild;
    if (executionSummaryEntity.getEntityGitDetails() == null) {
      entityGitDetailsForChild =
          pmsGitSyncHelper.getEntityGitDetailsFromBytes(executionSummaryEntityForChild.getGitSyncBranchContext());
    } else {
      entityGitDetailsForChild = executionSummaryEntityForChild.getEntityGitDetails();
    }

    ChildExecutionDetailDTOBuilder childGraphBuilder = ChildExecutionDetailDTO.builder().pipelineExecutionSummary(
        PipelineExecutionSummaryDtoMapper.toDto(executionSummaryEntityForChild, entityGitDetailsForChild));

    pipelineStageGraphBuilder = PipelineExecutionDetailDTO.builder().pipelineExecutionSummary(
        PipelineExecutionSummaryDtoMapper.toDto(executionSummaryEntity, entityGitDetails));

    // if child stage node id is not null, add bottom graph for child graph
    if (childStageNodeId != null) {
      childGraphBuilder.executionGraph(ExecutionGraphMapper.toExecutionGraph(
          pmsExecutionService.getOrchestrationGraph(childStageNodeId, childExecutionId, null),
          executionSummaryEntityForChild));
    }
    return ResponseDTO.newResponse(pipelineStageGraphBuilder.childGraph(childGraphBuilder.build()).build());
  }
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFd1QM01WiZ5UHPCLb:-NGFd1QM01WiZ5UHPCLc:b-55iefv) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L107)):*
> ```Java
>       // Wait notify is for Pipeline Chain Parent Node.
>       waitNotifyEngine.doneWith(pipelineExecutionSummaryUpdatedEntity.getPlanExecutionId(),
>           PipelineStageResponseData.builder()
> ```

Un commenting it out, has no impact in restrictions flow right?
take @sahilhindwani-harness to test out restrictions as well

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 2 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/ExecutionGraphMapper.java` line 97 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFaKHM7B42ioAnEpDi:-NGFtJbhD9_4P96GsIyk:b-8uav01) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/ExecutionGraphMapper.java#L97)):*
> pass getMetadataMap directly here?
We will have to create it in resource to pass metadata then
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 349 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFcyVuELCZAmf-T-WD:-NGFt_Pt0rNlqxCJKWpr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L349)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java` line 107 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFd1QM01WiZ5UHPCLb:-NGFtbM_45q6IyeGMS6p:b-cmjhg8) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers/PipelineStatusUpdateEventHandler.java#L107)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Un commenting it out, has no impact in restrictions flow right?
take @sahilhindwani-harness to test out restrictions as well
</blockquote></details>

Discussed this with @sahilhindwani-harness . we can remove this now.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 315 at r3](https://reviewable.io/reviews/harness/harness-core/39352#-NGFctdl7p7uFMqZ1dif:-NGFxdqs0_zqvcPRYA6G:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/b38424e73f2c917c47ee951a8a0b73bbdfd741d5/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L315)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

we should move all details to some helper or service, and not keep in resource
</blockquote></details>

done
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 297 at r4](https://reviewable.io/reviews/harness/harness-core/39352#-NGFxqsD7ur7qVQekQAP:-NGFxqsEBXhBROPSxSEf:b-3bkbu3) ([raw file](https://github.com/harness/harness-core/blob/2a69f43dd86e9dd3dd0a43a916fb7a8d63219ed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L297)):*
> ```Java
>       } catch (InvalidRequestException ex) {
>         log.info("NodeExecution is null for plan node: {} ", stageNodeId);
>       }
> ```

this is still not moved i guess



_Code quote:_
```Java
    if (stageNodeId != null) {
      NodeExecution nodeExecution = null;
      try {
        nodeExecution = nodeExecutionService.getByPlanNodeUuid(stageNodeId, planExecutionId);
      } catch (InvalidRequestException ex) {
        log.info("NodeExecution is null for plan node: {} ", stageNodeId);
      }
      if (PipelineStageHelper.validatePipelineStageNode(nodeExecution)
          && isNotEmpty(nodeExecution.getExecutableResponses())) {
        String childExecutionId = nodeExecution.getExecutableResponses().get(0).getAsync().getCallbackIds(0);
        PmsStepParameters parameters = nodeExecution.getNode().getStepParameters();

        return pipelineStageHelper.getPipelineExecutionDetailDTOResponseDTOForPipelineStage(
            accountId, childStageNodeId, executionSummaryEntity, entityGitDetails, childExecutionId, parameters);
      }
    }

    PipelineExecutionDetailDTO executionDetailDTO =
        getPipelineExecutionDetailDTOResponseDTO(accountId, orgId, projectId, stageNodeId, stageNodeExecutionId,
            renderFullBottomGraph, planExecutionId, executionSummaryEntity, entityGitDetails);

    return ResponseDTO.newResponse(executionDetailDTO);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 315 at r4](https://reviewable.io/reviews/harness/harness-core/39352#-NGFxuY09VTOqITserF6:-NGFxuY09VTOqITserF7:biltvev) ([raw file](https://github.com/harness/harness-core/blob/2a69f43dd86e9dd3dd0a43a916fb7a8d63219ed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L315)):*
> ```Java
>   }
> 
>   private PipelineExecutionDetailDTO getPipelineExecutionDetailDTOResponseDTO(String accountId, String orgId,
> ```

this function name is having dto and dto, and move to helper



_Code quote:_
```Java
getPipelineExecutionDetailDTOResponseDTO
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 4 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 297 at r4](https://reviewable.io/reviews/harness/harness-core/39352#-NGFxqsD7ur7qVQekQAP:-NGGHE4n7ucWcMQsrUEQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2a69f43dd86e9dd3dd0a43a916fb7a8d63219ed8/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L297)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

this is still not moved i guess
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 4 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGsenN35brUKC8o2rU:-NGGsenN35brUKC8o2rV:b-cfp4nu) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L147)):*
> ```Java
>       nodeExecution = nodeExecutionService.getByPlanNodeUuid(stageNodeId, planExecutionId);
>     } catch (InvalidRequestException ex) {
>       log.info("NodeExecution is null for plan node: {} ", stageNodeId);
> ```

info -> error
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 152 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGsz1oCqzEm4D-CEje:-NGGsz1oCqzEm4D-CEjf:b46vz0x) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L152)):*
> ```Java
> 
>     if (validateGraphToGenerate(nodeExecution)) {
>       String childExecutionId = nodeExecution.getExecutableResponses().get(0).getAsync().getCallbackIds(0);
> ```

current method is becoming big, split into multiple methods to follow single responsibility principle



_Code quote:_
```Java
    if (validateGraphToGenerate(nodeExecution)) {
      String childExecutionId = nodeExecution.getExecutableResponses().get(0).getAsync().getCallbackIds(0);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 161 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGspQf4HmiMQMGAkK8:-NGGspQf4HmiMQMGAkK9:b-hyb226) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L161)):*
> ```Java
>       accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, orgId, projectId),
>           Resource.of("PIPELINE", executionSummaryEntity.getPipelineIdentifier()),
>           PipelineRbacPermissions.PIPELINE_VIEW);
> ```

Should we check view permissions? as view is basic permission? Checked with product?



_Code quote:_
```Java
      // check child pipeline view permission
      accessControlClient.checkForAccessOrThrow(ResourceScope.of(accountId, orgId, projectId),
          Resource.of("PIPELINE", executionSummaryEntity.getPipelineIdentifier()),
          PipelineRbacPermissions.PIPELINE_VIEW);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGt8bR8-CMN06xU8Hg:-NGGt8bR8-CMN06xU8Hh:b-uahvob) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L187)):*
> ```Java
>             executionSummaryEntityForChild));
>       }
>       return ResponseDTO.newResponse(pipelineStageGraphBuilder.childGraph(childGraphBuilder.build()).build());
> ```

Split into single responsible methods



_Code quote:_
```Java
      EntityGitDetails entityGitDetailsForChild;
      if (executionSummaryEntity.getEntityGitDetails() == null) {
        entityGitDetailsForChild =
            pmsGitSyncHelper.getEntityGitDetailsFromBytes(executionSummaryEntityForChild.getGitSyncBranchContext());
      } else {
        entityGitDetailsForChild = executionSummaryEntityForChild.getEntityGitDetails();
      }

      ChildExecutionDetailDTOBuilder childGraphBuilder = ChildExecutionDetailDTO.builder().pipelineExecutionSummary(
          PipelineExecutionSummaryDtoMapper.toDto(executionSummaryEntityForChild, entityGitDetailsForChild));

      PipelineExecutionDetailDTOBuilder pipelineStageGraphBuilder =
          PipelineExecutionDetailDTO.builder().pipelineExecutionSummary(
              PipelineExecutionSummaryDtoMapper.toDto(executionSummaryEntity, entityGitDetails));

      // if child stage node id is not null, add bottom graph for child execution
      if (childStageNodeId != null) {
        childGraphBuilder.executionGraph(ExecutionGraphMapper.toExecutionGraph(
            pmsExecutionService.getOrchestrationGraph(childStageNodeId, childExecutionId, null),
            executionSummaryEntityForChild));
      }
      return ResponseDTO.newResponse(pipelineStageGraphBuilder.childGraph(childGraphBuilder.build()).build());
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtXHZBQiuaenKQiJ6:-NGGtXHZBQiuaenKQiJ7:b-65hxco) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L286)):*
> ```Java
>     }
> 
>     if (stageNodeId != null) {
> ```

why the logic of stageNodeId null then response is different handling is in resource layer?



_Code quote:_
```Java
if (stageNodeId != null) {
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 290 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtQIB4WNaZHYlaqRX:-NGGtQIB4WNaZHYlaqRY:b-3yw203) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L290)):*
> ```Java
>       ResponseDTO<PipelineExecutionDetailDTO> responseDTO = pipelineStageHelper.getResponseDTO(
>           accountId, childStageNodeId, executionSummaryEntity, entityGitDetails, stageNodeId, planExecutionId);
>       if (responseDTO != null) {
> ```

if null then you will return nothing?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 301 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtlnx2EQPO074FRdt:-NGGtlnx2EQPO074FRdu:b1vg7kw) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L301)):*
> ```Java
>   }
> 
>   private PipelineExecutionDetailDTO getResponseDTO(String accountId, String orgId, String projectId,
> ```

Such helper methods move to resource helper class, if not exists create one

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 4 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 286 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtXHZBQiuaenKQiJ6:-NGGuAS_4DmaSmBPKMih:bfj0k57) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L286)):*
> why the logic of stageNodeId null then response is different handling is in resource layer?
Stage node id is not null when user clicks on any stage. If stage node id is not null then we need to fetch its node execution and check if its of type Pipeline Stage. If yes, return the top graph of child pipeline. If childStageNode id is not null then return the lower graph of child pipeline also
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 290 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtQIB4WNaZHYlaqRX:-NGGurHq20UwL-V6eHo0:b86s6f1) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L290)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

if null then you will return nothing?
</blockquote></details>

Yes, we do not even add child graph in that case. It means the stage is not of type Pipeline stage

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 5 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java` line 301 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGtlnx2EQPO074FRdt:-NGH--Yq2p6WRHZq6Yqc:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java#L301)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Such helper methods move to resource helper class, if not exists create one
</blockquote></details>

Done.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 5 file(s) to review. 1 change requests. 8. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 147 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGsenN35brUKC8o2rU:-NGKoANpB_hxTvWSMH5E:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L147)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

info -> error
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 161 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGspQf4HmiMQMGAkK8:-NGKoHID6e24jab9UVKT:b-eoplp2) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L161)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should we check view permissions? as view is basic permission? Checked with product?
</blockquote></details>

This is what we are checking for normal graph executions.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 187 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGt8bR8-CMN06xU8Hg:-NGKoNqP66QjXimbz_pY:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L187)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Split into single responsible methods
</blockquote></details>

Done.

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 7 file(s) to review. 1 change requests. 7. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java` line 152 at r5](https://reviewable.io/reviews/harness/harness-core/39352#-NGGsz1oCqzEm4D-CEje:-NHNpw37B0HsZysWEXjE:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/ecf4d81e9b1773328872fd63a1ab3732bd6db56c/pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/helper/PipelineStageHelper.java#L152)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

current method is becoming big, split into multiple methods to follow single responsibility principle
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r8, 2 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 516 at r11](https://reviewable.io/reviews/harness/harness-core/39352#-NHSiaUo601FgRveuRrT:-NHSiaUo601FgRveuRrU:b21p8lp) ([raw file](https://github.com/harness/harness-core/blob/efb68658b60c118f9531c8931780503a40e9fd77/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L516)):*
> ```Java
> 
>     if (EmptyPredicate.isEmpty(stageNodeId) && (renderFullBottomGraph == null || !renderFullBottomGraph)) {
>       pmsExecutionService.sendGraphUpdateEvent(executionSummaryEntity);
> ```

Did we do the same earlier here?



_Code quote:_
```Java
pmsExecutionService.sendGraphUpdateEvent(executionSummaryEntity);
```
___
*[`pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java` line 530 at r11](https://reviewable.io/reviews/harness/harness-core/39352#-NHSijFdAnZ2aXo1iZgS:-NHSijFeBniJNHhcan4n:b51w7l0) ([raw file](https://github.com/harness/harness-core/blob/efb68658b60c118f9531c8931780503a40e9fd77/pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java#L530)):*
> ```Java
>   }
> 
>   private NodeExecution getNodeExecution(String stageNodeId, String planExecutionId) {
> ```

Why are we handling null here? i mean why cant we throw exception if thrown from nodeExecutionService?

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: 8 file(s) to review. 1 of 2 approvals obtained.

**Review by brijeshdhakar — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 7 of 10 files at r2, 2 of 4 files at r5, 3 of 5 files at r8, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39352)* status: :shipit: complete! ✓

**Pull request merged**
