### PR TITLE
[feat]: [PL-24130]: Add Support for AccountIdentifier in NG API Key Token

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Added Support for AccountIdentifier in NG API Key Token

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31931)

### CODE REVIEW

**Comment by pbarapatre10** [comment]
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java, line 109 at r1](https://reviewable.io/reviews/harness/harness-core/31931#-N-SAfS6C-lUp1wGbFt5:-N-SAfS6C-lUp1wGbFt6:b-52l96v) ([raw file](https://github.com/harness/harness-core/blob/fa43b955092e2d5e3542aa63bb77dcf0f441758a/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L109)):*
> ```Java
>       TokenInfoDTO tokenInfo =
>           TokenInfoDTO.builder().accountId(newToken.getAccountIdentifier()).tokenId(newToken.getUuid()).build();
>       return token.getApiKeyType().getValue() + deliminator + tokenInfo.getAccountId() + deliminator
> ```

why can't we use the `TokenDTO` itself here? it has "accountIdentifier" in it. 
Can be changed to something like ?



_Code snippet:_
```Java
token.getApiKeyType().getValue() + deliminator + token.getAccountIdentifier() + deliminator + newToken.getUuid() + deliminator + randomString;
```

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31931)* status: 5 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java, line 109 at r1](https://reviewable.io/reviews/harness/harness-core/31931#-N-SAfS6C-lUp1wGbFt5:-N-X7NML20oG2tMfwAWL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/fa43b955092e2d5e3542aa63bb77dcf0f441758a/120-ng-manager/src/main/java/io/harness/ng/core/api/impl/TokenServiceImpl.java#L109)):*
<details><summary><i>Previously, pbarapatre10 (Prateek Barapatre) wrote…</i></summary><blockquote>

why can't we use the `TokenDTO` itself here? it has "accountIdentifier" in it. 
Can be changed to something like ?
</blockquote></details>

Done.

**Review by piyush-harness — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31931)* status: 5 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ashishsanodia-harness — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger DeepSource: Java

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31931)* status: :shipit: complete! ✓

**Pull request merged**
