### PR TITLE
[fix]: [DEL-3859]: move HttpTask and GitFetchFilesTask to 930-delegat…

### PR DESCRIPTION
**Pull request by raghuAtWings**
…e-tasks

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32414)

### CODE REVIEW

**Review by puneetsar — DISMISSED** [review]
> Reviewed 61 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32414)* status: :shipit: complete! ✓

___
*[930-delegate-tasks/src/main/java/software/wings/service/impl/ContainerServiceParams.java, line 31 at r1](https://reviewable.io/reviews/harness/harness-core/32414#-N0H9bK65eL3Jh9B2CTk:-N0H9bK65eL3Jh9B2CTl:b36z22i) ([raw file](https://github.com/harness/harness-core/blob/49993bb8d76e7e7378978370c679a7e76700ffa0/930-delegate-tasks/src/main/java/software/wings/service/impl/ContainerServiceParams.java#L31)):*
> ```Java
> import software.wings.beans.RancherConfig;
> import software.wings.beans.SettingAttribute;
> import software.wings.delegatetasks.utils.CapablityUtility;
> ```

Nit: typo in spelling of Capab[i]lity



_Code quote:_
```Java
CapablityUtility
```

**Review by puneetsar — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 12 files at r2, 12 of 22 files at r3, 4 of 11 files at r4, 14 of 14 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32414#-:-N0IPN_R-v4MyLxaxKBi:bnfp4nl)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 35 of 61 files at r1, 1 of 12 files at r2, 3 of 22 files at r3, 1 of 11 files at r4, 4 of 14 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32414)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32414)* status: :shipit: complete! ✓

**Pull request merged**
