### PR TITLE
fix: [CDS-36236]: Fix SwapSlot verifier for AzureWebApps

### PR DESCRIPTION
**Pull request by jelenaHarness**
`EventData` payload has been changed, for reference see activity logs: https://portal.azure.com/#@harness.io/resource/subscriptions/12d2db62-5aa9-471d-84bb-faa489b3e319/resourceGroups/devappserviceresourcegroup/providers/Microsoft.Web/sites/jelena-test/slots/stage/eventlogs

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32372)

### CODE REVIEW

**Comment by jelenaHarness** [comment]
trigger messagecheck

**Review by ivan-83 — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32372#-:-N0A72IRD-GlIvqTHDcV:bnfp4nl)* status: :shipit: complete! ✓

___
*[260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java, line 89 at r2](https://reviewable.io/reviews/harness/harness-core/32372#-N0A6PJm1KOuVKH1V-6a:-N0A6PJm1KOuVKH1V-6b:b-elilll) ([raw file](https://github.com/harness/harness-core/blob/8936026a533a4e8d6792c6affa725446125d484b/260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java#L89)):*
> ```Java
>     START_SLOT_WARM_UP("Microsoft.Web/sites/slots/StartSlotWarmup/action"),
>     END_SLOT_WARM_UP("Microsoft.Web/sites/slots/EndSlotWarmup/action"),
>     SLOT_SWAP_ACTION("Microsoft.Web/sites/slots/slotsswap/action");
> ```

Minor - just make sure that we will get this action from different Azure accounts/platforms/versions. I am just wondering why they changed the event name. Is there some release notes, or? Maybe we could post public question to MS.

**Comment by anilchowdhury-harness** [comment]
Let not merge this change for now. We need more discussion on this. I am able to run today in my local without any issue. Not sure what changed

**Review by anilchowdhury-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32372)* status: 4 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java, line 70 at r3](https://reviewable.io/reviews/harness/harness-core/32372#-N0FU9rACoLcw4O8vIUe:-N0FU9rACoLcw4O8vIUf:bexfk3c) ([raw file](https://github.com/harness/harness-core/blob/a5bc774720a0ab7bb9ed74cfde549cfe2e1ee2eb/260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java#L70)):*
> ```Java
>       // previousHighestAction to preserve the order of events
>       if (!seenBefore.contains(currentEvent) && SwapSlotAction.shouldLog(currentEvent.action)
>           && SwapSlotAction.compare(currentEvent.action, previousHighestAction)) {
> ```

!seenBefore.contains(currentEvent)    || 
(SwapSlotAction.shouldLog(currentEvent.action)  && SwapSlotAction.compare(currentEvent.action, previousHighestAction))

We should have || between this two conditions
It could be possible the swap operation can stay at the same event for long time. We should log it so as to give better user experience else there could be very large gap when user see the message on UI. This might give wrong sense as nothing is happening

**Review by jelenaHarness — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32372)* status: 4 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java, line 70 at r3](https://reviewable.io/reviews/harness/harness-core/32372#-N0FU9rACoLcw4O8vIUe:-N0GclgbCICHWcPXGqhh:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/a5bc774720a0ab7bb9ed74cfde549cfe2e1ee2eb/260-delegate/src/main/java/software/wings/delegatetasks/azure/appservice/deployment/verifier/SwapSlotStatusVerifier.java#L70)):*
<details><summary><i>Previously, anilchowdhury-harness (Anil Chowdhury) wrote…</i></summary><blockquote>

!seenBefore.contains(currentEvent)    || 
(SwapSlotAction.shouldLog(currentEvent.action)  && SwapSlotAction.compare(currentEvent.action, previousHighestAction))

We should have || between this two conditions
It could be possible the swap operation can stay at the same event for long time. We should log it so as to give better user experience else there could be very large gap when user see the message on UI. This might give wrong sense as nothing is happening

</blockquote></details>

Done.

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32372#-:-N0_v6C7AG7iszWalwMQ:bnfp4nl)* status: Some of the checks are too old. 1 file(s) to review. 1 change requests. 1. unresolved discussions.

**Pull request merged**
