### PR TITLE
[feat]: [CDS-40078]: support jenkins artifact in copy artifact step

### PR DESCRIPTION
**Pull request by vladimir-peric**
## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* Vulnerability 1 Vulnerabilities 
 * Code issue 7 Code issues 
* Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36433)

**Comment by vladimir-peric** [comment]
trigger codebasehash

**Comment by vladimir-peric** [comment]
trigger ti4

**Review by ivan-83 — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433#-:-N9f2ROnAut3EOwkmiOA:bnfp4nl)* status: :shipit: complete! ✓

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 363 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f-INdE6P1VO7SSpCC:-N9f-INdE6P1VO7SSpCD:b-hjqi6u) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L363)):*
> ```Java
>   }
> 
>   public SshWinRmArtifactDelegateConfig getArtifactDelegateConfigConfig(
> ```

There is a new SshWinRmArtifactHelper class where this logic should be placed. I see you already implement that logic there pls remove this method here. 
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/JenkinsArtifactCommandUnitHandler.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f0NlwAGJzsQuMb8-I:-N9f0NlwAGJzsQuMb8-J:b-nnf8h7) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/JenkinsArtifactCommandUnitHandler.java#L93)):*
> ```Java
> 
>   @Override
>   public Long getArtifactSize(SshExecutorFactoryContext context, LogCallback logCallback) {
> ```

I feel that this method should be placed in a common place to be reusable by other artifact delegate config types or method already exists and needs to be consumed.
___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f21uZEPPnqLMGzKDu:-N9f21uZEPPnqLMGzKDv:bpbu2kp) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L147)):*
> ```Java
>           copyCommandUnit.getDestinationPath(), artifactPathOnTarget, session, outputWriter, errorWriter);
> 
>       String command = getDownloadJenkinsArtifactCommand(
> ```

qq, is this getDownloadJenkinsArtifactCommand method only intended for WinRm or for both(SSH/WinRm)?

**Comment by vladimir-peric** [comment]
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java` line 147 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f21uZEPPnqLMGzKDu:-N9f3gCe1OGuDqmvK6gE:b8esrj1) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/FileBasedWinRmExecutorNG.java#L147)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

qq, is this getDownloadJenkinsArtifactCommand method only intended for WinRm or for both(SSH/WinRm)? 
</blockquote></details>

Only for WinRm.

**Comment by vladimir-peric** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java` line 363 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f-INdE6P1VO7SSpCC:-N9f8Fb1AtlpI7P5k_Z7:b-li345k) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/127-cd-nextgen-entities/src/main/java/io/harness/cdng/ssh/SshEntityHelper.java#L363)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

There is a new SshWinRmArtifactHelper class where this logic should be placed. I see you already implement that logic there pls remove this method here. 
</blockquote></details>

yes, used that one, I think I forgot to remove this, thx

**Review by vladimir-peric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)* status: 1 file(s) to review. 3. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/JenkinsArtifactCommandUnitHandler.java` line 93 at r1](https://reviewable.io/reviews/harness/harness-core/36433#-N9f0NlwAGJzsQuMb8-I:-N9fUq0q0J3Y5LJ9Avnn:bqsex3h) ([raw file](https://github.com/harness/harness-core/blob/a5838b01eaa43438c8ff48dddde0c9da38375cba/930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/ssh/JenkinsArtifactCommandUnitHandler.java#L93)):*
<details><summary><i>Previously, ivan-83 (Ivan Mijailovic) wrote…</i></summary><blockquote>

I feel that this method should be placed in a common place to be reusable by other artifact delegate config types or method already exists and needs to be consumed.
</blockquote></details>

This class needs to override this method, and is pretty much specific for the handler. I wouldn't put this logic anywhere else, for now. In case of need we can refactor.

**Review by mdmilic — DISMISSED** [review]
Approve delegate change

> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433#-:-N9fWXOe1DH7OB4a0o4g:bawykz)* status: 1 file(s) to review. 3. unresolved discussions.

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)* status: :shipit: complete! ✓

**Comment by vladimir-peric** [comment]
trigger codebasehash

**Comment by vladimir-peric** [comment]
trigger codebasehash

**Review by arpit3107 — APPROVED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
Looks good. The task under consideration here is a new task, not being used in production right now. It is under development.

**Review by yogesh-chauhan — APPROVED** [review]

**Comment by vladimir-peric** [comment]
trigger codebasehash

**Review by ivan-83 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36433)* status: :shipit: complete! ✓

**Pull request merged**
