### PR TITLE
feat: [PL-26927]: Added access control permissions for settings

### PR DESCRIPTION
**Pull request by tiwaritejas**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35657)

### CODE REVIEW

**Review by nishantsaini20 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35657)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Review by gupta-utkarsh — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35657)* status: 1 change requests. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1083 at r1](https://reviewable.io/reviews/harness/harness-core/35657#-N7dJ3Dv2dVPtVvoQ-X3:-N7dJ3Dv2dVPtVvoQ-X4:b-vamfq3) ([raw file](https://github.com/harness/harness-core/blob/932fcad19e7747ef32cea8339adc648dfada637a/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1083)):*
> ```YAML
>     includeInAllRoles: false
>     allowedScopeLevels:
>       - account
> ```

Does the setting exist at all the levels or only account level?

**Review by tiwaritejas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35657)* status: 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml` line 1083 at r1](https://reviewable.io/reviews/harness/harness-core/35657#-N7dJ3Dv2dVPtVvoQ-X3:-N7dKJ9P6ua0jDgdc8B_:bjgi1j) ([raw file](https://github.com/harness/harness-core/blob/932fcad19e7747ef32cea8339adc648dfada637a/access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml#L1083)):*
<details><summary><i>Previously, gupta-utkarsh (Utkarsh Gupta) wrote…</i></summary><blockquote>

Does the setting exist at all the levels or only account level?
</blockquote></details>

It exists at all scopes

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35657#-:-N7kdQiD3Ukm6J6H3kuZ:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
