### PR TITLE
feat: [DEL-3520]: delegate listing apis

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34637)

### CODE REVIEW

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java` line 730 at r1](https://reviewable.io/reviews/harness/harness-core/34637#-N6M4EaE6MzQVhcAHnH0:-N6M4EaE6MzQVhcAHnH1:bdmw45y) ([raw file](https://github.com/harness/harness-core/blob/c1ba76fd1b3bf563f45f373c7ef61282574b694e/420-delegate-service/src/main/java/io/harness/service/impl/DelegateSetupServiceImpl.java#L730)):*
> ```Java
> 
>   @Override
>   public List<DelegateGroupDTO> listDelegateGroupsHavingTags(
> ```

unit tests for these

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34637)* status: Some of the checks are too old.

**Review by AnupamIO — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34637)* status: Some of the checks are too old.

**Review by Vbhatia20 — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34637)* status: :shipit: complete! ✓

**Pull request merged**
