### PR TITLE
feat: [CDS-68683]: Force delete flow must set isLastUpdatedTemplate 

### PR DESCRIPTION
**Pull request by rohitk-h**
for another template.

## Describe your changes
- Templates list page only lists templates when one template has `isLastUpdatedTemplate` set to true. 
- When multiple referenced templates are deleted, the code logic leads to all the templates versions having `isLastUpdatedTemplate` set to false. This leads to no templates visible on UI even though they do exist. 
- The code change is to mark another version of template's `isLastUpdatedTemplate` set to true to avoid no templates visible on UI. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/47589)

### CODE REVIEW

**Comment by rohitk-h** [comment]
trigger messagecheck

**Comment by rohitk-h** [comment]
There is no unit test added since this behavior must be captured using automation tests. Tagged Hemanth in Jira for helping add automation tests.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47589)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 631 at r1](https://reviewable.io/reviews/harness/harness-core/47589#-NV2j6wQ0-0rNeSKes0X:-NV2j6wQ0-0rNeSKes0Y:b-wfm962) ([raw file](https://github.com/harness/harness-core/blob/c68ba714725cf54c7a103c90c2e588e8ecdf67a5/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L631)):*
> ```Java
>         deleteSingleTemplateHelper(accountId, orgIdentifier, projectIdentifier, templateEntity.getIdentifier(),
>             templateEntity, version, canDeleteStableTemplate, comments, forceDelete);
>         if (!canDeleteStableTemplate && lastUpdatedTemplateDeleted) {
> ```

instead of moving instead for loop, as it will lead to more updates, can we catch for loop exception and handle inside exception?

**Comment by rohitk-h** [comment]
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 631 at r1](https://reviewable.io/reviews/harness/harness-core/47589#-NV2j6wQ0-0rNeSKes0X:-NV6ME-u2em05CdG6jgi:buw1r8a) ([raw file](https://github.com/harness/harness-core/blob/c68ba714725cf54c7a103c90c2e588e8ecdf67a5/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L631)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

instead of moving instead for loop, as it will lead to more updates, can we catch for loop exception and handle inside exception?
</blockquote></details>

Catching the `ReferencedEntityException` exception and updating template will work. However, in case user doesn't decide to force delete the template then we would have made an update to stable template. What are the implications then?  
Below is what I cam thinking as per your suggestion. 



_Code snippet:_
```Java
try (TemplateGitSyncBranchContextGuard ignored = templateServiceHelper.getTemplateGitContextForGivenTemplate(
               templateEntity, GitContextHelper.getGitEntityInfo(),
               format("Deleting template with identifier [%s] and versionLabel [%s].", templateEntity.getIdentifier(),
                   templateEntity.getVersionLabel()))) {
        if (templateEntity.isLastUpdatedTemplate()) {
          lastUpdatedTemplateDeleted = true;
        }
        deleteSingleTemplateHelper(accountId, orgIdentifier, projectIdentifier, templateEntity.getIdentifier(),
            templateEntity, version, canDeleteStableTemplate, comments, forceDelete);
      } catch (ReferencedEntityException e){
        if (!canDeleteStableTemplate && lastUpdatedTemplateDeleted) {
          makeGivenTemplateLastUpdatedTemplateTrue(stableTemplate);
        }
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/47589)* status: 1 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java` line 631 at r1](https://reviewable.io/reviews/harness/harness-core/47589#-NV2j6wQ0-0rNeSKes0X:-NVAEApX6OMA4wYYtWPb:b-j6ff21) ([raw file](https://github.com/harness/harness-core/blob/c68ba714725cf54c7a103c90c2e588e8ecdf67a5/840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java#L631)):*
<details><summary><i>Previously, rohitk-h (Rohit Karelia) wrote…</i></summary><blockquote>

Catching the `ReferencedEntityException` exception and updating template will work. However, in case user doesn't decide to force delete the template then we would have made an update to stable template. What are the implications then?  
Below is what I cam thinking as per your suggestion. 
</blockquote></details>

Yes i was thinking to be this impl, as stable template is not updated, here its only for latestTemplate only isn't?

**Comment by rohitk-h** [comment]
Due to renaming of service, the file changes increased after rebasing with develop. Closing this PR. New PR : https://github.com/harness/harness-core/pull/47914

**Pull request closed without merging**
