### PR TITLE
[feat]: [CDS-85171]: Add filters for selected infrastructure when using environment propagation

### PR DESCRIPTION
**Pull request by lovish1999**
## Describe your changes
Add filters for selected infrastructure when using environment propagation. This is required when an infrastructure is provided by the user in yaml even if environment is propagated from a different stage. 

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56328)

### CODE REVIEW

**Comment by tchaurasiya** [comment]
Lets add the test cases in pr description

**Review by tchaurasiya — COMMENTED** [review]
Lets add test cases in PR description

**Comment by lovish1999** [comment]
trigger ut1

**Comment by lovish1999** [comment]
trigger ut5

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger ut7

**Comment by lovish1999** [comment]
trigger messagecheck

**Comment by lovish1999** [comment]
trigger ut7

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 372 at r3](https://reviewable.io/reviews/harness/harness-core/56328#-NlQaPwZB0jLzQWStpkd:-NlQaPwZB0jLzQWStpke:bftwzsg) ([raw file](https://github.com/harness/harness-core/blob/0328976d2626db4696ee39c035d66b80ea616400/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L372)):*
> ```Java
>             format(
>                 "Exception occurred while saving filters for environment propagated from stage [%s] but having a different infrastructure selected.",
>                 env.getUseFromStage().getStage()),
> ```

can we create a ticket to monitor these warnings ?

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 354 at r3](https://reviewable.io/reviews/harness/harness-core/56328#-NlQaVM93ltC5VPqOzpc:-NlQaVM93ltC5VPqOzpd:b-frglkw) ([raw file](https://github.com/harness/harness-core/blob/0328976d2626db4696ee39c035d66b80ea616400/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L354)):*
> ```Java
>         if (useFromStageEnvironmentYaml == null || useFromStageEnvironmentYaml.getEnvironmentRef() == null) {
>           return;
>         }
> ```

can we extract this out as a method for better readability of this code ?



_Code quote:_
```Java
        YamlField propagatedFromStageConfig =
            PlanCreatorUtils.getStageConfig(filterCreationContext.getCurrentField(), env.getUseFromStage().getStage());
        if (propagatedFromStageConfig == null) {
          return;
        }
        DeploymentStageNode stageElementConfig =
            YamlUtils.read(propagatedFromStageConfig.getNode().toString(), DeploymentStageNode.class);
        if (stageElementConfig == null) {
          return;
        }
        DeploymentStageConfig deploymentStage = stageElementConfig.getDeploymentStageConfig();
        if (deploymentStage == null) {
          return;
        }
        EnvironmentYamlV2 useFromStageEnvironmentYaml = deploymentStage.getEnvironment();
        if (useFromStageEnvironmentYaml == null || useFromStageEnvironmentYaml.getEnvironmentRef() == null) {
          return;
        }
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56328)* status: Some of the checks are too old. 5 file(s) to review. 0 of 2 approvals obtained.

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java` line 86 at r6](https://reviewable.io/reviews/harness/harness-core/56328#-NlRdC22--2Hvv6NqoUB:-NlRdC22--2Hvv6NqoUC:bi4q8h0) ([raw file](https://github.com/harness/harness-core/blob/97d2d415e7c118c3326db950183baee64d3425b2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java#L86)):*
> ```Java
> import org.apache.commons.collections4.CollectionUtils;
> import org.apache.commons.lang3.StringUtils;
> import org.jetbrains.annotations.Nullable;
> ```

import org.jetbrains.annotations.Nullable -> lets not use

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56328)* status: 5 file(s) to review. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56328)* status: 5 file(s) to review. 1 of 2 approvals obtained.

**Comment by lovish1999** [comment]
trigger uts

**Review by tchaurasiya — APPROVED** [review]

**Comment by lovish1999** [comment]
trigger ut8

**Comment by lovish1999** [comment]
trigger ut9

**Comment by lovish1999** [comment]
trigger review

**Comment by lovish1999** [comment]
trigger ut8

**Comment by lovish1999** [comment]
trigger ut9

**Pull request merged**
