### PR TITLE
techdebt: [CDS-80734]: Decouple interfaces from executables

### PR DESCRIPTION
**Pull request by hextechpal**
## Describe your changes
We had coupled out interfaces by extending them and this created a limitation that multiple of our executables cannot be used together. For example, if you want to use a task and task chain executable for a single step you cannot because they share a common method via the Abortable, Expirable, etc. interfaces and cause conflicts.

This PR makes the executables independent in themselves and removes the coupling between them 
Please pay attention that this change is backward compatible as all the changes are localized to the SDK. IF reviewers feel other wise please leave a comment for the same

Testing:

Tested did basic testing in my local and things are running fine
image

image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53627)

### CODE REVIEW

**Review by archit-harness — APPROVED** [review]
> Reviewed 71 of 71 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53627)* status: 71 file(s) to review. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/InterruptPackage.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/53627#-Nfop_iyCAF09vsktL4f:-Nfop_iyCAF09vsktL4g:bcyk9md) ([raw file](https://github.com/harness/harness-core/blob/a2cab93dd562b5ed78e6328b606e50ca8b0b7344/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/InterruptPackage.java#L17)):*
> ```Java
> @Value
> @Builder
> public class InterruptPackage {
> ```

nit: shoud we make multiple impl of interruptPackage based on executableResponse?

**Review by hextechpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53627)* status: 71 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/InterruptPackage.java` line 17 at r1](https://reviewable.io/reviews/harness/harness-core/53627#-Nfop_iyCAF09vsktL4f:-NfosHAQBAS37sAhvJcu:brcovb4) ([raw file](https://github.com/harness/harness-core/blob/a2cab93dd562b5ed78e6328b606e50ca8b0b7344/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/InterruptPackage.java#L17)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

nit: shoud we make multiple impl of interruptPackage based on executableResponse?
</blockquote></details>

yes will make that change, was just lazy :P

**Comment by hextechpal** [comment]
trigger feature-build

**Comment by hextechpal** [comment]
trigger uts

**Comment by hextechpal** [comment]
trigger uts

**Comment by hextechpal** [comment]
trigger uts

**Comment by hextechpal** [comment]
trigger messagecheck

**Review by rohitk-h — APPROVED** [review]
> Reviewed 68 of 71 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53627)* status: 6 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildChainStrategy.java` line 87 at r5](https://reviewable.io/reviews/harness/harness-core/53627#-Nfqam2U1jkLgSyNYf9y:-Nfqam2U1jkLgSyNYf9z:b-pfj3aw) ([raw file](https://github.com/harness/harness-core/blob/e0d1654dfe100a144839202b2f5be0fc2fb63d21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildChainStrategy.java#L87)):*
> ```Java
>   @Override
>   public void failure(InterruptPackage interruptPackage) {
>     throw new UnsupportedOperationException("Expire not supported for Child Chain");
> ```

nit: `Failure` instead of `Expire`
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildrenStrategy.java` line 71 at r5](https://reviewable.io/reviews/harness/harness-core/53627#-Nfqas7YEFwfw_wESjqT:-Nfqas7YEFwfw_wESjqU:b-pfj3aw) ([raw file](https://github.com/harness/harness-core/blob/e0d1654dfe100a144839202b2f5be0fc2fb63d21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildrenStrategy.java#L71)):*
> ```Java
>   @Override
>   public void failure(InterruptPackage interruptPackage) {
>     throw new UnsupportedOperationException("Expire not supported for Child Chain");
> ```

nit: `Failure` instead of `Expire`
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildStrategy.java` line 65 at r5](https://reviewable.io/reviews/harness/harness-core/53627#-NfqawREEmxb17EH7mBw:-NfqawREEmxb17EH7mBx:b-pfj3aw) ([raw file](https://github.com/harness/harness-core/blob/e0d1654dfe100a144839202b2f5be0fc2fb63d21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/ChildStrategy.java#L65)):*
> ```Java
>   @Override
>   public void failure(InterruptPackage interruptPackage) {
>     throw new UnsupportedOperationException("Expire not supported for Child Chain");
> ```

nit: `Failure` instead of `Expire`
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/SyncStrategy.java` line 64 at r5](https://reviewable.io/reviews/harness/harness-core/53627#-Nfqb0ntDYxJ4IpoX7Gg:-Nfqb0ntDYxJ4IpoX7Gh:b-pfj3aw) ([raw file](https://github.com/harness/harness-core/blob/e0d1654dfe100a144839202b2f5be0fc2fb63d21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/invokers/SyncStrategy.java#L64)):*
> ```Java
>   @Override
>   public void failure(InterruptPackage interruptPackage) {
>     throw new UnsupportedOperationException("Expire not supported for Child Chain");
> ```

nit: `Failure` instead of `Expire`
___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java` line 154 at r5](https://reviewable.io/reviews/harness/harness-core/53627#-NfqcaTM9NM5EiHKwVsg:-NfqcaTM9NM5EiHKwVsh:bbo97n1) ([raw file](https://github.com/harness/harness-core/blob/e0d1654dfe100a144839202b2f5be0fc2fb63d21/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/interrupt/InterruptEventHandler.java#L154)):*
> ```Java
>       default:
>         // This should never happen
>         throw new IllegalStateException("response case not supported");
> ```

nit: printing the responseCase will help during troubleshooting.

**Comment by hextechpal** [comment]
trigger ut3

**Comment by hextechpal** [comment]
trigger ut7

**Comment by hextechpal** [comment]
trigger ut3

**Review by archit-harness — APPROVED** [review]

**Review by harshjain12 — APPROVED** [review]

**Pull request merged**
