### PR TITLE
feat: [SSCA-1032]: Adding Elastic search queries in Artifact Service

### PR DESCRIPTION
**Pull request by reetika04**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)

### CODE REVIEW

**Comment by reetika04** [comment]
trigger uts

**Comment by reetika04** [comment]
trigger messagecheck

**Comment by reetika04** [comment]
trigger uts

**Comment by reetika04** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlW9JS86c9dlOILeVxM:-NlW9JS86c9dlOILeVxN:b-jm3jo3) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java#L47)):*
> ```Java
>       case STARTSWITH:
>         return ElasticSearchQueryBuilder.startsWithFieldValue(field, value);
>       case LESSTHAN:
> ```

Can we use metadata/annotation to map operator to elastic ElasticSearchQueryBuilder ?  this will ensure getFiledValue method is extensible.
We can create a common interface for Operator<Query> ->  Query buildQuery(filed,value) .

This will have operator specific implementation like -> ElasticEqualsQueryBuilder , ElasticContainsQueryBuilder .

This can be extended to mongo later with -> MongoEqualsQueryBuilder etc.
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 299 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlWFGK67_l3gdSkt2cj:-NlWFGK67_l3gdSkt2ck:bey4lxs) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L299)):*
> ```Java
>       ArtifactListingRequestBody body, Pageable pageable) {
>     if (featureFlagService.isFeatureFlagEnabled(accountId, FeatureName.SSCA_USE_ELK.name())) {
>       List<String> orchestrationIds = searchService.getOrchestrationIds(accountId, orgIdentifier, projectIdentifier,
> ```

I think we are having both policy & license data in aartifact , we can fetch the artifact from elastic & do pagination here

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlW9JS86c9dlOILeVxM:-NlX8dMK43Zb__DW2nd9:b-5td68c) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java#L47)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

Can we use metadata/annotation to map operator to elastic ElasticSearchQueryBuilder ?  this will ensure getFiledValue method is extensible.
We can create a common interface for Operator<Query> ->  Query buildQuery(filed,value) .

This will have operator specific implementation like -> ElasticEqualsQueryBuilder , ElasticContainsQueryBuilder .

This can be extended to mongo later with -> MongoEqualsQueryBuilder etc.
</blockquote></details>

The Operators are very specific to our usecase. This would introduce 8 classes for a single method. 
MongoEqualsQueryBuilder does not come in the case of this ELKQueryBuilder. Since this is very specifc to ELK and we handle mongo queries using criteria

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 299 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlWFGK67_l3gdSkt2cj:-NlX9MHiBtT67EPL8OYP:b-ifjgjf) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L299)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

I think we are having both policy & license data in aartifact , we can fetch the artifact from elastic & do pagination here
</blockquote></details>

We don't have policy filters and license data in artifact collection. policy details are in enforcement sumary collection

**Comment by reetika04** [comment]
trigger uts

**Review by deepharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlW9JS86c9dlOILeVxM:-NlffqXQ4FqSyK6nZajF:bpwccm9) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/search/ArtifactQueryBuilder.java#L47)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

The Operators are very specific to our usecase. This would introduce 8 classes for a single method. 
MongoEqualsQueryBuilder does not come in the case of this ELKQueryBuilder. Since this is very specifc to ELK and we handle mongo queries using criteria
</blockquote></details>

You can push this to ElasticSearchQueryBuilder itself , keep a map which will be created in ctor
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ComponentVersionQueryBuilder.java` line 25 at r2](https://reviewable.io/reviews/harness/harness-core/56671#-NlfdV8m-grPZAjxwvy7:-NlfdV8m-grPZAjxwvy8:bssi29i) ([raw file](https://github.com/harness/harness-core/blob/c16c4b4f270cd0505f7094861b436d150d3456fe/ssca-manager/service/src/main/java/io/harness/ssca/search/ComponentVersionQueryBuilder.java#L25)):*
> ```Java
> @OwnedBy(HarnessTeam.SSCA)
> public class ComponentVersionQueryBuilder {
>   private Query buildEqualsQuery(List<Integer> versions) {
> ```

Take semantic version her major, minor patch for all the methods
___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ElasticSearchQueryBuilder.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/56671#-NlfgDgo4tib4fGzr2Pg:-NlfgDgo4tib4fGzr2Ph:bt0tqg6) ([raw file](https://github.com/harness/harness-core/blob/c16c4b4f270cd0505f7094861b436d150d3456fe/ssca-manager/service/src/main/java/io/harness/ssca/search/ElasticSearchQueryBuilder.java#L20)):*
> ```Java
> @UtilityClass
> @OwnedBy(HarnessTeam.SSCA)
> public class ElasticSearchQueryBuilder {
> ```

we can make it static class

**Review by reetika04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 7 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/search/ElasticSearchQueryBuilder.java` line 20 at r2](https://reviewable.io/reviews/harness/harness-core/56671#-NlfgDgo4tib4fGzr2Pg:-NlfnGzS1_E2OH3U__kv:b-7f8456) ([raw file](https://github.com/harness/harness-core/blob/c16c4b4f270cd0505f7094861b436d150d3456fe/ssca-manager/service/src/main/java/io/harness/ssca/search/ElasticSearchQueryBuilder.java#L20)):*
<details><summary><i>Previously, deepharness wrote…</i></summary><blockquote>

we can make it static class
</blockquote></details>

It is already a static class because of the @UtilityClass annotation.

**Comment by reetika04** [comment]
trigger uts

**Comment by reetika04** [comment]
trigger uts

**Review by deepharness — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 8 files at r3, 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/56671)* status: 3 file(s) to review. 

___
*[`ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java` line 299 at r1](https://reviewable.io/reviews/harness/harness-core/56671#-NlWFGK67_l3gdSkt2cj:-Nlfhn6qBeR_68W4sHQK:b-6bj5b4) ([raw file](https://github.com/harness/harness-core/blob/031bbd913c2f949bb917b203e2dbd6dfbc5fffc1/ssca-manager/service/src/main/java/io/harness/ssca/services/ArtifactServiceImpl.java#L299)):*
<details><summary><i>Previously, reetika04 (Reetika) wrote…</i></summary><blockquote>

We don't have policy filters and license data in artifact collection. policy details are in enforcement sumary collection
</blockquote></details>

Lets take this in next PR

**Pull request merged**
