### PR TITLE
feat: [IDP-1308]: Audit trails - Scorecards - create, update, delete

### PR DESCRIPTION
**Pull request by devesh-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/54201)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54201)* status: 12 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/audittrials/eventhandlers/dtos/ScorecardsDTO.java` line 23 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-NgvoA1W2_1dJ0x_ZF53:-NgvoA1W2_1dJ0x_ZF54:bnxusle) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/audittrials/eventhandlers/dtos/ScorecardsDTO.java#L23)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @Builder
> public class ScorecardsDTO implements YamlDTO {
> ```

nit: team.IDP 



_Code quote:_
```Java
ScorecardsDTO
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java` line 71 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-Ngvp4VM2ni5YqvynSvy:-Ngvp4VM2ni5YqvynSvz:baev1z3) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java#L71)):*
> ```Java
> 
>   @Inject @Named(OUTBOX_TRANSACTION_TEMPLATE) private TransactionTemplate transactionTemplate;
>   @Inject private OutboxService outboxService;
> ```

nit: private final



_Code quote:_
```Java
  @Inject @Named(OUTBOX_TRANSACTION_TEMPLATE) private TransactionTemplate transactionTemplate;
  @Inject private OutboxService outboxService;
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-Ngvq4X98XnNy77rtJfq:-Ngvq4X98XnNy77rtJfr:b-pc0qr8) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java#L196)):*
> ```Java
>       outboxService.save(new ScorecardUpdateEvent(accountIdentifier, updatedScorecardDetails, oldScorecardDetails));
> 
>       setupUsageProducer.deleteScorecardSetupUsage(
> ```

Not related to this PR - Instead of deleting everything here, we could get the diff and delete only those which aren't applicable now and create/update the remaining.



_Code quote:_
```Java
deleteScorecardSetupUsage
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java` line 322 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-NgvpKoSAhjOWJoxWHbE:-NgvpKoSAhjOWJoxWHbF:b-p2jft) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java#L322)):*
> ```Java
>   }
> 
>   private Map<String, CheckEntity> getIdentifierCheckEntityMapping(String accountIdentifier, Set<String> checkIds) {
> ```

Can we call this method inside validateChecks as well? Looks like we have same code there?



_Code quote:_
```Java
getIdentifierCheckEntityMapping
```

**Review by devesh-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54201)* status: 12 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java` line 196 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-Ngvq4X98XnNy77rtJfq:-Ngy95tp7eF1vp1i4Ib7:b-pl8ohv) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java#L196)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Not related to this PR - Instead of deleting everything here, we could get the diff and delete only those which aren't applicable now and create/update the remaining.
</blockquote></details>

yes will update @vigneswara-propelo on this.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java` line 322 at r2](https://reviewable.io/reviews/harness/harness-core/54201#-NgvpKoSAhjOWJoxWHbE:-Ngy9FYn05DlSRfNd6E_:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/252a981a9f00130be0b861aaa1652d101d662ad2/idp-service/src/main/java/io/harness/idp/scorecard/scorecardchecks/service/ScorecardServiceImpl.java#L322)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Can we call this method inside validateChecks as well? Looks like we have same code there?
</blockquote></details>

Done.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/54201)* status: 20 file(s) to review. 1 of 2 approvals obtained.

**Comment by devesh-harness** [comment]
trigger uts

**Review by Aashrit-Harness — APPROVED** [review]

**Comment by devesh-harness** [comment]
trigger ut8, ut9

**Comment by devesh-harness** [comment]
trigger review

**Pull request merged**
