### PR TITLE
[feat]: [PIE-5235]: Add Pipeline Rollback as Failure Strategy for setup

### PR DESCRIPTION
**Pull request by namanvermah**
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37460)

### CODE REVIEW

**Comment by namanvermah** [comment]
trigger messagecheck

**Review by vaibhav-si — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37460)* status: 16 file(s) to review. 1 of 2 approvals obtained. Waiting on team(s): sto.

**Review by archit-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37460)* status: Waiting on team(s): sto.

**Review by r0610205 — DISMISSED** [review]

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 5 of 11 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37460)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37460)* status: 6 file(s) to review.

**Pull request merged**
