### PR TITLE
fix: [SPG-854]: Fix for null key in secretManagerFunctor

### PR DESCRIPTION
**Pull request by gaurav-jain1**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39844)

### CODE REVIEW

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39844)* status: :shipit: complete! ✓

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/39844#-NGVBirG2wPEsYsSpCy-:-NGVBirG2wPEsYsSpCy0:b6fqhis) ([raw file](https://github.com/harness/harness-core/blob/7551a895188ed127620124c3aa90d4b736f2651d/400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java#L248)):*
> ```Java
>     String encryptionConfigUuid = encryptedDataDetail.getEncryptionConfig().getUuid();
> 
>     encryptionConfigs.put(encryptionConfigUuid, encryptedDataDetail.getEncryptionConfig());
> ```

can the value be null? does concurrent hashmap allows null values?

**Review by gaurav-jain1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39844)* status: 1. unresolved discussions. 

___
*[`400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java` line 248 at r1](https://reviewable.io/reviews/harness/harness-core/39844#-NGVBirG2wPEsYsSpCy-:-NGVuS5iAFSkg2S-h8_H:b-73ue6z) ([raw file](https://github.com/harness/harness-core/blob/7551a895188ed127620124c3aa90d4b736f2651d/400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java#L248)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

can the value be null? does concurrent hashmap allows null values?
</blockquote></details>

conccurent hash map doesn't allow null values either. Here value cannot be null because we are accessing the value in line before that. So in this case, seems like only key can be null.

**Comment by gaurav-jain1** [comment]
trigger ti1

**Pull request merged**
