### PR TITLE
fix: [CDS-42067]: Validate that every phase was its own rollback phase declared

### PR DESCRIPTION
**Pull request by Fernando-Dourado**
## Describe your changes
- Enforce that every phase was its own rollback phase declared

## Checklist
- [X] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36745)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36745)

**Comment by Fernando-Dourado** [comment]
trigger checkstyle, pmd

**Review by hextechpal — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36745)* status: :shipit: complete! ✓

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36745)* status: :shipit: complete! ✓

___
*[`400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java` line 1067 at r2](https://reviewable.io/reviews/harness/harness-core/36745#-NAKlX8Y413J27jp2QdK:-NAKlX8Y413J27jp2QdL:b-6864xf) ([raw file](https://github.com/harness/harness-core/blob/178259b468d6a2ad6bee3f92806ac0caf7790629/400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java#L1067)):*
> ```Java
>     YamlWorkflowValidator.validateWorkflowPreDeploymentSteps(load);
>     if (featureFlagService.isEnabled(FeatureName.VALIDATE_PHASES_AND_ROLLBACK, accountId)) {
>       YamlWorkflowValidator.validatePhasesAndRollbackPhases(load);
> ```

These validations should be in WorkflowYamlHandler.

**Comment by Fernando-Dourado** [comment]
Branch discarded because a wrong merge operation

**Comment by Fernando-Dourado** [comment]
The same content was moved to https://github.com/harness/harness-core/pull/36807

**Pull request closed without merging**
