### PR TITLE
fix: [CDS-83752]: Use strategySetupId when publishing RollbackInfo for steps under stages with strategy

### PR DESCRIPTION
**Pull request by vcalasansh**
## Describe your changes
Suppose you have a pipeline's stage wrapped under a looping strategy, and one of the step's failure strategy is configured with "Manual Intervention" + "Rollback Stage" (see below picture). Then in case the step fails and manual intervention timeout is reached, the pipeline goes into "Waiting" status indefinitely, instead of starting the rollback phase.

image

The root cause of this issue is related to the swapping of stage node's ID with strategy node's ID during plan creation. This swapping is correctly accounted for when calculating rollback parameters during plan creation: https://github.com/harness/harness-core/blob/6d823783b69d4075cf291a46916fcf4d1734c706/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/PlanCreatorUtilsCommon.java#L117C40-L117C62

image

We see that the rollback's node ID is calculated as:
```
RollbackStrategy.STAGE_ROLLBACK, stageNodeId + NGCommonUtilPlanCreationConstants.COMBINED_ROLLBACK_ID_SUFFIX
```
Here, `stageNodeId` is the yaml ID of the stage, which will effectively become the strategy's setupId during the execution, because of the above-mentioned swapping that we do.

However, in the case of "Manual Intervention" + "Stage rollback" failure strategy, we are relying on the outcome published by the `RollbackExecutableUtility.publishRollbackInfo` method to calculate the rollback's plan node ID. This method is currently fetching the stage's node ID from the ambiance, and is not considering the fact that if the stage is wrapped under a strategy, the prefix of the rollback 's plan node ID will be the strategy's setupId, and not the stage's setupId.

In this PR, we fix this behavior by using the strategy's setupId to prefix the rollback's nodeId in case the stage is wrapped under a strategy.

Currently, pipeline gets stuck in "Waiting" status:
image

After this fix, the rollback is correctly started:
image

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55315)

### CODE REVIEW

**Comment by vcalasansh** [comment]
trigger messagecheck

**Comment by vcalasansh** [comment]
trigger uts

**Comment by vcalasansh** [comment]
Failed UTs are related to CI module, so we can disregard them.

**Comment by vcalasansh** [comment]
trigger messagecheck

**Review by sahilhindwani-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55315)* status: 4 file(s) to review. 1 of 2 approvals obtained.

**Review by rohitk-h — APPROVED** [review]

**Comment by vcalasansh** [comment]
trigger review

**Pull request merged**
