### PR TITLE
[feat]: [SRM-9973]: added template registry & iterator for triggering SLO notifications

### PR DESCRIPTION
**Pull request by kapil-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 923 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nkSpjAL_FY0fQ-kRz:-N0nkSpjAL_FY0fQ-kS-:b-suequ5) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L923)):*
> ```Java
>         notificationClient.saveNotificationTemplate(Team.CV, template, true);
>       } catch (UnexpectedException ex) {
>         log.error("Unable to save {} to NotificationService - skipping register notification templates.", template, ex);
> ```

any reason to ignoring this exception?
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/converters/ParameterFieldConverter.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nluj56Vl8LLEtWy7u:-N0nluj56Vl8LLEtWy7v:b-5qo2gy) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/converters/ParameterFieldConverter.java#L26)):*
> ```Java
>       return null;
>     }
>     return ((ParameterField) value).getValue();
> ```

what if ParameterValue is an expression?
___
*[`800-pipeline-service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nw5TH1ksLsXiLSuUD:-N0nw5TH1ksLsXiLSuUE:bqebhii) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/800-pipeline-service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L119)):*
> ```Java
>         NotificationChannelWrapper wrapper = notificationRules.getNotificationChannelWrapper().getValue();
>         String templateId = getNotificationTemplate(pipelineEventType.getLevel(), wrapper.getType());
>         NotificationChannel channel = wrapper.getNotificationChannel().toNotificationChannel(
> ```

why this change?

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o7h7P3R7N2YAOKUUc:-N0o7h7P3R7N2YAOKUUd:b-9pgt4k) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L40)):*
> ```Java
>   @Override
>   public void handle(ServiceLevelObjective sloEntity) {
>     ProjectParams projectParams = ProjectParams.builder()
> ```

this code should be in the service layer.
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o8lZaEuaiwxmwKvOa:-N0o8lZaEuaiwxmwKvOb:b-avcg25) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L74)):*
> ```Java
>   private boolean shouldSendNotification(
>       SLOHealthIndicator sloHealthIndicator, SLONotificationRuleEntityCondition condition) {
>     return condition.getConditionType().equals(SLONotificationRuleConditionType.ERROR_BUDGET_REMAINING_PERCENTAGE)
> ```

this logic should move to actual condition

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 30 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 923 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nkSpjAL_FY0fQ-kRz:-N0rXHKmBEtbFhvz1e7L:bzcorwo) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L923)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

any reason to ignoring this exception?
</blockquote></details>

CVNGAppStartupTest.java is failing due to an external network call
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o7h7P3R7N2YAOKUUc:-N0rXQJe6tkB3zGltROr:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L40)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this code should be in the service layer.
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 74 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o8lZaEuaiwxmwKvOa:-N0rXRIrCsWaI0XFhy0Z:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L74)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this logic should move to actual condition 
</blockquote></details>

done
___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/converters/ParameterFieldConverter.java` line 26 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nluj56Vl8LLEtWy7u:-N0rXVfm6c26DASnQIHn:blj9ecj) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/converters/ParameterFieldConverter.java#L26)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

what if ParameterValue is an expression?
</blockquote></details>

removed this
___
*[`800-pipeline-service/src/main/java/io/harness/pms/notification/NotificationHelper.java` line 119 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nw5TH1ksLsXiLSuUD:-N0rXYty1tRsuv3LidDj:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/800-pipeline-service/src/main/java/io/harness/pms/notification/NotificationHelper.java#L119)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

removed

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o7h7P3R7N2YAOKUUc:-N11z0Cg8j5SiONdPptg:b-mpb72q) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L40)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

done
</blockquote></details>

this entire code should be in the service layer. Not just part of the code.

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 4 file(s) to review. 1 change requests. 5. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0o7h7P3R7N2YAOKUUc:-N1HenPZCmMLfW-jWUUK:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/notification/jobs/SLONotificationHandler.java#L40)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

this entire code should be in the service layer. Not just part of the code.
</blockquote></details>

done

**Review by kjoshi12345 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: 1 change requests. 3. unresolved discussions. 0 of 1 approvals obtained.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598#-:-N1HfKK_1jsgc_g0-Qnd:bnfp4nl)* status: 2. unresolved discussions. 

___
*[`300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java` line 923 at r1](https://reviewable.io/reviews/harness/harness-core/32598#-N0nkSpjAL_FY0fQ-kRz:-N1HfVDJ2p9xiy18SBII:bu2pisb) ([raw file](https://github.com/harness/harness-core/blob/c5e9a2693dbca62114ff49b9838f385e9de01763/300-cv-nextgen/src/main/java/io/harness/cvng/VerificationApplication.java#L923)):*
<details><summary><i>Previously, kapil-harness (Kapil Choudhary) wrote…</i></summary><blockquote>

CVNGAppStartupTest.java is failing due to an external network call
</blockquote></details>

nit: Let's discuss this separately. We should have a flag in the config and we should fail if the template registration does not work.

**Review by kjoshi12345 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32598)* status: :shipit: complete! ✓

**Pull request merged**
