### PR TITLE
[fix]: [PL-22645]: Removed branch name from log in case of duplicate yamlGitConfig

### PR DESCRIPTION
**Pull request by rathodmeetsatish**
Removed branch name from log in case of duplicate yamlGitConfig

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)

### CODE REVIEW

**Review by abhinav-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 274 at r1](https://reviewable.io/reviews/harness/harness-core/31660#-MypgPXhCltVu0Pieo4b:-MypgPXi05XmUpfBNcxS:b6cemu6) ([raw file](https://github.com/harness/harness-core/blob/1c480210f64b04cc53ca13657c1440f5957a13f9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L274)):*
> ```Java
>       log.error("A git sync config with this identifier or repo {} already exists", gitSyncConfigDTO.getRepo());
>       throw new DuplicateEntityException(String.format(
>           "A git sync config with this identifier or repo %s already exists", gitSyncConfigDTO.getRepo()));
> ```

Please also put repo identifier in log and exception both.

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 274 at r1](https://reviewable.io/reviews/harness/harness-core/31660#-MypgPXhCltVu0Pieo4b:-MysHACPAwN76akvv0ZN:b-2rw3qh) ([raw file](https://github.com/harness/harness-core/blob/1c480210f64b04cc53ca13657c1440f5957a13f9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L274)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

Please also put repo identifier in log and exception both.
</blockquote></details>

It should be "A git sync config with identifier %s...". We should remove "this" from here.

Also, I see duplication of exact same message. Lets log the message and then return same in the exception.

**Review by rathodmeetsatish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 274 at r1](https://reviewable.io/reviews/harness/harness-core/31660#-MypgPXhCltVu0Pieo4b:-MyvffAz7aaha0QZcQG-:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1c480210f64b04cc53ca13657c1440f5957a13f9/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L274)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

It should be "A git sync config with identifier %s...". We should remove "this" from here.

Also, I see duplication of exact same message. Lets log the message and then return same in the exception.
</blockquote></details>

Done.

**Review by bhavya181 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Comment by mohitg0795** [comment]
___
*[136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, line 274 at r3](https://reviewable.io/reviews/harness/harness-core/31660#-MywvmdO-aHK0mjieJyX:-MywvmdP82hJOXIY5jyn:b5op5bj) ([raw file](https://github.com/harness/harness-core/blob/41879e9f71863272ceec9fea83617e681787594f/136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java#L274)):*
> ```Java
>       String duplicateIdentifierOrRepoErrorMessage =
>           "A git sync config with identifier [%s] or repo [%s] already exists";
>       log.error(String.format(
> ```

this is again duplication of effort. Why String.format() at 2 places? This complete message should be in a variable.



_Code quote:_
```Java
      log.error(String.format(
          duplicateIdentifierOrRepoErrorMessage, gitSyncConfigDTO.getIdentifier(), gitSyncConfigDTO.getRepo()));
```

**Comment by rathodmeetsatish** [comment]
trigger messagecheck

**Review by mohitg0795 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660#-:-MyxX_ktErZZFmsWUMCU:bnfp4nl)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by goelsatyam2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31660)* status: :shipit: complete! ✓

**Pull request merged**
