### PR TITLE
feat: [PIE-37239]: Infra planCreator change in Environment PlanCreato…

### PR DESCRIPTION
**Pull request by prashantsharma04**
…r V2

Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java` line 79 at r1](https://reviewable.io/reviews/harness/harness-core/33497#-N2pv_FE74Tijnelw6b1:-N2pv_FE74Tijnelw6b2:bnhndj3) ([raw file](https://github.com/harness/harness-core/blob/dc92a35cd4732a3c3e8b9a90ad46e4c7b66d9ff2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/environment/EnvironmentPlanCreatorV2.java#L79)):*
> ```Java
>       try {
>         infraDefinitionField = YamlUtils.readTree(
>             config.getInfrastructureDefinitions().get(0).getInfrastructureDefinitionConfig().toString());
> ```

nit:  we can directly use ```infrastructureDefinitionConfig``` here and also make ```infrastructureDefinitionConfig``` final
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 144 at r1](https://reviewable.io/reviews/harness/harness-core/33497#-N2pv7geEpm32xapEUMk:-N2pv7geEpm32xapEUMl:bw8gvk3) ([raw file](https://github.com/harness/harness-core/blob/dc92a35cd4732a3c3e8b9a90ad46e4c7b66d9ff2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L144)):*
> ```Java
>   public LinkedHashMap<String, PlanCreationResponse> createPlanForInfraSectionV2(YamlNode infraSectionNode,
>       String infraStepNodeUuid, InfrastructureDefinitionConfig infrastructure, KryoSerializer kryoSerializer) {
>     LinkedHashMap<String, PlanCreationResponse> planCreationResponseMap = new LinkedHashMap<>();
> ```

nit: can be final
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/33497#-N2pvMhq9JDW8N264xce:-N2pvMhq9JDW8N264xcf:b-vtbwzk) ([raw file](https://github.com/harness/harness-core/blob/dc92a35cd4732a3c3e8b9a90ad46e4c7b66d9ff2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L185)):*
> ```Java
>     //    if (infraField != null && environmentV2 != null) {
>     //      throw new InvalidRequestException("Infrastructure and Environment cannot be siblings of each other");
>     //    }
> ```

this is still a valid condition, right ?

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 4 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java` line 185 at r1](https://reviewable.io/reviews/harness/harness-core/33497#-N2pvMhq9JDW8N264xce:-N2pw8K-8MKXCM0jVVAS:b-cj1vph) ([raw file](https://github.com/harness/harness-core/blob/dc92a35cd4732a3c3e8b9a90ad46e4c7b66d9ff2/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java#L185)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

this is still a valid condition, right ?
</blockquote></details>

Yes this is valid. Will revert this after doing manual testing

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 5 file(s) to review. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 89 at r2](https://reviewable.io/reviews/harness/harness-core/33497#-N2tak7-5VNWi_GvMV0F:-N2tak7-5VNWi_GvMV0G:bujihiv) ([raw file](https://github.com/harness/harness-core/blob/04acc190c15cae394264fb4edcd53ef9b9c214f3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L89)):*
> ```Java
>       pipelineInfrastructure = (PipelineInfrastructure) stepParameters;
>     }
> ```

use else
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java` line 95 at r2](https://reviewable.io/reviews/harness/harness-core/33497#-N2tbA47BBm3cwXVVo6Z:-N2tbA47BBm3cwXVVo6_:b-ouczg) ([raw file](https://github.com/harness/harness-core/blob/04acc190c15cae394264fb4edcd53ef9b9c214f3/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java#L95)):*
> ```Java
>     }
> 
>     InfraSectionStepParameters infraSectionStepParameters = pipelineInfrastructure != null
> ```

add extra info for v2 plan creator

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 6 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/33497#-N2vJAbA7sYReVnWy4dM:-N2vJAbA7sYReVnWy4dN:b-1zt79r) ([raw file](https://github.com/harness/harness-core/blob/7cce834baa39d2e71bbdee2dcc3884638559fe59/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java#L48)):*
> ```Java
> @FieldDefaults(level = AccessLevel.PRIVATE)
> @TypeAlias("infrastructureDefinitionConfig")
> public class InfrastructureDefinitionConfig implements StepParameters {
> ```

Should create new step params for infra v2 and not use yaml config



_Code quote:_
```Java
InfrastructureDefinitionConfig implements StepParameters
```

**Review by prashantsharma04 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 9 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java` line 48 at r3](https://reviewable.io/reviews/harness/harness-core/33497#-N2vJAbA7sYReVnWy4dM:-N2vX1xICZMQ9YoEYtuB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/7cce834baa39d2e71bbdee2dcc3884638559fe59/125-cd-nextgen/src/main/java/io/harness/cdng/infra/yaml/InfrastructureDefinitionConfig.java#L48)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Should create new step params for infra v2 and not use yaml config
</blockquote></details>

Done.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: 9 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraSection.java` line 7 at r4](https://reviewable.io/reviews/harness/harness-core/33497#-N2yn-F4891f0C63ABYp:-N2yn-F4891f0C63ABYq:b7lcwd8) ([raw file](https://github.com/harness/harness-core/blob/040cd32c4d34d8868ee38e402645f8e7ea30dada/125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfraSection.java#L7)):*
> ```Java
> 
> @OwnedBy(HarnessTeam.CDC)
> public interface InfraSection {}
> ```

why this is needed? without this also we can make common code



_Code quote:_
```Java
public interface InfraSection {}
```

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: Some of the checks are too old. 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33497)* status: Some of the checks are too old. 9 file(s) to review. 1 change requests. 1 of 2 approvals obtained.

**Pull request closed without merging**
