### PR TITLE
feat: [CDS-7363]: Support GCP Inheriting credentials from delegate

### PR DESCRIPTION
**Pull request by jelenaHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)

### CODE REVIEW

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sYamlToDelegateDTOMapper.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31216#-MxgIXo_09OlOvGjJIe7:-MxgIXo_09OlOvGjJIe8:b-6qbtv) ([raw file](https://github.com/harness/harness-core/blob/b88f4cc1b8d92a184551a0683b129aa3f49e5b96/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sYamlToDelegateDTOMapper.java#L49)):*
> ```Java
>     switch (kubernetesCredentialType) {
>       case INHERIT_FROM_DELEGATE:
>         return createKubernetesConfigWhenInheritingCredentials(namespaceNotBlank);
> ```

This does not look right. Since we are inheriting use GCP connector, we should use the Gcloud SDK for workload identity to work. 
```createKubernetesConfigWhenInheritingCredentials(namespaceNotBlank)``` will bring in the exact same behaviour as a k8s connector ( which is not what we want )

**Comment by jelenaHarness** [comment]
> > > Reviewed 7 of 7 files at r1, all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)_ status: 1 change requests. 0 of 1 approvals obtained.
> > 
> > 
> > _[930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sYamlToDelegateDTOMapper.java, line 49 at r1](https://reviewable.io/reviews/harness/harness-core/31216#-MxgIXo_09OlOvGjJIe7:-MxgIXo_09OlOvGjJIe8:b-6qbtv) ([raw file](https://github.com/harness/harness-core/blob/b88f4cc1b8d92a184551a0683b129aa3f49e5b96/930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sYamlToDelegateDTOMapper.java#L49)):_
> > > ```java
> > >     switch (kubernetesCredentialType) {
> > >       case INHERIT_FROM_DELEGATE:
> > >         return createKubernetesConfigWhenInheritingCredentials(namespaceNotBlank);
> > > ```
> > 
> > 
> > This does not look right. Since we are inheriting use GCP connector, we should use the Gcloud SDK for workload identity to work. `createKubernetesConfigWhenInheritingCredentials(namespaceNotBlank)` will bring in the exact same behaviour as a k8s connector ( which is not what we want )
> 
> Reverted back the old changes. The issue was that the gcp clusters don't support basic authentication anymore. I'll set up an old cluster for pr testing

tested changes on 1.8 cluster, working as expected: 
https://pr.harness.io/gcp-test-7/ng/#/account/kmpySmUISimoRrJL6NL73w/cd/orgs/default/projects/defaultproject/pipelines/testpipeline/executions/AtHByrM8RrSadTffm4MfaA/pipeline

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)* status: 1 change requests. 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216#-:-N-zqxQP3Bwyp4Eu3Hy5:bnfp4nl)* status: 1. unresolved discussions.

**Review by jelenaHarness — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31216)* status: :shipit: complete! ✓

**Pull request merged**
