### PR TITLE
feat: [cds-46107]: load templates from fallBack Branch

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
Allows loading of templates from fallBack branch, incase when the template was not created in default branch, earlier we had to manually select the branch from UI to load it, now initially will try to load from default branch, if we didn't find the template in that place, then will try to fetch the template from the fallback branch, it will improve overall user experience and This change will only work for newly created templates, this is the same behaviour as in case of pipelines.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/41034)

### CODE REVIEW

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41034)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateExceptionHelper.java` line 26 at r5](https://reviewable.io/reviews/harness/harness-core/41034#-NIfpS3a9ZszzUdg7nMY:-NIfpS3a9ZszzUdg7nMZ:b-nyfsvr) ([raw file](https://github.com/harness/harness-core/blob/1f0a844e2c31db7ff7df4ea1ac9688e4f8421e7b/840-template-service/src/main/java/io/harness/template/utils/TemplateExceptionHelper.java#L26)):*
> ```Java
>       ex = ex.getCause();
>     }
>     return null;
> ```

We have this already in the TemplateUtils, pls use that



_Code quote:_
```Java
 getScmException
```

**Review by utkarshchoubey-harness — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r3, 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41034)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`840-template-service/src/main/java/io/harness/template/utils/TemplateExceptionHelper.java` line 26 at r5](https://reviewable.io/reviews/harness/harness-core/41034#-NIfpS3a9ZszzUdg7nMY:-NIgEpaQ-seqi8h18-pQ:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/1f0a844e2c31db7ff7df4ea1ac9688e4f8421e7b/840-template-service/src/main/java/io/harness/template/utils/TemplateExceptionHelper.java#L26)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

We have this already in the TemplateUtils, pls use that
</blockquote></details>

Done.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41034)* status: 3 file(s) to review.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r3, 2 of 3 files at r6, 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/41034)* status: :shipit: complete! ✓

**Pull request merged**
