### PR TITLE
[fix]: [CDS-44987]: remove @NGAccessControlCheck from infra get api

### PR DESCRIPTION
**Pull request by tchaurasiya**
## Describe your changes
This is being removed from the annotation because we are manually checking for Access via the accessControlClient
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/39284)

### CODE REVIEW

**Review by Jimit09Gandhi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39284)* status: 2 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/39284#-NFO8Pd7C9oMEcdm_oR2:-NFO8Pd7C9oMEcdm_oR3:bywpny2) ([raw file](https://github.com/harness/harness-core/blob/ff153b867482930e1bf66101c2f241f29a15110d/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L149)):*
> ```Java
>   @Path("{infraIdentifier}")
>   @ApiOperation(value = "Gets an Infrastructure by identifier", nickname = "getInfrastructure")
>   @NGAccessControlCheck(resourceType = NGResourceType.ENVIRONMENT, permission = "core_environment_view")
> ```

Why are we removing access check?
Is it because we are having explicit call checkForAccessOrThrow?

**Comment by tchaurasiya** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java` line 149 at r2](https://reviewable.io/reviews/harness/harness-core/39284#-NFO8Pd7C9oMEcdm_oR2:-NFOleTJDlocYd8NhALZ:b3v6ost) ([raw file](https://github.com/harness/harness-core/blob/ff153b867482930e1bf66101c2f241f29a15110d/120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource/InfrastructureResource.java#L149)):*
<details><summary><i>Previously, Jimit09Gandhi (Jimit Gandhi) wrote…</i></summary><blockquote>

Why are we removing access check?
Is it because we are having explicit call checkForAccessOrThrow?
</blockquote></details>

yes. @jimit09gandhi .
And also as i mentioned in comments.
This annotation requires @resourceIdentifier on the arguments. In our scenario that was not the case.

**Comment by tchaurasiya** [comment]
trigger messagecheck

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39284)* status: 1 change requests. 1. unresolved discussions.

**Review by Jimit09Gandhi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/39284#-:-NFS41YVDW-hcFBMiOV3:bnfp4nl)* status: 1. unresolved discussions.

**Pull request merged**
