### PR TITLE
[feat]: [CCM-10123]: Adding FF to enable Cloud Governance and Chewys Monthly Budget

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
As part of this PR, we have added below feature flags:
1. FF to enable Budget enhancements for chewy
2. FF to enable Cloud Governance in Prod.

## Checklist
- [x] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40914)

### CODE REVIEW

**Comment by iamanmolm** [comment]
trigger messagecheck

**Review by rdsoze — APPROVED** [review]

**Review by Rohit-Kaliki — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40914)* status: :shipit: complete! ✓

___
*[`400-rest/src/test/java/software/wings/features/FeatureNameTest.java` line 455 at r1](https://reviewable.io/reviews/harness/harness-core/40914#-NIDalMuDGbJYMvCZQij:-NIDalMv3w5d3BEnCNsR:b-ivfon1) ([raw file](https://github.com/harness/harness-core/blob/7a9bc9d0b3ccc506a4c78ea1bcc8efbe18a7dd79/400-rest/src/test/java/software/wings/features/FeatureNameTest.java#L455)):*
> ```Java
>     featureNameOrdinalMapping.put(419, "SPG_OPTIMIZE_PIPELINE_QUERY_ON_AUTH");
>     featureNameOrdinalMapping.put(420, "SPG_NG_CUSTOM_WEBHOOK_AUTHORIZATION");
>     featureNameOrdinalMapping.put(421, "HELM_STEADY_STATE_CHECK_1_16");
> ```

@iamanmolm any more context here?

**Comment by iamanmolm** [comment]
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/harness/harness-core/40914)_ status: :shipit: complete! ✓
> 
> _[`400-rest/src/test/java/software/wings/features/FeatureNameTest.java` line 455 at r1](https://reviewable.io/reviews/harness/harness-core/40914#-NIDalMuDGbJYMvCZQij:-NIDalMv3w5d3BEnCNsR:b-ivfon1) ([raw file](https://github.com/harness/harness-core/blob/7a9bc9d0b3ccc506a4c78ea1bcc8efbe18a7dd79/400-rest/src/test/java/software/wings/features/FeatureNameTest.java#L455)):_
> 
> > ```java
> >     featureNameOrdinalMapping.put(419, "SPG_OPTIMIZE_PIPELINE_QUERY_ON_AUTH");
> >     featureNameOrdinalMapping.put(420, "SPG_NG_CUSTOM_WEBHOOK_AUTHORIZATION");
> >     featureNameOrdinalMapping.put(421, "HELM_STEADY_STATE_CHECK_1_16");
> > ```
> 
> @iamanmolm any more context here?

Test cases in 400-rest/src/test/java/software/wings/features/FeatureNameTest.java were failing. Since HELM_STEADY_STATE_CHECK_1_16 was not present in it but was present in 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java earlier at line number 99. But the feature flags in both FeatureNameTest.java and FeatureName.java should be in exact order for the test cases to pass.

Note: In current develop branch they have deleted the test file 400-rest/src/test/java/software/wings/features/FeatureNameTest.java  altogether. But to have a clean PR in [release/saas/776xx](https://github.com/harness/harness-core/tree/release/saas/776xx) I fixed that.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40914)* status: 1. unresolved discussions.

**Pull request merged**
