### PR TITLE
feat: [PL-39275]: send prometheus event fro active project metrics

### PR DESCRIPTION
**Pull request by sahibaCCM**
## Describe your changes
Publish active project event to Prometheus to populate Grafana dashboards.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52186)

### CODE REVIEW

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger ut0

**Comment by sahibaCCM** [comment]
trigger ut1

**Comment by sahibaCCM** [comment]
trigger ut3

**Comment by sahibaCCM** [comment]
trigger ut4

**Comment by sahibaCCM** [comment]
trigger ut0

**Review by Raghav-Murali — APPROVED** [review]

**Review by tiwaritejas — APPROVED** [review]

**Comment by sahibaCCM** [comment]
trigger ut0

**Comment by sahibaCCM** [comment]
trigger ut1

**Comment by sahibaCCM** [comment]
trigger ut3

**Comment by sahibaCCM** [comment]
trigger ut4

**Comment by sahibaCCM** [comment]
trigger ut0

**Comment by sahibaCCM** [comment]
trigger ut1

**Comment by sahibaCCM** [comment]
trigger ut3

**Comment by sahibaCCM** [comment]
trigger uts

**Comment by sahibaCCM** [comment]
trigger ut5

**Comment by mohitg0795** [comment]
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java` line 20 at r1](https://reviewable.io/reviews/harness/harness-core/52186#-NdC0cmx9tRnAAg_OViz:-NdC0cmx9tRnAAg_OVj-:bl254xs) ([raw file](https://github.com/harness/harness-core/blob/301d32bb001eabb2243459139748fde5fc8d43bf/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java#L20)):*
> ```Java
> @NoArgsConstructor
> public class ProjectAuditMetricContext extends AutoMetricContext {
>   public ProjectAuditMetricContext(String projectId, String orgId, String accountId, String identifier) {
> ```

As a general recommendation, we should always structure our arguments in a logical order. eg: AccountIdentifier is generally the first, then org, then project and so on.

**Comment by mohitg0795** [comment]
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java` line 21 at r1](https://reviewable.io/reviews/harness/harness-core/52186#-NdC0v8u0KpB69ZB97Z4:-NdC0v8u0KpB69ZB97Z5:byuyflo) ([raw file](https://github.com/harness/harness-core/blob/301d32bb001eabb2243459139748fde5fc8d43bf/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/beans/ProjectAuditMetricContext.java#L21)):*
> ```Java
> public class ProjectAuditMetricContext extends AutoMetricContext {
>   public ProjectAuditMetricContext(String projectId, String orgId, String accountId, String identifier) {
>     put("projectId", projectId);
> ```

I would suggest you to use constants instead of hard coded strings here. It would help to keep it consistent for all type of metrics we publish, currently high chances of making mistakes with using direct hard coded strings.

**Comment by mohitg0795** [comment]
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 33 at r1](https://reviewable.io/reviews/harness/harness-core/52186#-NdC1AUT3xWRR8Vx5ri5:-NdC1AUT3xWRR8Vx5ri6:b9odzrk) ([raw file](https://github.com/harness/harness-core/blob/301d32bb001eabb2243459139748fde5fc8d43bf/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L33)):*
> ```Java
>     try (ProjectAuditMetricContext ignore = new ProjectAuditMetricContext(projectId, orgId, accountId, identifier)) {
>       metricService.incCounter(metricName);
>     }
> ```

don't want to use catch block at all?

**Comment by mohitg0795** [comment]
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/52186#-NdC1Evz8a6PQkJitWao:-NdC1Evz8a6PQkJitWap:b-5qezjb) ([raw file](https://github.com/harness/harness-core/blob/301d32bb001eabb2243459139748fde5fc8d43bf/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L34)):*
> ```Java
>       metricService.incCounter(metricName);
>     }
>   }
> ```

missing line space

**Comment by mohitg0795** [comment]
*[`platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/52186#-NdC1Kvn-149xwdozl6Q:-NdC1Kvn-149xwdozl6R:b-kpq2m8) ([raw file](https://github.com/harness/harness-core/blob/301d32bb001eabb2243459139748fde5fc8d43bf/platform-service/modules/audit-service/src/main/java/io/harness/audit/metrics/impl/ProjectAuditMetricsServiceImpl.java#L35)):*
> ```Java
>     }
>   }
>   public void recordAuditMetricForActiveProject(String projectId, String orgId, String accountId, String identifier) {
> ```

Keep public methods on top of the class and private methods toward bottom, it helps to enhance the readability

**Pull request merged**
