### PR TITLE
fix: [CDS-34611]: Add log for working directory

### PR DESCRIPTION
**Pull request by puthrayaharness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31293)

### CODE REVIEW

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31293)* status: :shipit: complete! ✓

**Comment by puthrayaharness** [comment]
trigger messagecheck

**Review by inderschera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31293)* status: :shipit: complete! ✓

*[a discussion](https://reviewable.io/reviews/harness/harness-core/31293#-MxhPz0F4lCNNksct7pg:-MxhPz0F4lCNNksct7ph:bw8u3m0) (no related file):*
No delegate side logging?

---
___
*[400-rest/src/main/java/software/wings/sm/states/ShellScriptState.java, line 533 at r1](https://reviewable.io/reviews/harness/harness-core/31293#-MxhPlBpDWdok5fXwEzi:-MxhPlBpDWdok5fXwEzj:bc8xuu3) ([raw file](https://github.com/harness/harness-core/blob/7c6f97fbeec10ae5a80d92d70e46cad104d08a46/400-rest/src/main/java/software/wings/sm/states/ShellScriptState.java#L533)):*
> ```Java
>     ShellScriptParameters params = shellScriptParameters.build();
>     log.info("Working directory for accountId: {} appId: {} & activityId: {} is {}", params.getAccountId(),
>         params.getAppId(), params.getActivityId(), params.getWorkingDirectory());
> ```

let's log both commandPath, and params.getWorkingDirectory().

**Review by poojaSinghal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31293)* status: :shipit: complete! ✓

**Pull request merged**
