### PR TITLE
[feat]: [PLG-2002]: added NG Audits for NG Update API for isCrossGenerationAccessEnabled and defaultExperience

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
added NG Audits for NG Update API for isCrossGenerationAccessEnabled and defaultExperience

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)

### CODE REVIEW

**Comment by kapil-harness** [comment]
Screenshot 2023-02-23 at 2 02 51 AM
Screenshot 2023-02-23 at 2 03 02 AM
Screenshot 2023-02-23 at 2 03 16 AM

**Review by Xin-Harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 1 of 4 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 12 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuu9WP6-4gAxfzocjP:-NOuu9WP6-4gAxfzocjQ:b-cnladw) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java#L11)):*
> ```Java
> 
> public class AccountDetailsConstants {
>   public static final String RESOURCE_NAME = "Account Details";
> ```

We may need to eliminate space between the word

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 12 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java` line 11 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuu9WP6-4gAxfzocjP:-NOuwV8h8McoEGTskuiw:bshumq0) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java#L11)):*
<details><summary><i>Previously, Xin-Harness (Xin Shao) wrote…</i></summary><blockquote>

We may need to eliminate space between the word
</blockquote></details>

this is displayed on the NG Audits UI hence we need space in "Account Details", so that it is readable.

**Review by thomas-grasman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 12 file(s) to review. 2 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsCrossGenerationAccessUpdateEvent.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuubvr42uZW4sRE56V:-NOuubvr42uZW4sRE56W:bfbh1nc) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsCrossGenerationAccessUpdateEvent.java#L47)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     Map<String, String> labels = new HashMap<>();
> ```

Create a static map rather than generating a new object each call:



_Code snippet:_
```Java
private static Map<String, String> labels = Collections.singletonMap(LABEL_KEY_RESOURCE_NAME, RESOURCE_NAME);
```
___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsDefaultExperienceUpdateEvent.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuvZ-P3vC_FgROBg1b:-NOuvZ-P3vC_FgROBg1c:b-ya81ng) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsDefaultExperienceUpdateEvent.java#L47)):*
> ```Java
>   @Override
>   public Resource getResource() {
>     Map<String, String> labels = new HashMap<>();
> ```

Same as above

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 12 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsCrossGenerationAccessUpdateEvent.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuubvr42uZW4sRE56V:-NOv1n-zEXjLhD9Zgn-P:bgg7g4z) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsCrossGenerationAccessUpdateEvent.java#L47)):*
<details><summary><i>Previously, thomas-grasman (Thomas Grasman) wrote…</i></summary><blockquote>

Create a static map rather than generating a new object each call:
</blockquote></details>

Static immutable map won't work here because in next line we are added a value to it. I tried it but my IDE was giving compilation warning. Also, cannot find any code snippet as such in our code base.
___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsDefaultExperienceUpdateEvent.java` line 47 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOuvZ-P3vC_FgROBg1b:-NOv29vJ-gjXQv_TTl7o:bnj7hl0) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/events/AccountDetailsDefaultExperienceUpdateEvent.java#L47)):*
<details><summary><i>Previously, thomas-grasman (Thomas Grasman) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

same as above

**Review by Xin-Harness — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 13 file(s) to review. 2 change requests. 2. unresolved discussions. 0 of 2 approvals obtained.

**Review by Xin-Harness — DISMISSED** [review]
> Reviewed 5 of 8 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 13 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by neelam-harness — CHANGES_REQUESTED** [review]

**Review by kapil-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 13 file(s) to review. 2 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java` line 10 at r3](https://reviewable.io/reviews/harness/harness-core/44238#-NOueZy88rGe8kFtArMo-r3-10:-NOv5sqfAnlZOomSWx2G:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/9bcc670b0cbd79c08bebd8c544caa332c85c2090/400-rest/src/main/java/software/wings/beans/accountproperties/AccountDetailsConstants.java#L10)):*
<details><summary><i>Previously, neelam-harness wrote…</i></summary><blockquote>

Let's add the owner as PLG ? `@OwnedBy(HarnessTeam.PLG)`
</blockquote></details>

Done.

**Review by neelam-harness — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 2 of 7 files at r3, 5 of 8 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 1 of 2 approvals obtained.

**Review by Xin-Harness — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: 1 change requests. 2. unresolved discussions.

**Review by thomas-grasman — APPROVED** [review]
> Reviewed 2 of 10 files at r1, 2 of 7 files at r3, 5 of 8 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/44238)* status: :shipit: complete! ✓

**Pull request merged**
