### PR TITLE
feat: [CDS-36903]: Move ServiceEntity to new 127-cd-nextgen-entities module

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- created **127-cd-nextgen-entities** module to contain entities, serviceImpls for the entities of CD NG
- Also merge **127-cd-nextgen-beans** into **127-cd-nextgen-entities** 

You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)* status: 94 file(s) to review. 0 of 1 approvals obtained. 

___
*[`950-ng-core/src/main/java/io/harness/ng/core/variable/entity/Variable.java` line 49 at r3](https://reviewable.io/reviews/harness/harness-core/32773#-N1IG5sD6qLL5qhYb6vP:-N1IG5sE4M3mT5oUmDWI:b-55m06w) ([raw file](https://github.com/harness/harness-core/blob/2fdb21083c028de4a6e4efb28ed91051c83c8f9f/950-ng-core/src/main/java/io/harness/ng/core/variable/entity/Variable.java#L49)):*
> ```Java
> @StoreIn(DbAliases.NG_MANAGER)
> @Persistent
> public abstract class Variable implements PersistentEntity, NGAccountAccess {
> ```

Fix for broken develop, copied from https://github.com/harness/harness-core/pull/32808

**Review by archit-harness — DISMISSED** [review]
> Reviewed 26 of 38 files at r1, 61 of 68 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)* status: :shipit: complete! ✓

___
*[`125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java` line 59 at r4](https://reviewable.io/reviews/harness/harness-core/32773#-N1IgKzwApaFVyFeF6-g:-N1IgKzwApaFVyFeF6-h:b9sq37r) ([raw file](https://github.com/harness/harness-core/blob/c52b9a2fb4d0ec10fb312430c99c29545c3b03e2/125-cd-nextgen/src/main/java/io/harness/serializer/CDNGRegistrars.java#L59)):*
> ```Java
>           .addAll(ConnectorNextGenRegistrars.kryoRegistrars)
>           .addAll(GitOpsRegistrars.kryoRegistrars)
>           .addAll(io.harness.serializer.YamlBeansModuleRegistrars.kryoRegistrars)
> ```

Fully qualified name can be reduced



_Code quote:_
```Java
io.harness.serializer.
```

**Comment by yogesh-chauhan** [comment]
A basic k8s deployment for sanity since classes
Screenshot 2022-05-05 at 4 25 40 PM

**Review by anilchowdhury-harness — APPROVED** [review]
:lgtm:

> Reviewed 26 of 38 files at r1, 61 of 68 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773#-:-N1Iw8xe6RtlLoSw3c9e:bnfp4nl)* status: :shipit: complete! ✓

**Review by anilchowdhury-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)* status: :shipit: complete! ✓

**Review by jennyjames21 — DISMISSED** [review]
> Reviewed 26 of 38 files at r1, 61 of 68 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)* status: :shipit: complete! ✓

**Review by jennyjames21 — APPROVED** [review]
> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32773)* status: :shipit: complete! ✓

**Pull request merged**
