### PR TITLE
feat: [IDP-1135]: Multiple datapoint values support for isFileExist & meanTimeToMerge

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52646)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52646)* status: 15 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/52646#-NdotuwQ9N9ZJIFr-MCu:-NdotuwQ9N9ZJIFr-MCv:b-gnb7q6) ([raw file](https://github.com/harness/harness-core/blob/a8dd92987a411477b40d0a07a12d6e24a5d0bd3d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java#L34)):*
> ```Java
>     for (String inputValue : inputValues) {
>       if (!data.containsKey(inputValue)) {
>         if (inputValue.equals(GITHUB_DEFAULT_BRANCH_KEY_ESCAPED)) {
> ```

We need the regular string (ref/) in the data map instead of the escaped string (\"ref/"\)
We need to escaped string only in the expression. Here the input value will have the escaped string. That's why added this.

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52646)* status: 15 file(s) to review. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java` line 34 at r1](https://reviewable.io/reviews/harness/harness-core/52646#-NdotuwQ9N9ZJIFr-MCu:-NdoysGb3dxQdB9SMian:b-fi3ke6) ([raw file](https://github.com/harness/harness-core/blob/a8dd92987a411477b40d0a07a12d6e24a5d0bd3d/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/GithubIsBranchProtectedParser.java#L34)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We need the regular string (ref/) in the data map instead of the escaped string (\"ref/"\)
We need to escaped string only in the expression. Here the input value will have the escaped string. That's why added this.
</blockquote></details>

we are already doing this in constructDataPointInfo method right?

**Review by vikyathharekal — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52646)* status: 15 file(s) to review. 1 of 2 approvals obtained.

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52646)* status: 16 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut0, ut9

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
