### PR TITLE
[feat]: [PIE-7568]: Changed ErrorCode from InvalidRequestException(400) to EntityNotFoundException(404)

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Issue: We were earlier sending to InvalidRequestException(400) in case when inputSet was deleted from github-Repo.
Change: Have changes error-code to EntityNotFoundException(404).
Testing: Local.

Note: This is a backward incompatible change and as decided with PM, we are adding public notes for the same.

In Case of New Apis(for whom this change was requested)
Screenshot 2023-03-21 at 4 50 17 PM

InCase of Remote Entities: (No Change in flows and behaviour)
Screenshot 2023-03-21 at 4 47 08 PM

InCase of Inline: (No change in behaviour but change in error code)
Screenshot 2023-03-21 at 4 50 00 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45404)

### CODE REVIEW

**Review by adivishy1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45404)* status: 3 file(s) to review. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/45404#-NR2pb0UEm_E2rT5XCaP:-NR2pb0UEm_E2rT5XCaQ:b-45svmu) ([raw file](https://github.com/harness/harness-core/blob/74bed865e29a2e6f30bf3814794e83033dd9cb8d/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L123)):*
> ```Java
>     if (!optionalInputSetEntity.isPresent()) {
>       throw new EntityNotFoundException(
>           String.format("InputSet with the given ID: %s does not exist or has been deleted", inputSet));
> ```

Can we add repo and branch as well to this error message? or will is it not needed as we have it in the hint exception which being thrown?

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45404)* status: 3 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java` line 123 at r2](https://reviewable.io/reviews/harness/harness-core/45404#-NR2pb0UEm_E2rT5XCaP:-NR2rRgG4985IKfxvzA0:bi1w208) ([raw file](https://github.com/harness/harness-core/blob/74bed865e29a2e6f30bf3814794e83033dd9cb8d/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/InputSetsApiImpl.java#L123)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

+1
</blockquote></details>

In case of Remote entites, already SCM error is thrown which has this information. Basically SCM_BAD_REQUESTS surfaces up.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 153 at r2](https://reviewable.io/reviews/harness/harness-core/45404#-NR2rSqT-XwxJg76aFgU:-NR2rkDsBnLsNoIiWb-0:b-6zi56o) ([raw file](https://github.com/harness/harness-core/blob/74bed865e29a2e6f30bf3814794e83033dd9cb8d/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L153)):*
> In case of Remote entites, already SCM error is thrown which has this information. Basically SCM_BAD_REQUESTS surfaces up.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45404)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45404)* status: :shipit: complete! ✓

**Pull request merged**
