### PR TITLE
[fix]: [PIE-6267]: Adding whenCondition in customStagePlanCreatorV1 for simplified YAML

### PR DESCRIPTION
**Pull request by brijeshdhakar**
## Describe your changes
Adding when condition in CustomStagePlanCreatorV1 for simplified YAML.
Impact: Will impact the execution of customStage with simplified YAML. Till now, customStage always run irresprctive of whenCondition and pipeline status so far. Now when condition will be honoured.

Testing: Did manual testing. Ran basic flows of pipeline with custom stage in simplified YAML.

ReleaseNotes summary needed? No

Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? Yes
if the newer version of pipeline-service creates the task parameter and calls older cg manager, will it be okay? Yes
Did you remove an enum → No
Did you add an enum(That too at end of list) → No
FeatureFlag Added/Removed -> No
Verify Changes with affects any -> No

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger messagecheck

**Review by hextechpal — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/40108#-NGtsu8m-Z0CByfHvejB:-NGtsu8m-Z0CByfHvejC:b-byd1yp) ([raw file](https://github.com/harness/harness-core/blob/3242a32f393340afb4d83c39910621e6054b4fe8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L125)):*
> ```Java
>     String name = config.getNodeName();
>     StageWhenCondition whenCondition = null;
>     if (config.getNode().getField("when") != null) {
> ```

Can we have this constant in some common util which everyone would be using? YAMLFieldNameConstants maybe



_Code quote:_
```Java
"when"
```

**Review by archit-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 1 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/40108#-NGtsu8m-Z0CByfHvejB:-NGtt9jk9F7LyQ3_o6jW:b-2m8c1m) ([raw file](https://github.com/harness/harness-core/blob/3242a32f393340afb4d83c39910621e6054b4fe8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L125)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Can we have this constant in some common util which everyone would be using? YAMLFieldNameConstants maybe
</blockquote></details>

Plus you would be using Stage and Step When condition  a lot in simplified yaml, so helper - YamlFieldsHelper where we can keep this?

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 3 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java` line 125 at r1](https://reviewable.io/reviews/harness/harness-core/40108#-NGtsu8m-Z0CByfHvejB:-NGz7-Hm0QGlgTMHwesW:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/3242a32f393340afb4d83c39910621e6054b4fe8/pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/customstage/v1/CustomStagePlanCreatorV1.java#L125)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

Plus you would be using Stage and Step When condition  a lot in simplified yaml, so helper - YamlFieldsHelper where we can keep this?
</blockquote></details>

Done.

**Review by archit-harness — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 3 file(s) to review. 1 of 2 approvals obtained.

**Review by prashantsharma04 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108)* status: 3 file(s) to review. 1 change requests. 1 of 2 approvals obtained. 

___
*[`clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java` line 109 at r2](https://reviewable.io/reviews/harness/harness-core/40108#-NGzTyJ9C4ILzsN1XTb9:-NGzTyJA487N4b_YUxac:bpyxvp0) ([raw file](https://github.com/harness/harness-core/blob/bbcb0134a3c2fb96839b57474f7486ecc1470ab8/clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/when/utils/RunInfoUtils.java#L109)):*
> ```Java
>   public String getStageWhenCondition(YamlField field) {
>     StageWhenCondition stageWhenCondition = null;
>     if (field.getNode().getField(YAMLFieldNameConstants.WHEN) != null) {
> ```

field.getNode() can be null

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108#-:-NGzVpYs7Nlx_IE5_Dj8:bnfp4nl)* status: 3 file(s) to review.

**Review by prashantsharma04 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108#-:-NGzVybt7ERrbQ7eqA7z:bnfp4nl)* status: 3 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108#-:-NGzWBWZDIiilnxw5mAS:bnfp4nl)* status: 3 file(s) to review.

**Review by prashantsharma04 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40108#-:-NGzWla6E485p7Xni-3a:bnfp4nl)* status: :shipit: complete! ✓

**Pull request merged**
