### PR TITLE
feat: [SRM-10698]: Support Variables in monitoredService template

### PR DESCRIPTION
**Pull request by AbhijithHarness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33766)

### CODE REVIEW

**Comment by AbhijithHarness** [comment]
trigger ti1

**Comment by AbhijithHarness** [comment]
trigger ti3

**Comment by AbhijithHarness** [comment]
trigger ti4

**Review by deepak-harness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33766)* status: 7 file(s) to review. 

___
*[`840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java` line 591 at r2](https://reviewable.io/reviews/harness/harness-core/33766#-N3XtjcTCvy9r17m5Zoo:-N3XtjcTCvy9r17m5Zop:buldx1v) ([raw file](https://github.com/harness/harness-core/blob/75e3ef52b3ee9b46cbd922d1eba4fcae2c24de68/840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java#L591)):*
> ```Java
>     } else {
>       return ResponseDTO.newResponse(
>           YamlVariablesUtils.getVariablesFromYaml(entityYaml, templateEntity.getTemplateEntityType()));
> ```

nit: we can have map binder for template entity type and get the variable merge response from the service.

**Review by AbhijithHarness — COMMENTED** [review]
tr

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33766#-:-N3Y7oRf4nlWmE7CF5UY:b32wxv)* status: 7 file(s) to review.

**Review by deepak-harness — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33766)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33766)* status: :shipit: complete! ✓

**Pull request merged**
