### PR TITLE
feat: [SRM-9872]: CVNG verify step V2 migration

### PR DESCRIPTION
**Pull request by AbhijithHarness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32205)

### CODE REVIEW

**Review by kjoshi12345 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32205)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/32205#-N-S_K6M-3i1CPYAeuX0:-N-S_K6M-3i1CPYAeuX1:b-d0v2xg) ([raw file](https://github.com/harness/harness-core/blob/3d13d11d3b51b45222e87f510423f31e2412b686/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java#L45)):*
> ```Java
> @RecasterAlias("io.harness.cvng.cdng.beans.CVNGStepInfo")
> public class CVNGStepInfo implements CVStepInfoBase {
>   @VariableExpression(skipVariableExpression = true)
> ```

why do we need this annotation. are static fields also getting used? 
Otherwise we can move this to some other constants file.
___
*[300-cv-nextgen/src/main/resources/io/harness/cvng/cdng/services/impl/pipeline-with-verify-step.json, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/32205#-N-S_lF7-GgjFcaVn4O6:-N-S_lF7-GgjFcaVn4O7:b-g5enni) ([raw file](https://github.com/harness/harness-core/blob/3d13d11d3b51b45222e87f510423f31e2412b686/300-cv-nextgen/src/main/resources/io/harness/cvng/cdng/services/impl/pipeline-with-verify-step.json#L1)):*
> ```JSON
> {
> ```

should we use yaml instead of json?

**Review by AbhijithHarness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32205)* status: 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java, line 45 at r1](https://reviewable.io/reviews/harness/harness-core/32205#-N-S_K6M-3i1CPYAeuX0:-N-WAuXn-Ds65cUV-ZyX:b-hmcp0g) ([raw file](https://github.com/harness/harness-core/blob/3d13d11d3b51b45222e87f510423f31e2412b686/300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGStepInfo.java#L45)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

why do we need this annotation. are static fields also getting used? 
Otherwise we can move this to some other constants file.
</blockquote></details>

Yes, i had fixed it on PMS code, but Archit asked me to do this as of now.
___
*[300-cv-nextgen/src/main/resources/io/harness/cvng/cdng/services/impl/pipeline-with-verify-step.json, line 1 at r1](https://reviewable.io/reviews/harness/harness-core/32205#-N-S_lF7-GgjFcaVn4O6:-N-WB6nBDIPHbMd9WVZx:bfykaeb) ([raw file](https://github.com/harness/harness-core/blob/3d13d11d3b51b45222e87f510423f31e2412b686/300-cv-nextgen/src/main/resources/io/harness/cvng/cdng/services/impl/pipeline-with-verify-step.json#L1)):*
<details><summary><i>Previously, kjoshi12345 (Kamal Joshi) wrote…</i></summary><blockquote>

should we use yaml instead of json?
</blockquote></details>

PMS code takes json string as input.

**Review by kjoshi12345 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32205#-:-N-WPdL05oHPn3tyrr8a:bnfp4nl)* status: :shipit: complete! ✓

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Comment by AbhijithHarness** [comment]
trigger messagecheck

**Pull request merged**
