### PR TITLE
feat:[CDS-78286]: refactoring jira user flow to optimize jira calls

### PR DESCRIPTION
**Pull request by naman-goenka**
## Describe your changes

- Refactors the Jira user flow in `JiraTaskNGHandler` and shifts the flow to `JiraClient`.
- Delegate Only Change. Backward compatibility of `JiraClient` create and update calls in CG and CCM are taken care of.
- Advantage 
   a. removes duplicate metadata calls in create and update flows in NG.
   b. reduces `getInstanceDetails` calls to 1 per create/update flow from 3 per jira user field per create/update flow
- While refactoring adding one fast return condition if no user type fields in metadata. Also added some null checks.   
- Changed error message to include the query used.
- Dev Testing Jira User flow in NG: [Test Plan](https://docs.google.com/spreadsheets/d/1PfTDKLqKibFRfyO1dmlTkrhri_-GI8JdISfwws9njLc/edit#gid=1495506352)
- Exhaustive UTs added for different cases of Jira user flow in `JiraClient
- [Tech Spec](https://harness.atlassian.net/wiki/spaces/CDNG/pages/21451080128/Jira+API+Performance+Improvements)

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52786)

### CODE REVIEW

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by Y0709 — APPROVED** [review]

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52786)* status: 5 file(s) to review.

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger review

**Comment by naman-goenka** [comment]
trigger messagecheck

**Review by lasdox — DISMISSED** [review]

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger messagecheck

**Comment by naman-goenka** [comment]
trigger uts

**Comment by naman-goenka** [comment]
trigger ut1

**Review by Y0709 — APPROVED** [review]

**Review by abhinavmittal-harness — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52786)* status: 5 file(s) to review.

**Comment by naman-goenka** [comment]
trigger review

**Pull request merged**
