### PR TITLE
feat: [CDS-44948]: Remove CD_SERVICE_ENV_RECONCILIATION FF

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
## Describe your changes
Removing the feature flag CD_SERVICE_ENV_RECONCILIATION
This enables template service to call NG manager for reconciling inputs of service/environment/infrastructure

We also identified a tech debt that needs to be handled, more details here https://harness.atlassian.net/browse/CDS-46540

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40076)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger ti0

**Comment by yogesh-chauhan** [comment]
trigger ft1

**Review by inderschera — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40076)* status: :shipit: complete! ✓

___
*[`840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java` line 114 at r1](https://reviewable.io/reviews/harness/harness-core/40076#-NGtcELEDVZj4zUnWSdW:-NGtcELEDVZj4zUnWSdX:b-jfty09) ([raw file](https://github.com/harness/harness-core/blob/67dcbde6f32038f4e3e72afe3b81ed095a55e468/840-template-service/src/main/java/io/harness/template/helpers/InputsValidator.java#L114)):*
> ```Java
>     InputsValidationResponse templateInputsValidationResponse =
>         validateTemplateInputs(accountId, orgId, projectId, yamlNode, templateCacheMap, depth);
>     Map<String, Object> resolvedTemplatesMap = templateMergeServiceHelper.mergeTemplateInputsInObject(
> ```

nit: should we only do this if yamlNode has templateRefs? 
___
*[`840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java` line 78 at r1](https://reviewable.io/reviews/harness/harness-core/40076#-NGtcVCL4OPpu7x1w4ID:-NGtcVCMDb49pnvwBeSm:b-vdhdo0) ([raw file](https://github.com/harness/harness-core/blob/67dcbde6f32038f4e3e72afe3b81ed095a55e468/840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java#L78)):*
> ```Java
>     // Returning the Refreshed YAML corresponding to the ResMap
>     String inputsRefreshYaml = YamlPipelineUtils.writeYamlString(refreshedTemplateInputsMap);
>     Map<String, Object> resolvedTemplatesMap = templateMergeServiceHelper.mergeTemplateInputsInObject(
> ```

nit: same here

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40076)* status: :shipit: complete! ✓

**Review by inderschera — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40076)* status: :shipit: complete! ✓

**Pull request merged**
