### PR TITLE
feat: [CDP-37112]: Added unit tests for changes in CDS-36740

### PR DESCRIPTION
**Pull request by sainath-b**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32799)

### CODE REVIEW

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by PragyeshMishra01 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32799)* status: :shipit: complete! ✓

**Comment by sainath-b** [comment]
trigger messagecheck

**Comment by arvind-choudhary-h** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/32799#-N1Iwb_v60m9nPJ_hXde:-N1Iwb_v60m9nPJ_hXdf:bsjm0vu) ([raw file](https://github.com/harness/harness-core/blob/639edc74e57ee1e47359a9685cdd950c7b350a03/930-delegate-tasks/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L163)):*
> ```Java
> 
>   @VisibleForTesting
>   public String generateKubeConfigFromRancher(RancherConfig rancherConfig, String clusterId) throws IOException {
> ```

nit: public is also not required. Can be package private



_Code quote:_
```Java
public
```

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32799)* status: :shipit: complete! ✓

**Comment by sainath-b** [comment]
> _[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java` line 163 at r1](https://reviewable.io/reviews/harness/harness-core/32799#-N1Iwb_v60m9nPJ_hXde:-N1Iwb_v60m9nPJ_hXdf:bsjm0vu) ([raw file](https://github.com/harness/harness-core/blob/639edc74e57ee1e47359a9685cdd950c7b350a03/930-delegate-tasks/src/main/java/software/wings/delegatetasks/rancher/RancherTaskHelper.java#L163)):_
> 
> > ```java
> >   @VisibleForTesting
> >   public String generateKubeConfigFromRancher(RancherConfig rancherConfig, String clusterId) throws IOException {
> > ```
> 
> nit: public is also not required. Can be package private
> 
> _Code quote:_
> 
> ```java
> public
> ```

Done. Earlier was writing test in file which was not in same package. But it can be package private.

**Review by arvind-choudhary-h — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32799)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by PragyeshMishra01 — APPROVED** [review]

**Review by PragyeshMishra01 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32799)* status: :shipit: complete! ✓

**Pull request merged**
