### PR TITLE
[feat]: [CDS-72805]: Integrated defaultRepo setting at BE.

### PR DESCRIPTION
**Pull request by senjucanon2**
## Describe your changes:
Context: Default Repo setting was already present, when user doesn't provide repo for gitX, this will be used.
Changes: Have integrated defaultRepo as gitX setting for pipeline/InputSets and Templates.
Impact: Creation Flow for pipeline/InputSets and Templates.
Testing: Cases:

- Valid Repos
- Invalid Repos
- Request having repo different from default repo in setting
- Request not having repo and default repo in setting being honoured.
- Request not having connector and repo, but default connector and default repo being honoured.

## Checklist
- [ ] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50475)

### CODE REVIEW

**Comment by senjucanon2** [comment]
trigger uts

**Review by adivishy1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50475)* status: 8 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_DuknsBBKuUniZ6Bmy:-N_DuknsBBKuUniZ6Bmz:b-y7oylk) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L100)):*
> ```Java
>       String defaultRepoForGitX = getDefaultRepoForGitX(accountIdentifier, orgIdentifier, projIdentifier);
> 
>       if (!isEmpty(defaultRepoForGitX)) {
> ```

why not use isNotEmpty?
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 765 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_Duudl9dSxauFKitF0:-N_Duudl9dSxauFKitF1:b3bhm1p) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L765)):*
> ```Java
>     gitXSettingsHelper.setConnectorRefForRemoteEntity(accountIdentifier, orgIdentifier, projIdentifier);
>     gitXSettingsHelper.setDefaultRepoForRemoteEntity(accountIdentifier, orgIdentifier, projIdentifier);
>   }
> ```

are we setting default repo even if we have not set a default connector?

IMO, we should set default repo only if the default connector is set[default repo should be at a connector level instead of just the scope], else the selected connector might not have access to default repo

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50475)* status: 8 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 100 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_DuknsBBKuUniZ6Bmy:-N_DxCKPDJ98uRcmMdnV:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L100)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

why not use isNotEmpty?
</blockquote></details>

Done.
___
*[`pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java` line 765 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_Duudl9dSxauFKitF0:-N_DxCt63DKyVxEgSwQb:bg861q6) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/PMSInputSetServiceImpl.java#L765)):*
<details><summary><i>Previously, adivishy1 (Adithya Viswanathan) wrote…</i></summary><blockquote>

are we setting default repo even if we have not set a default connector?

IMO, we should set default repo only if the default connector is set[default repo should be at a connector level instead of just the scope], else the selected connector might not have access to default repo
</blockquote></details>

These all settings are independent of each other with no co-relation. Purpose of each setting is to provide defaultValues, if the user misses some gitMetadata values while making call, to API. The various combination of failures, repo being incorrect, repo set but connector ref not present everything is already handled at GitService end.

**Comment by mohitg0795** [comment]
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_DxvyHCMjb_JtuGsTv:-N_DxvyHCMjb_JtuGsTw:bl8vvzn) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L94)):*
> ```Java
>   }
> 
>   public void setDefaultRepoForRemoteEntity(String accountIdentifier, String orgIdentifier, String projIdentifier) {
> ```

again "projIdentifier" used here !

**Review by senjucanon2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50475)* status: 8 file(s) to review. 1 change requests. 3. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java` line 94 at r2](https://reviewable.io/reviews/harness/harness-core/50475#-N_DxvyHCMjb_JtuGsTv:-N_DyRep4AAslnxx6VZv:b4kq5gg) ([raw file](https://github.com/harness/harness-core/blob/4cb3bce4c2e6ba64f5f8cf04b3b907f3075bdc5a/878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java#L94)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

again "projIdentifier" used here !
</blockquote></details>

Changed to projectIdentifier.

**Review by adivishy1 — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50475)* status: 8 file(s) to review. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by ankittiwari-harness — APPROVED** [review]

**Comment by senjucanon2** [comment]
trigger review

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
