### PR TITLE
[feat]: [PL-21198]: Hierarchical Resource Groups and Permissions

### PR DESCRIPTION
**Pull request by karansiwach360**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/30199)

### CODE REVIEW

**Review by gupta-utkarsh — APPROVED** [review]
:lgtm:

> Reviewed 26 of 46 files at r1, 31 of 32 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30199#-:-MuPF5xMByvwiFLnW8sn:bnfp4nl)* status: 60 file(s) to review. 1 of 2 approvals obtained.

**Review by reetika04 — APPROVED** [review]
:lgtm:

> Reviewed 26 of 46 files at r1, 29 of 32 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30199#-:-MuPFasY4cwtafSul8f8:bnfp4nl)* status: 2 file(s) to review.

**Review by reetika04 — APPROVED** [review]
> Reviewed 2 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/30199)* status: :shipit: complete! ✓

**Comment by karansiwach360** [comment]
trigger ft2

**Pull request merged**
