### PR TITLE
feat: [PL-24966]: Added bitbucket error handling and corresponding UTs

### PR DESCRIPTION
**Pull request by mohitg0795**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33389)

### CODE REVIEW

**Review by DeepakPatankar — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389)* status: 11 file(s) to review. 1 of 2 approvals obtained.

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389#-:-N2W7vPB2b6XnwZTcjPk:bnfp4nl)* status: :shipit: complete! ✓

**Review by ankit-harness — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389#-:-N2W8HSTAS9xyn-JMdE3:bnfp4nl)* status: :shipit: complete! ✓

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389)* status: :shipit: complete! ✓

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33389#-N2W947H-GRzA0PeANDS:-N2W947H-GRzA0PeANDT:boonp2t) ([raw file](https://github.com/harness/harness-core/blob/2e66f78e1e97bbc24e9f236875b816297c75f677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java#L35)):*
> ```Java
>             CREATE_FILE_REQUEST_FAILURE + INVALID_CONNECTOR_CREDS, new ScmUnauthorizedException(errorMessage));
>       case 404:
>         throw NestedExceptionUtils.hintWithExplanationException(REPO_NOT_FOUND,
> ```

what if branch is invalid or file is invalid

**Comment by mohitg0795** [comment]
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33389#-N2W947H-GRzA0PeANDS:-N2WCT_vAJVSFYb_jm66:bha8y5f) ([raw file](https://github.com/harness/harness-core/blob/2e66f78e1e97bbc24e9f236875b816297c75f677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, bhavya181 (Bhavya Agrawal) wrote…</i></summary><blockquote>

what if branch is invalid or file is invalid
</blockquote></details>

For create file use-case, there's no such case as branch not valid. Bitbucket automatically creates branch in such a case.

**Review by namanvermah — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389#-:-N2WHT8aA1JdDfIORaS4:bnfp4nl)* status: 1 change requests. 1. unresolved discussions.

**Review by bhavya181 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389)* status: :shipit: complete! ✓

___
*[`136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java` line 35 at r1](https://reviewable.io/reviews/harness/harness-core/33389#-N2W947H-GRzA0PeANDS:-N2Wd7rmEXTE0HpNxVH5:b-v8olbp) ([raw file](https://github.com/harness/harness-core/blob/2e66f78e1e97bbc24e9f236875b816297c75f677/136-git-sync-manager/src/main/java/io/harness/gitsync/common/scmerrorhandling/handlers/bitbucket/BitbucketCreateFileScmApiErrorHandler.java#L35)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

For create file use-case, there's no such case as branch not valid. Bitbucket automatically creates branch in such a case.
</blockquote></details>

what about invalid filePath?

**Review by bhavya181 — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33389)* status: :shipit: complete! ✓

**Pull request merged**
