### PR TITLE
feat: [CDS-58046]: Data Models for multi environment expansion handler

### PR DESCRIPTION
**Pull request by yogesh-chauhan**
- [fix]: [CDS-58046]: Add MultiEnvExpandedValue and tests
- [fix]: [CDS-58046]: Add MultiEnvExpandedValue and tests

## Describe your changes

Data model to describe the expanded json for multi environment i.e the "environments" key ( part of Deploy stage )
Sample "environments" yaml
```
environments:
    environmentRef: my_env
    infrastructureDefinitions:
    - identifier: my_infra
      inputs: ..
```

A sample json created corresponding to this new data model ( MultiEnvExpandedValue ) is attached below

```
[
    {
        "identifier": "my_env",
        "name": "my env",
        "type": "Production",
        "orgIdentifier": "org",
        "projectIdentifier": "proj",
        "infrastructures":
        [
            {
                "type": "KubernetesDirect",
                "spec":
                {
                    "namespace": "default",
                    "releaseName": "release_name",
                    "connector":
                    {
                        "name": "k8s",
                        "identifier": "k8s",
                        "type": "K8sCluster",
                        "spec":
                        {
                            "key": "value"
                        }
                    }
                }
            }
        ]
    }
]
```
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-58046]: https://harness.atlassian.net/browse/CDS-58046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-58046]: https://harness.atlassian.net/browse/CDS-58046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45646)

### CODE REVIEW

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Comment by yogesh-chauhan** [comment]
trigger messagecheck

**Review by hingerabhinav — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45646)* status: 9 file(s) to review. 1 of 2 approvals obtained.

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45646)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/pms/governance/SingleEnvironmentExpandedValue.java` line 22 at r2](https://reviewable.io/reviews/harness/harness-core/45646#-NRatwWZ96t5MAooJl5c:-NRatwW_3ZnXPQnBF3dk:b-r0ht6l) ([raw file](https://github.com/harness/harness-core/blob/547dae24d73cd1cd4f59dbe3203312380dcd44fb/125-cd-nextgen/src/main/java/io/harness/pms/governance/SingleEnvironmentExpandedValue.java#L22)):*
> ```Java
> @Data
> @Builder
> @FieldNameConstants(innerTypeName = "keys")
> ```

Todo: add test to make sure new fields are added here

**Comment by yogesh-chauhan** [comment]
trigger ut7

**Review by tchaurasiya — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45646)* status: :shipit: complete! ✓

**Pull request merged**
