### PR TITLE
fix: [CDS-37894]: Skip execution of Terraform plan if executing command fails

### PR DESCRIPTION
**Pull request by jelenaHarness**
## Describe your changes
If terraform command execution fails, do not attempt to apply the file.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)

### CODE REVIEW

**Review by yogesh-chauhan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 478 at r4](https://reviewable.io/reviews/harness/harness-core/33847#-N4fm6xB2Zt1M-s7iBN2:-N4fm6xB2Zt1M-s7iBN3:b-gkaqjm) ([raw file](https://github.com/harness/harness-core/blob/b3bc1feab7a5eb5b14ff9b5b7234a9861ed2a124/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L478)):*
> ```Java
>             .errorMessage("The terraform command exited with code " + code)
>             .build();
>       }
> ```

Skip execution of terraform apply if init command fails, 
The changes in the PR look different from the PR summary, is that correct @jelenaharness  ?

**Comment by jelenaHarness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 478 at r4](https://reviewable.io/reviews/harness/harness-core/33847#-N4fm6xB2Zt1M-s7iBN2:-N4ftf2N6cTRlJDK7zj3:bkdxjz4) ([raw file](https://github.com/harness/harness-core/blob/b3bc1feab7a5eb5b14ff9b5b7234a9861ed2a124/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L478)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

Skip execution of terraform apply if init command fails, 
The changes in the PR look different from the PR summary, is that correct @jelenaharness  ?
</blockquote></details>

@yogesh-chauhan I've updated the summary to reflect the changes

**Review by yogesh-chauhan — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: 1 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 574 at r4](https://reviewable.io/reviews/harness/harness-core/33847#-N5FMLOQ92Ipna3XIkQD:-N5FMLOQ92Ipna3XIkQE:bxy3bkd) ([raw file](https://github.com/harness/harness-core/blob/90d63f1f6e9440c68030329b56ae0732dd264b51/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L574)):*
> ```Java
>               .delegateTag(parameters.getDelegateTag())
>               .executionStatus(ExecutionStatus.SUCCESS)
>               .errorMessage("The terraform command exited with code " + code)
> ```

ideally the error message should be null, right ?

**Comment by jelenaHarness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 574 at r4](https://reviewable.io/reviews/harness/harness-core/33847#-N5FMLOQ92Ipna3XIkQD:-N5ZWFhf8okSkbemgOH7:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/90d63f1f6e9440c68030329b56ae0732dd264b51/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L574)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

ideally the error message should be null, right ?
</blockquote></details>

Done.

**Review by gaurav-jain1 — APPROVED** [review]

**Review by BogdanAtHarness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 

___
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 474 at r5](https://reviewable.io/reviews/harness/harness-core/33847#-N5nhO0h7PHpGpASVTnS:-N5nhO0h7PHpGpASVTnT:b-by5via) ([raw file](https://github.com/harness/harness-core/blob/875a9fd5f56eb5b483fbee33e7da6fa011c09612/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L474)):*
> ```Java
>         saveExecutionLog("Script execution finished with status: " + CommandExecutionStatus.FAILURE,
>             CommandExecutionStatus.FAILURE, INFO, logCallback);
>         return TerraformExecutionData.builder()
> ```

This return command returns substantially less information than the previous in case of failure. You sure the caller does not rely on some of these?

**Comment by jelenaHarness** [comment]
*[`930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java` line 474 at r5](https://reviewable.io/reviews/harness/harness-core/33847#-N5nhO0h7PHpGpASVTnS:-N5oBMycAxf6MKtZwipb:bsojdd) ([raw file](https://github.com/harness/harness-core/blob/875a9fd5f56eb5b483fbee33e7da6fa011c09612/930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java#L474)):*
<details><summary><i>Previously, BogdanAtHarness (Bogdan Azaric) wrote…</i></summary><blockquote>

This return command returns substantially less information than the previous in case of failure. You sure the caller does not rely on some of these?
</blockquote></details>

Yes, in case of failure the caller doesn't rely on these. In case of command being something other than 0, the terraform command execution failed, so only request parameters would actually contain any information.

**Review by BogdanAtHarness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: Some of the checks are too old. 1. unresolved discussions.

**Review by raghuAtWings — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: 1. unresolved discussions.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/33847)* status: :shipit: complete! ✓

**Pull request merged**
