### PR TITLE
[fix]: [DEL-4390]: Job queuing -- Start 500 jobs on a delegate at once and overwhelms it

### PR DESCRIPTION
**Pull request by raghuAtWings**
This reverts commit 00f058750b693b8602c3902389ffcf0206bbe1d4.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/34851)

### CODE REVIEW

**Review by gaurav-jain1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34851)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1949 at r2](https://reviewable.io/reviews/harness/harness-core/34851#-N6llKEB0N2jydsAkexk:-N6llKEB0N2jydsAkexl:bf2hn9k) ([raw file](https://github.com/harness/harness-core/blob/d4cdc9b67ef5fdcd3671fbb083546db65d64e5e8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1949)):*
> ```Java
> 
>         int perpetualTaskCount = 0;
>         if (perpetualTaskWorker != null) {
> ```

What's the reason behind having this limit ? If there are enough resource available, we should allow delegate to execute tasks.



_Code quote:_
```Java
        int perpetualTaskCount = 0;
        if (perpetualTaskWorker != null) {
          perpetualTaskCount = perpetualTaskWorker.getCurrentlyExecutingPerpetualTasksCount().intValue();
        }

        if (delegateTaskLimit > 0 && (currentlyExecutingFutures.size() + perpetualTaskCount) >= delegateTaskLimit) {
          log.info(
              "Delegate reached Delegate Size Task Limit of {}. It will not acquire this time.", delegateTaskLimit);
          return;
        }
```

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/34851)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 107 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V756W7wTMzkFDmjBB:-N8V6ytUEAf_yQEiDtIC:b-evc5dr) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L107)):*
> ```Java
>       while (iterator.hasNext()) {
>         DelegateTask delegateTask = iterator.next();
>         if (delegateTask.getBroadcastRound() >= MAX_BROADCAST_ROUND) {
> ```

can you move below block of code to private for readability purpose?

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7GVD-9aEx9ihZpLr:-N8V7GVE1DcyiHHOVcZq:b-74i4m0) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java#L3)):*
> ```Java
> package io.harness.delegate.beans;
> 
> public enum DelegateTaskExpiryReason {
> ```

kryo register for new enum?

**Comment by jennyjames21** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1975 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7VpLD8Inhej_Gb67:-N8V7VpLD8Inhej_Gb68:b-w1ucpm) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1975)):*
> ```Java
> 
>         if (delegateTaskLimit > 0 && (currentlyExecutingFutures.size() + perpetualTaskCount) >= delegateTaskLimit) {
>           log.info(
> ```

Error here(log.error)

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V6IrxEY73Iq5I-6ZX:-N8V7gReDPJ4W_6dLTfa:b-xi8juo) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L146)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Should this be inside below loop, even though you are checking same condition inside? As long this is verified it's fine. 
</blockquote></details>

below if statement

**Review by jennyjames21 — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/34851)* status: 1 change requests. 0 of 1 approvals obtained.

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1949 at r2](https://reviewable.io/reviews/harness/harness-core/34851#-N6llKEB0N2jydsAkexk:-N8jVryc85RVjx2VWeHN:bkhrfe8) ([raw file](https://github.com/harness/harness-core/blob/d4cdc9b67ef5fdcd3671fbb083546db65d64e5e8/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1949)):*
<details><summary><i>Previously, gaurav-jain1 (Gaurav Jain) wrote…</i></summary><blockquote>

What's the reason behind having this limit ? If there are enough resource available, we should allow delegate to execute tasks.
</blockquote></details>

this is a customer ask, they want to ensure that delegate doesn't die because of high cpu/memory usage

**Comment by raghuAtWings** [comment]
*[`260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java` line 1975 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7VpLD8Inhej_Gb67:-N8jW0X907O4dNAleWn1:b-xqa8j4) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java#L1975)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

Error here(log.error)
</blockquote></details>

its not actually an error

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V6IrxEY73Iq5I-6ZX:-N8jWeFY-G3cTF99e8Ss:b-5eoqkx) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L146)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

below if statement
</blockquote></details>

not following what you mean here

**Comment by raghuAtWings** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 107 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V756W7wTMzkFDmjBB:-N8jWhMvETSC9PQMkW8i:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L107)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

can you move below block of code to private for readability purpose?
</blockquote></details>

Done.

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7GVD-9aEx9ihZpLr:-N8jWjiK9XmBbtEBPz0t:b-mmwrzn) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java#L3)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

kryo register for new enum?
</blockquote></details>

this is never sent to over wire so not needed to register in kryo

**Comment by jennyjames21** [comment]
*[`400-rest/src/main/java/software/wings/app/DelegateQueueTask.java` line 146 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V6IrxEY73Iq5I-6ZX:-N8jt2x-87DSgbezJ3rj:bygxxdq) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/400-rest/src/main/java/software/wings/app/DelegateQueueTask.java#L146)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

not following what you mean here
</blockquote></details>

On prev implementation we are clearing alreadTriedDelegates set, then setting broadcastround count in db versus now you are setting broadcast count then clearing set and then incrementing.  Change in order. I think it's worth verifying this for sure. if you have a PR environment i can verify or will create one.

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7GVD-9aEx9ihZpLr:-N8jtsqt9QIyyoCKgX29:bphzbvz) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java#L3)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

this is never sent to over wire so not needed to register in kryo
</blockquote></details>

what about driver response back to microservices?  But i dont understand why kryo test didn't fail on PR.

**Comment by raghuAtWings** [comment]
trigger compile

**Comment by raghuAtWings** [comment]
trigger ft2

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java` line 3 at r4](https://reviewable.io/reviews/harness/harness-core/34851#-N8V7GVD-9aEx9ihZpLr:-N8k-wBmDOmX88UZU17A:b-2hg3xa) ([raw file](https://github.com/harness/harness-core/blob/2d5cc28e79121cc1b852b6be39c184e7ce4e2fae/420-delegate-service/src/main/java/io/harness/delegate/beans/DelegateTaskExpiryReason.java#L3)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

what about driver response back to microservices?  But i dont understand why kryo test didn't fail on PR.
</blockquote></details>

thats a fair point, i didn't test it it in NG. I guess there i will have to add

**Pull request closed without merging**
