### PR TITLE
fix: [CDS-42427]: Revert "removed the dependency on canaryDeletefqn and moving to stage to uniquely identify step using matrix looping strategy."

### PR DESCRIPTION
**Pull request by GoelPratyush99**
Reverts harness/harness-core#36948

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37407)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37407)

**Comment by GoelPratyush99** [comment]
MessageMetadata: trigger messagecheck

**Comment by GoelPratyush99** [comment]
Compile: trigger compile

**Comment by GoelPratyush99** [comment]
TI-bootstrap: trigger ti0
TI-bootstrap1: trigger ti1
TI-bootstrap2: trigger ti2
TI-bootstrap3: trigger ti3
TI-bootstrap4: trigger ti4

**Pull request merged**
