### PR TITLE
feat: [DEL-6066]: add FF integration and decryption using client

### PR DESCRIPTION
**Pull request by AnupamIO**
Add FF integration and decryption using client

Tested:
1- Tested on local using local FF and client FF. 
2- Tested connection to manager client from dms for decrypting delegate token.
3- Added a API containing delegateAuth and tested E2E flow.

**Pending**: 
DMS is non existent in pre-qa and qa. After setting it up on those env we will have to get an api-key for DMS to hit FF client.
For testing I used QA Manager API key.

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)

### CODE REVIEW

**Review by mdmilic — COMMENTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: Some of the checks are too old. 0 of 1 approvals obtained. Waiting on team(s): del-team. 

___
*[`400-rest/src/main/java/software/wings/resources/SecretManagerRessource.java` line 40 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx7O9tBhEz2Nc-SelW:-NTx7O9tBhEz2Nc-SelX:bf51te8) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/400-rest/src/main/java/software/wings/resources/SecretManagerRessource.java#L40)):*
> ```Java
>   @ExceptionMetered
>   @InternalApi
>   public RestResponse<String> getDelegateImageTag(@QueryParam("accountIdentifier") @NotEmpty String accountId,
> ```

change the method name
___
*[`419-delegate-service-app/config/config.yml` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx1xnoCpFjN3zzT203:-NTx1xnoCpFjN3zzT204:b-97juji) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/419-delegate-service-app/config/config.yml#L83)):*
> ```YAML
> 
> featureFlagConfig:
>   featureFlagSystem: LOCAL
> ```

Should this be CF (and maybe not the one in CG manager)
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/service/DelegateServiceDelegateSecretManagerImpl.java` line 14 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx6YBK1GdnAXGYShmb:-NTx6YBK1GdnAXGYShmc:b-rdcmyh) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/419-delegate-service-app/src/main/java/io/harness/dms/service/DelegateServiceDelegateSecretManagerImpl.java#L14)):*
> ```Java
> @RequiredArgsConstructor(onConstructor_ = @Inject)
> @Singleton
> public class DelegateServiceDelegateSecretManagerImpl extends DelegateSecretManager {
> ```

Maybe just call it DMSSecretManager or DelegateServiceSecretManager
___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx79kl3V_3SIewtLbS:-NTx79kl3V_3SIewtLbT:bmpsxqu) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L166)):*
> ```Java
>   private final HarnessConnectionPoolListener harnessConnectionPoolListener;
> 
>   private boolean overrideDelegateMigration = false;
> ```

What is this used for?
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/resource/DelegateServiceVersionInfoResource.java` line 46 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx6SMJ-0OQHo9MAof3:-NTx6SMJ-0OQHo9MAof4:b-wz8re0) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/419-delegate-service-app/src/main/java/io/harness/dms/resource/DelegateServiceVersionInfoResource.java#L46)):*
> ```Java
>   private final FeatureFlagService featureFlagService;
> 
>   private final DelegateSecretManagerClient delegateSecretManagerClient;
> ```

Doesn't seem to be used



_Code quote:_
```Java
  private final FeatureFlagService featureFlagService;

  private final DelegateSecretManagerClient delegateSecretManagerClient;
```
___
*[`419-delegate-service-app/src/main/java/io/harness/dms/resource/DelegateServiceVersionInfoResource.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx6MiC43IHNyJdKJ-B:-NTx6MiD6-o0N0qmbLhp:b-l6mwxj) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/419-delegate-service-app/src/main/java/io/harness/dms/resource/DelegateServiceVersionInfoResource.java#L70)):*
> ```Java
>     boolean ffValue = featureFlagService.isEnabled(FeatureName.USE_IMMUTABLE_DELEGATE, "kmpySmUISimoRrJL6NL73w");
>     System.out.print("Value of FF is" + ffValue);
>     System.out.println("checking value of string"
> ```

remove



_Code quote:_
```Java
    boolean ffValue = featureFlagService.isEnabled(FeatureName.USE_IMMUTABLE_DELEGATE, "kmpySmUISimoRrJL6NL73w");
    System.out.print("Value of FF is" + ffValue);
    System.out.println("checking value of string"
        + CGRestUtils.getResponse(
            delegateSecretManagerClient.fetchSecretValue("kmpySmUISimoRrJL6NL73w", "ogQyM9_kRguLaVmUERhioA")));
```

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: Some of the checks are too old. 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`419-delegate-service-app/config/config.yml` line 83 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx1xnoCpFjN3zzT203:-NXPNzJW-eJXKJcZ-huY:b-onvse7) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/419-delegate-service-app/config/config.yml#L83)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

Should this be CF (and maybe not the one in CG manager)
</blockquote></details>

both should be LOCAL, corrected to LOCAL in cg-manager as well.

**Review by AnupamIO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: Some of the checks are too old. 4 file(s) to review. 0 of 1 approvals obtained. 

___
*[`960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java` line 166 at r1](https://reviewable.io/reviews/harness/harness-core/45567#-NTx79kl3V_3SIewtLbS:-NXPR7LqCbt0C1Qb3lUk:bv07nnh) ([raw file](https://github.com/harness/harness-core/blob/c2addf7d0efaf66d800136ce74ce28a6a3366d2c/960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java#L166)):*
<details><summary><i>Previously, mdmilic (Marko Milic) wrote…</i></summary><blockquote>

What is this used for?
</blockquote></details>

While using any delegate related collection, we look for flag in harness db first which tells whether to use collection from harness db or DMS db. After that we store that in cache and query from respective DB.
Since here we don't have access to harness DB, hence adding this variable to ensure that we don't check for that flag and we always use collection from DMS DB.

**Comment by AnupamIO** [comment]
trigger uts

**Review by mdmilic — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: :shipit: complete! ✓

___
*[`419-delegate-service-app/src/main/java/io/harness/dms/service/DMSSecretManagerImpl.java` line 13 at r3](https://reviewable.io/reviews/harness/harness-core/45567#-NXQVgJa4_pHt6rzim2W:-NXQVgJa4_pHt6rzim2X:bmlqejn) ([raw file](https://github.com/harness/harness-core/blob/784639e334839e65478c422169139e2d267419b5/419-delegate-service-app/src/main/java/io/harness/dms/service/DMSSecretManagerImpl.java#L13)):*
> ```Java
> @Singleton
> public class DMSSecretManagerImpl extends DelegateSecretManager {
>   @Inject DelegateSecretManagerClient delegateSecretManagerClient;
> ```

make it private final
use constructor level injection
___
*[`420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateSecretManager.java` line 21 at r3](https://reviewable.io/reviews/harness/harness-core/45567#-NXQVm_N4mVCkjusmt7_:-NXQVm_N4mVCkjusmt7a:bjk9186) ([raw file](https://github.com/harness/harness-core/blob/784639e334839e65478c422169139e2d267419b5/420-delegate-service/src/main/java/io/harness/delegate/authenticator/DelegateSecretManager.java#L21)):*
> ```Java
> 
> public abstract class DelegateSecretManager {
>   @Inject FeatureFlagService featureFlagService;
> ```

Your implementation works, but it uses field level injection which is a big problem for testability (the code is not testable now unless you create mock Guice injections which we shouldn't do for unit tests as it's too slow)
To solve it, you should use @RequiredArgsConstructor here (with no juice injection) and in the subclass, create a custom constructor which takes all the params of that subclass + featureFlagService and annotate the constructor with @Inject. First line of the subclass constructor would be to invoke the `super(featureFlagService)` and the rest is standard field assignment.
Lombok can't generate the right constructors automatically for you when you have fields in super classes, so you have to do it manually.

**Review by mdmilic — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: :shipit: complete! ✓

**Review by mdmilic — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45567)* status: :shipit: complete! ✓

**Pull request closed without merging**
