### PR TITLE
[feat]: [CDS-41639]: add v2 endpoint

### PR DESCRIPTION
**Pull request by tmacari-harness**
## Describe your changes
[feat]: [CDS-41639]: add v2 endpoint

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

[CDS-41639]: https://harness.atlassian.net/browse/CDS-41639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/36263)

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/36263#-N96iO6o1ENVejMwY9b3:-N96iO6o1ENVejMwY9b4:bwc28a0) ([raw file](https://github.com/harness/harness-core/blob/6677d346dce88b79a33f41c3b6bc91b374ad9d65/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L96)):*
> ```Java
> 
>   @GET
>   @Path("repositoriesV2")
> ```

Path should be /v2/repositories (ref: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21063864229/Next+Gen+APIs+specification#Versioning-%26-Deprecation-of-API)

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/36263#-N96iO6o1ENVejMwY9b3:-N96lORtB6tUUrUbT6s9:b5xun0z) ([raw file](https://github.com/harness/harness-core/blob/6677d346dce88b79a33f41c3b6bc91b374ad9d65/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L96)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

Path should be /v2/repositories (ref: https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21063864229/Next+Gen+APIs+specification#Versioning-%26-Deprecation-of-API)
</blockquote></details>

I was thinking about it by everywhere else we add that  as suffix.
A little bit below: " @Path("getBuildDetailsV2")"
Also we're not deprecating previous endpoint V2 here means that those will be used  in some scenarios with v2 env/service.
@yogesh-chauhan what do you think?

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/36263#-N96iO6o1ENVejMwY9b3:-N96mvxt9rens57vQjdb:bpbkur5) ([raw file](https://github.com/harness/harness-core/blob/6677d346dce88b79a33f41c3b6bc91b374ad9d65/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L96)):*
<details><summary><i>Previously, tmacari-harness (Tudor Macari) wrote…</i></summary><blockquote>

I was thinking about it by everywhere else we add that  as suffix.
A little bit below: " @Path("getBuildDetailsV2")"
Also we're not deprecating previous endpoint V2 here means that those will be used  in some scenarios with v2 env/service.
@yogesh-chauhan what do you think?
</blockquote></details>

getBuildDetailsV2 is a very bad example of API path..

**Review by yogesh-chauhan — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 change requests. 1. unresolved discussions. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/36263#-N96iO6o1ENVejMwY9b3:-N96q6KxBmuDms2RqQI-:bewzadw) ([raw file](https://github.com/harness/harness-core/blob/6677d346dce88b79a33f41c3b6bc91b374ad9d65/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L96)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

getBuildDetailsV2 is a very bad example of API path.. 
</blockquote></details>

yeah I agree. getBuildDetailsV2 was an existing endpoint but as per versioning it should be /v2/repositories

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 96 at r1](https://reviewable.io/reviews/harness/harness-core/36263#-N96iO6o1ENVejMwY9b3:-N96xpd57LHSY0DNSQsU:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6677d346dce88b79a33f41c3b6bc91b374ad9d65/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L96)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

yeah I agree. getBuildDetailsV2 was an existing endpoint but as per versioning it should be /v2/repositories
</blockquote></details>

Done.

**Review by abosii-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/36263#-N96y6HHCrlgGo_IxXPg:-N96y6HHCrlgGo_IxXPh:b-x27wkb) ([raw file](https://github.com/harness/harness-core/blob/108aa050e683caa5cf760cf3678d5af2f7dcc22d/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L124)):*
> ```Java
>   @GET
>   @Path("v2/repositories")
>   @ApiOperation(value = "Gets ACR repositories", nickname = "getACRRepositories")
> ```

nickname should be unique otherwise it will fail for some UI processes 



_Code quote:_
```Java
nickname = "getACRRepositories"
```

**Review by tmacari-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: 1 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java` line 124 at r2](https://reviewable.io/reviews/harness/harness-core/36263#-N96y6HHCrlgGo_IxXPg:-N971T078Eq2pl8_UITx:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/108aa050e683caa5cf760cf3678d5af2f7dcc22d/120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/acr/AcrArtifactResource.java#L124)):*
<details><summary><i>Previously, abosii-harness (Alexandru Bosii) wrote…</i></summary><blockquote>

nickname should be unique otherwise it will fail for some UI processes 
</blockquote></details>

Done.

**Review by abosii-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/36263)* status: :shipit: complete! ✓

**Pull request merged**
