### PR TITLE
fix: [CDS-36968]: fix for parallel deployments using s3 helm chart

### PR DESCRIPTION
**Pull request by achyuth-harness**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)

### CODE REVIEW

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1D_W1S3Q9ePvEKk8oq:-N1D_W1S3Q9ePvEKk8or:b9k86an) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L283)):*
> ```Java
>     String bucketName = helmChartConfigParams.getHelmRepoConfig().getBucketName();
>     String repoName = helmChartConfigParams.getRepoName();
>     repoName = repoName + "-" + bucketName;
> ```

I would advise to create a new variable instead of re-using repoName. Also make bucketName and repoName as final
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/settings/helm/HelmRepoConfig.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1DaYKG1tB2OjLANggH:-N1DaYKHAUm7RX46N7po:br2rwta) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/950-delegate-tasks-beans/src/main/java/software/wings/beans/settings/helm/HelmRepoConfig.java#L25)):*
> ```Java
> 
>   default String getBucketName() {
>     return null;
> ```

maybe better to return ""

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: 3 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1D_W1S3Q9ePvEKk8oq:-N1DfvQNBXJkGeSgABiB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L283)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I would advise to create a new variable instead of re-using repoName. Also make bucketName and repoName as final
</blockquote></details>

Done.
___
*[`950-delegate-tasks-beans/src/main/java/software/wings/beans/settings/helm/HelmRepoConfig.java` line 25 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1DaYKG1tB2OjLANggH:-N1DfxBb0XPpZyJU_-Zr:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/950-delegate-tasks-beans/src/main/java/software/wings/beans/settings/helm/HelmRepoConfig.java#L25)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

maybe better to return ""
</blockquote></details>

Done.

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1D_W1S3Q9ePvEKk8oq:-N1Dm1ftESm7hf-Ors4T:by3rta9) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L283)):*
<details><summary><i>Previously, achyuth-harness (Achyuth Prakash) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please check what happens in case of http repos. We ideally do not want repo names ending with "-"

**Review by achyuth-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: 1 file(s) to review. 0 of 1 approvals obtained. 

___
*[`400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java` line 283 at r1](https://reviewable.io/reviews/harness/harness-core/32758#-N1D_W1S3Q9ePvEKk8oq:-N1Dmpxz7NGK_xvCtHDg:b-8xsdx5) ([raw file](https://github.com/harness/harness-core/blob/eca9cc09745f2aeed9361752397773bfe5a1ba60/400-rest/src/main/java/software/wings/delegatetasks/helm/HelmTaskHelper.java#L283)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

please check what happens in case of http repos. We ideally do not want repo names ending with "-"
</blockquote></details>

In case of Http Repo, the connector contains the repo url. so within that there can only be different charts (no question of buckets). thus, for http flow we have a difft method: fetchChartFromHttpServer 

only in case of s3/gcs we have a single connector which can reference multiple buckets and these in turn can have different charts

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: :shipit: complete! ✓

**Review by abosii-harness — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32758)* status: :shipit: complete! ✓

**Comment by achyuth-harness** [comment]
trigger messagecheck

**Pull request merged**
