### PR TITLE
feat: [CDS-42897]: Delete instances of deleted projects

### PR DESCRIPTION
**Pull request by vikyathharekal**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Vulnerability 1 Vulnerabilities 
 * Anti-pattern 1 Anti-patterns 

 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37266)

**Comment by vikyathharekal** [comment]
trigger messagecheck

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNR6Dd1B0OjKDFqPco:-NBNR6De7c6XQTlqyyjy:b-s4fk84) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L47)):*
> ```Java
>   @Override
>   public void migrate() {
>     log.info("Migrating instances belonging to deleted projects");
> ```

let's scope this to only a couple of accounts, before making it GA.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNRQu35FFB7_B0hrDJ:-NBNRQu35FFB7_B0hrDK:b-ieae6l) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L68)):*
> ```Java
>   private void deleteInstance(Project project) {
>     log.info("Deleting instances for account {} belonging to deleted project {}", project.getAccountIdentifier(),
>         project.getIdentifier());
> ```

let's log the mongo document ID of the project as well, to distinguish between projects with same name as well.
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNScsQ1Lr473oEjlaO:-NBNScsQ1Lr473oEjlaP:bobjsa2) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L70)):*
> ```Java
>         project.getIdentifier());
>     Query query = new Query(new Criteria()
>                                 .and(InstanceKeys.accountIdentifier)
> ```

is this correct.?
aren't we supposed to delete the instances which belong to the inframappingIds of the deleted project.?



_Code quote:_
```Java
                                .and(InstanceKeys.accountIdentifier)
                                .is(project.getAccountIdentifier())
                                .and(InstanceKeys.orgIdentifier)
                                .is(project.getOrgIdentifier())
                                .and(InstanceKeys.projectIdentifier)
                                .is(project.getIdentifier()));
```
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNSUVs-hYEfGAt9HY4:-NBNSUVs-hYEfGAt9HY5:b-ahqfq2) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L99)):*
> ```Java
>                         .is(infrastructureMapping.getId()));
>       InstanceSyncPerpetualTaskInfo instanceSyncPerpetualTaskInfo =
>           mongoTemplate.findOne(instanceSyncPerpetualTaskInfoQuery, InstanceSyncPerpetualTaskInfo.class);
> ```

is it possible to have multiple PTs for the criteria. Of so, would we not want to delete them all.

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 1 file(s) to review. 1 change requests. 4. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 47 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNR6Dd1B0OjKDFqPco:-NBNhk0Q0JH73i0pMOM1:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L47)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's scope this to only a couple of accounts, before making it GA.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 68 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNRQu35FFB7_B0hrDJ:-NBNhglm5cAxKR7PRs5B:bb6un1j) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L68)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's log the mongo document ID of the project as well, to distinguish between projects with same name as well.
</blockquote></details>

Done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 70 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNScsQ1Lr473oEjlaO:-NBNhc_GAHN2ol8V48h2:b-886gsx) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L70)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

is this correct.?
aren't we supposed to delete the instances which belong to the inframappingIds of the deleted project.?
</blockquote></details>

Fixed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 99 at r1](https://reviewable.io/reviews/harness/harness-core/37266#-NBNSUVs-hYEfGAt9HY4:-NBNhFWB-CeB1r6JRlDA:b-v68la4) ([raw file](https://github.com/harness/harness-core/blob/af07ac462a98f558f89c6e3c7e79dfd1bd2bde72/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L99)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

is it possible to have multiple PTs for the criteria. Of so, would we not want to delete them all.
</blockquote></details>

We have a unique index on infrastructureMappingId. There will be only one record.



_Code snippet:_
```Java
[
    {
        "v" : 2,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "ng-harness.instanceSyncPerpetualTasksInfoNG"
    },
    {
        "v" : 2,
        "unique" : true,
        "key" : {
            "infrastructureMappingId" : 1
        },
        "name" : "infrastructureMappingId_1",
        "ns" : "ng-harness.instanceSyncPerpetualTasksInfoNG"
    },
    {
        "v" : 2,
        "unique" : true,
        "key" : {
            "perpetualTaskId" : 1.0
        },
        "name" : "perpetualTaskId_1",
        "ns" : "ng-harness.instanceSyncPerpetualTasksInfoNG"
    }
]
```

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/37266#-NBNj99I5WM70LJuFGH9:-NBNj99J2DN4SFU7lEr3:b-wi59og) ([raw file](https://github.com/harness/harness-core/blob/c826f5435fe2a68a862b812cb99438e2eb01f2d2/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L72)):*
> ```Java
>           project.getAccountIdentifier(), project.getIdentifier(), project.getId(), infrastructureMapping.getId());
>       Query query =
>           new Query(new Criteria().and(InstanceKeys.infrastructureMappingId).is(infrastructureMapping.getId()));
> ```

let's also keep the account, org, project filter criteria as well, just to be extra safe here. :grimacing:

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/37266#-NBNj99I5WM70LJuFGH9:-NBQI4rn-XXyqckXlR0q:b-sy260r) ([raw file](https://github.com/harness/harness-core/blob/c826f5435fe2a68a862b812cb99438e2eb01f2d2/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L72)):*
<details><summary><i>Previously, shubham-in10se (Shubham Maheshwari) wrote…</i></summary><blockquote>

let's also keep the account, org, project filter criteria as well, just to be extra safe here. :grimacing: 
</blockquote></details>

We could add account and org filters. The project filter might not work as these instances are mapped to the new project and not this deleted one.

**Review by shubham-in10se — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 72 at r2](https://reviewable.io/reviews/harness/harness-core/37266#-NBNj99I5WM70LJuFGH9:-NBQngW46KFvdu97bzl1:bo47jks) ([raw file](https://github.com/harness/harness-core/blob/c826f5435fe2a68a862b812cb99438e2eb01f2d2/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L72)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We could add account and org filters. The project filter might not work as these instances are mapped to the new project and not this deleted one.
</blockquote></details>

right. I completely missed the project mapping part.
Let's at least add the accountId and orgId filters to the query.

**Review by shubham-in10se — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: :shipit: complete! ✓

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBR6Fts1C0YtaJMvrXp:-NBR6Fts1C0YtaJMvrXq:b-e1wgr0) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java#L26)):*
> ```Java
>   @Override
>   public boolean isBackground() {
>     return false;
> ```

looks like this is not a background migration

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBRBzjb0KZW9gz7fGMW:-NBRBlnjCB2uNup5_hX2:b-ephond) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L52)):*
> ```Java
>     log.info("Migrating instances belonging to deleted projects");
>     try {
>       List<AccountDTO> accounts = RestClientUtils.getResponse(accountClient.getAllAccounts());
> ```

I think we can get rid of the accounts call since we already have the accountIds

**Comment by yogesh-chauhan** [comment]
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBRKa5w1LAZJsZkXTZf:-NBRKa5w1LAZJsZkXTZg:b-uqyz99) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L97)):*
> ```Java
>     try {
>       Query instanceSyncPerpetualTaskInfoQuery =
>           new Query(new Criteria()
> ```

lets put accountId filter also

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBR6Fts1C0YtaJMvrXp:-NBRNA19EEIpadXlQq7U:b-7ql1td) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java#L26)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

looks like this is not a background migration
</blockquote></details>

fixed
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 52 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBRBzjb0KZW9gz7fGMW:-NBRN84i79GqRecdtPyX:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L52)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

I think we can get rid of the accounts call since we already have the accountIds 
</blockquote></details>

done
___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java` line 97 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBRKa5w1LAZJsZkXTZf:-NBRN5Ol14nz3iuiCQTM:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/DeleteInstanceOfDeletedProjects.java#L97)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

lets put accountId filter also
</blockquote></details>

done

**Review by vikyathharekal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37266)* status: 2 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java` line 26 at r4](https://reviewable.io/reviews/harness/harness-core/37266#-NBR6Fts1C0YtaJMvrXp:-NBRciIU8uGg09mmY8Pc:bb7f2mf) ([raw file](https://github.com/harness/harness-core/blob/8d8ac64a16a27d9329d8b9d450220cd778c3c191/125-cd-nextgen/src/main/java/io/harness/cdng/migration/CDMigrationDetails.java#L26)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

done

**Pull request merged**
