### PR TITLE
fix: [DEL-4963]: Separate Redis instance for delegate-related operation

### PR DESCRIPTION
**Pull request by jennyjames21**
## Describe your changes
Summary:
- Separate Redis instance for delegate-related operations and introduce separate Redis Config for delegate service.
- Distributed caching approach using Redisson Client RMap data structure
- Local Redis cache support using RLocalCachedMap
https://harness.atlassian.net/wiki/spaces/DEL/pages/21255423025/Dedicated+Redis+Instance+for+Delegate+Service

Test Performed
Sanity Test with disable flag to use Redis cache
         1) Delegate Installation - CG and NG
         2) K8 end to end flow - CG
         3) NG Pipeline execution

Delegate Cache 
- If flag enabled, Verify cache is present in Redis and value in hash
- Verify Delegate Cache fetch from Redis cache on read and refresh on every 1 minute
- Verify any update on Delegate entity reflects on UI/Redis cache
- Verify delete delegate updates the cache and remove from cache (pending)
- Verify task execution flow with delegate entity fetched from Redis

Delegate Group Cache
- Verify delegate groups cache are getting added to the Redis cache and value in hash
- Verify UI all delegates are displayed under the delegate group
- End to End Task execution with NG pipeline
- Verify list of selectors are displaying correctly in NG   

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)

### CODE REVIEW

**Comment by jennyjames21** [comment]
With EnableRedisCache
CG - K8 end to end - using DelegateCache
image

**Comment by jennyjames21** [comment]
WithRedisCacheEnabled 
DelegateGroupCache - Delegates are displayed under delegateGroup. 
image

List of selectors
image

**Comment by jennyjames21** [comment]
Verified key in PR Redis instance
image
image
Cache value stored as hash
image

**Comment by jennyjames21** [comment]
With RedisEnabled, NG pipeline execution 
image

**Comment by jennyjames21** [comment]
With disable DMS Redis cache,  Sanity test
1)K8 end to end flow
image
2) NG execution
image

**Review by archit-harness — COMMENTED** [review]
@piyush-harness @kshitij-harness as per delegate team scale testing, then shouldn't we also use RLocalCacheMap for caches inside other usecases?

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262#-:-NNZzQv889ChMPg4JHSa:b-3ojys9)* status: 50 file(s) to review. 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Comment by raghuAtWings** [comment]
*[`160-model-gen-tool/config-datagen.yml` line 324 at r6](https://reviewable.io/reviews/harness/harness-core/43262#-NN_AW0v7aElNf6Gj6v6:-NN_AW0v7aElNf6Gj6v7:b-hllmrl) ([raw file](https://github.com/harness/harness-core/blob/0dffaa8f31cfbc1e787e52b8f8e0bf14d9fe810d/160-model-gen-tool/config-datagen.yml#L324)):*
> ```YAML
>   envNamespace: ""
>   readMode: MASTER
>   nettyThreads: 16
> ```

what is this thread size for? this is not a blocking comment, just understand what it is and what size will make sense for our use case

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/BUILD.bazel` line 20 at r6](https://reviewable.io/reviews/harness/harness-core/43262#-NN_B-mV-lDZQP7m1wGK:-NN_B-mV-lDZQP7m1wGL:b-75ywm7) ([raw file](https://github.com/harness/harness-core/blob/0dffaa8f31cfbc1e787e52b8f8e0bf14d9fe810d/420-delegate-service/BUILD.bazel#L20)):*
> ```Starlark
>         "//867-polling-contracts:module",
>         "//870-cg-orchestration:module",
>         "//940-feature-flag:module",
> ```

why is this needed?

**Comment by raghuAtWings** [comment]
*[`420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/43262#-NN_BA1dEHLhvp0Lsqpr:-NN_BA1dEHLhvp0Lsqps:bu753fl) ([raw file](https://github.com/harness/harness-core/blob/0dffaa8f31cfbc1e787e52b8f8e0bf14d9fe810d/420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java#L44)):*
> ```Java
> 
>   @Override
>   public <K, V> RLocalCachedMap<K, V> getCache(
> ```

why have it if returning null?

**Review by raghuAtWings — COMMENTED** [review]
> Reviewed 5 of 20 files at r1, 4 of 37 files at r2, 20 of 27 files at r4, 16 of 19 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)* status: 0 of 1 approvals obtained. Waiting on team(s): del-team.

**Review by ankit-harness — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)* status: 6 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 561 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjUyV548GC9Fud8QJf:-NNjUyV548GC9Fud8QJg:b-dlouhj) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L561)):*
> ```Java
>   @Singleton
>   @Named("redissonClient")
>   RedissonClient redissonClient() {
> ```

Why is there a need for change in modules outside of CG Manager? My assumption is Delegate code is all contained with-in CG manager
___
*[`360-cg-manager/config.yml` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjVqqx-S-hLRLce4Z5:-NNjVqqx-S-hLRLce4Z6:b4f0lme) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/360-cg-manager/config.yml#L134)):*
> ```YAML
> distributedLockImplementation: REDIS
> 
> redisConfig:
> ```

1. Which Redis instance would we use for Delegate? We do have redisAtmosphereConfig which is used or Delegate Broadcasting. Can't we use the same Redis instance. This will make sure there is a single Redis instance for all Delegate needs.
2. Can we rename it to redisDelegateConfig

**Review by archit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)* status: 6 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`360-cg-manager/config.yml` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjVqqx-S-hLRLce4Z5:-NNjmbTrDHqk7PR8BgrX:b-tglh51) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/360-cg-manager/config.yml#L134)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

1. Which Redis instance would we use for Delegate? We do have redisAtmosphereConfig which is used or Delegate Broadcasting. Can't we use the same Redis instance. This will make sure there is a single Redis instance for all Delegate needs.
2. Can we rename it to redisDelegateConfig
</blockquote></details>

@ankit-harness if delegate did scale testing on using RlocalCachemap then shouldn't our other cache also move towards it?

**Comment by jennyjames21** [comment]
*[`360-cg-manager/config.yml` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjVqqx-S-hLRLce4Z5:-NNnVmZX2LY9osCkdQuf:b4t4tib) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/360-cg-manager/config.yml#L134)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

@ankit-harness if delegate did scale testing on using RlocalCachemap then shouldn't our other cache also move towards it?
</blockquote></details>

@ankit-harness We are creating a new Redis instance(Memstore) dedicated to delegate-related operations. Currently 
 redisAtmosphereConfig points to manager one. We are planning to move Atmosphere Redis also to this new instance eventually, last phase of rolling out. 

i will update to RedisDelegateConfig

**Comment by jennyjames21** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 561 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjUyV548GC9Fud8QJf:-NNoOu6F0m5trGZtEhDQ:bikpvbo) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L561)):*
<details><summary><i>Previously, ankit-harness (Ankit Singhal) wrote…</i></summary><blockquote>

Why is there a need for change in modules outside of CG Manager? My assumption is Delegate code is all contained with-in CG manager
</blockquote></details>

that's right, let me recheck this, probably added due to juice error

**Comment by jennyjames21** [comment]
*[`420-delegate-service/BUILD.bazel` line 20 at r6](https://reviewable.io/reviews/harness/harness-core/43262#-NN_B-mV-lDZQP7m1wGK:-NNoP4e5-tn30UN4tJU4:b-a7vwhy) ([raw file](https://github.com/harness/harness-core/blob/0dffaa8f31cfbc1e787e52b8f8e0bf14d9fe810d/420-delegate-service/BUILD.bazel#L20)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

added by mistake

**Comment by jennyjames21** [comment]
*[`420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java` line 44 at r6](https://reviewable.io/reviews/harness/harness-core/43262#-NN_BA1dEHLhvp0Lsqpr:-NNoP7Mo0ZfaFlTdC7h1:b-hfpv0l) ([raw file](https://github.com/harness/harness-core/blob/0dffaa8f31cfbc1e787e52b8f8e0bf14d9fe810d/420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java#L44)):*
<details><summary><i>Previously, raghuAtWings (Raghvendra Singh) wrote…</i></summary><blockquote>

why have it if returning null?
</blockquote></details>

removed

**Comment by jennyjames21** [comment]
*[`360-cg-manager/config.yml` line 134 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjVqqx-S-hLRLce4Z5:-NOScryI5Bz-aMR6EQfx:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/360-cg-manager/config.yml#L134)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

@ankit-harness We are creating a new Redis instance(Memstore) dedicated to delegate-related operations. Currently 
 redisAtmosphereConfig points to manager one. We are planning to move Atmosphere Redis also to this new instance eventually, last phase of rolling out. 

i will update to RedisDelegateConfig


</blockquote></details>

updated

**Comment by jennyjames21** [comment]
*[`120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java` line 561 at r7](https://reviewable.io/reviews/harness/harness-core/43262#-NNjUyV548GC9Fud8QJf:-NOScvvN2VRwq0VdG5Yk:bvnrpcm) ([raw file](https://github.com/harness/harness-core/blob/87aaeb1055b1aa533f0b937803bb6d6869aeb97c/120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java#L561)):*
<details><summary><i>Previously, jennyjames21 (Jenny James) wrote…</i></summary><blockquote>

that's right, let me recheck this, probably added due to juice error
</blockquote></details>

updated

**Review by piyush-harness — APPROVED** [review]
> Reviewed 4 of 37 files at r2, 20 of 27 files at r4, 6 of 19 files at r5, 3 of 5 files at r6, 2 of 3 files at r8, 17 of 17 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)* status: Some of the checks are too old. 1 change requests. 4. unresolved discussions.

**Comment by piyush-harness** [comment]
:lgtm:

**Review by mdmilic — APPROVED** [review]
> Reviewed 4 of 37 files at r2, 20 of 27 files at r4, 5 of 19 files at r5, 3 of 5 files at r6, 2 of 3 files at r8, 8 of 17 files at r9, 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/43262)* status: 1 change requests. 4. unresolved discussions. 

___
*[`420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java` line 28 at r10](https://reviewable.io/reviews/harness/harness-core/43262#-NOzE2b14GC1aLdGqH5D:-NOzE2b14GC1aLdGqH5E:b-smdkb4) ([raw file](https://github.com/harness/harness-core/blob/75128225b545f81d0ca1289a7dca9a720bb5da02/420-delegate-service/src/main/java/io/harness/redis/impl/DelegateRedissonCacheManagerImpl.java#L28)):*
> ```Java
> public class DelegateRedissonCacheManagerImpl implements DelegateRedissonCacheManager {
>   @Inject @Named("redissonClient") RedissonClient redissonClient;
>   private RedisConfig redisConfig;
> ```

Remove this @Inject and make both fields `private final`



_Code quote:_
```Java
  @Inject @Named("redissonClient") RedissonClient redissonClient;
  private RedisConfig redisConfig;
```
___
*[`420-delegate-service/src/main/java/io/harness/redis/intfc/DelegateRedissonCacheManager.java` line 20 at r10](https://reviewable.io/reviews/harness/harness-core/43262#-NOzEKuI4V4JpYO6B9hq:-NOzEKuI4V4JpYO6B9hr:b-biy7yp) ([raw file](https://github.com/harness/harness-core/blob/75128225b545f81d0ca1289a7dca9a720bb5da02/420-delegate-service/src/main/java/io/harness/redis/intfc/DelegateRedissonCacheManager.java#L20)):*
> ```Java
> 
> @OwnedBy(DEL)
> @ImplementedBy(DelegateRedissonCacheManagerImpl.class)
> ```

What is the use of this annotation? It will cause circular dependency when we try to break this module into package level bazel targets. i.e. because of that annotation, this intfc depends on the implementation and implementation depends on intfc. This would only work if they are both in the same java package (once we start breaking things up)
___
*[`420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java` line 23 at r10](https://reviewable.io/reviews/harness/harness-core/43262#-NOzFMVB3_iQVtMKXRoP:-NOzFMVB3_iQVtMKXRoQ:b-u7228q) ([raw file](https://github.com/harness/harness-core/blob/75128225b545f81d0ca1289a7dca9a720bb5da02/420-delegate-service/src/main/java/io/harness/serializer/kryo/DelegateServiceKryoRegister.java#L23)):*
> ```Java
>     kryo.register(PerpetualTaskClientContext.class, 40030);
>     kryo.register(Delegate.class, 40031);
>     kryo.register(DelegateCapacity.class, 5808);
> ```

Why this change? Your change doesn't seem to be related to kryo
___
*[`420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java` line 67 at r10](https://reviewable.io/reviews/harness/harness-core/43262#-NP-HFz_5Do72IBELFTH:-NP-HFza6iVchlVtQV-2:b-qhbrx8) ([raw file](https://github.com/harness/harness-core/blob/75128225b545f81d0ca1289a7dca9a720bb5da02/420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java#L67)):*
> ```Java
>   @Inject private DelegateTaskMigrationHelper delegateTaskMigrationHelper;
> 
>   @Inject @Named(DELEGATE_CACHE) RLocalCachedMap<String, Delegate> delegateRedisCache;
> ```

Seems like redis mode doesn't have much in common with old local cache mode. Not blocking, but if you need to change other stuff as well, it would reduce complexity if you actually created entire separate implementation of the DelegateCache interface (e.g. RedisDelegateCacheImpl). Then based on the `enableRedisForDelegateService` flag (which I understand you get from config anyway and you can't/shouldn't change it dynamically) guice up either one or the other implementation.

**Comment by jennyjames21** [comment]
checked in PR https://github.com/harness/harness-core/pull/43898

**Pull request closed without merging**
