### PR TITLE
feat: [IDP-1174]: Bitbucket Data Source

### PR DESCRIPTION
**Pull request by vigneswara-propelo**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/53111)

### CODE REVIEW

**Review by vikyathharekal — COMMENTED** [review]
> Reviewed 10 of 27 files at r1, 1 of 6 files at r2, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53111)* status: 33 file(s) to review. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketIsBranchProtectedParser.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-Neve1CBEGQYoiOukVVP:-Neve1CBEGQYoiOukVVQ:b-cw63pr) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketIsBranchProtectedParser.java#L38)):*
> ```Java
>           (List<Map<String, Object>>) CommonUtils.findObjectByName(inputValueData, "values");
>       if (isEmpty(values)) {
>         dataPointData.putAll(constructDataPointInfo(inputValue, false, null));
> ```

The check will fail in this case, right? Should we add an error message? "Could not find branch protection information" or something similar.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevexCfATlFHZEd_HBB:-NevexCfATlFHZEd_HBC:b-ookc0w) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java#L46)):*
> ```Java
>         continue;
>       }
>       int numberOfPullRequests = 0;
> ```

values.size() would give us this number. we might not have to compute it explicitly 



_Code quote:_
```Java
numberOfPullRequests
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevfCqFCq8Zf5BMAi0s:-NevfCqFCq8Zf5BMAi0t:bby30nf) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java#L57)):*
> ```Java
> 
>       long value = 0;
>       if (numberOfPullRequests != 0) {
> ```

We have a check for isEmpty(). So this check would be always true.
Same would be applicable for corresponding github parser



_Code quote:_
```Java
if (numberOfPullRequests != 0) {
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevfvGg-l4LkyNOG_OU:-NevfvGg-l4LkyNOG_OV:bmkejb2) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java#L75)):*
> ```Java
>       Map<DataPointEntity, String> dataPointAndInputValueToFetch = new HashMap<>() {
>         { put(dataPoint, inputValue); }
>       };
> ```

This is getting flagged by sonar. How about using Map.of(dataPoint, inputValue)?



_Code quote:_
```Java
      Map<DataPointEntity, String> dataPointAndInputValueToFetch = new HashMap<>() {
        { put(dataPoint, inputValue); }
      };
```
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-Nevg8tH5UyNBa0FJfb4:-Nevg8tH5UyNBa0FJfb5:bfli5hg) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java#L89)):*
> ```Java
>         inputValueData.put(ERROR_MESSAGE_KEY, ((ResponseMessage) response.getEntity()).getMessage());
>       } else {
>         inputValueData.put(DSL_RESPONSE,
> ```

Shouldn't we populate the ERROR_MESSAGE_KEY instead? This would be for 4xx.



_Code quote:_
```Java
DSL_RESPONSE
```

**Review by vigneswara-propelo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53111)* status: 33 file(s) to review. 5. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketIsBranchProtectedParser.java` line 38 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-Neve1CBEGQYoiOukVVP:-NevoIyM3XOHfPjCBBrN:b55l2dh) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketIsBranchProtectedParser.java#L38)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

The check will fail in this case, right? Should we add an error message? "Could not find branch protection information" or something similar.
</blockquote></details>

If its empty then it means that the branch is not protected. 
Ideally, we should be populating default failure message that was provided by the user
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java` line 46 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevexCfATlFHZEd_HBB:-Nevor0o2iJ6HaODfEXa:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java#L46)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

values.size() would give us this number. we might not have to compute it explicitly
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java` line 57 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevfCqFCq8Zf5BMAi0s:-NevoqXRA6RouG_956HL:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datapoints/parser/BitbucketMeanTimeToMergeParser.java#L57)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

We have a check for isEmpty(). So this check would be always true.
Same would be applicable for corresponding github parser
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java` line 75 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-NevfvGg-l4LkyNOG_OU:-Nevq08mBiHthRS8mI-R:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java#L75)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

This is getting flagged by sonar. How about using Map.of(dataPoint, inputValue)?
</blockquote></details>

Done.
___
*[`idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java` line 89 at r3](https://reviewable.io/reviews/harness/harness-core/53111#-Nevg8tH5UyNBa0FJfb4:-Nevq0fH53rgkxGKl8vT:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/0f4b981f828a59cfbed29aa9379d4f99b6689921/idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/BitbucketIsBranchProtectionSetDsl.java#L89)):*
<details><summary><i>Previously, vikyathharekal (Vikyath Harekal) wrote…</i></summary><blockquote>

Shouldn't we populate the ERROR_MESSAGE_KEY instead? This would be for 4xx.
</blockquote></details>

Done.

**Review by vikyathharekal — DISMISSED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53111)* status: 33 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger ut1, ut4

**Comment by vigneswara-propelo** [comment]
trigger uts

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by vikyathharekal — APPROVED** [review]
> Reviewed 22 of 23 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/53111)* status: 36 file(s) to review. 1 of 2 approvals obtained.

**Comment by vigneswara-propelo** [comment]
trigger uts

**Review by devesh-harness — APPROVED** [review]

**Comment by vigneswara-propelo** [comment]
trigger review

**Pull request merged**
