### PR TITLE
[feat]: [CDS-75249]: Restrict the maximum number of nested levels in …

### PR DESCRIPTION
**Pull request by brijeshdhakar**
…nodeExecution and do now allow to start the nodeExecution if it breaches the limit

Screenshot of the error that will be shown to UI when this limit is reached.
Screenshot 2023-07-26 at 1 26 47 PM

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)* status: 5 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/50927#-NaA7yRU9tCNR_4d3WKs:-NaA7yRU9tCNR_4d3WKt:bia9kiy) ([raw file](https://github.com/harness/harness-core/blob/6f0383bc0dd208fdf5321b1028058e58d5aa11a2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L374)):*
> ```Java
>     if (ambiance.getLevelsCount() > orchestrationRestrictionConfiguration.getMaxNestedLevelsCount()) {
>       return ExecutionCheck.builder()
>           .proceed(false)
> ```

can we move this inside RunPreFacilitationChecker
___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 376 at r1](https://reviewable.io/reviews/harness/harness-core/50927#-NaA81Ie9yVhrC9oyTla:-NaA81Ie9yVhrC9oyTlb:b-e4tb4x) ([raw file](https://github.com/harness/harness-core/blob/6f0383bc0dd208fdf5321b1028058e58d5aa11a2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L376)):*
> ```Java
>           .proceed(false)
>           .reason(
>               "The pipeline has reached the maximum nesting allowed for an execution. Please simplify the pipeline configuration so that it does not breach the allowed limit of nesting")
> ```

Lets get this message reviewed from @SudarshanPurohit 



_Code quote:_
```Java
The pipeline has reached the maximum nesting allowed for an execution. Please simplify the pipeline configuration so that it does not breach the allowed limit of nesting
```

**Review by hextechpal — APPROVED** [review]

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by brijeshdhakar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)* status: 7 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java` line 374 at r1](https://reviewable.io/reviews/harness/harness-core/50927#-NaA7yRU9tCNR_4d3WKs:-NaAclbW2AxCvtLMS-FB:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/6f0383bc0dd208fdf5321b1028058e58d5aa11a2/pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode/PlanNodeExecutionStrategy.java#L374)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

can we move this inside RunPreFacilitationChecker
</blockquote></details>

Done.

**Comment by brijeshdhakar** [comment]
trigger ut1 ut5 ut9

**Comment by brijeshdhakar** [comment]
trigger ut5

**Comment by brijeshdhakar** [comment]
trigger ut5

**Review by archit-harness — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)* status: 7 file(s) to review. 1 of 2 approvals obtained.

**Comment by brijeshdhakar** [comment]
trigger ut6 ut7

**Comment by brijeshdhakar** [comment]
trigger ut7

**Review by prashantsharma04 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/50927)* status: :shipit: complete! ✓

**Comment by brijeshdhakar** [comment]
trigger review

**Pull request merged**
