### PR TITLE
[fix]: [PL-29896]: restrict CG 2FA email for SCIM & LDAP NG user invite flow

### PR DESCRIPTION
**Pull request by kapil-harness**
## Describe your changes
restrict CG 2FA email for SCIM & LDAP NG user invite flow

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40392)

### CODE REVIEW

**Comment by kapil-harness** [comment]
trigger messagecheck

**Review by pbarapatre10 — COMMENTED** [review]
Is this working well with/without any FFs? AUTO_SAML_ACCEPT & PL_NO_EMAIL? 
Also, for other cases: Manual invite user, OAuth, etc., the behaviour is correct and consistent with CG? 

Thanks

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40392#-:-NHD9nmm353ElmAU-JJq:b3dvk80)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Review by kapil-harness — COMMENTED** [review]
Thanks for the thorough review.
All the scenarios mentioned in the table in this doc have been successfully tested, for both CG and NG.
I think we are good here.
https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21199980172/User+Invite+Flow+Behaviour

> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40392#-:-NHEBLtv0UUluzy9MJb7:b-p35j7a)* status: 1 file(s) to review. 0 of 2 approvals obtained.

**Review by pbarapatre10 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40392)* status: 1 file(s) to review. 1 of 2 approvals obtained.

**Review by shashank-harness — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40392)* status: :shipit: complete! ✓

**Pull request merged**
