### PR TITLE
feat: [CDS-36902]: Service env refactoring feat ( do not merge )

### PR DESCRIPTION
**Pull request by prashantsharma04**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/32811)

### CODE REVIEW

**Comment by prashantsharma04** [comment]
do-not-merge

**Comment by prashantsharma04** [comment]
trigger ti0

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 4 files at r3, 1 of 4 files at r20, 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/32811)* status: Waiting on team(s): sto.

**Pull request merged**
