### PR TITLE
[feat]: [CCM-9676]: Migration to support Budget Breakdown toggle

### PR DESCRIPTION
**Pull request by iamanmolm**
## Describe your changes
Since we are adding a new object/field for yearly budgets, we are filling the already existing budget of customer with default breakdown value as "YEARLY". So, this migration is meant for same.

## Checklist
- [x] I've documented the changes in the PR description.
- [x] I've tested this change either in PR or local environment.
- [x] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
    - CodeFormat: `trigger codeformat`
    - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- Trigger all Checks: `trigger smartchecks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/40660)

### CODE REVIEW

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40660)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/40660#-NHiQyXF0hklGcDoigir:-NHiQyXF0hklGcDoigis:b4gk9iy) ([raw file](https://github.com/harness/harness-core/blob/c15c42856af2fdd89c7220409170b6903c5e92ff/ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java#L51)):*
> ```Java
> 
>   private void migrateBudgetBreakdownObject(final Budget budget) {
>     modifyBudget(budget);
> ```

Why are we doing this additional operation of setting budget monthly breakdown in the budget object? Can't we have updateBudgetMonthlyBreakdown take budgetId and budgetMonthlyBreakdown as input?

**Review by svmav — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40660)* status: 3 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/40660#-NHiRS433fL61ebZgXnG:-NHiRS433fL61ebZgXnH:bczqexn) ([raw file](https://github.com/harness/harness-core/blob/c15c42856af2fdd89c7220409170b6903c5e92ff/ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java#L39)):*
> ```Java
>         // For every budget we are adding default breakdown as YEARLY
>         try {
>           migrateBudgetBreakdownObject(budget);
> ```

Note that you are setting BudgetBreakdown as YEARLY for every budget. This might also impact some test budgets that you have created with BudgetBreakdown as MONTHLY.

**Review by iamanmolm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40660)* status: 3 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/40660#-NHiRS433fL61ebZgXnG:-NHiRypdEqXJ6VkvyV3l:b-c9msi7) ([raw file](https://github.com/harness/harness-core/blob/c15c42856af2fdd89c7220409170b6903c5e92ff/ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java#L39)):*
<details><summary><i>Previously, svmav (Shubhanshu Verma) wrote…</i></summary><blockquote>

Note that you are setting BudgetBreakdown as YEARLY for every budget. This might also impact some test budgets that you have created with BudgetBreakdown as MONTHLY.
</blockquote></details>

I tried that, it safely converted those test budgets to YEARLY breakdown budgets.
___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java` line 51 at r1](https://reviewable.io/reviews/harness/harness-core/40660#-NHiQyXF0hklGcDoigir:-NHiTu4U5sHE2JqPrp6r:b-896fix) ([raw file](https://github.com/harness/harness-core/blob/c15c42856af2fdd89c7220409170b6903c5e92ff/ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java#L51)):*
<details><summary><i>Previously, svmav (Shubhanshu Verma) wrote…</i></summary><blockquote>

Why are we doing this additional operation of setting budget monthly breakdown in the budget object? Can't we have updateBudgetMonthlyBreakdown take budgetId and budgetMonthlyBreakdown as input?
</blockquote></details>

Done.

**Review by svmav — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/40660)* status: :shipit: complete! ✓

___
*[`ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java` line 39 at r1](https://reviewable.io/reviews/harness/harness-core/40660#-NHiRS433fL61ebZgXnG:-NHwZhUbAouIcWts5IJH:b36l748) ([raw file](https://github.com/harness/harness-core/blob/c15c42856af2fdd89c7220409170b6903c5e92ff/ce-nextgen/service/src/main/java/io/harness/ccm/migration/BudgetAddBreakdownMigration.java#L39)):*
<details><summary><i>Previously, iamanmolm (Anmol Maheshwari) wrote…</i></summary><blockquote>

I tried that, it safely converted those test budgets to YEARLY breakdown budgets.
</blockquote></details>

That's not what I meant, but anyways its fine.

**Pull request merged**
