### PR TITLE
feat: [CDS-85164]: remove multi threading for remote YAML metadata for service/env

### PR DESCRIPTION
**Pull request by hingerabhinav**
## Describe your changes
remove multi threading for service / environment inputs fetching. 
there was a race condition between threads for git sync branch context. 
So we're removing the logic for now and relying on Load-From-Cache and Bi-directional sync for UX. Will revisit this if load increases. 

Tested:
1. multi service inputs with dynamic and static linking 
2. multi env inputs with dynamic and static linking
3. infra inputs 

image
image
image

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)

### CODE REVIEW

**Comment by hingerabhinav** [comment]
trigger compile, uts

**Comment by hingerabhinav** [comment]
trigger compile, uts

**Review by mohitg0795 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 947 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjqqPeU8WEegtMuyIYb:-NjqqPeU8WEegtMuyIYc:b-z0vjav) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L947)):*
> ```Java
>           loadFromCache);
>     } catch (WingsException ex) {
>       log.error(String.format("Error while getting environment inputs: %s", serviceRefs), ex);
> ```

this is confusing : in log it says "getting environment inputs" and we are logging servicerefs?

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 947 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjqqPeU8WEegtMuyIYb:-NjrI0Od33Jcd0L4IS-v:b8j7j0s) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L947)):*
<details><summary><i>Previously, mohitg0795 (Mohit Garg) wrote…</i></summary><blockquote>

this is confusing : in log it says "getting environment inputs" and we are logging servicerefs?
</blockquote></details>

@hingerabhinav I think we should log both serviceRefs & environmentRefs

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 969 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjrIIrVAepFTNaAC123:-NjrIIrVAepFTNaAC124:b-w7vrte) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L969)):*
> ```Java
>         fetchesNonDeletedEnvironmentFromListOfRefs(accountIdentifier, orgIdentifier, projectIdentifier, envRefs);
> 
>     for (int i = 0; i < environmentEntities.size(); i += REMOTE_ENVIRONMENTS_BATCH_SIZE) {
> ```

do we even need batching then ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)* status: 2 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 911 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjrIVVs-2g0VK9c7sro:-NjrIVVs-2g0VK9c7srp:b-w7vrte) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L911)):*
> ```Java
>         getScopedServiceEntities(accountIdentifier, orgIdentifier, projectIdentifier, serviceRefs);
> 
>     for (int i = 0; i < serviceEntities.size(); i += REMOTE_SERVICE_BATCH_SIZE) {
> ```

do we even need batching then ?

**Review by hingerabhinav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 947 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjqqPeU8WEegtMuyIYb:-Njs73oA-fcKp01sKGJ_:bs7wumx) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L947)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

@hingerabhinav I think we should log both serviceRefs & environmentRefs
</blockquote></details>

Done. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 969 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjrIIrVAepFTNaAC123:-Njs75UoBHcIBSCRudvP:b-h5pthf) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L969)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we even need batching then ?
</blockquote></details>

Yes. We dont need it. We added to space out remote calls for thread pool. 
___
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java` line 911 at r2](https://reviewable.io/reviews/harness/harness-core/55760#-NjrIVVs-2g0VK9c7sro:-Njs7D398nF4-UrSeXPn:b-h5pthf) ([raw file](https://github.com/harness/harness-core/blob/80bedce6232ea599ccb3cef7eda15b235bc539c7/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java#L911)):*
<details><summary><i>Previously, yogesh-chauhan (Yogesh Chauhan) wrote…</i></summary><blockquote>

do we even need batching then ?
</blockquote></details>

Yes. We dont need it. We added to space out remote calls for thread pool.

**Comment by hingerabhinav** [comment]
trigger uts

**Comment by yogesh-chauhan** [comment]
*[`127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java` line 956 at r3](https://reviewable.io/reviews/harness/harness-core/55760#-NjurpPRDp0wOtIyesUU:-NjurpPRDp0wOtIyesUV:b807fqw) ([raw file](https://github.com/harness/harness-core/blob/f5c89a73dd3b27fb9c08f620e0fd549bbacd8941/127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java#L956)):*
> ```Java
>           ex);
>       throw new InternalServerErrorException(
>           String.format("Unexpected error occurred while getting environment inputs for envs: %s: [%s]", envRefs,
> ```

same message update here ?

**Review by yogesh-chauhan — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 0 of 2 approvals obtained.

**Review by yogesh-chauhan — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/55760)* status: 2 file(s) to review. 1 change requests. 1. unresolved discussions. 1 of 2 approvals obtained.

**Review by mohitg0795 — APPROVED** [review]

**Comment by hingerabhinav** [comment]
trigger review

**Pull request merged**
