### PR TITLE
feat: [CDS-78733]: add adviser for retry step group failure strategy

### PR DESCRIPTION
**Pull request by shalini-agr**
## Describe your changes

**Changes:** Add adviser for retry step group failure strategy in v1.

**Testing:** Tested that the retry step group failure strategy is now working with v1 yaml.

https://github.com/harness/harness-core/assets/97503816/71e2a3e9-de39-4943-8039-315426e6de26

Tested with following yaml:
```
version: 1
name: testHttpV1
stages:
    - name: custom2
      type: Custom
      spec: 
        steps:
          - name: group
            type: group
            spec:
              steps:
                - name: http
                  type: Http
                  desc: my http step 
                  id: http2
                  spec:
                    url: httpsss://www.dummyurl.com
                    method: GET
                    inputVariables: []
                    headers: []
                    outputVariables: []
                    requestBody: null
                  timeout: 10s
                  when: true
                  on: 
                    failure:
                      - errors:
                          - authorization
                        type: retry
                        spec: 
                          attempts: 1
                          interval: 10s
                          on_failure:
                            type: manual-intervention
                            spec:
                              timeout: 10s
                              timeout_action:
                                type: ignore
            on:
              failure:
                errors:
                  - all
                type: retry-step-group
                spec:
                  attempts: 2
                  interval: 10s
```

## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- 
  Specific builds
  - `trigger manager`
  - `trigger dms`
  - `trigger ng_manager`
  - `trigger cvng `
  - `trigger cmdlib`
  - `trigger template_svc`
  - `trigger events_fmwrk_monitor`
  - `trigger event_server`
  - `trigger change_data_capture`
  -  Trigger multiple builds together: For eg: `trigger dms, manager`
- Immutable delegate `trigger publish-delegate`
</details>

## [Latest PR Check Triggers](https://github.com/harness/harness-core/blob/develop/.github/pull_request_template.md)

<details>
  <summary>PR Check triggers</summary>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ut0, ut1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- Trigger CommonChecks: `trigger commonchecks`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger uts`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
- Validate_Reviews: `trigger review`
- Module Dependency Check: `trigger mdc`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/52564)

### CODE REVIEW

**Review by archit-harness — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52564)* status: 4 file(s) to review. 1 change requests. 0 of 2 approvals obtained. 

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/52564#-Ndiqo-3BJ1OrO7ZMEcJ):*
add we add which yaml we tested and video or shot for working of this feature?
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryStepGroupFailureSpecConfigV1.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/52564#-NdiqyAX-1NxW-t4TnjM:-NdiqyAX-1NxW-t4TnjN:bjsdr7v) ([raw file](https://github.com/harness/harness-core/blob/215eaf253ce56dc3f6d1fb8e1cb103e9bfb1e2ea/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryStepGroupFailureSpecConfigV1.java#L29)):*
> ```Java
> public class RetryStepGroupFailureSpecConfigV1 {
>   ParameterField<Integer> attempts;
>   @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) ParameterField<List<Timeout>> intervals;
> ```

isnt this interval and not intervals?

**Review by shalini-agr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52564)* status: 6 file(s) to review. 1 change requests. 2. unresolved discussions. 0 of 2 approvals obtained. 

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/harness/harness-core/52564#-Ndiqo-3BJ1OrO7ZMEcJ):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

add we add which yaml we tested and video or shot for working of this feature?
</blockquote></details>

Done.
___
*[`953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryStepGroupFailureSpecConfigV1.java` line 29 at r2](https://reviewable.io/reviews/harness/harness-core/52564#-NdiqyAX-1NxW-t4TnjM:-NdjXm4z53Zp3rfmusLa:b-dpxus8) ([raw file](https://github.com/harness/harness-core/blob/215eaf253ce56dc3f6d1fb8e1cb103e9bfb1e2ea/953-yaml-commons/src/main/java/io/harness/yaml/core/failurestrategy/retry/v1/RetryStepGroupFailureSpecConfigV1.java#L29)):*
<details><summary><i>Previously, archit-harness (Archit Singla) wrote…</i></summary><blockquote>

isnt this interval and not intervals?
</blockquote></details>

yes, changed to interval

**Comment by shalini-agr** [comment]
trigger uts

**Review by archit-harness — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/52564)* status: 6 file(s) to review. 1 of 2 approvals obtained.

**Review by utkarshchoubey-harness — APPROVED** [review]

**Comment by shalini-agr** [comment]
trigger review

**Pull request merged**
