### PR TITLE
feat: [SRM-14148]: Added SLI Calculation for request SLO

### PR DESCRIPTION
**Pull request by arpit-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>

- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>

You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`

- Compile: `trigger compile`
- CodeformatCheckstyle: `trigger checkstylecodeformat`
  - CodeFormat: `trigger codeformat`
  - Checkstyle: `trigger checkstyle`
- MessageMetadata: `trigger messagecheck`
- File-Permission-Check: `trigger checkpermission`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- PMD: `trigger pmd`
- Copyright Check: `trigger copyrightcheck`
- Feature Name Check: `trigger featurenamecheck`
- UnitTests-ALL: `trigger utAll`
- UnitTests-0: `trigger ut0`
- UnitTests-1: `trigger ut1`
- UnitTests-2: `trigger ut2`
- UnitTests-3: `trigger ut3`
- UnitTests-4: `trigger ut4`
- UnitTests-5: `trigger ut5`
- UnitTests-6: `trigger ut6`
- UnitTests-7: `trigger ut7`
- UnitTests-8: `trigger ut8`
- UnitTests-9: `trigger ut9`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
- CodeFormatCheckstyle: `trigger checkstylecodeformat`
- SonarScan: `trigger ss`
- GitLeaks: `trigger gitleaks`
- Trigger all Checks: `trigger smartchecks`
- Go Build: `trigger gobuild`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)

### CODE REVIEW

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: 12 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecord.java` line 89 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhnyiv765QtTCNNIcD:-NQhnyiv765QtTCNNIcE:bqr13xu) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecord.java#L89)):*
> ```Java
>     private SLIState sliState;
>     private Instant timeStamp;
>     private Long goodEventCount;
> ```

We should not add new field. running good count is agnostic to if it is talking about events or minutes
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataProcessorServiceImpl.java` line 54 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhpU7o0YNzS_JFnw9s:-NQhpU7o0YNzS_JFnw9t:b-2lbo7e) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataProcessorServiceImpl.java#L54)):*
> ```Java
>       Pair<Long, Long> countValues = Pair.of(0L, 0L);
>       if (sliProcessRequestMap.containsKey(i)) {
>         if (serviceLevelIndicatorDTO.getType() == SLIExecutionType.WINDOW) {
> ```

Let see if we can remove the if clause my moving it the calculation to enum

**Review by naveen-harness — COMMENTED** [review]
> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataProcessorServiceImpl.java` line 62 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhoiU45fL71Cp9VDbr:-NQhoiU45fL71Cp9VDbs:b-9x4p4u) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataProcessorServiceImpl.java#L62)):*
> ```Java
>           sliState = SLIState.GOOD;
>         } else {
>           throw new InvalidArgumentsException("ServiceLevelIndicator type does not exist");
> ```

nit: you should put ServiceLevelIndicator type as well in the exception.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: 7 file(s) to review. 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhviCO3WuEqY8bJA5t:-NQhviCO3WuEqY8bJA5u:bycv3lj) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java#L23)):*
> ```Java
>   private long runningBadCount;
>   private long runningGoodCount;
>   private Long goodEventCount;
> ```

Any particular reason we are adding event count here, since we already have running good count

**Review by Varsha-lalwani — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhviCO3WuEqY8bJA5t:-NQxOzW8EvlAOEvckQU-:b32v57) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java#L23)):*
<details><summary><i>Previously, deepak-harness (Deepak Chhikara) wrote…</i></summary><blockquote>

Any particular reason we are adding event count here, since we already have running good count
</blockquote></details>

+1

**Review by arpit-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: Some of the checks are too old. 1 change requests. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java` line 23 at r1](https://reviewable.io/reviews/harness/harness-core/45268#-NQhviCO3WuEqY8bJA5t:-NQxf4cH4yu9bg1MH0uS:b-edidul) ([raw file](https://github.com/harness/harness-core/blob/eaac22f7629186089658be4b50d19085535cdd0a/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLIAnalyseResponse.java#L23)):*
<details><summary><i>Previously, Varsha-lalwani (Varsha Lalwani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

these running counts are only used for onboarding apis, these are dropped while transforming them in SLIRecordParams. While creating the SLIRecords running counts are recalculated based on skip data points to get an accurate result.

**Review by deepak-harness — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: 1 change requests. 0 of 1 approvals obtained. 

___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java` line 202 at r4](https://reviewable.io/reviews/harness/harness-core/45268#-NR6xHVxEs8I_tqInVIS:-NR6xHVxEs8I_tqInVIT:bwe4wg2) ([raw file](https://github.com/harness/harness-core/blob/59decc07ecaa1f34b02aa63e2e09973894af5b28/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/ServiceLevelIndicatorServiceImpl.java#L202)):*
> ```Java
>     } else if (serviceLevelIndicatorDTO.getType() == SLIExecutionType.REQUEST) {
>       return SLIValue.builder()
>           .goodCount((int) sliAnalyseResponse.getRunningGoodCount())
> ```

don't type case. change SLIValue 



_Code quote:_
```Java
SLIValue
```
___
*[`srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataUnavailabilityInstancesHandlerServiceImpl.java` line 67 at r4](https://reviewable.io/reviews/harness/harness-core/45268#-NR719dp-U6zK1YRjqM6:-NR719dp-U6zK1YRjqM7:bz5xcd6) ([raw file](https://github.com/harness/harness-core/blob/59decc07ecaa1f34b02aa63e2e09973894af5b28/srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIDataUnavailabilityInstancesHandlerServiceImpl.java#L67)):*
> ```Java
>       if (failureInstants.contains(sliRecord.getTimeStamp())) {
>         sliRecord.setSliState(SLIRecord.SLIState.SKIP_DATA);
>         sliRecord.setBadEventCount(0l);
> ```

set it to 0 in case of SKIP DATA

**Review by Varsha-lalwani — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268#-:-NR7nsfG5LqjcQJApao6:bnfp4nl)* status: :shipit: complete! ✓

**Review by deepak-harness — APPROVED** [review]
> Reviewed 9 of 10 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/45268)* status: :shipit: complete! ✓

**Pull request merged**
