### PR TITLE
[fix]: [CDS-40872]: Removed templates from StageElementConfig

### PR DESCRIPTION
**Pull request by utkarshchoubey-harness**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/35723)

### CODE REVIEW

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/35723#-N7tLTOeB4oipM5HfKf_:-N7tLTOeB4oipM5HfKfa:b-x5luzl) ([raw file](https://github.com/harness/harness-core/blob/b4e2f730f5272a4bb46a5d3ef8c7b4d302af2b25/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java#L97)):*
> ```Java
>   @VariableExpression
>   StageInfoConfig stageType;
>   @VariableExpression(skipVariableExpression = true) TemplateLinkConfig template;
> ```

I think UI uses this in swagger. can you verify it once with the UI team if they use it in swagger then UI also need to make changes from their end?

**Review by utkarshchoubey-harness — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35723)* status: 1 file(s) to review. 1. unresolved discussions. 0 of 1 approvals obtained. 

___
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/35723#-N7tLTOeB4oipM5HfKf_:-N7tPO3z-QgcdbQooRLz:b-c5485y) ([raw file](https://github.com/harness/harness-core/blob/b4e2f730f5272a4bb46a5d3ef8c7b4d302af2b25/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java#L97)):*
<details><summary><i>Previously, brijeshdhakar (Brijesh Dhakar) wrote…</i></summary><blockquote>

I think UI uses this in swagger. can you verify it once with the UI team if they use it in swagger then UI also need to make changes from their end? 
</blockquote></details>

I've already raised the ticket for UI, it is already in progress , Will merge this PR only after UI changes are done

**Comment by brijeshdhakar** [comment]
*[`953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java` line 97 at r1](https://reviewable.io/reviews/harness/harness-core/35723#-N7tLTOeB4oipM5HfKf_:-N7tQwMtDqdA7umcC3BO:bx075z2) ([raw file](https://github.com/harness/harness-core/blob/b4e2f730f5272a4bb46a5d3ef8c7b4d302af2b25/953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java#L97)):*
<details><summary><i>Previously, utkarshchoubey-harness wrote…</i></summary><blockquote>

I've already raised the ticket for UI, it is already in progress , Will merge this PR only after UI changes are done
</blockquote></details>

Ok, So are they using TemplateStageNode now in place of StageElementConfig?
And can you update the PR description? Its a bit confusing, it says removing templates from TemplateStageNode but it removes them from StageElementConfig.

**Review by brijeshdhakar — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35723)* status: :shipit: complete! ✓

**Review by archit-harness — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/35723)* status: :shipit: complete! ✓

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/35723)

**Pull request closed without merging**
