### PR TITLE
feat: [DEL-4218]: delegate should not depend on manager for jreConfigs

### PR DESCRIPTION
**Pull request by arpit3107**
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.
- [ ] If hashcheck failed I followed [the checklist](https://harness.atlassian.net/wiki/spaces/DEL/pages/21016838831/PR+Codebasehash+Check+merge+checklist) and updated this PR description with my answers to make sure I'm not introducing any breaking changes.

## Comment Triggers
<details>
  <summary>Build triggers</summary>
  
- Feature build: `trigger feature-build`
- Immutable delegate `trigger publish-delegate`
</details>

<details>
  <summary>PR Check triggers</summary>
  
  You can run multiple PR check triggers by comma separating them in a single comment. e.g. `trigger ti0, ti1`
  
- Compile: `trigger compile`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

## [Contributor license agreement](https://github.com/harness/harness-core/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

- - -
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/7752dbb3099d2dba3b5d37f5931a5e4c/pull-request/37960)

**Review by mdmilic — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960#-:-NCz3Ln299d9fm6lm51q:bnfp4nl)* status: :shipit: complete! ✓

**Review by bharatgoelharness — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)* status: :shipit: complete! ✓

___
*[`260-delegate/container/scripts/delegate.sh` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1UutU3CJlipjhCljq:-ND1UutU3CJlipjhCljr:b-62wdqj) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/260-delegate/container/scripts/delegate.sh#L65)):*
> ```Shell
> 
> JRE_DIR=jdk-11.0.14+9-jre
> JVM_URL=$JVM_URL_BASE_PATH/jre/openjdk-11.0.14_9/OpenJDK11U-jre_x64_linux_hotspot_11.0.14_9.tar.gz
> ```

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
___
*[`260-delegate/container/scripts/start.sh` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VIFXEmBbH7kGVRbd:-ND1VIFXEmBbH7kGVRbe:b-62wdqj) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/260-delegate/container/scripts/start.sh#L62)):*
> ```Shell
> fi
> 
> JRE_TAR_FILE=OpenJDK11U-jre_x64_linux_hotspot_11.0.14_9.tar.gz
> ```

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VbQs8XN_9UclyBty:-ND1VbQs8XN_9UclyBtz:b-62wdqj) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L53)):*
> ```FreeMarker
> <#if useCdn == "true">
>   <#noparse>
>     JVM_URL=$DELEGATE_STORAGE_URL/public/shared/jre/openjdk-11.0.14_9/OpenJDK11U-jre_x64_${OS}_hotspot_11.0.14_9.tar.gz
> ```

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VbwQ9p6LUTlQ7jdg:-ND1VbwQ9p6LUTlQ7jdh:b-62wdqj) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L57)):*
> ```FreeMarker
> <#else>
>   <#noparse>
>     JVM_URL=$DELEGATE_STORAGE_URL/jre/openjdk-11.0.14_9/OpenJDK11U-jre_x64_${OS}_hotspot_11.0.14_9.tar.gz
> ```

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
___
*[`dockerization/delegate/scripts/start.sh` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VV3q80xgC9nP8Czm:-ND1VV3q80xgC9nP8Czn:b-62wdqj) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/dockerization/delegate/scripts/start.sh#L198)):*
> ```Shell
> echo "using JRE11 with watcher $WATCHER_VERSION"
> JRE_DIR="jdk-11.0.14+9-jre"
> JVM_URL=$JVM_URL_BASE_PATH/jre/openjdk-11.0.14_9/OpenJDK11U-jre_x64_linux_hotspot_11.0.14_9.tar.gz
> ```

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.

**Review by arpit3107 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)* status: 1 change requests. 5. unresolved discussions. 

___
*[`260-delegate/container/scripts/delegate.sh` line 65 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1UutU3CJlipjhCljq:-ND1h4lqEAixq0E5t7nU:broqydk) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/260-delegate/container/scripts/delegate.sh#L65)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
</blockquote></details>

this pr is only for amd machines. For arm we have https://harness.atlassian.net/browse/DEL-4551
___
*[`260-delegate/container/scripts/start.sh` line 62 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VIFXEmBbH7kGVRbd:-ND1hACt9MK8I7GzIrtF:begqack) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/260-delegate/container/scripts/start.sh#L62)):*
> this pr is only for amd machines. For arm we have https://harness.atlassian.net/browse/DEL-4551
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 53 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VbQs8XN_9UclyBty:-ND1hBuGBBg-wiCl1udZ:broqydk) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L53)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
</blockquote></details>

this pr is only for amd machines. For arm we have https://harness.atlassian.net/browse/DEL-4551
___
*[`400-rest/src/main/resources/delegatetemplates/common.sh.ftl` line 57 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VbwQ9p6LUTlQ7jdg:-ND1hCoU9aTodUncFWyM:broqydk) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/400-rest/src/main/resources/delegatetemplates/common.sh.ftl#L57)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
</blockquote></details>

this pr is only for amd machines. For arm we have https://harness.atlassian.net/browse/DEL-4551
___
*[`dockerization/delegate/scripts/start.sh` line 198 at r2](https://reviewable.io/reviews/harness/harness-core/37960#-ND1VV3q80xgC9nP8Czm:-ND1hE0UDPJDIhxoKRUX:broqydk) ([raw file](https://github.com/harness/harness-core/blob/9786a060229890038deddfe0454162da243b2786/dockerization/delegate/scripts/start.sh#L198)):*
<details><summary><i>Previously, bharatgoelharness (Bharat Goel) wrote…</i></summary><blockquote>

This will not work in case of arm arch shell delegate. We need to get the arch from env and generate the url.
</blockquote></details>

this pr is only for amd machines. For arm we have https://harness.atlassian.net/browse/DEL-4551

**Review by bharatgoelharness — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)* status: :shipit: complete! ✓

**Review by bharatgoelharness — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)* status: :shipit: complete! ✓

**Review by gaurav-jain1 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/37960)* status: :shipit: complete! ✓

**Pull request merged**
