### PR TITLE
feat: [SPG-15]: fix hazelcast vulnerability

### PR DESCRIPTION
**Pull request by shivagowda**
You can use the following comments to re-trigger PR Checks

- Compile: `trigger compile`
- runAeriformCheck: `trigger AeriformCheck`
- CodeFormat: `trigger codeformat`
- MessageMetadata: `trigger messagecheck`
- Recency: `trigger recency`
- BuildNumberMetadata: `trigger buildnum`
- runDockerizationCheck: `trigger dockerizationcheck`
- runAuthorCheck: `trigger authorcheck`
- Checkstyle: `trigger checkstyle`
- PMD: `trigger pmd`
- TI-bootstrap: `trigger ti0`
- TI-bootstrap1: `trigger ti1`
- TI-bootstrap2: `trigger ti2`
- TI-bootstrap3: `trigger ti3`
- TI-bootstrap4: `trigger ti4`
- FunctionalTest1: `trigger ft1`
- FunctionalTest2: `trigger ft2`
- CodeBaseHash: `trigger codebasehash`

---
This change is [Reviewable](https://reviewable.io/reviews/harness/harness-core/31387)

### CODE REVIEW

**Comment by shivagowda** [comment]
trigger ti2, ti4, ft1, compile, codeformat

**Comment by shivagowda** [comment]
trigger ti4, ti2, ft1, compile

**Comment by shivagowda** [comment]
trigger compile

**Comment by shivagowda** [comment]
trigger compile

**Review by kjoshi12345 — APPROVED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/harness-core/31387)* status: :shipit: complete! ✓

**Comment by shivagowda** [comment]
trigger recency

**Comment by shivagowda** [comment]
trigger pmd

**Pull request merged**
